### PR TITLE
[Doc-Improvement][Update app studio messages][ADO2417487]

### PR DESCRIPTION
**Pull request by v-habibaumme**
adding warning message

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a141ed63ba1eb48f66ea620eff0bfc77d0dd7238/msteams-platform%2Fget-started%2Fget-started-overview.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a159d7e-ac77-4c61-a88e-1e0f6596fb0d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1b0fccb86d7ebaec100b3bcc54203bfef98ffec/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/063a303b-8747-4c11-a0fc-35ee858f3f55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/app-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1b0fccb86d7ebaec100b3bcc54203bfef98ffec/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapp-studio-overview.md) | 83 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a649474-68d8-4ee8-9d57-e53c845bffef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/debug.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1b0fccb86d7ebaec100b3bcc54203bfef98ffec/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdebug.md) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/407bf395-7778-43e7-89fb-3da46ecd2e4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1b0fccb86d7ebaec100b3bcc54203bfef98ffec/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 99 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f53b309-f8af-4e84-9d9c-3393e5487911) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1b0fccb86d7ebaec100b3bcc54203bfef98ffec/msteams-platform%2Fget-started%2Fget-started-overview.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26a2c0a5-691f-42a0-842c-39732b7e31a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1b0fccb86d7ebaec100b3bcc54203bfef98ffec/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 87 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69bbc9ab-8fa5-486e-b301-844ddeb6496b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1b0fccb86d7ebaec100b3bcc54203bfef98ffec/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10c031c1-ac8b-42ce-8510-1ad0b1844078) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f1d411454bd88794437ca84311d9bcc8583179d/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb7b4060-0c2c-4a11-b905-adbe3e7569a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/app-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f1d411454bd88794437ca84311d9bcc8583179d/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapp-studio-overview.md) | 83 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45837f66-6926-4d99-b6a1-de57e498b4d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/debug.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f1d411454bd88794437ca84311d9bcc8583179d/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdebug.md) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e518417a-81b0-40bc-95a5-c8316aed5292) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f1d411454bd88794437ca84311d9bcc8583179d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 99 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8afb4acc-8e58-4b20-875f-4643b4534c3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f1d411454bd88794437ca84311d9bcc8583179d/msteams-platform%2Fget-started%2Fget-started-overview.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e644b24a-bab6-43c9-894c-d28185be6cac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f1d411454bd88794437ca84311d9bcc8583179d/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 87 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60dc030d-5cdd-4baf-b4a6-cff61acd31a7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f1d411454bd88794437ca84311d9bcc8583179d/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/debd4b24-4f42-4847-b938-eef35532f4dc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/343b7e5e24750ede4cf8d2e0de941d07720fa508/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/021b122d-e9e5-4613-a82f-a2e6efac86eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/app-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/343b7e5e24750ede4cf8d2e0de941d07720fa508/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapp-studio-overview.md) | 83 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7df39e6a-f078-4a63-8766-c0c5fd1a3275) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/debug.md](https://github.com/MicrosoftDocs/msteams-docs/blob/343b7e5e24750ede4cf8d2e0de941d07720fa508/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdebug.md) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6088817-0a9b-4fc0-a528-f2e4f68832bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/343b7e5e24750ede4cf8d2e0de941d07720fa508/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 99 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa9e327c-8707-48fd-b05f-4f1cfb97b47c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/343b7e5e24750ede4cf8d2e0de941d07720fa508/msteams-platform%2Fget-started%2Fget-started-overview.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b8d4a53-b21f-4412-b96a-9bba5995da5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/343b7e5e24750ede4cf8d2e0de941d07720fa508/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 87 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e45b671b-3db0-440f-9204-3fea05bfb8dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/343b7e5e24750ede4cf8d2e0de941d07720fa508/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/583e5e88-a1b8-4332-bb5d-5fb61faeaee2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by ashishguptaiitb** [comment]
@surbhigupta12 and @v-habibaumme , I don't believe this should be a warning. Is there a definition of 'warning' that we refer/adhere to?

**Pull request merged**
