### PR TITLE
[Doc Improvement][Update Teams AI SBS and Advantages]

### PR DESCRIPTION
**Pull request by v-ypalikila**
updated SBS guide

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-conversation-AI.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/301b163dcc575b5ad4431e249ae91ee78bb845e7/msteams-platform%2Fsbs-botbuilder-conversation-AI.yml) | 88 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54942b68-0130-46a8-95dd-09deb9a70156) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-conversation-AI.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d7eaa718763adb252e3db49cc8c8b5b8729f6868/msteams-platform%2Fsbs-botbuilder-conversation-AI.yml) | 87 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46348335-2974-466f-aeab-95b4693d608d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eadbe985f8120bd24bc1f8fc147879dd34441a11/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fteams-conversation-ai-overview.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7d9aa31-b315-409a-9a96-ac55c9086b3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-conversation-AI.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/eadbe985f8120bd24bc1f8fc147879dd34441a11/msteams-platform%2Fsbs-botbuilder-conversation-AI.yml) | 87 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/436ac7e6-a6ef-4817-8070-678d8c1ae180) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae5bbf7e44475592045209f69523e1f5001f092b/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fteams-conversation-ai-overview.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56ba2c32-baca-4449-a301-d24c6c3d20a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-conversation-AI.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ae5bbf7e44475592045209f69523e1f5001f092b/msteams-platform%2Fsbs-botbuilder-conversation-AI.yml) | 87 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/167719ee-5568-4da4-89f7-cd243bd5fe83) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87ac051eadf3a8d073726d91282342708d160d43/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fteams-conversation-ai-overview.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32330de2-f680-420c-907b-4ef9a47e0014) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-conversation-AI.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/87ac051eadf3a8d073726d91282342708d160d43/msteams-platform%2Fsbs-botbuilder-conversation-AI.yml) | 87 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d97a574-209b-4612-bc52-328d34af847b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7df038c3331c9c9f54aad961c5b270deb5f23b1e/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fteams-conversation-ai-overview.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/008992e3-052f-47ca-b2f7-979e3a724a92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-conversation-AI.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7df038c3331c9c9f54aad961c5b270deb5f23b1e/msteams-platform%2Fsbs-botbuilder-conversation-AI.yml) | 87 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6009d68-d0d4-416e-bf41-4b28cf12bbc9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d362d15e37fe542818ce2ad7c2e8cc01eef1e0d/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fteams-conversation-ai-overview.md) | 88 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9262b19-cb88-4cfc-8c27-5b4bd43b5ed2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-conversation-AI.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3d362d15e37fe542818ce2ad7c2e8cc01eef1e0d/msteams-platform%2Fsbs-botbuilder-conversation-AI.yml) | 87 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90df2461-90ce-47e3-b1a5-9fdf3c0b5cbe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/beefd090767239962695739819723305460cbc71/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fteams-conversation-ai-overview.md) | 88 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cd29253-8a2a-4d42-b58f-4301cfce4246) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-conversation-AI.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/beefd090767239962695739819723305460cbc71/msteams-platform%2Fsbs-botbuilder-conversation-AI.yml) | 87 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8a00bbf-1f60-4506-80b4-155b0275e802) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e236aea02eb9b5c2df6c8729c8e20c99ab116ffc/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fteams-conversation-ai-overview.md) | 88 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5b57d24-3120-42eb-bacc-432af84b6367) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-conversation-AI.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e236aea02eb9b5c2df6c8729c8e20c99ab116ffc/msteams-platform%2Fsbs-botbuilder-conversation-AI.yml) | 87 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cf30bb6-1ead-4380-b30b-0383455e1d16) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9e34add2e0e6843b1d385074c3e7ac4b256637/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fteams-conversation-ai-overview.md) | 88 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c21140e6-1155-48c1-8ee5-613b1630214e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-conversation-AI.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7e9e34add2e0e6843b1d385074c3e7ac4b256637/msteams-platform%2Fsbs-botbuilder-conversation-AI.yml) | 87 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6661fd6c-99e2-4686-87b0-ffbd431adb00) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by singhk97 — DISMISSED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/465c3115f598518ea87814054b9f01fb9187f1d3/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fteams-conversation-ai-overview.md) | 88 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29ea5ecc-2c57-4774-876c-ae2c3590bf5a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-conversation-AI.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/465c3115f598518ea87814054b9f01fb9187f1d3/msteams-platform%2Fsbs-botbuilder-conversation-AI.yml) | 87 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ec9dfa6-6a91-4425-abfc-65ce63ed5717) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e17ac491f059c0756b493719b05daa37bb7181df/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fteams-conversation-ai-overview.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03aa3471-ca83-4ceb-8a57-5bb16672bbfa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-conversation-AI.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e17ac491f059c0756b493719b05daa37bb7181df/msteams-platform%2Fsbs-botbuilder-conversation-AI.yml) | 87 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3e8d902-7632-4358-a9af-1cec14acd6ab) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
