### PR TITLE
[MetaOS updates for Extend your apps across Microsoft 365]

### PR DESCRIPTION
**Pull request by v-habibaumme**
update metadata

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f49488e1c16922685ecffac84776ca366ee0e3e/msteams-platform%2Fm365-apps%2Foverview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c154462-c3f1-49fe-b740-dd5e3a51a897) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3ee4f155aadc419e73a4a08ab369949ac7f2d14/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 96 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e39e6610-dc84-4a28-8de3-99f058d68e82) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3ee4f155aadc419e73a4a08ab369949ac7f2d14/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 94 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec82ce19-ebfa-48e7-9a5f-5c11061238e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3ee4f155aadc419e73a4a08ab369949ac7f2d14/msteams-platform%2Fm365-apps%2Foverview.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65062d19-c446-4b03-8cf1-5e6acbddf6bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3ee4f155aadc419e73a4a08ab369949ac7f2d14/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a54e364-3088-426a-aa4a-cce7ddea0520) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3ee4f155aadc419e73a4a08ab369949ac7f2d14/msteams-platform%2Fm365-apps%2Fpublish.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/083c8ad8-8a8c-4e39-a3ec-1a5eb6ce53f6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/acffea53453eb3ce9bf46e589b2d4c6173ac0db1/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 96 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14b5e27c-f37b-4dc2-9f66-9db10984854b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/acffea53453eb3ce9bf46e589b2d4c6173ac0db1/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 94 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7448fcd5-e013-4c55-b9d8-59d228c99c20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/acffea53453eb3ce9bf46e589b2d4c6173ac0db1/msteams-platform%2Fm365-apps%2Foverview.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e843ba27-0311-414b-a947-e5ccdf046782) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/acffea53453eb3ce9bf46e589b2d4c6173ac0db1/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f10f8300-9037-4a49-ae7d-b8413b2d2b47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/acffea53453eb3ce9bf46e589b2d4c6173ac0db1/msteams-platform%2Fm365-apps%2Fpublish.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a41c3b0-e931-4862-a532-2f91cdbaaa60) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4f8db1815d4c89778f87636bac33e1f3901c792/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 96 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7aeb4e3e-fcd2-4de2-adcb-fa2f6d657e4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4f8db1815d4c89778f87636bac33e1f3901c792/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 94 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2eb0f09-4022-4fab-9571-7ce94cb99535) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4f8db1815d4c89778f87636bac33e1f3901c792/msteams-platform%2Fm365-apps%2Foverview.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/695575bb-0957-4ed8-8727-31d3a8e04c84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4f8db1815d4c89778f87636bac33e1f3901c792/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bf1f048-8920-4cae-9715-fb9e67415595) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4f8db1815d4c89778f87636bac33e1f3901c792/msteams-platform%2Fm365-apps%2Fpublish.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71d5816e-cc2b-4d15-b43c-a63ab618ed7f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/70104e3059f8a56528cc2b2a531e7ad10e317f3b/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 96 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2c69383-3979-4a0f-a67c-832efcec029a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/70104e3059f8a56528cc2b2a531e7ad10e317f3b/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 94 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35277a17-00bc-46f3-9174-01444d893396) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/70104e3059f8a56528cc2b2a531e7ad10e317f3b/msteams-platform%2Fm365-apps%2Foverview.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa5fcba1-2448-4564-9bce-6a4dd656ddcb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/70104e3059f8a56528cc2b2a531e7ad10e317f3b/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef7e990d-0bf1-4fc0-97ba-543411552334) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/70104e3059f8a56528cc2b2a531e7ad10e317f3b/msteams-platform%2Fm365-apps%2Fpublish.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bcb30760-4f76-4591-b018-e28393a5d5c8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5563af3f8d8254d79326c8c2f832b287ca6a0bec/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 96 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/197eb3e4-6808-4400-b440-0dfbb29d361e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5563af3f8d8254d79326c8c2f832b287ca6a0bec/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 94 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acb653a0-1909-4257-89d3-e4e4b930758a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5563af3f8d8254d79326c8c2f832b287ca6a0bec/msteams-platform%2Fm365-apps%2Foverview.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05cf707b-2138-4538-9625-9cff72c5886e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5563af3f8d8254d79326c8c2f832b287ca6a0bec/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a0ef4b1-903c-4b23-a4a5-5f7246e49297) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5563af3f8d8254d79326c8c2f832b287ca6a0bec/msteams-platform%2Fm365-apps%2Fpublish.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9939296e-d192-4b76-8b2a-1ea338244b86) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
