### PR TITLE
[Doc Improvement][Hyperlink updates][3830174]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-meeting-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/083357cdff29798efb5f279f74333a4d5e35c7a2/msteams-platform%2Fm365-apps%2Fextend-m365-meeting-app.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc8f2aab-4a4c-4cc2-9046-138cb46b1eed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-core-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/856e16f7603bd2499041250fb78b17c0bc853096/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-core-capabilities.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e684c8f1-53bc-4678-9f76-097c42767641) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-meeting-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/856e16f7603bd2499041250fb78b17c0bc853096/msteams-platform%2Fm365-apps%2Fextend-m365-meeting-app.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fed8214a-96b1-48ba-b08b-45dc7b83c168) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/856e16f7603bd2499041250fb78b17c0bc853096/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 75 | 79 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab94996b-2177-4f65-8ceb-874246f6da90) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-core-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1bf3a881a67eeaf843e77fa8fe4615c4e6f73d12/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-core-capabilities.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c8e511a-f8ef-4fa3-affd-c387bc7e01ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-get-started.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1bf3a881a67eeaf843e77fa8fe4615c4e6f73d12/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-get-started.md) | 90 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e79d78ea-eb48-47a5-a514-1c12e18fe784) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-meeting-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1bf3a881a67eeaf843e77fa8fe4615c4e6f73d12/msteams-platform%2Fm365-apps%2Fextend-m365-meeting-app.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24c865c0-a70c-4dbe-bab6-e673c3dda6ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1bf3a881a67eeaf843e77fa8fe4615c4e6f73d12/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 75 | 79 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2c051ae-dc8d-4b09-9197-840d420cc555) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-core-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a39434b7eaacb116537981ba9a7160b572567e1/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-core-capabilities.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a43d404-d801-4c97-b447-4f1024346669) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-get-started.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a39434b7eaacb116537981ba9a7160b572567e1/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-get-started.md) | 90 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/904e24f4-0dab-4a72-b938-0984f7aba445) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-meeting-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a39434b7eaacb116537981ba9a7160b572567e1/msteams-platform%2Fm365-apps%2Fextend-m365-meeting-app.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8ba7b07-1af0-4fae-82a0-75afc8bfb269) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
