### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by a-b-r-o-w-n**

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[3efa0d6](https://github.com/a-b-r-o-w-n/msteams-docs/pull/395/commits/3efa0d663828fd872d53c4f387e6505d6e2f9735)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[3efa0d6](https://github.com/a-b-r-o-w-n/msteams-docs/pull/395/commits/3efa0d663828fd872d53c4f387e6505d6e2f9735)_: 

:clock10: **Incremental building**: average incremental building time is _21 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[3efa0d6](https://github.com/a-b-r-o-w-n/msteams-docs/pull/395/commits/3efa0d663828fd872d53c4f387e6505d6e2f9735)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/bots/bot-conversations/bots-conversations.md](https://github.com/a-b-r-o-w-n/msteams-docs/blob/patch-1/msteams-platform/concepts/bots/bot-conversations/bots-conversations.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fconcepts%2Fbots%2Fbot-conversations%2Fbots-conversations.md)

<a name="msteams-platform%2Fconcepts%2Fbots%2Fbot-conversations%2Fbots-conversations.md"></a>
### [msteams-platform/concepts/bots/bot-conversations/bots-conversations.md](https://github.com/a-b-r-o-w-n/msteams-docs/blob/patch-1/msteams-platform/concepts/bots/bot-conversations/bots-conversations.md)
 - **Line 13**: **[Warning]** Invalid file link:(~/resources/dev-preview/developer-preview-features#adding-tabs-and-bots-to-chats).
 - **Line 17**: **[Warning]** Invalid file link:(~/concepts/bots/bot-conversations/bots-conv-channel).
 - **Line 18**: **[Warning]** Invalid file link:(~/concepts/bots/bot-conversations/bots-conv-personal).
 - **Line 20**: **[Warning]** Invalid file link:(~/resources/schema/manifest-schema).
 - **Line 34**: **[Warning]** Invalid file link:(~/concepts/bots/bots-notifications).
 - **Line 48**: **[Warning]** Invalid file link:(~/concepts/cards/cards-reference).
 - **Line 56**: **[Warning]** Invalid file link:(~/concepts/bots/bot-conversations/bots-message-format).
 - **Line 59**: **[Warning]** Invalid file link:(~/concepts/bots/bots-text-formats).
 - **Line 61**: **[Warning]** Invalid file link:(~/concepts/cards/cards-format).
 - **Line 81**: **[Warning]** Invalid file link:(~/concepts/bots/bots-notifications#channel-updates).
 - **Line 142**: **[Warning]** Invalid file link:(~/concepts/bots/bot-conversations/bots-conv-channel#mentions).
 - **Line 152**: **[Warning]** Invalid file link:(~/concepts/bots/bots-notifications#channel-updates).
 - **Line 156**: **[Warning]** Invalid file link:(~/concepts/bots/bots-notifications#team-name-updates).
 - **Line 159**: **[Warning]** Invalid file link:(~/concepts/bots/bots-notifications#channel-updates).
 - **Line 196**: **[Warning]** Invalid file link:(~/concepts/cards-actions).
 - **Line 267**: **[Warning]** Invalid file link:(~/concepts/bots/bot-conversations/bots-conv-proactive#starting-personal-conversations).
 - **Line 268**: **[Warning]** Invalid file link:(~/concepts/bots/bot-conversations/bots-conv-proactive#creating-a-channel-conversation).
 - **Line 270**: **[Warning]** Invalid file link:(~/concepts/bots/bot-conversations/bots-conv-proactive).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201901031948119878-395%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aG6tDNI4kjR6Lx57ZKenYweGJvt342CX0pSXcOGFtds%3D&st=2019-01-03T19%3A44%3A21Z&se=2019-02-03T19%3A49%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by a-b-r-o-w-n** [comment]
Just noticed that #393 fixes the same typo!

**Pull request closed without merging**
