### PR TITLE
[Doc Enhancement][Tools and SDKs][ADO No]

### PR DESCRIPTION
**Pull request by v-dreddipogu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/accounts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8645ccce4c520e33931bf01e9c2c8cc1eed3bacf/msteams-platform%2Ftoolkit%2Faccounts.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/423e8cc6-0de5-4e96-8534-26ffcafe818b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/accounts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f5a10a110955d6b7001870f7ed711581bd5cbe3/msteams-platform%2Ftoolkit%2Faccounts.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b03d961-627d-419a-a96d-3f03a477253e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f5a10a110955d6b7001870f7ed711581bd5cbe3/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 85 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/979827dd-923c-4948-99ce-5171796121d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f5a10a110955d6b7001870f7ed711581bd5cbe3/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/880c902d-6d05-489b-9352-62d68ab7a583) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/accounts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc991358c5c543263816df047586b4306e89c5a9/msteams-platform%2Ftoolkit%2Faccounts.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38e097c8-bd3e-4fea-995e-0d2fdda4700a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc991358c5c543263816df047586b4306e89c5a9/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 85 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55f75d15-f3c4-4d73-a60f-76d5e27c8ae7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc991358c5c543263816df047586b4306e89c5a9/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f85b3e82-f153-4466-b3ef-f4a759522680) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/accounts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c76bbfc8abc25f3b769bdb6df0fee2cb03540961/msteams-platform%2Ftoolkit%2Faccounts.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01479c99-72b0-418c-9875-46bfc832aeea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c76bbfc8abc25f3b769bdb6df0fee2cb03540961/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 85 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/775bc1a4-4e23-4575-9e73-689a119aa786) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c76bbfc8abc25f3b769bdb6df0fee2cb03540961/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5eafa24e-ec2e-4abd-a8f3-f30bb37f3ee0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c76bbfc8abc25f3b769bdb6df0fee2cb03540961/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ae73ae2-7784-46fc-aab3-5da101a108c2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/accounts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a65046a28c13e08c2f038cae55f20508a0e42ed3/msteams-platform%2Ftoolkit%2Faccounts.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d994cb3a-2ddf-498d-b7d1-45c235bf596b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a65046a28c13e08c2f038cae55f20508a0e42ed3/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 85 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/deba6f77-1be9-4991-b50b-b3f59ad43ef7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a65046a28c13e08c2f038cae55f20508a0e42ed3/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/855e4773-73fd-4f49-b4e8-7aebfc7226c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a65046a28c13e08c2f038cae55f20508a0e42ed3/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de0bb295-bb34-4b7f-810e-64a670d71f62) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/accounts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca06b18a197a1a7892f3f91ccfaeb2a24dd2c179/msteams-platform%2Ftoolkit%2Faccounts.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4238f205-a2fc-409a-b2cf-a8fca0f5a00f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca06b18a197a1a7892f3f91ccfaeb2a24dd2c179/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d4a83c3-34ae-49fc-8371-f7e99c6cf4c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca06b18a197a1a7892f3f91ccfaeb2a24dd2c179/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f61465d5-a6c8-43c9-af6d-d9ce76b504e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca06b18a197a1a7892f3f91ccfaeb2a24dd2c179/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d4a912c-265a-4795-966a-1cd7662e9573) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/accounts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a9bc8ae45e4389ba4fbf66d03f392480a92d2af/msteams-platform%2Ftoolkit%2Faccounts.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b036f18c-3549-4db1-aa4c-265544a35173) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a9bc8ae45e4389ba4fbf66d03f392480a92d2af/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 88 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cafe8c1b-7cd9-4b42-92a1-20e540a79346) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a9bc8ae45e4389ba4fbf66d03f392480a92d2af/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d069ec3-dfbf-4e78-9a7f-3213f18b22c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a9bc8ae45e4389ba4fbf66d03f392480a92d2af/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4e97ca6-5aa8-41aa-9192-2afac2d91ca0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/accounts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/333ac84be81d5fd2f64c552d551d3c0c7ad515f5/msteams-platform%2Ftoolkit%2Faccounts.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d654ba23-798d-465a-b473-9d29b78986c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/333ac84be81d5fd2f64c552d551d3c0c7ad515f5/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be84a81b-752d-42f0-abe0-f3d4bb0905b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/333ac84be81d5fd2f64c552d551d3c0c7ad515f5/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a2a78aa-6c8b-4509-97bd-57266ce5c06e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/333ac84be81d5fd2f64c552d551d3c0c7ad515f5/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1db6157e-7a1e-4d23-933b-8f0e169b95a9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/accounts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bb98914a4248c237082fcdf76a9065a2565568b/msteams-platform%2Ftoolkit%2Faccounts.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6165aec6-f599-4286-8890-30e100f50b1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bb98914a4248c237082fcdf76a9065a2565568b/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c5d9e15-0b32-495d-a9c8-23097295ffcf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bb98914a4248c237082fcdf76a9065a2565568b/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ccfaf1c-5ee2-4ec9-907d-abc0ad1ba4cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bb98914a4248c237082fcdf76a9065a2565568b/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e489e5bf-db9b-407d-b1fb-5053b3ea9f34) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/accounts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b428999f8962141acae393c32aa624b291d074ae/msteams-platform%2Ftoolkit%2Faccounts.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a41b64b1-beef-441c-a3eb-3825715d1bf4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b428999f8962141acae393c32aa624b291d074ae/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 88 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc68f71e-3dd7-42dc-8da9-3428a5b6a03f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b428999f8962141acae393c32aa624b291d074ae/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7400a45c-0583-4144-ab57-973e88434926) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b428999f8962141acae393c32aa624b291d074ae/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31dd2f07-ead2-40ce-a55d-753c062be92b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
