### PR TITLE
[Doc improvement][Address Markdown warnings Ph-1][2227327]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c79301f3df1a3561c0c2c60aaef135a64b7862a/msteams-platform/concepts/build-and-test/deep-links.md) | 84 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d2f1685-5ee0-4b7f-9f6f-7dec45f8118f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c79301f3df1a3561c0c2c60aaef135a64b7862a/msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md) | 93 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/572ec40c-0377-4edb-8fbe-5b4d01ac1081) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c79301f3df1a3561c0c2c60aaef135a64b7862a/msteams-platform/concepts/deploy-and-publish/appsource/publish.md) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a76b5775-e2ce-4e9b-9e33-b830af60488e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c79301f3df1a3561c0c2c60aaef135a64b7862a/msteams-platform/get-started/get-started-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01b7e317-a08c-4db3-b396-2d91e4bdbee1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c79301f3df1a3561c0c2c60aaef135a64b7862a/msteams-platform/resources/schema/manifest-schema.md) | 91 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdba1682-e55d-435e-a327-53ffcf084549) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c79301f3df1a3561c0c2c60aaef135a64b7862a/msteams-platform/samples/app-templates.md) | 87 | 103 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dc903b1-1a40-4446-b2d5-3fa0c3b80c05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c79301f3df1a3561c0c2c60aaef135a64b7862a/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/491c90a6-037f-4868-a2ec-c5ed6ccc2243) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c79301f3df1a3561c0c2c60aaef135a64b7862a/msteams-platform/task-modules-and-cards/cards/cards-format.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b940f23-dfa7-43b7-9396-ff4803b7c725) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c79301f3df1a3561c0c2c60aaef135a64b7862a/msteams-platform/task-modules-and-cards/cards/cards-reference.md) | 87 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4293507d-0fec-4048-ae07-08c3d8c90edc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c79301f3df1a3561c0c2c60aaef135a64b7862a/msteams-platform/task-modules-and-cards/what-are-cards.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be1227a6-375b-4439-bf63-99ebe02cbb6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c79301f3df1a3561c0c2c60aaef135a64b7862a/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6252ffd-2aac-4bfa-bb23-8cd075b61b80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c79301f3df1a3561c0c2c60aaef135a64b7862a/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc4c1ec9-8646-449d-af58-20da3a39111e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c79301f3df1a3561c0c2c60aaef135a64b7862a/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04d32f47-c8b3-47fc-8474-6b86e5780203) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8769c7c1ff1a6861ee7995162ca2a8cc8e3fe155/msteams-platform/concepts/build-and-test/deep-links.md) | 84 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/084e762c-8e16-4127-b953-7d83d84d8dc6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8769c7c1ff1a6861ee7995162ca2a8cc8e3fe155/msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md) | 93 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dcba6b8-68a7-402c-9e24-97fc14bd27fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8769c7c1ff1a6861ee7995162ca2a8cc8e3fe155/msteams-platform/concepts/deploy-and-publish/appsource/publish.md) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5b11fc7-d79d-48df-bc82-857039160ba1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8769c7c1ff1a6861ee7995162ca2a8cc8e3fe155/msteams-platform/get-started/get-started-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81025506-ab79-4e87-b1bf-00e46d2da808) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8769c7c1ff1a6861ee7995162ca2a8cc8e3fe155/msteams-platform/resources/schema/manifest-schema.md) | 91 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67ec0be7-7984-4e80-9b8a-04c767e76784) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8769c7c1ff1a6861ee7995162ca2a8cc8e3fe155/msteams-platform/samples/app-templates.md) | 87 | 103 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8d2c089-d1a9-49bb-a7d6-e0316affc769) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8769c7c1ff1a6861ee7995162ca2a8cc8e3fe155/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/119c5144-478f-4db6-bc4e-4a56e9a656e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8769c7c1ff1a6861ee7995162ca2a8cc8e3fe155/msteams-platform/task-modules-and-cards/cards/cards-format.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7665e13-35ca-4a5b-9f29-bda033fc3264) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8769c7c1ff1a6861ee7995162ca2a8cc8e3fe155/msteams-platform/task-modules-and-cards/cards/cards-reference.md) | 87 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58f86793-8a76-4b6d-bc3c-659b860746ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8769c7c1ff1a6861ee7995162ca2a8cc8e3fe155/msteams-platform/task-modules-and-cards/what-are-cards.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7fa45db-44c2-4b49-a374-449e95d08454) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8769c7c1ff1a6861ee7995162ca2a8cc8e3fe155/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12c847a0-c4b8-43de-8309-d8c9312a1e05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8769c7c1ff1a6861ee7995162ca2a8cc8e3fe155/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8621df15-aae5-4c56-a3ce-a5f8e97d2e11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8769c7c1ff1a6861ee7995162ca2a8cc8e3fe155/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5062a974-74bb-4b69-a96c-6dd377585e2c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65f72ebb167023538715b8df6d14f9ee215aa929/msteams-platform/concepts/build-and-test/deep-links.md) | 84 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b87455c-b245-46e9-b30b-5a20088161b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65f72ebb167023538715b8df6d14f9ee215aa929/msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md) | 93 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ee9d817-4bdc-4694-8c88-3a9c5f467170) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65f72ebb167023538715b8df6d14f9ee215aa929/msteams-platform/concepts/deploy-and-publish/appsource/publish.md) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b47b0a4-68b0-46d7-b60b-56344f21a1c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65f72ebb167023538715b8df6d14f9ee215aa929/msteams-platform/get-started/get-started-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92f576fa-4020-4cc1-9b49-a519cbaba60e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65f72ebb167023538715b8df6d14f9ee215aa929/msteams-platform/resources/schema/manifest-schema.md) | 91 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9620ec8f-3cee-4909-943c-a87cdd6ad901) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65f72ebb167023538715b8df6d14f9ee215aa929/msteams-platform/samples/app-templates.md) | 87 | 103 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/028f4157-7867-4098-9c9b-67c8a485fec1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65f72ebb167023538715b8df6d14f9ee215aa929/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39981c47-ea68-41eb-a001-68b350dc3954) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65f72ebb167023538715b8df6d14f9ee215aa929/msteams-platform/task-modules-and-cards/cards/cards-format.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/678a526d-7f7e-44b0-b35d-b01bebf183d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65f72ebb167023538715b8df6d14f9ee215aa929/msteams-platform/task-modules-and-cards/cards/cards-reference.md) | 87 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24493a21-4f17-4888-afec-ca751eda3f63) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65f72ebb167023538715b8df6d14f9ee215aa929/msteams-platform/task-modules-and-cards/what-are-cards.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96d766f7-57c0-44f8-a443-90773cbdbedf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65f72ebb167023538715b8df6d14f9ee215aa929/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b6def74-8d0b-40f8-a250-e14acb35c3c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65f72ebb167023538715b8df6d14f9ee215aa929/msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83cc1b2d-b48f-4a19-8b52-6d4f6ff84d63) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65f72ebb167023538715b8df6d14f9ee215aa929/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1040dc73-0b14-466f-8a49-a60266c755b0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
