### PR TITLE
[Doc improvement] [Plan your app GCC]

### PR DESCRIPTION
**Pull request by v-ypalikila**
removed collapsible heading for GCC content

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28c696406f2b70d4afd0d6c87d22903c98851338/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d4432e4-ce73-4c46-9247-430b53e5f288) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54ddf418fb3223071b0ad81181d4915e3630ec33/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bcc5e0f-ef7a-479d-b038-36ae78f4cbc8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54ddf418fb3223071b0ad81181d4915e3630ec33/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aee28d97-75d4-4e98-9809-e4a57cb992f9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/767938405fff23e365f294a1732174b8bce0ad94/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e6fc380-275c-4067-9050-1f9ade4889a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/767938405fff23e365f294a1732174b8bce0ad94/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33a286ae-a526-4fbe-8796-db8db4ef25fb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
