### PR TITLE
[Doc Improvement][Broken link updates build tabs and design your app][2720391]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4dbe05439016d21af139ff0d635c3a04e40096f/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f126d2c6-4e81-45f9-9915-f29ebdb67e82) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6221817e9a4c7a64c5f69a2b9e2ad7586b2dc99/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b54e27de-d494-4ce9-bd88-a759e6756205) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6221817e9a4c7a64c5f69a2b9e2ad7586b2dc99/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/318fc972-a550-4d1c-9496-25ebb559cab1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2226df33a514880dc7768f53b96d4a5e149a80fd/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a0f2762-26bc-47a8-aca0-b507bbebd8df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2226df33a514880dc7768f53b96d4a5e149a80fd/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03e0f6fc-fea0-46d7-9432-b218c827d0ea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6603b65a0cdbd62e9a9a893230becddf39f77056/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b279240b-93ce-4c74-8488-0cb93f608957) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6603b65a0cdbd62e9a9a893230becddf39f77056/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/769a8bc4-b560-4516-843e-2804daf084e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6603b65a0cdbd62e9a9a893230becddf39f77056/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e608a7f-0e98-4daf-b8a1-f43497829cc7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6603b65a0cdbd62e9a9a893230becddf39f77056/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b73167f-45c1-4e67-9a94-2bd89abe4a36) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9602241714b15061c03bf2b4528aac62c3f744d7/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1af3b109-4082-44e2-a2b2-b7a5264f7ce9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9602241714b15061c03bf2b4528aac62c3f744d7/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32596e9b-8696-4072-94b1-ee7c72ecf043) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9602241714b15061c03bf2b4528aac62c3f744d7/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50cda3fa-ff43-4061-8cac-b569bac4de7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9602241714b15061c03bf2b4528aac62c3f744d7/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d834948c-ebd1-48cd-a399-4f96be7cedee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9602241714b15061c03bf2b4528aac62c3f744d7/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26abd740-6e00-4776-9f85-21665e4961fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-fluid-msteam.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9602241714b15061c03bf2b4528aac62c3f744d7/msteams-platform%2Ftabs%2Fhow-to%2Fusing-fluid-msteam.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1458809-a87f-4e31-818d-53a80e4f2ed2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9602241714b15061c03bf2b4528aac62c3f744d7/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d55a8207-7213-4bb9-8984-d1f8ba4a72eb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7be9f4b1c6000e7060dd1d30b412826d75bb88df/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b193434-f547-450e-8c8b-214e7c160a30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7be9f4b1c6000e7060dd1d30b412826d75bb88df/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6d798ad-0814-4658-9425-12b640ccd101) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7be9f4b1c6000e7060dd1d30b412826d75bb88df/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85308b78-6ea0-435a-a4ec-11d16f71f042) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7be9f4b1c6000e7060dd1d30b412826d75bb88df/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dabc9fd6-9eab-459b-8143-c06db6c55243) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7be9f4b1c6000e7060dd1d30b412826d75bb88df/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d10dc986-f4ef-4f6f-b541-40e11ac43ff6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-fluid-msteam.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7be9f4b1c6000e7060dd1d30b412826d75bb88df/msteams-platform%2Ftabs%2Fhow-to%2Fusing-fluid-msteam.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd043ae2-e111-40ea-a774-1aac288fc996) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7be9f4b1c6000e7060dd1d30b412826d75bb88df/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c63b36bb-00d0-41e8-a1e0-4c38089e7853) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c0363cdffeaf26f231b4edd34a530c52f34b5df/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8087caf0-6fd3-4d83-92c1-eca087f5f396) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c0363cdffeaf26f231b4edd34a530c52f34b5df/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8092344-817b-416e-9dad-2deaa164633f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c0363cdffeaf26f231b4edd34a530c52f34b5df/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d74bf00-add2-45bd-a302-056bbdb8b2b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c0363cdffeaf26f231b4edd34a530c52f34b5df/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80893f7d-5bbb-425d-a9f5-158bda23064a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c0363cdffeaf26f231b4edd34a530c52f34b5df/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0ba3750-cbc6-43f5-94b8-16f82f0237b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-fluid-msteam.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c0363cdffeaf26f231b4edd34a530c52f34b5df/msteams-platform%2Ftabs%2Fhow-to%2Fusing-fluid-msteam.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2596ee6-ddcf-4279-a09a-47bfd8475dbb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c0363cdffeaf26f231b4edd34a530c52f34b5df/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19e38c3b-8be2-44b2-8a80-761605ee29d9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de12be6a9a4fbed334446c65d4f5ade020bcd31c/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c729f254-5012-4b9b-a664-f834a2e5e7e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de12be6a9a4fbed334446c65d4f5ade020bcd31c/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/151485ef-b64e-40de-837e-3548fafbab5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de12be6a9a4fbed334446c65d4f5ade020bcd31c/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/989f564c-083d-4d58-942c-72e32cc5af55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de12be6a9a4fbed334446c65d4f5ade020bcd31c/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9e125cd-15af-4c0e-892d-0b9daef2d45e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de12be6a9a4fbed334446c65d4f5ade020bcd31c/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48eac425-72d2-44b5-b5d5-21a3359e4a11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de12be6a9a4fbed334446c65d4f5ade020bcd31c/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/606665e0-7508-4cd8-8a75-4bf85c3a3e2f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2925b2c2f4fea9543e1d15830920ac015bb3514c/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63ba60bb-c810-4407-837d-34499de67c80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2925b2c2f4fea9543e1d15830920ac015bb3514c/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/362b44f4-0802-43c2-911b-8303f0dee893) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2925b2c2f4fea9543e1d15830920ac015bb3514c/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d14290d-3d49-4370-9cc6-225362e9c216) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2925b2c2f4fea9543e1d15830920ac015bb3514c/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7f19968-1877-40f3-9393-fa52c7daab04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2925b2c2f4fea9543e1d15830920ac015bb3514c/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d7aec31-518e-4593-8624-94775b7619c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2925b2c2f4fea9543e1d15830920ac015bb3514c/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d677a3d-e320-468a-a2ad-de789f932b17) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
