### PR TITLE
Update app-templates.md

### PR DESCRIPTION
**Pull request by jhwang-ms**
Moved FAQ Plus, Icebreaker and Tournament of Teams into the App Template Code Samples section.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/22ce9af506197a8044b25ce22c1b9aa69a37a6d8/msteams-platform%2Fsamples%2Fapp-templates.md) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a575888-4d4c-4abc-992f-99bcf0a6a025) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by jhwang-ms** [comment]
@CarolynRowe could you review and merge this?

**Comment by CarolynRowe** [comment]
Hi @jhwang-ms:  I'm sorry, but I don't have permissions to this repository.

**Comment by jhwang-ms** [comment]
@CarolynRowe can you see who has perms?

**Comment by CarolynRowe** [comment]
No.  I would submit a question on the ask the admins channel.

**Comment by jhwang-ms** [comment]
Hi @surbhigupta12 - would you be able to review and merge this PR?

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4bc4fa66e1c7ecfc9064b801822456ca3ce17c5/msteams-platform%2Fsamples%2Fapp-templates.md) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4a73088-15fe-4b8d-a084-2ea2948f23aa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
