### PR TITLE
[Bulk] MS-1-6-msteams-links-fixes

### PR DESCRIPTION
**Pull request by Roudabeh1348**
This PR fixes 6 broken links in msteams-docs pr.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0689649227724f323645045e234a89f5e9785fe2/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c02ef41-5861-4c1d-b6cb-73cec5a56bf6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0689649227724f323645045e234a89f5e9785fe2/msteams-platform%2Fresources%2Ftroubleshoot.md) | 75 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae4a6fdd-6586-4a77-abb8-448b34f680c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0689649227724f323645045e234a89f5e9785fe2/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b35274a-91e3-4160-a689-8e68b0c33431) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0689649227724f323645045e234a89f5e9785fe2/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4149b9b4-6bd5-42a2-b3e1-4a0c7b6cddfd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0689649227724f323645045e234a89f5e9785fe2/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9883752-0fdd-4cf4-bd95-394c7897d116) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e3909dc9b8a4fe93dcd6729799545503c2f2976/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbdfcd4a-4f94-41b8-9bf4-35aeb9d325d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e3909dc9b8a4fe93dcd6729799545503c2f2976/msteams-platform%2Fresources%2Ftroubleshoot.md) | 75 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d54a29de-1602-46a1-9bdb-e14ac72beed3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e3909dc9b8a4fe93dcd6729799545503c2f2976/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8f3d896-756f-4891-b6a5-7e30a46e4d1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e3909dc9b8a4fe93dcd6729799545503c2f2976/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6caba63c-5b5f-4226-9ef2-863fd57aeb0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e3909dc9b8a4fe93dcd6729799545503c2f2976/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea505ded-68ba-4fc1-aaf4-cb19e174ac35) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by Roudabeh1348** [comment]
@surbhigupta12  
The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. I’d very much appreciate your timely review and feedback on the link changes I’ve suggested. Thanks!

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b9047c421584a685024734a2e6e60282b7752b7/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9908625f-9485-42a8-b5a8-8384377680d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b9047c421584a685024734a2e6e60282b7752b7/msteams-platform%2Fresources%2Ftroubleshoot.md) | 75 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9685db03-adbc-46bc-97f5-1542987d59cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b9047c421584a685024734a2e6e60282b7752b7/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b61179b8-5f04-45f6-8a81-ac95d991323a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b9047c421584a685024734a2e6e60282b7752b7/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b86064b0-2dde-42ad-b324-3129ac00890e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b9047c421584a685024734a2e6e60282b7752b7/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0d77ea7-abc0-4f4e-b108-66e2f77888ff) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/91f157e765e6bc88194628df4e2c3170034a3a2d/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0229cb1-c856-49b0-bb33-d5b8fc3e9319) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/91f157e765e6bc88194628df4e2c3170034a3a2d/msteams-platform%2Fresources%2Ftroubleshoot.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71407a25-eff0-4c1e-8841-e14078f0645e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/91f157e765e6bc88194628df4e2c3170034a3a2d/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9bb7d25-c73c-4893-8eec-812f5f4430a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/91f157e765e6bc88194628df4e2c3170034a3a2d/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b37566b-8230-477c-8857-76cbea849aab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/91f157e765e6bc88194628df4e2c3170034a3a2d/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29906417-e489-4175-9925-32770c37755f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ca52548c34a22745a5d65dad15b4ce4db85670b/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f744166a-2ee4-4308-b49f-6703a362120c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ca52548c34a22745a5d65dad15b4ce4db85670b/msteams-platform%2Fresources%2Ftroubleshoot.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df2f1e1c-22cf-440c-a782-697d8a918a47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ca52548c34a22745a5d65dad15b4ce4db85670b/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c3ca60e-9cfd-4b3e-8da1-343929684b21) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ca52548c34a22745a5d65dad15b4ce4db85670b/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5fc156c-8e97-4c67-90f2-14ba975d237b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ca52548c34a22745a5d65dad15b4ce4db85670b/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09c0d31f-13d9-4186-91f0-b498d81588dd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
