### PR TITLE
[Doc Feature][Support meeting start or end event in channel meeting][2014851]

### PR DESCRIPTION
**Pull request by v-tanmayirs**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd6c8cafa034a3534e1bd70dd63ed5d9338de57c/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9538a13f-0204-4638-a0c1-46421b26bbd3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d40040b0a3e524335218248ec7709fe82087e39f/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d03b349-d164-419a-bedc-b7ddc4e8de9a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ae3ba4dc9ce56744760cecc9d11439ccbfc170c/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eadfe232-6ece-443c-8527-4c0a693d40d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ae3ba4dc9ce56744760cecc9d11439ccbfc170c/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5e381df-ed3f-4d10-bc23-525d7c19ef0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ae3ba4dc9ce56744760cecc9d11439ccbfc170c/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8166b7cb-9ae3-4fe4-9868-0d82166f8d3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ae3ba4dc9ce56744760cecc9d11439ccbfc170c/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89aeae67-8127-491c-875d-894384cf75f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ae3ba4dc9ce56744760cecc9d11439ccbfc170c/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/982d8ba2-85ed-43f9-9465-e5abb46a2018) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31ddc89c394626407714586d8c1f01bc866104d4/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9095b08-fdc7-46e3-96d0-4b9364c8b701) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31ddc89c394626407714586d8c1f01bc866104d4/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c3e11b0-e196-40f5-b90f-09a5acb84316) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31ddc89c394626407714586d8c1f01bc866104d4/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d91474bc-3a0f-4086-9ecf-d35f93c02fd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31ddc89c394626407714586d8c1f01bc866104d4/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ed9bf94-cedc-4f0b-89a5-bacfd2028fb3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc71b999677a28eb20f9dcdd871c76345c1b022b/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd2ba59c-9c90-4453-9767-9eaa3b71fc41) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc71b999677a28eb20f9dcdd871c76345c1b022b/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/866d5700-9573-4099-8f62-ccc41d4f139c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc71b999677a28eb20f9dcdd871c76345c1b022b/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7318ffd-d27f-464d-97fe-0631f9b00abb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc71b999677a28eb20f9dcdd871c76345c1b022b/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbc6d827-2c49-425f-a5a5-d07fbdd4d751) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc71b999677a28eb20f9dcdd871c76345c1b022b/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8486060-6ad9-43c3-92ad-a86b315aa576) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by surbhigupta12** [comment]
Duplicate of PR #4815

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ca456523c65b1cdc2b0438a277f98315cb3c391/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 99 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2e20104-1ea5-4068-a096-e630e870d92b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ca456523c65b1cdc2b0438a277f98315cb3c391/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0959b72-0a0d-490e-ad76-4d89b340acef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ca456523c65b1cdc2b0438a277f98315cb3c391/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5a05a15-132b-4899-944a-8ccdee9da581) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ca456523c65b1cdc2b0438a277f98315cb3c391/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ea444e6-730b-45b1-9b67-cdcc16a5ca3b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1dcf21f044a6ec439a223c4c4a0d02b8fd440ae9/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 99 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/313e2a75-bb19-4a3b-8d1a-f9be40a635c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1dcf21f044a6ec439a223c4c4a0d02b8fd440ae9/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da4483eb-6cbb-43b2-a022-9bd0e05f321d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1dcf21f044a6ec439a223c4c4a0d02b8fd440ae9/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ebcf7d8-fe0c-4474-b65a-1c7e8cfada5d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1dcf21f044a6ec439a223c4c4a0d02b8fd440ae9/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95956331-d8a8-487f-8772-ee328a5b2897) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1dcf21f044a6ec439a223c4c4a0d02b8fd440ae9/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/966a5b03-9096-4412-a3a3-a44336a08b56) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e6d8f0c03dd82f62f4b0b0dac568a3e787a02b56/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 99 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ce6d779-51bc-47b0-a505-f60e8ada05fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e6d8f0c03dd82f62f4b0b0dac568a3e787a02b56/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7625e00f-afb8-49cf-b924-6beedf1b3f61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e6d8f0c03dd82f62f4b0b0dac568a3e787a02b56/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/376fa295-8311-4f13-b39c-2f6abf23d1f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e6d8f0c03dd82f62f4b0b0dac568a3e787a02b56/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20f79a7e-57da-49a9-a7b2-6b526f1c15d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e6d8f0c03dd82f62f4b0b0dac568a3e787a02b56/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce498a24-72fb-4b3d-ac06-db5b1a2f95e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e6d8f0c03dd82f62f4b0b0dac568a3e787a02b56/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cea79c57-592b-49c3-93b0-410a11c06830) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e569268392a6a3cfcd938072e596ca9f31d8ed7/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 99 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17b32ad4-c53c-4580-a191-e841902ecf79) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e569268392a6a3cfcd938072e596ca9f31d8ed7/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33d88cb4-26a9-4e73-9b59-d47ecd4c527b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e569268392a6a3cfcd938072e596ca9f31d8ed7/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d35fb078-c6e9-4e5e-85a3-bc71a8fc486f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5e569268392a6a3cfcd938072e596ca9f31d8ed7/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/276686b2-8e5d-4648-a767-01e23dd4c700) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e569268392a6a3cfcd938072e596ca9f31d8ed7/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/289638df-39ce-43d9-9471-202afcabb2d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e569268392a6a3cfcd938072e596ca9f31d8ed7/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8798eb5f-f3ef-4157-9ecc-758576940099) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2803aaf71383135b4f7cc759545a6b969b838166/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9904910-5042-4495-b0de-f850940490cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2803aaf71383135b4f7cc759545a6b969b838166/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/358cc6f6-9e54-495c-aecd-c9643dc2e254) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16413b52919f02a23c9d7f4f0888854c6d0c852f/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d44fbee-4811-46f6-8892-950595292230) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16413b52919f02a23c9d7f4f0888854c6d0c852f/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9e79dd9-609b-4e4a-b992-454ce2e61171) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-ypalikila** [comment]
Created a new PR [7813](https://github.com/MicrosoftDocs/msteams-docs/pull/7813) with the changes from this PR.

**Pull request closed without merging**
