### PR TITLE
[Doc Issue][Tab UI/content changes not reflecting for users][2565485]

### PR DESCRIPTION
**Pull request by v-silakshmi**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/sdk-include.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d648873d8ded6727aa01ec07d4a1656814d5cad/msteams-platform%2Fincludes%2Fsdk-include.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44dd705b-1e61-4922-93a5-53d96eae7c9e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/sdk-include.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0087a5f031c089575cd16d816fa738b26e01b377/msteams-platform%2Fincludes%2Fsdk-include.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4ee79de-3305-4352-baaa-576a3c095d7b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — DISMISSED** [review]
Approved

**Review by SubbaReddi — APPROVED** [review]
Approved

**Review by surbhigupta12 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/sdk-include.md](https://github.com/MicrosoftDocs/msteams-docs/blob/24c196b9124d1369dfec4a2018293080367d8a93/msteams-platform%2Fincludes%2Fsdk-include.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91382ac6-ddd4-4231-b6a3-ed83c286115b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2b47bf0c105e361f1e3607e011bb9215d01da1a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-links.md) | 93 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/104edc36-7185-4580-8bae-cade66364807) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/sdk-include.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2b47bf0c105e361f1e3607e011bb9215d01da1a/msteams-platform%2Fincludes%2Fsdk-include.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/351c02b6-2d17-438e-87c4-d9018c83b637) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8599efed5dabac47c135ed20401eb0ec3c9af238/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-links.md) | 93 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61da4ce3-e9ca-479d-bd8c-4c54cc143c50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/sdk-include.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8599efed5dabac47c135ed20401eb0ec3c9af238/msteams-platform%2Fincludes%2Fsdk-include.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0a7b26e-9326-4f6f-8245-7a375db424fb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58308facb074d1790b8a1c0d7978305d8a4bdb15/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-links.md) | 93 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f64bc23-adb0-4b05-9c42-f5455b56156f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/sdk-include.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58308facb074d1790b8a1c0d7978305d8a4bdb15/msteams-platform%2Fincludes%2Fsdk-include.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b109e60b-4843-4db2-b8aa-153eae9573ae) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4b8ddfdf993cc63beeca0f4611cd48c996f2e59a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-links.md) | 93 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d6491e8-a1fd-4e59-ac88-e7a7ade21c39) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/sdk-include.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4b8ddfdf993cc63beeca0f4611cd48c996f2e59a/msteams-platform%2Fincludes%2Fsdk-include.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0361811d-4cd8-4e83-bf67-dd1552a016ce) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5d328199b44c2c675556b3e41a01e9e2012f57fd/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-links.md) | 93 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9007aef6-c8d1-4398-b64a-dfe0cd621745) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/sdk-include.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5d328199b44c2c675556b3e41a01e9e2012f57fd/msteams-platform%2Fincludes%2Fsdk-include.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/672a43df-e1dc-4c7c-bbca-e82ec78473bb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/492544773fd416226b4360c5e61b389bfd2307ca/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-links.md) | 93 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6b8c9fa-3e59-4585-9e56-0dfe6e48820f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/sdk-include.md](https://github.com/MicrosoftDocs/msteams-docs/blob/492544773fd416226b4360c5e61b389bfd2307ca/msteams-platform%2Fincludes%2Fsdk-include.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4fa94a1f-89a8-423d-8cf1-184cdbb25baf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b96e32b608272ea880305761bef2cb68cf784e02/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-links.md) | 93 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31a91cf7-9dc9-4b57-9a66-9fef532917cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/sdk-include.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b96e32b608272ea880305761bef2cb68cf784e02/msteams-platform%2Fincludes%2Fsdk-include.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64582736-6f04-4cef-87db-b39666b30e21) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b96e32b608272ea880305761bef2cb68cf784e02/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e11a4c7-5155-4a46-94d5-7920565f8d4a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Pull request merged**
