### PR TITLE
[Doc Feature][Media elements in AC][3968525]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f8dcb46fccf30bff072221719cd3b6b8ad46f15/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30d6b203-db5d-4228-9f4d-46cbbae8d990) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17b0dee9de778582146504b14178095badb2bcbb/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c03e305b-b0ea-4875-9e35-5c66da407585) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ca4ed8b190f5a704d45d2cd2178b0cd8170983a/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe58b08d-b90a-4a34-ae4d-e3c62df1248e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6a8a3c2ac3801272a241ba5e77423965a2cb0b63/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bdd95c3-e1b0-4fd3-835e-fdf3ed015d75) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/83b898f9961fe3d06e6182b011b833e7253288f4/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e3bd7fb-5a79-4886-8645-286933bf02ec) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ac1ec530773494662ccac1b8b47b561ae8cda4/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52713e89-4aad-4e5a-bae6-106953efabb3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94ec28bf1a9b3ff922893e103fde6feb69416145/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1dcbd064-5041-4df2-9e5e-9be8f58b5399) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/67afa2381ca345729477501ea7ac316fcd852fce/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c06f340-5d10-40e4-949f-584bd7dfa034) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f57a24aef26a6ddd225044a84683d45750f7133/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c01bcbb-e494-4d6b-8a55-2ad24a848bef) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59912b04b9644bfcf151df4927fe35f176f58140/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90ec87c9-102a-47a6-938d-1a90c2541620) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59912b04b9644bfcf151df4927fe35f176f58140/msteams-platform%2Fwhats-new.md) | 90 | 89 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fedc9d2a-3c7f-4214-ab0f-5fd26fde381d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78e166254af59f09163ab4dc0b74f5f556184588/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7809b86c-0255-437a-ad4c-56efe0f4b6e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78e166254af59f09163ab4dc0b74f5f556184588/msteams-platform%2Fwhats-new.md) | 90 | 89 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2322eabc-caa6-43c0-9488-7748c4485253) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66eb27f0da58a07f50022ec69b0aef646d6253f5/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c28a54d-a9bf-4de3-ad56-5ed2b408129b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66eb27f0da58a07f50022ec69b0aef646d6253f5/msteams-platform%2Fwhats-new.md) | 90 | 89 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04cdb43a-ed4d-4d5e-8121-167aad5d2c08) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d673fdd1e7ab51b12a0a6bbaf393ae1ac8b9048/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db7ab088-ff9e-4fb1-8ae5-4ba88b7510e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d673fdd1e7ab51b12a0a6bbaf393ae1ac8b9048/msteams-platform%2Fwhats-new.md) | 90 | 89 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b76567ec-e1a4-4ae3-aaf1-aa497b7d5ef4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3a769b154cb41cea838a85401f305ce78c758e35/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5fc73a48-2333-477d-8319-340725d6605f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3a769b154cb41cea838a85401f305ce78c758e35/msteams-platform%2Fwhats-new.md) | 90 | 89 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/abdd05e3-40e4-4e54-9b48-82e6f1b494c2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6861b6cac94e38da33120101cd34fe15cba6fca5/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f09a77fc-90a7-4669-bbd4-c91416f099c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6861b6cac94e38da33120101cd34fe15cba6fca5/msteams-platform%2Fwhats-new.md) | 90 | 89 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c4fd9c4-9a4d-4f4a-8b52-54cadacec1f2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a8302e8d0ddffa6c9573c868bbd4de062e0d4e23/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb876ed3-baa4-46ab-bef5-c99214def375) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a8302e8d0ddffa6c9573c868bbd4de062e0d4e23/msteams-platform%2Fwhats-new.md) | 90 | 89 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1eaebdbc-79db-403a-9301-06bb14173f13) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfb2db3d6f644ed55b07fbcb763ba63ec20a8436/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47169d7c-54ae-4714-9afa-71b6d6dd62c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfb2db3d6f644ed55b07fbcb763ba63ec20a8436/msteams-platform%2Fwhats-new.md) | 89 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d0cc9d3-baca-4b32-bb87-da4fdcc796b2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48aa551c9e6920ea63ce70430a3a86e2f2355aa1/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc1f1653-fbb3-41b3-a1e4-6a555dea25e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48aa551c9e6920ea63ce70430a3a86e2f2355aa1/msteams-platform%2Fwhats-new.md) | 89 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75d6053c-494e-4b9d-9ffd-b37cb1ee22af) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc275b83e9235ce469bf5285b58a77fd6e64c18f/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/376d4e03-bc05-4681-a6cc-f20c5a24da7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fc275b83e9235ce469bf5285b58a77fd6e64c18f/msteams-platform%2Fwhats-new.md) | 89 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f47a88af-673c-464e-bf1c-ab37ef47161c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ff157d27ecc2e567c815310c89160b652631c25/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfce8e3e-854b-4323-a25e-229093c463a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ff157d27ecc2e567c815310c89160b652631c25/msteams-platform%2Fwhats-new.md) | 89 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58ae4b2d-1f61-4537-8545-15b763de0fee) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-npaladugu** [comment]
Assigned to @v-bvishnu

**Review by SwarathmikaK — DISMISSED** [review]

**Review by susanshen96 — APPROVED** [review]

**Review by Wajeed-msft — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc3525477eee17a5a6d9c5c5bb6f1b4965d9ed45/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a694b976-9745-488b-a085-8b361d03ee1b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8df0ca7c609dc21aff53a3551dd80494e7d91f4/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a738ab10-12f7-4a34-aade-1bfd0e936b7a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/media-elements-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b26a0465e2014a82e3d0d6104cf44b9a60b94509/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fmedia-elements-in-adaptive-cards.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66379455-457b-4d6a-81cf-7be2771e2d05) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
