### PR TITLE
Added uhfHeaderID to metadata

### PR DESCRIPTION
**Pull request by lindalu-MSFT**

### CODE REVIEW

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/includes/get-started/step1-prepare-for-dev.md](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/includes/get-started/step1-prepare-for-dev.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fincludes%2Fget-started%2Fstep1-prepare-for-dev.md)
[msteams-platform/includes/get-started/step1-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/includes/get-started/step1-intro.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fincludes%2Fget-started%2Fstep1-intro.md)
[msteams-platform/docfx.json](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/docfx.json) | :white_check_mark:Succeeded | |

<a name="msteams-platform%2Fincludes%2Fget-started%2Fstep1-prepare-for-dev.md"></a>
### [msteams-platform/includes/get-started/step1-prepare-for-dev.md](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/includes/get-started/step1-prepare-for-dev.md)
 - **Line 10**: **[Warning]** Invalid file link:(~/get-started/get-started-tenant).
 - **Line 10**: **[Warning]** Invalid file link:(~/get-started/get-started-tenant).
 - **Line 15**: **[Warning]** Invalid file link:(~/get-started/get-started-tenant).
 - **Line 15**: **[Warning]** Invalid file link:(~/get-started/get-started-tenant).

<a name="msteams-platform%2Fincludes%2Fget-started%2Fstep1-intro.md"></a>
### [msteams-platform/includes/get-started/step1-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/includes/get-started/step1-intro.md)
 - **Line 3**: **[Warning]** Invalid file link:(~/concepts/apps/apps-overview).
 - **Line 3**: **[Warning]** Invalid file link:(~/concepts/apps/apps-overview).
 - **Line 5**: **[Warning]** Invalid file link:(~/get-started/get-started-app-studio).
 - **Line 5**: **[Warning]** Invalid file link:(~/get-started/get-started-app-studio).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C18%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201810180245535901-290%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=azFirAbnQ6XNITHqfHNSc7WiPtREhjGLkyhYhjq9l7U%3D&st=2018-10-18T02%3A42%3A21Z&se=2018-11-18T02%3A47%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@charlesprakash Hi, please merge and publish this metadata update. This will add the custom Teams header to MicrosoftDocs, right now it uses the default Microsoft header. We want to use the Teams header like on the Dev Portal: https://developer.microsoft.com/en-us/microsoft-teams/docs. Thanks, lindalu

**Comment by NormSohl** [comment]
Hi, Linda - Charles is no longer working on this doc set, but I can take care of it for you.  Thanks.

**Comment by lindalu-MSFT** [comment]
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
