### PR TITLE
Update tabs-mobile.md

### PR DESCRIPTION
**Pull request by vikramjit-singh-chug**

### CODE REVIEW

**Review by KirtiPereira — DISMISSED** [review]
Approved

**Review by heath-hamilton — COMMENTED** [review]
@vikramjit-singh-chug Please see my commit, which includes your new content but in a different flow.

**Review by vikramjit-singh-chug — COMMENTED** [review]
In the last paragraph, can we specify that the default here is only for unapproved apps? And the default for approved apps is that it will open within Teams? @heath-hamilton 

 For channel and group tabs, by default the tab launches in a browser using your `websiteUrl` configuration.

**Review by heath-hamilton — COMMENTED** [review]
@vikramjit-singh-chug Please see the updated text. Just want to verify the following is accurate?

`Instead, a channel and group tab by default opens in a browser using your `websiteUrl` configuration (which you also must include in your source code's `setSettings()` function, which is part of the Teams JavaScript client SDK).`

What about personal tabs? Do they also open in the browser by default?

`If you're sideloading your app or publishing to an org's app catalog, you don't need mobile-specific approval.`

In these situations, will the tab always open in the mobile client?

**Comment by vikramjit-singh-chug** [comment]
My suggestion for the text:

Apps listed on the Teams store must be approved for mobile use. Configurable Tabs (distributed via Teams Store) that are unapproved by Microsoft for Teams Mobile open in the device's default browser using your websiteUrl configuration (which you also must include in your source code's setSettings() function, which is part of the Teams JavaScript client SDK). However, users can still load an unapproved tab in the Teams mobile client by selecting the ... more menu next to the app and Open. This triggers your app's contentUrl configuration. **Approved Configurable Tabs always open in Teams using the contenturl configuration.**

Personal Apps (distributed via Teams Store) that are unapproved by Microsoft for Mobile do not show up on Teams Mobile Clients. Those Personal Apps that are approved for mobile show up in the bottom bar of the mobile clients and all static tabs within the Personal App are opened within the Teams client using their respective contenturls.

If you're sideloading your app or publishing to an org's app catalog, you don't need mobile-specific approval and the behavior of such constructs on mobile clients will be same as that of Store apps that are approved by Microsoft for mobile.

**Comment by vikramjit-singh-chug** [comment]
Gist of the behavior

Tabs:

If not approved: Will show up on Mobile in More section of Channel/chat, but clicking on the app will open the browser window using the website url

If approved: Will show up in More section, clicking on the app will use the contenturl and open the content within the Teams client using an in-app webview

Personal Apps:

If not approved: Will not show up on Mobile at all

If approved: Will show up in the bottom bar of Mobile Clients. Clicking on the app will load the Personal App in which each static tab is loaded in an in-app webview using the respective content urls

**Review by heath-hamilton — APPROVED** [review]
Approved based on latest discussion and changes, @vikramjit-singh-chug. (cc: @surbhigupta12)

**Review by surbhigupta12 — APPROVED** [review]
Approved the PR

**Pull request merged**
