### PR TITLE
[Doc Improvement][Teams 2.1 update][3417008]

### PR DESCRIPTION
**Pull request by v-ganr**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47938e106861efd255bf3dea7711553dd64c2e65/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19080839-d651-4ed6-b8ee-b1d3c5ee10fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47938e106861efd255bf3dea7711553dd64c2e65/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21c0d9d7-1718-4225-8f6e-0de3845dc272) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9dd385dcce195bd10ffaa2747e479545ed5f577c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b42eca12-06b4-4334-bcae-35607bf130ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9dd385dcce195bd10ffaa2747e479545ed5f577c/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8296e819-b48a-4dfb-bcec-b5b35c04bfb4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a12b562cbf8b2a1d8dfee34441191de6328c361/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a75069a-a55d-426a-8360-5cce9358095d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a12b562cbf8b2a1d8dfee34441191de6328c361/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d7f645a-56a9-4187-832a-38c2e9f2ac3d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c3a6c746df5622b90f3b3d7e3201a7b117b227c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fea6633f-65b9-425a-87e9-7d0706173d49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c3a6c746df5622b90f3b3d7e3201a7b117b227c/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9348649b-fd7d-4fc4-8e68-6c2807553f99) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f4024550ea7e6438b69aa6facdc5059355f3863/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f9d1205-62de-4b0f-8e3f-68228fe0cb2a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f4024550ea7e6438b69aa6facdc5059355f3863/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 94 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9365dffb-095f-40fb-b28d-59667cdd49d8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8d122783109fa21587f443e419a946d8604fb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/324ac2ab-3d10-4aa4-be11-7a17bf52f69a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7cc8d122783109fa21587f443e419a946d8604fb/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 94 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/796a7921-ab2c-4301-a520-a20d8713981a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/75d7df92b9dde91b8fb0e82d200618a36e32380c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f3dd397-4a62-4fb4-b5b7-89ed8d1ea5ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/75d7df92b9dde91b8fb0e82d200618a36e32380c/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 94 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54decf26-a83c-4d8c-ba4e-1be25a11463e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99ac6337df7473a2959228f2bdf1c352b0c355e0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e496f075-6034-44f6-b347-0668cb08ed2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99ac6337df7473a2959228f2bdf1c352b0c355e0/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 94 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c23c6267-f0f1-4620-b5a1-552de5f28044) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/955a1bda60b68face2b327310bfcb181ad4ec4fd/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/889a74c5-cefc-40df-98f5-c7c75479f51d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/955a1bda60b68face2b327310bfcb181ad4ec4fd/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6397524e-c06d-4c4f-8dd7-a13d5ba8a9fc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32d34bfb6260d307d78b5cbc46049ace13d53c23/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32c81e74-f50d-46ad-8b2f-8daef31c43ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32d34bfb6260d307d78b5cbc46049ace13d53c23/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55dde119-cd8d-4c6a-80d0-57beb6dec2b4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
