### PR TITLE
[Doc Improvement][How to guide - Create configure outlook add-in][3636350]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/configure-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0731ad5c8af9e4903d92a1f4fd62a4b8b684708/msteams-platform%2Ftoolkit%2Fconfigure-outlook-add-in.md) | 55 | 326 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ea86fb1-3d24-4049-937c-7d7ea322343e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/configure-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f1c9c2a68781cf478f64a19cced1c47e591ea556/msteams-platform%2Ftoolkit%2Fconfigure-outlook-add-in.md) | 60 | 245 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9160979-09c8-47bf-b87e-1862696a093b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/configure-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ccc35e08dcb51c0e1f2195932e9de295286b2fa5/msteams-platform%2Ftoolkit%2Fconfigure-outlook-add-in.md) | 60 | 245 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57f00732-c6db-46a9-82ec-0c75641edb19) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-How-to-guides-v5.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e22098b57960516887dd21b2db670f623e9a4074/msteams-platform%2Ftoolkit%2Fadd-How-to-guides-v5.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d8fb4b4-d2d8-402c-bd73-9b168d58e39e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e22098b57960516887dd21b2db670f623e9a4074/msteams-platform%2Ftoolkit%2Fconfigure-outlook-add-in.md) | 60 | 246 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39e0219f-b96d-43bb-a5eb-bea503488767) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-How-to-guides-v5.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1abf0e4bfb4c50bc0dd5f667c027ccd6afa34aa6/msteams-platform%2Ftoolkit%2Fadd-How-to-guides-v5.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/483f691b-6cc9-4749-b929-343eb982bea5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1abf0e4bfb4c50bc0dd5f667c027ccd6afa34aa6/msteams-platform%2Ftoolkit%2Fconfigure-outlook-add-in.md) | 60 | 239 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c0bb22f-b15b-45a0-a962-aa121ff5473e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-How-to-guides-v5.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5de86c4340f8589bcc043cb7e5d4d9aeb48c634c/msteams-platform%2Ftoolkit%2Fadd-How-to-guides-v5.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd9773ff-882c-4f23-801d-f432838b5584) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5de86c4340f8589bcc043cb7e5d4d9aeb48c634c/msteams-platform%2Ftoolkit%2Fconfigure-outlook-add-in.md) | 70 | 158 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0507d8bf-f098-4f9a-961f-d4a126beef95) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-How-to-guides-v5.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32333cc8e7d181d67ca99a6f0805ea172582d0c0/msteams-platform%2Ftoolkit%2Fadd-How-to-guides-v5.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/736200aa-c33f-45ec-9da5-162e3d249823) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32333cc8e7d181d67ca99a6f0805ea172582d0c0/msteams-platform%2Ftoolkit%2Fconfigure-outlook-add-in.md) | 70 | 158 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7098ddb5-3ec4-47f4-b4aa-d3f98056e7e1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-How-to-guides-v5.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3fa77df7b61cab8c91bdd01008f9f1066f17e337/msteams-platform%2Ftoolkit%2Fadd-How-to-guides-v5.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d109d0c-e22e-4465-8ade-12a675665515) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3fa77df7b61cab8c91bdd01008f9f1066f17e337/msteams-platform%2Ftoolkit%2Fconfigure-outlook-add-in.md) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93db424c-dc65-44ec-89d2-9df3e8c32366) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-How-to-guides-v5.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba3f46b1444b1f98fbb44cab099c9d1463661024/msteams-platform%2Ftoolkit%2Fadd-How-to-guides-v5.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c82e075f-bca6-49e3-a108-9b4882ea7e05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba3f46b1444b1f98fbb44cab099c9d1463661024/msteams-platform%2Ftoolkit%2Fconfigure-outlook-add-in.md) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ec8a288-7f63-4169-97bb-683a97d7038b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-How-to-guides-v5.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff2b7e4aaef5b7a0a95bd3ea6d981c59959604e1/msteams-platform%2Ftoolkit%2Fadd-How-to-guides-v5.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72d315be-8b63-4ab8-8f4b-8b579463b53e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff2b7e4aaef5b7a0a95bd3ea6d981c59959604e1/msteams-platform%2Ftoolkit%2Fconfigure-outlook-add-in.md) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc49a6b3-5a33-4adc-a6af-4b6bbe8bf0c5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-How-to-guides-v5.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87756a1ed3cf0295b1e036bfcf4b52afbf754cf8/msteams-platform%2Ftoolkit%2Fadd-How-to-guides-v5.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92460c5e-ccdc-410f-b779-ac90a1a2c0c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87756a1ed3cf0295b1e036bfcf4b52afbf754cf8/msteams-platform%2Ftoolkit%2Fconfigure-outlook-add-in.md) | 89 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a84a72b-b192-48eb-b274-632c7ff4aa82) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-How-to-guides-v5.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f7322ed0e43d62db0979e790705e141b5be93471/msteams-platform%2Ftoolkit%2Fadd-How-to-guides-v5.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c57f8f0-b452-4d9b-91a7-48ace486d66f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f7322ed0e43d62db0979e790705e141b5be93471/msteams-platform%2Ftoolkit%2Fconfigure-outlook-add-in.md) | 87 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8a39900-2b81-455b-b5b8-76f0bd01b471) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by summzhan — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-How-to-guides-v5.md](https://github.com/MicrosoftDocs/msteams-docs/blob/401d38d783cde9c23fe68cf791313236241ba777/msteams-platform%2Ftoolkit%2Fadd-How-to-guides-v5.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b11663a7-26ff-4aca-a5bb-f958b4fcea22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/401d38d783cde9c23fe68cf791313236241ba777/msteams-platform%2Ftoolkit%2Fconfigure-outlook-add-in.md) | 87 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61be9f7e-1d35-40db-b70f-45c8f534466d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request closed without merging**
