### PR TITLE
Adding documentation for using connectors in Tenant App Catalog

### PR DESCRIPTION
**Pull request by pradeepananth**

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[0d9c09f](https://github.com/pradeepananth/msteams-docs/pull/567/commits/0d9c09f53dec6aeded70c53f504e11084afa979d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Connectors/connector-app-install.png](https://github.com/pradeepananth/msteams-docs/blob/using-sideloaded-connectors/msteams-platform/assets/images/Connectors/connector-app-install.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Connectors/connector-app-setup.png](https://github.com/pradeepananth/msteams-docs/blob/using-sideloaded-connectors/msteams-platform/assets/images/Connectors/connector-app-setup.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Connectors/connector-dialog-sideloaded.png](https://github.com/pradeepananth/msteams-docs/blob/using-sideloaded-connectors/msteams-platform/assets/images/Connectors/connector-dialog-sideloaded.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Connectors/tenant-app-catalog.png](https://github.com/pradeepananth/msteams-docs/blob/using-sideloaded-connectors/msteams-platform/assets/images/Connectors/tenant-app-catalog.png) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/connectors/connectors-using.md](https://github.com/pradeepananth/msteams-docs/blob/using-sideloaded-connectors/msteams-platform/concepts/connectors/connectors-using.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904152155593699-567%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qfRKyUqH6qHTr%2BcvBYoP8TYVKjU%2Bb6HdCssqduqGOLQ%3D&st=2019-04-15T21%3A52%3A33Z&se=2019-05-16T21%3A57%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clearab** [comment]
I'm going to move this to the Create your connector page, instead of on the using page

**Comment by o365devx** [comment]
Docs Build status updates of commit _[a8923bf](https://github.com/pradeepananth/msteams-docs/pull/567/commits/a8923bfe282bcf7886efe624d1a0a0bae5eb230a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Connectors/connector-app-install.png](https://github.com/pradeepananth/msteams-docs/blob/using-sideloaded-connectors/msteams-platform/assets/images/Connectors/connector-app-install.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Connectors/connector-app-setup.png](https://github.com/pradeepananth/msteams-docs/blob/using-sideloaded-connectors/msteams-platform/assets/images/Connectors/connector-app-setup.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Connectors/connector-dialog-sideloaded.png](https://github.com/pradeepananth/msteams-docs/blob/using-sideloaded-connectors/msteams-platform/assets/images/Connectors/connector-dialog-sideloaded.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Connectors/tenant-app-catalog.png](https://github.com/pradeepananth/msteams-docs/blob/using-sideloaded-connectors/msteams-platform/assets/images/Connectors/tenant-app-catalog.png) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904191829062619-567%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fmEpNvCkaXttry%2B4uIFQGG5S69Ssyhwsr9mKltp4JD4%3D&st=2019-04-19T18%3A25%3A04Z&se=2019-05-20T18%3A30%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clearab** [comment]
Merging this PR for the screenshots, moving the article changes to a new branch so I can make some deeper edits.

**Pull request merged**
