### PR TITLE
[Doc-Improvement][Test preview monetize]

### PR DESCRIPTION
**Pull request by v-habibaumme**
Updating the what's new page

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/33c142253c10b740a3697dc1bdf2141141310a20/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60a35cbf-1a3e-450e-b039-f0075e8c94b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/33c142253c10b740a3697dc1bdf2141141310a20/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b512edd-1271-4e17-8843-9a99cd3898f7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8de443b5772a6cbc989499cd4c83b00c5ace43fb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42c167d3-db35-41e2-afa5-7a99227bec45) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8de443b5772a6cbc989499cd4c83b00c5ace43fb/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8536467c-3d30-46e4-a90b-58e52b8ef29e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by ashishguptaiitb — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8a3b916b8bfbe0abf30babe73eab5218fc7bb47a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24fee6fb-dcc3-44fe-8de4-ee017a7fa841) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8a3b916b8bfbe0abf30babe73eab5218fc7bb47a/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2472929-28a5-4561-9110-d931c09f7591) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d73e40d3c902115625701f5f9ed6c35bb73ada5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8870ac9-d914-4c62-88ae-803b97ebb2d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d73e40d3c902115625701f5f9ed6c35bb73ada5/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3979ca8-21b1-4a0e-9d90-7070ec3dcd11) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6a8993fc4eb7dc2d7f7d82b84f25cd4c680ec88b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3b3244a-9b52-49cd-b888-30a73e5e3656) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6a8993fc4eb7dc2d7f7d82b84f25cd4c680ec88b/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/932367df-52d5-4f44-b9e0-052737985f7e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by ashishguptaiitb — APPROVED** [review]

**Pull request merged**
