### PR TITLE
[Doc Improvement][add-api-connections.md][2894687]

### PR DESCRIPTION
**Pull request by Namitha-23**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4b25eafef1d188e8f6962cd3961544e3586ac2a0/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 86 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ba5b0d0-d63c-43b5-8b5b-33923030fe3f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6787eacc29fb72376e35e2a25d057a2706d90133/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19a50ad8-c755-4ee0-ad67-d8831718360d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfb5f390fa996bc204d34b7237bc05e56bbda95b/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f4fbf75-9b7d-443d-ac37-f9b52273c6f3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b3deb6ff8e0e549ea5b5da77b3a661d732dc820c/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75635aca-85b7-4591-9e57-3d1de2305114) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f18614cf32877e72738f2c090cb0c30cbf4c04/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ee16242-334a-445c-a855-1a6583ab59bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f18614cf32877e72738f2c090cb0c30cbf4c04/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fnotification-bot-in-teams.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/723b7d00-4df5-4a3c-9f99-905891f9858f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f18614cf32877e72738f2c090cb0c30cbf4c04/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52f296af-5c03-4b76-b5b3-cd7bef5dbc7b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9caffaa7370bba89db2f2f5bd5351fc2c9e93d67/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc059c63-0f43-4e05-8437-10199bcd1203) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9caffaa7370bba89db2f2f5bd5351fc2c9e93d67/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fnotification-bot-in-teams.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31526acc-6fc0-4eba-a617-54f46af5c74b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9caffaa7370bba89db2f2f5bd5351fc2c9e93d67/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c0a1098-dbac-423b-8d3b-f4e91287f063) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e779ea38e4262013b1e1b69aebec26977effbeaa/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7095092-4848-4fae-adf8-5165ef59bff5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e779ea38e4262013b1e1b69aebec26977effbeaa/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fnotification-bot-in-teams.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb8548a0-bf91-4aae-a603-56f92b4d3cfc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e779ea38e4262013b1e1b69aebec26977effbeaa/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa06051f-bea8-4b35-8db7-6a98728405f3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66d01ebd4f5f11069b31f82dc8a131664ee12437/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bdaedc4-2ca4-4d57-b08c-18f1d448a4fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66d01ebd4f5f11069b31f82dc8a131664ee12437/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fnotification-bot-in-teams.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70fafe12-9311-41c1-bc90-fc71be78c3b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66d01ebd4f5f11069b31f82dc8a131664ee12437/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6b14557-8076-43e4-9fe5-d578a8bbed5e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71aa35e0fb50cd2e797f0f3545dfce61705f6f51/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a8c134b-3df8-449c-b7ce-6fad4b96db97) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71aa35e0fb50cd2e797f0f3545dfce61705f6f51/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fnotification-bot-in-teams.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfbc712e-fb3c-4484-ab28-33ead4ae5862) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71aa35e0fb50cd2e797f0f3545dfce61705f6f51/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63cabb97-58cd-4429-b367-57028e0f7f53) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5d1669aa9f52d70c417487cb0adc1c880274128e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7c90e1f-32e8-4d12-89b0-5a91025cb51d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5d1669aa9f52d70c417487cb0adc1c880274128e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fnotification-bot-in-teams.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5c549a4-5829-4fb1-a146-d258a4b9e419) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5d1669aa9f52d70c417487cb0adc1c880274128e/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d8846ea-8be2-487f-adae-b147c485d6da) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
