### PR TITLE
[Doc Improvement][Remove time and future ref: 10]

### PR DESCRIPTION
**Pull request by v-bvishnu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/scale-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2beb1a33b170e325615ee75b07e34872bd6bc7d4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fscale-app.md) | 80 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7ca5a3f-0219-488b-b885-f7484cccd187) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2beb1a33b170e325615ee75b07e34872bd6bc7d4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 83 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3187c446-d726-4444-91a0-c1fc10a1bc26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2beb1a33b170e325615ee75b07e34872bd6bc7d4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/150edda6-afc6-4e7c-b604-54762594c0e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2beb1a33b170e325615ee75b07e34872bd6bc7d4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 88 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff01bea4-3ee9-4ee5-adfc-c39d466e9d53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-nodejs.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2beb1a33b170e325615ee75b07e34872bd6bc7d4/msteams-platform%2Fsbs-gs-nodejs.yml) | 89 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0088c6f4-8b51-4c3d-b99c-201f5b6c7c81) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/scale-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad14b7cbb35be6fbd5fe9081d555986ff54487ec/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fscale-app.md) | 80 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e4c1104-bbc3-48b8-8fdb-5c3de64d734f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad14b7cbb35be6fbd5fe9081d555986ff54487ec/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 83 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4027543-3a70-4155-ad5f-23f56749ca97) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad14b7cbb35be6fbd5fe9081d555986ff54487ec/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fdf885c-5c10-4f5b-b96d-9ad15e3c32bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad14b7cbb35be6fbd5fe9081d555986ff54487ec/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 88 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0dbbd62-44da-489b-835b-b6dee16f1832) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-nodejs.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ad14b7cbb35be6fbd5fe9081d555986ff54487ec/msteams-platform%2Fsbs-gs-nodejs.yml) | 89 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f4e3c8a-bb88-4d06-ad17-016cbc774cb0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-ypalikila — APPROVED** [review]
Approved.

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/scale-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcd24453a54bd5ab2441f8d893f0b9fe1ee4a3f8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fscale-app.md) | 80 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfa4140c-3958-4a42-8245-584be65460ed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcd24453a54bd5ab2441f8d893f0b9fe1ee4a3f8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 83 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cbe9da4f-faf3-406a-84a3-ceda3cb7acbc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcd24453a54bd5ab2441f8d893f0b9fe1ee4a3f8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63f222c2-2745-48aa-b906-3419e8b01442) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcd24453a54bd5ab2441f8d893f0b9fe1ee4a3f8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 88 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/730e1bc3-2495-4111-bf6f-9ae905e303c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-nodejs.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dcd24453a54bd5ab2441f8d893f0b9fe1ee4a3f8/msteams-platform%2Fsbs-gs-nodejs.yml) | 89 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aabca4e4-b9dd-461b-8e4b-e90e07689137) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
