### PR TITLE
[Doc Feature][Integrate people-picker-capability]

### PR DESCRIPTION
**Pull request by v-leenagopal**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3244bccc2fce3eded445e8223da4a1e1809aa08b/msteams-platform/concepts/device-capabilities/people-picker-capability.md) | 82 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ae33fb2-7342-4ab3-8f1f-008e69c9275d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ec45bbd85128e7593132185349037bed5372350/msteams-platform/concepts/device-capabilities/people-picker-capability.md) | 81 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2942a3c5-1c1e-46d7-a587-a6811fd6f065) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/67e7254454f822122574206a72a6f83a8048778d/msteams-platform/concepts/device-capabilities/people-picker-capability.md) | 81 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6824578-f195-43ff-bd08-bc07f7cf5c42) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0e2fdd6029553ee63af844aaa6e32d2f7db4c983/msteams-platform/concepts/device-capabilities/people-picker-capability.md) | 81 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b92bc31-a7a9-4367-be6e-6b54672e6172) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3eadff7a637826d0f8898cc02168fcac57753e/msteams-platform/concepts/device-capabilities/people-picker-capability.md) | 81 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f718758f-548f-44b8-91de-f56674d0ced9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/afca6f4c53dc06bb18b253c19f8c8d60cc4f2784/msteams-platform/concepts/device-capabilities/people-picker-capability.md) | 81 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1c42ab0-2700-4950-b66b-cbe6f5dc7efb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac4be5d59ac1426d81e66f9481d8ae056ee94aca/msteams-platform/concepts/device-capabilities/people-picker-capability.md) | 83 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/996cf6dd-dc6f-47d8-a501-7dcc818de98c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf07fcf461c1b1816f98e8f3e2ecb6c6e6984571/msteams-platform/concepts/device-capabilities/people-picker-capability.md) | 82 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37da28c3-6998-494e-a0e8-d9f02f978349) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2bcba19b28c3bb60cbee4c6e52789b540f0246f2/msteams-platform/concepts/device-capabilities/people-picker-capability.md) | 84 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b6d888d-c1db-442e-9217-070f2fde6096) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ed7ac24a688f67f82758a76b6f5ec7052c74aeb/msteams-platform/concepts/device-capabilities/people-picker-capability.md) | 85 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4c47f17-e7e1-4639-975b-84077f07b371) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/TOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f693ba0-79e3-41ee-be03-c0027992f430) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/bots/bot-features.md) | 86 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62e8b014-a6e4-4b2f-a058-67dc3687ac65) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/call-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/bots/calls-and-meetings/call-notifications.md) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f553d2f7-1c67-44ba-9a2e-4b6795ffc3fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | 87 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74d5ba6c-457f-4792-86e5-c6085cf7979d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md) | 80 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dca4ed90-58ab-432d-895c-2ec01f759bf8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99eeff55-4563-4113-8385-8dae38848d6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/auth-flow-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/bots/how-to/authentication/auth-flow-bot.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b79a1cd-2541-4150-a5ae-15e973dfd43d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/bots/how-to/bots-filesv4.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7895d6ee-4770-4b41-9e76-14e766a49c60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ede9add8-e1e3-41b8-9ddf-2d94aafd13e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | 87 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bec236d3-a8c0-49bb-8727-3cc6c8a15d2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/debug/locally-with-an-ide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/bots/how-to/debug/locally-with-an-ide.md) | 81 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6372a7b-fb64-4614-a76c-67857a561c35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/rate-limit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/bots/how-to/rate-limit.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/024faa23-9703-4583-8bc6-d0c772368a10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/bots/how-to/update-and-delete-bot-messages.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38ea443c-1f86-48bf-a2c9-34dbc2f48fbc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/configure-identity-provider.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/authentication/configure-identity-provider.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9e5008d-5872-4bac-9f9c-06707649ec7c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/build-and-test/apps-localization.md) | 83 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b347e2fc-a19a-429b-aeb0-9df445547072) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/test-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/build-and-test/test-app-overview.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ee1e687-38b0-4efa-8dcc-ac81f89d6d7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/build-and-test/test-data.md) | 85 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6d66ed6-7346-4f99-8222-b88d3e0c4f8b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/add-default-install-scope.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/deploy-and-publish/add-default-install-scope.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70351d69-c307-425c-8f78-11305d6f7e22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/deploy-and-publish/apps-upload.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb3c4e83-cf88-410f-a63d-c73d990939d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md) | 87 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0cbe528f-589f-4cce-88a2-a73dfaed6f73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d48f7d77-b51b-4a43-8f5c-e31c8c0885ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5806b83e-f7a8-4d1b-a20c-d6dbb88c34a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c52af76-292c-4cca-9b49-3cf2c82d9c3b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/design/map-use-cases.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f5a9a76-5afa-42b2-8bdf-47bff70b960a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/plan-responsive-tabs-for-teams-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/design/plan-responsive-tabs-for-teams-mobile.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ce7197c-69a1-4286-9843-e7620bd151a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/browser-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/device-capabilities/browser-device-permissions.md) | 88 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/296d7d07-37cd-4186-b2bb-8d826877f196) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/device-capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/device-capabilities/device-capabilities-overview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7296a688-85f0-4941-b744-457f153cba70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/device-capabilities/location-capability.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b67283e-0efd-4629-b304-f0b8733660fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/mobile-camera-image-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/device-capabilities/mobile-camera-image-permissions.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e513a41-483d-45ac-baa3-9eb04a27d17b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f04e8f8c68e720fbffa4c327e87974e76f177fcf/msteams-platform/concepts/device-capabilities/people-picker-capability.md) | 84 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd3176c8-5735-4b2f-a696-4cf2f77fe8b3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-leenagopal** [comment]
Closing the PR due to conflict issues.

**Comment by v-leenagopal** [comment]
Closing the PR due to conflict.

**Pull request closed without merging**
