### PR TITLE
[Doc Improvement][Meeting apps mobile images][2707126]

### PR DESCRIPTION
**Pull request by v-ypalikila**
updated mobile images for meeting apps.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba3ed96a1c2ce36d5219db46d036920e23a78840/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66c34134-8589-4d09-abe3-d8727ea68033) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba3ed96a1c2ce36d5219db46d036920e23a78840/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7fb01daf-b1f4-42f8-9298-03737f43bb63) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba3ed96a1c2ce36d5219db46d036920e23a78840/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b01a71d0-f406-460d-879d-041a5aa46fbf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15a0568a099efc70d0ead29d3f46985108ad96bf/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/977d2a18-9ebe-493b-b1f4-b9a2c593cef8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15a0568a099efc70d0ead29d3f46985108ad96bf/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/728bd349-cb95-4fbc-8b92-0279f79d40d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15a0568a099efc70d0ead29d3f46985108ad96bf/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cf9a195-a217-4bac-98b2-a813b982a70e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e0e259b6cb74418147c7a2596cf04a01af0cdb0/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b325e37-49e4-4ac4-8614-46feaafb2382) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e0e259b6cb74418147c7a2596cf04a01af0cdb0/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57fef444-5488-4fee-b7ea-465d688b1209) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e0e259b6cb74418147c7a2596cf04a01af0cdb0/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21d2d648-6161-436c-99e5-eaa6a04a8675) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbb1fd1852c6262eaeb863a15770671b08e4d626/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/427d9a98-a37d-44b6-9155-44f37375aa73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbb1fd1852c6262eaeb863a15770671b08e4d626/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/044efdd3-e7c8-436e-9e20-1866e7db57c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbb1fd1852c6262eaeb863a15770671b08e4d626/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33272f2f-b1f9-4372-a1c8-9ec6b3988d65) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f9b0fd84c96c36c3a0e0167e42b258b060578fb6/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71789f6e-5343-4679-9034-ee1b2f5696b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f9b0fd84c96c36c3a0e0167e42b258b060578fb6/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ebfc15d5-d0e8-4c35-95b2-678ecc136061) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f9b0fd84c96c36c3a0e0167e42b258b060578fb6/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/714c547f-e5a2-4771-9c5f-126c3147ef51) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/920273e79dda3492ee341032be85a9bda229c88c/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9d4208e-094e-433a-8833-f6ae7e245da0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/920273e79dda3492ee341032be85a9bda229c88c/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d361c037-b650-4f95-837d-a914d49eeb0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/920273e79dda3492ee341032be85a9bda229c88c/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d979c6c-1034-4f5b-b300-b9caa3b578bf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/300c665cd7fbb42411ffafcbd9c6fb80d7d4c130/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66595b31-6f36-4e93-a380-bd448688725c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/300c665cd7fbb42411ffafcbd9c6fb80d7d4c130/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96def491-ef48-46d9-a610-cb723a0b7fbe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/300c665cd7fbb42411ffafcbd9c6fb80d7d4c130/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97582c41-766d-40b9-9cb1-0eacde92b18e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8a4fe69531afff4aeda7e9024e4940c55a277d2c/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc4a973b-7773-4b03-b16e-73076bc58f0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8a4fe69531afff4aeda7e9024e4940c55a277d2c/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67eda7ae-e402-46e7-b1e8-92b1bdb7b351) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8a4fe69531afff4aeda7e9024e4940c55a277d2c/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/990722fd-39f1-4d78-9477-abeed235da63) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/52c379b748a33272221489a15e6bed3f98c40c64/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c38c1ff1-8a90-4daf-a422-6410b97d935d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/52c379b748a33272221489a15e6bed3f98c40c64/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c40c047-6e7c-47b5-80ee-c3eceb78e6d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/52c379b748a33272221489a15e6bed3f98c40c64/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b5ac2b2-97ae-44b2-b845-adb5bcdc96d7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea8d1f63807b9f0a4daa0210054e154959f48152/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 93 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68188cbb-f4e2-41e0-9ad8-accf033d4bb5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea8d1f63807b9f0a4daa0210054e154959f48152/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e7b0252-9cd1-43e1-8d5c-feffb01b075b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea8d1f63807b9f0a4daa0210054e154959f48152/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3363b0d2-fedb-4099-b2c9-8ba7ed842d88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea8d1f63807b9f0a4daa0210054e154959f48152/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd2ed9c8-097d-41c3-928c-8ba12005e80d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea8d1f63807b9f0a4daa0210054e154959f48152/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8e90e82-ce8a-4fa3-9e73-ae17c44b854a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668cd76ef14924f25fb5b58c977d72a3447d7623/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 93 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af3e3ba6-2b72-466b-98f0-09790ac4decd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668cd76ef14924f25fb5b58c977d72a3447d7623/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/873a761a-a6b3-4361-ae74-902fbf589c0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668cd76ef14924f25fb5b58c977d72a3447d7623/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8f48ccd-e762-475c-a192-f0e313631aac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668cd76ef14924f25fb5b58c977d72a3447d7623/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9a61760-0c6e-4e88-aea9-ef478f6abbf3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668cd76ef14924f25fb5b58c977d72a3447d7623/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47d2ddc3-460b-4f64-b1c9-af214bbff4c1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
