### PR TITLE
[Doc Improvement][Validating docs as per MSTP][2471028]

### PR DESCRIPTION
**Pull request by v-dreddipogu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f284516c9d711cf7546de0ef43675ad8be55ada7/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68b9b37b-d286-453f-9591-5fb17214b409) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f284516c9d711cf7546de0ef43675ad8be55ada7/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6e8a88b-c159-43d6-9374-e7c5f52a879a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f284516c9d711cf7546de0ef43675ad8be55ada7/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dbe14e4-43f0-4909-b826-db81e9087010) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f284516c9d711cf7546de0ef43675ad8be55ada7/msteams-platform%2Fsbs-send-proactive.yml) | 88 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/591a1a7a-4a4b-4fbc-a007-e85ef79c07a7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f284516c9d711cf7546de0ef43675ad8be55ada7/msteams-platform%2Fsbs-tab-device-permissions.yml) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69196cae-7f7f-41cb-9b73-8b62de374ae6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f284516c9d711cf7546de0ef43675ad8be55ada7/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/719fa447-5a5f-4de9-a93b-634787fe3912) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f284516c9d711cf7546de0ef43675ad8be55ada7/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 82 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19bd3dd1-5e66-407f-aff2-9ae0c2f62a91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f284516c9d711cf7546de0ef43675ad8be55ada7/msteams-platform%2Fsbs-teams-connectors.yml) | 79 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a42ae431-d9a9-44df-b07b-8373ad22eec5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — DISMISSED** [review]
Approved

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/471f218e6f554ea06196e84e21810382009a9fe5/msteams-platform%2Foverview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc2ebf7e-f5de-4127-bd3c-1cf27aeef978) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/471f218e6f554ea06196e84e21810382009a9fe5/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73605d1e-6fee-4e05-9cf9-6322571b8bd3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/471f218e6f554ea06196e84e21810382009a9fe5/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd9b2633-d899-4096-9b70-01d82170dddf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/471f218e6f554ea06196e84e21810382009a9fe5/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d309c55-0607-47ce-8e94-473c9c416c80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/471f218e6f554ea06196e84e21810382009a9fe5/msteams-platform%2Fsbs-send-proactive.yml) | 88 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5243c0e7-4d93-4666-ab0b-0801f16bd87c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/471f218e6f554ea06196e84e21810382009a9fe5/msteams-platform%2Fsbs-tab-device-permissions.yml) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b2086ed-e6f6-4688-819f-17279598314c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/471f218e6f554ea06196e84e21810382009a9fe5/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82b91522-1c4f-4e67-9e6c-de3db85adeaa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/471f218e6f554ea06196e84e21810382009a9fe5/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 82 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff9ada9a-28a1-4730-8561-5394784157f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/471f218e6f554ea06196e84e21810382009a9fe5/msteams-platform%2Fsbs-teams-connectors.yml) | 79 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04330156-bca0-42f1-b368-d9bbe191a4fe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/536748db6e8643ae5e177e5349a9d93f66400350/msteams-platform%2Foverview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c263b20e-f962-4b7d-a217-12a71ab2ef36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/536748db6e8643ae5e177e5349a9d93f66400350/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4dcb9821-720f-4e6a-9a8d-5e51b2f593cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/536748db6e8643ae5e177e5349a9d93f66400350/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/debd8265-8d87-4043-a9a4-e37ab35c2b47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/536748db6e8643ae5e177e5349a9d93f66400350/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5aded9b4-e186-49cd-acb5-50dcd619c34e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/536748db6e8643ae5e177e5349a9d93f66400350/msteams-platform%2Fsbs-send-proactive.yml) | 88 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5eadafaa-b015-43d6-90db-cc9ac0fc88de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/536748db6e8643ae5e177e5349a9d93f66400350/msteams-platform%2Fsbs-tab-device-permissions.yml) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e42252b-04e5-4213-85fc-4b98c501bef0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/536748db6e8643ae5e177e5349a9d93f66400350/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/459a96f9-69d8-49c3-b15d-6fd71bc2f6a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/536748db6e8643ae5e177e5349a9d93f66400350/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 82 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee71c880-e460-4b6e-b929-640c1a8fe939) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/536748db6e8643ae5e177e5349a9d93f66400350/msteams-platform%2Fsbs-teams-connectors.yml) | 84 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68382136-b255-4fb2-8572-9097149ce6b1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3234c16121a17acd7bc25d70a58cc0dae9eba7ee/msteams-platform%2Foverview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05194b81-c2ff-42f4-90d5-6bc43e42a9fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3234c16121a17acd7bc25d70a58cc0dae9eba7ee/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf7fc72e-5054-45b8-bcbc-dc4806271910) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3234c16121a17acd7bc25d70a58cc0dae9eba7ee/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3ad0718-a182-40d0-be6c-680d2a7c1f7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3234c16121a17acd7bc25d70a58cc0dae9eba7ee/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d50a2954-2544-4983-a9b3-211504ac90bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3234c16121a17acd7bc25d70a58cc0dae9eba7ee/msteams-platform%2Fsbs-send-proactive.yml) | 88 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa8eba53-49e0-4d72-bf3d-33bbdbe13a4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3234c16121a17acd7bc25d70a58cc0dae9eba7ee/msteams-platform%2Fsbs-tab-device-permissions.yml) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c80d059-23ab-4351-a22d-6bdfea187cda) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3234c16121a17acd7bc25d70a58cc0dae9eba7ee/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6cd7e24-b880-40e9-8696-7c9959aa3f59) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3234c16121a17acd7bc25d70a58cc0dae9eba7ee/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 82 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d155352-413e-4e1d-9d91-2c6f0222107f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3234c16121a17acd7bc25d70a58cc0dae9eba7ee/msteams-platform%2Fsbs-teams-connectors.yml) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbc50312-20bc-40ef-a544-15c9ea18b266) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1fafcdb0f3e14cfb92f243f4dd7664ad794e7921/msteams-platform%2Foverview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70884e2d-3b5e-4ce9-abe5-1f2699eed222) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1fafcdb0f3e14cfb92f243f4dd7664ad794e7921/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a62c9f9e-fcec-4b2b-90c7-8798fa71fae7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1fafcdb0f3e14cfb92f243f4dd7664ad794e7921/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86079be9-9e0a-4114-8479-043bd7fd0ab6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1fafcdb0f3e14cfb92f243f4dd7664ad794e7921/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ca99ce7-300c-4d2d-85b6-c736d5cb9d3b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1fafcdb0f3e14cfb92f243f4dd7664ad794e7921/msteams-platform%2Fsbs-send-proactive.yml) | 88 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5031c8f-6dca-4f8f-97c2-e5c9aa977732) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1fafcdb0f3e14cfb92f243f4dd7664ad794e7921/msteams-platform%2Fsbs-tab-device-permissions.yml) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/378fe014-cdd9-4b61-bf45-8b1c077c4548) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1fafcdb0f3e14cfb92f243f4dd7664ad794e7921/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95c47b6d-f6ce-4a22-9991-18cb805997c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1fafcdb0f3e14cfb92f243f4dd7664ad794e7921/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 82 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4fd6705-c2e3-4713-b41c-2d53ab7978a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1fafcdb0f3e14cfb92f243f4dd7664ad794e7921/msteams-platform%2Fsbs-teams-connectors.yml) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff0c1b84-fe84-470b-9bf6-7254c42b2425) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35af79625afb843fcfd2c1f0605a6dc91dd58eb0/msteams-platform%2Foverview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fca7fd4-f430-48a0-97e6-b43151699e26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35af79625afb843fcfd2c1f0605a6dc91dd58eb0/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b44d7bc9-42c9-44bb-9ceb-1a8a6f67eb1a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35af79625afb843fcfd2c1f0605a6dc91dd58eb0/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2746764e-d594-44e2-b313-6f4598d7c733) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35af79625afb843fcfd2c1f0605a6dc91dd58eb0/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/487186c3-9583-4d38-881e-f035025c571b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35af79625afb843fcfd2c1f0605a6dc91dd58eb0/msteams-platform%2Fsbs-send-proactive.yml) | 88 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f22423f-d847-49df-9068-f13646a15e33) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35af79625afb843fcfd2c1f0605a6dc91dd58eb0/msteams-platform%2Fsbs-tab-device-permissions.yml) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f203b73-2d83-4b8d-83ba-2326b0aeb8a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35af79625afb843fcfd2c1f0605a6dc91dd58eb0/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3af091db-cd38-41ea-a6d8-42c8249a63fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35af79625afb843fcfd2c1f0605a6dc91dd58eb0/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 82 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/865284f2-15d0-4aa0-a9ec-8ac6c04527d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35af79625afb843fcfd2c1f0605a6dc91dd58eb0/msteams-platform%2Fsbs-teams-connectors.yml) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd73c4d1-56a0-4d69-a7a5-e74b883ca877) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a45c9af08f3ffa129fe147bd26199c95205636b5/msteams-platform%2Foverview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb9d50ac-fb65-42ff-b0d1-a6c603016e59) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a45c9af08f3ffa129fe147bd26199c95205636b5/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da7b4716-fea7-4723-a788-19720aa3efd2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a45c9af08f3ffa129fe147bd26199c95205636b5/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1415fe0f-fc2f-4acb-9c7e-eca4da0e7b3b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a45c9af08f3ffa129fe147bd26199c95205636b5/msteams-platform%2Fsbs-meetings-stage-view.yml) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43cd190b-653d-405b-b1c5-c4b75e5d0a19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a45c9af08f3ffa129fe147bd26199c95205636b5/msteams-platform%2Fsbs-send-proactive.yml) | 88 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09eff39c-0c52-4973-a5db-cf618dc6d29d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a45c9af08f3ffa129fe147bd26199c95205636b5/msteams-platform%2Fsbs-tab-device-permissions.yml) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e7642a8-a2b7-4696-9d69-a46b02240ffd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a45c9af08f3ffa129fe147bd26199c95205636b5/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/504aafde-eb0e-45ef-854d-50d5d50c2294) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a45c9af08f3ffa129fe147bd26199c95205636b5/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 82 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95186dd3-ef70-421d-b5f4-e9c5c1a2aea0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a45c9af08f3ffa129fe147bd26199c95205636b5/msteams-platform%2Fsbs-teams-connectors.yml) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77dc9899-533f-4b31-b321-9dabfa1875a4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
