### PR TITLE
[Doc Improvement][Link unfurling note on commands]

### PR DESCRIPTION
**Pull request by v-ramyas5**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3ead7bfa13b771c6d874b332410494536776d4ed/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffb7c3f9-18e2-4b0c-933b-3924746520f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3ead7bfa13b771c6d874b332410494536776d4ed/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 86 | 115 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb501fc1-bb6b-443b-98b9-627a2f2ae5ef) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e135052af3894a481043d0ff71c420b927b3eee/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a0384e9-9a3d-41fd-8755-24027954b022) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e135052af3894a481043d0ff71c420b927b3eee/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 86 | 115 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3a272dc-84ca-43bd-a614-585899eaea6d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b32bac3ab4feb1641e05688324a4f27ed91c62ba/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44e553d7-d4da-4885-809b-c5be99f4e25c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b32bac3ab4feb1641e05688324a4f27ed91c62ba/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 86 | 115 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06b5ab5d-5d76-4b32-84cb-bb8b43ebba46) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31a25f448dd25ccd3247095d39dceb467eb0deed/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4fad785c-8e67-4cb7-a7f4-f7b141344b81) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31a25f448dd25ccd3247095d39dceb467eb0deed/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 86 | 115 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f920dd7-bd27-438a-8783-77823f813810) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6299f4fe2e220a1adca6e7a8f46aa95c26d5320/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c69a37cb-9def-4017-92be-3cc309e2eee0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6299f4fe2e220a1adca6e7a8f46aa95c26d5320/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 86 | 115 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18afef95-4924-4db0-8832-41fd829a2ad5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ccff758a7caa5f09e622d8d11368a779ff60c534/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2ed780e-db58-4c39-b909-03ded73ae1d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ccff758a7caa5f09e622d8d11368a779ff60c534/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 86 | 115 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/222a3faf-2966-4b09-908f-ebc600fe97e4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63c68820b5cbe4f69c170c5832ef207864ae3e4f/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b1abfc5-e761-45e5-8b67-57f0f6a84b69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63c68820b5cbe4f69c170c5832ef207864ae3e4f/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 87 | 109 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9389b25e-b5ea-4214-be83-3d2c7b72325e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by V-bvishnu5 — APPROVED** [review]
Approved.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/469e150ef900e4417f83f6e15da604ada9957f71/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef4b8edf-53de-4f3d-a64f-a14903836d50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/469e150ef900e4417f83f6e15da604ada9957f71/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 87 | 109 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c38596b5-9cb6-4810-8f2b-064938d00cba) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
