### PR TITLE
[Doc Improvement][SBS hello world with JavaScript message extension][2689561]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab9909cd8f5f245a08ffb275a0bc7f1344d65cbc/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46183b1c-aa14-4a1e-ad3f-e05777ffe423) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c4ae63b0f6e59a49ed81c72f7a08ba8e9f7e6ec5/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca2e0a63-57c8-4a64-979f-a8a1ff7e9988) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aedc9c9a0d134efaaafef1354476882c7b471a3c/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01281a06-7c30-444d-9b19-09c10c3e439c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bb86dbd29c4880251fc44959934d6bf20843c5f7/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9630f569-b9cf-45a0-8141-9d0fde82e845) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
