### PR TITLE
Doc Improvement][Teams 2.1 update][3460800]

### PR DESCRIPTION
**Pull request by v-vanv**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-blazorupdate-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/abe8c2ac662cc58f77b63b01ecfe712f2d828aa2/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-blazorupdate-v4.yml) | 90 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9bce4e78-b41f-4d9d-bef6-35aa286c904c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-blazorupdate-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f18c6bd10de153715904329e31e33e4eda0052f4/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-blazorupdate-v4.yml) | 90 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e795d5e-64f9-4e20-ace6-e3497c315efd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-blazorupdate-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/588a54685f24ccfcd090a8d36efc49aecf4af161/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-blazorupdate-v4.yml) | 90 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba54f014-2b9b-48bd-9d81-e917ef06beb0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-blazorupdate-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/16cd0643b16c629df9f222bd987b49e40be84b34/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-blazorupdate-v4.yml) | 89 | 75 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91ef9b79-aac1-48bc-9c75-c6d5310a9d81) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
