### PR TITLE
Buildbots-revamp-activity

### PR DESCRIPTION
**Pull request by v-silakshmi**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/699737e8cd85080aa363a6b16bbe29d9cd40f59a/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cd443d4-ed68-4e68-8c41-4836daf53431) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by yong-sea** [comment]
get out!
dont steal my email anymore!
________________________________
发件人: opbld30 ***@***.***>
发送时间: 2022年4月23日 9:26
收件人: MicrosoftDocs/msteams-docs ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [MicrosoftDocs/msteams-docs] Buildbots-revamp-activity (PR #5779)


Docs Build status updates of commit 699737e<https://github.com/MicrosoftDocs/msteams-docs/commits/699737e8cd85080aa363a6b16bbe29d9cd40f59a>:

✅ Validation status: passed
File    Status  Preview URL     Details
msteams-platform/assets/images/invokebotwithcard.png<https://github.com/MicrosoftDocs/msteams-docs/blob/buildbots-revamp-images/msteams-platform/assets/images/invokebotwithcard.png>   ✅Succeeded      View<https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-5779>
msteams-platform/assets/images/invokebotwithtext.png<https://github.com/MicrosoftDocs/msteams-docs/blob/buildbots-revamp-images/msteams-platform/assets/images/invokebotwithtext.png>   ✅Succeeded      View<https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-5779>
msteams-platform/bots/what-are-bots.md<https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/bots/what-are-bots.md>  ✅Succeeded      View<https://review.docs.microsoft.com/en-us/microsoftteams/platform/bots/what-are-bots?branch=pr-en-us-5779>

For more details, please refer to the build report<https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C23%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202204230925549175-5779%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-24T09%3A26%3A31Z&sr=b&sp=r&sig=oJbzjLc04h5ikJErCrgEyMo92MizXG%2FrSBX%2F040BMWo%3D>.

Note: Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the broken link report<https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks>.

For any questions, please:

  *   Try searching the docs.microsoft.com contributor guides<https://review.docs.microsoft.com/en-us/help/?branch=main>
  *   Post your question in the Docs support channel<https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47>

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cb0830d563771e7f9bebdd714049a0a930c698b/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 86 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d84218b9-4789-4474-bf3f-4fa83a55a548) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cb0830d563771e7f9bebdd714049a0a930c698b/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c64855b8-faef-4241-97c3-8a2b6f3a838f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cb0830d563771e7f9bebdd714049a0a930c698b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1e6e396-d3b1-4c74-973e-bdd6d59b9434) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cb0830d563771e7f9bebdd714049a0a930c698b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b9f9dc0-10f4-48de-bcd3-51ba798e52bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cb0830d563771e7f9bebdd714049a0a930c698b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d7051a9-9b93-4f52-bfcd-e6678339caa0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cb0830d563771e7f9bebdd714049a0a930c698b/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1495544-8e47-4ebc-8457-cc100d521a69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cb0830d563771e7f9bebdd714049a0a930c698b/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b26890a4-6018-4792-acaa-e6dd4ff806fa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63967cb9c120c407773790af29f286ce5446b143/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 86 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53f754f3-b10f-441d-b705-48592a5aeb71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63967cb9c120c407773790af29f286ce5446b143/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07d8e395-f7c3-4d7c-9222-ed315ae11f9b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63967cb9c120c407773790af29f286ce5446b143/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffb849c9-5bd4-43ef-a037-0744165213e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63967cb9c120c407773790af29f286ce5446b143/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/971fc7ea-78ca-455d-8f84-6c0bebb21e1b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63967cb9c120c407773790af29f286ce5446b143/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e10fbdb3-c405-4957-8f45-9f85eb1d5728) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63967cb9c120c407773790af29f286ce5446b143/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/062c7e57-b83a-4120-bc7a-e789a379d4e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63967cb9c120c407773790af29f286ce5446b143/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ee4ed63-0a79-41ca-a7c5-b5aaf70f234b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/801c19ce3d212c65b3725f1b71ddd04356ab2324/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 86 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ca7db63-0923-4ef8-a347-3558ac25bf2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/801c19ce3d212c65b3725f1b71ddd04356ab2324/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9589846e-cf87-4ff1-9ac3-a9671849ebc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/801c19ce3d212c65b3725f1b71ddd04356ab2324/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc0b3ff8-259e-4890-bcc2-1d94c8012f1b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/801c19ce3d212c65b3725f1b71ddd04356ab2324/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8d00c38-6fd0-4b15-8e29-23f6ef8fdf8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/801c19ce3d212c65b3725f1b71ddd04356ab2324/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1cbda379-0370-43b2-8e69-3887997cd26e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/801c19ce3d212c65b3725f1b71ddd04356ab2324/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8ed52c1-511f-4471-8d8f-c18a8316e5cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/801c19ce3d212c65b3725f1b71ddd04356ab2324/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfe94c73-445f-4ca8-9a7c-240d05130176) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d290e0e07436bf53f8e6b2cec111b9988abe1c75/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 86 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af8cab9b-2cc2-46dc-b845-28bde8134926) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d290e0e07436bf53f8e6b2cec111b9988abe1c75/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cac8b191-9b28-4417-ad62-1257ed311c5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d290e0e07436bf53f8e6b2cec111b9988abe1c75/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e17f9d8d-b27c-4ef2-b2f1-4544cd2480e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d290e0e07436bf53f8e6b2cec111b9988abe1c75/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cacb5cfb-df0c-4d62-8984-2ea1007f319e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d290e0e07436bf53f8e6b2cec111b9988abe1c75/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 88 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80960797-64b5-4ae3-ad1e-0abcd0ded3e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d290e0e07436bf53f8e6b2cec111b9988abe1c75/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73f12941-049f-4005-bc65-4c19efd888d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d290e0e07436bf53f8e6b2cec111b9988abe1c75/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a075bcc8-f0ea-46e9-9173-f31a1df8728f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
