### PR TITLE
[Doc Feature][Revised Tools Manual-2]

### PR DESCRIPTION
**Pull request by v-rpatkur**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a4caaa930c8d1a7a5c0b63b94d7c09719c71514/msteams-platform/toolkit/add-resource.md) | 88 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b187623-ca6c-499f-bea3-44dbc33b2ac7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a4caaa930c8d1a7a5c0b63b94d7c09719c71514/msteams-platform/toolkit/provision.md) | 83 | 101 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1c1b096-4681-4c27-8607-5931e73d8e15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a4caaa930c8d1a7a5c0b63b94d7c09719c71514/msteams-platform/toolkit/use-CICD-template.md) | 83 | 65 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e466dcff-edea-48ae-a5db-3988dc4ae892) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by xzf0587 — DISMISSED** [review]
looks good for key vault part

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35103bd07259e857448b76a82e9f300718023961/msteams-platform/toolkit/add-resource.md) | 87 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d78e211-e294-4b84-b1a3-964ccc2386e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35103bd07259e857448b76a82e9f300718023961/msteams-platform/toolkit/provision.md) | 85 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ea6969c-50b0-4520-ad51-f593135d356f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35103bd07259e857448b76a82e9f300718023961/msteams-platform/toolkit/use-CICD-template.md) | 83 | 65 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d563e4a1-b858-4dc4-ba04-cc9668fb9038) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-rpatkur** [comment]
Closing the PR.

**Pull request closed without merging**
