### PR TITLE
[Doc Improvement][Acro Score Improvement-VSC Documents3][ADO-2438788]

### PR DESCRIPTION
**Pull request by v-psambrani**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9aac1cbde882996fba7e75195a0cd113e947b7f6/msteams-platform%2Fsbs-send-proactive.yml) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec74811e-a611-4f62-b0d2-e4f963ce134a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1e63665c9db6c2b031bb49f7a91046b8d1cfdcc4/msteams-platform%2Fsbs-send-proactive.yml) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92e40b29-d72e-444d-9113-d907ce7b3bbd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1e63665c9db6c2b031bb49f7a91046b8d1cfdcc4/msteams-platform%2Fsbs-tab-device-permissions.yml) | 88 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9a64e71-dced-4c4e-93a5-7d2d2c7cb35a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1e63665c9db6c2b031bb49f7a91046b8d1cfdcc4/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73bed2e8-4187-4bc8-8d60-d81d12ca14c1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/305bb62895b23ccb1822345791d1e17070276b58/msteams-platform%2Fsbs-send-proactive.yml) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/117f42b4-6663-49bb-88fc-e11bc9629f24) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/305bb62895b23ccb1822345791d1e17070276b58/msteams-platform%2Fsbs-tab-device-permissions.yml) | 88 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8ee967a-6421-476e-be67-e3b1268d5a85) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/305bb62895b23ccb1822345791d1e17070276b58/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3934946-dd23-4ee2-84c7-00021cdecad0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/305bb62895b23ccb1822345791d1e17070276b58/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/885c30dd-02f4-4d9b-9a10-d26e60ffa54b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7800b174df92c837fa4ef154e56a5a75a567b9ac/msteams-platform%2Fsbs-send-proactive.yml) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c31b23c-839c-4704-ac0f-c5a442542321) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7800b174df92c837fa4ef154e56a5a75a567b9ac/msteams-platform%2Fsbs-tab-device-permissions.yml) | 88 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c901473-f3b6-4d67-8c90-23280d2ed35c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7800b174df92c837fa4ef154e56a5a75a567b9ac/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bf4009c-1749-4e0d-8099-1325ca016502) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7800b174df92c837fa4ef154e56a5a75a567b9ac/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e231f36-5f1b-410e-be49-c3ab12cddc90) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7800b174df92c837fa4ef154e56a5a75a567b9ac/msteams-platform%2Ftoolkit%2FTeamsFx-CLI.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c5c62de-1f3e-48c1-ac1c-0ce54937f828) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/54f43c6c479b1e9cd2de48cc18bf569fd58d2ff7/msteams-platform%2Fsbs-send-proactive.yml) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd13be1b-4b2e-4aa0-a740-70cc8f7cd90b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/54f43c6c479b1e9cd2de48cc18bf569fd58d2ff7/msteams-platform%2Fsbs-tab-device-permissions.yml) | 88 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eeb8ef90-0b49-450d-9373-6bfa7306fdda) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/54f43c6c479b1e9cd2de48cc18bf569fd58d2ff7/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdda4624-56ff-4f93-a190-d5ae5baceb46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/54f43c6c479b1e9cd2de48cc18bf569fd58d2ff7/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e08032d-d076-4457-9de4-0750bbb8ae76) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54f43c6c479b1e9cd2de48cc18bf569fd58d2ff7/msteams-platform%2Ftoolkit%2FTeamsFx-CLI.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81fb942b-97d5-44f8-bcfa-51e46edad8dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-code-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54f43c6c479b1e9cd2de48cc18bf569fd58d2ff7/msteams-platform%2Ftoolkit%2Fvisual-studio-code-overview.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85b89e09-25db-409d-8b52-81c0fb880051) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-code-tab-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54f43c6c479b1e9cd2de48cc18bf569fd58d2ff7/msteams-platform%2Ftoolkit%2Fvisual-studio-code-tab-sso.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be817a34-ea93-4e8a-a869-179742a8fe66) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d0b2507b4c222c55cd1336dcd16404f628986be5/msteams-platform%2Fsbs-send-proactive.yml) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b0c29c2-40f3-4b24-aec1-91d5a750f233) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d0b2507b4c222c55cd1336dcd16404f628986be5/msteams-platform%2Fsbs-tab-device-permissions.yml) | 88 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13142d33-17a2-414f-a3dc-f66df668bcfb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d0b2507b4c222c55cd1336dcd16404f628986be5/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0ca58a4-36c9-4f1f-84ae-e81b9e24df37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d0b2507b4c222c55cd1336dcd16404f628986be5/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62232766-fcd9-43e4-a8d1-4adbcc23d93f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d0b2507b4c222c55cd1336dcd16404f628986be5/msteams-platform%2Ftoolkit%2FTeamsFx-CLI.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d029b449-b7f3-494d-965e-47c396470b1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-code-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d0b2507b4c222c55cd1336dcd16404f628986be5/msteams-platform%2Ftoolkit%2Fvisual-studio-code-overview.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7f865bd-5943-4777-8e84-f655b03e3aeb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-code-tab-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d0b2507b4c222c55cd1336dcd16404f628986be5/msteams-platform%2Ftoolkit%2Fvisual-studio-code-tab-sso.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c025ea13-9586-4e8a-947a-92558b510af2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/86adec1eaa1de18bf1561d76bf41f40bd6511c21/msteams-platform%2Fsbs-send-proactive.yml) | 88 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ef536c6-6fa7-42ab-9401-83d978adc4ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/86adec1eaa1de18bf1561d76bf41f40bd6511c21/msteams-platform%2Fsbs-tab-device-permissions.yml) | 88 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/267e903d-f73f-41e6-a30a-cf93ac2228c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/86adec1eaa1de18bf1561d76bf41f40bd6511c21/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ce3c6fe-0b67-4520-88b2-59a0ffabf487) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/86adec1eaa1de18bf1561d76bf41f40bd6511c21/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57732e9b-ad00-430e-a57d-02d21a4a2dee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86adec1eaa1de18bf1561d76bf41f40bd6511c21/msteams-platform%2Ftoolkit%2FTeamsFx-CLI.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/feb6dcff-78c4-469f-ad82-e2d1fe34e650) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-code-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86adec1eaa1de18bf1561d76bf41f40bd6511c21/msteams-platform%2Ftoolkit%2Fvisual-studio-code-overview.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b46a9296-4582-4bc5-aace-3ec9e9df8738) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-code-tab-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86adec1eaa1de18bf1561d76bf41f40bd6511c21/msteams-platform%2Ftoolkit%2Fvisual-studio-code-tab-sso.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/202aca6b-e769-4bee-8f86-9155c5f487d3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
