### PR TITLE
[BrokenLinksH2] Fix path in link

### PR DESCRIPTION
**Pull request by DhurataJ**
Fixing the path link. Removed .md

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/create-messaging-extension-using-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd59f59f958f3599a1a22feecc82a43095145289/msteams-platform/resources/create-messaging-extension-using-appstudio.md) | 81 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfcfd814-6dd3-4d9a-9aed-3d02b5926859) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by DhurataJ** [comment]
@tfosmark - Please can you verify and merge this PR!

**Review by v-habibaumme — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
