### PR TITLE
[Doc Improvement][Update Adaptive and SSO Bot Type]

### PR DESCRIPTION
**Pull request by v-sreenivasv**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/65c8b832de57d2d36d4bc921e49d9fcc242ff9ca/msteams-platform/sbs-tab-with-adaptive-cards.yml) | 89 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3bc2ed8a-caae-4806-a12e-b220083118e7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cb6f09a3fea893c3e11c8e0d66ce380b52720a82/msteams-platform/sbs-bots-with-sso.yml) | 87 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/632f84a2-cd9e-4aab-a554-de8b2800989f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cb6f09a3fea893c3e11c8e0d66ce380b52720a82/msteams-platform/sbs-tab-with-adaptive-cards.yml) | 89 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a13091fc-2f55-4d3a-918b-dc89243ed9d6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a47ee1643738e166ee8dfd27d29e014c9264d392/msteams-platform/sbs-bots-with-sso.yml) | 87 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6da84733-e6d1-4437-ac5e-4fe02ffb82fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a47ee1643738e166ee8dfd27d29e014c9264d392/msteams-platform/sbs-tab-with-adaptive-cards.yml) | 89 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6daf222-a922-4725-a547-5a9669082e78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a47ee1643738e166ee8dfd27d29e014c9264d392/msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml) | 87 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffc24abb-1b4b-4652-ac9c-350772af6bfb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a4094430f9d0c4b7ee751368fc04cb7234eef917/msteams-platform/sbs-bots-with-sso.yml) | 87 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/559c40e1-d0de-4bfd-9ffd-49ddec3731c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a4094430f9d0c4b7ee751368fc04cb7234eef917/msteams-platform/sbs-tab-with-adaptive-cards.yml) | 88 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/910868c5-d8a3-4be7-8953-2c14757e8077) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a4094430f9d0c4b7ee751368fc04cb7234eef917/msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml) | 87 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a94d7e2d-d898-4778-877a-c708de181792) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
