### PR TITLE
[Doc-Enhancement][AAD procedures]

### PR DESCRIPTION
**Pull request by v-shalinirobinson**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b3b313c72d2a6095449532529c1b8b621c95c4c2/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13d52e3a-9427-4a22-a35a-08e4f71675f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/aad/bot-resource-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b3b313c72d2a6095449532529c1b8b621c95c4c2/msteams-platform%2Fincludes%2Faad%2Fbot-resource-aad.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6f30de8-37c4-4e91-ba56-81cdb38be295) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/aad/register-on-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b3b313c72d2a6095449532529c1b8b621c95c4c2/msteams-platform%2Fincludes%2Faad%2Fregister-on-aad.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cea16191-507d-496d-9b29-5b59411d467b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/39c42289810db6791eb5d99106c338c2fa56ecc2/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40fb32ad-0b21-4eea-9e62-7750665d8d17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/bot-resource-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39c42289810db6791eb5d99106c338c2fa56ecc2/msteams-platform%2Fconcepts%2Faad%2Fbot-resource-aad.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13d684b1-d206-441c-a414-28b87b1a0c9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/register-on-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39c42289810db6791eb5d99106c338c2fa56ecc2/msteams-platform%2Fconcepts%2Faad%2Fregister-on-aad.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91e506e7-365c-4071-af6d-3acff8f79e88) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/98215eb013f80151e68beea5573568a23ffecd0c/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48c4eab4-9f7b-4256-8b62-4c54dbb1416a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/bot-resource-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98215eb013f80151e68beea5573568a23ffecd0c/msteams-platform%2Fconcepts%2Faad%2Fbot-resource-aad.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a752616-c560-4612-9ad6-13adb79e7983) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/register-on-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98215eb013f80151e68beea5573568a23ffecd0c/msteams-platform%2Fconcepts%2Faad%2Fregister-on-aad.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16d6ce9a-298a-4571-8b2b-1755ae53155d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/333072b2a0d8de9747e20bce2fbe340abb1315bc/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07f2a72d-6fdb-4b2f-a9f3-90a8786dcd4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/bot-resource-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/333072b2a0d8de9747e20bce2fbe340abb1315bc/msteams-platform%2Fconcepts%2Faad%2Fbot-resource-aad.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3729e131-dd5a-437b-9293-136caa32face) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/register-on-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/333072b2a0d8de9747e20bce2fbe340abb1315bc/msteams-platform%2Fconcepts%2Faad%2Fregister-on-aad.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8bc426e-0670-42f6-98d2-5f5513dbf8c2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3a5e0ff9fe254ed52105c098ebd0c19875d45172/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9347d59-0aa2-4c12-bdb0-a0ac91d2cb43) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/bot-resource-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3a5e0ff9fe254ed52105c098ebd0c19875d45172/msteams-platform%2Fconcepts%2Faad%2Fbot-resource-aad.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcd62da0-d694-4266-99e7-a2148894f640) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/register-on-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3a5e0ff9fe254ed52105c098ebd0c19875d45172/msteams-platform%2Fconcepts%2Faad%2Fregister-on-aad.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fec7b58-043c-455e-8460-826e99225245) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/47a9d284ee62cb6c13f628fef9e31cee6f468519/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/170fa1f4-2e3e-464f-aba5-2ff61137666e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/bot-resource-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47a9d284ee62cb6c13f628fef9e31cee6f468519/msteams-platform%2Fconcepts%2Faad%2Fbot-resource-aad.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e061378-a07d-494e-82d8-097cf57eee0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/register-on-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47a9d284ee62cb6c13f628fef9e31cee6f468519/msteams-platform%2Fconcepts%2Faad%2Fregister-on-aad.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53d5f0ef-d61b-4e15-8833-8d7db11f879f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/43a51b0b2e65ef00e10ad211974b7314ba30fe0f/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c4d058b-bad9-41c3-9f58-a996ae3916a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/bot-resource-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43a51b0b2e65ef00e10ad211974b7314ba30fe0f/msteams-platform%2Fconcepts%2Faad%2Fbot-resource-aad.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a22602bb-1e1d-4b5e-96dc-56f504877940) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/register-on-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43a51b0b2e65ef00e10ad211974b7314ba30fe0f/msteams-platform%2Fconcepts%2Faad%2Fregister-on-aad.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a0ca11b-3b9d-40f7-9c65-9a3936dda182) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6514179dac88e5c50a4031f964c0335ba21fa32d/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d642595-50a1-4a0c-b1ab-89dce7c3a809) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/bot-resource-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6514179dac88e5c50a4031f964c0335ba21fa32d/msteams-platform%2Fconcepts%2Faad%2Fbot-resource-aad.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9805227a-594c-4611-a256-c5c3ea2dbb31) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/register-on-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6514179dac88e5c50a4031f964c0335ba21fa32d/msteams-platform%2Fconcepts%2Faad%2Fregister-on-aad.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e01b36a5-58e7-475e-8af9-d7b6dcda85e1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c29a5f7966ad6f4acbc7476b5dceeab426e24a30/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/523c2744-f186-4293-8209-9b51afdf694b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/bot-resource-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c29a5f7966ad6f4acbc7476b5dceeab426e24a30/msteams-platform%2Fconcepts%2Faad%2Fbot-resource-aad.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/882111b2-66fd-4cd9-b63d-dc3f4c2cfe7f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/aad/register-on-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c29a5f7966ad6f4acbc7476b5dceeab426e24a30/msteams-platform%2Fconcepts%2Faad%2Fregister-on-aad.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3abfd18-820a-4017-80ca-55a3c757330b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-shalinirobinson** [comment]
Closed, to be taken up after revamp for Tools and SDK.

**Pull request closed without merging**
