### PR TITLE
 Updating removal handling section for connectors

### PR DESCRIPTION
**Pull request by pradeepananth**

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[af70776](https://github.com/pradeepananth/msteams-docs/pull/570/commits/af7077649e74fc80f5d01d0962dc91e5b175c85b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/connectors/connectors-creating.md](https://github.com/pradeepananth/msteams-docs/blob/connectors-handling-removals/msteams-platform/concepts/connectors/connectors-creating.md) | :warning:Warning | | [Details](#user-content-d9ea2145-3ccd7365)

<a id="d9ea2145-3ccd7365"></a>
### [msteams-platform/concepts/connectors/connectors-creating.md](https://github.com/pradeepananth/msteams-docs/blob/connectors-handling-removals/msteams-platform/concepts/connectors/connectors-creating.md)
 - **Line 13**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 13**: **[Warning]** Invalid file link:(~/publishing/apps-publish).
 - **Line 13**: **[Warning]** Invalid file link:(~/overview#apps-in-microsoft-teams).
 - **Line 20**: **[Warning]** Invalid file link:(~/publishing/apps-publish).
 - **Line 79**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package#icons).
 - **Line 137**: **[Warning]** Invalid file link:(~/concepts/connectors/connectors-using#setting-up-a-custom-incoming-webhook).
 - **Line 141**: **[Warning]** Invalid file link:(~/publishing/apps-publish).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904170509325164-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fLidoGRJgKqsNZ6s2eLztCJrWc1zDXnl5KWbybPZcG0%3D&st=2019-04-17T05%3A05%3A45Z&se=2019-05-18T05%3A10%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[582eb97](https://github.com/pradeepananth/msteams-docs/pull/570/commits/582eb97b9f5eab548636c1f9e2000d64ea4c386c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/connectors/connectors-creating.md](https://github.com/pradeepananth/msteams-docs/blob/connectors-handling-removals/msteams-platform/concepts/connectors/connectors-creating.md) | :warning:Warning | | [Details](#user-content-d9ea2145-d49ecacb)

<a id="d9ea2145-d49ecacb"></a>
### [msteams-platform/concepts/connectors/connectors-creating.md](https://github.com/pradeepananth/msteams-docs/blob/connectors-handling-removals/msteams-platform/concepts/connectors/connectors-creating.md)
 - **Line 13**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 13**: **[Warning]** Invalid file link:(~/publishing/apps-publish).
 - **Line 13**: **[Warning]** Invalid file link:(~/overview#apps-in-microsoft-teams).
 - **Line 20**: **[Warning]** Invalid file link:(~/publishing/apps-publish).
 - **Line 79**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package#icons).
 - **Line 137**: **[Warning]** Invalid file link:(~/concepts/connectors/connectors-using#setting-up-a-custom-incoming-webhook).
 - **Line 141**: **[Warning]** Invalid file link:(~/publishing/apps-publish).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904171716382843-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2Fb581LW2Wf%2Fg1KS%2BsuVWVgEtTYq2gmrOpcmrQjeR8o4%3D&st=2019-04-17T17%3A12%3A56Z&se=2019-05-18T17%3A17%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[af70776](https://github.com/pradeepananth/msteams-docs/pull/570/commits/af7077649e74fc80f5d01d0962dc91e5b175c85b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/connectors/connectors-creating.md](https://github.com/pradeepananth/msteams-docs/blob/connectors-handling-removals/msteams-platform/concepts/connectors/connectors-creating.md) | :warning:Warning | | [Details](#user-content-d9ea2145-af0cc5eb)

<a id="d9ea2145-af0cc5eb"></a>
### [msteams-platform/concepts/connectors/connectors-creating.md](https://github.com/pradeepananth/msteams-docs/blob/connectors-handling-removals/msteams-platform/concepts/connectors/connectors-creating.md)
 - **Line 13**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 13**: **[Warning]** Invalid file link:(~/publishing/apps-publish).
 - **Line 13**: **[Warning]** Invalid file link:(~/overview#apps-in-microsoft-teams).
 - **Line 20**: **[Warning]** Invalid file link:(~/publishing/apps-publish).
 - **Line 79**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package#icons).
 - **Line 137**: **[Warning]** Invalid file link:(~/concepts/connectors/connectors-using#setting-up-a-custom-incoming-webhook).
 - **Line 141**: **[Warning]** Invalid file link:(~/publishing/apps-publish).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904171843496934-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=EXf3iZNgknIazhBopSbSjiMt84Q4FitvY57aKh%2FwES4%3D&st=2019-04-17T18%3A40%3A07Z&se=2019-05-18T18%3A45%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[c595ada](https://github.com/pradeepananth/msteams-docs/pull/570/commits/c595ada7da8c3c10acb60aad2096212e25adb2dd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/connectors/connectors-creating.md](https://github.com/pradeepananth/msteams-docs/blob/connectors-handling-removals/msteams-platform/concepts/connectors/connectors-creating.md) | :warning:Warning | | [Details](#user-content-d9ea2145-e184f58e)

<a id="d9ea2145-e184f58e"></a>
### [msteams-platform/concepts/connectors/connectors-creating.md](https://github.com/pradeepananth/msteams-docs/blob/connectors-handling-removals/msteams-platform/concepts/connectors/connectors-creating.md)
 - **Line 13**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 13**: **[Warning]** Invalid file link:(~/publishing/apps-publish).
 - **Line 13**: **[Warning]** Invalid file link:(~/overview#apps-in-microsoft-teams).
 - **Line 20**: **[Warning]** Invalid file link:(~/publishing/apps-publish).
 - **Line 79**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package#icons).
 - **Line 137**: **[Warning]** Invalid file link:(~/concepts/connectors/connectors-using#setting-up-a-custom-incoming-webhook).
 - **Line 141**: **[Warning]** Invalid file link:(~/publishing/apps-publish).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904171847319828-570%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2FvmixlGIbDF85g4RnepSTWdrfJBKFRKbcTMJcrd4tPE%3D&st=2019-04-17T18%3A43%3A46Z&se=2019-05-18T18%3A48%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clearab** [comment]
@pradeepananth The note in this edit confuses me; if that SDK endpoint is unreliable are we fixing it?

**Pull request closed without merging**
