### PR TITLE
[Doc Improvement][Tools and SDK language review]

### PR DESCRIPTION
**Pull request by v-leenagopal**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/visual-studio-code-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c9e316a98d751afa7d308d2c32a23d50825c4183/msteams-platform/toolkit/visual-studio-code-overview.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de2184ee-33df-429c-9830-a42ab24bf345) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/visual-studio-code-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a04a5885207d8e0163305a8bf8ae9b019dbe74de/msteams-platform/toolkit/visual-studio-code-overview.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ca9fa89-ba37-498d-a063-bf20eab6336e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/visual-studio-code-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/084600b6ad4c8c77aaac0fbd9177617aadd966e9/msteams-platform/toolkit/visual-studio-code-overview.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10511440-a62d-4c7b-92b9-36b5ade73cf2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/visual-studio-code-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f26bdde3518677c622af80b001fd0ae42cbbda91/msteams-platform/toolkit/visual-studio-code-overview.md) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80be8f4f-7883-46b9-9516-32656da468ec) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/visual-studio-code-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eadf0950fcf57e1c54641235c44af748abc4aa94/msteams-platform/toolkit/visual-studio-code-overview.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c672fca6-46da-4a43-a695-780495e4c20e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/visual-studio-code-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18a0ba72b46b5053d39150b7cd83b25e02197943/msteams-platform/toolkit/visual-studio-code-overview.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a7f35d3-062f-4991-8dc6-9c984b262c79) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/visual-studio-code-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1f91cb75658d9ac915b1e18e6043532e1dc08f3/msteams-platform/toolkit/visual-studio-code-overview.md) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/030af123-ddf6-49f7-8073-87da0b5db562) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1f91cb75658d9ac915b1e18e6043532e1dc08f3/msteams-platform/toolkit/visual-studio-overview.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69e1d012-1c5c-49f8-aed8-6c68e28ea5cb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02867973eae2c4ec40a84ddba149a6bf39074bd2/msteams-platform/toolkit/teams-toolkit-fundamentals.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c63f593f-3059-41bc-8e9f-29f2359e49c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-code-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02867973eae2c4ec40a84ddba149a6bf39074bd2/msteams-platform/toolkit/visual-studio-code-overview.md) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2ca56b5-6ab1-4856-abe0-65a054368c95) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02867973eae2c4ec40a84ddba149a6bf39074bd2/msteams-platform/toolkit/visual-studio-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f766de8c-6c45-4192-a3ca-da7330d306a6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-leenagopal** [comment]
Closing PR as the content, language update is done on PR 5417.

**Pull request closed without merging**
