### PR TITLE
Coworker appreciation app template

### PR DESCRIPTION
**Pull request by adityachallapally**

### CODE REVIEW

**Review by surbhigupta12 — CHANGES_REQUESTED** [review]
Please verify and update the comments.

**Review by surbhigupta12 — APPROVED** [review]
Thank you for incorporating the comments. Approving the PR.

**Review by KirtiPereira — APPROVED** [review]
Approving the PR for merging.
Thank you.

**Review by surbhigupta12 — APPROVED** [review]
The changes seem fine. Approving the PR.

**Pull request merged**
