### PR TITLE
[Doc Improvement][Title metadata updated]

### PR DESCRIPTION
**Pull request by v-shalinir**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-canvas.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75170215ffd094af8945645723825bc652db596/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-canvas.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b650710d-742c-4ad2-b4ec-d65996c06240) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75170215ffd094af8945645723825bc652db596/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f43374f3-43bf-4444-882a-4800294ecdb5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/tool-sdk-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75170215ffd094af8945645723825bc652db596/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftool-sdk-overview.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4fb37a2-3684-4cdb-a19a-57822fae7dd0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75170215ffd094af8945645723825bc652db596/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2fe1de2-67f0-442d-bf4a-44610eec3baf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d75170215ffd094af8945645723825bc652db596/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 80 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42aa8ebf-2749-4a1f-a00a-1c6917df87a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d75170215ffd094af8945645723825bc652db596/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00bd2697-c233-40c6-a5b0-8c10f7eef9fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d75170215ffd094af8945645723825bc652db596/msteams-platform%2Fsbs-meeting-token-generator.yml) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/096357a4-7854-422c-99f3-c04446165e6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d75170215ffd094af8945645723825bc652db596/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83445943-1650-44af-b7ba-13cb59b50b9f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-canvas.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b542d16ebb92efefc209d8d16eb1e7380df0e5a/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-canvas.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dddb0f6b-8a12-4e45-8a56-4da0edb6b47e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b542d16ebb92efefc209d8d16eb1e7380df0e5a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87938c02-828c-4073-a372-939c4b4b6ce5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/tool-sdk-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b542d16ebb92efefc209d8d16eb1e7380df0e5a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftool-sdk-overview.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09f115c6-6e7b-44a5-8485-6920827f5f8b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b542d16ebb92efefc209d8d16eb1e7380df0e5a/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3620ff20-6a1b-458e-8949-b0496a5182d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0b542d16ebb92efefc209d8d16eb1e7380df0e5a/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 80 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a64aef02-3702-40b6-8420-9474752f4c58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0b542d16ebb92efefc209d8d16eb1e7380df0e5a/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be27f41c-046e-4ccc-83cf-942491fd07e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0b542d16ebb92efefc209d8d16eb1e7380df0e5a/msteams-platform%2Fsbs-meeting-token-generator.yml) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3648538e-1dcd-462f-b6de-b4dfb0baec8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0b542d16ebb92efefc209d8d16eb1e7380df0e5a/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3077c751-5802-4b48-bafd-b7e87eab0dd3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b542d16ebb92efefc209d8d16eb1e7380df0e5a/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-task-modules.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a377508-14cc-48b2-9964-ed56feb72628) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-canvas.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4394a9cd2105c8d32f7aeb97d5b7544a3503a1f/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-canvas.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a636d8f7-07a7-4a5d-81b0-3d28fdd3463c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4394a9cd2105c8d32f7aeb97d5b7544a3503a1f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cb857be-03d0-4d8b-9656-cfaa5ddb81bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/tool-sdk-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4394a9cd2105c8d32f7aeb97d5b7544a3503a1f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftool-sdk-overview.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56732547-e474-45db-9cf8-f07c5dc725b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4394a9cd2105c8d32f7aeb97d5b7544a3503a1f/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f3923f4-cf97-411b-bbbb-a1c7e076f95b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a4394a9cd2105c8d32f7aeb97d5b7544a3503a1f/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 80 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/976fa0b4-d645-449d-bdad-ce7a491bda71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a4394a9cd2105c8d32f7aeb97d5b7544a3503a1f/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e809d189-cd44-49f8-a908-e728c0917da9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a4394a9cd2105c8d32f7aeb97d5b7544a3503a1f/msteams-platform%2Fsbs-meeting-token-generator.yml) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93658d17-922b-4ea8-8845-c931aa544b27) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a4394a9cd2105c8d32f7aeb97d5b7544a3503a1f/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6973d05a-9b66-456b-976a-d300ba4265e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4394a9cd2105c8d32f7aeb97d5b7544a3503a1f/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-task-modules.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1414a4c2-2070-4905-99b8-4ac49cb6b1c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4394a9cd2105c8d32f7aeb97d5b7544a3503a1f/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ac9aa65-6ea7-4624-aca7-c6aa709a1c74) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-preethah — APPROVED** [review]
Approved.

**Review by Wajeed-msft — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-canvas.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae7cafeb5d92d0f3457842c88e9d115ebdec9bcd/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-canvas.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2283b7c0-bf58-4f96-b887-45c01d16339f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae7cafeb5d92d0f3457842c88e9d115ebdec9bcd/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4f6b886-77af-48a4-9bd7-7704b740b4ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/tool-sdk-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae7cafeb5d92d0f3457842c88e9d115ebdec9bcd/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftool-sdk-overview.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d8fa199-3120-4fe4-aad1-2058630aa1d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae7cafeb5d92d0f3457842c88e9d115ebdec9bcd/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/699147e3-3cf3-4390-8785-f459f4d6b784) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ae7cafeb5d92d0f3457842c88e9d115ebdec9bcd/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 80 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c77483de-50ed-4ede-8740-c2b00dfbc5cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ae7cafeb5d92d0f3457842c88e9d115ebdec9bcd/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67f12cfe-3d3b-41fa-a100-87515a4a2384) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ae7cafeb5d92d0f3457842c88e9d115ebdec9bcd/msteams-platform%2Fsbs-meeting-token-generator.yml) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b991411a-19cb-4e37-b9fa-722abfeee96a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ae7cafeb5d92d0f3457842c88e9d115ebdec9bcd/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15d56bd3-8cf9-4bae-8c63-e5038e6c4e94) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae7cafeb5d92d0f3457842c88e9d115ebdec9bcd/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-task-modules.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d106898-669a-4cac-8d23-769ae6ef0020) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae7cafeb5d92d0f3457842c88e9d115ebdec9bcd/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82747ee0-c213-4c1f-8241-2606fbe0f70c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
