### PR TITLE
[Doc Improvement][Upgrading minor grammatical mistakes][2720397]

### PR DESCRIPTION
**Pull request by v-spharish**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/common-reasons-for-app-validation-failure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/080edb7bf09123a7004f661f991a499348a3cb02/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fcommon-reasons-for-app-validation-failure.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58175a77-9d58-4bad-bf81-b8a8804f9532) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/common-reasons-for-app-validation-failure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/278c7aaa4a61f46c068f4f08efe6caa5a1753c39/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fcommon-reasons-for-app-validation-failure.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64ff55b8-162c-4027-a119-82d152e21998) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47af0ff2dce584ba76f39df4ce97c1eb080feab8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41a48c52-c458-4896-82ce-7536f70de1d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/common-reasons-for-app-validation-failure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47af0ff2dce584ba76f39df4ce97c1eb080feab8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fcommon-reasons-for-app-validation-failure.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6ecdcc7-8c5a-4158-a8ba-ea851e804ab2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d190909856d441649e113b91402d0f081fb6324/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d2c2a0b-3794-49f7-bccb-60598ac06d53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/common-reasons-for-app-validation-failure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d190909856d441649e113b91402d0f081fb6324/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fcommon-reasons-for-app-validation-failure.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e3099b6-048b-40b8-ae8c-54f99affe0aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d190909856d441649e113b91402d0f081fb6324/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8aeb9a30-30f0-4bb5-a17c-786d6e81bfd0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad7b691741733e4d7577a23e44c92d9a31f6c734/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69b20d81-6ed9-4872-b292-f4897a38870b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/test-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad7b691741733e4d7577a23e44c92d9a31f6c734/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-app-overview.md) | 88 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a587495-4cf2-4227-b26c-712090a4fa0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/common-reasons-for-app-validation-failure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad7b691741733e4d7577a23e44c92d9a31f6c734/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fcommon-reasons-for-app-validation-failure.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65c18e8b-a542-4ac5-985c-7e9b35c1314d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad7b691741733e4d7577a23e44c92d9a31f6c734/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63f8cfb9-28c8-432f-9a0c-16866c001e52) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18e2575d2fdb4f752580d0bb233722f0c00f361b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/097b9485-7692-49f4-9620-b297a564a70c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/test-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18e2575d2fdb4f752580d0bb233722f0c00f361b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-app-overview.md) | 88 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/082466f1-bd4e-4830-b799-f93c06cfd702) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/common-reasons-for-app-validation-failure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18e2575d2fdb4f752580d0bb233722f0c00f361b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fcommon-reasons-for-app-validation-failure.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c71e01c-e4cd-45f8-a73f-906b85828bd7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18e2575d2fdb4f752580d0bb233722f0c00f361b/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c71542e-48e1-4cf6-95b0-5cf3a39bd066) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/896cdd551dbc8f9db9d35d2d4789744f0efc2e89/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aab9c5e8-d77b-4ad4-9039-707bd3c0bf0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/test-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/896cdd551dbc8f9db9d35d2d4789744f0efc2e89/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-app-overview.md) | 88 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19844e01-a139-4a7e-84dc-fc5464c0e74a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/common-reasons-for-app-validation-failure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/896cdd551dbc8f9db9d35d2d4789744f0efc2e89/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fcommon-reasons-for-app-validation-failure.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd30e623-c7e3-4a90-bb38-a91f724aabde) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/896cdd551dbc8f9db9d35d2d4789744f0efc2e89/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b8954f9-1c7c-47fc-8f36-4bccdb33ce39) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0df606c2193b3b87e7e2562779f72b36130dea6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da810491-c13d-4c9c-8bd3-c672ebd08626) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/test-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0df606c2193b3b87e7e2562779f72b36130dea6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-app-overview.md) | 88 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67f5c9a5-6d5f-49be-bd3e-0ec4e1d6e782) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/common-reasons-for-app-validation-failure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0df606c2193b3b87e7e2562779f72b36130dea6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fcommon-reasons-for-app-validation-failure.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61822b5f-b05a-4efd-ba02-303c26900e2a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0df606c2193b3b87e7e2562779f72b36130dea6/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f78c8a7-4d2c-4ea2-92ef-0a17a8925ca5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
