### PR TITLE
[Doc Improvement][SEO title update 2][3942029]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3963e3a73a3201aa4407787843d0aaeab5dfaa5/msteams-platform%2Fbots%2Fbot-features.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9230af6-ddc8-4d03-9791-93fca283759f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3963e3a73a3201aa4407787843d0aaeab5dfaa5/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9be2e283-b2ed-47c9-a498-fedb1a8aab12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3963e3a73a3201aa4407787843d0aaeab5dfaa5/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-vs.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/821269fc-73ed-4818-a25d-4cfb25b2eff3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a3cf945f294a3593c10a07fd6b6437db66b1b49/msteams-platform%2Fbots%2Fbot-features.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e210ccb5-8bfd-4fb0-b6fd-aefddb90606e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a3cf945f294a3593c10a07fd6b6437db66b1b49/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0cd74f3c-3093-438e-9ebf-42afd931267c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a3cf945f294a3593c10a07fd6b6437db66b1b49/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-vs.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef79e825-76df-49b5-9d6c-a82f5cda0f92) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8daa1e3b700a52d3022866549fbf0a9fee3f9935/msteams-platform%2Fbots%2Fbot-features.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2fff0f4c-83f2-4207-99b5-c6e6caa2ab00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8daa1e3b700a52d3022866549fbf0a9fee3f9935/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ce13337-b6d6-4e4c-bcca-f319242b6382) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1d0d3ce1b28b771c1f245d5862755048a7deca8/msteams-platform%2Fbots%2Fbot-features.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78cb27ad-7443-4dc1-b2de-c6698f96c2c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/workflow-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1d0d3ce1b28b771c1f245d5862755048a7deca8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fworkflow-bot-in-teams.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30e096ad-b602-40f9-88c3-753a1bf929cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1d0d3ce1b28b771c1f245d5862755048a7deca8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-from-web-apps.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/351ac4a9-78d8-4048-8465-594b0830de46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1d0d3ce1b28b771c1f245d5862755048a7deca8/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc3b3ebc-993a-48ec-9079-6bb358b4e8ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1d0d3ce1b28b771c1f245d5862755048a7deca8/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-proactive.md) | 87 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2082498-8537-402d-96d3-3ebbb6304299) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1d0d3ce1b28b771c1f245d5862755048a7deca8/msteams-platform%2Fresources%2FmoodleInstructions.md) | 88 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38548ff4-87b2-4af3-9b2e-b9443e51707f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/partner-apps-for-moodle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1d0d3ce1b28b771c1f245d5862755048a7deca8/msteams-platform%2Fresources%2Fpartner-apps-for-moodle.md) | 82 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/997a5667-311c-4e2d-8942-199de6fdd6f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1d0d3ce1b28b771c1f245d5862755048a7deca8/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 87 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9231f12-98ed-4d3a-9f50-2f15e6610797) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Sequential-Workflows.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1d0d3ce1b28b771c1f245d5862755048a7deca8/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2FSequential-Workflows.md) | 87 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7253962-6813-4fcf-83f4-5a7d4a9df6d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1d0d3ce1b28b771c1f245d5862755048a7deca8/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03e1ac5a-731e-4833-995d-e0f3f8b439ee) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-preethah — DISMISSED** [review]
Approved.

**Review by Wajeed-msft — DISMISSED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6fab3c0076d9cbb81cbdef67434ab0e7080477a6/msteams-platform%2Fbots%2Fbot-features.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/586038da-d96d-46dd-8617-fed9665fbfc3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/workflow-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6fab3c0076d9cbb81cbdef67434ab0e7080477a6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fworkflow-bot-in-teams.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f2f201d-7a5c-4c06-bea0-67bf94af18ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6fab3c0076d9cbb81cbdef67434ab0e7080477a6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-from-web-apps.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a3a40d5-b1ac-4c9d-bb73-7289083d1191) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6fab3c0076d9cbb81cbdef67434ab0e7080477a6/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11c20ebe-db71-4724-943c-de4aa9c0e501) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6fab3c0076d9cbb81cbdef67434ab0e7080477a6/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-proactive.md) | 87 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ae0bc49-afe2-4922-9392-b67a453df982) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6fab3c0076d9cbb81cbdef67434ab0e7080477a6/msteams-platform%2Fresources%2FmoodleInstructions.md) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8054aef-1ecd-4fbb-a84d-0689563762a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/partner-apps-for-moodle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6fab3c0076d9cbb81cbdef67434ab0e7080477a6/msteams-platform%2Fresources%2Fpartner-apps-for-moodle.md) | 82 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9e2de4d-90ae-40c1-9e8e-37d13c894391) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6fab3c0076d9cbb81cbdef67434ab0e7080477a6/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 87 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3a4de87-9503-4746-9aed-513c83b7cfc7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Sequential-Workflows.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6fab3c0076d9cbb81cbdef67434ab0e7080477a6/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2FSequential-Workflows.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a2bb55f-ef8e-4c3a-a709-98db6b9db9c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6fab3c0076d9cbb81cbdef67434ab0e7080477a6/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/800d6269-b358-451d-946e-e04d1b2d3aab) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/552639cfd47f4f68fd04801f0eaf7191136aec2e/msteams-platform%2Fbots%2Fbot-features.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/408a495b-f113-49a1-849a-68c1251d4126) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/workflow-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/552639cfd47f4f68fd04801f0eaf7191136aec2e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fworkflow-bot-in-teams.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d4383e6-2413-4f82-a4c1-0cfce032588d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/552639cfd47f4f68fd04801f0eaf7191136aec2e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-from-web-apps.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddae0c65-39ed-4f5f-8bcb-f85837daf586) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/552639cfd47f4f68fd04801f0eaf7191136aec2e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff03c667-bae9-4b34-bd1a-f9129e55608c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/552639cfd47f4f68fd04801f0eaf7191136aec2e/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-proactive.md) | 87 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d37b1210-e923-44ba-9b2f-ea9b781580d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/552639cfd47f4f68fd04801f0eaf7191136aec2e/msteams-platform%2Fresources%2FmoodleInstructions.md) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2a34dd7-97a9-4818-8cfc-13a5d9006403) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/partner-apps-for-moodle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/552639cfd47f4f68fd04801f0eaf7191136aec2e/msteams-platform%2Fresources%2Fpartner-apps-for-moodle.md) | 82 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40b2889c-351b-451e-8aba-0e565fb77c4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/552639cfd47f4f68fd04801f0eaf7191136aec2e/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 87 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/469a7a35-2b1f-4c2e-b759-b3a678054533) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Sequential-Workflows.md](https://github.com/MicrosoftDocs/msteams-docs/blob/552639cfd47f4f68fd04801f0eaf7191136aec2e/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2FSequential-Workflows.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/583774a0-05c1-4ba0-b47e-e0480d956448) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/552639cfd47f4f68fd04801f0eaf7191136aec2e/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa8a54f8-7e6a-4ef1-92be-d2bbfd95bf36) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
