### PR TITLE
[Doc Improvement][Update bookmarks]

### PR DESCRIPTION
**Pull request by v-andreaco**
Sections were removed in this PR https://github.com/MicrosoftDocs/msteams-docs/pull/5831

Caused broken bookmarks, which are showing up in the validation report. Broken bookmarks can cause a bad user experience.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db4de6f1f09c9aecd6bad5846cbf7e56ca7d1d86/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14e451e7-1faa-498d-a8b4-ecdeb1b48ae1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-andreaco** [comment]
**Global effort to fix build validation errors**

@laujan 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

**Review by v-abirade — CHANGES_REQUESTED** [review]
Approved

**Review by v-abirade — APPROVED** [review]
Approved.

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
