### PR TITLE
[Doc Improvement][Task module to dialog integrate with Teams][3457835]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8a0668cf0aaf58a2d274bda74c2b36f9fc96675/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd108863-d1e2-40da-9a09-2dd3d2f0f307) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8a0668cf0aaf58a2d274bda74c2b36f9fc96675/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f92c5aab-1d7e-4be9-8041-5dd5499f4a6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8a0668cf0aaf58a2d274bda74c2b36f9fc96675/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5dd95087-dd88-4be3-9168-f97d9659a50c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4170846490f415ccc1766b1d7de7bcb723f81bfa/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/541a6cfa-0ff5-4553-9467-27dc3008e652) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4170846490f415ccc1766b1d7de7bcb723f81bfa/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6a06b4d-edea-4c18-8b5c-12ccbe07e8e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4170846490f415ccc1766b1d7de7bcb723f81bfa/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/341e066c-b26f-46b6-b22f-449d161a1080) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4170846490f415ccc1766b1d7de7bcb723f81bfa/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/498bcb74-15c7-4be3-a730-b9f60507467e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/40e47e046c3224da3ec6665657e4ef3859f3df93/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e4312e2-158e-44b0-8ac5-1511535d54a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/40e47e046c3224da3ec6665657e4ef3859f3df93/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 93 | 114 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aaf1c6d6-cf75-4b9f-88b8-b4dd58d27379) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/40e47e046c3224da3ec6665657e4ef3859f3df93/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c20ec36-9a06-4a43-8ddf-8834e323f0c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/40e47e046c3224da3ec6665657e4ef3859f3df93/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8985b26d-737f-4911-8383-8e2762ee3436) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/40e47e046c3224da3ec6665657e4ef3859f3df93/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a66b2b0-c9b0-48aa-9083-8c437f5362cf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/211c970b3f321c9b069272901caa1d96330856e3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40a3abb4-16b3-4270-9115-14caffb4cbe0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/211c970b3f321c9b069272901caa1d96330856e3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 93 | 114 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cfb80c1-8a0c-4f9a-8028-e6d126616088) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/211c970b3f321c9b069272901caa1d96330856e3/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed40fa9a-e227-4638-83ce-65d0ebb37087) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/211c970b3f321c9b069272901caa1d96330856e3/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00701b6f-2438-44d9-b040-72cf3360b7e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/211c970b3f321c9b069272901caa1d96330856e3/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/540b49b9-e214-4a8d-9916-b5eac7e8da11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/211c970b3f321c9b069272901caa1d96330856e3/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Finvoking-task-modules.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0d15ada-6dbb-4fbd-8528-787dc25f8a9b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/211c970b3f321c9b069272901caa1d96330856e3/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-bots.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddc65c3a-5cb4-4d84-a6cc-58aed267c473) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/211c970b3f321c9b069272901caa1d96330856e3/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-task-modules.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58ced998-9094-4a7e-ae3b-49424580fc83) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by erikadoyle — CHANGES_REQUESTED** [review]
Looks good, but could we update "TeamsJS v.1.0" to "TeamsJS v1.x" to generalize across all minor versions?

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f23aeded6404e5cf26ebf40ad8f588dea81c3082/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d979fd2-7e70-4a01-8e18-a18feaf7aeb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f23aeded6404e5cf26ebf40ad8f588dea81c3082/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 93 | 114 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c8c51ba-00f7-4ba8-89cc-3d42d8f23317) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f23aeded6404e5cf26ebf40ad8f588dea81c3082/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea81bc5f-08d2-4609-8f2f-62afc7639e16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f23aeded6404e5cf26ebf40ad8f588dea81c3082/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2848c267-7210-4ac5-8d45-a292c4d98679) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f23aeded6404e5cf26ebf40ad8f588dea81c3082/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92a5e55b-5fd6-4ec7-85a8-b01ba85c594e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f23aeded6404e5cf26ebf40ad8f588dea81c3082/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Finvoking-task-modules.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b407721b-b0cd-407a-be1d-9fa5dd0252f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f23aeded6404e5cf26ebf40ad8f588dea81c3082/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-bots.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57039dc8-764d-4c5e-bcff-3662510d3e8b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f23aeded6404e5cf26ebf40ad8f588dea81c3082/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-task-modules.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30c53bbc-3016-4d93-9dff-486674746d03) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/506a944a7ae23e5fe6062c1de409910ed8a716eb/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 91 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6d6282e-b7f6-4249-821d-94f997bf3fb7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/506a944a7ae23e5fe6062c1de409910ed8a716eb/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74075826-aade-47cc-bd63-37cb4423ce6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/506a944a7ae23e5fe6062c1de409910ed8a716eb/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e03f1a8-fef0-42aa-9122-04098c5a7393) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/506a944a7ae23e5fe6062c1de409910ed8a716eb/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7587f25a-bf57-4770-91a6-2a5ee4be1057) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/506a944a7ae23e5fe6062c1de409910ed8a716eb/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Finvoking-task-modules.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac43f5a5-83e6-48ce-91a0-52cd1b7ecc99) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/506a944a7ae23e5fe6062c1de409910ed8a716eb/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-bots.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9febdf29-2d88-40ae-aa46-e270679b729e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/506a944a7ae23e5fe6062c1de409910ed8a716eb/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-task-modules.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdb8dfac-fdab-4818-852a-7b2f8926b91e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0534359272861973b824d384e0077e78684f94/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b60e55d-5501-4256-9376-ad682e2b0fac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0534359272861973b824d384e0077e78684f94/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43135b5d-8ce2-4c02-8de8-b6d7431e6e88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0534359272861973b824d384e0077e78684f94/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb6f01c7-4b40-4bd2-9e22-ca33d5fd61ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0534359272861973b824d384e0077e78684f94/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9081a461-a11d-4858-b65b-b52addb22dca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0534359272861973b824d384e0077e78684f94/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Finvoking-task-modules.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd2ba125-dc3a-4729-80a9-d33f226be0d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0534359272861973b824d384e0077e78684f94/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-bots.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bbef4f7-709e-4648-9d9f-78467185e7d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc0534359272861973b824d384e0077e78684f94/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-task-modules.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a559f40c-02e6-4293-a9ac-0a14581e29d4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
