### PR TITLE
[Doc Feature][Revise Interactive Mode]

### PR DESCRIPTION
**Pull request by v-rpatkur**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db74e75bab3ffe145a0c19e746ad2a36fa565a13/msteams-platform/apps-in-teams-meetings/API-references.md) | 93 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/739fa76d-1dbe-4692-a2aa-bc8b5a9b07e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db74e75bab3ffe145a0c19e746ad2a36fa565a13/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ffaae32-d880-4e5d-8395-6259577424cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/db74e75bab3ffe145a0c19e746ad2a36fa565a13/msteams-platform/mstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9d0f477-329a-4838-8cc9-59222c2cd102) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db74e75bab3ffe145a0c19e746ad2a36fa565a13/msteams-platform/whats-new.md) | 89 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74ded79a-4cd6-4f8a-a7a7-c55afd52d058) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c04339efc4254568f13ad267d358084ef61bf80f/msteams-platform/apps-in-teams-meetings/API-references.md) | 93 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e1da905-52af-4887-bcbc-cb11c99156b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c04339efc4254568f13ad267d358084ef61bf80f/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b96e176e-18f7-4fab-a9ad-027f893370dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c04339efc4254568f13ad267d358084ef61bf80f/msteams-platform/mstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f38ffb4b-a7de-4a5d-825a-a80bcd4c81b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c04339efc4254568f13ad267d358084ef61bf80f/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 83 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0616356-7aba-47a6-b0dc-63075c6e86fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c04339efc4254568f13ad267d358084ef61bf80f/msteams-platform/whats-new.md) | 89 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00454bcd-6884-429d-81a8-890480ff62ee) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8acbf96e25c891bc6ae9283abaf2b9f6a0982743/msteams-platform/apps-in-teams-meetings/API-references.md) | 93 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb8e0425-ea1c-46a7-8284-2288fcf3e278) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8acbf96e25c891bc6ae9283abaf2b9f6a0982743/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bb17b30-600d-49d7-92f8-a1d550fd6023) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8acbf96e25c891bc6ae9283abaf2b9f6a0982743/msteams-platform/mstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79a20e1c-d29a-4a65-8397-3a5a8d4330c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8acbf96e25c891bc6ae9283abaf2b9f6a0982743/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 83 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9158275a-ac36-4f3f-9596-6b4cd451cba4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8acbf96e25c891bc6ae9283abaf2b9f6a0982743/msteams-platform/whats-new.md) | 89 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bacd58dd-aaee-47e8-8a2e-1708db107597) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce9e9d5080c9bd24deab7f82ab6b1d23cd37f390/msteams-platform/apps-in-teams-meetings/API-references.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d13f8705-24cf-40bd-8a15-4a36a6c43162) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce9e9d5080c9bd24deab7f82ab6b1d23cd37f390/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca7ebe9e-d3e6-4de9-b033-4b51389020fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ce9e9d5080c9bd24deab7f82ab6b1d23cd37f390/msteams-platform/mstdd-landing.yml) | 90 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ebf594f-feed-4c1c-bae2-43da12d9191e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce9e9d5080c9bd24deab7f82ab6b1d23cd37f390/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 84 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1553fdf9-6272-4759-a917-4964e179529a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce9e9d5080c9bd24deab7f82ab6b1d23cd37f390/msteams-platform/whats-new.md) | 91 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/809477f1-81f1-40ee-bc05-18e6d6a98f8c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2600ec10171e9cfbf7d5325d112d124ffc40c63/msteams-platform/apps-in-teams-meetings/API-references.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc38b657-0ae2-46d3-a5c7-3611cdc04bba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2600ec10171e9cfbf7d5325d112d124ffc40c63/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f94c9433-0308-45a2-9d2c-cc80c35fecd4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c2600ec10171e9cfbf7d5325d112d124ffc40c63/msteams-platform/mstdd-landing.yml) | 90 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9284cd0-257f-46ec-80df-11a5cd3b4eb4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2600ec10171e9cfbf7d5325d112d124ffc40c63/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 84 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e05b254f-3a42-444c-88f0-75d6d859ca13) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2600ec10171e9cfbf7d5325d112d124ffc40c63/msteams-platform/whats-new.md) | 91 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80198666-101a-4dcc-8383-f8124e9f4c65) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce814ce5e903bd29b75d1aab1741be92bd4caee/msteams-platform/apps-in-teams-meetings/API-references.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/373f4536-9982-404e-93b6-446a9bf4d623) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce814ce5e903bd29b75d1aab1741be92bd4caee/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79efd74c-5cd4-4cc4-8601-4350474de3e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce814ce5e903bd29b75d1aab1741be92bd4caee/msteams-platform/mstdd-landing.yml) | 90 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/534f72e6-a28a-4181-8ea7-3f8c241b9328) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce814ce5e903bd29b75d1aab1741be92bd4caee/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 84 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a506100a-90a2-487d-9b72-94f7aedac176) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ce814ce5e903bd29b75d1aab1741be92bd4caee/msteams-platform/whats-new.md) | 91 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f61e4cd-2ba0-4be4-a37a-714755480375) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/631ea3e5a3c0931686e279eeecc981b0cfb3b89b/msteams-platform/apps-in-teams-meetings/API-references.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74036637-e58a-4fe4-b499-de2ced6400f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/631ea3e5a3c0931686e279eeecc981b0cfb3b89b/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5af00ec-193a-4334-a03f-42c2b019292d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/631ea3e5a3c0931686e279eeecc981b0cfb3b89b/msteams-platform/mstdd-landing.yml) | 90 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8eb3ae30-b4d0-4c04-9796-ea0b94e1d45a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/631ea3e5a3c0931686e279eeecc981b0cfb3b89b/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 83 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f23a38cb-3149-41da-8408-c977284575e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/631ea3e5a3c0931686e279eeecc981b0cfb3b89b/msteams-platform/whats-new.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1ff0e1b-795f-4eeb-ab48-b7e6c726765a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4838f3415dc90185bda8e070d7b8387c04b3170f/msteams-platform/apps-in-teams-meetings/API-references.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0cf4ed5-b9bf-40cc-a07d-ac3f7d35f788) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4838f3415dc90185bda8e070d7b8387c04b3170f/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/967e5b2a-a7b6-47f4-ab17-25f93bb49395) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4838f3415dc90185bda8e070d7b8387c04b3170f/msteams-platform/mstdd-landing.yml) | 90 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b3fcdf3-f173-4b2d-87fb-8ce3457ef32b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4838f3415dc90185bda8e070d7b8387c04b3170f/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 83 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/938f8107-64a1-4368-af61-cf59df126f0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4838f3415dc90185bda8e070d7b8387c04b3170f/msteams-platform/whats-new.md) | 90 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66e8742d-3dc2-4bb2-bcb6-a3d2330e7f3f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0cac06cf6b29e77a5eaf704e01305ececf6c56e3/msteams-platform/apps-in-teams-meetings/API-references.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57a60cb9-cac6-41c6-a8a3-cc4d001b50b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0cac06cf6b29e77a5eaf704e01305ececf6c56e3/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f967f303-4139-466a-8366-409a11df3ad7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0cac06cf6b29e77a5eaf704e01305ececf6c56e3/msteams-platform/mstdd-landing.yml) | 90 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a5be1b3-6884-4df3-bbcd-7e2b4eb34216) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0cac06cf6b29e77a5eaf704e01305ececf6c56e3/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | 85 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/540b724e-7a60-4a08-b8f4-300092a506c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0cac06cf6b29e77a5eaf704e01305ececf6c56e3/msteams-platform/whats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3eed1e5-5f1b-491e-b662-d6182c6f6c74) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-abirade** [comment]
Closing the PR as outdated.

**Pull request closed without merging**
