### PR TITLE
[Doc Improvement][Remove time and future ref: 6][3886824]

### PR DESCRIPTION
**Pull request by v-deabira**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a908f3ec026186b49fc9658fc44ba8b50c0c11c0/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6178b69e-2a73-494e-9ce8-72e28f8e315c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a908f3ec026186b49fc9658fc44ba8b50c0c11c0/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3aac5f6-8df7-447c-acd3-b987aed5699b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a908f3ec026186b49fc9658fc44ba8b50c0c11c0/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-media-capabilities.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39a14e1b-dcb2-4cf6-b2b0-28fe6ea2f6fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a908f3ec026186b49fc9658fc44ba8b50c0c11c0/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 83 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d6911ef-3ac8-487d-b2de-9734a82a75c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/real-time-media-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a908f3ec026186b49fc9658fc44ba8b50c0c11c0/msteams-platform%2Fbots%2Fcalls-and-meetings%2Freal-time-media-concepts.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22c97117-8b92-4208-b143-ae7349f39d42) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a908f3ec026186b49fc9658fc44ba8b50c0c11c0/msteams-platform%2Fbots%2Fcalls-and-meetings%2Frequirements-considerations-application-hosted-media-bots.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f996ac6-a2cc-473e-9b6a-c0b1846b547f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a908f3ec026186b49fc9658fc44ba8b50c0c11c0/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfb102e7-6f51-4eb9-b04a-684ff9c16263) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a908f3ec026186b49fc9658fc44ba8b50c0c11c0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 85 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3bc1b1f2-6fce-4213-bfb3-2fa87d37fefb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a908f3ec026186b49fc9658fc44ba8b50c0c11c0/msteams-platform%2Fbots%2Fhow-to%2Fformat-your-bot-messages.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c9aba36-513d-4fe2-aa30-4a9d1343fda1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a908f3ec026186b49fc9658fc44ba8b50c0c11c0/msteams-platform%2Fbots%2Fhow-to%2Fget-teams-context.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93ee73c1-1c06-4161-9677-ca84781c9c4c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/866de227770870039458d2c535953769ec0bbbe7/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03825755-6eef-4502-a31b-88682459d8e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/866de227770870039458d2c535953769ec0bbbe7/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62411f42-b2d5-45f4-9d85-9992e26465d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/866de227770870039458d2c535953769ec0bbbe7/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-media-capabilities.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a12ef73d-85df-4e02-bc0c-8cd75c01858e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/866de227770870039458d2c535953769ec0bbbe7/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 83 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55651bed-8edc-4153-8695-94d1410243cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/real-time-media-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/866de227770870039458d2c535953769ec0bbbe7/msteams-platform%2Fbots%2Fcalls-and-meetings%2Freal-time-media-concepts.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/996c2f15-2e86-47c3-aa4e-7919649a4c03) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/866de227770870039458d2c535953769ec0bbbe7/msteams-platform%2Fbots%2Fcalls-and-meetings%2Frequirements-considerations-application-hosted-media-bots.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfa68e00-e21b-4eec-84ca-b3db99c42195) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/866de227770870039458d2c535953769ec0bbbe7/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/151d8f96-94a2-45ad-9951-6133ce6aee74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/866de227770870039458d2c535953769ec0bbbe7/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 85 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9094b99-9683-4d54-91e2-73892702b8fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/866de227770870039458d2c535953769ec0bbbe7/msteams-platform%2Fbots%2Fhow-to%2Fformat-your-bot-messages.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c53dde9-f55e-43f9-8171-20789f0825b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/866de227770870039458d2c535953769ec0bbbe7/msteams-platform%2Fbots%2Fhow-to%2Fget-teams-context.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0412fb99-5e98-47ab-be01-2d68161a5369) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/866de227770870039458d2c535953769ec0bbbe7/msteams-platform%2Fteams-faq.md) | 90 | 80 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ada87f8-01eb-4abc-aad3-22655bfb0bdf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f52304cf5a779a95fe2455350ffdb43cc95167e/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb1419a2-b79f-4a53-87ee-a223507c0db3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f52304cf5a779a95fe2455350ffdb43cc95167e/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 88 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ef2698a-5391-411b-bea7-323f17d3b189) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f52304cf5a779a95fe2455350ffdb43cc95167e/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-media-capabilities.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d73ae3a2-93d7-40e8-a148-62e7eb3101ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f52304cf5a779a95fe2455350ffdb43cc95167e/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 83 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d5543e4-2ed3-4421-bcf0-f4d90016787e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/real-time-media-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f52304cf5a779a95fe2455350ffdb43cc95167e/msteams-platform%2Fbots%2Fcalls-and-meetings%2Freal-time-media-concepts.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd556ba8-9103-4b5f-b95a-e29363b61616) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f52304cf5a779a95fe2455350ffdb43cc95167e/msteams-platform%2Fbots%2Fcalls-and-meetings%2Frequirements-considerations-application-hosted-media-bots.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68a92999-a01f-42b9-86c9-14f6d04abacf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f52304cf5a779a95fe2455350ffdb43cc95167e/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d38aa28b-d5a8-4024-a109-715ba586e4ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f52304cf5a779a95fe2455350ffdb43cc95167e/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 85 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e956c6e-346e-4d91-8126-d48f8e6d2711) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f52304cf5a779a95fe2455350ffdb43cc95167e/msteams-platform%2Fbots%2Fhow-to%2Fformat-your-bot-messages.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22acb95f-13a9-46a0-9cc0-6ceabf3f1fee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f52304cf5a779a95fe2455350ffdb43cc95167e/msteams-platform%2Fbots%2Fhow-to%2Fget-teams-context.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42df1756-ef07-443b-94f8-c98d19a5593d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f52304cf5a779a95fe2455350ffdb43cc95167e/msteams-platform%2Fteams-faq.md) | 90 | 80 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c9a9cf1-6995-4839-8c6c-d3af62dd44b4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/776112cd63cc56feb96dbb7a045a22093b74366a/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42e50e83-e86c-43fd-8048-f35718a150be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/776112cd63cc56feb96dbb7a045a22093b74366a/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 86 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e90cdccf-03b3-456a-8425-b7bd6a3827c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/776112cd63cc56feb96dbb7a045a22093b74366a/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-media-capabilities.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16236946-e4a0-43cd-9828-3f44b3d0fc1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/776112cd63cc56feb96dbb7a045a22093b74366a/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 83 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2d32750-e518-40f1-9de4-cfa71847b824) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/real-time-media-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/776112cd63cc56feb96dbb7a045a22093b74366a/msteams-platform%2Fbots%2Fcalls-and-meetings%2Freal-time-media-concepts.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6c39c9e-4d6c-4eb8-96e0-8a586c86b8d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/776112cd63cc56feb96dbb7a045a22093b74366a/msteams-platform%2Fbots%2Fcalls-and-meetings%2Frequirements-considerations-application-hosted-media-bots.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5071ae5-fbae-4e09-8cba-69e625452e7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/776112cd63cc56feb96dbb7a045a22093b74366a/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0096b659-b3c0-48e2-bed9-3befece24d98) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/776112cd63cc56feb96dbb7a045a22093b74366a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 85 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf6ae861-4253-45db-97bb-f5b6e2b029bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/776112cd63cc56feb96dbb7a045a22093b74366a/msteams-platform%2Fbots%2Fhow-to%2Fformat-your-bot-messages.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65e6bc99-31a7-4f57-9dc3-bf0e7326a839) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/776112cd63cc56feb96dbb7a045a22093b74366a/msteams-platform%2Fbots%2Fhow-to%2Fget-teams-context.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bc7b545-2a63-4fd4-865e-888528327853) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/776112cd63cc56feb96dbb7a045a22093b74366a/msteams-platform%2Fteams-faq.md) | 90 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2448f13d-359f-4c9f-ace0-ce3dc2b7d805) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-ypalikila — DISMISSED** [review]
Approved.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/real-time-media-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2992af46954308116729caf833d114befe70b2c9/msteams-platform%2Fbots%2Fcalls-and-meetings%2Freal-time-media-concepts.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/824c6c69-acde-4948-8a8c-50d9faa1be70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2992af46954308116729caf833d114befe70b2c9/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2dfa067-c6ad-4903-a496-de4d7cd96f47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2992af46954308116729caf833d114befe70b2c9/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 85 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75193229-bdcf-4d63-a6e9-7d80e86c3522) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2992af46954308116729caf833d114befe70b2c9/msteams-platform%2Fbots%2Fhow-to%2Fformat-your-bot-messages.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a673549-e2cd-41f3-8383-3959fb1072a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2992af46954308116729caf833d114befe70b2c9/msteams-platform%2Fbots%2Fhow-to%2Fget-teams-context.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/750cfe2d-77d1-4028-a7c2-c9db9c8a5393) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2992af46954308116729caf833d114befe70b2c9/msteams-platform%2Fteams-faq.md) | 90 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3928095-99ae-4002-ab41-0ae9ae923143) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
