### PR TITLE
[Doc Improvement][Update dynamic-search]

### PR DESCRIPTION
**Pull request by v-habibaumme**
Code sample added

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/dynamic-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f075ecdd3ca3c3d5821193abcfaa94899aebc2cb/msteams-platform/task-modules-and-cards/cards/dynamic-search.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82dd740f-993f-4f86-b35a-f61388d9ad35) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/dynamic-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3836c891555aa5478c4a3942e222ea2314aa8a3/msteams-platform/task-modules-and-cards/cards/dynamic-search.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22493eb2-79fc-4fdf-ac97-161b2fe3d6b5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/dynamic-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e39dc6ccd568d7a22bb3c797621600fa0a7a9fa6/msteams-platform/task-modules-and-cards/cards/dynamic-search.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fd609b9-092e-4ef9-a72f-cfe6ee2d5488) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/dynamic-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f73441aebb39ac437b15cd6ca75bf5c76fc0585c/msteams-platform/task-modules-and-cards/cards/dynamic-search.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e372b021-7cce-4f7b-8604-ae0263e1e226) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by ashishguptaiitb** [comment]
Please check if it should be typeahead (without space)?

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/dynamic-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4dfb49c77c0ddc263cccafd3096085a201cdbe5/msteams-platform/task-modules-and-cards/cards/dynamic-search.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95474e44-6cd8-4ba1-bb73-1b65a4e3bd98) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/dynamic-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d71421553ed99078efd8e8c3de4ba313dba43088/msteams-platform/task-modules-and-cards/cards/dynamic-search.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c07af95a-79e0-4a46-a952-7289b96f7140) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by ashishguptaiitb** [comment]
@v-habibaumme please address the issues reported by the build bot. 
Also, see formatting at https://review.docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/dynamic-search?branch=pr-en-us-4931&tabs=desktop%2Ccsharp#code-sample

**Comment by v-habibaumme** [comment]
@ashishguptaiitb,

Thank you. I will take a look and make the necessary changes.

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Comment by v-habibaumme** [comment]
Approved by Wajeed

**Pull request merged**
