### PR TITLE
[Doc Improvement][SEO meta description update][3915734]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d70b75ff472902878b808c10f2d8e270bdc2c35c/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e601ff1f-77c2-4c4b-a4e8-ac585af54843) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/create-new-project-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d70b75ff472902878b808c10f2d8e270bdc2c35c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fcreate-new-project-vs.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09c2993c-62fb-4961-aeac-a3634520f581) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-local-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d70b75ff472902878b808c10f2d8e270bdc2c35c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-local-vs.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5024d33-29f4-4d5c-9c18-b78c7fe44103) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a24366d2c919f4029836da845b4426542af4ee0/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bafa9aa9-d667-4b52-bc91-74570490e70a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a24366d2c919f4029836da845b4426542af4ee0/msteams-platform%2Ftoolkit%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1220c247-f131-4ec8-b7fb-c6e72ab60275) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a24366d2c919f4029836da845b4426542af4ee0/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d691e93-14a1-45ac-a3a4-89d605317559) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/create-new-project-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a24366d2c919f4029836da845b4426542af4ee0/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fcreate-new-project-vs.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6f33728-99e1-4ead-9e3e-af70ac2968a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-local-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a24366d2c919f4029836da845b4426542af4ee0/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-local-vs.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1e548dd-0400-4b96-b910-1eae502a920e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f8ea42c7def62bba58d014bb4f2acad1a2fdd78/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 90 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad26a9ff-92fa-47b3-8f51-69db76111fe9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f8ea42c7def62bba58d014bb4f2acad1a2fdd78/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8828ab7c-2155-4e18-a071-e572c035c464) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f8ea42c7def62bba58d014bb4f2acad1a2fdd78/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5ba9568-835e-4b36-b208-430e74a7081b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f8ea42c7def62bba58d014bb4f2acad1a2fdd78/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aab37bad-dd81-4ce5-a753-7944b679057a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f8ea42c7def62bba58d014bb4f2acad1a2fdd78/msteams-platform%2Ftoolkit%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/539b50c9-5273-49b0-9f01-a62e5ffe0596) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f8ea42c7def62bba58d014bb4f2acad1a2fdd78/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7363a7c6-c260-416f-9e2b-230f72a4e773) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/create-new-project-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f8ea42c7def62bba58d014bb4f2acad1a2fdd78/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fcreate-new-project-vs.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eaccf13d-d2be-4245-adff-4167462a82f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-local-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f8ea42c7def62bba58d014bb4f2acad1a2fdd78/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-local-vs.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/beec778f-68bd-4055-95f0-9e15eb0c20bf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/041f1a9ca5da149e04470c195e431d0ab99b6d1a/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 90 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52c1c7e2-55b9-4b01-90ec-db57be3af3d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/041f1a9ca5da149e04470c195e431d0ab99b6d1a/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d81643c-7bab-47fb-bfca-5e868dd1150a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/041f1a9ca5da149e04470c195e431d0ab99b6d1a/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22adbd12-76a4-4950-98cc-96870b1ae7bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/041f1a9ca5da149e04470c195e431d0ab99b6d1a/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e59737fb-fd36-490e-9ed5-0ef3f5dee641) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/041f1a9ca5da149e04470c195e431d0ab99b6d1a/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6841a509-93e2-45a6-901c-2fd5296a6b81) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/041f1a9ca5da149e04470c195e431d0ab99b6d1a/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce37b621-9e1b-46d2-8d91-fa13aba5608e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/041f1a9ca5da149e04470c195e431d0ab99b6d1a/msteams-platform%2Ftoolkit%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ff64c19-8226-44cb-a0f3-4065d3d48df5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/041f1a9ca5da149e04470c195e431d0ab99b6d1a/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a174b1d-8ace-4701-9e4a-6f1a248a45a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/create-new-project-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/041f1a9ca5da149e04470c195e431d0ab99b6d1a/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fcreate-new-project-vs.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95957f55-e84d-4386-be0a-af60857d6818) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-local-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/041f1a9ca5da149e04470c195e431d0ab99b6d1a/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-local-vs.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2d91df4-1888-44db-8f19-fe84b66cff10) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbf773eab88072accece7fb30d02948e556b1f60/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 90 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c8e8b8c-78fe-4c53-95f8-4cb828318254) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbf773eab88072accece7fb30d02948e556b1f60/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34ffa35b-ddcd-422e-9d92-9430fded694d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbf773eab88072accece7fb30d02948e556b1f60/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc0904ed-3c22-476f-a9da-dda2632f9fc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbf773eab88072accece7fb30d02948e556b1f60/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c30f1a7-446b-47c1-9cd3-dfae735891ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbf773eab88072accece7fb30d02948e556b1f60/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbb87bfb-0a90-4a7a-9094-e87d0140a771) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbf773eab88072accece7fb30d02948e556b1f60/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9cdec75-2753-44cc-bd79-dbdbc4e730d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbf773eab88072accece7fb30d02948e556b1f60/msteams-platform%2Ftoolkit%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/430df45b-3b2b-4862-9d96-d71f7f321090) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbf773eab88072accece7fb30d02948e556b1f60/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62b6d780-4208-4569-befb-4e4a457abc8e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/create-new-project-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbf773eab88072accece7fb30d02948e556b1f60/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fcreate-new-project-vs.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50bcb490-466d-4796-b97a-de1b275ac2b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-local-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbf773eab88072accece7fb30d02948e556b1f60/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-local-vs.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4ef2712-daee-4cf9-8781-4f951f129726) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5cc62eb9ec6946baeb604ceec19934a7bcbaa26e/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 90 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cdc76d2-f71f-410d-815f-a0c9b3ebff53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5cc62eb9ec6946baeb604ceec19934a7bcbaa26e/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/309fa858-d222-44a7-8b1c-4cd143c5537d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5cc62eb9ec6946baeb604ceec19934a7bcbaa26e/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6018c581-9d1b-427f-bfa2-eedf6b9ef661) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5cc62eb9ec6946baeb604ceec19934a7bcbaa26e/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7da42ddc-1465-4d1a-a499-2d57cbc0cbd1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5cc62eb9ec6946baeb604ceec19934a7bcbaa26e/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e490220f-dce6-4135-b38f-fd5491929d88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5cc62eb9ec6946baeb604ceec19934a7bcbaa26e/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8028e5f-b684-415b-8ed0-cdc8c4410048) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5cc62eb9ec6946baeb604ceec19934a7bcbaa26e/msteams-platform%2Ftoolkit%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e67e97a8-44a0-4c10-8753-5fd32bce7d15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5cc62eb9ec6946baeb604ceec19934a7bcbaa26e/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5e97b73-561c-4d1c-8b2f-79a3637616df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/create-new-project-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5cc62eb9ec6946baeb604ceec19934a7bcbaa26e/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fcreate-new-project-vs.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/058ad54b-f4b7-4e46-95d3-fe693a0f6da6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-local-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5cc62eb9ec6946baeb604ceec19934a7bcbaa26e/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-local-vs.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfe895ec-dd09-4961-92c1-aa87766516b5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3237ea2e408481e7fdc72292cba7d574094f1a9f/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 90 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c2aa2de-f1fa-4b38-96fd-a891bcf7ccfd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3237ea2e408481e7fdc72292cba7d574094f1a9f/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8859de6-b420-402f-b8ac-a82efbc171c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3237ea2e408481e7fdc72292cba7d574094f1a9f/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d71723b5-4571-4417-9631-78ab1eb95038) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3237ea2e408481e7fdc72292cba7d574094f1a9f/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c18bb11-bd7b-4f5f-8111-0c70a4e0f005) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3237ea2e408481e7fdc72292cba7d574094f1a9f/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcb67544-fc6c-4a7e-9fc5-5a5b01caf48f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3237ea2e408481e7fdc72292cba7d574094f1a9f/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3bc4872-72d0-4d6f-8967-5e15131ab1d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3237ea2e408481e7fdc72292cba7d574094f1a9f/msteams-platform%2Ftoolkit%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88433d53-72ce-4106-a811-aa8dac8e9b46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3237ea2e408481e7fdc72292cba7d574094f1a9f/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4104724-52ef-4f6f-a763-e9007b796f67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/create-new-project-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3237ea2e408481e7fdc72292cba7d574094f1a9f/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fcreate-new-project-vs.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8675d145-f448-4575-9d65-b659ee4c92b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-local-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3237ea2e408481e7fdc72292cba7d574094f1a9f/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-local-vs.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ed38bb0-aac1-4448-8e47-d19abb0052be) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
