### PR TITLE
M365 apps: Add screenshots for latest capabilities

### PR DESCRIPTION
**Pull request by erikadoyle**
Also corrected some javascript in a snippet and address https://github.com/MicrosoftDocs/msteams-docs/issues/4923

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/79c21c87e2f84f1bbedb0dc5937189e3761fc455/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd92712a-a982-47e4-bab6-4af4d2eda513) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/79c21c87e2f84f1bbedb0dc5937189e3761fc455/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | 93 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cccbf76d-8345-45dc-8e97-2672f53575a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/using-teams-client-sdk-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/79c21c87e2f84f1bbedb0dc5937189e3761fc455/msteams-platform/m365-apps/using-teams-client-sdk-preview.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb5d3bdb-cf3c-4cd5-a6d9-730805a2df3d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fb29df2f35acee6039393e62b95a8c3cf5a989e/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9083a14d-125b-450d-87a9-a78f43a47d91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fb29df2f35acee6039393e62b95a8c3cf5a989e/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | 93 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9286e72f-209b-423c-af27-81478ec56938) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/using-teams-client-sdk-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fb29df2f35acee6039393e62b95a8c3cf5a989e/msteams-platform/m365-apps/using-teams-client-sdk-preview.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a1dda22-b97d-4d19-b4f0-53682d1991de) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f86fd181af03b8474e8eddebc52aa7d30846ee37/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/443b0bda-8d92-489c-b3ab-b14416ebda57) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f86fd181af03b8474e8eddebc52aa7d30846ee37/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | 93 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/107bc08c-cc67-4932-9018-0af0e4332c80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/using-teams-client-sdk-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f86fd181af03b8474e8eddebc52aa7d30846ee37/msteams-platform/m365-apps/using-teams-client-sdk-preview.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01e58c24-0070-4462-b14b-e4469b135f7c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65a6a1c095eca004b54531c4a55b4374492a3f3f/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb41ccd9-9863-4189-96a8-ead70e3b9ae6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65a6a1c095eca004b54531c4a55b4374492a3f3f/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | 93 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5e94bbe-b096-42b5-9a89-a29eebf276c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/using-teams-client-sdk-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/65a6a1c095eca004b54531c4a55b4374492a3f3f/msteams-platform/m365-apps/using-teams-client-sdk-preview.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77a12247-2bb3-4dce-90fe-4f0911226741) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d7c66442ae491a8c6344cc9aa27311820a61d79d/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36895fe4-f992-4cf7-af2c-70a8be5fab41) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d7c66442ae491a8c6344cc9aa27311820a61d79d/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | 93 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96489a1c-d72c-4b18-954c-46bfb4097e26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/using-teams-client-sdk-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d7c66442ae491a8c6344cc9aa27311820a61d79d/msteams-platform/m365-apps/using-teams-client-sdk-preview.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cad4f5c-ea17-44e3-8e65-f0f106ceed88) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
