### PR TITLE
[Doc update][Unified feedback deprecated][3173122]

### PR DESCRIPTION
**Pull request by v-ypalikila**
updated Select **This page** in the **Submit and view feedback** section available at the footer of the documentation, to open an issue. **This page** option will be deprecated soon.  You can also seelect :::image type="icon" source="assets/icons/feedback-icon.png" border="false"::: **Feedback** in the upper-right corner of the article.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ac0fe1edae106f7e37cc92da002adde0ce73bc0/msteams-platform%2Ffeedback.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ac0fe1edae106f7e37cc92da002adde0ce73bc0/msteams-platform%2Fwhats-new.md) | 92 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c4b0b2c-cbc4-4ac9-a98a-40b6240a12e2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/877855527bbd7d8ec3c9c27e3644ae3589efdaac/msteams-platform%2Ffeedback.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81a8571e-d2ec-450f-88b9-c0adb340ab78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/877855527bbd7d8ec3c9c27e3644ae3589efdaac/msteams-platform%2Fwhats-new.md) | 92 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/471edef8-e75d-4db9-8fda-efa7a02f2e76) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5eae31eced795c22677c155069e2e245fe0657/msteams-platform%2Ffeedback.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36ae08dc-bef9-4436-a2c7-39bb999f6cf6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5eae31eced795c22677c155069e2e245fe0657/msteams-platform%2Fm365-apps%2Factions-in-m365.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cf3254a-3a33-4a87-8931-8f5d3aa8eab0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/build-actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5eae31eced795c22677c155069e2e245fe0657/msteams-platform%2Fm365-apps%2Fbuild-actions-in-m365.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43ed9332-e03a-466b-86ae-18d089c76637) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5eae31eced795c22677c155069e2e245fe0657/msteams-platform%2Fwhats-new.md) | 92 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec2f1d55-e05c-475e-a34a-a5e8ba8e6a6e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f6d3fb88029c7b98b505e9ef8d75bb0ff41025a/msteams-platform%2Ffeedback.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/572aa0b7-8014-429e-b5f4-7ce7d0d0826e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f6d3fb88029c7b98b505e9ef8d75bb0ff41025a/msteams-platform%2Fm365-apps%2Factions-in-m365.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30464002-9355-41d0-ae3a-553dc014f2a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/build-actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f6d3fb88029c7b98b505e9ef8d75bb0ff41025a/msteams-platform%2Fm365-apps%2Fbuild-actions-in-m365.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/493ace0d-36bb-4ca9-b89f-0d2d64b386fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f6d3fb88029c7b98b505e9ef8d75bb0ff41025a/msteams-platform%2Fwhats-new.md) | 92 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7bbad19b-97d6-4d5d-beea-4834cf606f8e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
