### PR TITLE
[Tools and SDKs][Dasboard, widget and Graph API call in Teams toolkit][2820143]

### PR DESCRIPTION
**Pull request by v-silakshmi**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/26d4fee5b6459e1300982e744338a43e24ea384b/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c61df39-cc74-4056-a7af-144b0528e02f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/dashboard-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/26d4fee5b6459e1300982e744338a43e24ea384b/msteams-platform%2Ftabs%2Fhow-to%2Fdashboard-teams-toolkit.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d94fcd47-af80-4fe0-9e4d-44eab13eb493) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/848229f6d96af17a23808023b7590a5236b40dde/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9a78702-a1ea-487f-920d-e4ef3c8e6f2a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/dashboard-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/848229f6d96af17a23808023b7590a5236b40dde/msteams-platform%2Ftabs%2Fhow-to%2Fdashboard-teams-toolkit.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c01e42d3-419d-4702-abd2-57075513e01b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/848229f6d96af17a23808023b7590a5236b40dde/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5641caf-d6fc-400b-88cb-6992352bdd07) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/dashboard-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/848229f6d96af17a23808023b7590a5236b40dde/msteams-platform%2Ftabs%2Fhow-to%2Fdashboard-teams-toolkit.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5a2263f-f54a-493f-8d3a-23969a86dd3c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fa7c7c6b1c3fef23b12d017d18056bbd9c2d872c/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8adb362-9e49-48d6-aaa3-9cdb572f7b71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/dashboard-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa7c7c6b1c3fef23b12d017d18056bbd9c2d872c/msteams-platform%2Ftabs%2Fhow-to%2Fdashboard-teams-toolkit.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b80d4908-e884-4009-95b1-12dadb964905) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ff867a50ae429c2f7a3243b52027456b2f8a31aa/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd91a528-25a6-4aac-8c8e-cdfcd04c4dc6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/dashboard-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff867a50ae429c2f7a3243b52027456b2f8a31aa/msteams-platform%2Ftabs%2Fhow-to%2Fdashboard-teams-toolkit.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95736477-645f-45ec-b14f-ebb20d6a4319) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/45a460d07e1f52312f6707e95393cf7f6e90f497/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f36422a8-5765-4328-b909-5aefe6f3d617) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/dashboard-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45a460d07e1f52312f6707e95393cf7f6e90f497/msteams-platform%2Ftabs%2Fhow-to%2Fdashboard-teams-toolkit.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8658b4cd-3c84-4e83-b97a-a9729d555542) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/447dafd518ff9064bda0a5e37ccb2df195da52b0/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acb10f80-968c-49b9-9f94-c78c03b7c919) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/dashboard-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/447dafd518ff9064bda0a5e37ccb2df195da52b0/msteams-platform%2Ftabs%2Fhow-to%2Fdashboard-teams-toolkit.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1df6ea4-5c0c-4592-b655-4d43384beb98) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/08ec6ace3808a542ee345ef7a0c5b8d903f44003/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88c89079-d78c-4b7a-b6c9-947f12ea86d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/dashboard-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08ec6ace3808a542ee345ef7a0c5b8d903f44003/msteams-platform%2Ftabs%2Fhow-to%2Fdashboard-teams-toolkit.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/990a8363-90b0-4929-b989-3ba9073dc105) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/481ddc3721b936c8ac3cf24e061452fbdf14a1ec/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e47cc401-4dca-4e90-bbbd-3d6bdd23115c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/dashboard-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/481ddc3721b936c8ac3cf24e061452fbdf14a1ec/msteams-platform%2Ftabs%2Fhow-to%2Fdashboard-teams-toolkit.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d0dbd25-405e-45a8-8806-91c66c5a4a19) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4470381b7ec5f1ab586f86b0b7e5d1ea7cacf882/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5e9dfc3-bd80-440c-966f-1378d2f8868b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/dashboard-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4470381b7ec5f1ab586f86b0b7e5d1ea7cacf882/msteams-platform%2Ftabs%2Fhow-to%2Fdashboard-teams-toolkit.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8363e67-aa67-4784-b147-5a29203d9e88) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c1873930faa6d231193903a374fa41797de6891d/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f456ed1-ab36-4b58-afad-7b0ab9b9806d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/dashboard-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c1873930faa6d231193903a374fa41797de6891d/msteams-platform%2Ftabs%2Fhow-to%2Fdashboard-teams-toolkit.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ab0ceed-7fe7-4741-a74d-843090979ed2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-silakshmi** [comment]
this is a duplicate.

**Pull request closed without merging**
