### PR TITLE
[Doc Enhancement][Branding Terms3][ADO No]

### PR DESCRIPTION
**Pull request by v-dreddipogu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/800cd8a5d95ea7255546fc3028f60d19f9cebc61/msteams-platform/bots/calls-and-meetings/registering-calling-bot.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/999bd0ff-f663-4368-89fe-0ed1f19dea45) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/800cd8a5d95ea7255546fc3028f60d19f9cebc61/msteams-platform/bots/how-to/authentication/add-authentication.md) | 86 | 102 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fa3b3c3-4b71-4488-b17e-6a50e1caa668) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/800cd8a5d95ea7255546fc3028f60d19f9cebc61/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md) | 98 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99907d85-5da3-4efb-af26-619a6d1a8a29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/800cd8a5d95ea7255546fc3028f60d19f9cebc61/msteams-platform/graph-api/rsc/resource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de3195af-5db9-41a0-974b-4dca53fa4976) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/bots/azure-bot-channels-registration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/800cd8a5d95ea7255546fc3028f60d19f9cebc61/msteams-platform/includes/bots/azure-bot-channels-registration.md) | 85 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc19bba7-8fa5-4a1b-abf6-46cbd5d52b2a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/800cd8a5d95ea7255546fc3028f60d19f9cebc61/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15d164bd-e335-40bd-a1d8-7b6b1654fb84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/800cd8a5d95ea7255546fc3028f60d19f9cebc61/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | 93 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb3ff347-72b6-4281-8dd3-7f5e712e1682) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/800cd8a5d95ea7255546fc3028f60d19f9cebc61/msteams-platform/resources/bot-v3/bots-create.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f85ce41-230d-451e-a882-a680a73e6324) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/800cd8a5d95ea7255546fc3028f60d19f9cebc61/msteams-platform/sbs-calling-and-meeting.yml) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a601f771-2e83-4b95-b02f-adcb874338b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/800cd8a5d95ea7255546fc3028f60d19f9cebc61/msteams-platform/sbs-meeting-content-bubble.yml) | 85 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e222dc46-90dc-4429-9d99-70c674a4bb6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/800cd8a5d95ea7255546fc3028f60d19f9cebc61/msteams-platform/sbs-meeting-token-generator.yml) | 89 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9600d20a-8cca-4d7e-aaa5-49a810c8a5ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/800cd8a5d95ea7255546fc3028f60d19f9cebc61/msteams-platform/sbs-meetings-sidepanel.yml) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7351d922-2a55-45ce-b71e-5062bc266201) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/800cd8a5d95ea7255546fc3028f60d19f9cebc61/msteams-platform/sbs-tab-with-adaptive-cards.yml) | 89 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa4844ce-239c-4036-ab4c-95e552b4a390) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/800cd8a5d95ea7255546fc3028f60d19f9cebc61/msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml) | 85 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60ea5460-3859-427c-8a00-8a0923cd6cd0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/bots/calls-and-meetings/registering-calling-bot.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e0b3271-5008-48c7-8f43-8d767ba52b47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/bots/how-to/authentication/add-authentication.md) | 86 | 102 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/452f3aa0-d184-4c33-8050-6873132c230f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md) | 98 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df313ea9-6103-4ee1-8e55-4e7baf12ccb6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/graph-api/rsc/resource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e178458-2d0f-4437-ac5b-c5e49a2905db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/bots/azure-bot-channels-registration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/includes/bots/azure-bot-channels-registration.md) | 85 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/151882bc-b0e9-49f0-a0f0-da83137c0f8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3eecab99-316f-40bf-829f-4a2e8a70a356) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | 93 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee7df0de-5c72-45e8-bcb3-97f313535b03) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/resources/bot-v3/bots-create.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9142442c-9995-47df-8a89-dca1d63b5699) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/sbs-calling-and-meeting.yml) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5aa09103-d610-4128-a97f-d19153169758) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/sbs-meeting-content-bubble.yml) | 85 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09f1233e-4958-41d1-8ca1-cfb274e9f092) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/sbs-meeting-token-generator.yml) | 89 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea58f0b0-74fe-4d80-8c8a-b59760e88186) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/sbs-meetings-sidepanel.yml) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe1bdeb0-5eaa-4749-949d-d157868e2f89) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/sbs-tab-with-adaptive-cards.yml) | 89 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9160f34-39e1-4dd2-a10e-94afb6d67873) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml) | 85 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1915f6ef-5e13-4482-aaab-beb0abba77c9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/bots/calls-and-meetings/registering-calling-bot.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90d8aab8-1985-4533-a2db-26e072cf7bc6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/bots/how-to/authentication/add-authentication.md) | 86 | 102 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/390085e5-3cfc-4892-b2a1-09b6bc94d188) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md) | 98 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c65c8f9d-bbd1-4146-8d05-68c06c9c2e35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/graph-api/rsc/resource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0da7c019-2afe-4de7-8cd1-b008ee1d95e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/bots/azure-bot-channels-registration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/includes/bots/azure-bot-channels-registration.md) | 85 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89332222-3f02-4d97-a565-120f4ae3be5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/980f6ac2-eb40-4252-9291-67641073a858) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | 93 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7124bc98-d2ea-4c78-82b3-241407735741) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/resources/bot-v3/bots-create.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0cdf7417-51f9-4678-9be1-2f52a650f20b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/sbs-calling-and-meeting.yml) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e35ccee3-93b1-4ff7-942e-48c945bb5fe2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/sbs-meeting-content-bubble.yml) | 85 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4f3e225-0655-4852-bc9f-c3c15a3b1ba1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/sbs-meeting-token-generator.yml) | 89 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/587f8a80-6e85-42b1-b7b8-234de0ef62ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/sbs-meetings-sidepanel.yml) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/764103f5-faff-4ea6-a002-ecd631b4e559) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/sbs-tab-with-adaptive-cards.yml) | 89 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99c17a05-8dfb-4967-a82a-6b3499aa49b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e20b92aa4eece63476f08acdfe6b0b2b03c2a5ff/msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml) | 85 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02685102-d6e4-476c-a756-573dbd32d8dd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Review by v-habibaumme — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
