### PR TITLE
[Doc Improvement][Live share git links update][2729860]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-canvas.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6be21de7d94958d7736e13d88cfe13bc9a90752e/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-canvas.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1ef2fc3-11b2-4c2a-98e6-cf370b22248e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6be21de7d94958d7736e13d88cfe13bc9a90752e/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-quick-start.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec5842e9-08b9-48fa-9387-12b014d0556a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6be21de7d94958d7736e13d88cfe13bc9a90752e/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f4161e2-5829-42f8-ae02-bd7a80e9f2d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6be21de7d94958d7736e13d88cfe13bc9a90752e/msteams-platform%2Fsbs-teams-live-share.yml) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01b7001a-192c-4318-9f60-5e8904ede487) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by ryanbliss — CHANGES_REQUESTED** [review]
A couple other tweaks that are needed as well, but looks good overall

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-canvas.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9db3c4a968ab73d3a1cf93a5c1f9d2d0a5f0878/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-canvas.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27624ea8-25cc-427e-a7a4-5cbb2e53425a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9db3c4a968ab73d3a1cf93a5c1f9d2d0a5f0878/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-quick-start.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09cee60d-0f54-4603-9faf-5d001e6a1c9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9db3c4a968ab73d3a1cf93a5c1f9d2d0a5f0878/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/552b8a5d-d0b9-45a1-a2cd-eb2aed1c02b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a9db3c4a968ab73d3a1cf93a5c1f9d2d0a5f0878/msteams-platform%2Fsbs-teams-live-share.yml) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac97deb7-80d1-4800-be48-c197e51a99fe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-canvas.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97ac0bb61635339d78346d77f0b259caeda7b616/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-canvas.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d248ffd2-0592-4a3d-90a2-a694a354bd4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97ac0bb61635339d78346d77f0b259caeda7b616/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-quick-start.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a911cd12-fb98-416d-afc2-bd57c591517a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97ac0bb61635339d78346d77f0b259caeda7b616/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4afd5e7c-4889-4fa2-b61a-c57e0627aece) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/97ac0bb61635339d78346d77f0b259caeda7b616/msteams-platform%2Fsbs-teams-live-share.yml) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f31f2ca3-80f9-4483-bcf9-8843103478c2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-canvas.md](https://github.com/MicrosoftDocs/msteams-docs/blob/084cdfd56c3042a49cbaad1a30511f4c9d1dcf5b/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-canvas.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb93195f-3825-4312-beaa-dc2df99d4089) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/084cdfd56c3042a49cbaad1a30511f4c9d1dcf5b/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-quick-start.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35ea4e85-e9af-47f8-b21e-213bc3fcee08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/084cdfd56c3042a49cbaad1a30511f4c9d1dcf5b/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/524dfd5c-8d2e-4309-9d1b-507828f52000) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/084cdfd56c3042a49cbaad1a30511f4c9d1dcf5b/msteams-platform%2Fsbs-teams-live-share.yml) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bcc29580-359f-4966-8d45-7c6d6549bc00) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-canvas.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b73db50d1d3bb1adbc3c78afa1de55608be26671/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-canvas.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4298cb92-164c-44ad-8ea4-9b88e612815b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b73db50d1d3bb1adbc3c78afa1de55608be26671/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-quick-start.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a932aa15-f30e-440b-8c8b-f0d690e5c0ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b73db50d1d3bb1adbc3c78afa1de55608be26671/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bbc2cbb-3a4a-4acf-93c8-0c00d60a39a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b73db50d1d3bb1adbc3c78afa1de55608be26671/msteams-platform%2Fsbs-teams-live-share.yml) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a461891-781a-4143-a669-4c4b031ed064) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by ryanbliss — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-canvas.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a38c23aea5062902d444f5288339c18571f8f2b3/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-canvas.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21aa59ef-00f4-45df-97a3-f056e41351c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a38c23aea5062902d444f5288339c18571f8f2b3/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-quick-start.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/348766d3-3c29-4498-be3e-e416b4d96746) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a38c23aea5062902d444f5288339c18571f8f2b3/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/869072f4-cbf0-4248-9af8-7efd1ed23216) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a38c23aea5062902d444f5288339c18571f8f2b3/msteams-platform%2Fsbs-teams-live-share.yml) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9167b855-0983-4d93-bce3-6b10f43a4a33) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
