### PR TITLE
[Doc improvement][SEO11 metatitle update][3881913]

### PR DESCRIPTION
**Pull request by v-ramyas5**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/auth-flow-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2078e98934f75b1a116b651fde299ed51c6db1e7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-flow-tab.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b7091e0-9f0a-4391-84d8-74ddf3508631) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2078e98934f75b1a116b651fde299ed51c6db1e7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-tab-aad.md) | 86 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b19d1c95-0001-45e7-986a-e7845fdbf221) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2078e98934f75b1a116b651fde299ed51c6db1e7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-code.md) | 83 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22ca9f93-d063-49b5-8001-de6b5975c0ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2078e98934f75b1a116b651fde299ed51c6db1e7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-graph-api.md) | 87 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d53ff44f-f1cd-45ce-87b9-154cbe9ce002) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2078e98934f75b1a116b651fde299ed51c6db1e7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 86 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf94bb3d-02aa-472d-9b10-abb6001810ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2078e98934f75b1a116b651fde299ed51c6db1e7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-overview.md) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29dd7717-7abc-4dc0-9252-6cf181891fc7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2078e98934f75b1a116b651fde299ed51c6db1e7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-register-aad.md) | 92 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe83e2e1-858b-4dda-89fe-ff53f4b2c4f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-troubleshooting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2078e98934f75b1a116b651fde299ed51c6db1e7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-troubleshooting.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/006c4e96-a337-4866-ae32-293be4feb941) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/authentication-flow-in-universal-action-for-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2078e98934f75b1a116b651fde299ed51c6db1e7/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fauthentication-flow-in-universal-action-for-adaptive-cards.md) | 87 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16cf0bbb-0a6b-4e7b-b2b2-622c22b8ac6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/enable-sso-for-your-adaptive-cards-universal-action.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2078e98934f75b1a116b651fde299ed51c6db1e7/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fenable-sso-for-your-adaptive-cards-universal-action.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5904be33-2c29-48ad-ae41-427d762b9eb6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/auth-flow-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4df3573816f35a8fbd2dd8aeb19f8797bc67051c/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-flow-tab.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9fc6364-390e-42a5-9623-6674b3602d10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4df3573816f35a8fbd2dd8aeb19f8797bc67051c/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-tab-aad.md) | 86 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bee6de5-8277-4603-8fc1-3f07d1a519d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4df3573816f35a8fbd2dd8aeb19f8797bc67051c/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-code.md) | 83 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4f6c1cb-5f6f-400f-b1e5-1c63431e5bcb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4df3573816f35a8fbd2dd8aeb19f8797bc67051c/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-graph-api.md) | 87 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91812863-28c6-491b-8a71-054f5d87dc90) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4df3573816f35a8fbd2dd8aeb19f8797bc67051c/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 86 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d2fceb8-b176-4786-ba4a-c906cf15d503) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4df3573816f35a8fbd2dd8aeb19f8797bc67051c/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-overview.md) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1e1a2bb-11bd-43f5-9aa1-6e2cafda841f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4df3573816f35a8fbd2dd8aeb19f8797bc67051c/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-register-aad.md) | 92 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99e25a10-8276-4708-a208-6e7b9117816d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-troubleshooting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4df3573816f35a8fbd2dd8aeb19f8797bc67051c/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-troubleshooting.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a5d8b0e-a526-400d-a7f7-b394e504e11c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/authentication-flow-in-universal-action-for-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4df3573816f35a8fbd2dd8aeb19f8797bc67051c/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fauthentication-flow-in-universal-action-for-adaptive-cards.md) | 87 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b881e4c-429c-4290-a9a1-cf899fc812b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/enable-sso-for-your-adaptive-cards-universal-action.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4df3573816f35a8fbd2dd8aeb19f8797bc67051c/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fenable-sso-for-your-adaptive-cards-universal-action.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3a37e89-8a6d-47e4-8fa1-5e9920283c51) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/auth-flow-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57dca7e24cf68d0a71decc651168038a965012f7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-flow-tab.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/119b8d2c-0857-4dfa-803a-4e6b652b4b1f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57dca7e24cf68d0a71decc651168038a965012f7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-tab-aad.md) | 86 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f77a42d-b3ac-4224-b979-3b682990f0c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57dca7e24cf68d0a71decc651168038a965012f7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-code.md) | 83 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d23a3f5e-8aa2-4846-bc4a-81c1d2805f1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57dca7e24cf68d0a71decc651168038a965012f7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-graph-api.md) | 87 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72297fb9-ea32-4b36-a197-9cc35e4f9c17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57dca7e24cf68d0a71decc651168038a965012f7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 86 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57feb374-d9e0-46c8-aff0-48dcc665d3ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57dca7e24cf68d0a71decc651168038a965012f7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-overview.md) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/757db08c-c441-4eae-8409-d8f20a5d5272) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57dca7e24cf68d0a71decc651168038a965012f7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-register-aad.md) | 92 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac744655-d8d9-4b12-8bd1-db2396a7db85) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-troubleshooting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57dca7e24cf68d0a71decc651168038a965012f7/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-troubleshooting.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2d7ffa5-260d-4c71-95f5-d2376241b791) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/authentication-flow-in-universal-action-for-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57dca7e24cf68d0a71decc651168038a965012f7/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fauthentication-flow-in-universal-action-for-adaptive-cards.md) | 87 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5411b6c3-9e3a-45e0-864e-4d37c4785531) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/enable-sso-for-your-adaptive-cards-universal-action.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57dca7e24cf68d0a71decc651168038a965012f7/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fenable-sso-for-your-adaptive-cards-universal-action.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d34f6e2-f1d2-4b16-b9b8-7807617581f8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/auth-flow-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b06974b59be7347fe9f482c0444dc09c465cbdc/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-flow-tab.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/980a8c9a-d385-4446-acf3-dffe3f1950c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b06974b59be7347fe9f482c0444dc09c465cbdc/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-tab-aad.md) | 86 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6a91584-9088-4721-9638-d15ae66617f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b06974b59be7347fe9f482c0444dc09c465cbdc/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-code.md) | 83 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5dd99820-0d37-480c-87b2-211669587d35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b06974b59be7347fe9f482c0444dc09c465cbdc/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-graph-api.md) | 87 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1331835-e534-473f-adcf-c3455f21e238) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b06974b59be7347fe9f482c0444dc09c465cbdc/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 86 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7fe23f8d-2697-4520-958d-488519290476) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b06974b59be7347fe9f482c0444dc09c465cbdc/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-overview.md) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84405167-5a67-4eef-b5fa-a451e3c6e7a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b06974b59be7347fe9f482c0444dc09c465cbdc/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-register-aad.md) | 92 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bb7be8c-2e81-40ef-9d37-8e037ba728c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-troubleshooting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b06974b59be7347fe9f482c0444dc09c465cbdc/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-troubleshooting.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6abf5817-4d3c-48a9-8ee1-5514ce884aee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/authentication-flow-in-universal-action-for-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b06974b59be7347fe9f482c0444dc09c465cbdc/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fauthentication-flow-in-universal-action-for-adaptive-cards.md) | 87 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c24b12b-6bee-47fd-99ad-e8033022706c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/enable-sso-for-your-adaptive-cards-universal-action.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b06974b59be7347fe9f482c0444dc09c465cbdc/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fenable-sso-for-your-adaptive-cards-universal-action.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e88c84e3-fb48-46e6-b233-5177e5df3956) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/auth-flow-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85c1e182dd7782dd286d7851aed03896cd9f5a07/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-flow-tab.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/086ea442-40e7-4439-b09d-45267697a25a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85c1e182dd7782dd286d7851aed03896cd9f5a07/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-tab-aad.md) | 86 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f18af9c2-fce9-4710-bb39-ae6278fb8b9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85c1e182dd7782dd286d7851aed03896cd9f5a07/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-code.md) | 83 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c67f4a9-297a-49e4-b2aa-66b980dc1827) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85c1e182dd7782dd286d7851aed03896cd9f5a07/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-graph-api.md) | 87 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffab5c27-57a0-42b0-bdd0-d6ffbe5c099f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85c1e182dd7782dd286d7851aed03896cd9f5a07/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 86 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e01e166a-c962-4264-aa97-5a20ed562cfd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85c1e182dd7782dd286d7851aed03896cd9f5a07/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-overview.md) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6590b50c-dba3-42c1-a87b-7e0cf24ab267) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85c1e182dd7782dd286d7851aed03896cd9f5a07/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-register-aad.md) | 92 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62bb4d95-b3a7-45a2-a671-f122daff07a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-troubleshooting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85c1e182dd7782dd286d7851aed03896cd9f5a07/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-troubleshooting.md) | 95 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a22e365-023b-427d-9b45-2d5f7a705811) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/authentication-flow-in-universal-action-for-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85c1e182dd7782dd286d7851aed03896cd9f5a07/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fauthentication-flow-in-universal-action-for-adaptive-cards.md) | 87 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28962192-1cee-4a51-849a-97134c7f9ef0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/enable-sso-for-your-adaptive-cards-universal-action.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85c1e182dd7782dd286d7851aed03896cd9f5a07/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fenable-sso-for-your-adaptive-cards-universal-action.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/adf28c59-64e8-4b63-91d9-4d761b5495a2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
