### PR TITLE
[Doc Improvement][PowerShell references: Add Azure AD and MSOnline PowerShell deprecation note][3706097]

### PR DESCRIPTION
**Pull request by TimShererWithAquent**
This PR updates 1 file with the deprecation note approved by @CelesteDG.

This update adds a note to address instances of Azure AD and MSOnline PowerShell in content.

(Never worked in this repo - let me know if I'm in the right place.)

ADO reference: 155303

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55623fee6122ea8a7d393c567ccadb826a6c4733/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-data.md) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3073994b-53bb-4f46-99b4-f26563932695) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by TimShererWithAquent** [comment]
@surbhigupta12 @omondiatieno @csmulligan This PR is ready for review.

cc @MeeraDi

**Review by omondiatieno — APPROVED** [review]
LGTM! kindly sign off after applying the suggestion in PR 2582

**Comment by MeeraDi** [comment]
#sign-off

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47ace278ef5d9d30c2d6be81e3543bdf849e6d31/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-data.md) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01854e97-d43c-4586-a935-f271087a7348) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47ace278ef5d9d30c2d6be81e3543bdf849e6d31/msteams-platform%2Fwhats-new.md) | 92 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9cff7e0e-8b5a-49b2-ba9c-c1c0f5e9473b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd6acbce18bbc124f62fdde120f342948cdf6b6e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-data.md) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ece14bd3-5f05-4fe0-8a51-7a92a984afbd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd6acbce18bbc124f62fdde120f342948cdf6b6e/msteams-platform%2Fwhats-new.md) | 92 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25fe8a1d-14eb-4791-9245-e12faa2788b0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af6bd21d7f7559e7ab325d0ba95017ce2b2f4cf/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-data.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be6742bc-f250-4b8e-ae6d-f7bebdeef9cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8af6bd21d7f7559e7ab325d0ba95017ce2b2f4cf/msteams-platform%2Fwhats-new.md) | 92 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38bec42e-be37-43ab-a6f8-a6bb6a773014) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b802e4596bec47e7955fda76497355e7a2e4b96/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-data.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79abc06a-4c39-41dd-9f69-b0b91921d0c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b802e4596bec47e7955fda76497355e7a2e4b96/msteams-platform%2Fwhats-new.md) | 92 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd32476f-306a-4d85-ace8-e8cec60cd180) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by MeeraDi** [comment]
#sign-off

**Comment by MeeraDi** [comment]
@v-vanv can you help us to get this PR merged?

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/13539d576c3985f886a0a7ef5a3218d594d63336/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-data.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/444161a3-a2bd-4096-9561-384f248d029b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/13539d576c3985f886a0a7ef5a3218d594d63336/msteams-platform%2Fwhats-new.md) | 92 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bda98253-4508-4904-8805-14aa0987703a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab5f7db5195eddfc1dfbfbf5bd1fc839a98179a0/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-data.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e1ad0e5-38d8-4402-9deb-3651c7ad0f7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab5f7db5195eddfc1dfbfbf5bd1fc839a98179a0/msteams-platform%2Fwhats-new.md) | 92 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4e2445f-22b8-4dd6-a71f-377b9bbdccdc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7102778717cb717e56b680230ff07a21276682bb/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-data.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc4567f3-ddc9-4c5a-8aa6-75c23b2b6a30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7102778717cb717e56b680230ff07a21276682bb/msteams-platform%2Fwhats-new.md) | 92 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a4c09bb-cbdb-4d11-b030-26c9167cb9de) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f0eabf9fd59d4f4424d3dd876ffd52ffef28d3f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-data.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdf8a420-da8e-4fb4-9d30-cd4f9e9a4fe5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f0eabf9fd59d4f4424d3dd876ffd52ffef28d3f/msteams-platform%2Fwhats-new.md) | 92 | 65 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab7329bd-6d20-4aca-acf0-e6fef01f2b53) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e16b6e097c023d0dd2180d2525a594cdcc04bc20/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-data.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7fa3b51-b1f0-4610-97f2-d41611429de0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e16b6e097c023d0dd2180d2525a594cdcc04bc20/msteams-platform%2Fwhats-new.md) | 90 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b265e73-141a-45ad-acc2-827831dbdf26) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
