### PR TITLE
Update meeting-app-extensibility.md

### PR DESCRIPTION
**Pull request by guneetkaurms**
Update to the Share to Stage permissions for anon, federated and guest users to add more clarity

### CODE REVIEW

**Comment by aosolis** [comment]
@surbhigupta12 can we review substantive changes like this one with the product team? This table didn't look quite right to me, so I ran it by Manasi and she confirmed some errors.

**Comment by guneetkaurms** [comment]
Hi @aosolis I had worked with Rajesh on the updates. Let me review with Manasi and fix the discrepancies.

**Comment by guneetkaurms** [comment]
I checked with Manasi. The issue is not with what was changed in this particular PR for Meeting Stage but with what was added/updated previously for Task Modules. I'll work with her and Surbhi to close the gaps.

**Comment by aosolis** [comment]
Oh, my apologies. I saw that these were the latest changes to the incorrect section, but failed to notice that you simply made editorial changes, and the substantive revision occurred much earlier.

**Pull request merged**
