### PR TITLE
remove reference to AAD tokens

### PR DESCRIPTION
**Pull request by satyakonmsft**
remove part describing future use of AAD tokens in callback notifications

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[4a76fd9](https://github.com/satyakonmsft/msteams-docs/pull/545/commits/4a76fd994b2220054fbeb3865d8f698abd028a68)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/call-notifications.md](https://github.com/satyakonmsft/msteams-docs/blob/patch-1/msteams-platform/concepts/calls-and-meetings/call-notifications.md) | :warning:Warning | | [Details](#user-content-86b64262-39ac477e)

<a id="86b64262-39ac477e"></a>
### [msteams-platform/concepts/calls-and-meetings/call-notifications.md](https://github.com/satyakonmsft/msteams-docs/blob/patch-1/msteams-platform/concepts/calls-and-meetings/call-notifications.md)
 - **Line 10**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot#creating-a-new-bot-or-adding-calling-capabilities-to-an-existing-bot).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904022118401796-545%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LZ0rkjr6anl2kyIPG0mzqPNfxnp7X8NoqvFySZ%2FZuEo%3D&st=2019-04-02T21%3A15%3A05Z&se=2019-05-03T21%3A20%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by billbliss** [comment]
I remember thinking about this originally - are we really going to expose SkypeTokens? But I agree this is a good way to limit the work and security exposure.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[4a76fd9](https://github.com/satyakonmsft/msteams-docs/pull/545/commits/4a76fd994b2220054fbeb3865d8f698abd028a68)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/call-notifications.md](https://github.com/satyakonmsft/msteams-docs/blob/patch-1/msteams-platform/concepts/calls-and-meetings/call-notifications.md) | :warning:Warning | | [Details](#user-content-86b64262-b7dc4787)

<a id="86b64262-b7dc4787"></a>
### [msteams-platform/concepts/calls-and-meetings/call-notifications.md](https://github.com/satyakonmsft/msteams-docs/blob/patch-1/msteams-platform/concepts/calls-and-meetings/call-notifications.md)
 - **Line 10**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot#creating-a-new-bot-or-adding-calling-capabilities-to-an-existing-bot).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904022134414547-545%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zkR6HGhpDHAWx4Vh2GlFFU839FswI7mle42UQyF5a0c%3D&st=2019-04-02T21%3A31%3A05Z&se=2019-05-03T21%3A36%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[65e0c74](https://github.com/satyakonmsft/msteams-docs/pull/545/commits/65e0c7492159e8a9f05d053f309501e7d1955d31)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/call-notifications.md](https://github.com/satyakonmsft/msteams-docs/blob/patch-1/msteams-platform/concepts/calls-and-meetings/call-notifications.md) | :warning:Warning | | [Details](#user-content-86b64262-2808976f)

<a id="86b64262-2808976f"></a>
### [msteams-platform/concepts/calls-and-meetings/call-notifications.md](https://github.com/satyakonmsft/msteams-docs/blob/patch-1/msteams-platform/concepts/calls-and-meetings/call-notifications.md)
 - **Line 10**: **[Warning]** Invalid file link:(~/registering-calling-bot#creating-a-new-bot-or-adding-calling-capabilities-to-an-existing-bot).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904022137447189-545%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4xsutcbLHJzXm9NvjU0hxBi7kOA7Cwd4KJuvD7%2BjWf0%3D&st=2019-04-02T21%3A34%3A07Z&se=2019-05-03T21%3A39%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[bea0dab](https://github.com/satyakonmsft/msteams-docs/pull/545/commits/bea0dabab888903a8545994acc626a562e51c832)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/call-notifications.md](https://github.com/satyakonmsft/msteams-docs/blob/patch-1/msteams-platform/concepts/calls-and-meetings/call-notifications.md) | :warning:Warning | | [Details](#user-content-86b64262-9340aa12)

<a id="86b64262-9340aa12"></a>
### [msteams-platform/concepts/calls-and-meetings/call-notifications.md](https://github.com/satyakonmsft/msteams-docs/blob/patch-1/msteams-platform/concepts/calls-and-meetings/call-notifications.md)
 - **Line 10**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot#creating-a-new-bot-or-adding-calling-capabilities-to-an-existing-bot).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904022139167762-545%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CfFufsj35TMbulj3EsscNStaU2rrAiDD36WqTe6tjjE%3D&st=2019-04-02T21%3A35%3A37Z&se=2019-05-03T21%3A40%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[7ac361e](https://github.com/satyakonmsft/msteams-docs/pull/545/commits/7ac361e1c5a113d78e502a4dfe6c97c2eb100350)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/call-notifications.md](https://github.com/satyakonmsft/msteams-docs/blob/patch-1/msteams-platform/concepts/calls-and-meetings/call-notifications.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904022140289773-545%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=DKrdV7226EpOwQKQsdaW6z%2FYx86jOZwF6Dxhv3Nxm14%3D&st=2019-04-02T21%3A37%3A18Z&se=2019-05-03T21%3A42%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[3d35d58](https://github.com/satyakonmsft/msteams-docs/pull/545/commits/3d35d58e7b50c950d48b20545c41f47cf9e2e36c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/call-notifications.md](https://github.com/satyakonmsft/msteams-docs/blob/patch-1/msteams-platform/concepts/calls-and-meetings/call-notifications.md) | :warning:Warning | | [Details](#user-content-86b64262-3bd5e6d4)

<a id="86b64262-3bd5e6d4"></a>
### [msteams-platform/concepts/calls-and-meetings/call-notifications.md](https://github.com/satyakonmsft/msteams-docs/blob/patch-1/msteams-platform/concepts/calls-and-meetings/call-notifications.md)
 - **Line 10**: **[Warning]** Illegal link: `&lt;a href=&quot;concepts/calls-and-meetings/registering-calling-bot.md#creating-a-new-bot-or-adding-calling-capabilities-to-an-existing-bot.md&quot;&gt;Registering a calling and meeting bot for Microsoft Teams&lt;/a&gt;` -- missing bookmark. The file concepts/calls-and-meetings/registering-calling-bot.md doesn&#39;t contain a bookmark named creating-a-new-bot-or-adding-calling-capabilities-to-an-existing-bot.md.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904022142060171-545%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WM%2FVZEahWK2HL6WmyDGEvbUTYhNAqYYq32fquZHw1n4%3D&st=2019-04-02T21%3A38%3A54Z&se=2019-05-03T21%3A43%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[f93878c](https://github.com/satyakonmsft/msteams-docs/pull/545/commits/f93878c0309ca705abce58db14499da27ab42a4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/call-notifications.md](https://github.com/satyakonmsft/msteams-docs/blob/patch-1/msteams-platform/concepts/calls-and-meetings/call-notifications.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904022143296246-545%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zTVHHWJ9qNjtPeWF%2BqXyB9RPNd%2Ff5BETPU3WnrIO17U%3D&st=2019-04-02T21%3A40%3A24Z&se=2019-05-03T21%3A45%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
