### PR TITLE
[Doc Improvement][Manage multiple environment and debug your Teams app for TTK]

### PR DESCRIPTION
**Pull request by v-tanmayirs**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/07ad53ed7c2d0cb683124ea9e2771510899d48d7/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f1b2980-feff-425f-a6ac-cc5889793e15) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6eb00cb20461b17c95bb2ae089ff4b5cff54460f/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8583b20-6596-4f8b-b2d8-311baead34a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6eb00cb20461b17c95bb2ae089ff4b5cff54460f/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9216c463-aa13-476d-bc2a-2d1fa3d9bbcf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf959d99ea1244081f2c19619ccf42aee09352c3/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e5ce503-bad0-4009-8e6e-72eca9abdc7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf959d99ea1244081f2c19619ccf42aee09352c3/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2778de8d-c46e-41c2-96d5-1893a13938aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf959d99ea1244081f2c19619ccf42aee09352c3/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/799c1d87-8651-49d3-9b81-85261f835095) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf959d99ea1244081f2c19619ccf42aee09352c3/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eec73df6-9627-4344-9a9f-0b98256eea1e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/662414bbcbb13a026cc8373e44a029f89b0e8d17/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07342030-cbaa-466f-a509-cfd46f02ee3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/662414bbcbb13a026cc8373e44a029f89b0e8d17/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76b36f4b-d468-4b6b-bdf6-c3d591af2863) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/662414bbcbb13a026cc8373e44a029f89b0e8d17/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e321264c-3663-4d5b-a8e3-56e8164db84e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/662414bbcbb13a026cc8373e44a029f89b0e8d17/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce902fb6-b812-4639-a90e-537b5b70c0b9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57b0abbca97de7c5d76aa7930f8bfdedd6ba6148/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e33d724a-cb43-4c1c-ad48-7ef886ca5fab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57b0abbca97de7c5d76aa7930f8bfdedd6ba6148/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c5dfb1d-97cf-4f24-b1d4-f97b432fe7d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57b0abbca97de7c5d76aa7930f8bfdedd6ba6148/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2aca708-50d6-4d5b-8e50-2a55a49a4acf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57b0abbca97de7c5d76aa7930f8bfdedd6ba6148/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5edf0ae0-723b-4ab6-adb8-9658bd07cc63) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e3372f7aacc5a14890cf3baea9c89186cc9ae8df/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91c72029-9c3e-4c86-9b7f-53dafa1b343b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e3372f7aacc5a14890cf3baea9c89186cc9ae8df/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbbb82b6-8254-4eca-9895-59cac032c7ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e3372f7aacc5a14890cf3baea9c89186cc9ae8df/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf8ef9b5-9e66-4235-b6ec-d8bcaf1cf3fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e3372f7aacc5a14890cf3baea9c89186cc9ae8df/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1d4ef6a-3c39-4788-9f82-d5c30428e182) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e97da88a7548b8d33328c81abe8a6c527df9a9f/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43bc7436-dd97-438a-bbd3-655d7ec42f57) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e97da88a7548b8d33328c81abe8a6c527df9a9f/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d65f0fcf-62c2-4f76-ad34-7fa0df509aa7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e97da88a7548b8d33328c81abe8a6c527df9a9f/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ccf317c-aec2-48c9-acb8-9fcef9cd47de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e97da88a7548b8d33328c81abe8a6c527df9a9f/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74cc4377-76da-4181-ba67-ab242ce5d2dc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7025f055df8158d2ad0fb16fa9373b2f4baddcd5/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a85c2577-ad28-49a4-a0ba-243c63feb1db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7025f055df8158d2ad0fb16fa9373b2f4baddcd5/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7772f51-e8c4-4b05-8c31-4784486875cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7025f055df8158d2ad0fb16fa9373b2f4baddcd5/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bb771ec-0016-4bcc-b300-bf22ca89a33c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7025f055df8158d2ad0fb16fa9373b2f4baddcd5/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ed4ae08-2bbf-41e7-9c75-abddc02867cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7025f055df8158d2ad0fb16fa9373b2f4baddcd5/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/940053b0-adb5-49c4-b344-8ace31bd477f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea0240d4ae4246e8f810c99048ee488d5d1c5f57/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7b8b9a5-20e8-4d18-b178-56b08d764e26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea0240d4ae4246e8f810c99048ee488d5d1c5f57/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 93 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f2b2310-f2ee-43e9-ae7e-1ce5d7406f1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea0240d4ae4246e8f810c99048ee488d5d1c5f57/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/538b2f00-30b2-4115-845a-7b6ea528a94a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea0240d4ae4246e8f810c99048ee488d5d1c5f57/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b1e924b-dc9b-4c97-848e-7ee12f637aa3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea0240d4ae4246e8f810c99048ee488d5d1c5f57/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a88022d2-e1b8-41e3-9e5e-45c5d4158291) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfe7ba508396b9cbe75633d2e4d8a753d0f6286f/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a66862ed-e35e-4ed3-9176-291fd4d44a0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfe7ba508396b9cbe75633d2e4d8a753d0f6286f/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 92 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9c9924d-ba4f-424e-bcd9-17730bb361b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfe7ba508396b9cbe75633d2e4d8a753d0f6286f/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91f567c3-caec-417f-8c6f-2148f213b600) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfe7ba508396b9cbe75633d2e4d8a753d0f6286f/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9fc8c929-ecd1-4810-ac2a-872697c65cbc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dfe7ba508396b9cbe75633d2e4d8a753d0f6286f/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef4dd037-f4d1-43d1-9adf-bc1addf0e0c9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9160f4a7a39f1f9d6378f84ac3e12603ca26f1a1/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30f60949-7d05-4054-83e4-a041671cbd18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9160f4a7a39f1f9d6378f84ac3e12603ca26f1a1/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 92 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0dbe8520-cb70-405c-acea-f1aea1d6ef26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9160f4a7a39f1f9d6378f84ac3e12603ca26f1a1/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9be82e14-5ed4-4a4e-b0b0-985d45b842c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9160f4a7a39f1f9d6378f84ac3e12603ca26f1a1/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3292c550-e124-40e3-b4c0-fd1a77dc72d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9160f4a7a39f1f9d6378f84ac3e12603ca26f1a1/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dcf7d718-da05-40e2-8021-bea4cb308117) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df70269032a463cd97e5c9ed54f41549fd92a31e/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1009a196-954d-48bc-b4aa-6a5ccb301e48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df70269032a463cd97e5c9ed54f41549fd92a31e/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 92 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d97d9845-6385-4d6d-ac24-dd0dac744de7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df70269032a463cd97e5c9ed54f41549fd92a31e/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/684f0b45-0448-48e6-8a3b-af48543cb5f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df70269032a463cd97e5c9ed54f41549fd92a31e/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2721a170-2d7c-4b4b-a114-426b370dc5f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df70269032a463cd97e5c9ed54f41549fd92a31e/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e62912c-5304-47ae-ad4a-be212e3703d1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-abirade** [comment]
The content has been merged with PR #6470.

**Pull request closed without merging**
