### PR TITLE
[Doc Improvement][Verify and fix sign in and casing][3008097]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c51b4fc33ec18d5b6558b3ec3a77009812ca7163/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-advanced-ui-components.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cea2bf82-14e5-4e70-a412-3f89b048e130) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c1c36f666c79e5996f8ef83a2eda23fe30dc436/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-advanced-ui-components.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64fd9d8d-d73a-4474-9af2-247a4d5ffb25) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c1c36f666c79e5996f8ef83a2eda23fe30dc436/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b613dd71-c127-4070-9e73-8dc63d3a5bad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c1c36f666c79e5996f8ef83a2eda23fe30dc436/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af46c455-f9fc-444b-9e2f-356664999053) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/533822c6444236dcf0103f7d616d7233a88af38d/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-advanced-ui-components.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0239194e-360c-48b5-9c58-0f8bb12d6d47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/533822c6444236dcf0103f7d616d7233a88af38d/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c53290a-5bab-4f4a-9f4e-0936fe9a6d9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/533822c6444236dcf0103f7d616d7233a88af38d/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7732701-738c-4c4f-9fac-a020b6a754fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/explore-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/533822c6444236dcf0103f7d616d7233a88af38d/msteams-platform%2Ftoolkit%2Fexplore-Teams-Toolkit.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d557480e-7e39-4442-90a3-289befbf515a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/533822c6444236dcf0103f7d616d7233a88af38d/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfe353fc-4e0a-4775-9f89-ecdf1b2eed0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/533822c6444236dcf0103f7d616d7233a88af38d/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79933d82-5908-4b68-8fe1-98bf3661d658) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa5408f93a678c66251c4601b6d4b25c8fc422b0/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a2be6bb-7c75-44dd-9d7f-b35c14da3763) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa5408f93a678c66251c4601b6d4b25c8fc422b0/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d52e9836-5c5c-452a-b63d-b7588d762ec4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/explore-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa5408f93a678c66251c4601b6d4b25c8fc422b0/msteams-platform%2Ftoolkit%2Fexplore-Teams-Toolkit.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac94ca28-c725-41ca-9ed4-71a13aa6cc44) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f22aa619c8eaf0375803d51cae3bf4a2c643a1d1/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bd09091-f121-41b2-82f7-39cf42db7b69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f22aa619c8eaf0375803d51cae3bf4a2c643a1d1/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a9b081d-3f4e-4ddc-a3eb-a54e96e45d54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/explore-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f22aa619c8eaf0375803d51cae3bf4a2c643a1d1/msteams-platform%2Ftoolkit%2Fexplore-Teams-Toolkit.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45f56636-3c63-4f58-b26d-8c9c65bbff97) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cf69402d8f0f4d2fc664778e07f32ea680c7641/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e938e78-4068-4b0d-b3fb-c1674784cf80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cf69402d8f0f4d2fc664778e07f32ea680c7641/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75ab761a-c129-4a5c-aa51-1bc4247a709d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/explore-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cf69402d8f0f4d2fc664778e07f32ea680c7641/msteams-platform%2Ftoolkit%2Fexplore-Teams-Toolkit.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7254e827-d6c4-4c6d-b529-27583021823e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/23ec166b3b374032332b31b915c13983f18517df/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7f6dc43-8f49-49a5-812a-d4f273ed8103) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/23ec166b3b374032332b31b915c13983f18517df/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f1ea592-42ca-4eb5-88af-a2cc9695f001) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c5547c829bd8c3020565bdfb9b3a46e64aea7944/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49796c23-3b1b-46ef-84e5-9befa67ac469) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c5547c829bd8c3020565bdfb9b3a46e64aea7944/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f93208a-268c-4ecc-97d8-f1dbd8a6e9ef) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6d6e8c06c889dba4e772eeee50e53a1ae8c4e62/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96632ed5-46da-4aeb-b862-d975f7288924) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6d6e8c06c889dba4e772eeee50e53a1ae8c4e62/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a42267b6-f27f-4763-bdbe-d6135797fed6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
