### PR TITLE
Update Live Share docs with preview 4 syntax

### PR DESCRIPTION
**Pull request by ryanbliss**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-canvas.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aac8faf2a87684576f3459af734637170cc02d47/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-canvas.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7ebdca2-a346-4cf2-9e40-57e670977466) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aac8faf2a87684576f3459af734637170cc02d47/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-capabilities.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1ceb321-c200-43af-af31-b2a5d8223134) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aac8faf2a87684576f3459af734637170cc02d47/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-media-capabilities.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e38fcd68-7654-4a68-bcdf-dde76a63d091) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aac8faf2a87684576f3459af734637170cc02d47/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23d4d75e-aa7e-45bb-a368-3c4378099387) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aac8faf2a87684576f3459af734637170cc02d47/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31073682-9047-438a-8b69-6355500d8ae5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-canvas.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9309d0247d29315fbde39485fe22347164e1bfa9/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-canvas.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45d5801a-6a7e-43a5-be84-3521210c4fd3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9309d0247d29315fbde39485fe22347164e1bfa9/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-capabilities.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/920aab28-a28f-4f38-936e-04ff2bf875b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9309d0247d29315fbde39485fe22347164e1bfa9/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-media-capabilities.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6271afd9-6dc9-434e-b41d-61f096c8a282) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9309d0247d29315fbde39485fe22347164e1bfa9/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbc05f83-e35e-4c2c-bb38-2cb26f827f67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9309d0247d29315fbde39485fe22347164e1bfa9/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34e33f67-5c89-474a-81e6-441e08b8a4b3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-canvas.md](https://github.com/MicrosoftDocs/msteams-docs/blob/966052e4adb305e7cbeb0b117c60fb293f65b756/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-canvas.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4369a9ff-2896-4a40-ae9b-6040991cbcd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/966052e4adb305e7cbeb0b117c60fb293f65b756/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-capabilities.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54c7693a-91f3-47ea-8d2a-b22cf9816d72) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-how-to/how-to-custom-azure-fluid-relay.md](https://github.com/MicrosoftDocs/msteams-docs/blob/966052e4adb305e7cbeb0b117c60fb293f65b756/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-how-to%2Fhow-to-custom-azure-fluid-relay.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/609444f0-0f7e-473f-9b9b-c28c049b4a22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/966052e4adb305e7cbeb0b117c60fb293f65b756/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-media-capabilities.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce2b6958-d885-4c08-99db-a63bca1b7caa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/966052e4adb305e7cbeb0b117c60fb293f65b756/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e63da7e1-a2fc-4125-8386-4a9159a89899) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/966052e4adb305e7cbeb0b117c60fb293f65b756/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35760096-5671-48c5-a3a7-3f29188f7a02) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-canvas.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2527f300a1b77ec01906481e506250aab390fe7d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-canvas.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb47a3d7-1b26-4d25-b8f4-007d994916a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2527f300a1b77ec01906481e506250aab390fe7d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-capabilities.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2603768-7852-425d-8dd0-ffd01c20d9ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-how-to/how-to-custom-azure-fluid-relay.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2527f300a1b77ec01906481e506250aab390fe7d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-how-to%2Fhow-to-custom-azure-fluid-relay.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2e3fb2e-c5ec-4d0f-aae6-a4b14ba2f3bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2527f300a1b77ec01906481e506250aab390fe7d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-media-capabilities.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a7b8b24-0fd1-4067-973c-4faaf414b06c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2527f300a1b77ec01906481e506250aab390fe7d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38c81b79-3117-4fa5-97b7-fc9dcb49df4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2527f300a1b77ec01906481e506250aab390fe7d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cdee683-515a-4e37-b11e-c9af7e1d148a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-ypalikila — APPROVED** [review]
Approved.

**Pull request merged**
