### PR TITLE
[Doc Improvement][Get Started Basic Checks]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d1778973aefb90fe1b926753dc9f33e6729e1b93/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a856056-5a8b-497a-aa11-a1de4c9d19ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d1778973aefb90fe1b926753dc9f33e6729e1b93/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66e9c8c1-8d5c-4964-8c91-3683c9b6e15e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c55dfdaeee6483ea27efbb8eb6054854e092b46/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4dfda69-1c99-4b3f-8490-0104536359c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c55dfdaeee6483ea27efbb8eb6054854e092b46/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78b26d42-66eb-4f6d-8f28-e39baabeafc2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c55dfdaeee6483ea27efbb8eb6054854e092b46/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3388acc6-37f3-4e41-b6d2-c0a0f1ff754c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c55dfdaeee6483ea27efbb8eb6054854e092b46/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f929d19-31b9-403a-acf7-0759b734e42f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c55dfdaeee6483ea27efbb8eb6054854e092b46/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7437512d-9f5a-496f-9c4c-8f997c62fac6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20a33a94d71d02bcc0396d8bf878050eb4a2dc81/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/711a4420-a8ad-4873-886c-90bb2f3bbc48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20a33a94d71d02bcc0396d8bf878050eb4a2dc81/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98fe3b93-f266-4911-a004-021ed4679535) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20a33a94d71d02bcc0396d8bf878050eb4a2dc81/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29b18f16-d107-4e75-bef4-d0c5d023194a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20a33a94d71d02bcc0396d8bf878050eb4a2dc81/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0f851e3-1ce3-43f7-87fa-b33de4564ac5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20a33a94d71d02bcc0396d8bf878050eb4a2dc81/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1718fcbd-7801-4171-8c47-0491b0065f98) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20a33a94d71d02bcc0396d8bf878050eb4a2dc81/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6850d362-19e8-425a-97cf-0a19116a64f9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/203c1b328dc3a59e5d4f00b914809473723bd377/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ac81f8d-9719-4782-bb0e-7a582be0f4ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/203c1b328dc3a59e5d4f00b914809473723bd377/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f93f6079-9eb2-451e-8980-bea8b80876ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/203c1b328dc3a59e5d4f00b914809473723bd377/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2dafa337-88b4-4ad8-b2f1-91906d9ddd4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/203c1b328dc3a59e5d4f00b914809473723bd377/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a11e965-d8bc-4272-a459-5af030f1c2b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/203c1b328dc3a59e5d4f00b914809473723bd377/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea6d1e15-e309-432e-867a-50fd0cf94170) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/203c1b328dc3a59e5d4f00b914809473723bd377/msteams-platform%2Fget-started%2Fglossary.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/353e9c7e-24f0-476b-bf4b-363bc2b319fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/203c1b328dc3a59e5d4f00b914809473723bd377/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d8d9617-80af-4e96-9bef-a94ef8b71450) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74fe84125ad3df703ed6269ae8aa809a3f012b26/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a89d893-b5b2-4624-b976-94cc86649bf6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74fe84125ad3df703ed6269ae8aa809a3f012b26/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a6f5b9a-ba9f-40a7-b22a-5018263fc58e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74fe84125ad3df703ed6269ae8aa809a3f012b26/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0abf71e6-a9ef-4475-9198-015d6916e982) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74fe84125ad3df703ed6269ae8aa809a3f012b26/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d76ab20-6bae-4d9d-a04a-fec4d7efdf7c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74fe84125ad3df703ed6269ae8aa809a3f012b26/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0a593af-7630-41eb-95ec-464d2f130ed9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74fe84125ad3df703ed6269ae8aa809a3f012b26/msteams-platform%2Fget-started%2Fglossary.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c652ec77-8c21-457f-ac57-5e0c647b0e5a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74fe84125ad3df703ed6269ae8aa809a3f012b26/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3ec8593-6d0e-4655-8849-1bad25ba8c36) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/build-basic-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d71453946a6171808109f439e8f6cf0d41f267dd/msteams-platform%2Fget-started%2Fbuild-basic-tab-app.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04dbb3d0-2b54-41fb-b7bd-efd134f7285f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d71453946a6171808109f439e8f6cf0d41f267dd/msteams-platform%2Fget-started%2Fbuild-message-extension.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce1c4321-80fa-430b-87c9-2cc760d0d659) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/build-notification-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d71453946a6171808109f439e8f6cf0d41f267dd/msteams-platform%2Fget-started%2Fbuild-notification-bot.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb01d994-cebe-4fb3-b07f-7fcc71e5ea33) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d71453946a6171808109f439e8f6cf0d41f267dd/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2262134e-0be8-4b6c-a2ae-81e5408ca2ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d71453946a6171808109f439e8f6cf0d41f267dd/msteams-platform%2Fget-started%2Fget-started-overview.md) | 90 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78bf1567-deaf-4788-8223-72f4e2529278) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d71453946a6171808109f439e8f6cf0d41f267dd/msteams-platform%2Fget-started%2Fglossary.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae1df31f-06aa-4eda-b422-bb695891975f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d71453946a6171808109f439e8f6cf0d41f267dd/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c3d24ed-97b8-42fa-a94a-61d1a8ab935f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Pull request merged**
