### PR TITLE
[Doc Improvement][Bot-ratelimit-note-update][2471018]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/edc7f3dabc6e6ed042111439430a9983a1d3ae7c/msteams-platform%2FTOC.yml) | 97 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ddaaa68-d4c6-445a-b2b0-863e8a9da3b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/rate-limit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/edc7f3dabc6e6ed042111439430a9983a1d3ae7c/msteams-platform%2Fbots%2Fhow-to%2Frate-limit.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/836335b4-7241-41c7-9776-5f13dc35e918) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/edc7f3dabc6e6ed042111439430a9983a1d3ae7c/msteams-platform%2Fresources%2Fteam-chat-member-api-changes.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46737e98-c9aa-4a6d-bb65-1130bde0ebee) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/01080d59ff291553e6debc437adb50cc1986676a/msteams-platform%2FTOC.yml) | 97 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f264819e-d8ce-414a-ba23-3aa828a575f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/rate-limit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01080d59ff291553e6debc437adb50cc1986676a/msteams-platform%2Fbots%2Fhow-to%2Frate-limit.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0bc0e1c-623d-4e80-ba5f-d6fe473ac1e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01080d59ff291553e6debc437adb50cc1986676a/msteams-platform%2Fresources%2Fteam-chat-member-api-changes.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4298c6f5-14a0-4ab2-b4dc-b8a52d788e16) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — COMMENTED** [review]
Approved

**Review by Wajeed-msft — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/72989497446c813c0c92d76b596f94364b383b52/msteams-platform%2FTOC.yml) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25e5b0de-bc23-4dd3-88a0-c8ecaf5b0be0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/rate-limit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72989497446c813c0c92d76b596f94364b383b52/msteams-platform%2Fbots%2Fhow-to%2Frate-limit.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9914581-03a2-46bc-a8fb-8e1a00aa1c59) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72989497446c813c0c92d76b596f94364b383b52/msteams-platform%2Fresources%2Fteam-chat-member-api-changes.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68e5b116-f89d-4e3d-8b64-6f0c7b786ae8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
