### PR TITLE
Change absolute link to docs.microsoft to relative links

### PR DESCRIPTION
**Pull request by ashishguptaiitb**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-commandbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/15a5d934501a1d2607ae3056d9d50055c2f3f29e/msteams-platform%2Fsbs-gs-commandbot.yml) | 90 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad6ee544-36e2-42a4-bcbf-009dbcb7f8f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/15a5d934501a1d2607ae3056d9d50055c2f3f29e/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52361312-181a-4764-91ba-eca56dd0e19b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/15a5d934501a1d2607ae3056d9d50055c2f3f29e/msteams-platform%2Fsbs-meetings-stage-view.yml) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6e17cbf-6ad6-4999-a0fa-d11c020b3805) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/15a5d934501a1d2607ae3056d9d50055c2f3f29e/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/634aae67-5de1-4ea1-8b67-0463e9caf634) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/15a5d934501a1d2607ae3056d9d50055c2f3f29e/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 83 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/386373e4-1ba5-43fb-875d-6a5dcdf5a712) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by ashishguptaiitb** [comment]
@surbhigupta12 , please verify on stage and approve and merge.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-commandbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/423a48580a00e880eb5eee4f329c8d8d3c8c2ff3/msteams-platform%2Fsbs-gs-commandbot.yml) | 90 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4fff62f2-072d-45fd-8cd4-4cd502c46479) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/423a48580a00e880eb5eee4f329c8d8d3c8c2ff3/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99318c04-caff-450f-936c-41f4cb86b585) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/423a48580a00e880eb5eee4f329c8d8d3c8c2ff3/msteams-platform%2Fsbs-meetings-stage-view.yml) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7447136a-1feb-4138-b589-afa4172a046a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/423a48580a00e880eb5eee4f329c8d8d3c8c2ff3/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcf6f52c-3d22-45d4-98a4-8e8edc1f6ee5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/423a48580a00e880eb5eee4f329c8d8d3c8c2ff3/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 83 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e763e7b-dae5-4e64-a448-d93aa248e705) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by ashishguptaiitb** [comment]
@surbhigupta12 and @v-habibaumme , please review and merge.

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
