### PR TITLE
[Doc Improvement][Infographic update for dev docs continued][3174752]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/collaboration-control.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad84346f4996241cc91e903b6bfb4a3f742233be/msteams-platform%2Fsamples%2Fcollaboration-control.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90fe52e3-af43-4f7e-906f-1684f54caf8e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad84346f4996241cc91e903b6bfb4a3f742233be/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ecae4df7-9abd-4ef0-9436-0f75f205b2d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-for-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad84346f4996241cc91e903b6bfb4a3f742233be/msteams-platform%2Fsamples%2Fvirtual-tables-for-tasks.md) | 87 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe59a935-42ae-4ca8-a14d-12fd4a2fe8ea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/collaboration-control.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c45990441ce05fb730a27b10a8254b9612af987d/msteams-platform%2Fsamples%2Fcollaboration-control.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3efd4c35-3e2f-4299-9db2-c77052ac0954) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c45990441ce05fb730a27b10a8254b9612af987d/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82266841-b9fb-4e36-b31a-85655942ce30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-for-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c45990441ce05fb730a27b10a8254b9612af987d/msteams-platform%2Fsamples%2Fvirtual-tables-for-tasks.md) | 87 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8cfc55c-9925-4c89-89b9-a9d246add595) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/collaboration-control.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48edf7da9bf6cecb72fd342406d9ef57b0b74758/msteams-platform%2Fsamples%2Fcollaboration-control.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ad1ea05-20b9-4ec0-a9c3-46bbf57d5ecd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48edf7da9bf6cecb72fd342406d9ef57b0b74758/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0b99093-71a3-4a56-9585-08411159166d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-for-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48edf7da9bf6cecb72fd342406d9ef57b0b74758/msteams-platform%2Fsamples%2Fvirtual-tables-for-tasks.md) | 87 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cca7ea28-c466-41e4-b0bb-47ef1e407fbb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/collaboration-control.md](https://github.com/MicrosoftDocs/msteams-docs/blob/260d9785dfdfae967e252317aa46d930676d406f/msteams-platform%2Fsamples%2Fcollaboration-control.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0a757b5-f6f0-4c42-9ab3-ee0b0536ada8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/260d9785dfdfae967e252317aa46d930676d406f/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35307f64-4259-419c-9ef9-bb544d8710db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-for-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/260d9785dfdfae967e252317aa46d930676d406f/msteams-platform%2Fsamples%2Fvirtual-tables-for-tasks.md) | 87 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cbf0b1d-8c49-49e9-ba07-05e2ec1e0424) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/collaboration-control.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05c215dead624b2f508b1dea448b153bd432ffa8/msteams-platform%2Fsamples%2Fcollaboration-control.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a73ab840-2812-4f6e-9b2f-62b58c766e37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05c215dead624b2f508b1dea448b153bd432ffa8/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce53ff7e-8c03-441a-a847-56108ff7d3c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-for-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05c215dead624b2f508b1dea448b153bd432ffa8/msteams-platform%2Fsamples%2Fvirtual-tables-for-tasks.md) | 90 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bd26866-c220-414d-b084-032af3510f3e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/collaboration-control.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1ac5a05f9dade798049083c2107fadf1fb0cc3d/msteams-platform%2Fsamples%2Fcollaboration-control.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d166fd1a-1d94-49b5-a8bb-6490eaeedbaf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1ac5a05f9dade798049083c2107fadf1fb0cc3d/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28585d7c-3abd-449b-90d9-d74e10b6946e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-for-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1ac5a05f9dade798049083c2107fadf1fb0cc3d/msteams-platform%2Fsamples%2Fvirtual-tables-for-tasks.md) | 90 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f39ecd4d-2ce6-45fb-bd59-9a821fc51319) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/collaboration-control.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b84a77feaf63dcb06f671c06c372cf01df921909/msteams-platform%2Fsamples%2Fcollaboration-control.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee85ee47-0a86-4d99-869c-0eeddcf1b366) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b84a77feaf63dcb06f671c06c372cf01df921909/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7815b363-6571-4bc2-a151-4f62ead1a0f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-for-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b84a77feaf63dcb06f671c06c372cf01df921909/msteams-platform%2Fsamples%2Fvirtual-tables-for-tasks.md) | 90 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b469134-45ac-4dc9-95d5-b804cdcd1696) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/collaboration-control.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6401d9a946fe1b25b3b9549aab5442b5dd512332/msteams-platform%2Fsamples%2Fcollaboration-control.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71ba2ae5-11a6-419f-96a0-3de2c1866411) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6401d9a946fe1b25b3b9549aab5442b5dd512332/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e15d5645-9b4a-4aef-97e0-52b6700afb30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-for-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6401d9a946fe1b25b3b9549aab5442b5dd512332/msteams-platform%2Fsamples%2Fvirtual-tables-for-tasks.md) | 90 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf2996c9-a65f-4646-aba2-6635ff32565c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
