### PR TITLE
chetsharma/code snippets comments updates

### PR DESCRIPTION
**Pull request by ChetanSharma-msft**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e6b230f45a8bc0f2b3f337998fb07f166c82a6/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 93 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da0fc6bb-31a3-44d1-9bb5-b4c0078eccea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e6b230f45a8bc0f2b3f337998fb07f166c82a6/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a28d7dd-d150-4566-9e78-bd472738dd07) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e6b230f45a8bc0f2b3f337998fb07f166c82a6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d7b21b2-2924-409d-b7f6-19503b013789) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e6b230f45a8bc0f2b3f337998fb07f166c82a6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc03ea6b-4886-4ccc-a271-104e73f29597) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e6b230f45a8bc0f2b3f337998fb07f166c82a6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47db931a-190f-4b81-99fe-610238d45d4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e6b230f45a8bc0f2b3f337998fb07f166c82a6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6983e4a-17b1-40fa-85a3-88802c17716f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e6b230f45a8bc0f2b3f337998fb07f166c82a6/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2272d24-9715-4bfd-baf5-2361e02824cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e6b230f45a8bc0f2b3f337998fb07f166c82a6/msteams-platform%2Fbots%2Fhow-to%2Fupdate-and-delete-bot-messages.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/962da3f7-c237-400c-94f0-ccaa6ec100e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e6b230f45a8bc0f2b3f337998fb07f166c82a6/msteams-platform%2Fgraph-api%2Fproactive-bots-and-messages%2Fgraph-proactive-bots-and-messages.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74f51859-2aed-478f-a72e-29e01cc21a29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e6b230f45a8bc0f2b3f337998fb07f166c82a6/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcc362d9-713f-47ba-a2f7-5d3d79a80404) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e6b230f45a8bc0f2b3f337998fb07f166c82a6/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e00aeae9-2c8d-485e-86e3-10a8943c2e3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e6b230f45a8bc0f2b3f337998fb07f166c82a6/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-graph-api.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5a97c24-a00f-4010-bf67-46d96fd11b6c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6e8a4ed906f488f73a366935b22931beab158dd/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 93 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95fb7e3b-0795-43a7-8f99-83d6d774fc8e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6e8a4ed906f488f73a366935b22931beab158dd/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/511ac870-069a-40d8-b172-741cc3f1e47f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aacd67fe74b5d881d3496d23ffe31e140ad75ffd/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 93 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b230ee03-0e07-4b3b-85c2-f80d6e650e13) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aacd67fe74b5d881d3496d23ffe31e140ad75ffd/msteams-platform%2Fbots%2Fhow-to%2Fupdate-and-delete-bot-messages.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6655a732-5368-40f9-831a-ec4a7cd06a42) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aacd67fe74b5d881d3496d23ffe31e140ad75ffd/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b805de4-b1c2-4600-939a-e7761d48bf61) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e723af261fecd3df7403296d93bb5666646970c/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 93 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bd5e1ee-fe15-4563-a06d-976dfbeb7947) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e723af261fecd3df7403296d93bb5666646970c/msteams-platform%2Fbots%2Fhow-to%2Fupdate-and-delete-bot-messages.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6312e0b0-873d-47ed-9adf-370902611476) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e723af261fecd3df7403296d93bb5666646970c/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5bcfbc0-854f-461d-a5a7-525e43b1851b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-ypalikila — APPROVED** [review]
Approved.

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d426d94d5f136ee150494ba6c2fdf3932cc8c084/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 93 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c6a5eea-3325-486b-8128-4dfd11221edc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/update-and-delete-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d426d94d5f136ee150494ba6c2fdf3932cc8c084/msteams-platform%2Fbots%2Fhow-to%2Fupdate-and-delete-bot-messages.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62166dc9-5c25-4031-b249-d595d6736038) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d426d94d5f136ee150494ba6c2fdf3932cc8c084/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fcf6b01-aa20-4f22-af7e-3fe031614e5d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
