### PR TITLE
Change absolute docs links to learn links

### PR DESCRIPTION
**Pull request by ashishguptaiitb**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/602d3cad6b423afdc3c51b6d7831a1efbdbbcd37/msteams-platform%2Findex.yml) | 94 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc594d48-011b-4bf1-852b-b4c39dcd25e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/602d3cad6b423afdc3c51b6d7831a1efbdbbcd37/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a35fae9a-ba3d-4620-b811-6bbe9737ae95) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/602d3cad6b423afdc3c51b6d7831a1efbdbbcd37/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-actions.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3c5357c-dde9-4403-99aa-20874ec5420a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/602d3cad6b423afdc3c51b6d7831a1efbdbbcd37/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-using.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f077c18d-155f-45bf-a072-d3793fc1d77a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2562a16a1d7e4bef655faa385adefdcbcc2b6a9f/msteams-platform%2Findex.yml) | 94 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce7de24a-4819-4f43-ad06-0151ab6ef379) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2562a16a1d7e4bef655faa385adefdcbcc2b6a9f/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35e4b76b-a367-4fbf-8dce-5f405a4a37f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-commandbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2562a16a1d7e4bef655faa385adefdcbcc2b6a9f/msteams-platform%2Fsbs-gs-commandbot.yml) | 90 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d6c5985-dd19-4c53-9fe9-fcb7b82b57b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2562a16a1d7e4bef655faa385adefdcbcc2b6a9f/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39778d80-da7d-4709-af24-d0f8802d5e67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2562a16a1d7e4bef655faa385adefdcbcc2b6a9f/msteams-platform%2Fsbs-meetings-stage-view.yml) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c444dadf-fe4b-42f4-8573-df9853110a6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2562a16a1d7e4bef655faa385adefdcbcc2b6a9f/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2577d26a-35fd-40ad-8b7e-9366fcface5a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2562a16a1d7e4bef655faa385adefdcbcc2b6a9f/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 83 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b6b7206-eb24-40fc-8f1c-dda76dcf6adb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2562a16a1d7e4bef655faa385adefdcbcc2b6a9f/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-actions.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2bf64ee-239b-44b8-9bab-69bb899aa9e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2562a16a1d7e4bef655faa385adefdcbcc2b6a9f/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-using.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93d2f5e0-6f06-4bd2-a71a-5a1a8d48dacf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by ashishguptaiitb** [comment]
Hi @Wajeed-msft and @surbhigupta12 , need your review for this PR. These changes should go live (immediately) after rebranding when learn links are active. 

CC @v-habibaumme as FYI.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ff256d4b7352bb70dda238315745a07593b450fd/msteams-platform%2Findex.yml) | 94 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1eedb8cc-9e28-4e7b-acf3-fe2abd7528e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff256d4b7352bb70dda238315745a07593b450fd/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a7a9f94-2020-4329-9313-198f0b3e46b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-commandbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ff256d4b7352bb70dda238315745a07593b450fd/msteams-platform%2Fsbs-gs-commandbot.yml) | 90 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/105244e7-8716-4aef-b986-b05843e3e6b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ff256d4b7352bb70dda238315745a07593b450fd/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9111ba13-be98-4eda-8f4f-fffec9ccfc43) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ff256d4b7352bb70dda238315745a07593b450fd/msteams-platform%2Fsbs-meetings-stage-view.yml) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55b340e4-b89c-4718-914b-2ed09fc640f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ff256d4b7352bb70dda238315745a07593b450fd/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3208ea3d-3e4c-4ccb-9654-f080c87d782f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ff256d4b7352bb70dda238315745a07593b450fd/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 83 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81dba6f4-8261-426e-aed3-41cf943c2144) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff256d4b7352bb70dda238315745a07593b450fd/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-actions.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5dfbe567-ff86-4f9f-96b3-f160c068feea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff256d4b7352bb70dda238315745a07593b450fd/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-using.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ba94a2a-1f49-4910-95e5-1102377ddec5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
