### PR TITLE
[Doc Improvement][Update on JavaScript code][3368532]

### PR DESCRIPTION
**Pull request by v-ganr**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/messaging-extensions/msgex-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1428e5c5c9e82217de9ff839749161d705fd660c/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmsgex-sso-code.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80209065-2f22-4363-b75b-e8c5b3227fa3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea763440da73fe21386329075098477f675deb5a/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b20de279-06b5-4d30-8db6-0083f64a5e0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/msgex-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea763440da73fe21386329075098477f675deb5a/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmsgex-sso-code.md) | 94 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a95241e8-7a65-4dde-97d5-89d79c47a966) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d35dff92db6cabb926eca0832567374bf8f65fc9/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e79dd65c-663f-456b-b127-04ac2e7e2d45) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/msgex-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d35dff92db6cabb926eca0832567374bf8f65fc9/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmsgex-sso-code.md) | 94 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5fdfa0a7-1d4d-4d3f-9b58-1dd46cfb825a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6023c3f47476268828e4cb80fd13618ff893333f/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d977f2ea-ada8-43db-b76f-44530a850723) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/msgex-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6023c3f47476268828e4cb80fd13618ff893333f/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmsgex-sso-code.md) | 96 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf138525-716d-40ff-9e84-eca9dc8f3449) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1e60352507bf4529efd6fff0f15cfe75d50291c/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8376089a-ae99-4989-9f07-cf90fa876496) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/msgex-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a1e60352507bf4529efd6fff0f15cfe75d50291c/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmsgex-sso-code.md) | 94 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9cb73dd-6ee5-430b-8743-cbd2b2b9a39f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/11ca6c0a6030d4ce03dbfa3edf6c770ea7a8b333/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79feeba9-4b7d-4d98-a410-4175b15ee325) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/msgex-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/11ca6c0a6030d4ce03dbfa3edf6c770ea7a8b333/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmsgex-sso-code.md) | 94 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe2f403a-09b2-4f71-b6b2-08d12bb199f2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
