### PR TITLE
[Doc Improvement][Updated API-based ME SBS titles][3970771]

### PR DESCRIPTION
**Pull request by v-shalinir**
Title content from API ME PR.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e8597ad17156ab7b9ae5594ed2bbf52c7b6a9260/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 73 | 120 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a282cff2-fc02-49a5-a019-1f8ed76078b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-msg-ext-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e8597ad17156ab7b9ae5594ed2bbf52c7b6a9260/msteams-platform%2Fsbs-api-msg-ext-ttk.yml) | 82 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f432aaa-6951-4806-8942-06241adab4a0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/55d6983064fe6707c00382d493531df0c7ac1ef9/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 75 | 115 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f406c6ce-a7a1-447a-9007-3259befe8e62) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-msg-ext-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/55d6983064fe6707c00382d493531df0c7ac1ef9/msteams-platform%2Fsbs-api-msg-ext-ttk.yml) | 82 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dddc0475-ca5f-4bd9-b30b-1bddcca877ea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd2fcdbdc358d6fb77ef8a5833610f99576a282/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 76 | 110 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c1ea173-e136-4bd5-b831-e668e109e75c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-msg-ext-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd2fcdbdc358d6fb77ef8a5833610f99576a282/msteams-platform%2Fsbs-api-msg-ext-ttk.yml) | 82 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/910e0838-dcc8-420a-92c3-eb24dfa36981) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aec7dd58e996f1277fbc41771ba296edc6f8eb7d/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 76 | 109 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cae1f146-0395-45ef-8d2e-8fc23468534c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-msg-ext-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aec7dd58e996f1277fbc41771ba296edc6f8eb7d/msteams-platform%2Fsbs-api-msg-ext-ttk.yml) | 82 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0478a831-fcc8-4be8-9402-3b6dea1e401b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/858767c5f13782b539f11b5768918818e41674ea/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 107 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/259bde89-6b56-47da-8afa-43c894bb54e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-msg-ext-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/858767c5f13782b539f11b5768918818e41674ea/msteams-platform%2Fsbs-api-msg-ext-ttk.yml) | 82 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d006d019-b028-416d-b266-080d488a93d0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d329e67fc48fd22f0f288df4c7e2313df2b4c9f7/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 107 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3654bb18-6277-4119-b09b-00e3e4b84d43) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-msg-ext-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d329e67fc48fd22f0f288df4c7e2313df2b4c9f7/msteams-platform%2Fsbs-api-msg-ext-ttk.yml) | 82 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb17af78-9a82-44bf-81eb-79f8db7a1dba) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
