### PR TITLE
[Doc Improvement][Analyze your apps usage in Developer Portal]

### PR DESCRIPTION
**Pull request by v-vvchaganti**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/analyze-your-apps-usage-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/34769111f13026a3902cd514a3772ccb6a0636a6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fanalyze-your-apps-usage-in-developer-portal.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3890f82f-58d5-46e0-b1e6-b7b7706f4d3b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/analyze-your-apps-usage-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be5d649dafd5ddddc66b87c40709925ca432f2c9/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fanalyze-your-apps-usage-in-developer-portal.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38ddff23-b3bc-49e4-82c6-5ed295e347fc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/analyze-your-apps-usage-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eaaa0d1cb853d6cff3b01018a48116f2b5e2293a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fanalyze-your-apps-usage-in-developer-portal.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7c51459-0937-41b0-9884-095501b51857) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/analyze-your-apps-usage-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d181303034556fb9dae8333fcc681960f2b3df1/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fanalyze-your-apps-usage-in-developer-portal.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2dd16414-364a-4a15-b3c6-023e9bc76132) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/analyze-your-apps-usage-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b67fafcc6dfdf1ec1fbcc9e18c026ffb6c94987a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fanalyze-your-apps-usage-in-developer-portal.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a52fa0a-1337-47fc-97fc-5eac9e32b940) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/analyze-your-apps-usage-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5d2a5dfe59c7d63cc1d1b92db9343a4174932aa/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fanalyze-your-apps-usage-in-developer-portal.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29e6a466-2321-4ada-855b-9f74a8fc49d1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/analyze-your-apps-usage-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/296aa38c3ff3c2f1f912a8320c01fda3cd1862bb/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fanalyze-your-apps-usage-in-developer-portal.md) | 95 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/652e26cd-e59d-427f-8ba4-b22c0c67eb93) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
