### PR TITLE
[Doc Improvement][Teams 2.1 update][3427657] 

### PR DESCRIPTION
**Pull request by v-ganr**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-msgext-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8c150fbbcba8038206f9e0aa99c31c3dc60534ef/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-msgext-v4.yml) | 86 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a171eb5-f3a3-4a03-b584-81d3a400ea9a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-msgext-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cd815fff26f22438e0426edaa5a35b74bac0b147/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-msgext-v4.yml) | 86 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3990323-6b02-48f9-b4d9-b43346ef98b7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-msgext-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b15bb7e757ef63ee828cb26543be171a71ef5650/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-msgext-v4.yml) | 86 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a1fad4e-2f2c-43fa-8c87-a6e0e4e67279) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-msgext-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/74b937fb5ad1d1883a88e6eec26d7292e92c523b/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-msgext-v4.yml) | 87 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b52379db-906f-4790-83f3-5042f711a38f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-msgext-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/376481bdea9d7e3fc20d794a25185f6c4816dc8a/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-msgext-v4.yml) | 86 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38d07032-dc61-4743-95dd-7ec90806ee4d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-msgext-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/09a0d332ca4e225229c3a60c311d66ef56d37d5d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-msgext-v4.yml) | 86 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/838ffae8-2e34-4fd8-922c-07519ba578e2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-csharp-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7c795094f9d9eea860c10a2f706ba66c81aa8d2d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-csharp-v4.yml) | 88 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4443ef02-8577-41e9-a97d-7a850262f239) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-msgext-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7c795094f9d9eea860c10a2f706ba66c81aa8d2d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-msgext-v4.yml) | 86 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/110fe438-3ad7-46fa-86f4-32715c57398e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-csharp-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0af2032108f2cfaf7314c664eb35b1bc0096cee8/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-csharp-v4.yml) | 88 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fde233f6-04dd-42b8-9e56-f8e25d091d19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-msgext-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0af2032108f2cfaf7314c664eb35b1bc0096cee8/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-msgext-v4.yml) | 86 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8f9a2dd-25ed-48ac-a675-0a25f0449f4a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-csharp-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9c5de2fbaec03b2a3ba98568dd47fe1bd01d162d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-csharp-v4.yml) | 86 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/973677cc-0ba4-4fcc-aa59-0248b03b9722) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-msgext-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9c5de2fbaec03b2a3ba98568dd47fe1bd01d162d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-msgext-v4.yml) | 85 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db701271-b779-4175-b9d7-c601663286fe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-csharp-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3d5398859d92b6c06b62a0acac8f522904c9e895/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-csharp-v4.yml) | 86 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1b03dde-b0b4-4aa0-9ad8-4107ce80ae75) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-msgext-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3d5398859d92b6c06b62a0acac8f522904c9e895/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-msgext-v4.yml) | 85 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22f286da-5af2-4f2e-9dfd-8dbb7b7866d7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-csharp-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/927c74abd4b4879fdef90c63b4c657ed400376bc/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-csharp-v4.yml) | 86 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a20cc77-a39e-4e05-b3f2-c186b5f8e9ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-msgext-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/927c74abd4b4879fdef90c63b4c657ed400376bc/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-msgext-v4.yml) | 85 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a58360e8-3003-42c7-a1e7-09db5e1a46c2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
