### PR TITLE
Doc Improvement][Teams 2.1 update][3460800]

### PR DESCRIPTION
**Pull request by v-vanv**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-spfx-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ad44b72e694d8b06b18832733c893db118d06533/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-spfx-v4.yml) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25431b76-6d0e-41f2-956b-fe004afb6d8f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-spfx-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d580c15a2c1303be1008601a10f6ce0508c8d231/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-spfx-v4.yml) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d58af9f-ae54-404f-8966-2b7e2069900f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-spfx-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3002c2cc77ee799e0a4d286d79963054698b8022/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-spfx-v4.yml) | 89 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b24f4a10-a1f2-43f1-b28c-7309c4662514) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-spfx-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/743d60c5114f5e7e18863b59eb3c3087c9552ab3/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-spfx-v4.yml) | 89 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c78f26b6-c3c3-490c-94a7-e41d4ac42129) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-spfx-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0338d046d20e04bf3e2c507aff12df82c32c073f/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-spfx-v4.yml) | 89 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a961e521-4148-4d1c-8da8-2ebbae8e2376) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-spfx-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ac0223515476795ea84336c36dcf980d984b46eb/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-spfx-v4.yml) | 89 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f58fee29-651d-4e96-b19a-e9f7df3a24dd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-spfx-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/46baa6867d5c6bf97cbee11f6422e1347701ba23/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-spfx-v4.yml) | 89 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6906f332-4f21-4ecd-8d85-11ca6ba8d673) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
