### PR TITLE
fix typoes and update incorrect link

### PR DESCRIPTION
**Pull request by paul-cheung**

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[bf1241d](https://github.com/paul-cheung/msteams-docs/pull/566/commits/bf1241d34a7cbf2cc40b904e7495671b500b0382)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md) | :warning:Warning | | [Details](#user-content-d51c8c4f-34cbba86)
[msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :warning:Warning | | [Details](#user-content-3ef7bbf0-34cbba86)
[msteams-platform/concepts/tabs/tabs-in-sharepoint.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/tabs/tabs-in-sharepoint.md) | :warning:Warning | | [Details](#user-content-aaf0b02c-34cbba86)
[msteams-platform/concepts/cards/cards-format.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/cards/cards-format.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/outgoingwebhook.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/outgoingwebhook.md) | :white_check_mark:Succeeded | |

<a id="d51c8c4f-34cbba86"></a>
### [msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md)
 - **Line 28**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots).
 - **Line 36**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot).
 - **Line 36**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot#application-permissions).
 - **Line 37**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots).
 - **Line 38**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots).
 - **Line 38**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/real-time-media-concepts).
 - **Line 39**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/call-notifications).

<a id="3ef7bbf0-34cbba86"></a>
### [msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md)
 - **Line 24**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/calls-meetings-bots-overview).

<a id="aaf0b02c-34cbba86"></a>
### [msteams-platform/concepts/tabs/tabs-in-sharepoint.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/tabs/tabs-in-sharepoint.md)
 - **Line 76**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 78**: **[Warning]** Invalid file link:(~/concepts/tabs/tabs-context).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904151018284939-566%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=en8Tlu8yGRL8R05z3SxlWVZR3vsSvwev0bAwq3tK%2Fgk%3D&st=2019-04-15T10%3A14%3A40Z&se=2019-05-16T10%3A19%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[28625b6](https://github.com/paul-cheung/msteams-docs/pull/566/commits/28625b69730c6e07c1f7587fadae8f19bc2d385a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md) | :warning:Warning | | [Details](#user-content-d51c8c4f-e53b2077)
[msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :warning:Warning | | [Details](#user-content-3ef7bbf0-e53b2077)
[msteams-platform/concepts/tabs/tabs-in-sharepoint.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/tabs/tabs-in-sharepoint.md) | :warning:Warning | | [Details](#user-content-aaf0b02c-e53b2077)
[msteams-platform/concepts/cards/cards-format.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/cards/cards-format.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/outgoingwebhook.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/outgoingwebhook.md) | :white_check_mark:Succeeded | |

<a id="d51c8c4f-e53b2077"></a>
### [msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md)
 - **Line 28**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots).
 - **Line 36**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot).
 - **Line 36**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot#application-permissions).
 - **Line 37**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots).
 - **Line 38**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots).
 - **Line 38**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/real-time-media-concepts).
 - **Line 39**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/call-notifications).

<a id="3ef7bbf0-e53b2077"></a>
### [msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md)
 - **Line 24**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/calls-meetings-bots-overview).

<a id="aaf0b02c-e53b2077"></a>
### [msteams-platform/concepts/tabs/tabs-in-sharepoint.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/tabs/tabs-in-sharepoint.md)
 - **Line 76**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 78**: **[Warning]** Invalid file link:(~/concepts/tabs/tabs-context).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904151734568665-566%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ruCipvJEkkIzb4wGXBjKPsfMmaoJFTt1MJO6DFc%2Fd7w%3D&st=2019-04-15T17%3A31%3A09Z&se=2019-05-16T17%3A36%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[be3e65b](https://github.com/paul-cheung/msteams-docs/pull/566/commits/be3e65bf8326aeb84ed675549f89072641e8ad74)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md) | :warning:Warning | | [Details](#user-content-d51c8c4f-2336c2cd)
[msteams-platform/concepts/tabs/tabs-in-sharepoint.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/tabs/tabs-in-sharepoint.md) | :warning:Warning | | [Details](#user-content-aaf0b02c-2336c2cd)
[msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/cards/cards-format.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/cards/cards-format.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/outgoingwebhook.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/outgoingwebhook.md) | :white_check_mark:Succeeded | |

<a id="d51c8c4f-2336c2cd"></a>
### [msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md)
 - **Line 28**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots).
 - **Line 36**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot).
 - **Line 36**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot#application-permissions).
 - **Line 37**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots).
 - **Line 38**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots).
 - **Line 38**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/real-time-media-concepts).
 - **Line 39**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/call-notifications).

<a id="aaf0b02c-2336c2cd"></a>
### [msteams-platform/concepts/tabs/tabs-in-sharepoint.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/tabs/tabs-in-sharepoint.md)
 - **Line 76**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 78**: **[Warning]** Invalid file link:(~/concepts/tabs/tabs-context).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904151736045187-566%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ezkCAzqQIPfZcz79UMqIAsh%2FoFRCYD5YC0pk1eQDjvE%3D&st=2019-04-15T17%3A32%3A27Z&se=2019-05-16T17%3A37%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[55dbd2e](https://github.com/paul-cheung/msteams-docs/pull/566/commits/55dbd2e8d518d1e0222533caab1e092492da4bb5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md) | :warning:Warning | | [Details](#user-content-d51c8c4f-845efaa6)
[msteams-platform/concepts/tabs/tabs-in-sharepoint.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/tabs/tabs-in-sharepoint.md) | :warning:Warning | | [Details](#user-content-aaf0b02c-845efaa6)
[msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/cards/cards-format.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/cards/cards-format.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/outgoingwebhook.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/outgoingwebhook.md) | :white_check_mark:Succeeded | |

<a id="d51c8c4f-845efaa6"></a>
### [msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md)
 - **Line 28**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots).
 - **Line 36**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot).
 - **Line 36**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot#application-permissions).
 - **Line 37**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots).
 - **Line 38**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots).
 - **Line 38**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/real-time-media-concepts).
 - **Line 39**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/call-notifications).

<a id="aaf0b02c-845efaa6"></a>
### [msteams-platform/concepts/tabs/tabs-in-sharepoint.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/tabs/tabs-in-sharepoint.md)
 - **Line 76**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 78**: **[Warning]** Invalid file link:(~/concepts/tabs/tabs-context).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904151737191398-566%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=BwQS4gwzQF%2B8HX8Mos%2FUU%2BxhNpN7JGTIZZBUnVRdWQc%3D&st=2019-04-15T17%3A33%3A58Z&se=2019-05-16T17%3A38%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[441a6e2](https://github.com/paul-cheung/msteams-docs/pull/566/commits/441a6e2ca27937ccc57b9045155ac2218cb7e01e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md) | :warning:Warning | | [Details](#user-content-d51c8c4f-880aef41)
[msteams-platform/concepts/tabs/tabs-in-sharepoint.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/tabs/tabs-in-sharepoint.md) | :warning:Warning | | [Details](#user-content-aaf0b02c-880aef41)
[msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/cards/cards-format.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/cards/cards-format.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/outgoingwebhook.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/outgoingwebhook.md) | :white_check_mark:Succeeded | |

<a id="d51c8c4f-880aef41"></a>
### [msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md)
 - **Line 28**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots).
 - **Line 36**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot).
 - **Line 36**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot#application-permissions).
 - **Line 37**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots).
 - **Line 38**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots).
 - **Line 38**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/real-time-media-concepts).
 - **Line 39**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/call-notifications).

<a id="aaf0b02c-880aef41"></a>
### [msteams-platform/concepts/tabs/tabs-in-sharepoint.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/tabs/tabs-in-sharepoint.md)
 - **Line 76**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 78**: **[Warning]** Invalid file link:(~/concepts/tabs/tabs-context).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904151738194817-566%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=NxQYAOPf0J7oXEhQvxzYy5lRlZtVpgcZJ7cW2TWhDd4%3D&st=2019-04-15T17%3A35%3A18Z&se=2019-05-16T17%3A40%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[24072aa](https://github.com/paul-cheung/msteams-docs/pull/566/commits/24072aaa9415f250ec75864c8fb0915d6ab97df8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md) | :warning:Warning | | [Details](#user-content-d51c8c4f-9dfa41ad)
[msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/cards/cards-format.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/cards/cards-format.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/outgoingwebhook.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/outgoingwebhook.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-in-sharepoint.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/tabs/tabs-in-sharepoint.md) | :white_check_mark:Succeeded | |

<a id="d51c8c4f-9dfa41ad"></a>
### [msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md)
 - **Line 28**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots).
 - **Line 36**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot).
 - **Line 36**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/registering-calling-bot#application-permissions).
 - **Line 37**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots).
 - **Line 38**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/requirements-considerations-application-hosted-media-bots).
 - **Line 38**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/real-time-media-concepts).
 - **Line 39**: **[Warning]** Invalid file link:(~/concepts/calls-and-meetings/call-notifications).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904151739543803-566%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xqwlUfYIWWeDdLTOyIvJw48kmlsbWpQ36%2FtjoK3QquM%3D&st=2019-04-15T17%3A36%3A36Z&se=2019-05-16T17%3A41%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[2ef8911](https://github.com/paul-cheung/msteams-docs/pull/566/commits/2ef891162a8ae8d7b6bb28924a5b0592460bdb44)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md) | :warning:Warning | | [Details](#user-content-d51c8c4f-b2b15111)
[msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/cards/cards-format.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/cards/cards-format.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/outgoingwebhook.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/outgoingwebhook.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-in-sharepoint.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/tabs/tabs-in-sharepoint.md) | :white_check_mark:Succeeded | |

<a id="d51c8c4f-b2b15111"></a>
### [msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md)
 - **Line 36**: **[Warning]** Illegal link: `&lt;a href=&quot;concepts/calls-and-meetings/registering-calling-bot.md#application-permissions&quot;&gt;Microsoft Graph permissions for calls and online meetings bots&lt;/a&gt;` -- missing bookmark. The file concepts/calls-and-meetings/registering-calling-bot.md doesn&#39;t contain a bookmark named application-permissions.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904151741538444-566%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Hu6otVhz%2FGbFQJOcbWV6Q5iDNhPW4l4cUREu98GDX9A%3D&st=2019-04-15T17%3A38%3A08Z&se=2019-05-16T17%3A43%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[8489ce5](https://github.com/paul-cheung/msteams-docs/pull/566/commits/8489ce5db4c82b7b0e876e42f21ad5b6bae94068)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/calls-meetings-bots-overview.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/cards/cards-format.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/cards/cards-format.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/outgoingwebhook.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/outgoingwebhook.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-in-sharepoint.md](https://github.com/paul-cheung/msteams-docs/blob/fix-typos/msteams-platform/concepts/tabs/tabs-in-sharepoint.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904151748198500-566%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=D4nlynz9JePy3gKW0SY0DF2%2B02Ok5RIbdep%2FANVrHns%3D&st=2019-04-15T17%3A44%3A29Z&se=2019-05-16T17%3A49%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clearab** [comment]
Thanks!

**Pull request merged**
