### PR TITLE
Update meeting-app-extensibility.md

### PR DESCRIPTION
**Pull request by ericsche**
Fixing the annonimous user scenario on meeting stage that is inversed.

### CODE REVIEW

**Review by guneetkaurms — COMMENTED** [review]
@ericsche - the anon users can view and interact with the app on stage. The only thing they cannot do is view the tab app in the meeting to invoke share to stage. 

I suggest updating the meeting stage column as follows: 

- Federated Users: Can start, view and interact with app on meeting stage 
- Guest Users: Can start, view and interact with app on meeting stage
- Anonymous Users: Can view and interact with app on meeting stage

**Comment by ericsche** [comment]
My tests showed that interaction was not possible. There was even a banner mentioning it.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by guneetkaurms** [comment]
I think the interaction is not allowed for apps in share tray e.g. Whiteboard. I tried with the tab app "Mural" and it worked.

**Comment by ericsche** [comment]
Yes but then is a tab a stage view/ share stage?

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Review by surbhigupta12 — APPROVED** [review]
Sorry, merged this PR by mistake. have reverted the merge in PR #4339

**Pull request merged**
