### PR TITLE
[Doc Improvement][See also section update 3][3844135]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18a9aa43586a5d280f0ef4f40ccba45c17635e00/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3357d24-96ef-4a6a-8d8a-94fc9a847d5a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18a9aa43586a5d280f0ef4f40ccba45c17635e00/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff29e2fb-e599-4988-ba6d-715130cb7d7b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18a9aa43586a5d280f0ef4f40ccba45c17635e00/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90f2f2af-abbf-4bc4-b92e-cbdb942cd5f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18a9aa43586a5d280f0ef4f40ccba45c17635e00/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c1e1ec1-48f1-4c99-b266-05c01f6fe1ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-chat-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18a9aa43586a5d280f0ef4f40ccba45c17635e00/msteams-platform%2Fgraph-api%2Frsc%2Ftest-chat-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f553c25-6bc5-479c-8ef8-f22e22808c97) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-team-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18a9aa43586a5d280f0ef4f40ccba45c17635e00/msteams-platform%2Fgraph-api%2Frsc%2Ftest-team-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e32b5da-eecc-41b9-8690-249034ed0067) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18a9aa43586a5d280f0ef4f40ccba45c17635e00/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3e75bc8-4106-45fe-99ed-4e2e35fb1e94) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18a9aa43586a5d280f0ef4f40ccba45c17635e00/msteams-platform%2Fresources%2Fmoodle-overview.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82325c13-e112-4d8c-8174-bcf32343344d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/partner-apps-for-moodle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18a9aa43586a5d280f0ef4f40ccba45c17635e00/msteams-platform%2Fresources%2Fpartner-apps-for-moodle.md) | 79 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62fc9bd2-3da7-45e7-b865-ed92d227efac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18a9aa43586a5d280f0ef4f40ccba45c17635e00/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8aad663-e7f0-4c19-8981-717674da9375) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18a9aa43586a5d280f0ef4f40ccba45c17635e00/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/778a5f08-7654-498a-91f7-ae97116e5a51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18a9aa43586a5d280f0ef4f40ccba45c17635e00/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2fbfad25-6ecc-48f1-9577-b89521b2347a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18a9aa43586a5d280f0ef4f40ccba45c17635e00/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 88 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa4dd873-a499-480e-942a-44e31689e5ae) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/565f28024ad8af434d57c15806c0ae45fa6acbe1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98827213-43a2-46fd-9b0e-8674093d6c4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/565f28024ad8af434d57c15806c0ae45fa6acbe1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8c259b7-79e2-4c3b-a826-c17ec80298cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/565f28024ad8af434d57c15806c0ae45fa6acbe1/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8da4129a-d0d3-4ad8-9127-685a0f8e6a6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/565f28024ad8af434d57c15806c0ae45fa6acbe1/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2b48d0c-6df7-40ff-8bab-705535792282) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-chat-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/565f28024ad8af434d57c15806c0ae45fa6acbe1/msteams-platform%2Fgraph-api%2Frsc%2Ftest-chat-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6051349-ee06-4398-9aa0-6d1c17a9b319) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-team-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/565f28024ad8af434d57c15806c0ae45fa6acbe1/msteams-platform%2Fgraph-api%2Frsc%2Ftest-team-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ea393bf-e88b-432e-8612-cb59da71e523) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/565f28024ad8af434d57c15806c0ae45fa6acbe1/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d7baf92-2088-4666-96d4-2a2916945c34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/565f28024ad8af434d57c15806c0ae45fa6acbe1/msteams-platform%2Fresources%2Fmoodle-overview.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd4bb02e-a50a-42a1-8369-63df901395a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/partner-apps-for-moodle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/565f28024ad8af434d57c15806c0ae45fa6acbe1/msteams-platform%2Fresources%2Fpartner-apps-for-moodle.md) | 82 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8e8f1a7-75a4-4e93-b6a3-cfab61c4123d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/565f28024ad8af434d57c15806c0ae45fa6acbe1/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fc68fa9-f951-496e-85e9-7addaa7861d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/565f28024ad8af434d57c15806c0ae45fa6acbe1/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5107e392-8fc9-44a7-ad1d-b074ce65027e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/565f28024ad8af434d57c15806c0ae45fa6acbe1/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ea7f61f-b4ac-4851-8234-afcde2fcd076) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/565f28024ad8af434d57c15806c0ae45fa6acbe1/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 88 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/613dd9f6-e1e7-473a-a923-1d29e61cf7a9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd293b1d388e706b4e4e267a01931daf4442efd6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e5c8427-1622-4b3b-93b7-62c8bbce5ccd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd293b1d388e706b4e4e267a01931daf4442efd6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50f4b005-370a-4685-a7c7-e91b7ca90529) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd293b1d388e706b4e4e267a01931daf4442efd6/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50dd9c6c-7959-4425-b927-d13f49bf4f6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd293b1d388e706b4e4e267a01931daf4442efd6/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14b8b95c-049e-4358-81d1-47231a37fbc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-chat-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd293b1d388e706b4e4e267a01931daf4442efd6/msteams-platform%2Fgraph-api%2Frsc%2Ftest-chat-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53b4b103-0ae6-4668-b7ba-fb4a280e09e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-team-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd293b1d388e706b4e4e267a01931daf4442efd6/msteams-platform%2Fgraph-api%2Frsc%2Ftest-team-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a3fdf9d-4221-4515-8632-39465c4bbea6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd293b1d388e706b4e4e267a01931daf4442efd6/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/477c5329-6139-448c-b73f-2fd23732b3a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd293b1d388e706b4e4e267a01931daf4442efd6/msteams-platform%2Fresources%2Fmoodle-overview.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c501971-1c30-49dd-8cdb-188fb957aa2a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/partner-apps-for-moodle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd293b1d388e706b4e4e267a01931daf4442efd6/msteams-platform%2Fresources%2Fpartner-apps-for-moodle.md) | 82 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfc97600-13a1-4d1d-82ee-ba64b0c3e11a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd293b1d388e706b4e4e267a01931daf4442efd6/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6541671-d208-4397-9a4e-41022a533cd8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd293b1d388e706b4e4e267a01931daf4442efd6/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36d1ef73-86a8-48f6-b62e-04cdf695df97) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ed3bae8a25d4ed6295cbea66f5e1b0f7e2ffb53/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbc36857-f5dd-44e9-8f95-5b2902debc9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ed3bae8a25d4ed6295cbea66f5e1b0f7e2ffb53/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/537387eb-769e-4fda-9aa8-55e9c0614f4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ed3bae8a25d4ed6295cbea66f5e1b0f7e2ffb53/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd396bf7-f161-4324-a345-04cc2b9383b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ed3bae8a25d4ed6295cbea66f5e1b0f7e2ffb53/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd784e73-2670-4fdd-aae9-763461377084) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-chat-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ed3bae8a25d4ed6295cbea66f5e1b0f7e2ffb53/msteams-platform%2Fgraph-api%2Frsc%2Ftest-chat-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a42265e3-4ed0-4d8b-915a-3aa21dbe76b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-team-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ed3bae8a25d4ed6295cbea66f5e1b0f7e2ffb53/msteams-platform%2Fgraph-api%2Frsc%2Ftest-team-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c966b864-1971-47ab-b2dd-b1573ce920eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ed3bae8a25d4ed6295cbea66f5e1b0f7e2ffb53/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/071fc650-21b8-489d-85b3-abc3ed4ef01c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ed3bae8a25d4ed6295cbea66f5e1b0f7e2ffb53/msteams-platform%2Fresources%2Fmoodle-overview.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a5616bd-c676-4273-ab64-015fc740170a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/partner-apps-for-moodle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ed3bae8a25d4ed6295cbea66f5e1b0f7e2ffb53/msteams-platform%2Fresources%2Fpartner-apps-for-moodle.md) | 82 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55b82410-9f6a-4714-b495-20141b78849d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ed3bae8a25d4ed6295cbea66f5e1b0f7e2ffb53/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa31f475-c27e-44cb-9563-9cfa2b752a17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ed3bae8a25d4ed6295cbea66f5e1b0f7e2ffb53/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb49d3ed-e1f0-42e4-b815-8c0a289872cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ed3bae8a25d4ed6295cbea66f5e1b0f7e2ffb53/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a591e97-df38-4099-b15c-2a6ec637b19c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ed3bae8a25d4ed6295cbea66f5e1b0f7e2ffb53/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 87 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/371af204-8711-4be9-9e89-ebcbd8ef3a6e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
