### PR TITLE
[Doc Issue][Update multiple docs][2589876]

### PR DESCRIPTION
**Pull request by v-abirade**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8e248c4076ce11d83bd224334a8bd26772ed3e96/msteams-platform%2Fwhats-new.md) | 95 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f85008a-8b2c-4a9b-b425-80095dab82fb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/828402fb4d57d1eeb2de3fd7ffa6fc4ffdbaa01d/msteams-platform%2Fget-started%2Fglossary.md) | 96 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a3355da-1566-4b30-a3b7-5132a1d764bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/828402fb4d57d1eeb2de3fd7ffa6fc4ffdbaa01d/msteams-platform%2Fwhats-new.md) | 95 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c42b3214-9120-4689-8ba4-6f577982b1a2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd54ab156ff27e72c7d87f39a59933563466458d/msteams-platform%2Fget-started%2Fglossary.md) | 96 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7fee862-86c9-47ec-9043-de2a12e18661) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd54ab156ff27e72c7d87f39a59933563466458d/msteams-platform%2Foverview.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bdeedfb0-18df-4066-85f5-59fa69f558d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd54ab156ff27e72c7d87f39a59933563466458d/msteams-platform%2Fwhats-new.md) | 95 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f3a1ca1-a383-4841-93c3-ae5a2a0eb9cb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/359b29d9af13d58ba8c5cecba4f11ef164ecbb85/msteams-platform%2Fget-started%2Fglossary.md) | 96 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2be6c4ac-cb29-438e-8bee-c7bfadf49ed5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-story.md](https://github.com/MicrosoftDocs/msteams-docs/blob/359b29d9af13d58ba8c5cecba4f11ef164ecbb85/msteams-platform%2Foverview-story.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e183dc5-3de0-4041-88df-bdfb7c214f35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/359b29d9af13d58ba8c5cecba4f11ef164ecbb85/msteams-platform%2Foverview.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9445c660-1b94-4baf-99fb-9e9308a6d14d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/359b29d9af13d58ba8c5cecba4f11ef164ecbb85/msteams-platform%2Fwhats-new.md) | 95 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55a39860-af7f-4772-b602-3a473d3f40c9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcc2cd6c11ec6c7f849ce91adddd13bbfb9d69c2/msteams-platform%2Fget-started%2Fglossary.md) | 96 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/919e893b-3c60-44a2-b744-dc365abfcb9b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcc2cd6c11ec6c7f849ce91adddd13bbfb9d69c2/msteams-platform%2Foverview-solution.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec189a74-40a8-4f43-a166-ba66e6039090) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-story.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcc2cd6c11ec6c7f849ce91adddd13bbfb9d69c2/msteams-platform%2Foverview-story.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00a74c0c-ad5c-4a78-823d-76b3a43e6a19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcc2cd6c11ec6c7f849ce91adddd13bbfb9d69c2/msteams-platform%2Foverview.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9364dcb8-660a-4339-8de2-1929ca80f5b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcc2cd6c11ec6c7f849ce91adddd13bbfb9d69c2/msteams-platform%2Fwhats-new.md) | 95 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14a5c0b7-0e35-4b84-8e63-d5d83a8c4cae) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2dc7fe44228cf615592b8ddce764fe2d4c1e52c5/msteams-platform%2Fget-started%2Fget-started-overview.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cab77999-9df2-45f8-a430-c36e9b69f8ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2dc7fe44228cf615592b8ddce764fe2d4c1e52c5/msteams-platform%2Fget-started%2Fglossary.md) | 96 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c9eeeab-6a7b-4d58-bc6c-525547f66067) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2dc7fe44228cf615592b8ddce764fe2d4c1e52c5/msteams-platform%2Foverview-solution.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5db8eaf-b00e-4fb9-bdcf-5e5a5a3e83c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-story.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2dc7fe44228cf615592b8ddce764fe2d4c1e52c5/msteams-platform%2Foverview-story.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c424ee39-892c-4a18-aae7-aa08fe8c93e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2dc7fe44228cf615592b8ddce764fe2d4c1e52c5/msteams-platform%2Foverview.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cebdd089-3c96-48e5-86dc-e0e36c615e01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2dc7fe44228cf615592b8ddce764fe2d4c1e52c5/msteams-platform%2Fwhats-new.md) | 95 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a659bccc-98ff-46be-b987-a5b36d753b99) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b66072c57addf425a43469218a8222065d60fc6/msteams-platform%2Fget-started%2Fget-started-overview.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/002b0776-5a5e-460c-8147-e4657c5671de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b66072c57addf425a43469218a8222065d60fc6/msteams-platform%2Fget-started%2Fglossary.md) | 96 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36c716c6-6b46-4356-a759-5ecd20472a71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b66072c57addf425a43469218a8222065d60fc6/msteams-platform%2Foverview-solution.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab30990a-c418-4f6c-b311-9e47a67672bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-story.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b66072c57addf425a43469218a8222065d60fc6/msteams-platform%2Foverview-story.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7abbe268-d12b-47e6-bb07-aeb2f5a62f80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b66072c57addf425a43469218a8222065d60fc6/msteams-platform%2Foverview.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/763aa6b4-bd36-4bb7-bb1c-4a0199f4dea1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b66072c57addf425a43469218a8222065d60fc6/msteams-platform%2Fsbs-gs-javascript.yml) | 94 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c1d7b8d-55c8-45bd-880e-c827a3c2e1fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b66072c57addf425a43469218a8222065d60fc6/msteams-platform%2Fwhats-new.md) | 95 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b9d110f-d4f2-43bf-acd9-215673e307b7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7576fd3904e5c0eb2644f910d4e5088e18e2f3a5/msteams-platform%2Fget-started%2Fget-started-overview.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a11ede38-eae6-4fc6-8c0a-b707c3645ed2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7576fd3904e5c0eb2644f910d4e5088e18e2f3a5/msteams-platform%2Fget-started%2Fglossary.md) | 96 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/829d86e8-deaa-45a2-a1d1-5f0b5ca95b9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7576fd3904e5c0eb2644f910d4e5088e18e2f3a5/msteams-platform%2Foverview-solution.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1cccec9d-2833-4563-952d-328303a5ff34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-story.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7576fd3904e5c0eb2644f910d4e5088e18e2f3a5/msteams-platform%2Foverview-story.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f916c58d-2bce-4111-9ed9-69ba80dd0a19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7576fd3904e5c0eb2644f910d4e5088e18e2f3a5/msteams-platform%2Foverview.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ade0c39-f731-45ac-b185-9eca32d1f31b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7576fd3904e5c0eb2644f910d4e5088e18e2f3a5/msteams-platform%2Fsbs-gs-bot.yml) | 94 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0558c00-08a7-4ec5-a2c9-c50dece8c1af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7576fd3904e5c0eb2644f910d4e5088e18e2f3a5/msteams-platform%2Fsbs-gs-javascript.yml) | 94 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b13d8e79-8cd6-4437-9634-5a5db11820cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7576fd3904e5c0eb2644f910d4e5088e18e2f3a5/msteams-platform%2Fwhats-new.md) | 95 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ea4c047-f255-4380-9df0-5ae59e2dc76b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-abirade** [comment]
Closing the PR as obsolete.

**Pull request closed without merging**
