### PR TITLE
[Doc Improvement][Create a dashboard toc changes][2820143]

### PR DESCRIPTION
**Pull request by v-silakshmi**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e20a8a1d0bc577bcda053ff3f392eaed56c50852/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c58580d-2ed4-4c29-b84b-4da2f8cd3531) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — DISMISSED** [review]
Approved

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b48c2738bddd41007ba3cf4e8152b3ac71e9ecef/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10d97ed5-9b72-430a-8d80-134a1bc59f73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b48c2738bddd41007ba3cf4e8152b3ac71e9ecef/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/464f43a3-a626-4587-86f9-b0ece483f0d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b48c2738bddd41007ba3cf4e8152b3ac71e9ecef/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03c12e05-d5a1-4d08-9fe9-cbfad4bbd225) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b48c2738bddd41007ba3cf4e8152b3ac71e9ecef/msteams-platform%2Fwhats-new.md) | 89 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/def8ea61-b570-4260-b936-d5f459a7c8c0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1b40d6502022db534f204936b6a99699980ebd6e/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/adf3151b-0569-42fe-b35e-bd63e5cce0a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1b40d6502022db534f204936b6a99699980ebd6e/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99cf3b64-fac6-4e51-9737-5a2b0ac7b4c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1b40d6502022db534f204936b6a99699980ebd6e/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9080ec3c-c5dc-438f-a858-9c9b0856f87a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b40d6502022db534f204936b6a99699980ebd6e/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7303a4d7-a0f6-4af7-8f00-8fdaf55f832e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b40d6502022db534f204936b6a99699980ebd6e/msteams-platform%2Fwhats-new.md) | 89 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb530817-2be1-4244-9912-1dbadd428b20) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/869beada0832c0f27279fc70814e48b1d25e1a1e/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0733be9f-33d2-4571-9cdc-4f0fd409f8f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/869beada0832c0f27279fc70814e48b1d25e1a1e/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea8eaa88-8c38-4fec-9ccd-e43fd150e247) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/869beada0832c0f27279fc70814e48b1d25e1a1e/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9414fad8-a75d-41f5-9dda-7e234a1d726e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/869beada0832c0f27279fc70814e48b1d25e1a1e/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a1d27e8-156c-4e48-bdd9-4ba99c3ae8fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/869beada0832c0f27279fc70814e48b1d25e1a1e/msteams-platform%2Fwhats-new.md) | 89 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26d0d613-3ad3-43fb-9fac-a36dc24cb3b4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/939b95b066d2b76cf6f3e1b50dc305c8567bf931/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44ba4461-4687-476f-96c1-adc7a7a45efa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/939b95b066d2b76cf6f3e1b50dc305c8567bf931/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c862c64c-f06a-461a-9754-666e8b777200) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/939b95b066d2b76cf6f3e1b50dc305c8567bf931/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d9fad9c-cf8f-4624-a543-a0f1f90e4894) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/939b95b066d2b76cf6f3e1b50dc305c8567bf931/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3cacb129-3bb1-4fe7-a98f-f06f66146a78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/939b95b066d2b76cf6f3e1b50dc305c8567bf931/msteams-platform%2Fwhats-new.md) | 89 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbf9092f-7072-46fd-aaf9-028482dcb6af) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5c0b4430cd17e265c0f9f91b380505b0b5e5afee/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ebe6c34-379f-40db-a26b-ca57297646e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5c0b4430cd17e265c0f9f91b380505b0b5e5afee/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/954dae98-9cce-4012-a771-61e713efdcef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5c0b4430cd17e265c0f9f91b380505b0b5e5afee/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29cca305-224e-40c9-a44a-d56ae3ce9da7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c0b4430cd17e265c0f9f91b380505b0b5e5afee/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcf6b3f8-90fe-403b-8c60-de88c0b55254) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c0b4430cd17e265c0f9f91b380505b0b5e5afee/msteams-platform%2Fwhats-new.md) | 89 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec595442-81ad-411a-a5dc-3f9a1a0e5293) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/818905d35110ac769c4b78859b4d5f8b7c13d1b4/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0203ca63-f9b3-498a-ad92-b12e38686161) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/818905d35110ac769c4b78859b4d5f8b7c13d1b4/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da07d6f0-deff-436f-b20b-951baeae0050) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/818905d35110ac769c4b78859b4d5f8b7c13d1b4/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07d727fc-75b0-4fed-a8f7-5951aaf4ec47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/818905d35110ac769c4b78859b4d5f8b7c13d1b4/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e891cc4-edde-442e-98a5-e9a402adf484) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/818905d35110ac769c4b78859b4d5f8b7c13d1b4/msteams-platform%2Fwhats-new.md) | 89 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbb4c0ec-d475-43c9-acbe-24fe42532b71) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2009bd2b65869a2a02675f95929fda2d736017de/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3203b35-bc50-49f0-a074-f157c38b38f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2009bd2b65869a2a02675f95929fda2d736017de/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/901dbeb5-3c2b-4928-a80b-77c1fd5096d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2009bd2b65869a2a02675f95929fda2d736017de/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96643365-69db-4b0a-a9d9-e27367b6bdcc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2009bd2b65869a2a02675f95929fda2d736017de/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93f990cc-dbe0-4af2-b458-0cb618930895) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2009bd2b65869a2a02675f95929fda2d736017de/msteams-platform%2Fwhats-new.md) | 89 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/655acab4-cd5d-447b-8f5d-06c52c434673) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cc146c76112134ba60be26f12aa2f47bf40cd0a3/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de09beb8-ce80-489f-9370-f5f5406acec4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cc146c76112134ba60be26f12aa2f47bf40cd0a3/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31e63d04-5786-49b8-81c3-1e544e1a341c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cc146c76112134ba60be26f12aa2f47bf40cd0a3/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1909c410-7c39-4b18-9ab3-abfd05126df2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc146c76112134ba60be26f12aa2f47bf40cd0a3/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/655d3ff6-fe5c-4183-9bae-c3c31cb5e10b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc146c76112134ba60be26f12aa2f47bf40cd0a3/msteams-platform%2Fwhats-new.md) | 89 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6094e022-dea8-44e4-8599-09fcc91deb9d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab3361f72fa6d2ba09e439eab5594dba4dd65707/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5d2a326-2787-47da-9baa-2e7b5887d770) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab3361f72fa6d2ba09e439eab5594dba4dd65707/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48906c80-dafa-4867-9397-a4cbc8b2dd7c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab3361f72fa6d2ba09e439eab5594dba4dd65707/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 87 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7deed798-d8c9-4fea-9b70-3e99726ad1fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab3361f72fa6d2ba09e439eab5594dba4dd65707/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08166e9b-7f51-4903-9041-04ad7f2ce154) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab3361f72fa6d2ba09e439eab5594dba4dd65707/msteams-platform%2Fwhats-new.md) | 90 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9fcba44a-729f-46f4-9c22-156a3102ac3e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
