### PR TITLE
Remove mobile client specific changes

### PR DESCRIPTION
**Pull request by jjustinms**
Starting from March/April store release and client SDK v 1.4.1 mobile fully supports auth. As discussed in a thread, we can remove this reference and capture the same in a blog post.

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[81162c7](https://github.com/jjustinms/msteams-docs/pull/632/commits/81162c7acc1ce9cbe51c2172f90b7a60988ccc63)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/authentication/auth-flow-bot.md](https://github.com/jjustinms/msteams-docs/blob/patch-4/msteams-platform/concepts/authentication/auth-flow-bot.md) | :warning:Warning | | [Details](#user-content-d068bbad-beb90d19)

<a id="d068bbad-beb90d19"></a>
### [msteams-platform/concepts/authentication/auth-flow-bot.md](https://github.com/jjustinms/msteams-docs/blob/patch-4/msteams-platform/concepts/authentication/auth-flow-bot.md)
 - **Line 46**: **[Warning]** Invalid file link:(~/concepts/authentication/auth-bot-AAD).
 - **Line 30**: **[Suggestion]** Illegal link: `&lt;a href=&quot;#Mobile-clients&quot;&gt;as described below&lt;/a&gt;` -- missing bookmark. The file concepts/authentication/auth-flow-bot.md doesn&#39;t contain a bookmark named Mobile-clients.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201905080338441904-632%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sxxcGjASHhX3tLXDYoEzXwXZsPlFNj30cP85M6%2BFNF8%3D&st=2019-05-08T03%3A34%3A56Z&se=2019-06-08T03%3A39%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by billbliss** [comment]
I agree with the deletion but we need to add the SDK version note and I think we should keep the old fallback URL content around in another page for a while and call the fallback URL deprecated. It still works. And as Andrew pointed out we need to update the sample.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[27f6b54](https://github.com/jjustinms/msteams-docs/pull/632/commits/27f6b54a4549dca94b135f7ef6e65a66f8b1620d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/authentication/auth-flow-bot.md](https://github.com/jjustinms/msteams-docs/blob/patch-4/msteams-platform/concepts/authentication/auth-flow-bot.md) | :warning:Warning | | [Details](#user-content-d068bbad-568733c8)

<a id="d068bbad-568733c8"></a>
### [msteams-platform/concepts/authentication/auth-flow-bot.md](https://github.com/jjustinms/msteams-docs/blob/patch-4/msteams-platform/concepts/authentication/auth-flow-bot.md)
 - **Line 49**: **[Warning]** Invalid file link:(~/concepts/authentication/auth-bot-AAD).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201905110319521475-632%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=eboaK9rnxaUX82p0xgHZ1HkK1iRqV1xMWtbwwhBls38%3D&st=2019-05-11T03%3A15%3A59Z&se=2019-06-11T03%3A20%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[be3c116](https://github.com/jjustinms/msteams-docs/pull/632/commits/be3c11632bb4436c9e3b0cfc63353def716b4bf2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/authentication/auth-flow-bot.md](https://github.com/jjustinms/msteams-docs/blob/patch-4/msteams-platform/concepts/authentication/auth-flow-bot.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C11%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201905110322239572-632%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kqaFwRHHN7h3o3CuRL%2B4rLclwqcCN3dAhBkCMSSwApw%3D&st=2019-05-11T03%3A18%3A35Z&se=2019-06-11T03%3A23%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
