### PR TITLE
[Doc-Improvement][Obsolete-files-links]

### PR DESCRIPTION
**Pull request by v-shalinirobinson**
Fix bad/broken links from the PR6702. Delete/Redirect files obsolete after the merging of Teams Toolkit for Visual Studio Code revamp.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b2e8cddb4773882e98bc055aa4f821f66ec50789/msteams-platform%2Fget-started%2Fglossary.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b986e96-d253-458c-b5b0-55e4c8308d15) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c690b200cf19168a4543374dd853dac807670762/msteams-platform%2Fget-started%2Fglossary.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2622d5ed-11e6-4d26-be48-b3732669b914) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bed08470bda6b5956fef6b77d7d179bf775a7835/msteams-platform%2Fget-started%2Fglossary.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5616c25e-dd1c-4b76-8e34-e35aea0d19f5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05a4d251be598ebd115348f0cc0c511b72a1f583/msteams-platform%2Fget-started%2Fglossary.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0c63d4c-7eb5-439a-95e2-65ea13e98276) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/05a4d251be598ebd115348f0cc0c511b72a1f583/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69192440-cb42-4669-80ec-bca2cd8a3a4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/05a4d251be598ebd115348f0cc0c511b72a1f583/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 83 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01b8799e-3f1a-4bd4-8ccb-ae0bcbd55472) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d215c419f654b35eb826a07f60ff18e6f95cc7b/msteams-platform%2Fget-started%2Fglossary.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9aa0af44-7d6c-4d1b-888e-1b7bdccc56b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6d215c419f654b35eb826a07f60ff18e6f95cc7b/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f42e16af-20f0-46f8-9212-e20f71f339a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6d215c419f654b35eb826a07f60ff18e6f95cc7b/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 84 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de115269-bb75-4b48-a0f7-bb268de2e313) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d215c419f654b35eb826a07f60ff18e6f95cc7b/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cca7523-dc13-4bb6-b672-1aff1fb32353) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3917fe6f276d944dc9b6b8e5fdec5e66ab7dc9df/msteams-platform%2Fget-started%2Fglossary.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89361c88-4a9d-40ac-b552-8c3e4f73496b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3917fe6f276d944dc9b6b8e5fdec5e66ab7dc9df/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f2cad93-c3dc-46e5-a4b8-461bbbde90e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3917fe6f276d944dc9b6b8e5fdec5e66ab7dc9df/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 84 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b54a030-0923-4244-94fa-0a0edbae4050) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3917fe6f276d944dc9b6b8e5fdec5e66ab7dc9df/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/696f340d-71e3-498c-a31f-35779aeb0bc1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/50877c6d9586d2ed0f6386f7539bb74949312f87/msteams-platform%2Fget-started%2Fglossary.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcb272b8-ec61-42e4-baac-5867642a0c99) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/50877c6d9586d2ed0f6386f7539bb74949312f87/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2c04ae2-80a5-4182-a27b-c0479b43eb37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/50877c6d9586d2ed0f6386f7539bb74949312f87/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 84 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b2665c7-35b2-4b1f-8613-b8bfb69058c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/50877c6d9586d2ed0f6386f7539bb74949312f87/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/452ddb4e-5afa-4e0a-80df-04967b5775b8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/deaf4e75a383e9d8ebd8f5f20d1fe4aea64e3d90/msteams-platform%2FTOC.yml) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33af4135-f80d-4ac1-9cbd-7fe4338ed66a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/deaf4e75a383e9d8ebd8f5f20d1fe4aea64e3d90/msteams-platform%2Fget-started%2Fglossary.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9adde346-135a-4461-93c4-8d805e4d7103) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/deaf4e75a383e9d8ebd8f5f20d1fe4aea64e3d90/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d50630d-af40-4a7d-b1ce-6b0b18cd0ea3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/deaf4e75a383e9d8ebd8f5f20d1fe4aea64e3d90/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 84 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f60e730b-fdce-4254-92cd-3cb759f363e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/deaf4e75a383e9d8ebd8f5f20d1fe4aea64e3d90/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8338efe7-7fba-48d4-8455-2844f5b73701) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/49ac0ef38172455dbf6a9758454de4cfeffb30fb/msteams-platform%2FTOC.yml) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af2502c7-c7f8-40a8-9fab-ad5ca8e63afe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ac0ef38172455dbf6a9758454de4cfeffb30fb/msteams-platform%2Fget-started%2Fglossary.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fde2bf76-b430-4fcc-9027-d46ee61a5d07) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/49ac0ef38172455dbf6a9758454de4cfeffb30fb/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f929a899-d489-4f28-bde3-f60b0f3a6466) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ac0ef38172455dbf6a9758454de4cfeffb30fb/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd1d89a4-73ad-42fc-96ab-c849c1193629) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ac0ef38172455dbf6a9758454de4cfeffb30fb/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33b0a868-ec1c-4325-a9c3-cf127ad4304d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/49ac0ef38172455dbf6a9758454de4cfeffb30fb/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 84 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3869119f-e1ec-4b14-80d2-a6f188e04b51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ac0ef38172455dbf6a9758454de4cfeffb30fb/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa835f89-c1db-45b2-b3f3-34247c87fa2c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/659fc02018adc651193cd718c677048cd7de0ddd/msteams-platform%2FTOC.yml) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e31af3c-4837-452a-9bd7-17c76df69908) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/659fc02018adc651193cd718c677048cd7de0ddd/msteams-platform%2Fget-started%2Fglossary.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22dcc1ce-a43c-4b31-b02d-6f1039707da4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/659fc02018adc651193cd718c677048cd7de0ddd/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4731e156-9bc6-4e6e-9af9-c60af33f7f4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/659fc02018adc651193cd718c677048cd7de0ddd/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a263daa4-07f1-4c76-bdff-0a2797d049e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/659fc02018adc651193cd718c677048cd7de0ddd/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e45ac15e-e1b9-4960-9629-65cc11b21504) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/659fc02018adc651193cd718c677048cd7de0ddd/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 84 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d8afc1d-7bf8-4cf5-a54d-c7cd95625b48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/659fc02018adc651193cd718c677048cd7de0ddd/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb5e43ff-1a51-446d-8868-535c8c90c436) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0a2b21f6daece3ca9821e963431ffc7ec5c82638/msteams-platform%2FTOC.yml) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76641f3f-3ab5-485f-9370-a12a130128f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a2b21f6daece3ca9821e963431ffc7ec5c82638/msteams-platform%2Fget-started%2Fglossary.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/702d8cc8-723e-4966-9ac4-2bac86a8b16c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0a2b21f6daece3ca9821e963431ffc7ec5c82638/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc5987f9-b0ec-455d-b812-c1eb72509b5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a2b21f6daece3ca9821e963431ffc7ec5c82638/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b16a74ed-778c-4d32-8c69-3e7130c99b1f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a2b21f6daece3ca9821e963431ffc7ec5c82638/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e36b7754-fd56-4215-ba5e-ed5aee9e80c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0a2b21f6daece3ca9821e963431ffc7ec5c82638/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 87 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7f77567-e092-4e5c-97b1-be0e37d904ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a2b21f6daece3ca9821e963431ffc7ec5c82638/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13bdaf73-fb06-4fcc-b7cb-5b842a415729) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/80597e87fae38dfb72817cb88be902c6985410d2/msteams-platform%2FTOC.yml) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8626b7f6-8cef-4577-aadf-e9f3ca1adfbd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80597e87fae38dfb72817cb88be902c6985410d2/msteams-platform%2Fget-started%2Fglossary.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/296ac4d4-f0a1-43f1-ab29-becec517043b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/80597e87fae38dfb72817cb88be902c6985410d2/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a611c960-271c-4802-bce8-d73295950506) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80597e87fae38dfb72817cb88be902c6985410d2/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c429860-1cf4-48e9-a477-0409479f7d02) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80597e87fae38dfb72817cb88be902c6985410d2/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a09e747a-4e39-4af9-85de-b2737c3b202e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/80597e87fae38dfb72817cb88be902c6985410d2/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 87 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bb0cabc-f680-434d-8db3-53a428e81c5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80597e87fae38dfb72817cb88be902c6985410d2/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1d451d8-a5cb-4340-8d2b-2373312faa4c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
