### PR TITLE
[Doc Improvement][Verify and fix sign in and casing][3008097]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/141dace0bc6c551982a53b1adf3bae1ac7753873/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16053f42-c1ab-4da1-9c73-a7a5f8388a59) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/analyze-your-apps-usage-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98ac0d016b360fa55b1ce3517e9c07d7af422be2/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fanalyze-your-apps-usage-in-developer-portal.md) | 96 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9562f876-87d3-4d7b-98b0-f725aa4b92f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98ac0d016b360fa55b1ce3517e9c07d7af422be2/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3407f41e-11e7-4b36-b41d-8796e46a21d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98ac0d016b360fa55b1ce3517e9c07d7af422be2/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97b07e57-05f5-44ce-8f86-32e0c2214002) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98ac0d016b360fa55b1ce3517e9c07d7af422be2/msteams-platform%2Ftoolkit%2FTeamsFx-CLI.md) | 93 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c20ba83-e62c-4ca9-a08c-83aa02a6747e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98ac0d016b360fa55b1ce3517e9c07d7af422be2/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c114796f-6f8e-4037-8b98-3bb54f96d07b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/analyze-your-apps-usage-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20255af03f9f2ffc9fd7b6b000048595d23b9f6f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fanalyze-your-apps-usage-in-developer-portal.md) | 96 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1641da97-8835-49a1-8268-36c8acc44794) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20255af03f9f2ffc9fd7b6b000048595d23b9f6f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19eaf9d3-d17a-4bba-b16d-7cd2e9514d66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20255af03f9f2ffc9fd7b6b000048595d23b9f6f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57788762-06f1-4ab2-8678-c1257cb99016) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20255af03f9f2ffc9fd7b6b000048595d23b9f6f/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-channel.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9cf784b-3d97-4cbd-99d6-1f426140994a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20255af03f9f2ffc9fd7b6b000048595d23b9f6f/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-proactive.md) | 89 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/782a7f7c-961f-4b7d-97c8-83e751787453) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20255af03f9f2ffc9fd7b6b000048595d23b9f6f/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a29377c-e00f-4f4a-9220-78fd817a2db8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20255af03f9f2ffc9fd7b6b000048595d23b9f6f/msteams-platform%2Ftoolkit%2FTeamsFx-CLI.md) | 93 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d18e88be-cf5f-4023-a8b1-df96ca73e28e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20255af03f9f2ffc9fd7b6b000048595d23b9f6f/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7c6bd5d-51f3-405e-b41a-b363dcadf537) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6dd54bfdfb5e659d84dea49811540d64243d7ac/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5949fa1d-3d49-4926-84b8-1e33f2be2709) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6dd54bfdfb5e659d84dea49811540d64243d7ac/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/940fc325-9dfd-497b-bcf8-0ecadb090c20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6dd54bfdfb5e659d84dea49811540d64243d7ac/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-channel.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb0363a8-6389-4b66-98f3-9a56b234c202) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6dd54bfdfb5e659d84dea49811540d64243d7ac/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-proactive.md) | 89 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1e88dba-29c7-4241-904d-79ef35814c68) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6dd54bfdfb5e659d84dea49811540d64243d7ac/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8033821b-0c5d-4199-a8fd-5554ee06d027) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6dd54bfdfb5e659d84dea49811540d64243d7ac/msteams-platform%2Ftoolkit%2FTeamsFx-CLI.md) | 93 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbb6dc03-a40c-4fd0-b12d-67e52ad6ea7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6dd54bfdfb5e659d84dea49811540d64243d7ac/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f8023bd-7dff-436a-9130-1b95effc9611) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f658e86bade941f04898b85a63a62c9c583889a0/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8ef0b0f-bae7-4935-93b4-0336602549a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f658e86bade941f04898b85a63a62c9c583889a0/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-proactive.md) | 89 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9aba1a2e-4376-477a-b9f8-ebeae25d32fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f658e86bade941f04898b85a63a62c9c583889a0/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a51f7387-85d7-4d6f-8974-1204523d393f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f658e86bade941f04898b85a63a62c9c583889a0/msteams-platform%2Ftoolkit%2FTeamsFx-CLI.md) | 93 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3df2a8d2-d630-4c02-8a96-9007271225c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f658e86bade941f04898b85a63a62c9c583889a0/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8dcb8c7-fd8b-4f66-b333-72166a0970b4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a72ceb571b9d485db7d83d3a8cf6687636fe687b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45cb3618-8c0b-43d7-9507-d9f3b84da2e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a72ceb571b9d485db7d83d3a8cf6687636fe687b/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-proactive.md) | 89 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28e692c4-c272-4108-9a0e-44d8e1271dfd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a72ceb571b9d485db7d83d3a8cf6687636fe687b/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2be973e9-d949-4b9d-ae01-2462f290972f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1428e154e181f719b4cf65c99c07520d9e0200b8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 97 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0ab4042-3f5f-407e-8188-52576a7e9798) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-proactive.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1428e154e181f719b4cf65c99c07520d9e0200b8/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-proactive.md) | 89 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cae5e05-f39e-4e6f-add7-fb45fcfc1ea5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1428e154e181f719b4cf65c99c07520d9e0200b8/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f70a9ca-044f-4440-a170-3f6c33d06a6d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
