### PR TITLE
[Doc Issue][Update Blazor app][2331290]

### PR DESCRIPTION
**Pull request by v-bdeepa**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/74fa6c8879ca639adf7322efae40584fa5c392ae/msteams-platform/TOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0103fce2-d16e-45f0-bb6f-5811fd29d3a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74fa6c8879ca639adf7322efae40584fa5c392ae/msteams-platform/get-started/get-started-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69f96308-638b-40ed-b57e-455e3d15319e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2ee333f4fa965d96df74b508b5b4f15781e6aed2/msteams-platform/TOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6a4f7dd-81b0-417a-ae69-aa1d3a82a646) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ee333f4fa965d96df74b508b5b4f15781e6aed2/msteams-platform/get-started/get-started-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea4028f9-0100-4133-ab38-d585447e5dc8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2ee333f4fa965d96df74b508b5b4f15781e6aed2/msteams-platform/sbs-gs-blazorupdate.yml) | 97 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed29f45b-1d2f-476e-9500-ac2152b5f543) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35af8b7a57ca64fa910b1ab00040209a8d42619a/msteams-platform/TOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22411370-ac43-41a5-9398-f88cc5b1493e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35af8b7a57ca64fa910b1ab00040209a8d42619a/msteams-platform/get-started/get-started-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3c90f84-77a7-4d1f-86ae-cd2642612ea9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35af8b7a57ca64fa910b1ab00040209a8d42619a/msteams-platform/sbs-gs-blazorupdate.yml) | 97 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2de9f1b8-91eb-4bfd-98c0-c05a57d138dd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a861f1460cea83dd90a9c33b24f3c7a4b81a6532/msteams-platform/TOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c4da86b-c6b4-4265-ad6a-b0f83676ffa4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a861f1460cea83dd90a9c33b24f3c7a4b81a6532/msteams-platform/get-started/get-started-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8110533-87d8-4217-ac18-2df344293b05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a861f1460cea83dd90a9c33b24f3c7a4b81a6532/msteams-platform/mstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7dbf43a-4340-4f3d-b08a-137ca9c967bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a861f1460cea83dd90a9c33b24f3c7a4b81a6532/msteams-platform/sbs-gs-blazorupdate.yml) | 97 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c697a638-15a3-4b51-93be-92d4cf3f082c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
