### PR TITLE
[Messaging extensions][update information][1549846]

### PR DESCRIPTION
**Pull request by Rajeshwari-v**
Updated information. Please review.

### CODE REVIEW

**Review by Nikitha-MSFT — APPROVED** [review]
Reviewed and Approved

**Review by KirtiPereira — CHANGES_REQUESTED** [review]
@Rajeshwari-v - please validate and incorporate the suggestion.

**Review by surbhigupta12 — APPROVED** [review]
Approving the PR.

**Review by KirtiPereira — APPROVED** [review]
Approved.

**Pull request merged**
