### PR TITLE
[Doc enhancement][youtube-video-links][]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/50e137ff390c89f609feabf85f8f8e7852b09256/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31f35d2e-082b-4b25-950e-d43bf1657685) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/50e137ff390c89f609feabf85f8f8e7852b09256/msteams-platform/tabs/what-are-tabs.md) | 88 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0cfad55c-9974-4208-9551-470b37e38be8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/050ebce5aca04b26c17c74d12c610c0ec94a8725/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | 96 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5c1664d-93a2-437a-86e9-406b5393ab01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/050ebce5aca04b26c17c74d12c610c0ec94a8725/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8efd4195-e0a7-49b9-b288-8c6dbd200ade) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/050ebce5aca04b26c17c74d12c610c0ec94a8725/msteams-platform/apps-in-teams-meetings/teams-together-mode.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c70c71e-1a0c-441d-a9d3-0b724f162fa0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/050ebce5aca04b26c17c74d12c610c0ec94a8725/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e7359cb-0f10-423d-a8e9-e2b3d5e0f5a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/050ebce5aca04b26c17c74d12c610c0ec94a8725/msteams-platform/tabs/what-are-tabs.md) | 88 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ec4c4b0-a58a-4da8-b114-c957a6fe3a26) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/242d8cab000cd01c8268bdaf7c3b1d60e29529c3/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | 96 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37f7ad28-f9a5-49ca-9eed-eb904ffc5f05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/242d8cab000cd01c8268bdaf7c3b1d60e29529c3/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0f838f4-9588-44f5-87a8-652cb0b1c95e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/242d8cab000cd01c8268bdaf7c3b1d60e29529c3/msteams-platform/apps-in-teams-meetings/teams-together-mode.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11da007d-dd96-4767-ae19-d4b55aa58bbb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/242d8cab000cd01c8268bdaf7c3b1d60e29529c3/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72ff113e-ae82-409d-96e2-6b292c37a098) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/242d8cab000cd01c8268bdaf7c3b1d60e29529c3/msteams-platform/tabs/what-are-tabs.md) | 88 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69972320-a460-4027-93ec-9d57f76f3fa7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/242d8cab000cd01c8268bdaf7c3b1d60e29529c3/msteams-platform/task-modules-and-cards/cards/cards-reference.md) | 83 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6783a697-262b-4149-9fc5-e3cf71118a00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/242d8cab000cd01c8268bdaf7c3b1d60e29529c3/msteams-platform/task-modules-and-cards/what-are-cards.md) | 88 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffdaffc4-0c24-4ac2-a4b2-fe0424b9866c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd9fab35015a889a43d2e469479e58cc9b97697d/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | 96 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfe14d02-fb38-475d-87d5-ac8072d651fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd9fab35015a889a43d2e469479e58cc9b97697d/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28a7d5f5-e6ad-4c2d-bfc6-0519924b9c21) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd9fab35015a889a43d2e469479e58cc9b97697d/msteams-platform/apps-in-teams-meetings/teams-together-mode.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b250fcf7-6050-42d4-a57a-0b59f2301831) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd9fab35015a889a43d2e469479e58cc9b97697d/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d4e1177-2626-4a7b-be8a-df0a0aaaea6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodle-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd9fab35015a889a43d2e469479e58cc9b97697d/msteams-platform/resources/moodle-overview.md) | 89 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/233ea86c-c6b3-44f0-979f-a6766b042fe4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd9fab35015a889a43d2e469479e58cc9b97697d/msteams-platform/tabs/what-are-tabs.md) | 88 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7195ec3d-6745-4ed6-b2fb-a083de03adea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd9fab35015a889a43d2e469479e58cc9b97697d/msteams-platform/task-modules-and-cards/cards/cards-reference.md) | 83 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42d51ae8-4bb3-4b14-bde9-21c803f637a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd9fab35015a889a43d2e469479e58cc9b97697d/msteams-platform/task-modules-and-cards/what-are-cards.md) | 88 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76670a6b-affe-4bf1-892a-474c24c2a45d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed7dff3f11ddcf0c91defce19141fa861b17070a/msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md) | 96 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/471d90e4-a7c5-43e3-8707-e807941956e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed7dff3f11ddcf0c91defce19141fa861b17070a/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19e3c2d1-e587-48e5-8c93-027915c1f86a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed7dff3f11ddcf0c91defce19141fa861b17070a/msteams-platform/apps-in-teams-meetings/teams-together-mode.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54924cdc-e4ea-49d6-bd15-a89f5f4d454c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed7dff3f11ddcf0c91defce19141fa861b17070a/msteams-platform/bots/what-are-bots.md) | 84 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f71c52ce-a46f-4d0a-9be6-cd98f03a1920) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed7dff3f11ddcf0c91defce19141fa861b17070a/msteams-platform/tabs/what-are-tabs.md) | 88 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea10ef1b-6dd4-4ae8-a769-8b519cdebd60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed7dff3f11ddcf0c91defce19141fa861b17070a/msteams-platform/task-modules-and-cards/cards/cards-reference.md) | 83 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f373eb4f-2390-49be-8432-7ddb4c23bdfc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed7dff3f11ddcf0c91defce19141fa861b17070a/msteams-platform/task-modules-and-cards/what-are-cards.md) | 88 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9fa0b76-99fa-47e4-be23-13937b63d384) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
