### PR TITLE
[Doc Improvement] [Duplicate images removed ph6] 

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f0c8489efbe4cc658f0d8bf0ea6d072c63042ae/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95a9cff2-a80c-4966-b171-2405da9eeb2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4f0c8489efbe4cc658f0d8bf0ea6d072c63042ae/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14837b3d-7808-4c0d-b7b7-cbccce82178a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4f0c8489efbe4cc658f0d8bf0ea6d072c63042ae/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8a07c0f-451d-4342-ac06-2ae7cd956296) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4f0c8489efbe4cc658f0d8bf0ea6d072c63042ae/msteams-platform%2Fsbs-gs-notificationbot.yml) | 89 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8359be7c-16ed-44c4-8e96-e459ece7170a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4f0c8489efbe4cc658f0d8bf0ea6d072c63042ae/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 83 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/356fdc34-118a-4f9f-b457-72b69b44b5ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4f0c8489efbe4cc658f0d8bf0ea6d072c63042ae/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 83 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/249b2d0e-e69d-4095-bd37-20f10b5b7064) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a9a673c1988cf2ec77e80303715de5cfd0526d21/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0eaa13d5-f511-444a-a749-124ceb5ac390) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a9a673c1988cf2ec77e80303715de5cfd0526d21/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23e89e74-13f6-4531-9b6f-a1a2aea3467f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a9a673c1988cf2ec77e80303715de5cfd0526d21/msteams-platform%2Fsbs-gs-notificationbot.yml) | 89 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d9e8a70-b988-492d-9afd-9d2ed05032d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a9a673c1988cf2ec77e80303715de5cfd0526d21/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 83 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf6b86e0-06ad-4473-af31-d5b153b9aff3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a9a673c1988cf2ec77e80303715de5cfd0526d21/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 83 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7524bb7c-907b-4534-852c-19a952062ed0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa3c2eec93189d870ecccb551634c6d5d5fa501b/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/849c23ec-f605-4916-a359-2950a90a23c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fa3c2eec93189d870ecccb551634c6d5d5fa501b/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef1b8c5b-a94d-42bd-8509-b9a31955a245) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fa3c2eec93189d870ecccb551634c6d5d5fa501b/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62889550-fc5d-4514-9ad7-160d55836313) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fa3c2eec93189d870ecccb551634c6d5d5fa501b/msteams-platform%2Fsbs-gs-notificationbot.yml) | 89 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2d4348e-dfe6-45ed-9c11-7cee5e858318) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fa3c2eec93189d870ecccb551634c6d5d5fa501b/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 83 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94cfb819-0bf0-4b9f-826f-aee81c03032a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fa3c2eec93189d870ecccb551634c6d5d5fa501b/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 83 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7aaf832a-290e-4f6b-af31-bb5a5674c7ed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by ashishguptaiitb** [comment]
A cursory check gives me an impression that the images `newclientsecret.png` and `new-client-secret.png` are same/similar. Please check once and accordingly resolve the conflicts in this PR.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ef065c9792f85c8f3cc8324bf3df5a9fe28ae32/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26a23446-56f9-4e55-b48d-ab9701c99ed3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6ef065c9792f85c8f3cc8324bf3df5a9fe28ae32/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97b84ee5-85ef-491c-bc2d-9d3b7e8810ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6ef065c9792f85c8f3cc8324bf3df5a9fe28ae32/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d920d08c-4b9d-4c37-85d6-6903c40fcf85) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6ef065c9792f85c8f3cc8324bf3df5a9fe28ae32/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 83 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f90df271-931f-4131-b36d-c7203a1b6dac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6ef065c9792f85c8f3cc8324bf3df5a9fe28ae32/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 83 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a9979f7-f998-4910-8890-31d6ccf39b2b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99901f6d732cabbdb1f3c08daecf6d3b592c4371/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66b81ffc-2607-4fe5-b54d-4a2e942826bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99901f6d732cabbdb1f3c08daecf6d3b592c4371/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1035ef8-a59d-4e28-a8e8-08de9ed2301b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/99901f6d732cabbdb1f3c08daecf6d3b592c4371/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc79876c-b0a2-4e80-ad1d-b0a0374a4f32) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/99901f6d732cabbdb1f3c08daecf6d3b592c4371/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c950e0eb-8480-40d8-9e85-e58b1d5e6c48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/99901f6d732cabbdb1f3c08daecf6d3b592c4371/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 83 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59721dd4-7367-4b64-a429-ac4765faf611) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/99901f6d732cabbdb1f3c08daecf6d3b592c4371/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dba1c692-1ccc-4332-b43d-8a2a24d28c78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/99901f6d732cabbdb1f3c08daecf6d3b592c4371/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 83 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b886841-c787-42da-bbba-d5a5d9b75571) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/99901f6d732cabbdb1f3c08daecf6d3b592c4371/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a8db672-f86c-4617-8efe-8f7fa5562651) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb6cc1338dbb77b5caa6601447385b0141f17af4/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66253abb-02e7-41aa-8e17-10c1b483ad66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb6cc1338dbb77b5caa6601447385b0141f17af4/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/847c1aea-74b6-48d5-b1ef-fdc26190de5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cb6cc1338dbb77b5caa6601447385b0141f17af4/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02a53657-20cd-4473-adfb-43b3dd90f339) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cb6cc1338dbb77b5caa6601447385b0141f17af4/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4739d69-78e5-4e8a-a345-afa26c185774) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cb6cc1338dbb77b5caa6601447385b0141f17af4/msteams-platform%2Fsbs-gs-notificationbot.yml) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/351cffb8-9121-43e0-bc4f-32b91a6a5bfd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cb6cc1338dbb77b5caa6601447385b0141f17af4/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 83 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f92a8fb8-df63-4dc1-9359-5868d89d4c10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cb6cc1338dbb77b5caa6601447385b0141f17af4/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e7f7963-de4a-4906-9750-fcfb8560b850) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cb6cc1338dbb77b5caa6601447385b0141f17af4/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 83 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39674b6b-760e-4f0a-abe3-2a1fc180124e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cb6cc1338dbb77b5caa6601447385b0141f17af4/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05223de5-1470-449c-9362-704b359451d6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab97465726067f57d23060363d0c08fb5dbff00a/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5783b8fb-a20e-411d-8d0b-7ad4b84296a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab97465726067f57d23060363d0c08fb5dbff00a/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17c412ab-d7be-4396-9df5-c3f82fb459bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab97465726067f57d23060363d0c08fb5dbff00a/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26a1d764-6b58-4315-9f51-c13b063ef810) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab97465726067f57d23060363d0c08fb5dbff00a/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63a1cdb1-8083-4f65-bd1c-fbf2ee861781) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab97465726067f57d23060363d0c08fb5dbff00a/msteams-platform%2Fsbs-gs-notificationbot.yml) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a984db46-7943-48df-83cd-6d6e89caae22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab97465726067f57d23060363d0c08fb5dbff00a/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 83 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9114bd29-a73e-40d5-8521-92d2b78542ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab97465726067f57d23060363d0c08fb5dbff00a/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e7cab6c-53b9-4b34-a578-61e025f17499) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab97465726067f57d23060363d0c08fb5dbff00a/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 83 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b1682c0-6819-4be0-b695-1ba2c537294a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab97465726067f57d23060363d0c08fb5dbff00a/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c73f074-64ca-4559-807e-af8d54b94713) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab97465726067f57d23060363d0c08fb5dbff00a/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 83 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f3a8721-a47e-4d3b-b4e9-c4db5e129d76) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab97465726067f57d23060363d0c08fb5dbff00a/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c4d206a-c409-491d-bb62-bdcf58bf62ed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-sdhakshina** [comment]
@ashishguptaiitb 

Conflicts resolved and duplicate images removed as per your comment.

**Review by ashishguptaiitb — APPROVED** [review]

**Pull request merged**
