### PR TITLE
[Doc Improvement][metadata-keywords-changes1][2333806]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/device-capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c77e5ff588f90e690aa91439afe114e977b10aae/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fdevice-capabilities-overview.md) | 88 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96e4fb7a-29a0-4da5-832f-11afc9194803) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/device-capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/24c354be204b6bbee3234afd36a4eafdb50c236b/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fdevice-capabilities-overview.md) | 88 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91c30b3d-83a3-416e-9910-a9d3b361f9b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/24c354be204b6bbee3234afd36a4eafdb50c236b/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 88 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/296643ba-bebb-4398-8e8b-ed260e296458) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/device-capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82ba319b64ea40bb96b957d55b471b04e32f685c/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fdevice-capabilities-overview.md) | 88 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c147f71-6250-41af-8994-ca4cf49a4b9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82ba319b64ea40bb96b957d55b471b04e32f685c/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97cad4c3-9694-488c-aa67-6df7f6be4d40) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/device-capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b339a36c5ad2f0b5f90509d731664256097ee3e7/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fdevice-capabilities-overview.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6eafe437-604e-494d-b42f-5135180ce22e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b339a36c5ad2f0b5f90509d731664256097ee3e7/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a16bb776-bbb1-4fc4-ad5a-2899057ff7e5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/device-capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6688e07ce47b7cda95ce73a635d7ac4470658cc4/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fdevice-capabilities-overview.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa8e48a4-4725-47dc-afb4-89cbdf76db18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6688e07ce47b7cda95ce73a635d7ac4470658cc4/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f65cdc8-c844-4f45-965e-50c05570596e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
