### PR TITLE
[Doc Improvement][Remove App customization from design your app][2909813]

### PR DESCRIPTION
**Pull request by v-ypalikila**
Removed app customization from design your app and added to Configure default install options.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/389ef078a33a3ba1a693157f236d62b1f78562ab/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5f6cfaf-0a7b-4c63-88ce-d50790ea1754) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/add-default-install-scope.md](https://github.com/MicrosoftDocs/msteams-docs/blob/389ef078a33a3ba1a693157f236d62b1f78562ab/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fadd-default-install-scope.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c0d52b6-7dbb-4cb4-bfd5-7a28b153e3f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/389ef078a33a3ba1a693157f236d62b1f78562ab/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db98c9cb-9147-4956-bd9a-54e45e715e7d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8b38f372cd405d6234bb23f6287bb432f41820/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2defd75d-8090-42be-b892-b09a749cada1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/add-default-install-scope.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8b38f372cd405d6234bb23f6287bb432f41820/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fadd-default-install-scope.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32a358dc-491b-4d48-801b-e6a6d5a5bb67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8b38f372cd405d6234bb23f6287bb432f41820/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5760905-4909-487c-8232-11d582c32d9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8b38f372cd405d6234bb23f6287bb432f41820/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25091e6d-cbdc-4163-b81e-d534edf2f2e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8b38f372cd405d6234bb23f6287bb432f41820/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 93 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fe7da03-24d5-4b72-adbb-79503280ab51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c8b38f372cd405d6234bb23f6287bb432f41820/msteams-platform%2Fwhats-new.md) | 94 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb64656e-01ce-46d4-9084-f919c09e1442) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d06a18efd79e3a2fc82295b0e78649f106e3fbfe/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c512093-c553-47ce-b8c5-783b3863fab1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/add-default-install-scope.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d06a18efd79e3a2fc82295b0e78649f106e3fbfe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fadd-default-install-scope.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06ea5e37-bb35-4742-9e0b-72819f663cdb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d06a18efd79e3a2fc82295b0e78649f106e3fbfe/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e564dd2c-de5d-4244-a467-bb6e81cfc3a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d06a18efd79e3a2fc82295b0e78649f106e3fbfe/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/943a386c-3b6c-4ebc-9320-b8de905c0b39) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d06a18efd79e3a2fc82295b0e78649f106e3fbfe/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 93 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/924623ec-cd0d-48b1-8811-8270eedb54d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d06a18efd79e3a2fc82295b0e78649f106e3fbfe/msteams-platform%2Fwhats-new.md) | 94 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f32a936-7571-496c-8032-8ddc674b35ed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dbae61b5d537fc9882d142d2e07a90ece15e0c60/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27650ba0-8cf8-41eb-a6f5-64c9a2696a65) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/add-default-install-scope.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbae61b5d537fc9882d142d2e07a90ece15e0c60/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fadd-default-install-scope.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51a9c4e4-2d75-46d5-92c6-23e729c10e02) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbae61b5d537fc9882d142d2e07a90ece15e0c60/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc6f9406-b06e-41c9-9cbf-cc8f694942cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbae61b5d537fc9882d142d2e07a90ece15e0c60/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69a948d5-5534-4b5b-94fb-d88b77c53cbe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbae61b5d537fc9882d142d2e07a90ece15e0c60/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 93 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff4ea710-b879-4f9b-ac16-8655176c0053) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbae61b5d537fc9882d142d2e07a90ece15e0c60/msteams-platform%2Fwhats-new.md) | 94 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0f05da2-623a-4655-af44-f62c728b89b1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a51794c6dd18bfae8a1b9452226ef5be07a1efc6/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea5554f2-630b-4acd-849c-173b3f3e5b92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/add-default-install-scope.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a51794c6dd18bfae8a1b9452226ef5be07a1efc6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fadd-default-install-scope.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6288c47f-056e-4921-935b-5b2db21800ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a51794c6dd18bfae8a1b9452226ef5be07a1efc6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b43a6c0-c0f6-42f7-9f87-07a8159bce87) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a51794c6dd18bfae8a1b9452226ef5be07a1efc6/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fccba3c3-9383-4229-b811-a7be59e62509) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a51794c6dd18bfae8a1b9452226ef5be07a1efc6/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 93 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05f497ec-05fb-4e50-864a-b31c2b21028b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a51794c6dd18bfae8a1b9452226ef5be07a1efc6/msteams-platform%2Fwhats-new.md) | 94 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8481f87-9472-4e18-8087-57891c1d9c03) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/212322b5a14d29a203c9c3b2d8ad30895ecdc3ee/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dadd7811-033c-4613-8b27-f46ea91b7c4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/add-default-install-scope.md](https://github.com/MicrosoftDocs/msteams-docs/blob/212322b5a14d29a203c9c3b2d8ad30895ecdc3ee/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fadd-default-install-scope.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d7253ce-3640-4bbd-8450-9590b49bc59f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/212322b5a14d29a203c9c3b2d8ad30895ecdc3ee/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5977029a-7ee5-490d-8816-83112896932f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/212322b5a14d29a203c9c3b2d8ad30895ecdc3ee/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02fed78b-6b36-4bf5-9ac6-21481d27668e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/212322b5a14d29a203c9c3b2d8ad30895ecdc3ee/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 93 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0fc76cc3-df47-475f-950c-b98e9d8e374c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/212322b5a14d29a203c9c3b2d8ad30895ecdc3ee/msteams-platform%2Fwhats-new.md) | 94 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/138839e8-50cf-4172-bf99-8b5691ba0fd0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
