### PR TITLE
[Doc Improvement][Casing and sign in fixes][2987574]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-files.md](https://github.com/MicrosoftDocs/msteams-docs/blob/69c032769dbb12fc07107a2aa2eff2fcb74d807a/msteams-platform%2Fresources%2Fbot-v3%2Fbots-files.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e78d94a-e8ee-4293-8fdf-eacea68d94d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-menus.md](https://github.com/MicrosoftDocs/msteams-docs/blob/69c032769dbb12fc07107a2aa2eff2fcb74d807a/msteams-platform%2Fresources%2Fbot-v3%2Fbots-menus.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3333a431-5d1e-473a-b84b-cdcf0f81d40d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/69c032769dbb12fc07107a2aa2eff2fcb74d807a/msteams-platform%2Fresources%2Fbot-v3%2Fbots-notifications.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/985e2435-fe6d-4e24-82c5-8b6701afb9fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/69c032769dbb12fc07107a2aa2eff2fcb74d807a/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ce10bc6-0490-45eb-995d-67b6a94916c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/69c032769dbb12fc07107a2aa2eff2fcb74d807a/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7fdd194-e633-401d-a931-feb7a9d190dd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2e2eebc2fa02eae45c50233448ed97f5acc2953/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26d56e6c-b6cd-43a2-bda3-9d52fd346f1b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2e2eebc2fa02eae45c50233448ed97f5acc2953/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d71d20a-f263-4272-b9c9-ff91c1f75ee6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fe0468a5e679082c355f821589411f4111b7bdbf/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c6d6571-45eb-465b-9342-f1291c977010) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fe0468a5e679082c355f821589411f4111b7bdbf/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd77df89-8be8-4608-8af9-644c48d607fb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/879fe2f8358a17c1086e4e169f2c7905f5b285af/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51deea01-2f24-410c-bff9-7ba885efee88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/879fe2f8358a17c1086e4e169f2c7905f5b285af/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c9571a8-4aab-4527-a304-b140dcb0d40c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c12a24f12b464132ebe8cccf04e3c92d6eb1e710/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7553625d-fe06-4e88-b814-4e7d89c0e3c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c12a24f12b464132ebe8cccf04e3c92d6eb1e710/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/057bcc28-7950-404f-a8ed-2a0ba26a8319) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98ea6c317abd2c2c5eb21822864781fba721ca99/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5405955d-923c-4458-b134-411653d02bf7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98ea6c317abd2c2c5eb21822864781fba721ca99/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e6a6893-42b4-411f-a9a5-d0e9796123a6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad095dc20e7bbca6897afffcdf082937df56b209/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7178a775-c70a-4759-ad70-ab734a2c11de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad095dc20e7bbca6897afffcdf082937df56b209/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c34ed5b4-b91b-4fcb-bbf9-a4d930453d44) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/142ca10eb95c3b5a26d7444777331161ce7720ed/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89ac3a17-447b-4c92-ae86-059ecebc7eb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/142ca10eb95c3b5a26d7444777331161ce7720ed/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d722924-248c-4a03-8e13-7a043d76f295) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4489c52f1ebc253108ce46da077ff2fa97f0d9b7/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11c4113c-a9f2-4c17-97e4-7f0656548b3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4489c52f1ebc253108ce46da077ff2fa97f0d9b7/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/971ac903-00d6-410c-a3e2-7b3bd99f9b0c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ffd754128434b7d0ce8e15ab7ad585abdbf977c/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f88ef467-753e-461a-9aa9-e93b1830019e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ffd754128434b7d0ce8e15ab7ad585abdbf977c/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04a95a32-4661-46c2-a21b-dfe581c839fd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4abae92ae27369ed1a9791e0f0b569f7805eff0b/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46c65cb8-ec4c-41eb-8502-ec084908b190) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4abae92ae27369ed1a9791e0f0b569f7805eff0b/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/466fec35-c4af-43d4-97e0-89e389d9c80e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-habibaumme — APPROVED** [review]

**Pull request merged**
