### PR TITLE
[Doc Improvement][edits-validation guidelines]

### PR DESCRIPTION
**Pull request by v-shalinir**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/review-copilot-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1dc5b5398dd910a935224c7a0e572515e613cbf5/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Freview-copilot-validation-guidelines.md) | 84 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f459fc6-5e6f-4248-8a6d-c044ea34dfa9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/dev-guidelines-copilot-agents.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1dc5b5398dd910a935224c7a0e572515e613cbf5/msteams-platform%2Fmessaging-extensions%2Fdev-guidelines-copilot-agents.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f36dcba-840d-47c3-ab31-e3ff3ee977e4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/review-copilot-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfdc293ea1ea1b82f4be6690e17e4ff21da15e70/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Freview-copilot-validation-guidelines.md) | 84 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58c0e08e-36d5-42af-800d-66011496f6d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/dev-guidelines-copilot-agents.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfdc293ea1ea1b82f4be6690e17e4ff21da15e70/msteams-platform%2Fmessaging-extensions%2Fdev-guidelines-copilot-agents.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ec3c858-78d0-4ec8-9c3b-2b119a5c5729) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/review-copilot-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c04667a9aa664b087cd4b792b465ba00836b3b6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Freview-copilot-validation-guidelines.md) | 84 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7994368d-dcb0-4643-a92f-b5ab8f5de164) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/dev-guidelines-copilot-agents.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c04667a9aa664b087cd4b792b465ba00836b3b6/msteams-platform%2Fmessaging-extensions%2Fdev-guidelines-copilot-agents.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54a3b9e7-14a0-429e-8984-980b7330a435) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c04667a9aa664b087cd4b792b465ba00836b3b6/msteams-platform%2Fwhats-new.md) | 90 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb58ce45-512b-4e73-8af9-07f3bfe1b63c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/review-copilot-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12a1975aa2b9d286382e29d7e59c6e51eb51fc45/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Freview-copilot-validation-guidelines.md) | 84 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f73f15a0-f99b-498f-8edc-efe657cd51fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/dev-guidelines-copilot-agents.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12a1975aa2b9d286382e29d7e59c6e51eb51fc45/msteams-platform%2Fmessaging-extensions%2Fdev-guidelines-copilot-agents.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6665ad04-91d2-4748-83e4-368775d831cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12a1975aa2b9d286382e29d7e59c6e51eb51fc45/msteams-platform%2Fwhats-new.md) | 90 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad05050e-1e33-44e1-ab82-7e0f6f26f3ed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
