### PR TITLE
[Doc Improvement][Targeted in-meeting notification GA]

### PR DESCRIPTION
**Pull request by v-ypalikila**
Removed Dev preview note and updated what's new to GA.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cae531e8f4eccdafdf9f71dad2331caecc0ec757/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8fee1cd6-9cdc-4f1d-8eb4-9ea0316fc025) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cae531e8f4eccdafdf9f71dad2331caecc0ec757/msteams-platform%2Fwhats-new.md) | 89 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c33dc5a-e636-47dd-8fa7-ebde17b4d556) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3936ab2ea6814994f2e997199ce1f70515cbc4dd/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f50a5fd1-fd3b-4f11-b38e-fd0a6b96085b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3936ab2ea6814994f2e997199ce1f70515cbc4dd/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aac26612-7e25-49aa-97ed-8265866ee47b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3936ab2ea6814994f2e997199ce1f70515cbc4dd/msteams-platform%2Fwhats-new.md) | 89 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81581c4e-f107-4c07-a607-967013d564d7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3750319b06d63654135782f7ed05de8770ba978e/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7afd607e-4068-47e1-8ef5-9adcd3b60db3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3750319b06d63654135782f7ed05de8770ba978e/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b864a25-5f0b-4097-b49f-fd2efaaec50b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3750319b06d63654135782f7ed05de8770ba978e/msteams-platform%2Fwhats-new.md) | 89 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1425ee51-987f-4219-8556-a9d05603e249) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by ChetanSharma-msft — APPROVED** [review]
Looks fine, approving it.

**Review by YunnyChung — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c5bb13db4bcf8c0a785811264437d222052de6f9/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b78ef20b-47fd-4c72-a7e6-28b4ee286034) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c5bb13db4bcf8c0a785811264437d222052de6f9/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5caf227c-bc9b-4ca7-a51b-fe4b678e12e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c5bb13db4bcf8c0a785811264437d222052de6f9/msteams-platform%2Fwhats-new.md) | 89 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d13dccb-3ade-4362-b8dc-34193907092c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a97ed829ebb838df9c9e42fc1605485b1f269bf8/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/129320a3-f7eb-445b-bf0e-fe463afe99fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a97ed829ebb838df9c9e42fc1605485b1f269bf8/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d26f147-0af9-4498-901b-92a97881ce5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a97ed829ebb838df9c9e42fc1605485b1f269bf8/msteams-platform%2Fwhats-new.md) | 89 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad7f13ad-e57c-462a-b821-a580cffb9b90) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dd160c5fbd2dd7307d00960be3023ff4d2cf468/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 88 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd5bad32-f2f0-41df-ad1e-0b2a10a320ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dd160c5fbd2dd7307d00960be3023ff4d2cf468/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aceebd96-70af-4fa1-ae66-b93ad253803d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dd160c5fbd2dd7307d00960be3023ff4d2cf468/msteams-platform%2Fwhats-new.md) | 89 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83173832-7841-40cd-87e2-3116ab88a188) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Aprpoved

**Pull request merged**
