### PR TITLE
[Doc Improvement][Copilot Validation Guidelines Fixes]

### PR DESCRIPTION
**Pull request by v-kushals**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/review-copilot-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958a49c589dcf4f8100df5d80477caa0699eca2b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Freview-copilot-validation-guidelines.md) | 84 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/497a6f48-48d6-4740-ae84-8bb53491078a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958a49c589dcf4f8100df5d80477caa0699eca2b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 138 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9d1507e-4dfd-4f1a-abb0-257b2e987b59) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958a49c589dcf4f8100df5d80477caa0699eca2b/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 94 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e4f7bcb-662c-43d9-80c8-30afc3fd87eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/copilot-plugin-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958a49c589dcf4f8100df5d80477caa0699eca2b/msteams-platform%2Fmessaging-extensions%2Fcopilot-plugin-faq.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2abd14b4-2b90-495b-b176-64d87ade2668) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/dev-guidelines-copilot-agents.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958a49c589dcf4f8100df5d80477caa0699eca2b/msteams-platform%2Fmessaging-extensions%2Fdev-guidelines-copilot-agents.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ba6883b-54f2-46e3-8476-d18b531bccac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/958a49c589dcf4f8100df5d80477caa0699eca2b/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 92 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8687d87b-1589-46a0-bccd-7cb0bee6c5bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958a49c589dcf4f8100df5d80477caa0699eca2b/msteams-platform%2Fteams-faq.md) | 89 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/beb2707b-d0c5-4ae2-8215-0bb2d4465c6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958a49c589dcf4f8100df5d80477caa0699eca2b/msteams-platform%2Fwhats-new.md) | 90 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd0e3faa-cf18-4537-8d9e-f002db2ff316) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/review-copilot-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b355dff52c982862b6ea9502c7df11ad2bede96f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Freview-copilot-validation-guidelines.md) | 84 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78d4c820-1dd3-4831-bc62-e4fcf2533051) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b355dff52c982862b6ea9502c7df11ad2bede96f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 138 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/adb8abc9-4226-472f-ae17-f540312c02e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b355dff52c982862b6ea9502c7df11ad2bede96f/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 94 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ef55913-eae1-4361-91a2-a7c971d6b78c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/copilot-plugin-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b355dff52c982862b6ea9502c7df11ad2bede96f/msteams-platform%2Fmessaging-extensions%2Fcopilot-plugin-faq.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bc6aae6-0ba7-4722-8802-db4660358edd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/dev-guidelines-copilot-agents.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b355dff52c982862b6ea9502c7df11ad2bede96f/msteams-platform%2Fmessaging-extensions%2Fdev-guidelines-copilot-agents.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be9fad1a-018d-4138-9f74-b4a40cbd71b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b355dff52c982862b6ea9502c7df11ad2bede96f/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 92 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ceae4dbb-4a5c-4921-a8a5-22e8608b1bb5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b355dff52c982862b6ea9502c7df11ad2bede96f/msteams-platform%2Fteams-faq.md) | 89 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25d50ea8-0af7-4297-b4e4-00e04f71a409) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b355dff52c982862b6ea9502c7df11ad2bede96f/msteams-platform%2Fwhats-new.md) | 90 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd2a5c1f-0304-4008-9868-e35ba2ee7327) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/review-copilot-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02c8921b857caa7af470afb8d827d93236735264/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Freview-copilot-validation-guidelines.md) | 84 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0e90c43-e16f-4559-8a37-adcdbe0d39f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02c8921b857caa7af470afb8d827d93236735264/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 138 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f2c7cef-7d3c-4653-bc8e-d113a4e62dce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02c8921b857caa7af470afb8d827d93236735264/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 94 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2255278d-7bf0-4ed7-93cb-aa5fafef9978) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/copilot-plugin-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02c8921b857caa7af470afb8d827d93236735264/msteams-platform%2Fmessaging-extensions%2Fcopilot-plugin-faq.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7edf6ede-c599-49c9-a951-eb392165130f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/dev-guidelines-copilot-agents.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02c8921b857caa7af470afb8d827d93236735264/msteams-platform%2Fmessaging-extensions%2Fdev-guidelines-copilot-agents.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1aa26c4c-cca8-4108-ab05-7f0494b7720e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/02c8921b857caa7af470afb8d827d93236735264/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 92 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e769478-3677-4ec1-ba19-1f029fd73e4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02c8921b857caa7af470afb8d827d93236735264/msteams-platform%2Fteams-faq.md) | 89 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/adf9b482-3e2c-407d-8ad0-05b744451c1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02c8921b857caa7af470afb8d827d93236735264/msteams-platform%2Fwhats-new.md) | 90 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/989a6b6b-62fb-46d0-a194-768a3d013b9d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/review-copilot-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1998d8ee5cd3e840129a17e362d521eff997302/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Freview-copilot-validation-guidelines.md) | 84 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/197bcd30-f014-4b8c-9b60-e5e03f22adac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1998d8ee5cd3e840129a17e362d521eff997302/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 137 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79826675-189f-433c-9aa4-14108f4e669a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1998d8ee5cd3e840129a17e362d521eff997302/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 94 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10f54c2f-ea34-45e5-a0f4-167264ab2e65) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/copilot-plugin-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1998d8ee5cd3e840129a17e362d521eff997302/msteams-platform%2Fmessaging-extensions%2Fcopilot-plugin-faq.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bccc6654-a704-43ab-acc8-06103ca01b3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/dev-guidelines-copilot-agents.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1998d8ee5cd3e840129a17e362d521eff997302/msteams-platform%2Fmessaging-extensions%2Fdev-guidelines-copilot-agents.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0d2bb40-13d2-453a-b6ca-0dab3516a35f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b1998d8ee5cd3e840129a17e362d521eff997302/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 92 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77de66db-c59d-45fa-8097-154f619f7dd4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1998d8ee5cd3e840129a17e362d521eff997302/msteams-platform%2Fteams-faq.md) | 89 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0e25c4d-547d-4382-93fb-6101eb170ff1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b1998d8ee5cd3e840129a17e362d521eff997302/msteams-platform%2Fwhats-new.md) | 90 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/531f44d8-264b-482e-bb7f-88806e138419) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/review-copilot-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ace534adc054ebc7ab26519b11a05bba9f8f3d0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Freview-copilot-validation-guidelines.md) | 84 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4011b552-abaa-4d3c-8385-692897524512) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ace534adc054ebc7ab26519b11a05bba9f8f3d0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 137 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b243f74b-ac41-455b-b7a8-95cb63c99cbc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ace534adc054ebc7ab26519b11a05bba9f8f3d0/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 94 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2257f4b5-4dbe-48cb-b081-f918cf2a4eea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/copilot-plugin-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ace534adc054ebc7ab26519b11a05bba9f8f3d0/msteams-platform%2Fmessaging-extensions%2Fcopilot-plugin-faq.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9424929-743e-4c4a-856f-41f377f7467e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/dev-guidelines-copilot-agents.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ace534adc054ebc7ab26519b11a05bba9f8f3d0/msteams-platform%2Fmessaging-extensions%2Fdev-guidelines-copilot-agents.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88c08357-751e-4953-9f31-4be5020006b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9ace534adc054ebc7ab26519b11a05bba9f8f3d0/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 92 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c04d01ce-a3aa-4dcd-8ef2-dfc88ea34ba4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ace534adc054ebc7ab26519b11a05bba9f8f3d0/msteams-platform%2Fteams-faq.md) | 89 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b08552a-cd12-4f0b-9d9a-8166f87c21ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ace534adc054ebc7ab26519b11a05bba9f8f3d0/msteams-platform%2Fwhats-new.md) | 90 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db107708-f6d9-41b6-bafa-11463c82f582) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/review-copilot-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fa767d065103e55e5b79d6848f05c88ea48418b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Freview-copilot-validation-guidelines.md) | 84 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e555983-1f24-445f-95be-06f25552dcd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fa767d065103e55e5b79d6848f05c88ea48418b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 137 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/058c5f74-374c-482c-9e5c-3604d2a3ffe5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fa767d065103e55e5b79d6848f05c88ea48418b/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 94 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/721c90f7-efe9-4f0b-85f7-c2c5d78aad13) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/copilot-plugin-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fa767d065103e55e5b79d6848f05c88ea48418b/msteams-platform%2Fmessaging-extensions%2Fcopilot-plugin-faq.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6490a93-bdda-4695-818a-d87cae92ba55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/dev-guidelines-copilot-agents.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fa767d065103e55e5b79d6848f05c88ea48418b/msteams-platform%2Fmessaging-extensions%2Fdev-guidelines-copilot-agents.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95608a5d-e997-44e6-86e3-8aefc7e4eb51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4fa767d065103e55e5b79d6848f05c88ea48418b/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 92 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07f21e1b-4822-4c6c-a6dd-21d52de23e71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fa767d065103e55e5b79d6848f05c88ea48418b/msteams-platform%2Fteams-faq.md) | 89 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/162034c7-7e28-4298-9866-ec57f249c3bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fa767d065103e55e5b79d6848f05c88ea48418b/msteams-platform%2Fwhats-new.md) | 90 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/207556cc-5049-487a-8cf2-7604400fec0b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/review-copilot-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/70457cbad6aa06344eb66a19fef837df60483466/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Freview-copilot-validation-guidelines.md) | 84 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37466a4c-2996-4922-924d-afbef57644ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/70457cbad6aa06344eb66a19fef837df60483466/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 137 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/570b7416-2640-4dfb-a5ca-3c91035bbdd7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/70457cbad6aa06344eb66a19fef837df60483466/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 94 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4237116-ddc3-42fe-879a-ab9018172988) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/copilot-plugin-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/70457cbad6aa06344eb66a19fef837df60483466/msteams-platform%2Fmessaging-extensions%2Fcopilot-plugin-faq.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4183140-b866-4c0d-a452-1b0b20b94117) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/dev-guidelines-copilot-agents.md](https://github.com/MicrosoftDocs/msteams-docs/blob/70457cbad6aa06344eb66a19fef837df60483466/msteams-platform%2Fmessaging-extensions%2Fdev-guidelines-copilot-agents.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92fa9fd4-9ebc-44b2-8f18-981c2c9f584a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/70457cbad6aa06344eb66a19fef837df60483466/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 92 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48e3903d-aef9-43ea-9109-b4018b56de0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/70457cbad6aa06344eb66a19fef837df60483466/msteams-platform%2Fteams-faq.md) | 89 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/019fccb9-e4c7-44a1-8538-52ceee3dba36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/70457cbad6aa06344eb66a19fef837df60483466/msteams-platform%2Fwhats-new.md) | 90 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2a81731-64f4-491f-af4e-3056259c82b1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
