### PR TITLE
[Doc Issue][Revert Tools manual]

### PR DESCRIPTION
**Pull request by v-abirade**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/116939c1915276e5caec51eb090a467d661baa3e/msteams-platform/toolkit/add-resource.md) | 88 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc9d8972-ea99-41af-ac8d-1927e1d7fa24) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/554582904656040217afff44b9e4e95603d0656d/msteams-platform/toolkit/add-resource.md) | 88 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e1d272d-51b2-4c88-9884-4b6c9e120de0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/554582904656040217afff44b9e4e95603d0656d/msteams-platform/toolkit/provision.md) | 83 | 97 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18b31b7e-3255-4228-8774-843fb7b761a9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ef11137c53c28b1a11bbf1c3d36fca515e48c40/msteams-platform/toolkit/add-resource.md) | 88 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc2947c8-6c3a-45fe-a677-bd8ca3dbd697) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ef11137c53c28b1a11bbf1c3d36fca515e48c40/msteams-platform/toolkit/provision.md) | 83 | 97 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70040343-4c6b-4c8a-abf8-409ec7da20b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ef11137c53c28b1a11bbf1c3d36fca515e48c40/msteams-platform/toolkit/use-CICD-template.md) | 85 | 67 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ec218d6-f657-47d2-addb-6573e956e257) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
