### PR TITLE
[Tabs][Content enhancement][1542438]

### PR DESCRIPTION
**Pull request by Rajeshwari-v**
Updated the content. Please review.

### CODE REVIEW

**Comment by vikramjit-singh-chug** [comment]
1. Width of column #2 and #3 should be same
2. Change Column #3, Row #1 to: "App does not show up in mobile clients."
3. Change Column #3, Row #2 to: "Clicking on the tab opens the content using the websiteUrl in the default web browser on the device."
4. Change Note #1 to: "Apps submitted to the AppSource for publishing on Teams are evaluated automatically for mobile responsiveness. For any queries, please reach out to teamsubm@microsoft.com."

**Review by vikramjit-singh-chug — DISMISSED** [review]

**Review by KirtiPereira — CHANGES_REQUESTED** [review]
@Rajeshwari-v - please check the consistency of capitalization. For example, webview and WebView.
Do a thorough self-review.

**Review by KirtiPereira — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]
Approved the PR.

**Pull request merged**
