### PR TITLE
[Doc Feature][Container layouts in Adaptive Cards][3758775]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/13c86678eae947aff634df4c39c1d9d95a8d5d39/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 65 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c26e1da-2d98-48a1-bfa3-e50f9104c1c1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4904fd877d000ae8cd0cf1e43fb475382d45e80/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 83 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4bd1c6a-d12f-46c6-b08f-7f1e1b3141fa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25714ba8da8389a0fc19ff0304f0c25d5e51306f/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 83 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a83025a7-4e61-4918-8d03-d6c89e760a09) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0c261e25e5d3e20460c5ee9706fcee08f570fed/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 83 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16ad85b0-97a1-4372-bbc1-d1bf4933fbd2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0dcb8d35919971f7e71b856b1444f3331114e233/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a210ed5a-925f-47ab-ac35-b36f62f87df5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dcb8d35919971f7e71b856b1444f3331114e233/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 83 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccf6adac-169c-4b72-a921-7aa677a2d4b1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3e822cdb8aaac180025d8b0e93f2d6a7d4530004/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ee4c630-be82-48eb-bc95-080aeb565514) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e822cdb8aaac180025d8b0e93f2d6a7d4530004/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 83 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1cdb4240-2e12-443c-a114-eaba4aa51a37) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0e308cba3cbd4be2d7bf7c334f300906bb62d792/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66524fb0-819a-4f72-8916-cf0f37fbd465) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0e308cba3cbd4be2d7bf7c334f300906bb62d792/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 85 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36633a13-11fb-48ea-bc0b-cea4294eb1c4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b11a54b3ae3217843f11491a610ffaa9b4f087bf/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc8874a1-f225-464f-898c-694544257d0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b11a54b3ae3217843f11491a610ffaa9b4f087bf/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 85 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3da2447f-1d8a-4c5e-b802-14f8bbbf33c9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a092546206c59d569bf7c837bf0013a19f9ec8e6/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a33046e5-656b-4d0e-9b30-7b9113cca5cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a092546206c59d569bf7c837bf0013a19f9ec8e6/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59508c3c-4d07-41bf-afb5-c39b9b0ddc1b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/563187f44d5f8dd88b4f47eefe5983b47c53002f/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dcbed557-3f43-4044-ae48-8d7e7615d69a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/563187f44d5f8dd88b4f47eefe5983b47c53002f/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aae41162-7dac-482b-a336-6b53a88cb82c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e0528f12a39ac3ec46f48052cf9e5234d296ca41/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e59d39c1-86b6-4b94-bffe-d8b7b45f0d57) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0528f12a39ac3ec46f48052cf9e5234d296ca41/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae4bd470-e3b5-490a-9f4e-63f3f47640ca) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d53a202fc1180304f0da23a2e90a58835a68a2a0/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/483520e1-876e-4515-b543-30eecd323ef4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d53a202fc1180304f0da23a2e90a58835a68a2a0/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f4504c0-589e-499f-b0f8-f2c0351cf621) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e85bed3eb25c986eb3a83885337c729c6039d598/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f905a97-9055-44cc-9c7e-836045608eab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e85bed3eb25c986eb3a83885337c729c6039d598/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9781ea8b-dafc-4400-8f36-a762f29276de) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c1f07fa48b8004af795f2582209224c62f7b8188/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99fb4a93-fc71-4cf0-ac45-113c2cc7ead2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c1f07fa48b8004af795f2582209224c62f7b8188/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7341654-b8a7-4923-ac6e-72c8e05b9d91) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/567b6af5efbb767fdca48dcf2efabe7d0539abc1/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e231d04-6ae2-4286-9980-28f385ff3644) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/567b6af5efbb767fdca48dcf2efabe7d0539abc1/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49f09c98-fa11-403c-8c67-4733db1c1acd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ffd34740bea89c58db090784a3f9ef0987f63614/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/806adff2-9738-4a1c-804d-90a57e97481b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ffd34740bea89c58db090784a3f9ef0987f63614/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3720ff1-663e-4588-aa4d-455010340543) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9ea9378288e8f02a8d50d7a331e213eef85102d8/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d594446b-776a-421f-85f8-faab4d5868b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ea9378288e8f02a8d50d7a331e213eef85102d8/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1fcfb3a-615c-48fb-986c-f2578980402f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/686610f8113e0508e9c751c6600ba1009db90f3c/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83fbc074-1e21-4fd0-82e2-43137e6594dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/686610f8113e0508e9c751c6600ba1009db90f3c/msteams-platform%2Fmstdd-landing.yml) | 87 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f4363e2-3666-40f6-b884-9e6ded75a7c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/container-layouts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/686610f8113e0508e9c751c6600ba1009db90f3c/msteams-platform%2Ftask-modules-and-cards%2Fcontainer-layouts.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a41b813-94c3-424b-8464-72fb14c9941e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/686610f8113e0508e9c751c6600ba1009db90f3c/msteams-platform%2Fwhats-new.md) | 90 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c20ef056-35a4-4300-bfa7-b5066f29177a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Pull request merged**
