### PR TITLE
[Doc Improvement][Verify and fix sign in and casing][3024405]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/591e3b339c832b7057b210c9e5f5b9d6d68f8434/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-actions.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc4f9c82-d316-4ba6-9072-d17c4cea9410) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/591e3b339c832b7057b210c9e5f5b9d6d68f8434/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-format.md) | 96 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c9a8545-4310-48da-856e-d24cf5ff9fb7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/591e3b339c832b7057b210c9e5f5b9d6d68f8434/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-reference.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db7018c2-8360-48e5-900c-95fd34152b4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/591e3b339c832b7057b210c9e5f5b9d6d68f8434/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44756f93-c6fe-4ff6-95cb-381e1cdb6a82) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/591e3b339c832b7057b210c9e5f5b9d6d68f8434/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/051077af-dc25-4d63-ada2-d9bc86a9b1e6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27aa517dee5b2464644c0ef82262d50d5fdbf9f3/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2FOverview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6833d2f-a3fa-4d5f-92e8-f995828a71e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27aa517dee5b2464644c0ef82262d50d5fdbf9f3/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-actions.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c17d0c3-e0e7-47af-9976-58eff053ca62) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27aa517dee5b2464644c0ef82262d50d5fdbf9f3/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-format.md) | 96 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f55428c9-6e34-4b52-88fb-f25273d5135c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27aa517dee5b2464644c0ef82262d50d5fdbf9f3/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-reference.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bde5985b-8e64-460a-ae76-c245d54d287f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27aa517dee5b2464644c0ef82262d50d5fdbf9f3/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a68a096-14ac-455f-bf50-5055492a04cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27aa517dee5b2464644c0ef82262d50d5fdbf9f3/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5de2bc66-2139-459f-a698-caf70aaa930d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/browser-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43c586e27ed1baad7336d2ea0ba18810b5fefb05/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fbrowser-device-permissions.md) | 91 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66926c7b-2b48-4cc4-9341-53f60ca2804c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43c586e27ed1baad7336d2ea0ba18810b5fefb05/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18e1f9af-457b-4c3c-bccf-6276a50fc88f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43c586e27ed1baad7336d2ea0ba18810b5fefb05/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a80b58c9-0b4f-4d5e-904c-c38228dfadba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43c586e27ed1baad7336d2ea0ba18810b5fefb05/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2FOverview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/141100f0-52f2-47e7-9cb7-a0fe7becf33f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43c586e27ed1baad7336d2ea0ba18810b5fefb05/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-actions.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba7b0b92-8dd0-469b-acf5-fb7c487c9885) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43c586e27ed1baad7336d2ea0ba18810b5fefb05/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-format.md) | 96 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9b40682-d688-475f-82cb-34b958f0ec3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43c586e27ed1baad7336d2ea0ba18810b5fefb05/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-reference.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93e75c58-caf7-498f-9747-2272836e76a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43c586e27ed1baad7336d2ea0ba18810b5fefb05/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b6a047b-b78e-4dcb-9268-479be54ffdcb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43c586e27ed1baad7336d2ea0ba18810b5fefb05/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc66c841-e673-4556-ae67-3bfa153c4bac) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/browser-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93721895b002cb0b88478fdd62db4206e26139c/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fbrowser-device-permissions.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27004e74-34a1-4eef-ac7f-5f661bb1e614) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93721895b002cb0b88478fdd62db4206e26139c/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bca39227-95ee-40a3-8120-f05e75a48c2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93721895b002cb0b88478fdd62db4206e26139c/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2FOverview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6361af6e-aa0b-4124-9e3d-2ad99b7c4400) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93721895b002cb0b88478fdd62db4206e26139c/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-actions.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb9c18b0-fa3b-4b70-8d66-6b16b907ed1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93721895b002cb0b88478fdd62db4206e26139c/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-reference.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/742550a9-d501-4592-8eef-646b5aec3efd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93721895b002cb0b88478fdd62db4206e26139c/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c8e843b-f621-41bf-a3ff-9a5de805545c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/browser-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac065566e3c83684a049d66ec91406153a40a7e9/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fbrowser-device-permissions.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d5d1a33-6262-4ebd-821c-cb3e290980d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac065566e3c83684a049d66ec91406153a40a7e9/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09309c7d-d68b-4ab0-8636-648aec5cc061) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac065566e3c83684a049d66ec91406153a40a7e9/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2FOverview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37eb6f68-a869-44a1-aff0-62263cb0b362) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac065566e3c83684a049d66ec91406153a40a7e9/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-actions.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e826002-e44b-43c6-930e-bb991205ba88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac065566e3c83684a049d66ec91406153a40a7e9/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-reference.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6998cef-cda5-4c72-bdbc-c79798392249) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac065566e3c83684a049d66ec91406153a40a7e9/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92c2e3bf-0db2-4fc5-99b2-5065f9588819) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/browser-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/521ae8c4a2be70b8198032636a5c76e09922bb3c/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fbrowser-device-permissions.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5e067e9-53bc-421f-a9c0-6665d62f7a84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/521ae8c4a2be70b8198032636a5c76e09922bb3c/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bcc6b4f2-a6f6-4c72-94d0-6da7880f4410) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/521ae8c4a2be70b8198032636a5c76e09922bb3c/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2FOverview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9082716-348a-4807-8c87-3ea55547fcad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/521ae8c4a2be70b8198032636a5c76e09922bb3c/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-actions.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32f434d0-190f-46c4-9b8c-62628a872a2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/521ae8c4a2be70b8198032636a5c76e09922bb3c/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-reference.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4e59c81-3370-4677-9f26-0dd8587507c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/521ae8c4a2be70b8198032636a5c76e09922bb3c/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb31d407-e33a-4e86-a999-da1c1efc173c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Pull request merged**
