### PR TITLE
[Doc Improvement][Manifest property link update][3178460]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5013b027e9f9b70d25c950109115a05cd8de54a/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 96 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17ece7b9-145b-4237-80c5-d31b32e9d608) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5013b027e9f9b70d25c950109115a05cd8de54a/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ae11b7a-d60a-4379-a5dc-b2a78f79cb59) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5013b027e9f9b70d25c950109115a05cd8de54a/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2917afb-f551-412a-8063-5ad8d7f95711) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5013b027e9f9b70d25c950109115a05cd8de54a/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fc6d84e-147e-425b-bcd4-97315b47e599) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5013b027e9f9b70d25c950109115a05cd8de54a/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7b8f3cd-de7f-4576-be49-3789517512b8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd820cc3a38d0c6e5df1de6c3dddf96d3b40b2d7/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 96 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa2fd62d-3c13-4704-bf63-867f6ca09c24) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd820cc3a38d0c6e5df1de6c3dddf96d3b40b2d7/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02ad5db2-a715-4df3-b8ab-7eb2ee1cc05b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd820cc3a38d0c6e5df1de6c3dddf96d3b40b2d7/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0c43dc5-f261-4e38-8d03-afac9b6a4214) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd820cc3a38d0c6e5df1de6c3dddf96d3b40b2d7/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d15f174-bb0b-4db6-9db7-b8bfd58d3fcb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd820cc3a38d0c6e5df1de6c3dddf96d3b40b2d7/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8a0770f-6452-4e88-b181-a1b0dcdfbc5c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64f0b5ba452136ade1802d38fdeb5d0ebed989e0/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 96 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40bc79e0-db92-4b50-8890-2b14ea6b8a10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64f0b5ba452136ade1802d38fdeb5d0ebed989e0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/102a3c79-90ce-471f-aadc-acb4657ca4df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64f0b5ba452136ade1802d38fdeb5d0ebed989e0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e00599d8-209c-4b24-b679-e3d92e87142e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64f0b5ba452136ade1802d38fdeb5d0ebed989e0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab5d00af-db2a-4847-96c3-8ca556791292) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64f0b5ba452136ade1802d38fdeb5d0ebed989e0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0db8a423-31c0-4f90-94ea-8308dfcd2701) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/89d746cedad009b2410096f4aa7d943fb1a18b73/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 96 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c4f3f8a-7f24-47ac-a146-55a40af660ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/89d746cedad009b2410096f4aa7d943fb1a18b73/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4c2a46c-fa08-4200-b789-8cb4056065b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/89d746cedad009b2410096f4aa7d943fb1a18b73/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9fc919a-08ea-447e-ac45-6445dd0d5d19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/89d746cedad009b2410096f4aa7d943fb1a18b73/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3102ade0-f0ef-4196-87f1-4fda6221bc99) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/89d746cedad009b2410096f4aa7d943fb1a18b73/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7570681c-ca19-4ac4-863b-43256e74e1e7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92732ed92c1ac036c9a4ccbd65d1246a9161f5d1/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 96 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fab0531b-b4e8-4903-af57-bdf1ed1deb69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92732ed92c1ac036c9a4ccbd65d1246a9161f5d1/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe8ccc3b-7e70-4823-9e3f-cbd7acc5153e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92732ed92c1ac036c9a4ccbd65d1246a9161f5d1/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6f96d9d-2d76-4bc3-bf54-ecf7ca799bbe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92732ed92c1ac036c9a4ccbd65d1246a9161f5d1/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1b2c0a8-e3f9-4240-8ac5-f466d4d53287) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92732ed92c1ac036c9a4ccbd65d1246a9161f5d1/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0153fc16-ec7e-4373-ac0d-726b54f8eb50) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/726b4c17bf772628bfb3e9b4200353812c0354df/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 96 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4cc0812-7de2-43a5-97b7-e8b7122ca7cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/726b4c17bf772628bfb3e9b4200353812c0354df/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/152d9ca1-267a-46d7-931b-695a2740f32b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/726b4c17bf772628bfb3e9b4200353812c0354df/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60798be3-f606-405f-889d-801e0832aa61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/726b4c17bf772628bfb3e9b4200353812c0354df/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d98bc835-9e90-47ad-9f1c-5b584b7b4099) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/726b4c17bf772628bfb3e9b4200353812c0354df/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e354a4f4-201a-4135-9289-2bed15215a0d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7719277ea67748021a82a9d3d39e93138841e73b/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 96 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3bbcc1b-0c46-4af9-8205-28ec99253152) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7719277ea67748021a82a9d3d39e93138841e73b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a4eb843-127b-46d7-9e7b-b26d970a9484) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7719277ea67748021a82a9d3d39e93138841e73b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a51105d-fa94-45cc-8436-5b16c7434342) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7719277ea67748021a82a9d3d39e93138841e73b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56b19b30-8b92-4040-a386-f785b3257216) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7719277ea67748021a82a9d3d39e93138841e73b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 87 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5445bdfb-f65e-409b-b6c9-472e4d575270) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb0cee95353df9b3a373613c4e32060670db7ae0/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 96 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2e9af6e-08ad-4ea5-b218-b6272f77aead) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb0cee95353df9b3a373613c4e32060670db7ae0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e65c420e-66f0-4f88-8f48-f3dbffdbc7b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb0cee95353df9b3a373613c4e32060670db7ae0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bd384de-36b8-4347-be82-cb7e49b2a903) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb0cee95353df9b3a373613c4e32060670db7ae0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40fef92a-ab0e-4774-a892-4848a2ad27aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb0cee95353df9b3a373613c4e32060670db7ae0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/008ed34b-39b2-46ea-8522-0f32f884dc94) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f935d55ca56cd128b8bde8997fed58dfeb6e53b9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16ef0243-210b-4ee8-995b-4ec42f9f9f9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f935d55ca56cd128b8bde8997fed58dfeb6e53b9/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d947fcf-c35a-4bc3-926f-055337dd34f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f935d55ca56cd128b8bde8997fed58dfeb6e53b9/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 96 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbe8ba87-56a0-4cb3-9e64-042e5b9c0ca4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f935d55ca56cd128b8bde8997fed58dfeb6e53b9/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04d4c44e-da71-4815-b698-8e48efb8ac8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f935d55ca56cd128b8bde8997fed58dfeb6e53b9/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e86fa4b-4ee7-4238-a312-2f19dbd9ab93) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f935d55ca56cd128b8bde8997fed58dfeb6e53b9/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f3a76a4-cb24-4729-bfbc-066d097aa06e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f935d55ca56cd128b8bde8997fed58dfeb6e53b9/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ec54e2f-23ff-4b29-80c3-f7475dba7b24) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f935d55ca56cd128b8bde8997fed58dfeb6e53b9/msteams-platform%2Fresources%2Ftroubleshoot.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/275b7d04-a427-4246-93ba-4ce069d0c3b8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
