### PR TITLE
[Doc Improvement][Build bots and messaging extensions articles][2720393]

### PR DESCRIPTION
**Pull request by v-ajiths**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d4c28a3b5285afcbb3b1a78d50aebc9ae0ad7ea/msteams-platform%2Fbots%2Fbot-basics.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44682705-8858-43ec-9bca-cfe083222b61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d4c28a3b5285afcbb3b1a78d50aebc9ae0ad7ea/msteams-platform%2Fbots%2Fbot-features.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e22c1a31-3160-48a5-82e4-30135459d60d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d4c28a3b5285afcbb3b1a78d50aebc9ae0ad7ea/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f336e8c3-f0db-481b-925c-a007fb5213cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d4c28a3b5285afcbb3b1a78d50aebc9ae0ad7ea/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8953d62-cafb-491b-b951-c14e4e64216a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d4c28a3b5285afcbb3b1a78d50aebc9ae0ad7ea/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7527e8b-b74e-4c31-85c2-5648bb5af84a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d4c28a3b5285afcbb3b1a78d50aebc9ae0ad7ea/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae57bf5d-c5cd-48d5-ae49-c8da7f156db7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/universal-actions-for-search-based-message-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d4c28a3b5285afcbb3b1a78d50aebc9ae0ad7ea/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Funiversal-actions-for-search-based-message-extensions.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d347abe-ed2a-442e-a701-93350438cf32) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d4c28a3b5285afcbb3b1a78d50aebc9ae0ad7ea/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef541b77-db78-417f-9f8a-4837532beac2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97aa276dcf14ca7172bec10439e2b90933309a20/msteams-platform%2Fbots%2Fbot-basics.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f5cdf23-2619-4899-a7ec-65551e20ec4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97aa276dcf14ca7172bec10439e2b90933309a20/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe16224c-c708-4153-ad39-bafdfdfddfdb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97aa276dcf14ca7172bec10439e2b90933309a20/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f9e4b7a-99ff-48c9-908f-d374a130dd6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97aa276dcf14ca7172bec10439e2b90933309a20/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99095662-4dbf-47c3-a8f9-bad31c6bbc72) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97aa276dcf14ca7172bec10439e2b90933309a20/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ab12198-78af-42bb-a405-62e833bb5a93) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97aa276dcf14ca7172bec10439e2b90933309a20/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a25bd8f-3818-4526-93e7-3e2e50705d01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/universal-actions-for-search-based-message-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97aa276dcf14ca7172bec10439e2b90933309a20/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Funiversal-actions-for-search-based-message-extensions.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0df78da4-6f74-4a17-8cb9-dd80db027f58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97aa276dcf14ca7172bec10439e2b90933309a20/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b9f33f5-0d91-450b-951d-a1595dfa58c1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d6a6628e6b4c280b3aaa12d83fd0cafc35cee17/msteams-platform%2Fbots%2Fbot-basics.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/695c3546-ae31-40a6-b8fe-ff52d20aa827) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d6a6628e6b4c280b3aaa12d83fd0cafc35cee17/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f25a5346-eac9-4ac6-a10a-d8656252e4c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d6a6628e6b4c280b3aaa12d83fd0cafc35cee17/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d85f217d-386f-4576-855e-59695646d713) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d6a6628e6b4c280b3aaa12d83fd0cafc35cee17/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1940ce44-2855-471a-8ba9-966e9ab89ffa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d6a6628e6b4c280b3aaa12d83fd0cafc35cee17/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6264557-a76b-47bf-a09b-66ee6736d73a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d6a6628e6b4c280b3aaa12d83fd0cafc35cee17/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a92b5d39-2898-47d0-b672-a7b7c84b96d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/universal-actions-for-search-based-message-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d6a6628e6b4c280b3aaa12d83fd0cafc35cee17/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Funiversal-actions-for-search-based-message-extensions.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d7c62ac-9f68-4e88-850b-a3471d5ff5d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d6a6628e6b4c280b3aaa12d83fd0cafc35cee17/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19dd0b2b-9854-4a8d-b3ab-814146f53790) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57823a7c9d0af792dd8c3a514e279750641d2e62/msteams-platform%2Fbots%2Fbot-basics.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/309491fa-90b4-48e1-a218-640319b25c7b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57823a7c9d0af792dd8c3a514e279750641d2e62/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74015634-2f78-46bf-8b6c-ab91067cc766) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57823a7c9d0af792dd8c3a514e279750641d2e62/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e51c90f-7ad5-4965-bfbe-2469c50dc2d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57823a7c9d0af792dd8c3a514e279750641d2e62/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/afdda55d-b0f3-48d1-91a8-f6cd4c3354db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57823a7c9d0af792dd8c3a514e279750641d2e62/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9437a847-3fb4-40f1-96f3-75b1e7ec9ad5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57823a7c9d0af792dd8c3a514e279750641d2e62/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d423e25-d8c3-4543-9a03-459ce0eb10a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/57823a7c9d0af792dd8c3a514e279750641d2e62/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09d618c0-88c1-4537-a2d4-32c9e7559d01) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/891a443165b46753f5b6fa15155352f2c2b56b3f/msteams-platform%2Fbots%2Fbot-basics.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f449aa5a-2887-4dd1-a636-70193a7699b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/891a443165b46753f5b6fa15155352f2c2b56b3f/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a32d545f-80c2-464c-bd56-dd35b00ac3f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/891a443165b46753f5b6fa15155352f2c2b56b3f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ca6ba2b-2618-4c58-9940-4bf22f9bfc0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/send-proactive-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/891a443165b46753f5b6fa15155352f2c2b56b3f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsend-proactive-messages.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4961f734-383a-4b3d-a5da-7920655eb195) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/891a443165b46753f5b6fa15155352f2c2b56b3f/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/455e6ec6-e3c5-4831-a2c9-cbb551caa880) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/891a443165b46753f5b6fa15155352f2c2b56b3f/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7444a86-7563-4e18-a17d-c0d1163c38ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/891a443165b46753f5b6fa15155352f2c2b56b3f/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b9418ee-33d0-4632-bdf5-f2d5aa517f02) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
