### PR TITLE
[Doc Improvement][SEO6 Metatitle Update][3876680]

### PR DESCRIPTION
**Pull request by v-ramyas5**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47d662ab07d88eb53e41fb00e2853f993450ce7e/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb357c79-64ab-4ab6-ab12-53f426336c5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47d662ab07d88eb53e41fb00e2853f993450ce7e/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 85 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8fea936c-77b1-4aea-98af-262df3bf370e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47d662ab07d88eb53e41fb00e2853f993450ce7e/msteams-platform%2Ffeedback.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99af7344-3266-4494-87bb-3391b15e9a36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47d662ab07d88eb53e41fb00e2853f993450ce7e/msteams-platform%2Fget-started%2Fb2c-apps.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b96424b3-4406-40c0-9646-9442a1da4c1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47d662ab07d88eb53e41fb00e2853f993450ce7e/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/459dad5d-54b6-43a7-b4a8-5e2965506f5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47d662ab07d88eb53e41fb00e2853f993450ce7e/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b521078f-0f22-427e-afb8-3b899bfbc36c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47d662ab07d88eb53e41fb00e2853f993450ce7e/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 89 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5e85bf3-32e9-4813-a8b1-90a26a6f0d20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47d662ab07d88eb53e41fb00e2853f993450ce7e/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5482d48-d231-4281-9b5c-d2490b5509c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47d662ab07d88eb53e41fb00e2853f993450ce7e/msteams-platform%2Fgraph-api%2Fproactive-bots-and-messages%2Fgraph-proactive-bots-and-messages.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3d690fc-c596-4c93-8c8b-fd7c51e111c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47d662ab07d88eb53e41fb00e2853f993450ce7e/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eaeea3df-4fa8-4158-8b84-606a443f8b18) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/382e09cf6afe8a8e9766523bac9b55a282435b44/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c8089e5-f9af-4f66-b04d-b838795136f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/382e09cf6afe8a8e9766523bac9b55a282435b44/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 85 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c62d3281-f52a-4e19-9d51-22f0852fec1a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/382e09cf6afe8a8e9766523bac9b55a282435b44/msteams-platform%2Ffeedback.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a25f013-82f9-4f1b-906d-0d66275eab64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/382e09cf6afe8a8e9766523bac9b55a282435b44/msteams-platform%2Fget-started%2Fb2c-apps.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7761643-67ae-4211-88e8-249c6b4283ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/382e09cf6afe8a8e9766523bac9b55a282435b44/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e378795c-8978-4aa8-bf3f-5ca179425236) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/382e09cf6afe8a8e9766523bac9b55a282435b44/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/217b6ed0-8879-47e1-aae7-f75506b18475) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/382e09cf6afe8a8e9766523bac9b55a282435b44/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 89 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e944060a-c5c4-4873-aa80-fb676b6a84e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/382e09cf6afe8a8e9766523bac9b55a282435b44/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a9ab4c1-fbf4-42c5-b267-e14d25315cac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/382e09cf6afe8a8e9766523bac9b55a282435b44/msteams-platform%2Fgraph-api%2Fproactive-bots-and-messages%2Fgraph-proactive-bots-and-messages.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a504569-b3f9-4527-b838-b3884dc94aaa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/382e09cf6afe8a8e9766523bac9b55a282435b44/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ad89176-250f-40ce-b204-e80209e09aff) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8b6ff272fb5c61c91a5af957a441e0f65e4b5b1/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a76f3742-0273-4a14-9282-711a7c4c0815) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8b6ff272fb5c61c91a5af957a441e0f65e4b5b1/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 85 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f80f0dc-03e8-4368-91f6-736ff96549fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8b6ff272fb5c61c91a5af957a441e0f65e4b5b1/msteams-platform%2Ffeedback.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/584a3c75-96fc-47f3-83b8-8c945f71ddec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8b6ff272fb5c61c91a5af957a441e0f65e4b5b1/msteams-platform%2Fget-started%2Fb2c-apps.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f35d79c-6837-488d-83e0-3159983e5282) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8b6ff272fb5c61c91a5af957a441e0f65e4b5b1/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92483ca2-f2a0-4f5b-ad47-118688cecf7f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8b6ff272fb5c61c91a5af957a441e0f65e4b5b1/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c61b92b7-afb4-43f2-9096-d444e17f622a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8b6ff272fb5c61c91a5af957a441e0f65e4b5b1/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 89 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3ce6f38-b29f-4c45-8474-4ee72c88958d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8b6ff272fb5c61c91a5af957a441e0f65e4b5b1/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a8abcfb-671a-44a1-a711-a2f8845fe7b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8b6ff272fb5c61c91a5af957a441e0f65e4b5b1/msteams-platform%2Fgraph-api%2Fproactive-bots-and-messages%2Fgraph-proactive-bots-and-messages.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/989b0003-386f-4639-9fed-756ff3e9e407) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8b6ff272fb5c61c91a5af957a441e0f65e4b5b1/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c43b085-3870-41e1-9713-e5231737aa24) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1d4d7487a8e9ee8e622b62040b2f7f8c706ba9/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbb8fa31-0991-4ffd-8c40-255a5f303ff4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1d4d7487a8e9ee8e622b62040b2f7f8c706ba9/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 85 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9a4d4b9-4784-4b34-b024-8d8c6a764250) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1d4d7487a8e9ee8e622b62040b2f7f8c706ba9/msteams-platform%2Ffeedback.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4da60f14-74ef-424d-8ed8-a755e144da01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/b2c-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1d4d7487a8e9ee8e622b62040b2f7f8c706ba9/msteams-platform%2Fget-started%2Fb2c-apps.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d22b28d2-df72-43cf-a2c6-388716ad8fc0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1d4d7487a8e9ee8e622b62040b2f7f8c706ba9/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29e5b275-5854-4bae-8c09-638cb0d39528) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1d4d7487a8e9ee8e622b62040b2f7f8c706ba9/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9610c806-2e8b-423a-8e16-003b26cc21d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1d4d7487a8e9ee8e622b62040b2f7f8c706ba9/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 89 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54639468-0183-415e-a4be-5866531aface) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1d4d7487a8e9ee8e622b62040b2f7f8c706ba9/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2f368a0-c6ed-4527-a6d1-0427621d3c4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1d4d7487a8e9ee8e622b62040b2f7f8c706ba9/msteams-platform%2Fgraph-api%2Fproactive-bots-and-messages%2Fgraph-proactive-bots-and-messages.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f60bdc59-b53e-4848-bce9-507ad3cc692e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1d4d7487a8e9ee8e622b62040b2f7f8c706ba9/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68700d17-b5fb-48b2-a3e8-474942f83657) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
