### PR TITLE
[Doc Improvement][Remove time and future ref: 8][3886829]

### PR DESCRIPTION
**Pull request by v-bvishnu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3639a54c8f6ae87ce9160bde08f8c0d574a46e65/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ccb0956-bcad-4967-b232-95a3869be158) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/strategize-measure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3639a54c8f6ae87ce9160bde08f8c0d574a46e65/msteams-platform%2Fconcepts%2Fdesign%2Fstrategize-measure.md) | 88 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e51dd201-0552-4d6e-867b-b3fe2344fa49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3639a54c8f6ae87ce9160bde08f8c0d574a46e65/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cea71c86-500a-4c32-bd67-9af7d66b752a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3639a54c8f6ae87ce9160bde08f8c0d574a46e65/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a99dd63-4514-4487-ab57-fdbc8c517f05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3639a54c8f6ae87ce9160bde08f8c0d574a46e65/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a97a4a4b-f167-4e87-b914-9bcf00a99589) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3639a54c8f6ae87ce9160bde08f8c0d574a46e65/msteams-platform%2Fresources%2FmoodleInstructions.md) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e92634aa-6375-4652-b82e-953e4cc08443) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-updates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3639a54c8f6ae87ce9160bde08f8c0d574a46e65/msteams-platform%2Fresources%2Fteams-updates.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54a99ddb-3e80-44f7-9f15-d0d4cd442760) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3639a54c8f6ae87ce9160bde08f8c0d574a46e65/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-graph-api.md) | 87 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5444cb4e-a3f6-4c64-809a-23dff9621ecf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3639a54c8f6ae87ce9160bde08f8c0d574a46e65/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-library.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d57c63d8-af2d-4830-8c31-e4faad16cdc2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3639a54c8f6ae87ce9160bde08f8c0d574a46e65/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24ab1d81-e7ec-4e79-aabb-aa6d9a8e9936) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3639a54c8f6ae87ce9160bde08f8c0d574a46e65/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5668ceb3-7005-4aea-bf48-98550cc9988b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b1cba9610ca55abaf14ecabfbaf03d46fde6b15/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/532e467b-7c35-4e68-941e-d52269f393ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/strategize-measure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b1cba9610ca55abaf14ecabfbaf03d46fde6b15/msteams-platform%2Fconcepts%2Fdesign%2Fstrategize-measure.md) | 87 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc92bed3-2e77-45a6-8987-e9e6a64c5a22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b1cba9610ca55abaf14ecabfbaf03d46fde6b15/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88cf3450-da38-4f4e-adb9-5c1dea93f147) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b1cba9610ca55abaf14ecabfbaf03d46fde6b15/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/382c5b61-5460-4ef3-b3b1-fd6466c7b964) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b1cba9610ca55abaf14ecabfbaf03d46fde6b15/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa5025f7-1e32-4998-94b1-c3de4222c059) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b1cba9610ca55abaf14ecabfbaf03d46fde6b15/msteams-platform%2Fresources%2FmoodleInstructions.md) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c095dfb-43fe-4f08-8f7a-8bccdb33f131) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-updates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b1cba9610ca55abaf14ecabfbaf03d46fde6b15/msteams-platform%2Fresources%2Fteams-updates.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6de34fcc-b997-4092-b0f8-9057a1edc9be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b1cba9610ca55abaf14ecabfbaf03d46fde6b15/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-graph-api.md) | 87 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58564413-42a3-417c-bbf0-e4ecc148a649) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b1cba9610ca55abaf14ecabfbaf03d46fde6b15/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-library.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26110e88-bd20-4e3a-896c-c10e772be1e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b1cba9610ca55abaf14ecabfbaf03d46fde6b15/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97b6d7d5-947e-4d98-b016-67ad1109a660) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b1cba9610ca55abaf14ecabfbaf03d46fde6b15/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16478d87-7f96-4fb3-9832-cf5816290f96) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ca72ec8cc240ebd2c732304079ed6feb7c21b8/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2d3e9a5-2f01-435b-a736-5f92629b073e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/strategize-measure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ca72ec8cc240ebd2c732304079ed6feb7c21b8/msteams-platform%2Fconcepts%2Fdesign%2Fstrategize-measure.md) | 87 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c91b990b-0522-41d2-8838-527052e50dfa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ca72ec8cc240ebd2c732304079ed6feb7c21b8/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d90bce33-9a01-41c2-9be7-6c8a0f8fee13) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ca72ec8cc240ebd2c732304079ed6feb7c21b8/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55e98166-93a4-4d55-bcee-158b7c5930e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ca72ec8cc240ebd2c732304079ed6feb7c21b8/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c3052f6-bdfe-443d-9f49-8579f9bb85fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ca72ec8cc240ebd2c732304079ed6feb7c21b8/msteams-platform%2Fresources%2FmoodleInstructions.md) | 88 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df32be59-cf14-4f2e-a078-25821e0727bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-updates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ca72ec8cc240ebd2c732304079ed6feb7c21b8/msteams-platform%2Fresources%2Fteams-updates.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf11848e-b77b-404d-9767-e6c660ec6468) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ca72ec8cc240ebd2c732304079ed6feb7c21b8/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-graph-api.md) | 87 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4192e8d-cc00-444c-a93e-b4c86fad3673) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ca72ec8cc240ebd2c732304079ed6feb7c21b8/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-library.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/338b48f5-418a-4fed-b510-25207f0f4a73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ca72ec8cc240ebd2c732304079ed6feb7c21b8/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45beb2f2-734b-487f-a6d2-ce77e5a24bd4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ca72ec8cc240ebd2c732304079ed6feb7c21b8/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d95df85-d365-48cb-9a7d-7cdb50bbb5dc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e0831d2bfcca6d3d51f3d6ed349f579bf5be27e/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c46c5b68-5d11-4c73-a738-d77338cbdfcc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/strategize-measure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e0831d2bfcca6d3d51f3d6ed349f579bf5be27e/msteams-platform%2Fconcepts%2Fdesign%2Fstrategize-measure.md) | 87 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76cf76b2-739e-4b87-9201-dc746e404a4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e0831d2bfcca6d3d51f3d6ed349f579bf5be27e/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c527e03-7f44-41f7-8065-6e35b3a49935) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e0831d2bfcca6d3d51f3d6ed349f579bf5be27e/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65f6f062-27a3-49f7-bcba-93ff31c39396) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e0831d2bfcca6d3d51f3d6ed349f579bf5be27e/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 89 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3bcc4a5-790f-4440-93ca-6268b8746d3e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e0831d2bfcca6d3d51f3d6ed349f579bf5be27e/msteams-platform%2Fresources%2FmoodleInstructions.md) | 88 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f3e1cf2-1426-47e0-8222-64968d9b0c45) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-updates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e0831d2bfcca6d3d51f3d6ed349f579bf5be27e/msteams-platform%2Fresources%2Fteams-updates.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db5d61c0-214f-4d4a-b729-558cb01629ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e0831d2bfcca6d3d51f3d6ed349f579bf5be27e/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-graph-api.md) | 87 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbef4a9f-5b03-4dd6-989d-0071aecba015) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e0831d2bfcca6d3d51f3d6ed349f579bf5be27e/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-library.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d939940-2fcc-4728-a1ee-894b98b51cc6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e0831d2bfcca6d3d51f3d6ed349f579bf5be27e/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6adb391-7883-4f36-9a45-e9e0255578cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e0831d2bfcca6d3d51f3d6ed349f579bf5be27e/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cc4a218-dc21-4569-a362-62b8a43c29e7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
