### PR TITLE
[Doc Enhancement][Branding terms2][2224899]

### PR DESCRIPTION
**Pull request by v-dreddipogu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4f082302b135806c7e5d62369b9128fc18fff21/msteams-platform/graph-api/rsc/resource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63d69b6c-d7ce-4fc7-a347-1d34cb788caa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0fd1a193ffa78b180017400f6d5c0b5e025a639/msteams-platform/graph-api/rsc/resource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56b4ed7f-e8b0-442b-b955-4abbcfa54394) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0fd1a193ffa78b180017400f6d5c0b5e025a639/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3affbb42-03f1-486d-aa6c-5ba6644b8239) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/create-messaging-extension-using-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0fd1a193ffa78b180017400f6d5c0b5e025a639/msteams-platform/resources/create-messaging-extension-using-appstudio.md) | 81 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9dd8a8f6-ffd2-430c-9940-5d0a74c01ee2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e0fd1a193ffa78b180017400f6d5c0b5e025a639/msteams-platform/sbs-calling-and-meeting.yml) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c6c0491-b0ec-4697-a84c-6813d947e51a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1ed626c76acab76d7ec3541644bd536969666c44/msteams-platform/graph-api/rsc/resource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e55b533-f87e-47f6-bccd-a8824308ed70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/browser-private-launch.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1ed626c76acab76d7ec3541644bd536969666c44/msteams-platform/includes/get-started/browser-private-launch.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0564fb3d-7a98-48bc-9098-7030e3722c0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1ed626c76acab76d7ec3541644bd536969666c44/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab80209f-7100-4b88-b5ae-0af640e0ec1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/create-messaging-extension-using-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1ed626c76acab76d7ec3541644bd536969666c44/msteams-platform/resources/create-messaging-extension-using-appstudio.md) | 81 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fa6a4b2-0cad-4eca-a68a-c89cd8a394dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1ed626c76acab76d7ec3541644bd536969666c44/msteams-platform/sbs-calling-and-meeting.yml) | 89 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c471ee62-33b8-4b6e-b041-d21528f4b437) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-nodejs.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1ed626c76acab76d7ec3541644bd536969666c44/msteams-platform/sbs-gs-nodejs.yml) | 92 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81b7b5c5-eb85-43e4-8d72-124fff710c03) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f1a84c41b868b9ff14fdf5aad3061306709c59fa/msteams-platform/graph-api/rsc/resource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff110019-9a0c-4f0c-910e-2e314eab7de4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/browser-private-launch.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f1a84c41b868b9ff14fdf5aad3061306709c59fa/msteams-platform/includes/get-started/browser-private-launch.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7daf49fb-ca61-46c0-9dee-76aa104aaccb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f1a84c41b868b9ff14fdf5aad3061306709c59fa/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f1c97fe-1d2c-409d-87cf-0c1e033404e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/create-messaging-extension-using-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f1a84c41b868b9ff14fdf5aad3061306709c59fa/msteams-platform/resources/create-messaging-extension-using-appstudio.md) | 81 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a687949-68f3-40e0-a15f-ba99750c90e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f1a84c41b868b9ff14fdf5aad3061306709c59fa/msteams-platform/sbs-calling-and-meeting.yml) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e092d0e-3a07-439c-b0d3-e2a4ea4ab62f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-nodejs.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f1a84c41b868b9ff14fdf5aad3061306709c59fa/msteams-platform/sbs-gs-nodejs.yml) | 92 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d9742b9-158b-45cd-8536-021edff4877a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b185b9532d05033f60c0b3869b810a07186e89fe/msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md) | 84 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a96d2062-2a34-42ee-b0c4-9380096de547) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b185b9532d05033f60c0b3869b810a07186e89fe/msteams-platform/graph-api/rsc/resource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba6476a4-cf80-44f6-86c1-e4b1cd4c0741) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/browser-private-launch.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b185b9532d05033f60c0b3869b810a07186e89fe/msteams-platform/includes/get-started/browser-private-launch.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4f5950a-744d-469b-aa20-caf87f1b7864) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b185b9532d05033f60c0b3869b810a07186e89fe/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d87c8e70-0759-4da8-af72-3cb16b9849b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/create-messaging-extension-using-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b185b9532d05033f60c0b3869b810a07186e89fe/msteams-platform/resources/create-messaging-extension-using-appstudio.md) | 81 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e57315d-81ce-4c0c-b127-ca0f7ffb79ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b185b9532d05033f60c0b3869b810a07186e89fe/msteams-platform/sbs-calling-and-meeting.yml) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62881f2d-4ba5-4a85-b57c-25956be59430) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-nodejs.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b185b9532d05033f60c0b3869b810a07186e89fe/msteams-platform/sbs-gs-nodejs.yml) | 92 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a668d17f-7d90-410e-82cc-611dae433c2f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0172277c341aa37d7aa7c79fa594e941c14f206/msteams-platform/concepts/build-and-test/share-to-teams.md) | 85 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d3a728a-fc94-4b52-8ae7-b27700c19026) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0172277c341aa37d7aa7c79fa594e941c14f206/msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md) | 92 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f34a36d-0821-43f7-a1a6-e7a7243e791f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0172277c341aa37d7aa7c79fa594e941c14f206/msteams-platform/graph-api/rsc/resource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f437e1e7-5a43-4cee-af00-587465af002d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/browser-private-launch.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0172277c341aa37d7aa7c79fa594e941c14f206/msteams-platform/includes/get-started/browser-private-launch.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7361b860-d46d-4396-a24d-be65b132dc8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0172277c341aa37d7aa7c79fa594e941c14f206/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f2a088a-dadc-4d82-ac4d-71375f23b530) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/create-messaging-extension-using-appstudio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0172277c341aa37d7aa7c79fa594e941c14f206/msteams-platform/resources/create-messaging-extension-using-appstudio.md) | 81 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b38a586a-bb0c-4b3a-a26c-255b35ac18ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0172277c341aa37d7aa7c79fa594e941c14f206/msteams-platform/resources/samesite-cookie-update.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7cbd164-b0bc-4cd1-94bc-192752ead825) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b0172277c341aa37d7aa7c79fa594e941c14f206/msteams-platform/sbs-calling-and-meeting.yml) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6059f21c-c68c-46f0-8fbb-c5d95a1ab4c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b0172277c341aa37d7aa7c79fa594e941c14f206/msteams-platform/sbs-gs-javascript.yml) | 93 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/054b7ba2-3091-4b35-aacc-90371a0c90fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-nodejs.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b0172277c341aa37d7aa7c79fa594e941c14f206/msteams-platform/sbs-gs-nodejs.yml) | 92 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23364922-dd1c-446b-bd4a-fa1ccaaac76b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b0172277c341aa37d7aa7c79fa594e941c14f206/msteams-platform/sbs-gs-spfx.yml) | 95 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61dc06b7-856b-4850-9129-ffe76acbc774) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by ashishguptaiitb — APPROVED** [review]

**Pull request merged**
