### PR TITLE
Define copilotExtensions element

### PR DESCRIPTION
**Pull request by erikadoyle**
Updates to preview manifest for declarative copilots and API Plugins

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/249a409a3e7986cacb87c9d9fb606727677cea68/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 132 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03a08e48-db68-4849-8c5f-7ce3e1ee344a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/daf71e3a89776c3981ed53f61b2116ce59321f13/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 132 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64923941-33bd-4639-8013-b8b974dbf246) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/34061618ef450c6fe6607cda9be7dab5848914ab/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 137 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4eeb59fd-fee0-4a47-a257-48048d0f45d5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d72e53f853a8f9f58cdfa4b661a90296ddf8d7/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 137 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7fd0a73d-1ef2-49c6-a0b2-e95370df75fc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4dfbad4bc4009130a781d70ac5f18ed207fe48af/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 136 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1877006-de2e-49d7-ac79-77dc89be708c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4dfbad4bc4009130a781d70ac5f18ed207fe48af/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 85 | 120 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d04ef3ae-5722-41d6-b91d-e312dde8433f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/33cd0ea42f22a9fc56a3f5ec647311e7b978de99/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 136 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aad9e2f1-c59e-4343-9891-f743a0c0251b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/33cd0ea42f22a9fc56a3f5ec647311e7b978de99/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 85 | 122 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2212f340-fb35-4381-a483-ebddae2e8c80) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66e33dfd4178ed8b524133806526a073eadd79df/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 136 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ecd7d5a2-e3ef-4023-9824-c312d0a14162) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66e33dfd4178ed8b524133806526a073eadd79df/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 85 | 122 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/870ed85c-2855-4775-885a-b4e3a0496110) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c9f7ba8350a7b3f69b202a392a85fb9431a663c/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 82 | 143 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a49026b6-4dac-4b39-9344-e6c66ab56a9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c9f7ba8350a7b3f69b202a392a85fb9431a663c/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 84 | 127 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e29dfd5-9a19-471a-bc37-4c8da26d5142) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by erikadoyle** [comment]
Closing; starting a fresh PR with latest

**Pull request closed without merging**
