### PR TITLE
Ac devpreview manifest

### PR DESCRIPTION
**Pull request by clearab**

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[1c9b9fd](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/1c9b9fd2663b12657fe38789dff4269ef1561fbc)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[1c9b9fd](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/1c9b9fd2663b12657fe38789dff4269ef1561fbc)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[1c9b9fd](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/1c9b9fd2663b12657fe38789dff4269ef1561fbc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/troubleshoot/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/troubleshoot/troubleshoot.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Ftroubleshoot%2Ftroubleshoot.md)
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview-intro.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | |

<a name="msteams-platform%2Ftroubleshoot%2Ftroubleshoot.md"></a>
### [msteams-platform/troubleshoot/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/troubleshoot/troubleshoot.md)
 - **Line 72**: **[Warning]** Illegal link: `[Mentions](~/concepts/bots/bot-conversations/bots-conv-channel.md#mentions)` -- missing bookmark. The file concepts/bots/bot-conversations/bots-conv-channel.md doesn&#39;t contain a bookmark named mentions.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C7%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903070220077709-491%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0R6JowySpIvzSnNiugkwEPB81C18ow0jUyrhZfI7FO8%3D&st=2019-03-07T02%3A16%3A18Z&se=2019-04-07T02%3A21%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[4490804](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/4490804e175ae695db713552df672dcbe331875e)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[4490804](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/4490804e175ae695db713552df672dcbe331875e)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[4490804](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/4490804e175ae695db713552df672dcbe331875e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview-intro.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/troubleshoot/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/troubleshoot/troubleshoot.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C7%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903070236418367-491%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TQdfjAeIMhnyIBOzxAfmd4%2BJLFG1ChhcPr0tTOqBQu4%3D&st=2019-03-07T02%3A32%3A52Z&se=2019-04-07T02%3A37%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clearab** [comment]
Intentionally didn't document TaskInfo or the Platform fields (per discussion with feature owners)

**Comment by o365devx** [comment]
OPS Build status updates of commit _[3b3bc03](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/3b3bc0364309b0d3bbe6ffd46e2e2519491ed85a)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[3b3bc03](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/3b3bc0364309b0d3bbe6ffd46e2e2519491ed85a)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[3b3bc03](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/3b3bc0364309b0d3bbe6ffd46e2e2519491ed85a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview-intro.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/troubleshoot/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/troubleshoot/troubleshoot.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C7%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903071834595601-491%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rKpdHWSdHggBB7hRIRkLbB02E%2BLIIKGmxCGx81HHOLk%3D&st=2019-03-07T18%3A31%3A10Z&se=2019-04-07T18%3A36%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[2129436](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/21294361ca46957217e8a1e21c29918c88cf942b)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[2129436](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/21294361ca46957217e8a1e21c29918c88cf942b)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[2129436](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/21294361ca46957217e8a1e21c29918c88cf942b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview-intro.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/troubleshoot/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/troubleshoot/troubleshoot.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C7%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903071842452587-491%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=znqE72Y9tCe3%2BAm%2Ban566OB4Ep8hYadmAQTsf0qPmdY%3D&st=2019-03-07T18%3A38%3A55Z&se=2019-04-07T18%3A43%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[1c479e6](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/1c479e615d20881b044344144920f14997327a64)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[1c479e6](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/1c479e615d20881b044344144920f14997327a64)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[1c479e6](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/1c479e615d20881b044344144920f14997327a64)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview-intro.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/troubleshoot/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/troubleshoot/troubleshoot.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C7%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903071901077975-491%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=NFypRlUY5bE7D1VWCihQU%2BswaVx26HWCEmNVLWYjSMQ%3D&st=2019-03-07T18%3A57%3A21Z&se=2019-04-07T19%3A02%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[5edb990](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/5edb9902b2bbe82f2dc5c8b3b5aa1b0443cb5bec)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[5edb990](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/5edb9902b2bbe82f2dc5c8b3b5aa1b0443cb5bec)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[5edb990](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/5edb9902b2bbe82f2dc5c8b3b5aa1b0443cb5bec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview-intro.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/troubleshoot/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/troubleshoot/troubleshoot.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C7%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903071908034354-491%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kE9iSVgBcqyUV%2BFC41PbK0O8WmN2kah26BebkbnF7SA%3D&st=2019-03-07T19%3A04%3A20Z&se=2019-04-07T19%3A09%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[0913db9](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/0913db99b7e068c582d753e81d0de5130607be29)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[0913db9](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/0913db99b7e068c582d753e81d0de5130607be29)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[0913db9](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/0913db99b7e068c582d753e81d0de5130607be29)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview-intro.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/troubleshoot/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/troubleshoot/troubleshoot.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C7%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903071909395832-491%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xQ97pPNEwPyaRwMig%2FxgZfLihHAWjk2jWBxpWrMnNkg%3D&st=2019-03-07T19%3A05%3A59Z&se=2019-04-07T19%3A10%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[5523a0f](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/5523a0f8df4a0585ab0d25566b25f07970893160)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[5523a0f](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/5523a0f8df4a0585ab0d25566b25f07970893160)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[5523a0f](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/5523a0f8df4a0585ab0d25566b25f07970893160)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview-intro.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/troubleshoot/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/troubleshoot/troubleshoot.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C7%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903071920479850-491%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=w4N7ttORmL09RDvWvQlxfVOgqMFCT1bOR%2F7TFs5Wc14%3D&st=2019-03-07T19%3A17%3A02Z&se=2019-04-07T19%3A22%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[6dd8fdf](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/6dd8fdfcea85a88e8a26b99b5ba5b28f18c44987)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[6dd8fdf](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/6dd8fdfcea85a88e8a26b99b5ba5b28f18c44987)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[6dd8fdf](https://github.com/MicrosoftDocs/msteams-docs/pull/491/commits/6dd8fdfcea85a88e8a26b99b5ba5b28f18c44987)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview-intro.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/dev-preview/developer-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/resources/schema/manifest-schema-dev-preview.md) | :white_check_mark:Succeeded | |
[msteams-platform/troubleshoot/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-devpreview-manifest/msteams-platform/troubleshoot/troubleshoot.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C7%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903071928337366-491%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LE36%2FNPcIcfSJZ2RoFVlerbj4Nd5wYeofTV7WAOE%2BCU%3D&st=2019-03-07T19%3A24%3A47Z&se=2019-04-07T19%3A29%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
