### PR TITLE
[Doc Improvement][Remove time and future ref: 4][3886822]

### PR DESCRIPTION
**Pull request by v-deabira**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39055b06d78481df56fbc59acda524108cbdd18d/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02a54810-cc05-4f74-aa95-16a30f888323) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39055b06d78481df56fbc59acda524108cbdd18d/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 85 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c0c1746-34df-475a-ab59-750323983e7c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39055b06d78481df56fbc59acda524108cbdd18d/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a82e0925-13dc-451a-b2fd-f1834b6962b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39055b06d78481df56fbc59acda524108cbdd18d/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c46e5a3f-aa0d-4b3f-a720-33298d8b8d23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39055b06d78481df56fbc59acda524108cbdd18d/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f547135-fdf8-4fc2-b2af-5f69efba6cf1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39055b06d78481df56fbc59acda524108cbdd18d/msteams-platform%2Fgraph-api%2Fproactive-bots-and-messages%2Fgraph-proactive-bots-and-messages.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c734b27c-63d0-4d1b-a62f-08576b992e20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39055b06d78481df56fbc59acda524108cbdd18d/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f0ebe1f-70ae-4707-ba4d-9d2b423d4f4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/messaging-extensions-common.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39055b06d78481df56fbc59acda524108cbdd18d/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmessaging-extensions-common.md) | 88 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/efea1d46-0f5d-4ffc-b493-43f688ae825f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/dotnet-core-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39055b06d78481df56fbc59acda524108cbdd18d/msteams-platform%2Fincludes%2Ftabs%2Fdotnet-core-prereq.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c35fc5d8-aa0b-4813-bad7-09778892038e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39055b06d78481df56fbc59acda524108cbdd18d/msteams-platform%2Fincludes%2Ftabs%2Fnode-js-yeoman-prereq.md) | 85 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/138f8c91-7236-4f5d-ae50-d7dd37a9d628) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39055b06d78481df56fbc59acda524108cbdd18d/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/753fce79-0530-4baa-ac1e-251518d0ee93) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39055b06d78481df56fbc59acda524108cbdd18d/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-message-extension.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e34287c3-70c8-40ea-86f6-01dbc4dee9cb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e6144055a88673e872b3f172a399e5d01f46d34/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83c4bf57-6969-43e6-a594-ef5da2d51c7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e6144055a88673e872b3f172a399e5d01f46d34/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 85 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87e46303-cc39-40d6-82ed-78831cc76235) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e6144055a88673e872b3f172a399e5d01f46d34/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd19a202-8349-4db3-8592-3f7bb6617762) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e6144055a88673e872b3f172a399e5d01f46d34/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9e38f47-f55d-4937-b427-aeb464517334) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e6144055a88673e872b3f172a399e5d01f46d34/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3e8bc3f-3cea-45d6-b9d3-96cd989dc785) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e6144055a88673e872b3f172a399e5d01f46d34/msteams-platform%2Fgraph-api%2Fproactive-bots-and-messages%2Fgraph-proactive-bots-and-messages.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e78e441-5b14-4996-95d2-c5829147396b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e6144055a88673e872b3f172a399e5d01f46d34/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a3d48b2-1fa1-4480-b467-47afca196409) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/messaging-extensions-common.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e6144055a88673e872b3f172a399e5d01f46d34/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmessaging-extensions-common.md) | 88 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33c955a6-2d69-45f5-97d3-c7fbf9b04d7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/dotnet-core-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e6144055a88673e872b3f172a399e5d01f46d34/msteams-platform%2Fincludes%2Ftabs%2Fdotnet-core-prereq.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5a94707-bf5a-4ee0-a461-cb9282e2a06f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e6144055a88673e872b3f172a399e5d01f46d34/msteams-platform%2Fincludes%2Ftabs%2Fnode-js-yeoman-prereq.md) | 85 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/969ef3d7-8370-47bd-964b-0e098aae5a80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e6144055a88673e872b3f172a399e5d01f46d34/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/338c7a04-4877-48ea-8b4e-ea0792fa10af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e6144055a88673e872b3f172a399e5d01f46d34/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-message-extension.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11ea0e60-bc14-4f54-9829-c95c82892b3b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff5e946af49fea889b4350f90185e002fd6739ee/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9491a57-1a9d-4ba9-9dbd-40e6a7827aa1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff5e946af49fea889b4350f90185e002fd6739ee/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 85 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2a17c9b-8964-4a81-8ced-679254343a44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff5e946af49fea889b4350f90185e002fd6739ee/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 89 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df2a9a92-70e5-48b8-a008-0f24fed1acea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff5e946af49fea889b4350f90185e002fd6739ee/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/342e9b2c-f6d3-4848-8546-5c3b7028f035) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff5e946af49fea889b4350f90185e002fd6739ee/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22405e2c-9143-4405-83a3-c4b920fe72ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff5e946af49fea889b4350f90185e002fd6739ee/msteams-platform%2Fgraph-api%2Fproactive-bots-and-messages%2Fgraph-proactive-bots-and-messages.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74148636-541e-43c8-a4ce-9f2f8a113e50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff5e946af49fea889b4350f90185e002fd6739ee/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da9f229e-ec0e-40d4-bb1e-8a579aee62b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/messaging-extensions-common.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff5e946af49fea889b4350f90185e002fd6739ee/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmessaging-extensions-common.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20f538a4-9da9-4c79-a4c7-0738928054b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/dotnet-core-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff5e946af49fea889b4350f90185e002fd6739ee/msteams-platform%2Fincludes%2Ftabs%2Fdotnet-core-prereq.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a0c82ed-fdff-4dcf-8afc-72492af29c8b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff5e946af49fea889b4350f90185e002fd6739ee/msteams-platform%2Fincludes%2Ftabs%2Fnode-js-yeoman-prereq.md) | 85 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/201d65a6-700d-419b-a0dc-1905cf97451c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff5e946af49fea889b4350f90185e002fd6739ee/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de7890bf-412e-45e6-a258-75063d4759dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff5e946af49fea889b4350f90185e002fd6739ee/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-message-extension.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b800452-c84e-48f6-bdb1-4e7ac6a8408f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-ypalikila — APPROVED** [review]
Approved.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c154483801f1c423e8470de6f9603292f49c3f6f/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c46a413-92c1-4b59-80ac-613a8f9378c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c154483801f1c423e8470de6f9603292f49c3f6f/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 85 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c1a9164-58ea-480b-b34a-7d304551b241) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c154483801f1c423e8470de6f9603292f49c3f6f/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 89 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a6f5037-dfc9-43f9-bd0a-95037508083a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c154483801f1c423e8470de6f9603292f49c3f6f/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52dac5c1-7047-4c4c-8b50-d0c9f489c5d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c154483801f1c423e8470de6f9603292f49c3f6f/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a61f9a7a-dd9b-4aa2-a72b-3d1b4d438d02) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c154483801f1c423e8470de6f9603292f49c3f6f/msteams-platform%2Fgraph-api%2Fproactive-bots-and-messages%2Fgraph-proactive-bots-and-messages.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fc7b398-715c-4685-a234-4c93015e72c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c154483801f1c423e8470de6f9603292f49c3f6f/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7dd4cd9f-f1fc-41c0-b164-34f9769d4c41) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/messaging-extensions-common.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c154483801f1c423e8470de6f9603292f49c3f6f/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmessaging-extensions-common.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/149b9f5f-fdfd-47c9-8407-aa08907d0133) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/dotnet-core-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c154483801f1c423e8470de6f9603292f49c3f6f/msteams-platform%2Fincludes%2Ftabs%2Fdotnet-core-prereq.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff456029-f66e-4e5e-959f-0ed6198e9f13) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c154483801f1c423e8470de6f9603292f49c3f6f/msteams-platform%2Fincludes%2Ftabs%2Fnode-js-yeoman-prereq.md) | 85 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fbce385-8702-4069-b8bb-255630a07403) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c154483801f1c423e8470de6f9603292f49c3f6f/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3e81b6e-c451-4222-ba80-5e42b1aa1a9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c154483801f1c423e8470de6f9603292f49c3f6f/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-message-extension.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ac3e9b3-41c9-4bff-a548-d43da5461fd3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7afef6c8c3339372ad2eca8383403fd876676712/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a42b1c94-e29e-450d-aa28-1da553d0ef36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7afef6c8c3339372ad2eca8383403fd876676712/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 85 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b43267ef-5c9e-4fb9-9909-6c172a505e7f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7afef6c8c3339372ad2eca8383403fd876676712/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 89 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea50e870-7277-41ff-8cf6-74753bbfdccf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7afef6c8c3339372ad2eca8383403fd876676712/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fc75e82-be18-4976-93a0-799fef866c3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7afef6c8c3339372ad2eca8383403fd876676712/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd9fdd2d-0468-4c61-a09b-776e5a8ba2be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7afef6c8c3339372ad2eca8383403fd876676712/msteams-platform%2Fgraph-api%2Fproactive-bots-and-messages%2Fgraph-proactive-bots-and-messages.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5921623-79f2-4831-a841-cb397d64f685) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7afef6c8c3339372ad2eca8383403fd876676712/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b16ffd8a-690a-4d4f-9373-00d1a60360ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/messaging-extensions-common.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7afef6c8c3339372ad2eca8383403fd876676712/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmessaging-extensions-common.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cdaa7b9-f5bf-466d-aa5d-ed08f8f91415) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/dotnet-core-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7afef6c8c3339372ad2eca8383403fd876676712/msteams-platform%2Fincludes%2Ftabs%2Fdotnet-core-prereq.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86267811-c275-42b0-8ee6-f9911b024e22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/node-js-yeoman-prereq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7afef6c8c3339372ad2eca8383403fd876676712/msteams-platform%2Fincludes%2Ftabs%2Fnode-js-yeoman-prereq.md) | 85 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ab9580a-99f0-43ff-be13-d0fc2549f583) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7afef6c8c3339372ad2eca8383403fd876676712/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08841e9d-21ca-4da0-b33a-18fa4d616081) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7afef6c8c3339372ad2eca8383403fd876676712/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-message-extension.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1154b5f3-a73d-4adc-8521-bb22e086964c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
