### PR TITLE
[Doc Improvement][Teams 2.1 update][3468460]

### PR DESCRIPTION
**Pull request by v-vanisreeth**
Replaced the image.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/publish-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c537bc95914b907e3b45839fc8680cbd4114d60b/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fpublish-v4.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20462e0d-47e9-4d07-bb70-05cd9cf13ca0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/publish-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53b9acb345b48d7bc8129da70caa43ec61a72a16/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fpublish-v4.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c755ab5-0537-4564-8555-3b1806f3faec) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/publish-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9aec7d1ff272d008b09d9121504df846f2bc6e2c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fpublish-v4.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2081b28-4876-45e8-9a56-95c571f4670c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-bot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9aec7d1ff272d008b09d9121504df846f2bc6e2c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-bot-v4.yml) | 87 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/526393f3-889e-4eb2-8900-04fb76cbb4ed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/publish-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ef4f4077ac2201488d905ab490c09ff41c9765ad/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fpublish-v4.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e07f26fe-fe99-47db-ac34-52930f880823) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-bot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ef4f4077ac2201488d905ab490c09ff41c9765ad/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-bot-v4.yml) | 87 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1c8f4c6-5b50-4df9-84ae-6537622b390f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/publish-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8e5e06c74e3a3628d99a8dde38f922f6651d9ec3/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fpublish-v4.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e1c9125-347c-4992-8613-76e867a31711) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-bot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8e5e06c74e3a3628d99a8dde38f922f6651d9ec3/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-bot-v4.yml) | 87 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f01b0cd-62aa-4716-9474-3a30c9a1b8c6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a782d6b9dd6c5f741b7c018e90ddd20f6bfd1e91/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7157273-e884-41ac-a3b8-f6e222adf623) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a782d6b9dd6c5f741b7c018e90ddd20f6bfd1e91/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b29e823-12bc-42e4-92fa-0d7ac729ce49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/publish-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a782d6b9dd6c5f741b7c018e90ddd20f6bfd1e91/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fpublish-v4.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2e468ca-1bfe-4a0a-96f4-14a5a817cc9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-bot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a782d6b9dd6c5f741b7c018e90ddd20f6bfd1e91/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-bot-v4.yml) | 87 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17e491fc-6296-4cd5-8338-ad27ac6ebf87) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/22dd5910b745a462be46cc01476dbd160e7315eb/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d384c720-1977-4d90-8712-03d878edf43d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/22dd5910b745a462be46cc01476dbd160e7315eb/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b918be3-3a38-4820-8e84-7d317c2efbdb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/publish-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/22dd5910b745a462be46cc01476dbd160e7315eb/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fpublish-v4.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09738ade-254b-4062-85c9-1cf3c1e71176) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-bot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/22dd5910b745a462be46cc01476dbd160e7315eb/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-bot-v4.yml) | 87 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72598136-9220-43e9-8115-78365db1cd94) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a54f08ba4ff2ba69421567006badebf8187b4935/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c777fce-74ed-4ad4-9ac2-51a258cc5941) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a54f08ba4ff2ba69421567006badebf8187b4935/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d73693b-2efb-4618-9b5d-b38289e2ae85) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/publish-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a54f08ba4ff2ba69421567006badebf8187b4935/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fpublish-v4.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ff5a555-42db-4f9a-9add-51a63240258e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-bot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a54f08ba4ff2ba69421567006badebf8187b4935/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-bot-v4.yml) | 87 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93d7f107-1726-4fc9-8421-5374c8b1e26a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97db3c312af18549eaf4c20d0a720a8404b2ae50/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea947b52-bc58-44a1-8e82-03dde0a3ead9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97db3c312af18549eaf4c20d0a720a8404b2ae50/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1010f1b-8893-4056-9902-fa8f0353c4f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/publish-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97db3c312af18549eaf4c20d0a720a8404b2ae50/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fpublish-v4.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f3ae298-a8f7-4237-ba35-031d0f5d021f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-bot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/97db3c312af18549eaf4c20d0a720a8404b2ae50/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-bot-v4.yml) | 87 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e94b46f-6e0c-45ea-9952-061d56834e35) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
