### PR TITLE
[Doc Improvement][Legacy bot page links fix]

### PR DESCRIPTION
**Pull request by v-shalinir**
Updated 'Create' to 'build' in title and description; added Important note to link users to AI library and Get started

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1311a03f095da49da4ba93f6d64c16c04c35a25d/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7dec61d-adc6-4d69-b522-81636fd64f80) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e25f0f10fa4726f325d051ff6de3158557ed8ba5/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eeb43d21-a110-4020-96d6-d4426d5b0e6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e25f0f10fa4726f325d051ff6de3158557ed8ba5/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd19530b-7667-4a4d-89bf-ea6772551449) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2789b3ec368e87f84c9174b144afb3897014fc24/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/522377d1-7726-4571-b6ba-cb7b60d933cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2789b3ec368e87f84c9174b144afb3897014fc24/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/936e7475-58bb-4000-bac0-bf21c73808d9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/406241deb6e03ecf877d38964f720b28b4b2b4d5/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a058091b-ea1d-44cf-889b-34d6d577a137) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/406241deb6e03ecf877d38964f720b28b4b2b4d5/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7503b04-0ea0-48dd-86bd-dd1ddf883bac) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e17c4eef986eaf9c47b63c94a76298e24b2f79bc/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e169727d-3adc-4c89-9827-540a0aa0a68e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e17c4eef986eaf9c47b63c94a76298e24b2f79bc/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/913afcb4-ae4d-4b2d-b66b-a82df0e1948c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/605b105ae37fb8e5a00ef0e2f17d5e05460484cb/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e7a33af-3517-4233-9731-fa92b1b149d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/605b105ae37fb8e5a00ef0e2f17d5e05460484cb/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12a86164-9394-4d86-b99b-aa6a45caeb5e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/485a1579f3aefa643646344768a456d3b991f134/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96c43184-1c76-470e-bf86-b9fa57eedb40) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/485a1579f3aefa643646344768a456d3b991f134/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c08fdc34-056b-4331-be6d-1d180fa9a36f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1dcbb97676a2e7f47bdd0174370e5d0e464307bc/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bd2c456-4bf2-4c2f-bf14-04926d26f849) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1dcbb97676a2e7f47bdd0174370e5d0e464307bc/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9e00b67-b55a-4c57-b424-b35dc17b7e40) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6e2b56bb23692c8bb957213d121b9c8d70fd24d6/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/154c33ad-bd79-4535-a0e3-8a1483b4f2cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e2b56bb23692c8bb957213d121b9c8d70fd24d6/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f6b6af5-29c6-404c-aa8d-11c7af0128fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6e2b56bb23692c8bb957213d121b9c8d70fd24d6/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e784a745-132f-4e9b-8958-ba5a0961489b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/176d785f23112e19f22fe7b4c9fd8d7fcfe332e1/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2247f04-e04e-4596-83a7-7cffc6ac01fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/176d785f23112e19f22fe7b4c9fd8d7fcfe332e1/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60a421e9-2fa3-41d2-962d-a4179976c897) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/176d785f23112e19f22fe7b4c9fd8d7fcfe332e1/msteams-platform%2Fget-started%2Fget-started-overview.md) | 81 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/712ac798-503a-428a-ab05-9cbfff25986a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/176d785f23112e19f22fe7b4c9fd8d7fcfe332e1/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfdd09c9-ac00-4b29-bb34-10bf7fdfa396) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/98a6e2021ac1553cc658bf9b6b0e73f716e78554/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d1a1f1e-bae3-45eb-a4dc-648a1ea16e99) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98a6e2021ac1553cc658bf9b6b0e73f716e78554/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2be87b10-6cea-4026-be0b-099bdd1737cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98a6e2021ac1553cc658bf9b6b0e73f716e78554/msteams-platform%2Fget-started%2Fget-started-overview.md) | 81 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/655ced5f-8447-47b1-a35e-304d687e4544) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98a6e2021ac1553cc658bf9b6b0e73f716e78554/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0433e56b-0e67-4515-8186-f04a2f35970c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/188ac1c530502be85fcee5ff538b5e3613eb8f23/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/868a587b-d4f8-47bb-bbb3-37afcdd6e7fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/188ac1c530502be85fcee5ff538b5e3613eb8f23/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9d039bd-b49e-407e-8cb6-384265124b15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/188ac1c530502be85fcee5ff538b5e3613eb8f23/msteams-platform%2Fget-started%2Fget-started-overview.md) | 81 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fedf0ff3-75a3-4e34-9aa3-732c23a33793) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/188ac1c530502be85fcee5ff538b5e3613eb8f23/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b45c3ee-b290-4b7a-92ae-7abb69d929fb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
