### PR TITLE
[Doc Improvement][Update the docs set with consistent app manifest terminology][3124756]

### PR DESCRIPTION
**Pull request by v-ganr**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/469bee377ae9d22c4573552a8ef1f5ea5576f349/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc559984-04d5-473c-93ae-a5477324205a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/469bee377ae9d22c4573552a8ef1f5ea5576f349/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b3a12d6-c461-497d-811d-68becec29060) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/469bee377ae9d22c4573552a8ef1f5ea5576f349/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30439335-8b88-4482-918a-9eeb445f9fb9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/469bee377ae9d22c4573552a8ef1f5ea5576f349/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a69deff-ff1a-4636-a8bc-9a78a8c9a6e2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1090e7ce0563994bfe0a94f85b500fff59b1ff3e/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae1779b7-d098-4a85-a202-0646f237f4ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1090e7ce0563994bfe0a94f85b500fff59b1ff3e/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c0c4eb1-5ab4-4af7-bd28-99011dd77ab2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1090e7ce0563994bfe0a94f85b500fff59b1ff3e/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98f50c40-3256-45dd-ade0-858a604ca642) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1090e7ce0563994bfe0a94f85b500fff59b1ff3e/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 94 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c7a82b8-daa9-4af0-83f3-5883e2756324) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-deabira** [comment]
The content has been added from PR #9225

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8691aecbea65295f10003476b688e9823d0bdbe2/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34f63f47-e57b-4281-839d-9984d80b307d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8691aecbea65295f10003476b688e9823d0bdbe2/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d31c9cc-90da-4354-bc65-dddbbb6a3678) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8691aecbea65295f10003476b688e9823d0bdbe2/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f13ad76b-a258-4ef1-b20f-80086ca0495e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8691aecbea65295f10003476b688e9823d0bdbe2/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 94 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b11cedb1-8a49-4007-b98d-edc04798c1b5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/911b454f430a28ef16255e2e4b46e2b92ee518a3/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c221da64-fad6-4d52-876e-ce9552f7a6e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/911b454f430a28ef16255e2e4b46e2b92ee518a3/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9dc084e7-d929-4194-bcfb-d9ad4145dcbd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/911b454f430a28ef16255e2e4b46e2b92ee518a3/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/558d53d0-44af-48ec-8654-fd507c0642b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/911b454f430a28ef16255e2e4b46e2b92ee518a3/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 94 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3c0c2b2-c840-4ed2-8910-29e25dbdef1b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
