### PR TITLE
[Doc Improvement][Update direct links to SDK references][3862519]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7090b97fa211a1b252f1075b67be5bbfbb0ce6d/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae0af639-0025-4b06-a30c-aad9b3d6fd86) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3fb0093b690de315ec4f0609ac2024e487970389/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 83 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2036399-6c2b-4c20-9279-b8cb66b5c26c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3fb0093b690de315ec4f0609ac2024e487970389/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b814d58b-946f-4cb3-849c-cef940072ca9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3fb0093b690de315ec4f0609ac2024e487970389/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8ee8e5a-5a66-48f5-aff7-4e94bdc5e70b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a7b56997500bcc424e98e1aaad50ccf42a4f1fe/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 83 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/675e3f76-d06a-4072-9ea6-09125fd885e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a7b56997500bcc424e98e1aaad50ccf42a4f1fe/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b113351-ce95-4a6a-a140-cb339c841dd4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a7b56997500bcc424e98e1aaad50ccf42a4f1fe/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5983cfd2-0e43-4a87-a98d-770ee0e72e11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a7b56997500bcc424e98e1aaad50ccf42a4f1fe/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bec1c04-1209-4178-b9ff-d3fec36bffb7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a7b56997500bcc424e98e1aaad50ccf42a4f1fe/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/919241eb-526d-464e-89f0-6a3f326f4a2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a7b56997500bcc424e98e1aaad50ccf42a4f1fe/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7362b9c1-40d2-4e29-a72e-0d172b05ec17) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c07b0b1310f6e716c6cc39fb19ebb2dda53f50d/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 83 | 82 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62d635d1-7c94-4570-b706-82ef65d8345f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c07b0b1310f6e716c6cc39fb19ebb2dda53f50d/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a7253a3-6f79-4406-ac77-bb2575bb323d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c07b0b1310f6e716c6cc39fb19ebb2dda53f50d/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a3aa83b-9f7f-4ab3-ae48-bf4474e51e56) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c07b0b1310f6e716c6cc39fb19ebb2dda53f50d/msteams-platform%2Ftabs%2Fdesign%2Ftabs-mobile.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee6616b2-2c2b-4b91-aeb9-eb685b33cbea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c07b0b1310f6e716c6cc39fb19ebb2dda53f50d/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/261f097c-e3c1-400d-8b87-cde568e95de0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c07b0b1310f6e716c6cc39fb19ebb2dda53f50d/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14c0ec65-9836-4ee0-afb6-2ec2bcde6104) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c07b0b1310f6e716c6cc39fb19ebb2dda53f50d/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9393d3db-b977-43ff-b882-b1a5df0f955b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0c07b0b1310f6e716c6cc39fb19ebb2dda53f50d/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd7fdbd8-f685-43d5-931e-b1fadfa8d4a4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/238db3ee4cbf3333666d42df40a083412eee9c25/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 83 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ec8215c-2ea2-4dcb-b2ad-f40179d2e4ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/238db3ee4cbf3333666d42df40a083412eee9c25/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/867a8521-d7b2-42ef-aa44-8ec3b41b0fb5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/238db3ee4cbf3333666d42df40a083412eee9c25/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1476e42f-7ec1-42be-a272-108de5c5dadb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/238db3ee4cbf3333666d42df40a083412eee9c25/msteams-platform%2Ftabs%2Fdesign%2Ftabs-mobile.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c4624da-58e7-4543-8386-02a2fa8edaa3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/238db3ee4cbf3333666d42df40a083412eee9c25/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7d280c0-0f37-4c89-bb0b-a0a8ae21d254) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/238db3ee4cbf3333666d42df40a083412eee9c25/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e128898-8ce7-4b9a-8685-96191b821094) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/238db3ee4cbf3333666d42df40a083412eee9c25/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/046ef343-5eb7-43d6-bd36-2e5b994c50dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/238db3ee4cbf3333666d42df40a083412eee9c25/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f58cc017-f53f-47a9-a1de-bf0af7330ea3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
