### PR TITLE
[Doc Improvement][SEO meta description update][3933315]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aa22a499cdc87ab799c4ac0b61d995b9c83e57a1/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 84 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e319347a-9162-487e-9a1c-e642b5791e20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-app-test-tool.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aa22a499cdc87ab799c4ac0b61d995b9c83e57a1/msteams-platform%2Fsbs-teams-app-test-tool.yml) | 80 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e88cd42-e07a-4a86-9e5e-a595465dca95) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aa22a499cdc87ab799c4ac0b61d995b9c83e57a1/msteams-platform%2Fsbs-teams-connectors.yml) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df9d11c9-b1ce-4664-bb78-d7cde952a2ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aa22a499cdc87ab799c4ac0b61d995b9c83e57a1/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b740e0b2-557a-4a20-bec5-d2dee5d2bc43) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aa22a499cdc87ab799c4ac0b61d995b9c83e57a1/msteams-platform%2Fsbs-teams-live-share.yml) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d23f09ac-7c56-45c6-a366-31034da928b4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/826ecfad9b41e1e0670ed9b85da6c425704588df/msteams-platform%2Fsbs-meetings-stage-view.yml) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1d64003-4977-4838-82f5-db7406f2b246) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/826ecfad9b41e1e0670ed9b85da6c425704588df/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 81 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4f19ddc-11c8-4cd7-b635-8e9c1e970a4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/826ecfad9b41e1e0670ed9b85da6c425704588df/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f9386ae-7ce6-43c7-aa1d-33dea4181c6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/826ecfad9b41e1e0670ed9b85da6c425704588df/msteams-platform%2Fsbs-tab-device-permissions.yml) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0dbbdba-af4b-4ac2-8629-e8fa1e3b226a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/826ecfad9b41e1e0670ed9b85da6c425704588df/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 84 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1688e122-3c28-4d3c-aa0f-77916a670e52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/826ecfad9b41e1e0670ed9b85da6c425704588df/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acc4c8b3-de20-4d7d-ab58-8b429ecdbbe6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-app-test-tool.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/826ecfad9b41e1e0670ed9b85da6c425704588df/msteams-platform%2Fsbs-teams-app-test-tool.yml) | 80 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/780b355d-dff7-4c17-ae08-0a6a6db72755) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/826ecfad9b41e1e0670ed9b85da6c425704588df/msteams-platform%2Fsbs-teams-connectors.yml) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6afa8ca0-9ff9-4a51-bb57-cddc3be0dcc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/826ecfad9b41e1e0670ed9b85da6c425704588df/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfad8173-84c5-4260-a68d-3490a19466d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/826ecfad9b41e1e0670ed9b85da6c425704588df/msteams-platform%2Fsbs-teams-live-share.yml) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e36dd9e-06d7-4775-8040-9a25d777b490) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91f7eb737846e2a28a62da9070cb54103cf65759/msteams-platform%2Fsbs-meetings-stage-view.yml) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0f0e5c7-94b5-4783-b771-a8f3c2082724) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91f7eb737846e2a28a62da9070cb54103cf65759/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 81 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ec80023-57e4-486b-8d3f-d9330480e012) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91f7eb737846e2a28a62da9070cb54103cf65759/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25b0da30-b45b-498f-81bf-9e759f683523) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91f7eb737846e2a28a62da9070cb54103cf65759/msteams-platform%2Fsbs-tab-device-permissions.yml) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb86ab32-d00d-4897-a6de-155fcec1ef84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91f7eb737846e2a28a62da9070cb54103cf65759/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 84 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e905f5e9-9a65-4d5c-835c-f1fa5f281fe0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91f7eb737846e2a28a62da9070cb54103cf65759/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27d62ea2-5e17-416a-bf3c-4322ef41153b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-app-test-tool.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91f7eb737846e2a28a62da9070cb54103cf65759/msteams-platform%2Fsbs-teams-app-test-tool.yml) | 80 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16475400-3b68-4d76-8903-c2d7262bda44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91f7eb737846e2a28a62da9070cb54103cf65759/msteams-platform%2Fsbs-teams-connectors.yml) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/228f8d5d-186e-4201-967c-210f41b0afc9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91f7eb737846e2a28a62da9070cb54103cf65759/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e760899c-5d87-4e45-87f7-56e7ddeb73aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91f7eb737846e2a28a62da9070cb54103cf65759/msteams-platform%2Fsbs-teams-live-share.yml) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81d8bb97-ae44-4895-9494-8c540daa3a84) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fc815c14538a7fd5418a4dc5af8210dabe9e66ae/msteams-platform%2Fsbs-meetings-stage-view.yml) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aabf9f41-65d7-4abf-a603-e5dd1d9f449f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fc815c14538a7fd5418a4dc5af8210dabe9e66ae/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 81 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ca5e124-c7ac-4d85-a5e5-972b58593418) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fc815c14538a7fd5418a4dc5af8210dabe9e66ae/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f1a4e9b-cf0f-4107-8419-942983c4d95a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fc815c14538a7fd5418a4dc5af8210dabe9e66ae/msteams-platform%2Fsbs-tab-device-permissions.yml) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5340bfd-c3a6-48d2-9c1f-2871b7d17d0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fc815c14538a7fd5418a4dc5af8210dabe9e66ae/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 84 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5eeddeaf-1ec8-4d7a-871a-2f59f323b519) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fc815c14538a7fd5418a4dc5af8210dabe9e66ae/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b2959be-7187-4b8a-923e-1fc5cdd2745e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-app-test-tool.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fc815c14538a7fd5418a4dc5af8210dabe9e66ae/msteams-platform%2Fsbs-teams-app-test-tool.yml) | 80 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbe6c4d5-6111-4dcf-8cca-297390f1bfe7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fc815c14538a7fd5418a4dc5af8210dabe9e66ae/msteams-platform%2Fsbs-teams-connectors.yml) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f19ee9b1-66be-420b-9ed0-214ff56d7791) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fc815c14538a7fd5418a4dc5af8210dabe9e66ae/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a936d789-7ada-4ada-ba91-1cf5a78ad3b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fc815c14538a7fd5418a4dc5af8210dabe9e66ae/msteams-platform%2Fsbs-teams-live-share.yml) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84b297de-8d41-44eb-baef-0accfd9b8977) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b4968b91b47daa758bc43b20536208f290fbddf/msteams-platform%2Fsbs-meetings-stage-view.yml) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f2b8c5a-6c74-488b-924a-1e5ac002ff04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b4968b91b47daa758bc43b20536208f290fbddf/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 81 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd2c6183-9ed8-479d-b168-9b32d1b7b8df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b4968b91b47daa758bc43b20536208f290fbddf/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3966f66a-7712-4c6e-a572-8644e3f09378) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b4968b91b47daa758bc43b20536208f290fbddf/msteams-platform%2Fsbs-tab-device-permissions.yml) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/147158ec-9cd6-485d-bf3c-dab2dca5dda5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b4968b91b47daa758bc43b20536208f290fbddf/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 84 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8837366-264f-440f-a662-92fd2ebdfa86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b4968b91b47daa758bc43b20536208f290fbddf/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bdb3d63-949a-4513-a131-6f650daf922d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-app-test-tool.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b4968b91b47daa758bc43b20536208f290fbddf/msteams-platform%2Fsbs-teams-app-test-tool.yml) | 80 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/934bd5b7-0903-4d67-bb7f-ea204e6fb4b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b4968b91b47daa758bc43b20536208f290fbddf/msteams-platform%2Fsbs-teams-connectors.yml) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01b0e0cc-b4b2-4d66-8ad8-668147c2b356) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b4968b91b47daa758bc43b20536208f290fbddf/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/236c4f05-1156-4c4e-8051-5185012859ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b4968b91b47daa758bc43b20536208f290fbddf/msteams-platform%2Fsbs-teams-live-share.yml) | 86 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3dadba7b-9fca-490a-840d-5883cc42075b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/317043d90480a5956a929ad33380f39e468abb71/msteams-platform%2Fsbs-meetings-stage-view.yml) | 88 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74dd888b-6cf8-40df-9ca4-a135ec1e3df8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/317043d90480a5956a929ad33380f39e468abb71/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 81 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00e75cfa-0a9d-43b9-826a-2a0d3b58b59e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/317043d90480a5956a929ad33380f39e468abb71/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/249efea0-2261-491a-9359-ec04ad1edc1f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/317043d90480a5956a929ad33380f39e468abb71/msteams-platform%2Fsbs-tab-device-permissions.yml) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34aa8502-6c2e-4eeb-94eb-abddf567734d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/317043d90480a5956a929ad33380f39e468abb71/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 84 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f120fb9-68da-47a8-a125-2d72e0f02c40) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/317043d90480a5956a929ad33380f39e468abb71/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/803b15bc-15e8-4733-a913-390d660f7a57) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-app-test-tool.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/317043d90480a5956a929ad33380f39e468abb71/msteams-platform%2Fsbs-teams-app-test-tool.yml) | 80 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cda7951-2857-4b72-ba9a-e745b99d3059) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/317043d90480a5956a929ad33380f39e468abb71/msteams-platform%2Fsbs-teams-connectors.yml) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57614ef1-6a08-4b6a-81d8-0748b2467c53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/317043d90480a5956a929ad33380f39e468abb71/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a84c4fd1-c959-46a4-9e36-f6a04bf0cbe3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/317043d90480a5956a929ad33380f39e468abb71/msteams-platform%2Fsbs-teams-live-share.yml) | 86 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6cf36b8-37aa-4819-b369-e669579060f7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
