### PR TITLE
[BULK UPDATE] DocuTune - Rebranding links

### PR DESCRIPTION
**Pull request by alexbuckgit**
**Global effort for the Microsoft Learn platform rebrand**

The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.

Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.

This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.

CorrelationId: d8c4c3ac-d49a-4c95-9ddc-9822ca297907
InitiativeId: docutune-rebranding-2022-09
PointOfContact: Alex Buck

### CODE REVIEW

**Comment by alexbuckgit** [comment]
#docutune-draft

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/article-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbaf8e4e21a61feb3eaf49a12dcda8d92715cddf/msteams-platform%2Fincludes%2Farticle-template.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/847c8161-4406-4148-ab10-e6d63b00cafa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bbaf8e4e21a61feb3eaf49a12dcda8d92715cddf/msteams-platform%2Findex.yml) | 94 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2fb18f3-ad4c-4ad7-b4f1-8e0bf6eeb45f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbaf8e4e21a61feb3eaf49a12dcda8d92715cddf/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86e07bec-1575-4399-a4a2-581e3254b619) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-commandbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bbaf8e4e21a61feb3eaf49a12dcda8d92715cddf/msteams-platform%2Fsbs-gs-commandbot.yml) | 90 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2077b2b0-4877-4b81-b4f4-ece60c8fb8ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bbaf8e4e21a61feb3eaf49a12dcda8d92715cddf/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b304620-3aa6-4957-9f21-a4d41bd9323a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bbaf8e4e21a61feb3eaf49a12dcda8d92715cddf/msteams-platform%2Fsbs-meetings-stage-view.yml) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de95ea88-8982-4e9c-a637-07cf68c3944b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bbaf8e4e21a61feb3eaf49a12dcda8d92715cddf/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ff33c5a-db52-4dc1-b8b7-0c14251eb403) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bbaf8e4e21a61feb3eaf49a12dcda8d92715cddf/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 87 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53006989-354c-4547-ad86-0c1616e1b0db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbaf8e4e21a61feb3eaf49a12dcda8d92715cddf/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-actions.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ff062dc-7d78-46e8-9644-9815f55f5c40) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bbaf8e4e21a61feb3eaf49a12dcda8d92715cddf/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-using.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22ba1a1f-e465-4692-b185-499afeceb55d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by damabe** [comment]
#docutune-ready

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/article-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/68eb01de2da5ebf594091e4735a664bff23139a6/msteams-platform%2Fincludes%2Farticle-template.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99687506-197f-4dfb-9c64-8387422f847d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/68eb01de2da5ebf594091e4735a664bff23139a6/msteams-platform%2Findex.yml) | 94 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf4ac9d2-d0a0-4c43-b4b3-17de476e42ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/68eb01de2da5ebf594091e4735a664bff23139a6/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca846cd7-eaa1-4555-9896-8f5b0ebe6a56) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/68eb01de2da5ebf594091e4735a664bff23139a6/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1517695b-5352-462d-b529-6ae575b48836) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/68eb01de2da5ebf594091e4735a664bff23139a6/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 87 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b214a04-3a75-4047-b1c4-13dd734e66f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/68eb01de2da5ebf594091e4735a664bff23139a6/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-actions.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34bd45b2-6db7-4834-a0e1-e52803459269) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
