### PR TITLE
[Doc Improvement][Update tabs section and redirect files][3987075]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/97ea7a5ee487583327a54c1a13e29e27175e33d6/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdf9719a-d815-434d-8a78-e47a40b6608a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2a9404154bcda3c0d60f633a1e5a997e85e77eee/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f0d17c9-29d7-4a79-9612-e643b4c08c8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a9404154bcda3c0d60f633a1e5a997e85e77eee/msteams-platform%2Ftabs%2Fdesign%2Ftabs-mobile.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec35f095-42d8-452f-a9df-77082fc434b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a9404154bcda3c0d60f633a1e5a997e85e77eee/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85be3ccf-67de-4337-a7ae-c3d934ce6d8e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a9404154bcda3c0d60f633a1e5a997e85e77eee/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 92 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81db9bf3-d922-4772-8a96-706e0bd6d5b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a9404154bcda3c0d60f633a1e5a997e85e77eee/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8f8abb5-fe86-49a2-995a-b659cdc80c6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a9404154bcda3c0d60f633a1e5a997e85e77eee/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-using.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8b6266e-e768-4b78-a018-81e2415b4dec) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by Wajeed-msft** [comment]
@Pawank-MSFT - Let's remove the sample code as well for Adaptive Card tabs. 

https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-adaptive-cards

**Review by Wajeed-msft — APPROVED** [review]

**Comment by v-npaladugu** [comment]
Moved the changes to PR #11634

**Pull request closed without merging**
