### PR TITLE
[Doc Improvement][Add location and media note][3562584]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff77fd45dfc3d6ddac0d962bc84bc1ec4a9b5ab4/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ccc3c68-3f86-406c-bcd0-d4dacd0098ef) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea6406a77994672e462e6e7505d6b6e034d5d37c/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe25aa05-e7d2-460a-929f-8a8272aa1145) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6102826c9621c283f8dcb653bfe992f0bca50653/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/576dbd28-39e2-4727-a502-a4dabefdc3d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6102826c9621c283f8dcb653bfe992f0bca50653/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5145e128-669d-4c8f-bbd2-1b9bc61028be) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6102826c9621c283f8dcb653bfe992f0bca50653/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a498959e-4000-48de-859f-040a2557384c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6102826c9621c283f8dcb653bfe992f0bca50653/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d45b6a9f-17c1-4fd7-9cc5-a7dc8f4520e4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf3ae26cd950f400dda2196018e731bfc2b326ca/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db788879-b24c-4f0b-b641-32f0c5b400bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf3ae26cd950f400dda2196018e731bfc2b326ca/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1b50a7f-426e-4ef4-828b-8998db257169) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/809a10ff8c7a3a28b71394466eda1f4541571c88/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aabc07d1-3c06-4e12-89b9-8437780689e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/809a10ff8c7a3a28b71394466eda1f4541571c88/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3ab670c-3732-4d13-ac26-bd5c951dc9be) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Pull request merged**
