### PR TITLE
[Doc Improvement][Update for adaptive card loop component GA support][3597403]

### PR DESCRIPTION
**Pull request by JoshuaPartlow**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/779721de16b955e6b3c379233d6c7cff2e961470/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/756ede64-9710-4e6c-af3b-6704159d983a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/779721de16b955e6b3c379233d6c7cff2e961470/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f17a8d15-f79c-417b-8cbe-ffd81b201239) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/779721de16b955e6b3c379233d6c7cff2e961470/msteams-platform%2Fm365-apps%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c96fd24-c9df-42e1-bdc7-52eeb9ed7d7e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by erikadoyle — APPROVED** [review]
LGTM. @surbhigupta12 could someone on your team please help to review/merge? Thanks!

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/afdf678c7c37854f1ffce2e2ab7e45dab7043cc1/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6383bc52-f23b-4334-b52a-a9d03393f593) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/afdf678c7c37854f1ffce2e2ab7e45dab7043cc1/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d672b821-d195-404b-9251-feb6925a9305) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/afdf678c7c37854f1ffce2e2ab7e45dab7043cc1/msteams-platform%2Fm365-apps%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4350662d-faa9-4678-a82e-bba23200ac74) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd46e47675a6253c9c308827f30e562bac00be2d/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8a1d9bb-0e90-4613-a83f-fb37c897946b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd46e47675a6253c9c308827f30e562bac00be2d/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de4b750f-f5cf-4d94-85a2-11b5a8431ccd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd46e47675a6253c9c308827f30e562bac00be2d/msteams-platform%2Fm365-apps%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e58827d7-f97b-4fb4-9b21-d739e25b8b42) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66a4cda0c793f17f1e5b3fe76a9739b5d32f147f/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da8ad41b-f6ad-4cff-a482-ed885b93205d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66a4cda0c793f17f1e5b3fe76a9739b5d32f147f/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39be8fbb-722b-45f3-9010-fafe4a3c300e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66a4cda0c793f17f1e5b3fe76a9739b5d32f147f/msteams-platform%2Fm365-apps%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/263cae42-f999-4b12-9517-dd58cbb285f1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/190f73a0b6049fc3daf35a5d5079f0d22392328a/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a3207f6-8056-45a0-a6ca-793b77327c8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/190f73a0b6049fc3daf35a5d5079f0d22392328a/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2af7ca2d-e8f8-4ab3-9256-831b09136f2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/190f73a0b6049fc3daf35a5d5079f0d22392328a/msteams-platform%2Fm365-apps%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de85de6a-f058-4d85-8431-b8c5debab134) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/190f73a0b6049fc3daf35a5d5079f0d22392328a/msteams-platform%2Fmstdd-landing.yml) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd8d23b4-4e11-49fe-ab79-85b0375925ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/190f73a0b6049fc3daf35a5d5079f0d22392328a/msteams-platform%2Fwhats-new.md) | 94 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6813214a-c8f1-4c6d-babb-7472ddabe909) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/629d3b72edaaea4bc4cfb5b6bb3a3676bd18d3fb/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac221b14-7577-4c22-a66b-3309af43ddbd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/629d3b72edaaea4bc4cfb5b6bb3a3676bd18d3fb/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/502dfde7-6200-428f-a28e-e39d070747ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/629d3b72edaaea4bc4cfb5b6bb3a3676bd18d3fb/msteams-platform%2Fm365-apps%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/993624a8-0917-4352-8ce9-7154d949a5ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/629d3b72edaaea4bc4cfb5b6bb3a3676bd18d3fb/msteams-platform%2Fmstdd-landing.yml) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9b6fc14-0251-4494-98a7-6df1e7380a34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/629d3b72edaaea4bc4cfb5b6bb3a3676bd18d3fb/msteams-platform%2Fwhats-new.md) | 94 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70296fdd-6492-44ec-b9a4-f775aa4e401d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/336a01bbfac1049b22490eafc4b3045b91093c70/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97cccd3d-3778-49ce-93c5-e1b21bd9020a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/336a01bbfac1049b22490eafc4b3045b91093c70/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5dce4c8-32a5-4d88-8f6f-7b110f6751f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/336a01bbfac1049b22490eafc4b3045b91093c70/msteams-platform%2Fm365-apps%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c2cb26f-b93b-455f-be10-f205d6fccf37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/336a01bbfac1049b22490eafc4b3045b91093c70/msteams-platform%2Fmstdd-landing.yml) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3f28fa8-6c6a-4f7b-befe-a7d7b735b1c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/336a01bbfac1049b22490eafc4b3045b91093c70/msteams-platform%2Fwhats-new.md) | 94 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1793ac1e-c727-468c-9818-6a4a22032ad9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15b11b521086c6d6c8e6fd6271a2b8709601868f/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8f77405-7b3f-49f7-a22e-07432ee52277) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15b11b521086c6d6c8e6fd6271a2b8709601868f/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c881747-7c72-4622-b053-9bb6caf633d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15b11b521086c6d6c8e6fd6271a2b8709601868f/msteams-platform%2Fm365-apps%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5553541e-4705-44a1-a75a-b7655bf37855) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/15b11b521086c6d6c8e6fd6271a2b8709601868f/msteams-platform%2Fmstdd-landing.yml) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b9c551a-876c-49fe-b63e-85535207b1e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15b11b521086c6d6c8e6fd6271a2b8709601868f/msteams-platform%2Fwhats-new.md) | 94 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0af863ef-9cbe-43cf-af9b-57e0eae2c31e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3bfe7cf14434c3c67be686675ba8c850ecf0d9b/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21cc4337-2a3f-4ed1-920e-2f09992b1001) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3bfe7cf14434c3c67be686675ba8c850ecf0d9b/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fddf887e-a8e8-4439-b6d9-bbc71df7e71b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3bfe7cf14434c3c67be686675ba8c850ecf0d9b/msteams-platform%2Fm365-apps%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/261535d0-3fe3-444a-b19b-d44993c7f8e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d3bfe7cf14434c3c67be686675ba8c850ecf0d9b/msteams-platform%2Fmstdd-landing.yml) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b5df3fd-0e7a-4be2-838a-3c061254dcde) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3bfe7cf14434c3c67be686675ba8c850ecf0d9b/msteams-platform%2Fwhats-new.md) | 94 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aef74d8c-2a4b-42c5-aa4d-976ea4edecca) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
