### PR TITLE
Updated info for R4 and future

### PR DESCRIPTION
**Pull request by billbliss**
Now that this feature is shipped, clarified that it only applies to legacy apps that never updated their config size and that the advice here also applies to the future.

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[de62683](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/de62683cf8ff50ec81911be842662c10ef03e531)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[de62683](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/de62683cf8ff50ec81911be842662c10ef03e531)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[de62683](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/de62683cf8ff50ec81911be842662c10ef03e531)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/resources/dev-preview/developer-preview-features.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C6%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903061654246417-490%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QihrmKG4jpzpgBKl8Fu2jD0MMAq0vjfQBJSo2zTharQ%3D&st=2019-03-06T16%3A50%3A35Z&se=2019-04-06T16%3A55%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[326ea79](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/326ea795eeec386d158176b5d6e48538db3b7c88)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[326ea79](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/326ea795eeec386d158176b5d6e48538db3b7c88)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[326ea79](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/326ea795eeec386d158176b5d6e48538db3b7c88)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/whats-new.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fwhats-new.md)
[msteams-platform/resources/design/framework/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/resources/design/framework/tabs.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/resources/dev-preview/developer-preview-features.md) | :white_check_mark:Succeeded | |

<a name="msteams-platform%2Fwhats-new.md"></a>
### [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/whats-new.md)
 - **Line 35**: **[Warning]** Illegal link: `[The tab configuration page is significantly taller](~/resources/dev-preview/developer-preview-features.md#the-tab-configuration-page-is-significantly-taller)` -- missing bookmark. The file resources/dev-preview/developer-preview-features.md doesn&#39;t contain a bookmark named the-tab-configuration-page-is-significantly-taller.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C6%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903062132237884-490%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ITV7qfEraOK1L8tUod3pA3EUdvE%2B3Z0OAEzcPG%2FHuM8%3D&st=2019-03-06T21%3A28%3A35Z&se=2019-04-06T21%3A33%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clearab** [comment]
@billbliss Since the design page had basically the same information, I consolidated it there. My thinking is w/o doing so there really wouldn't ever be a good time to remove this section from the developer preview features page.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[4166c30](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/4166c307116642db5c1497c1e12ee00682efa1c3)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[4166c30](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/4166c307116642db5c1497c1e12ee00682efa1c3)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[4166c30](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/4166c307116642db5c1497c1e12ee00682efa1c3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/whats-new.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fwhats-new.md)
[msteams-platform/concepts/tabs/tabs-configuration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/concepts/tabs/tabs-configuration.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/design/framework/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/resources/design/framework/tabs.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/resources/dev-preview/developer-preview-features.md) | :white_check_mark:Succeeded | |

<a name="msteams-platform%2Fwhats-new.md"></a>
### [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/whats-new.md)
 - **Line 35**: **[Warning]** Illegal link: `[The tab configuration page is significantly taller](~/resources/dev-preview/developer-preview-features.md#the-tab-configuration-page-is-significantly-taller)` -- missing bookmark. The file resources/dev-preview/developer-preview-features.md doesn&#39;t contain a bookmark named the-tab-configuration-page-is-significantly-taller.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C6%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903062232307544-490%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MBWVRCSL%2FjXSHqPnbvw9j%2Fi%2BkZ4x3kfgIVWJnqGQkYU%3D&st=2019-03-06T22%3A28%3A44Z&se=2019-04-06T22%3A33%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[f0f8b55](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/f0f8b55d3debf7ee829738fce94424cb4e0e932e)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[f0f8b55](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/f0f8b55d3debf7ee829738fce94424cb4e0e932e)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[f0f8b55](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/f0f8b55d3debf7ee829738fce94424cb4e0e932e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/whats-new.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fwhats-new.md)
[msteams-platform/concepts/tabs/tabs-configuration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/concepts/tabs/tabs-configuration.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/design/framework/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/resources/design/framework/tabs.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/resources/dev-preview/developer-preview-features.md) | :white_check_mark:Succeeded | |

<a name="msteams-platform%2Fwhats-new.md"></a>
### [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/whats-new.md)
 - **Line 35**: **[Warning]** Invalid file link:(~/resources/design/framework/tabs#configuration-page-height).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C6%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903062323248736-490%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ZN2QdqrvPasvANpURCaQnv6r1aHt8mjJanRKOhf5rac%3D&st=2019-03-06T23%3A19%3A35Z&se=2019-04-06T23%3A24%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[f254ff3](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/f254ff32a91516bc6dde6b99731e1491bd560184)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[f254ff3](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/f254ff32a91516bc6dde6b99731e1491bd560184)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[f254ff3](https://github.com/MicrosoftDocs/msteams-docs/pull/490/commits/f254ff32a91516bc6dde6b99731e1491bd560184)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/tabs/tabs-configuration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/concepts/tabs/tabs-configuration.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/design/framework/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/resources/design/framework/tabs.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/resources/dev-preview/developer-preview-features.md) | :white_check_mark:Succeeded | |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/billbl-tab-config-r4/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C6%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903062325352764-490%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1VbspecuCchh1q32JPPhSDFkxSiMqvuWadB1ylOyZCA%3D&st=2019-03-06T23%3A21%3A45Z&se=2019-04-06T23%3A26%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
