### PR TITLE
Vikramjit mobilewhitelisting

### PR DESCRIPTION
**Pull request by vikramjit-singh-chug**

### CODE REVIEW

**Review by KirtiPereira — CHANGES_REQUESTED** [review]
Please verify the suggestions for technical accuracy and commit them.
Thank you.

**Review by surbhigupta12 — CHANGES_REQUESTED** [review]
Hi @vikramjit-singh-chug, please update this comment as well:

https://github.com/MicrosoftDocs/msteams-docs/pull/2559/files#r552519372

**Review by KirtiPereira — APPROVED** [review]
Thank you for committing the suggestions. Approving the PR for merging.
Thank you.

**Review by surbhigupta12 — APPROVED** [review]
Thanks for the updates.

**Pull request merged**
