### PR TITLE
Clarifying Bot Framework version in Teams auth guide

### PR DESCRIPTION
**Pull request by mark-szabo**
Adding a clarifying message saying that the guide is for Bot Framework v3 SDK, and a link pointing to the v4 implementation.

### CODE REVIEW

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/authentication/auth-oauth-card.md](https://github.com/mark-szabo/msteams-docs/blob/patch-1/msteams-platform/concepts/authentication/auth-oauth-card.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fconcepts%2Fauthentication%2Fauth-oauth-card.md)

<a name="msteams-platform%2Fconcepts%2Fauthentication%2Fauth-oauth-card.md"></a>
### [msteams-platform/concepts/authentication/auth-oauth-card.md](https://github.com/mark-szabo/msteams-docs/blob/patch-1/msteams-platform/concepts/authentication/auth-oauth-card.md)
 - **Line 15**: **[Warning]** Invalid file link:(~/concepts/authentication/authentication).
 - **Line 45**: **[Warning]** Invalid file link:(~/concepts/authentication/authentication).
 - **Line 51**: **[Warning]** Invalid file link:(~/concepts/authentication/auth-configure).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C8%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201811080956241683-319%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=I6iVHD3NzorS2%2Bk0Okgnht1CIfhR4WuSSZ3UPckkgzE%3D&st=2018-11-08T09%3A52%3A33Z&se=2018-12-09T09%3A57%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by mark-szabo** [comment]
Should I replace the relative links with absolute ones?

**Comment by clearab** [comment]
@billbliss This looks ok to me, do you agree?

**Comment by o365devx** [comment]
OPS Build status updates of commit _[5a3ebb0](https://github.com/mark-szabo/msteams-docs/pull/319/commits/5a3ebb03eab1aada573a47131654393fbfbe81e5)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[5a3ebb0](https://github.com/mark-szabo/msteams-docs/pull/319/commits/5a3ebb03eab1aada573a47131654393fbfbe81e5)_: 

:clock10: **Incremental building**: average incremental building time is _21 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[5a3ebb0](https://github.com/mark-szabo/msteams-docs/pull/319/commits/5a3ebb03eab1aada573a47131654393fbfbe81e5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/authentication/auth-oauth-card.md](https://github.com/mark-szabo/msteams-docs/blob/patch-1/msteams-platform/concepts/authentication/auth-oauth-card.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fconcepts%2Fauthentication%2Fauth-oauth-card.md)

<a name="msteams-platform%2Fconcepts%2Fauthentication%2Fauth-oauth-card.md"></a>
### [msteams-platform/concepts/authentication/auth-oauth-card.md](https://github.com/mark-szabo/msteams-docs/blob/patch-1/msteams-platform/concepts/authentication/auth-oauth-card.md)
 - **Line 15**: **[Warning]** Invalid file link:(~/concepts/authentication/authentication).
 - **Line 44**: **[Warning]** Invalid file link:(~/concepts/authentication/authentication).
 - **Line 50**: **[Warning]** Invalid file link:(~/concepts/authentication/auth-configure).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201901222055486163-319%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=x8PGbMWZTS0eCtPK1z1IqF9wtx2cPNueBo6gjscNMGw%3D&st=2019-01-22T20%3A51%3A58Z&se=2019-02-22T20%3A56%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[2ec6b8b](https://github.com/mark-szabo/msteams-docs/pull/319/commits/2ec6b8b56498fe3e3cdf5e466d46f79b89e5f771)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[2ec6b8b](https://github.com/mark-szabo/msteams-docs/pull/319/commits/2ec6b8b56498fe3e3cdf5e466d46f79b89e5f771)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[2ec6b8b](https://github.com/mark-szabo/msteams-docs/pull/319/commits/2ec6b8b56498fe3e3cdf5e466d46f79b89e5f771)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/authentication/auth-oauth-card.md](https://github.com/mark-szabo/msteams-docs/blob/patch-1/msteams-platform/concepts/authentication/auth-oauth-card.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fconcepts%2Fauthentication%2Fauth-oauth-card.md)

<a name="msteams-platform%2Fconcepts%2Fauthentication%2Fauth-oauth-card.md"></a>
### [msteams-platform/concepts/authentication/auth-oauth-card.md](https://github.com/mark-szabo/msteams-docs/blob/patch-1/msteams-platform/concepts/authentication/auth-oauth-card.md)
 - **Line 18**: **[Warning]** Invalid file link:(~/concepts/authentication/authentication).
 - **Line 47**: **[Warning]** Invalid file link:(~/concepts/authentication/authentication).
 - **Line 53**: **[Warning]** Invalid file link:(~/concepts/authentication/auth-configure).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C20%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201902202225492275-319%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kBPeCy4f7dcjlIYunkvKZJBaJGHsmYUoOk2N2jggG1o%3D&st=2019-02-20T22%3A21%3A53Z&se=2019-03-23T22%3A26%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
