### PR TITLE
[Doc Improvement][SEO Description update 7][3876702]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56afbf539a304ed37e2c627475e6a07e95a1239a/msteams-platform%2Fapps-in-teams-meetings%2Fteams-together-mode.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66156c9e-ba69-4e3e-b870-0316d19c7cee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/archive/how-to-extend-copilot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56afbf539a304ed37e2c627475e6a07e95a1239a/msteams-platform%2Farchive%2Fhow-to-extend-copilot.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1d50aa5-cfbc-44e4-b06c-fc074da22493) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56afbf539a304ed37e2c627475e6a07e95a1239a/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fdebugging-local-testing-calling-meeting-bots.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11e60d6d-4287-4d00-bc0d-f33c68862725) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56afbf539a304ed37e2c627475e6a07e95a1239a/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e6924c9-5699-486f-80aa-e54312485753) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56afbf539a304ed37e2c627475e6a07e95a1239a/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 91 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f53663cf-37b5-413a-a92f-f75b5ac98ed5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56afbf539a304ed37e2c627475e6a07e95a1239a/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 86 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbc268ef-b3ca-4e1c-8a19-7a159924eb31) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56afbf539a304ed37e2c627475e6a07e95a1239a/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-graph-api.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc3ddd85-e4a8-4b7c-84ae-7b35494e5b51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56afbf539a304ed37e2c627475e6a07e95a1239a/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/771f390c-559e-428a-97cf-810b1e33c448) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56afbf539a304ed37e2c627475e6a07e95a1239a/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b69ae735-338b-412b-b9c8-9b8927186cc5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56afbf539a304ed37e2c627475e6a07e95a1239a/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-register-aad.md) | 91 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d08f7a77-2bad-4393-8a9e-d86c66aa945d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ebd8dbde6b781b24e9ddc8aaadb4a960c066e28/msteams-platform%2Fapps-in-teams-meetings%2Fteams-together-mode.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c66955a7-eaa8-4102-a771-f4b67f65bace) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/archive/how-to-extend-copilot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ebd8dbde6b781b24e9ddc8aaadb4a960c066e28/msteams-platform%2Farchive%2Fhow-to-extend-copilot.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65353889-87e7-4891-be3b-548dbcaffd27) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ebd8dbde6b781b24e9ddc8aaadb4a960c066e28/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fdebugging-local-testing-calling-meeting-bots.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ec0b165-fc35-4729-9495-ded6a929e929) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ebd8dbde6b781b24e9ddc8aaadb4a960c066e28/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d37ac756-f600-4424-a231-adf37b306c05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ebd8dbde6b781b24e9ddc8aaadb4a960c066e28/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 91 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/300062c1-81d6-44e3-b6c0-1dbef49893cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ebd8dbde6b781b24e9ddc8aaadb4a960c066e28/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 86 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62907071-7b0a-4251-b992-7987181a8980) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ebd8dbde6b781b24e9ddc8aaadb4a960c066e28/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-graph-api.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/720fe985-dbb4-4fe7-959d-13c1690b6e0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ebd8dbde6b781b24e9ddc8aaadb4a960c066e28/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e3cc70b-436d-4504-867c-6ff5ef79decd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ebd8dbde6b781b24e9ddc8aaadb4a960c066e28/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e4387dd-b85a-4d1f-ae7c-ef183bad0a59) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ebd8dbde6b781b24e9ddc8aaadb4a960c066e28/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-register-aad.md) | 91 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b696008a-7016-487a-a2e9-66a4b100b02b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3543bffa50d5cac0ba32175fec1b740ca6619c88/msteams-platform%2Fapps-in-teams-meetings%2Fteams-together-mode.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ad9427b-9de4-404e-9ed9-8f1b6cc44b2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/archive/how-to-extend-copilot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3543bffa50d5cac0ba32175fec1b740ca6619c88/msteams-platform%2Farchive%2Fhow-to-extend-copilot.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89430225-5be6-4c54-a213-a4802c109a18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3543bffa50d5cac0ba32175fec1b740ca6619c88/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fdebugging-local-testing-calling-meeting-bots.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70448baa-dc4b-4fd8-9595-0a8ff1388787) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3543bffa50d5cac0ba32175fec1b740ca6619c88/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0543b176-a260-4c84-b4e4-ffdd7cb71ecb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3543bffa50d5cac0ba32175fec1b740ca6619c88/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/132e0cc3-cc63-4736-a7eb-3cc80d99fb47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3543bffa50d5cac0ba32175fec1b740ca6619c88/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 86 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a22998ee-fc3d-4f86-b8b0-34ac4c30aa3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3543bffa50d5cac0ba32175fec1b740ca6619c88/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-graph-api.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90a3eadb-f8f8-4290-bc26-4ef59f325455) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3543bffa50d5cac0ba32175fec1b740ca6619c88/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/869acc71-4f47-4c6b-8752-5bc45b07b393) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3543bffa50d5cac0ba32175fec1b740ca6619c88/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d195e86-f360-4fdd-bf9f-924ac1ff287e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3543bffa50d5cac0ba32175fec1b740ca6619c88/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-register-aad.md) | 91 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8279c321-5a13-4013-8c7d-40c0d8134c82) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/620cbc3a2c9e0222064a3df26780f0924ce4ea7d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-together-mode.md) | 92 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ca758bf-b232-41e2-b38d-7ce3efed0c9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/archive/how-to-extend-copilot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/620cbc3a2c9e0222064a3df26780f0924ce4ea7d/msteams-platform%2Farchive%2Fhow-to-extend-copilot.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94928fc4-61b7-454b-b18c-6a55327cb33f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/debugging-local-testing-calling-meeting-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/620cbc3a2c9e0222064a3df26780f0924ce4ea7d/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fdebugging-local-testing-calling-meeting-bots.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da02f7ca-d093-4102-aedb-b72a3e4f7e58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/620cbc3a2c9e0222064a3df26780f0924ce4ea7d/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d49084c-a44e-4e0d-aee9-f873898bf282) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/620cbc3a2c9e0222064a3df26780f0924ce4ea7d/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e6cc6f8-0c3f-45d8-9b33-37430a7dbdf7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/620cbc3a2c9e0222064a3df26780f0924ce4ea7d/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-code.md) | 86 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0a1e28b-ef73-4b79-bf86-9ba75c95a91a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-graph-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/620cbc3a2c9e0222064a3df26780f0924ce4ea7d/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-graph-api.md) | 88 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c025152f-e34c-418a-89cd-aa87d9c3125d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/620cbc3a2c9e0222064a3df26780f0924ce4ea7d/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42ac7675-2cde-4466-b0c2-b7f77626aebf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/620cbc3a2c9e0222064a3df26780f0924ce4ea7d/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86281c5a-cd2d-45f9-8e0b-25cf79f76681) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/620cbc3a2c9e0222064a3df26780f0924ce4ea7d/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-register-aad.md) | 91 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7076b09b-0476-48a6-8c47-474384824022) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
