### PR TITLE
[Doc Issue][Update token parameter and link for SSO][3077745]

### PR DESCRIPTION
**Pull request by Namitha-23**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8e0d3699bf7e79cb367abf2a32707664b912c0d/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-code.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13956a13-0d3e-4978-897a-dded7025470e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by Namitha-23** [comment]
We have received Nivedipa's approval:
MicrosoftTeams-image (4)

**Comment by Namitha-23** [comment]
The PR is linked to https://github.com/MicrosoftDocs/msteams-docs/issues/8600.

**Comment by Namitha-23** [comment]
Hi @yuezk, request you to please review and approve the PR.

**Review by yuezk — APPROVED** [review]
Looks good.

**Review by Wajeed-msft — APPROVED** [review]

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-code.md](https://github.com/MicrosoftDocs/msteams-docs/blob/627c567204421466f92a937dd1ed571aa80b3515/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-code.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6e6cb80-bee7-4e1a-984c-450d38811718) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
