### PR TITLE
[Doc Improvement][FAQ section updates]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/coversational-ai-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/753b1c0f6e663342c54527d472adb32eab249de1/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fcoversational-ai-faq.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20977237-82f1-4c5f-9d1f-84d3097cdd56) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/753b1c0f6e663342c54527d472adb32eab249de1/msteams-platform%2Ftoolkit%2Ffaq.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f1228cb-c77b-4a08-8e25-473990c49319) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/coversational-ai-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c801b29100028eedd7c50d3d7fb691deb5003cae/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fcoversational-ai-faq.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d0e44e3-cae6-4f94-ac6a-09a47a28950f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/faqs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c801b29100028eedd7c50d3d7fb691deb5003cae/msteams-platform%2Fresources%2Ffaqs.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c48628b2-93ad-445b-b2ed-c7b6688fd345) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c801b29100028eedd7c50d3d7fb691deb5003cae/msteams-platform%2Fteams-faq.md) | 91 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1269dbf5-539a-4d41-a070-0b46cdb45630) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c801b29100028eedd7c50d3d7fb691deb5003cae/msteams-platform%2Ftoolkit%2Ffaq.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85a2e957-28d6-4710-baaf-3dfe2841b89e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/coversational-ai-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/680ac2cd64a95b27edac9e48756f3728e70a8170/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fcoversational-ai-faq.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ae17e77-b0b5-4db9-87e9-798cf512fc3c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/faqs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/680ac2cd64a95b27edac9e48756f3728e70a8170/msteams-platform%2Fresources%2Ffaqs.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa911c17-3c44-4e61-ae82-650b4567a352) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/680ac2cd64a95b27edac9e48756f3728e70a8170/msteams-platform%2Fteams-faq.md) | 91 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b4605f4-b99e-4058-817a-21851b476c48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/680ac2cd64a95b27edac9e48756f3728e70a8170/msteams-platform%2Ftoolkit%2Ffaq.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/842f71b2-3db2-4e62-b55d-c2eb0c92d12a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/coversational-ai-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b8c9220c764899fc2f01f2d641ed02b19988c41/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fcoversational-ai-faq.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5344ff17-86c1-4039-8752-369dca58743e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/faqs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b8c9220c764899fc2f01f2d641ed02b19988c41/msteams-platform%2Fresources%2Ffaqs.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95afe0b1-6347-42a4-b65b-68bdf4550a49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b8c9220c764899fc2f01f2d641ed02b19988c41/msteams-platform%2Fresources%2Fremoving-tab-margins.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7720f08-dffe-4d94-b7ad-c8743017ab46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b8c9220c764899fc2f01f2d641ed02b19988c41/msteams-platform%2Fteams-faq.md) | 91 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11936b79-e984-4b13-811b-d86eebeac9bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b8c9220c764899fc2f01f2d641ed02b19988c41/msteams-platform%2Ftoolkit%2Ffaq.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23f1c0f9-f842-4f00-8454-c82bdc74d20a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/coversational-ai-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d200b8d747ba8e2df6359a3fff650480164a9d5c/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fcoversational-ai-faq.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/310a5730-c77f-4d7d-8359-b87fb8bd075b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/faqs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d200b8d747ba8e2df6359a3fff650480164a9d5c/msteams-platform%2Fresources%2Ffaqs.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6188ba92-d2e1-4160-a4ad-e1b152e65534) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d200b8d747ba8e2df6359a3fff650480164a9d5c/msteams-platform%2Fresources%2Fremoving-tab-margins.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a07e502e-371c-404e-89d9-466cc2096afa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d200b8d747ba8e2df6359a3fff650480164a9d5c/msteams-platform%2Fteams-faq.md) | 91 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1b7a448-2d39-4905-acfe-6ccecb368995) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d200b8d747ba8e2df6359a3fff650480164a9d5c/msteams-platform%2Ftoolkit%2Ffaq.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40c2e66e-d1eb-461a-bf3a-eaa38734ce35) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/coversational-ai-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ceb18ddb76c24555715468770f305afe474f4dca/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fcoversational-ai-faq.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bcfc3132-ba9b-4a1a-9c19-dace254e044b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/faqs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ceb18ddb76c24555715468770f305afe474f4dca/msteams-platform%2Fresources%2Ffaqs.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fde28252-67dd-49a9-97b2-f7d84197e142) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ceb18ddb76c24555715468770f305afe474f4dca/msteams-platform%2Fresources%2Fremoving-tab-margins.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0da8d3e9-f1f7-4e0a-93f8-37fed73ee0d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ceb18ddb76c24555715468770f305afe474f4dca/msteams-platform%2Fteams-faq.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6d6d031-49d8-46a9-837e-a851d0d9f3fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ceb18ddb76c24555715468770f305afe474f4dca/msteams-platform%2Ftoolkit%2Ffaq.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/195fb5a1-ec1c-4e1b-a53e-6e4c1fbe939d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/coversational-ai-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55853d92d7243b96e4138db36b75206f14a99969/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fcoversational-ai-faq.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3534282c-5abf-46f9-aa6c-cdaa0e314a65) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55853d92d7243b96e4138db36b75206f14a99969/msteams-platform%2Fresources%2Fremoving-tab-margins.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94576b33-d78c-4877-bab8-7de8eb88042f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55853d92d7243b96e4138db36b75206f14a99969/msteams-platform%2Fteams-faq.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb1e97a6-7e9b-48ae-9451-c6824049efd8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55853d92d7243b96e4138db36b75206f14a99969/msteams-platform%2Ftoolkit%2Ffaq.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf4d91ae-d881-460e-beea-91ca528930c5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/coversational-ai-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2ffba20d98dc2d81f41d1ccfec5b20719edbafc/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fcoversational-ai-faq.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1541dbc0-0317-4897-90c7-fef2d1d825dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/faqs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2ffba20d98dc2d81f41d1ccfec5b20719edbafc/msteams-platform%2Fresources%2Ffaqs.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f685d751-4256-4671-bd12-b39b58d4d73f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2ffba20d98dc2d81f41d1ccfec5b20719edbafc/msteams-platform%2Fresources%2Fremoving-tab-margins.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51b41dd3-fdda-4bc4-aff5-ad7e9deb44cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2ffba20d98dc2d81f41d1ccfec5b20719edbafc/msteams-platform%2Fteams-faq.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c76f3a2e-ca7f-4c94-ac32-cd64ed00b6e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2ffba20d98dc2d81f41d1ccfec5b20719edbafc/msteams-platform%2Ftoolkit%2Ffaq.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af2390c8-8950-4330-8dc1-eb64bbc2c5b4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/coversational-ai-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e00c863731a46090725749e5bab6686833b7fcb/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fcoversational-ai-faq.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c98eee2a-dbf3-45cd-92ae-a6abdf6d5bc8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/faqs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e00c863731a46090725749e5bab6686833b7fcb/msteams-platform%2Fresources%2Ffaqs.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f34368b-b68b-46f9-949f-bd7c6f329781) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e00c863731a46090725749e5bab6686833b7fcb/msteams-platform%2Fresources%2Fremoving-tab-margins.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8dfa1e9f-af90-42ef-91e6-14943d319696) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e00c863731a46090725749e5bab6686833b7fcb/msteams-platform%2Fteams-faq.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76d13eff-e9cf-4d89-b0f4-df45577aeaad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e00c863731a46090725749e5bab6686833b7fcb/msteams-platform%2Ftoolkit%2Ffaq.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9ea9975-adff-4c84-910b-195fe6dc204c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/coversational-ai-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be0e35db5cda5d1eced69631dda0cd3e780ab451/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fcoversational-ai-faq.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28c9640f-663d-444b-84cf-3204b04b3dff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/faqs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be0e35db5cda5d1eced69631dda0cd3e780ab451/msteams-platform%2Fresources%2Ffaqs.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94e059e4-3df6-4a89-a5fd-acc2656e3791) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be0e35db5cda5d1eced69631dda0cd3e780ab451/msteams-platform%2Fresources%2Fremoving-tab-margins.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff6c035c-9baa-4f45-abd8-9953ce91f300) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be0e35db5cda5d1eced69631dda0cd3e780ab451/msteams-platform%2Fteams-faq.md) | 91 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad8125e1-d7bd-47e6-8cd2-650150a20a1a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be0e35db5cda5d1eced69631dda0cd3e780ab451/msteams-platform%2Ftoolkit%2Ffaq.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/590dc33d-1cf6-4445-8d3a-4a080f912e4c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/coversational-ai-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51f5203e7b8bd12835cb671883f651246ab686db/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fcoversational-ai-faq.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2120a7a-a1ab-49c7-8125-b207bd3309e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/faqs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51f5203e7b8bd12835cb671883f651246ab686db/msteams-platform%2Fresources%2Ffaqs.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2470a1ac-c44c-4639-b99c-cc529ce32cef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51f5203e7b8bd12835cb671883f651246ab686db/msteams-platform%2Fresources%2Fremoving-tab-margins.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d82fc35b-c7de-4ca4-9eeb-b061527bff95) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51f5203e7b8bd12835cb671883f651246ab686db/msteams-platform%2Fteams-faq.md) | 91 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4413a5d5-bc56-47bb-8e7f-063a4cca964a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51f5203e7b8bd12835cb671883f651246ab686db/msteams-platform%2Ftoolkit%2Ffaq.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/155042c0-a23c-4b93-8704-83fdaa097a32) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
