### PR TITLE
[Doc improvement][SEO14 meta title update][3881915]

### PR DESCRIPTION
**Pull request by v-ramyas5**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1d58ee19784d13d1671e9e7b5cfa1a265165baca/msteams-platform%2Findex.yml) | 80 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4faa19f8-9bc2-4169-9818-91d45ffb04f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/tools-prerequisites-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d58ee19784d13d1671e9e7b5cfa1a265165baca/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ftools-prerequisites-v4.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ecb6d48-cf3e-4d1f-a619-a29f07536075) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d58ee19784d13d1671e9e7b5cfa1a265165baca/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05f7b3e0-8404-4362-8e9a-e65868336b0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-existing-aad-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d58ee19784d13d1671e9e7b5cfa1a265165baca/msteams-platform%2Ftoolkit%2Fuse-existing-aad-app.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19d00071-f221-4ce8-9ab5-52f704ad7fdc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d58ee19784d13d1671e9e7b5cfa1a265165baca/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c498c41b-cd85-4538-9589-e2ca827772cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1d58ee19784d13d1671e9e7b5cfa1a265165baca/msteams-platform%2Fwhats-new.md) | 90 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b08e008e-32ce-4de2-bb62-fdeda146e9b1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/447725047da965fda01f40972d1a54aee85de76c/msteams-platform%2Findex.yml) | 80 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11b40f52-80f0-4d23-8426-f5dce74738ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/447725047da965fda01f40972d1a54aee85de76c/msteams-platform%2Fmstdd-landing.yml) | 83 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c6cba47-8a8e-43a1-8e90-7301fcb743a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/tools-prerequisites-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/447725047da965fda01f40972d1a54aee85de76c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ftools-prerequisites-v4.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1db784a2-7e8a-4d2b-8186-0e57f941c51b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/447725047da965fda01f40972d1a54aee85de76c/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a55069ff-5039-4ef9-b851-4d29957914f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-existing-aad-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/447725047da965fda01f40972d1a54aee85de76c/msteams-platform%2Ftoolkit%2Fuse-existing-aad-app.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fcd58e7-8324-4fe0-9482-3735ae0523e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/447725047da965fda01f40972d1a54aee85de76c/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/abb08766-4432-4912-a4df-6eaf6e8c1bf1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/447725047da965fda01f40972d1a54aee85de76c/msteams-platform%2Fwhats-new.md) | 90 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52188929-e987-4db2-9395-8f027805fabd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ee19e4ca98e1e9f4fea2b5a183026eb4be8436e2/msteams-platform%2Findex.yml) | 80 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e347c135-d50f-458a-ba16-30486d8cccc8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ee19e4ca98e1e9f4fea2b5a183026eb4be8436e2/msteams-platform%2Fmstdd-landing.yml) | 83 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14fc1e36-aa77-4f2e-8880-3f531977e327) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/tools-prerequisites-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee19e4ca98e1e9f4fea2b5a183026eb4be8436e2/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ftools-prerequisites-v4.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/298b4eef-1674-4194-9968-eaf86435bd6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee19e4ca98e1e9f4fea2b5a183026eb4be8436e2/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/888549b6-e184-466e-81f4-9de3a8e35c69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-existing-aad-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee19e4ca98e1e9f4fea2b5a183026eb4be8436e2/msteams-platform%2Ftoolkit%2Fuse-existing-aad-app.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad65fec3-595c-495d-9e5c-c88e2a45caef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee19e4ca98e1e9f4fea2b5a183026eb4be8436e2/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7cd24fe-8c31-481e-99b1-13f7429c4b54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee19e4ca98e1e9f4fea2b5a183026eb4be8436e2/msteams-platform%2Fwhats-new.md) | 90 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/325bbab6-850e-4cbb-aeb0-361cae492b36) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/12b28289bd1c9efcf8b2d126a9ef33d4de5086f8/msteams-platform%2Findex.yml) | 80 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/446f0c5d-8bfd-46c9-9a9c-15e4cd570f30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/tools-prerequisites-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12b28289bd1c9efcf8b2d126a9ef33d4de5086f8/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ftools-prerequisites-v4.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/794f694f-a225-4b0d-93cc-c3843254fefa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12b28289bd1c9efcf8b2d126a9ef33d4de5086f8/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78d66559-0a20-46b1-9559-a64f2ba3bad1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-existing-aad-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12b28289bd1c9efcf8b2d126a9ef33d4de5086f8/msteams-platform%2Ftoolkit%2Fuse-existing-aad-app.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea9eac45-215e-49ce-a06b-a8667ba0bdb3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12b28289bd1c9efcf8b2d126a9ef33d4de5086f8/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dce3fb6c-746f-42e5-9c15-8236653a4ece) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12b28289bd1c9efcf8b2d126a9ef33d4de5086f8/msteams-platform%2Fwhats-new.md) | 90 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad032595-d551-4593-bc6e-07fcb3453f77) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/27ab77026e9a4481c54732566c71af04f9f897ab/msteams-platform%2Findex.yml) | 80 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9f75f09-94b9-47aa-9f7f-bc7f1e6d79d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/tools-prerequisites-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27ab77026e9a4481c54732566c71af04f9f897ab/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ftools-prerequisites-v4.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4adbc615-3ada-4003-b692-4e78557c7779) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27ab77026e9a4481c54732566c71af04f9f897ab/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60faefcd-7bc7-47a8-bdf8-8b5032d8d9ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-existing-aad-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27ab77026e9a4481c54732566c71af04f9f897ab/msteams-platform%2Ftoolkit%2Fuse-existing-aad-app.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80dfb272-52b6-48ce-a62d-35bb134add54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27ab77026e9a4481c54732566c71af04f9f897ab/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37b89678-f462-45d2-a154-afb71b501ec6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27ab77026e9a4481c54732566c71af04f9f897ab/msteams-platform%2Fwhats-new.md) | 90 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53a51c05-3e3e-495a-81a9-4ce933982d3e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d4343ac34c79bd59feb54b452f0c9c92d6d9e0f8/msteams-platform%2Findex.yml) | 80 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b671f45-b17a-4d5a-9ea0-0e7f42dee02f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/tools-prerequisites-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4343ac34c79bd59feb54b452f0c9c92d6d9e0f8/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ftools-prerequisites-v4.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54563ba1-75ad-434b-b951-806e27e4ad4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4343ac34c79bd59feb54b452f0c9c92d6d9e0f8/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/502ee202-2777-4dd8-ae08-f23e793d8695) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-existing-aad-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4343ac34c79bd59feb54b452f0c9c92d6d9e0f8/msteams-platform%2Ftoolkit%2Fuse-existing-aad-app.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26a7be08-ef25-45ff-b672-b1570b322c51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4343ac34c79bd59feb54b452f0c9c92d6d9e0f8/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aca43483-997d-468f-8fa0-1dd870534e2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4343ac34c79bd59feb54b452f0c9c92d6d9e0f8/msteams-platform%2Fwhats-new.md) | 90 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6cf4199c-130f-4c9a-9da4-430b5bf52762) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/72cdb5426419b0020d03b52722a028dd4980bd61/msteams-platform%2Findex.yml) | 80 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/306c94dd-74d8-48e2-89f9-5c9c358b2a45) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/tools-prerequisites-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72cdb5426419b0020d03b52722a028dd4980bd61/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ftools-prerequisites-v4.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e4ee421-492d-4f99-81f9-7713c75f54b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72cdb5426419b0020d03b52722a028dd4980bd61/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1a27364-17c6-4de8-833b-48b88aedd894) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-existing-aad-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72cdb5426419b0020d03b52722a028dd4980bd61/msteams-platform%2Ftoolkit%2Fuse-existing-aad-app.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57619eae-feba-4506-aef4-ead81ad80dd0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72cdb5426419b0020d03b52722a028dd4980bd61/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78a51d1a-d9d5-401b-922f-2f44d009dd6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72cdb5426419b0020d03b52722a028dd4980bd61/msteams-platform%2Fwhats-new.md) | 90 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4537af6c-9cb6-4cfb-b09a-34805284dd72) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b9bd81ba1e9499852ef372b9dbf61c20bccadae/msteams-platform%2Findex.yml) | 80 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79b03ef0-e082-4347-9114-9030c59f6bf2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/tools-prerequisites-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b9bd81ba1e9499852ef372b9dbf61c20bccadae/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ftools-prerequisites-v4.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9bd9cb70-8c39-4909-92b3-ffd0301b7b64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b9bd81ba1e9499852ef372b9dbf61c20bccadae/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79f95666-99fe-4eb3-8fd8-df543cbc89f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-existing-aad-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b9bd81ba1e9499852ef372b9dbf61c20bccadae/msteams-platform%2Ftoolkit%2Fuse-existing-aad-app.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0708490-7e0b-4960-abfb-ab317584c82b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b9bd81ba1e9499852ef372b9dbf61c20bccadae/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3088ebcd-d337-4253-9f73-2e897f39ff28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b9bd81ba1e9499852ef372b9dbf61c20bccadae/msteams-platform%2Fwhats-new.md) | 90 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0ccf4b6-707e-46dd-a6cc-678306051f01) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
