### PR TITLE
Teams Dev hub updates

### PR DESCRIPTION
**Pull request by lindalu-MSFT**
added tech community tile
added Teams admin help tile
updated art to match Office Dev design
added alt text
minor edits

### CODE REVIEW

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/index.md](https://github.com/lindalu-MSFT/msteams-docs/blob/patch-3/msteams-platform/index.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Findex.md)
[msteams-platform/includes/landing-page.html](https://github.com/lindalu-MSFT/msteams-docs/blob/patch-3/msteams-platform/includes/landing-page.html) | :white_check_mark:Succeeded | |

<a name="msteams-platform%2Findex.md"></a>
### [msteams-platform/index.md](https://github.com/lindalu-MSFT/msteams-docs/blob/patch-3/msteams-platform/index.md)
 - **Line 0**: **[Warning]** Invalid file link:(~/assets/images/landing-page/MSTeams-Dev-getstarted400x140.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/resources/design/overview).
 - **Line 0**: **[Warning]** Invalid file link:(~/assets/images/landing-page/MSTeams-Dev-build-400x140.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/assets/images/landing-page/MSTeams-Dev-client.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/javascript/api/overview/msteams-client).
 - **Line 0**: **[Warning]** Invalid file link:(~/concepts/apps/apps-overview).
 - **Line 0**: **[Warning]** Invalid file link:(~/overview).
 - **Line 0**: **[Warning]** Invalid file link:(~/assets/images/landing-page/MSTeams-Dev-intro-400x140.svg).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201809141307172474-241%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vf80r5yDGOaHRg5YXnDzs%2FNdRmoSdBjaQOuYkVkiaaE%3D&st=2018-09-14T13%3A03%3A39Z&se=2018-10-15T13%3A08%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@LolaJacobsen @samanro Please upload the 4 new MSTeams-Dev SVG files (see warnings) to assets/images/landing-page. Thanks! lindalu

**Comment by lindalu-MSFT** [comment]
@billbliss Thanks, I had asked someone to upload these files but since you granted me perms, I just added them myself. I am not sure if the old assets are being used because there is another version of the landing page out there. I'm leaving the files there for now and will verify.

**Comment by billbliss** [comment]
Closing in favor of PR #242 which includes this

**Pull request closed without merging**
