### PR TITLE
[Doc Improvement][Resources revise see also section]

### PR DESCRIPTION
**Pull request by v-vvchaganti**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b761eb41f7e8bbb7d919868357af8b7afa8ebd8e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e35da145-c5d5-48b2-b40d-91b2def2eb47) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0eb75f9e36225e69385513e866b6bbc8932a4190/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccdbe873-7990-49a3-b1a8-3c300038bca7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0eb75f9e36225e69385513e866b6bbc8932a4190/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e668986-2bee-488f-8fe1-fdf3ec7cc09b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0eb75f9e36225e69385513e866b6bbc8932a4190/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5dc2808-252a-4d3f-afad-2b419b9e9ac8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64c80c894de8509f63ec4aca3aad310800bf51fa/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd3228d9-b9c6-4176-9fb2-e4dd0ac89d94) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64c80c894de8509f63ec4aca3aad310800bf51fa/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d03fd2a6-4725-44b5-b0ef-e0ea8d4af2cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64c80c894de8509f63ec4aca3aad310800bf51fa/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11df95d5-b33b-4ebc-9c1c-3ea1d7e9b568) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e099e0afaf1cc8a42c70b65fea634508af6c47c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87ee32bf-eecb-4c0c-af67-80b0f8305f0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e099e0afaf1cc8a42c70b65fea634508af6c47c/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20fd4df0-4bdb-4056-b3ed-ca463d88c0c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e099e0afaf1cc8a42c70b65fea634508af6c47c/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22178f00-1e92-432d-8ea7-a304eccb8302) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e099e0afaf1cc8a42c70b65fea634508af6c47c/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/565f922c-70f0-4c13-b7e7-111fa87c6f69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e099e0afaf1cc8a42c70b65fea634508af6c47c/msteams-platform%2Fresources%2Ftroubleshoot.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/526dd6b2-a57f-4288-bfe1-7dd0d5ee4285) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0b36b7c2a6d698e980654de1d65b8dfb1e60324/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3928c89-7fad-49e7-b710-e2f3e4ae4bec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0b36b7c2a6d698e980654de1d65b8dfb1e60324/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cce11d8-e807-400a-a4ed-016d888562d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0b36b7c2a6d698e980654de1d65b8dfb1e60324/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4bba2b6-15d0-4a69-a01c-f80e1149f8c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0b36b7c2a6d698e980654de1d65b8dfb1e60324/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e550cc90-4304-4c32-9404-6837139766c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0b36b7c2a6d698e980654de1d65b8dfb1e60324/msteams-platform%2Fresources%2Ftroubleshoot.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a00ee9e-0a60-4f75-924b-bce81e7e5e2d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/113a7def7fad55ebff3fea4bd8d9c1e6ee32617c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2352e08b-53e7-4025-8862-c208ba25746d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/113a7def7fad55ebff3fea4bd8d9c1e6ee32617c/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95f90965-b8c1-4a6a-941d-f53c18a4aa6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/113a7def7fad55ebff3fea4bd8d9c1e6ee32617c/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1daebe4d-85fa-443b-b83d-c9d0a3649ad1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/113a7def7fad55ebff3fea4bd8d9c1e6ee32617c/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acf8a3b0-4d74-4bcd-969c-672900703d2c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/113a7def7fad55ebff3fea4bd8d9c1e6ee32617c/msteams-platform%2Fresources%2Ftroubleshoot.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4670b45d-fffc-436e-91f7-60d164604ed3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-vpaliwal** [comment]
image

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5531061f0a3e522e3fe326b7d8a63974719a877/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e277df70-86b5-44a9-b1f8-c35b4891d48c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5531061f0a3e522e3fe326b7d8a63974719a877/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f66b2336-661c-4654-aaa8-6f68e9a940cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5531061f0a3e522e3fe326b7d8a63974719a877/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eec908b8-c12b-4f72-ad55-b1902b1400c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5531061f0a3e522e3fe326b7d8a63974719a877/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f62850b-fff3-4858-8de0-d3cb3452013c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5531061f0a3e522e3fe326b7d8a63974719a877/msteams-platform%2Fresources%2Ftroubleshoot.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b736f5f-62f5-41b3-ad5d-33589b70a733) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]

**Pull request merged**
