### PR TITLE
[Doc Improvement][Update Invoke Task modules SBS Guide][3264915]

### PR DESCRIPTION
**Pull request by v-vanv**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d1f8c7fd0285f2e041e78dd563b9f73819f72491/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 85 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f87b355-70d3-452f-8a57-08d830a6e399) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/96eefc312f8cb08f4051cd7b5ef566f7a1feb760/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 85 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a9422ec-415b-4cc7-8b70-5d796c16d024) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9f2a552d684f4c726615bd409647cc481459f4c4/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 85 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3f28422-7597-45e3-bef8-ae9720276900) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c118dae3e601135c35517943bdcb8cc3be107230/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 85 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30f4ea47-2020-4dd4-a16b-79b8384d0527) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c27438931265f95f98a89ac941d28606aa1dd5cd/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 85 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03af602f-3e3f-4018-b7b8-a6888f58b079) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8a61a0156e675cdd6fe1d17a8ce5986af9d8bfcb/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 85 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd6d4048-6f99-4d13-945d-5681f48c0514) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a5ddfee6543eb5e171f4d1030d050b6e08f02e24/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 85 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/724b56b9-f505-4cca-a0a6-9a2b584f9276) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/add-teams-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/647c8b10d19f17f14f2f767c4c9334e87d5533a7/msteams-platform%2Fincludes%2Fget-started%2Fadd-teams-channel.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80a1e186-6caf-4f32-b14a-1d047bef106c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-add-scope.md](https://github.com/MicrosoftDocs/msteams-docs/blob/647c8b10d19f17f14f2f767c4c9334e87d5533a7/msteams-platform%2Fincludes%2Fget-started%2Fazure-add-scope.md) | 94 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e31e331e-e9f9-4050-9cd0-e238033402f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-app-registration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/647c8b10d19f17f14f2f767c4c9334e87d5533a7/msteams-platform%2Fincludes%2Fget-started%2Fazure-app-registration.md) | 92 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25416125-b94a-4669-b53f-af5cf03aff9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-bot-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/647c8b10d19f17f14f2f767c4c9334e87d5533a7/msteams-platform%2Fincludes%2Fget-started%2Fazure-bot-resource.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d273ff82-3773-47d9-97a8-184bf6d49fc1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/clone-repository.md](https://github.com/MicrosoftDocs/msteams-docs/blob/647c8b10d19f17f14f2f767c4c9334e87d5533a7/msteams-platform%2Fincludes%2Fget-started%2Fclone-repository.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bea242cf-9c94-49ba-975b-5235995312fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/create-client-secret.md](https://github.com/MicrosoftDocs/msteams-docs/blob/647c8b10d19f17f14f2f767c4c9334e87d5533a7/msteams-platform%2Fincludes%2Fget-started%2Fcreate-client-secret.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e66be2d-7a85-4541-a6d7-799e58dd1a83) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/dev-tunnel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/647c8b10d19f17f14f2f767c4c9334e87d5533a7/msteams-platform%2Fincludes%2Fget-started%2Fdev-tunnel.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e1db678-ec17-4236-970e-09c50afc49cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/ngrok-tunnel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/647c8b10d19f17f14f2f767c4c9334e87d5533a7/msteams-platform%2Fincludes%2Fget-started%2Fngrok-tunnel.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04a4c452-8d54-4bab-b573-e9dd26b5d3ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/647c8b10d19f17f14f2f767c4c9334e87d5533a7/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 86 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cdfb680-b930-4cd2-9d84-2569515b4aae) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/add-teams-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/33b906332dfd029e550fd7248a410d6aff6f179e/msteams-platform%2Fincludes%2Fget-started%2Fadd-teams-channel.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7db86a6a-5659-4669-b9ce-5d932541ac81) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-add-scope.md](https://github.com/MicrosoftDocs/msteams-docs/blob/33b906332dfd029e550fd7248a410d6aff6f179e/msteams-platform%2Fincludes%2Fget-started%2Fazure-add-scope.md) | 94 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a5777f9-0449-41b4-bf5d-6ebfb4c25413) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-app-registration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/33b906332dfd029e550fd7248a410d6aff6f179e/msteams-platform%2Fincludes%2Fget-started%2Fazure-app-registration.md) | 92 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e7c23bf-52b5-4865-9e40-c375437b4753) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-bot-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/33b906332dfd029e550fd7248a410d6aff6f179e/msteams-platform%2Fincludes%2Fget-started%2Fazure-bot-resource.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2af62582-8278-4ed2-996a-ced2ce53c891) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/clone-repository.md](https://github.com/MicrosoftDocs/msteams-docs/blob/33b906332dfd029e550fd7248a410d6aff6f179e/msteams-platform%2Fincludes%2Fget-started%2Fclone-repository.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e710a0d2-5730-441f-850d-24b6c003875c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/create-client-secret.md](https://github.com/MicrosoftDocs/msteams-docs/blob/33b906332dfd029e550fd7248a410d6aff6f179e/msteams-platform%2Fincludes%2Fget-started%2Fcreate-client-secret.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6aaffce5-2cff-4f6e-b6ac-f7a6df56b073) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/dev-tunnel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/33b906332dfd029e550fd7248a410d6aff6f179e/msteams-platform%2Fincludes%2Fget-started%2Fdev-tunnel.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df17fabc-d9af-4644-be31-0f71e4776db0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/ngrok-tunnel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/33b906332dfd029e550fd7248a410d6aff6f179e/msteams-platform%2Fincludes%2Fget-started%2Fngrok-tunnel.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36b8f9a2-9ab1-42a8-8377-8cf8346ca62f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33b906332dfd029e550fd7248a410d6aff6f179e/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 86 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a28310e7-9048-41b7-8639-ef8cecb2038e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/add-teams-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b76f618ca88725a366cec2c1ef911466f83918f1/msteams-platform%2Fincludes%2Fget-started%2Fadd-teams-channel.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9b65b3e-754b-4297-91eb-029a457d3eda) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b76f618ca88725a366cec2c1ef911466f83918f1/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 86 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8e5fbab-1287-4f4d-a174-1831952e1e1b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a69d097471be8263dea0818efdb9160ffc5bc94a/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/013717fd-de99-48bc-8a66-4928a9635b20) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bcff8bc19e3bc414c7974f3cf27e5d80c1c40cb6/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/707ef956-677e-4383-8f64-0c1088654ccf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aaa4ab3b4a3ab6cbfc522a23a4948b6360ee6d45/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a1b8f93-d627-4bea-bcf8-2f8030c4df3e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/66fe08d9b8635838834192691b4b3cd2213f85fa/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ab823f4-9ebf-4f35-9fa2-af55821b577b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/81742dd8ac4552136f3cb6b603b9f725df6389d6/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 86 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b92a57b-91c8-4805-85cf-245cd2737d16) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/af5a5357fcd052f0774399fc556249a466584075/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 86 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c595610f-bb90-4270-98c5-aeac8278e6f0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5b929d1a95ea46f94eb0a16e5f152b86ffea6458/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 86 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/086d0a43-5f3b-406d-9cc3-178771991527) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fc473b147983e37525898afff2158a6fd1badffb/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 86 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/551091c6-4d4e-4d02-b0b4-29af428bf8d6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4e6d99f59097d6483e995d44a307cf09e1ca7575/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 86 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5c0110f-de8a-420d-acbd-a17c1f23b92b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/89999106a0555bad25ac8501f8c5fbc83c252c9d/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 86 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6ad116b-6703-419a-a4b1-6b859a40cdd6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
