### PR TITLE
[Doc Improvement][Update global comments in SBS guides][3196514]

### PR DESCRIPTION
**Pull request by v-vanv**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2481e8349b567204601579cbc6ff2ff694a85849/msteams-platform%2Fsbs-calling-and-meeting.yml) | 92 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b2b0510-7824-49be-a194-8cbe4246fc20) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d0fe1d1188fc0d5272443471a674f34965207cc6/msteams-platform%2Fsbs-calling-and-meeting.yml) | 92 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0222762-a810-48b4-95d4-c0cb71d10209) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f5853cc4d71996ef31b85f50a76355450067a593/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c40cc2e7-5977-4783-86c0-4661ac97376c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7bde34bc1de591def42b325fa1ee11c10b4be17e/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/850762fe-4109-4210-a359-f8c433ca3e53) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91c0c881319063f7da9be639eae95d9355769a57/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77ca9cf2-1008-4710-9af4-f518e8514e6e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a6935b1e890577a942320a28910f2527f6c54e78/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a7dd8ed-dd59-45f2-b9a3-d53aa4b6a36d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a6935b1e890577a942320a28910f2527f6c54e78/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 89 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da3f42d1-30b6-4e17-915e-e609e629258c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f34635f5a345f2565bff1be4ac33c3f0c2e45d12/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0a5ebcb-d34d-4e99-9c88-1095339c6c17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f34635f5a345f2565bff1be4ac33c3f0c2e45d12/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 89 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e597116-0480-4d1a-8ca7-03b12b8c89c8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b206d1f0dcff8ba08add89d005547a42a48b5b7/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af2e18f6-6643-4d17-9bcb-fe15b8696165) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b206d1f0dcff8ba08add89d005547a42a48b5b7/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 89 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3cc77ea-5cae-4fe8-819e-aaf5f57c2d18) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3ccf1d841c7485ca433ba9ee65014eaaad3d627a/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29225d98-5857-4f2e-8016-128c50370dab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3ccf1d841c7485ca433ba9ee65014eaaad3d627a/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5aa03466-15be-4c39-901c-9aa81d85a2ea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/054e82273006d3bf68b1744d63f8e9ba55df1fab/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e15b27c8-9acf-4b1f-99ad-efb95dfce40d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/054e82273006d3bf68b1744d63f8e9ba55df1fab/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a17f82f6-92e9-44e9-86a9-c55a28465ec7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c1bc03804313d2db5ca62287c14789413fb50147/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7e4fd48-a231-4f28-b1e2-0c8d88efa92b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c1bc03804313d2db5ca62287c14789413fb50147/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3717203d-079a-4d16-b753-a729425cf80e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a0c4b3cd99a66f59eecd335f134f98bb7aec67dc/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7516ff9-1ef5-47f9-84cc-d70cfe336e95) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d7e90b9aaa9b3ab6177c3aa6606110024e7515a7/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d149cc8d-32b1-4500-b39e-7a3db3a54336) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba0d3414f1ed6e37408d974e8ff1c9b9fd9740bc/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3c0a5e4-c742-4538-a909-18eee8541f1f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6abc858fa91ae4e4869e2bdfbe70bdc21dba0491/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6924217-80b3-4f3a-90ad-09115f11ac14) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ed75bea1dfb6da8bf7f6c4e46c127ffe5ac9b92d/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19ee2d2a-836b-46f8-b756-2b785345688b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8577e1dee2e619259a01a51b91a2203bed39bd15/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0273d9c-fe5f-47ac-b3ab-7c14739bb292) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8577e1dee2e619259a01a51b91a2203bed39bd15/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d914c1f9-6158-4d7f-9282-6a2600269675) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/68aa5867dcada17c7cdd4a9b2e18587d0fce3145/msteams-platform%2Fsbs-calling-and-meeting.yml) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0026960-ba0a-4ce7-ab7e-3fa42adc2bd9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
