### PR TITLE
[Doc Improvement][SBS prerequisites update][3761875]

### PR DESCRIPTION
**Pull request by v-ganr**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/qsg-bot-configuration-experience.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5682fecf9018fd8724e3b92636f52065956d4504/msteams-platform%2Fqsg-bot-configuration-experience.yml) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78b19def-6894-4f6b-b25f-0ce6264da7a4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/qsg-bot-configuration-experience.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aba4e27a3892b778ffb5a847ea905cce41b6c97c/msteams-platform%2Fqsg-bot-configuration-experience.yml) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1bc7c14-aa0c-4896-abe3-b4a39d01ff80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aba4e27a3892b778ffb5a847ea905cce41b6c97c/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 72 | 123 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f95fc69-4593-42d5-a03d-a9e312dec06f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-me-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aba4e27a3892b778ffb5a847ea905cce41b6c97c/msteams-platform%2Fsbs-api-me-ttk.yml) | 81 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00be0d10-7fc1-49fe-9ad1-65a66e5f4002) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aba4e27a3892b778ffb5a847ea905cce41b6c97c/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 81 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1c3a16c-53d4-428c-aa0c-7a1cb5c4af91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aba4e27a3892b778ffb5a847ea905cce41b6c97c/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 80 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f580793b-8227-41ca-9c95-c1e1b62538bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aba4e27a3892b778ffb5a847ea905cce41b6c97c/msteams-platform%2Fsbs-bots-with-sso.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd1bcca4-8a99-4db9-b5a7-be63b77a000c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aba4e27a3892b778ffb5a847ea905cce41b6c97c/msteams-platform%2Fsbs-calling-and-meeting.yml) | 88 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89c257a2-b161-44ed-bf43-52a90a4c209c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aba4e27a3892b778ffb5a847ea905cce41b6c97c/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 75 | 79 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e55c9c78-e9a2-423c-8c0c-f1479674b9ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aba4e27a3892b778ffb5a847ea905cce41b6c97c/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ae1ecd6-f543-4d9a-85e3-eb511cce961b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/qsg-bot-configuration-experience.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b99de44b0b6d0917d807d96f9e230a95a7630885/msteams-platform%2Fqsg-bot-configuration-experience.yml) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76134ed2-f575-4b55-86af-65263a785cbb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b99de44b0b6d0917d807d96f9e230a95a7630885/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 72 | 123 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b34233be-9913-4e55-a1ae-afbd9d346172) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-me-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b99de44b0b6d0917d807d96f9e230a95a7630885/msteams-platform%2Fsbs-api-me-ttk.yml) | 81 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e995387-ec33-46c2-ae25-87b4c1899c9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b99de44b0b6d0917d807d96f9e230a95a7630885/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 81 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/adb9bc47-d3bf-4771-a6b8-1d07b5016a89) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b99de44b0b6d0917d807d96f9e230a95a7630885/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 80 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/833165ae-4763-4107-b39f-6f2e02a30515) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b99de44b0b6d0917d807d96f9e230a95a7630885/msteams-platform%2Fsbs-bots-with-sso.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e78e8219-3993-4aa0-92e5-f598740e300d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b99de44b0b6d0917d807d96f9e230a95a7630885/msteams-platform%2Fsbs-calling-and-meeting.yml) | 88 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c42e833-e582-44b3-8f8d-0c23ec6aecf3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b99de44b0b6d0917d807d96f9e230a95a7630885/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 75 | 79 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb6a8303-e263-4299-9e08-3995322f4a23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b99de44b0b6d0917d807d96f9e230a95a7630885/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc541a4b-4640-461b-b7d8-492e6b20fc93) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/qsg-bot-configuration-experience.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/78f277b96ca8dac314b165276117523008d4ec48/msteams-platform%2Fqsg-bot-configuration-experience.yml) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/347d5285-48ac-4618-830b-7e12f93b256b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-me-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/78f277b96ca8dac314b165276117523008d4ec48/msteams-platform%2Fsbs-api-me-ttk.yml) | 81 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/008106fb-f483-46f0-ab6e-321d5053ed58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/78f277b96ca8dac314b165276117523008d4ec48/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 81 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b31d720-6651-4ec3-b515-5f1dd4c42406) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/78f277b96ca8dac314b165276117523008d4ec48/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 80 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ba2c424-043a-4e13-bfdf-8c3479b9dd6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/78f277b96ca8dac314b165276117523008d4ec48/msteams-platform%2Fsbs-bots-with-sso.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fde5f6f0-01d0-4de9-bd46-ff6ca90b9376) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/78f277b96ca8dac314b165276117523008d4ec48/msteams-platform%2Fsbs-calling-and-meeting.yml) | 88 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2906ac87-4317-482d-8295-47b617532413) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/78f277b96ca8dac314b165276117523008d4ec48/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4abda572-40b4-4403-bc6f-05260442ff77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/78f277b96ca8dac314b165276117523008d4ec48/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 84 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f79c0dbb-5fb3-4919-b190-f5a15b804b4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/78f277b96ca8dac314b165276117523008d4ec48/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 84 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f9cc536-5791-4c26-bd8f-070330c8bc1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/78f277b96ca8dac314b165276117523008d4ec48/msteams-platform%2Fsbs-meeting-token-generator.yml) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cc3f685-ea1d-4334-b27c-9da78e62abfa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/78f277b96ca8dac314b165276117523008d4ec48/msteams-platform%2Fsbs-meetingextension-action.yml) | 81 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb15efbd-f3ae-45be-8516-e336b70853c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/78f277b96ca8dac314b165276117523008d4ec48/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ec52d15-79d4-4ffb-ab84-3b0c92e25698) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/qsg-bot-configuration-experience.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/700bf717d4e21fe47e23be424046de48aa0c312d/msteams-platform%2Fqsg-bot-configuration-experience.yml) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d16de143-6a5b-480f-935c-2e7825b2b4e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-me-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/700bf717d4e21fe47e23be424046de48aa0c312d/msteams-platform%2Fsbs-api-me-ttk.yml) | 81 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/032e895a-49b6-47ce-900f-3a7ceb75ebe6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/700bf717d4e21fe47e23be424046de48aa0c312d/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 81 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a0b07ee-f9a0-445c-9602-5222b507e35f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/700bf717d4e21fe47e23be424046de48aa0c312d/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 80 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d021a9f3-121e-4daa-b6f7-2c7b88123bab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/700bf717d4e21fe47e23be424046de48aa0c312d/msteams-platform%2Fsbs-bots-with-sso.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5968d35-c387-43d0-8d35-8f4403fa623e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/700bf717d4e21fe47e23be424046de48aa0c312d/msteams-platform%2Fsbs-calling-and-meeting.yml) | 88 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4cf1a83-bc5a-4413-a796-ace958457def) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/700bf717d4e21fe47e23be424046de48aa0c312d/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9868024-e77d-46f7-a284-d72da237fef9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/700bf717d4e21fe47e23be424046de48aa0c312d/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 84 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5a004fc-cbdc-46d0-8c75-98269e2d5b25) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/700bf717d4e21fe47e23be424046de48aa0c312d/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 84 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d986247b-94fb-4c53-871e-3113897235b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/700bf717d4e21fe47e23be424046de48aa0c312d/msteams-platform%2Fsbs-meeting-token-generator.yml) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/755fa780-55fd-469e-809c-ee4e41742462) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/700bf717d4e21fe47e23be424046de48aa0c312d/msteams-platform%2Fsbs-meetingextension-action.yml) | 81 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e6ee02b-23f3-41c9-a5d5-e90ea8eac29f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/700bf717d4e21fe47e23be424046de48aa0c312d/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7bc592a0-2237-4a97-a026-28954bdf7b09) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/qsg-bot-configuration-experience.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6de27dde007a740b0d05fa709c25262090be9995/msteams-platform%2Fqsg-bot-configuration-experience.yml) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c2be6a1-cf6c-43e3-a659-3804439c4edd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-me-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6de27dde007a740b0d05fa709c25262090be9995/msteams-platform%2Fsbs-api-me-ttk.yml) | 81 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d6c953a-352d-4211-8651-ba10a1bd7853) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6de27dde007a740b0d05fa709c25262090be9995/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 81 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/976767a0-4e5f-4d17-8f3e-c20ae7e74671) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6de27dde007a740b0d05fa709c25262090be9995/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 80 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6adae96-ac08-4f0a-a4bc-61f208ee7796) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6de27dde007a740b0d05fa709c25262090be9995/msteams-platform%2Fsbs-bots-with-sso.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63628bf1-3ff4-4a10-b14d-e06370e6aa67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6de27dde007a740b0d05fa709c25262090be9995/msteams-platform%2Fsbs-calling-and-meeting.yml) | 88 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/929a342a-b848-49a5-8360-cc963333548d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6de27dde007a740b0d05fa709c25262090be9995/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e3ea0b4-eff8-4a6d-802d-2168e4669f26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6de27dde007a740b0d05fa709c25262090be9995/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 84 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b190884c-3a86-4da0-94a0-53f696a446a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6de27dde007a740b0d05fa709c25262090be9995/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 84 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56d452a4-5824-428d-b523-075bfdfc273c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6de27dde007a740b0d05fa709c25262090be9995/msteams-platform%2Fsbs-meeting-token-generator.yml) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/013f9c09-a502-4bd5-b20d-5daf9e3300fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6de27dde007a740b0d05fa709c25262090be9995/msteams-platform%2Fsbs-meetingextension-action.yml) | 81 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbb117bf-5c15-4615-8e91-88df25d057b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6de27dde007a740b0d05fa709c25262090be9995/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e21349f1-e1bf-44de-bf44-6f377bc2a96e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
