### PR TITLE
[Doc Improvement][Feedback SEO updates][3663470]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6911fa00ea553dd84d8d02c03b6371e7478c3d30/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42245a79-caa7-4c2d-8dbe-e8f3b6f3a78b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2c84a47cc345240ffcbaadb21d229f8f1ec80d71/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eaee5ded-6d8e-4304-ae66-b7976b77a3ce) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d040ff421ad6251b1a070cfe4972e27b5ff0e02a/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56413331-ad0f-4f4e-889e-e15204077080) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b25feb2d48e5a45bd85f91293d87eabcb0e208e1/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ce3e53e-cdd1-41ec-b15c-b76619d0d6ed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b25feb2d48e5a45bd85f91293d87eabcb0e208e1/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93d7cd39-db7e-4193-91b1-ea21a69f8a66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b25feb2d48e5a45bd85f91293d87eabcb0e208e1/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e0956a4-7495-41aa-8ce3-abf5c422847c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/acc02393b38fee2cce71853f1bfd5d3304032ab3/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/387a7073-b4ad-425d-8915-7c7d8d28cc14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/acc02393b38fee2cce71853f1bfd5d3304032ab3/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f358456-f9a2-497c-972b-5fb591c57707) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/acc02393b38fee2cce71853f1bfd5d3304032ab3/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7316f506-7338-451c-940d-150f047665af) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d0ca00604b0925a99ad02bae374182b0750f636b/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1f707f0-a58d-4c2c-a980-d165a3748597) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d0ca00604b0925a99ad02bae374182b0750f636b/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/235c0e2a-989a-4890-9476-62f65134b18b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d0ca00604b0925a99ad02bae374182b0750f636b/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e430760a-aaa1-4c88-8cf5-384296749bca) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/024185ad880f181b385562a21e6c54ee1de10609/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/390f77ea-0ea9-4003-8c55-eee424e5324e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/024185ad880f181b385562a21e6c54ee1de10609/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/468d61b7-a603-4d9a-8d35-24291f76c30d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/024185ad880f181b385562a21e6c54ee1de10609/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63bf5f16-3db4-4e0c-940f-48a71dc0f0b0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ce69b0c057c580a77b1359287656b46b8e1dca/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/823197f4-65b2-4cec-a0cf-019860b6e087) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ce69b0c057c580a77b1359287656b46b8e1dca/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/728e25ed-8240-47d6-87de-c218bcf063e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ce69b0c057c580a77b1359287656b46b8e1dca/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98ba1e40-e02f-4530-abbe-a3e06f14635b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7ce69b0c057c580a77b1359287656b46b8e1dca/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88d5e03b-f30b-47de-8b92-f616cb8daec6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/624ca208a360af923d3939dd4baabb005aa25ddc/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09130763-c0d5-45c9-a8d7-fc540ac94cb5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/624ca208a360af923d3939dd4baabb005aa25ddc/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9dd47139-da3d-4568-a781-d1325fb861aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/624ca208a360af923d3939dd4baabb005aa25ddc/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/229f27c2-833e-4663-a00b-189b5a7dd15d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/624ca208a360af923d3939dd4baabb005aa25ddc/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15717202-254c-4c18-88cb-0b905730695e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9e05a17e19520c858b93d709f6602e88b275eb02/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82df623d-7dbc-4977-b141-896f6f5de977) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e05a17e19520c858b93d709f6602e88b275eb02/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/045bb396-ba05-4659-bbd3-94fbc2b57f1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e05a17e19520c858b93d709f6602e88b275eb02/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4176e24e-c27b-4b5d-b96f-2e2e1d588fdf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e05a17e19520c858b93d709f6602e88b275eb02/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c168937-b851-4657-b754-d7d26a0b959c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d61bb3e98fecbaa3b7d98f95e5be493c18267120/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b1c9732-7f6e-4692-9399-6d17014eab34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d61bb3e98fecbaa3b7d98f95e5be493c18267120/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0ea6bcc-7378-487d-9cd7-caf2f4a4938d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d61bb3e98fecbaa3b7d98f95e5be493c18267120/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28274c2c-46fe-4dde-9ea0-8d4120b05a68) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d61bb3e98fecbaa3b7d98f95e5be493c18267120/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/500da02a-179a-4a26-80f5-5684a2a3bc4a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/10a27633910ba16f439e2ed4e0b14ff68d06ddee/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb89d80c-d046-41dd-ab7a-f4d550ac7eac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/10a27633910ba16f439e2ed4e0b14ff68d06ddee/msteams-platform%2Ftabs%2Fhow-to%2Ftab-requirements.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f8c6283-bc19-46e1-a7ca-218fef7be347) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/10a27633910ba16f439e2ed4e0b14ff68d06ddee/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37edee3f-fb85-4aae-8c1e-f8569ff406a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/10a27633910ba16f439e2ed4e0b14ff68d06ddee/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5c33897-6fcf-40d2-8599-782006de0956) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
