### PR TITLE
[Doc Improvement][Monet FAQ section added in Docs FAQ]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4acd269117643c656bf68a30e35a0df086f017eb/msteams-platform%2Fteams-faq.md) | 88 | 97 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af206cc5-d7b6-4a0c-9e9b-ddffe138a66a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/22316718a88ba1252d9ba0ba65d0a98aa40563b6/msteams-platform%2Fteams-faq.md) | 88 | 97 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85dd47e1-ddd8-49fa-9916-463686ec4691) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2395790c71206097085d06d8446ef660948512b/msteams-platform%2Fteams-faq.md) | 88 | 97 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97db2374-c3a0-4501-a79d-a546ae7e68fd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3cf3d317c253e8daa6a586348d94999de7d8dac/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c2e891c-ccb0-43f7-8d2c-a16736dc1b84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3cf3d317c253e8daa6a586348d94999de7d8dac/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 87 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c5349db-183a-4fbe-b0c8-a66addfc36c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3cf3d317c253e8daa6a586348d94999de7d8dac/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2a9c1f4-c618-4b6c-a119-b32d515531cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3cf3d317c253e8daa6a586348d94999de7d8dac/msteams-platform%2Fteams-faq.md) | 89 | 94 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a891f471-545c-4c7f-9e9c-73181267ba6e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/616c8abc1b8a05fb5ad0c3c2621eeb0467f916f1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cde51e64-4ad5-41cc-b396-c61c80d60d7f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/616c8abc1b8a05fb5ad0c3c2621eeb0467f916f1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 87 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9543e741-be7c-4de6-95d4-b3e1ca93ba42) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/616c8abc1b8a05fb5ad0c3c2621eeb0467f916f1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ff4c2de-9d77-4f6d-ab5e-2870b6fe4839) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/616c8abc1b8a05fb5ad0c3c2621eeb0467f916f1/msteams-platform%2Fteams-faq.md) | 88 | 95 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50b6faa8-55bc-4cac-92f5-086788ffe059) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3284fb9c003579e655b90119460da577d413a3d2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a3d2e75-7036-4f2a-abf5-b10df6e059e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3284fb9c003579e655b90119460da577d413a3d2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 87 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/447d85e8-957c-4a99-a9b9-fb55517c7f03) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3284fb9c003579e655b90119460da577d413a3d2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a523979c-fcf8-43dc-9e13-8d82c5fe8724) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3284fb9c003579e655b90119460da577d413a3d2/msteams-platform%2Fteams-faq.md) | 88 | 95 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88eafa4d-001e-47c4-aa18-bcefdee0032c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed8fd113353283a5059f11f221eb2bfbbd08e3f9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17d41c7f-a0f4-4ec0-9c4b-f16adce301e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed8fd113353283a5059f11f221eb2bfbbd08e3f9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 89 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c9a59ef-2b2f-4c21-9a46-8319dde38274) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed8fd113353283a5059f11f221eb2bfbbd08e3f9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/965f68f1-a0a3-4e89-bee0-8cd3259ee0fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed8fd113353283a5059f11f221eb2bfbbd08e3f9/msteams-platform%2Fteams-faq.md) | 89 | 95 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc98437f-a905-4068-b2dc-d15fb715b0bc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0238ca2bb04aebca6c8073ab4a1c49d0ddef39ef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58a3c21b-ce49-4eb6-ae91-c690cfc2aa3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0238ca2bb04aebca6c8073ab4a1c49d0ddef39ef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 89 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06df62fe-8433-484a-8820-d46dde27cb4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0238ca2bb04aebca6c8073ab4a1c49d0ddef39ef/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e682fd69-f58e-4145-bb66-50dd05a17449) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0238ca2bb04aebca6c8073ab4a1c49d0ddef39ef/msteams-platform%2Fteams-faq.md) | 88 | 102 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5c568d5-ae82-4b78-8cb0-0a94ebc45cb9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94e8e87fae1f1bbebb6b11b1bd997be01d2f689d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/396bd3ab-3396-4093-94c3-521a456dc77b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94e8e87fae1f1bbebb6b11b1bd997be01d2f689d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 89 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56df5d38-d386-4352-ad94-ceed75be2ec6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94e8e87fae1f1bbebb6b11b1bd997be01d2f689d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85ec52e8-db4a-4e17-b253-daf3ac4f0f3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94e8e87fae1f1bbebb6b11b1bd997be01d2f689d/msteams-platform%2Fteams-faq.md) | 88 | 102 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/590c9964-fd42-4262-8d0f-9252f2a6ea00) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
