### PR TITLE
[Doc Improvement][Error handling messages]

### PR DESCRIPTION
**Pull request by v-bvishnu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/error-handling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b3c0a971a196d62a97eb4e41208da06ec246db8/msteams-platform%2Fresources%2Ferror-handling.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9efbe75-4e44-4945-a899-c96dbe502fa1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/error-handling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb0162cd6c323786d8e13dbdad67f36d53fcefc7/msteams-platform%2Fresources%2Ferror-handling.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df3e7f06-73ee-4a09-86f0-b149753e9277) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/includes/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb0162cd6c323786d8e13dbdad67f36d53fcefc7/msteams-platform%2Fresources%2Fincludes%2Fbots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/184d67eb-4135-4733-a5bd-7f8032bab64a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/includes/cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb0162cd6c323786d8e13dbdad67f36d53fcefc7/msteams-platform%2Fresources%2Fincludes%2Fcards.md) | 91 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98282ede-bf68-42a3-b4f2-0f91fde3b397) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/error-handling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ef22acac8223c71c2ebe639d76166639a62ba06/msteams-platform%2Fresources%2Ferror-handling.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95e537b9-1f1a-40d9-8751-e269251caf07) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/includes/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ef22acac8223c71c2ebe639d76166639a62ba06/msteams-platform%2Fresources%2Fincludes%2Fbots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f97e5d5-5f22-4c89-bdf5-7e0e334be874) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/includes/cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ef22acac8223c71c2ebe639d76166639a62ba06/msteams-platform%2Fresources%2Fincludes%2Fcards.md) | 91 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5325f2b-df67-4cf8-8286-7623784d687d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/error-handling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/38adc63a53778ef7acb5c56536012b89dffb2ac4/msteams-platform%2Fresources%2Ferror-handling.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac5a5c17-df49-4ab7-af46-318e225dc8a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/includes/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/38adc63a53778ef7acb5c56536012b89dffb2ac4/msteams-platform%2Fresources%2Fincludes%2Fbots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/157c56e8-4525-4273-824d-2b5109154d6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/includes/cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/38adc63a53778ef7acb5c56536012b89dffb2ac4/msteams-platform%2Fresources%2Fincludes%2Fcards.md) | 91 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39d87f75-e2ac-4e94-9225-0d4cd9e79c51) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/error-handling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/30c7eecaad2a15a84875c6593400ea2d278ad7b1/msteams-platform%2Fresources%2Ferror-handling.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80c6b58c-6b46-4002-98ba-077a984d56ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/includes/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/30c7eecaad2a15a84875c6593400ea2d278ad7b1/msteams-platform%2Fresources%2Fincludes%2Fbots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e5f509f-53dc-42d4-b91c-e6865782dee0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/includes/cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/30c7eecaad2a15a84875c6593400ea2d278ad7b1/msteams-platform%2Fresources%2Fincludes%2Fcards.md) | 91 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48d63dc4-df1f-480c-8a70-8f81d27efd1a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/error-handling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aaf0650f1f902ab152c7d7157f73931f89c6a551/msteams-platform%2Fresources%2Ferror-handling.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62625b96-8cdf-42d8-a57d-b9d06e064ba5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/includes/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aaf0650f1f902ab152c7d7157f73931f89c6a551/msteams-platform%2Fresources%2Fincludes%2Fbots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/044b3513-ff0b-4942-94f8-6f1462196e3c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/includes/cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aaf0650f1f902ab152c7d7157f73931f89c6a551/msteams-platform%2Fresources%2Fincludes%2Fcards.md) | 91 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/abb90085-5e91-4b89-95f1-d1eca85aaca5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/error-handling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53229a6f4e3d44042503c72e25c1c7cf1baf682e/msteams-platform%2Fresources%2Ferror-handling.md) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/015e27ac-e877-45c9-adea-b4af01ea59e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/includes/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53229a6f4e3d44042503c72e25c1c7cf1baf682e/msteams-platform%2Fresources%2Fincludes%2Fbots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/753e7329-9320-4945-aa5c-213da63fdb0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/includes/cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53229a6f4e3d44042503c72e25c1c7cf1baf682e/msteams-platform%2Fresources%2Fincludes%2Fcards.md) | 91 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33870885-150a-4ddc-a8d0-5bd80d66178a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/error-handling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8bd116cb6ad7f4f1e826816627b5cf881b0a0ff5/msteams-platform%2Fresources%2Ferror-handling.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8b9464e-051a-4e4b-915d-4d10f36c8749) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/includes/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8bd116cb6ad7f4f1e826816627b5cf881b0a0ff5/msteams-platform%2Fresources%2Fincludes%2Fbots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64d6dffa-4a6f-4f69-9ebc-8e876c668562) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/includes/cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8bd116cb6ad7f4f1e826816627b5cf881b0a0ff5/msteams-platform%2Fresources%2Fincludes%2Fcards.md) | 91 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0eec636c-486c-4f98-b278-90226ffa82a2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/error-handling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/daec1ef72eb5cdd1303623c44cf4dc4e53c96cbf/msteams-platform%2Fresources%2Ferror-handling.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/358a7d94-9f00-49d9-8dc0-8203e737c11a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/error-handling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae898e319c81c807d127d5b9089aba5ecd3373bc/msteams-platform%2Fresources%2Ferror-handling.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06aefb33-5e45-405e-9e3b-defe80760c1b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/error-handling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/10f9f50b7550dd59d16b407350602c35397f494d/msteams-platform%2Fresources%2Ferror-handling.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f3f96af-0976-4116-a3d4-d10ecc274c9b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by surbhigupta12** [comment]
Closing this PR as it was a test PR.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/error-handling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/10f9f50b7550dd59d16b407350602c35397f494d/msteams-platform%2Fresources%2Ferror-handling.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/994feac3-d873-43e0-b373-965ad6045f86) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by surbhigupta12** [comment]
Closing this PR as the work is taken up in PR #9620

**Pull request closed without merging**
