### PR TITLE
[Doc Issue][Update links][2382239]

### PR DESCRIPTION
**Pull request by vsoniv**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80d40a891a17269558170121d880616d7d269d0c/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c13ebecd-ed68-4210-8f6a-6d40e0ae2e1a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99d35f46d10c626e9059f763881841cf17b45804/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acb17279-a433-4178-a23a-df0c750806f8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93306f33ae61a8da467f9da7673d4e76c1dc87e7/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/577c95ec-3f3b-4f12-9097-6fc82fa9837d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/51a15f8c09de292e952cc51eb6bfb60f03812bfc/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/555cd7ca-f758-4847-a0a4-49470631e60e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd5453531a420c2e77c0251e1092c00bc0ab8e35/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7041a0d-1d42-47c6-a402-3c1c90f27bd8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd5453531a420c2e77c0251e1092c00bc0ab8e35/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3b811a6-e5b7-4aa6-964a-56689eeb7026) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/474cb131cbedd92d1004d1f356e830ee0aaf40ec/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0f046db-9107-408a-a151-3741ea5007f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/474cb131cbedd92d1004d1f356e830ee0aaf40ec/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 87 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e6a95a4-375d-4fad-8507-1aba96c051bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/474cb131cbedd92d1004d1f356e830ee0aaf40ec/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0919f57c-9c9c-4952-955c-34da165fd14a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/474cb131cbedd92d1004d1f356e830ee0aaf40ec/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/682ec9a3-6db7-4d80-9860-dc81930273da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/474cb131cbedd92d1004d1f356e830ee0aaf40ec/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 87 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3301d00a-714e-49dd-8ac2-d232882678f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/474cb131cbedd92d1004d1f356e830ee0aaf40ec/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e8aa65d-cd6d-4fd4-9ceb-fd2810889b77) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2cfb6607251f0a44a21789291bb61f8ba605d96/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e72eec6-c337-48d4-87a8-36793df89bef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2cfb6607251f0a44a21789291bb61f8ba605d96/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 85 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd6f3d48-95c6-4a5a-abf7-f96f50be9d4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2cfb6607251f0a44a21789291bb61f8ba605d96/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 87 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fed45f9-c283-42ec-9591-89a88cba6381) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7b6177d4e2b6a67e253a9461274881ac47981e9/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0756faf-ec08-4941-9eaa-a39e5c3097b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7b6177d4e2b6a67e253a9461274881ac47981e9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 85 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc53248b-7970-4c42-a72f-0084470a85d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7b6177d4e2b6a67e253a9461274881ac47981e9/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 87 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fae00b06-d464-465d-955f-3ec78f91eebb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
