### PR TITLE
[Doc Improvement][Update overview see also]

### PR DESCRIPTION
**Pull request by v-jganga**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/edbefbc1cf94ace492e9a76a92ecab4f7e876094/msteams-platform%2Foverview.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12442dec-501a-44b8-a27a-67eedd4dabbb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18eaea3fe4927acf5d3d151b012faf3e32fb07e3/msteams-platform%2Foverview.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4812051-0f6c-4aac-9b15-042f0ca3d9f2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c189e243692e86ed629d5d53736ae983eaf2df25/msteams-platform%2Foverview-explore.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb6d85d0-2e14-42a6-afc1-363e63413b46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c189e243692e86ed629d5d53736ae983eaf2df25/msteams-platform%2Foverview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de493f7f-7158-43c8-bcb7-fb7dcda86afe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-story.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c189e243692e86ed629d5d53736ae983eaf2df25/msteams-platform%2Foverview-story.md) | 86 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8130ab6e-55cb-4cd7-a2be-846d6cc3db49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c189e243692e86ed629d5d53736ae983eaf2df25/msteams-platform%2Foverview.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/536edbac-7be7-4849-b920-fb1e5d3e31e3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8da27104fa080cf63c5e5e20fa568d9dc0879a24/msteams-platform%2Foverview-explore.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4976c4ca-f3c9-4827-8919-9af8fdc1a570) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8da27104fa080cf63c5e5e20fa568d9dc0879a24/msteams-platform%2Foverview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce9e4218-8428-4953-9a50-d2bbef63d0b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-story.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8da27104fa080cf63c5e5e20fa568d9dc0879a24/msteams-platform%2Foverview-story.md) | 86 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cbe0f360-48fb-4f74-897d-2c57d6c3e178) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8da27104fa080cf63c5e5e20fa568d9dc0879a24/msteams-platform%2Foverview.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee6ff9b0-b321-4085-a5f7-4d0e73932e85) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87d208acd33ce48734ab3a614c2139ea84179dd5/msteams-platform%2Foverview-explore.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd0b1eba-0a9d-48cd-859a-6fb88ab2c75d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87d208acd33ce48734ab3a614c2139ea84179dd5/msteams-platform%2Foverview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/216e8451-23fd-4a21-b152-cc1661c252f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-story.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87d208acd33ce48734ab3a614c2139ea84179dd5/msteams-platform%2Foverview-story.md) | 86 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc3b3d81-aa01-4594-b79d-ea6060efcafe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/87d208acd33ce48734ab3a614c2139ea84179dd5/msteams-platform%2Foverview.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46e72853-0aa1-42d5-912a-69298d4f093d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c7695014685d672081ad3071241eb7de40450d8/msteams-platform%2Foverview-explore.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfae3993-59c0-4d31-845f-69e17dc215a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c7695014685d672081ad3071241eb7de40450d8/msteams-platform%2Foverview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b769f682-0cb0-40d5-9961-189b3fccedd4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-story.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c7695014685d672081ad3071241eb7de40450d8/msteams-platform%2Foverview-story.md) | 86 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d18b7fe4-2344-474e-ab59-eda0f09268f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c7695014685d672081ad3071241eb7de40450d8/msteams-platform%2Foverview.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85726180-b24f-44d6-b05f-15d67a177fdc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/780571bf23d1a15aa9d7ac650f9eceba0b61c80a/msteams-platform%2Foverview-explore.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4be012d5-0afd-4443-aff8-291240e06267) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/780571bf23d1a15aa9d7ac650f9eceba0b61c80a/msteams-platform%2Foverview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38908961-c716-4ef2-a565-b70203bfc32c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-story.md](https://github.com/MicrosoftDocs/msteams-docs/blob/780571bf23d1a15aa9d7ac650f9eceba0b61c80a/msteams-platform%2Foverview-story.md) | 86 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a83499b6-db51-4447-9b9d-520ca6dd3f87) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/780571bf23d1a15aa9d7ac650f9eceba0b61c80a/msteams-platform%2Foverview.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c2df0c1-7682-4af9-afc8-79aa04f44adf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-abirade** [comment]
Closing the PR as discussed.

**Pull request closed without merging**
