### PR TITLE
[Doc Improvement][link-in-bots-overview][2325194]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4eb30ee6ffac3f302fff6a9d4a2e955047baee42/msteams-platform/bots/what-are-bots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34f7bd7a-9dc7-4226-9c07-dc01953acf35) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4eb30ee6ffac3f302fff6a9d4a2e955047baee42/msteams-platform/bots/what-are-bots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33fe4653-e688-4c82-be7d-4ebae6091e52) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by yong-sea** [comment]
Can you open the website  http://www.sdtzbike.com/
________________________________
发件人: opbld32 ***@***.***>
发送时间: 2022年3月27日 11:40
收件人: MicrosoftDocs/msteams-docs ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [MicrosoftDocs/msteams-docs] [Doc Improvement][link-in-bots-overview] (PR #5564)


Docs Build status updates of commit 4eb30ee<https://github.com/MicrosoftDocs/msteams-docs/commits/4eb30ee6ffac3f302fff6a9d4a2e955047baee42>:

❌ Validation status: errors

Please follow instructions here<https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish> which may help to resolve issue.

File    Status  Preview URL     Details
❌Error          Details

  *   [Error: RuningBuildFailed] Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot

For more details, please refer to the build report<https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C202203271138095994-5564%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-27T11%3A40%3A34Z&sr=b&sp=r&sig=%2B%2BIg5GnEZ5Vqp05%2BsrQiKhmo1zmXK2fF1kc9iWFMahA%3D>.

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions here<https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main> to re-authorize your GitHub account to Docs Build.

Note: Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the broken link report<https://ops.microsoft.com/#/repos/d98cc23d-94e8-765b-0855-bdd8964dc537?tabName=brokenlinks>.

Note: Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these instructions<https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch> to resolve them.

For any questions, please:

  *   Try searching the docs.microsoft.com contributor guides<https://review.docs.microsoft.com/en-us/help/?branch=main>
  *   Post your question in the Docs support channel<https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47>

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4eb30ee6ffac3f302fff6a9d4a2e955047baee42/msteams-platform/bots/what-are-bots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4f15dba-f1af-4acf-bfd1-99e51bdc01f3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
