### PR TITLE
[Doc Improvement][Border fixing for images][3124205]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/859b9ec376eb26ee25d71c2205162fa032fc4658/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc4a4b3e-b917-4289-a0bd-776f86fc3bce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/859b9ec376eb26ee25d71c2205162fa032fc4658/msteams-platform%2Fresources%2FmoodleInstructions.md) | 91 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c864eab-b5cf-401f-ba22-d88df867490c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/859b9ec376eb26ee25d71c2205162fa032fc4658/msteams-platform%2Fsamples%2Fapp-templates.md) | 89 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45414077-62f2-4c30-a7c3-daabd5ef2e63) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/859b9ec376eb26ee25d71c2205162fa032fc4658/msteams-platform%2Fsamples%2Fshifts-wfm-connectors.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4077dc31-e8f7-4986-b6b7-ae0a013a7f96) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a3f07bf62017b6a99d6ffe4197150b152f24a82/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9e4e188-78a5-4290-b6f3-dae3d171d6dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a3f07bf62017b6a99d6ffe4197150b152f24a82/msteams-platform%2Fresources%2FmoodleInstructions.md) | 91 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bbb14eb-09b9-49e7-b91b-454f3b6ff3ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a3f07bf62017b6a99d6ffe4197150b152f24a82/msteams-platform%2Fsamples%2Fapp-templates.md) | 89 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52d99de6-dc5c-4261-8d14-5b8cc1a95330) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a3f07bf62017b6a99d6ffe4197150b152f24a82/msteams-platform%2Fsamples%2Fshifts-wfm-connectors.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5ac4d75-053d-4ae9-bf22-a476a6ec2ef7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a3f07bf62017b6a99d6ffe4197150b152f24a82/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e7dbfd7-d2bf-4e34-959a-d2686121da27) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/335f842d2ffcd951d09adcdcc5eb63b6910cbaae/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c58cd4c-ee62-4506-9cab-48a8beabae55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/335f842d2ffcd951d09adcdcc5eb63b6910cbaae/msteams-platform%2Fresources%2FmoodleInstructions.md) | 91 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2306304-a87a-4b23-bde0-8f0fcc24a4f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/335f842d2ffcd951d09adcdcc5eb63b6910cbaae/msteams-platform%2Fsamples%2Fapp-templates.md) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6cc4565b-25e2-4bfe-bc2e-387abf26088e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/335f842d2ffcd951d09adcdcc5eb63b6910cbaae/msteams-platform%2Fsamples%2Fshifts-wfm-connectors.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92887259-d087-4c20-bcdb-d0fcec64b09c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/335f842d2ffcd951d09adcdcc5eb63b6910cbaae/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e30cef1c-f21c-47d2-a327-8ec8e7565ef6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2b607a097d5b5716ef3ca34faf3c38a19159c104/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed57576d-5f64-4c0e-a840-b7d0a597b124) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2b607a097d5b5716ef3ca34faf3c38a19159c104/msteams-platform%2Fresources%2FmoodleInstructions.md) | 91 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d4f528d-178c-4d06-8383-fa8b93bc69f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2b607a097d5b5716ef3ca34faf3c38a19159c104/msteams-platform%2Fsamples%2Fapp-templates.md) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3a0fa0c-d624-4569-9190-54e7de9ac670) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2b607a097d5b5716ef3ca34faf3c38a19159c104/msteams-platform%2Fsamples%2Fshifts-wfm-connectors.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f881d1f-4619-49ae-a3d8-6a05a615b722) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2b607a097d5b5716ef3ca34faf3c38a19159c104/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b357ba5a-7a81-4946-8064-44dac4f66d8b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfbaf7bda05f090db84364e2568809afca02ed7c/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9d35681-3dde-4dc3-95cc-24f5e893dbd8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfbaf7bda05f090db84364e2568809afca02ed7c/msteams-platform%2Fresources%2FmoodleInstructions.md) | 91 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c062f57a-e1a1-4a98-83dc-0a8de4a6a3ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfbaf7bda05f090db84364e2568809afca02ed7c/msteams-platform%2Fsamples%2Fapp-templates.md) | 91 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bc98a3d-5841-48fc-9444-490a8bbcd68b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfbaf7bda05f090db84364e2568809afca02ed7c/msteams-platform%2Fsamples%2Fshifts-wfm-connectors.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e152a7f8-1f8a-4445-9287-0189c041b65e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfbaf7bda05f090db84364e2568809afca02ed7c/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6afa57bf-f59a-44f1-9d64-fd316c88c8e9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d4714dd1ca89bc339e8b2fde7735a2534c360b8/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ce8ce81-022d-46a8-bc12-c23dddbf75c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d4714dd1ca89bc339e8b2fde7735a2534c360b8/msteams-platform%2Fresources%2FmoodleInstructions.md) | 91 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be341cf3-ff1c-40e4-8cea-0d754dfa7ef9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d4714dd1ca89bc339e8b2fde7735a2534c360b8/msteams-platform%2Fsamples%2Fapp-templates.md) | 91 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64efe778-11f5-40b7-8738-531951037f9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d4714dd1ca89bc339e8b2fde7735a2534c360b8/msteams-platform%2Fsamples%2Fshifts-wfm-connectors.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b95caa5-4901-4ccc-b624-7f44fd115d81) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d4714dd1ca89bc339e8b2fde7735a2534c360b8/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb8e23e9-c3c8-4042-89c7-78b7c89df401) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7374435cf419d1a1c1fdb677a5a36546e06d1527/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/619eb6b6-9774-457c-b752-a13a69e19444) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7374435cf419d1a1c1fdb677a5a36546e06d1527/msteams-platform%2Fresources%2FmoodleInstructions.md) | 91 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/188719a9-684c-4c2e-9315-e4d7f5a85477) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7374435cf419d1a1c1fdb677a5a36546e06d1527/msteams-platform%2Fsamples%2Fapp-templates.md) | 91 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e01b3d49-5461-4916-9adb-d6a82a6bab4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7374435cf419d1a1c1fdb677a5a36546e06d1527/msteams-platform%2Fsamples%2Fshifts-wfm-connectors.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22a62b16-a6d8-424f-b945-0529305c7745) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7374435cf419d1a1c1fdb677a5a36546e06d1527/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68cbc16f-97bc-47aa-ad4a-13f8c2b659dd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d0faefbdd3c54b3519ef8d7fdefe510e859b734/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/164f75e3-68a0-4be3-b121-016c5a8aec67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d0faefbdd3c54b3519ef8d7fdefe510e859b734/msteams-platform%2Fresources%2FmoodleInstructions.md) | 91 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea5cbc2e-6698-4f99-8cbb-c50bda2ea836) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d0faefbdd3c54b3519ef8d7fdefe510e859b734/msteams-platform%2Fsamples%2Fapp-templates.md) | 91 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76c85e95-cc16-46ac-8a98-aecd26031701) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d0faefbdd3c54b3519ef8d7fdefe510e859b734/msteams-platform%2Fsamples%2Fshifts-wfm-connectors.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21e8e7fa-cce8-426a-96a7-73b0cb02b827) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d0faefbdd3c54b3519ef8d7fdefe510e859b734/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c8c3e91-478f-4672-9b79-e21b74cb68be) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
