### PR TITLE
Add Sample Launch Page App to code sample table

### PR DESCRIPTION
**Pull request by AnanyaBarthakur1**
@erikadoyle

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/11d392a48110d25ce8e2764d87527e84c3364a50/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2915f954-1b96-41b6-9f0a-e3ac6afa177e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by erikadoyle** [comment]
Thanks @AnanyaBarthakur1, the table entry looks good. Let's plan to merge (publish) this doc update once the sample readme file has instructions on how to run the sample. Thanks!

**Review by erikadoyle — APPROVED** [review]
Looks good, and the [sample readme](https://github.com/OfficeDev/microsoft-teams-library-js/tree/main/apps/sample-app) looks good too!

**Comment by erikadoyle** [comment]
@surbhigupta12 would you mind helping us merge this once you have a chance? Thanks!

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
