### PR TITLE
[Doc Improvement][punctuation check][2481153]

### PR DESCRIPTION
**Pull request by v-silakshmi**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c4653881d27849a0f97ca229a9643b7db59115a/msteams-platform%2Fsamples%2Fapp-templates.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04c453d9-8408-4efe-9ba1-abcd9868acde) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c4653881d27849a0f97ca229a9643b7db59115a/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df9743fb-3d16-4eb4-a900-6a94eca382be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c4653881d27849a0f97ca229a9643b7db59115a/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-reference.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53eaa879-1c34-49a2-bbc7-64da9d037368) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c4653881d27849a0f97ca229a9643b7db59115a/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99948ba5-958b-41ae-bcf2-90c81333b054) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c4653881d27849a0f97ca229a9643b7db59115a/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/541e0975-b249-41c6-91b4-9d71e6780eaa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c4653881d27849a0f97ca229a9643b7db59115a/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e103b39-b036-4e3d-9829-c957c3275a0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c4653881d27849a0f97ca229a9643b7db59115a/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8455982d-d69c-48b8-96a2-0feccfc39b37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c4653881d27849a0f97ca229a9643b7db59115a/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e42bb17e-99f4-4b34-bb99-65190c594734) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c4653881d27849a0f97ca229a9643b7db59115a/msteams-platform%2Ftoolkit%2Fpublish.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28f82aef-45f2-4acf-9d7c-ff0211fe1d34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c4653881d27849a0f97ca229a9643b7db59115a/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bad9a19-ba93-4874-9639-4d4c99c30d46) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — DISMISSED** [review]
Approved

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee87cdcd3977f8de89e8f814e31cf8550915cd71/msteams-platform%2Fsamples%2Fapp-templates.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a18353c-44f1-4fad-82d6-2e00d133c834) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee87cdcd3977f8de89e8f814e31cf8550915cd71/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3a75f47-7a77-497e-bc3b-c59dd3ff891e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee87cdcd3977f8de89e8f814e31cf8550915cd71/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3eb5f037-7f10-44b8-bc3e-bfa7dcc5378b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee87cdcd3977f8de89e8f814e31cf8550915cd71/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/618402e7-d2fa-4f86-bb8c-98859956848f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee87cdcd3977f8de89e8f814e31cf8550915cd71/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b05e3b53-e6a1-42b2-af7f-0d3599836887) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee87cdcd3977f8de89e8f814e31cf8550915cd71/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/293b970e-70aa-46a9-8a96-d87081eea10b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee87cdcd3977f8de89e8f814e31cf8550915cd71/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/199f45e3-0eb9-44be-ada8-a8f84fdd6e21) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee87cdcd3977f8de89e8f814e31cf8550915cd71/msteams-platform%2Ftoolkit%2Fpublish.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c25f742d-b23f-4281-bbc7-43b0961d6082) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee87cdcd3977f8de89e8f814e31cf8550915cd71/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/916aebdc-e25c-41f4-a84a-9ad43649f522) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0d6b9a6b9eb1010434377dd5931f01fa3f4aaf9/msteams-platform%2Fsamples%2Fapp-templates.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb7a2542-b259-477a-898b-5d6be96b56cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0d6b9a6b9eb1010434377dd5931f01fa3f4aaf9/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/715b7f25-440f-4053-97e4-068b7f41a7bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0d6b9a6b9eb1010434377dd5931f01fa3f4aaf9/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/038a0821-0647-49a5-979b-3dbdd9416a81) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0d6b9a6b9eb1010434377dd5931f01fa3f4aaf9/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40e184b2-43a9-4cfa-bcd4-ea086b618176) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0d6b9a6b9eb1010434377dd5931f01fa3f4aaf9/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3eb83397-39ff-4402-8713-bce7471d67b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0d6b9a6b9eb1010434377dd5931f01fa3f4aaf9/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f782b0a-4b19-4892-898f-c4fc1608ac6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0d6b9a6b9eb1010434377dd5931f01fa3f4aaf9/msteams-platform%2Ftoolkit%2Fpublish.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89d0f53a-546f-4e59-9176-f2459c4ae577) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0d6b9a6b9eb1010434377dd5931f01fa3f4aaf9/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d92eb025-8bf4-4897-96f5-59bebf03a788) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e902d058b5db665e0baa9863ff500af90ccb53d2/msteams-platform%2Fsamples%2Fapp-templates.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/edee2b91-febe-490d-9936-3f3e2d225619) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e902d058b5db665e0baa9863ff500af90ccb53d2/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0aee543-087b-45df-9feb-2dae83022d20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e902d058b5db665e0baa9863ff500af90ccb53d2/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48b8898c-673d-4806-8666-d02db1e88dc3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e902d058b5db665e0baa9863ff500af90ccb53d2/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/375f9197-3104-45d9-8473-7052f7dea110) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e902d058b5db665e0baa9863ff500af90ccb53d2/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd627196-5b15-4e0a-996a-6b8314d9b49e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e902d058b5db665e0baa9863ff500af90ccb53d2/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eaabc663-d7aa-45d9-840f-9e5aabc78163) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e902d058b5db665e0baa9863ff500af90ccb53d2/msteams-platform%2Ftoolkit%2Fpublish.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67b5517e-514a-47ac-a7b7-c8becdf93764) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e902d058b5db665e0baa9863ff500af90ccb53d2/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2cabf2b-eab7-448a-b6d1-fe1622a91f62) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/618af9d89b6597377d4b237922c8a580880dc6a6/msteams-platform%2Fsamples%2Fapp-templates.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d86ce56e-48f0-4079-b27c-5dc6fae010db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/618af9d89b6597377d4b237922c8a580880dc6a6/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45761aaf-4fb6-430b-b787-0e8a4bae1c55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/618af9d89b6597377d4b237922c8a580880dc6a6/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b228cf39-70fa-479b-87e2-e84fa3768f09) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/618af9d89b6597377d4b237922c8a580880dc6a6/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc7200ae-a542-42bd-b3a0-2498483a35d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/618af9d89b6597377d4b237922c8a580880dc6a6/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dda7b35d-2503-4671-8ccf-c8a4408d06af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/618af9d89b6597377d4b237922c8a580880dc6a6/msteams-platform%2Ftoolkit%2Fpublish.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09b147f6-9b01-4f3e-bbb8-7dac6aefe709) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/618af9d89b6597377d4b237922c8a580880dc6a6/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c228f63c-469e-4ba4-8f88-0bea95669b73) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
