### PR TITLE
[Doc Improvement][Update localization metadata]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8ee3ae23596b44ee7d4d9c82fee5b16fb1dbca1/msteams-platform%2Ffeedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bce52c1e-a58b-4b38-9edf-657a5e174cf8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4ae7ac9e03525b5b31a0ca946daaabece25a5a8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 83 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07f24d92-e733-4b4c-bbbe-2dd3ebd92fea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4ae7ac9e03525b5b31a0ca946daaabece25a5a8/msteams-platform%2Ffeedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb5b7f67-2e49-4a5d-8b8c-478bd355b1f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4ae7ac9e03525b5b31a0ca946daaabece25a5a8/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4af7fa96-2740-40af-a847-b472d2410787) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4ae7ac9e03525b5b31a0ca946daaabece25a5a8/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85556b66-1304-469c-82e3-00616f4c79ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4ae7ac9e03525b5b31a0ca946daaabece25a5a8/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b445f207-449f-4348-97f9-b6a5855aa39f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b857eff01cd7bc37256323607df72e03afa6d95/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2083a399-ea92-4dfa-b601-133ad34b7fa5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b857eff01cd7bc37256323607df72e03afa6d95/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 83 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3f1bf68-da0c-4c0a-a9de-456c331a29ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b857eff01cd7bc37256323607df72e03afa6d95/msteams-platform%2Ffeedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc75866d-9c5f-4450-85d3-11a8ef7e717e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b857eff01cd7bc37256323607df72e03afa6d95/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c6686a1-7e30-46ab-b0b2-18cb4e7c2963) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b857eff01cd7bc37256323607df72e03afa6d95/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/530a4b18-eefd-4500-aadd-8344fe35225c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b857eff01cd7bc37256323607df72e03afa6d95/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3339492-fd04-4ebd-b3d8-fd5e4baa38ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b857eff01cd7bc37256323607df72e03afa6d95/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 87 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41223868-2de1-4574-9c21-38a761930cf7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b857eff01cd7bc37256323607df72e03afa6d95/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 86 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21c7279e-4755-46a6-bed3-f2c73cc0e430) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b857eff01cd7bc37256323607df72e03afa6d95/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d77ec9b4-daa0-403d-af7d-42834d893380) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b857eff01cd7bc37256323607df72e03afa6d95/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 85 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c568d711-6012-4543-96e0-c5bbdc085fc3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd4bf0327019c968bda7ae661a1a9acd6b94dc92/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef3aacbc-aef9-42a2-8bc9-e4b2f43e2c01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd4bf0327019c968bda7ae661a1a9acd6b94dc92/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 83 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94557128-afd4-4c0f-a4c2-7d13b30739db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd4bf0327019c968bda7ae661a1a9acd6b94dc92/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-from-web-apps.md) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de5cfb71-45ed-40ce-a579-95da1f4f52c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd4bf0327019c968bda7ae661a1a9acd6b94dc92/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3efe2d25-afcd-4ebb-b418-e9350436556b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd4bf0327019c968bda7ae661a1a9acd6b94dc92/msteams-platform%2Ffeedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aab8948b-3a86-4777-a2f8-bb280a3580fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd4bf0327019c968bda7ae661a1a9acd6b94dc92/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f762969f-4a4b-4c9e-81d9-11b2864d5318) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd4bf0327019c968bda7ae661a1a9acd6b94dc92/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7eea846-91db-420a-a9b2-4243a7d6a182) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd4bf0327019c968bda7ae661a1a9acd6b94dc92/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af07ab58-5400-4c42-bffc-b50f84dd1910) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd4bf0327019c968bda7ae661a1a9acd6b94dc92/msteams-platform%2Fsamples%2Fapp-templates.md) | 87 | 104 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8be749a-6fc9-4e26-b022-1901259b0ba7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd4bf0327019c968bda7ae661a1a9acd6b94dc92/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 87 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3d0952b-b20a-4392-851c-d9c566abdb29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd4bf0327019c968bda7ae661a1a9acd6b94dc92/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 86 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/702fd16f-848d-42c2-974e-35a301550879) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd4bf0327019c968bda7ae661a1a9acd6b94dc92/msteams-platform%2Fsamples%2Fshifts-wfm-connectors.md) | 84 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2cf97113-8187-47b0-be35-961e9d23aae0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd4bf0327019c968bda7ae661a1a9acd6b94dc92/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8ce344f-e8a1-4960-b6eb-07824875b8f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd4bf0327019c968bda7ae661a1a9acd6b94dc92/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 85 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/958bfbc7-0b31-4370-a194-3a229be3863b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7b2b249-6a0b-4e14-afc4-0f293e8bb09c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 83 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1711d7c7-6271-474f-9250-12fc14838221) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-from-web-apps.md) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50c190bc-0c82-468d-bb44-233dd1b91dd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe972d51-670d-4b38-90b8-cf8a3b2d44c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8cd5bb1-be4f-414c-85f9-72b0eaddf042) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Ffeedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc290054-26e4-44f4-ad1c-94b80b3c98fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/463acbf5-3002-458f-930e-23a8c72f52fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2385ff3c-8c8f-4473-a07a-49ba1600ad49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 84 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da40c81e-5221-4590-8b7d-3d9196d710db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/758893a0-6309-4f3f-9809-4ce8fe3083ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fsamples%2Fapp-templates.md) | 87 | 104 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db79862d-c2ff-4096-9412-6a57d4ea460d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 87 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21e8f825-7b12-4816-8ec8-30ec41ac7ebb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 86 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0dcb8f7f-e497-4ac3-9c6c-90200ffff7b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/shifts-wfm-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fsamples%2Fshifts-wfm-connectors.md) | 84 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d773ef2a-14a4-4a2b-a55d-b8f6fbfbfb27) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fsamples%2Fteams-low-code-solutions.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d5282d8-2a9e-4d0d-9bd5-9d08a5f087b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 85 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9403261-7039-428c-9e8b-81aadc68f901) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6009289cb1fc4c6f7dbd1038b01c35d1912cae9/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca5c14b6-2215-4b2e-98db-f7e4effa01c0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
