### PR TITLE
[Doc Improvement][Dev Comm Support][Metadata update and doc URL added][2541160]

### PR DESCRIPTION
**Pull request by v-ajiths**
Edited and added relevant doc link in "See also" section. updated the metadata for better SEO results

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93fc1e832e5444fb9b35ea6b0c20e4fdc4ea1f10/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7e3bb05-6f2e-44ce-86f9-d80b9615b8e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93fc1e832e5444fb9b35ea6b0c20e4fdc4ea1f10/msteams-platform%2Fgraph-api%2Fproactive-bots-and-messages%2Fgraph-proactive-bots-and-messages.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f760b6e-ac7a-4026-b4c5-0b4e0f336435) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6e89b0fff42c06e0241ffa5e73de8ca8032821e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d7aec7f-2f0c-4fe7-83df-45274996a027) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6e89b0fff42c06e0241ffa5e73de8ca8032821e/msteams-platform%2Fgraph-api%2Fproactive-bots-and-messages%2Fgraph-proactive-bots-and-messages.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b2469ac-616b-400e-bd21-bc8ff662a53e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — DISMISSED** [review]
Approved

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f4219aeb5d689069c4e235700129b538642031c1/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4ef4b02-0144-4fcf-9951-163242440854) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f4219aeb5d689069c4e235700129b538642031c1/msteams-platform%2Fgraph-api%2Fproactive-bots-and-messages%2Fgraph-proactive-bots-and-messages.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1129b09e-c73e-48fc-8fc7-2acae2d04fa7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
