### PR TITLE
[Doc Improvement][Update broken links][2994122]

### PR DESCRIPTION
**Pull request by v-vanv**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8e357bc4edf71b9f7f36183c282cbc3740382bd5/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/784e8fd8-1e24-4c69-919a-2b9e9eafb2ba) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f9f1bcfd93b719f283ede55fd9e551854a708bdf/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f149b13-e8f3-437f-93da-07ab4055a97c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f9f1bcfd93b719f283ede55fd9e551854a708bdf/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cdf87ad-253c-4498-adb7-a3b459517306) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f9f1bcfd93b719f283ede55fd9e551854a708bdf/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8de5b04e-9ee8-44e6-aa36-68bf6d6ab45b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0d2684acd433ddfec0a9119953a13ee398d7b49e/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1edfba11-1d12-4cc1-8843-bf1bf54ddf1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0d2684acd433ddfec0a9119953a13ee398d7b49e/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5e76f95-892c-4cb7-8075-5f15c8cc5e22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0d2684acd433ddfec0a9119953a13ee398d7b49e/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39d0415b-6278-4857-bbf6-e387e150e5e6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6085f54a2b97fcec30487b0cc58e2d57e3c83296/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95d485cf-ebfd-4ff4-8173-5e51ca18f7b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6085f54a2b97fcec30487b0cc58e2d57e3c83296/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2296e528-d2e5-44de-adc4-59b385db22de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6085f54a2b97fcec30487b0cc58e2d57e3c83296/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4571934c-23c2-4ead-8752-50b397fb9bdd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e487a888f609049870c6a6f5c236f82cdc62bfe9/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3433d202-f6e4-4b81-bb2b-827958fad026) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-SDK.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e487a888f609049870c6a6f5c236f82cdc62bfe9/msteams-platform%2Ftoolkit%2FTeamsFx-SDK.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d414eb9d-af7c-47ba-879a-83a72d1fa958) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e487a888f609049870c6a6f5c236f82cdc62bfe9/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51f962b9-9389-448c-899d-a8f397ff99b8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
