### PR TITLE
[Doc Improvement][Remove time and future ref: 5][3886823]

### PR DESCRIPTION
**Pull request by v-deabira**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/analyze-your-apps-usage-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad67d337f99ccbde38475826960f2144ae529e7e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fanalyze-your-apps-usage-in-developer-portal.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c56c6145-6968-4759-b607-ebc14ad16127) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad67d337f99ccbde38475826960f2144ae529e7e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e3356c3-d605-4d45-91e6-85e2b608dc66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad67d337f99ccbde38475826960f2144ae529e7e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0575386-37b6-4290-850d-263864d7e2d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad67d337f99ccbde38475826960f2144ae529e7e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2fa47ae9-1b62-4847-881a-690f2537fce1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad67d337f99ccbde38475826960f2144ae529e7e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-from-web-apps.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60d98d02-90df-4b53-bc9c-dc1a998150b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad67d337f99ccbde38475826960f2144ae529e7e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be00f390-4dd2-42d1-83b7-6071bce364cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad67d337f99ccbde38475826960f2144ae529e7e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1830c35-cb62-4e61-bb69-2de3ee75a761) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad67d337f99ccbde38475826960f2144ae529e7e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1de3b74f-fa26-482e-a080-d8848477e188) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad67d337f99ccbde38475826960f2144ae529e7e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 129 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ca18b35-d95a-4447-9024-01d884580da2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad67d337f99ccbde38475826960f2144ae529e7e/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-process.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61f93bc3-5e49-4680-b309-2cea62a21061) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/analyze-your-apps-usage-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fad5183b6aae60f843c3434c892e3f002f439d83/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fanalyze-your-apps-usage-in-developer-portal.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9be97d5d-2297-4d82-872e-0398e01e74ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fad5183b6aae60f843c3434c892e3f002f439d83/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/efc1c797-d11c-4b28-9df2-a8e1768f3c64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fad5183b6aae60f843c3434c892e3f002f439d83/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04b99548-3901-40d9-ad7b-4fb817a646d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fad5183b6aae60f843c3434c892e3f002f439d83/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab075765-ec49-49b8-93e8-18b384c128e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fad5183b6aae60f843c3434c892e3f002f439d83/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-from-web-apps.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a269afe-cb94-486f-b263-677576bd32f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fad5183b6aae60f843c3434c892e3f002f439d83/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fe1b482-0e07-4d39-a746-a30c3d055c28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fad5183b6aae60f843c3434c892e3f002f439d83/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ce8126f-62b3-409e-8391-5d3233da1002) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fad5183b6aae60f843c3434c892e3f002f439d83/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8101daae-c624-432d-b042-cc6868f5793d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fad5183b6aae60f843c3434c892e3f002f439d83/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 129 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8694adc-874f-4977-8160-0d78690e97fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fad5183b6aae60f843c3434c892e3f002f439d83/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-process.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3139824-974e-4126-a938-ec7355853bf8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/analyze-your-apps-usage-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030b489643ab3158b07eea9cc5d435ba01da4f95/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fanalyze-your-apps-usage-in-developer-portal.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f40e0ba3-c342-47b7-9bd7-ba121cb5c58b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030b489643ab3158b07eea9cc5d435ba01da4f95/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62385ae7-13ad-470b-ac43-ce14a86d094c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030b489643ab3158b07eea9cc5d435ba01da4f95/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4af22a9-cc81-442b-98b0-cb570703bc58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030b489643ab3158b07eea9cc5d435ba01da4f95/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15ed8b1d-b6ee-4a47-a68c-36c60a21e1da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030b489643ab3158b07eea9cc5d435ba01da4f95/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-from-web-apps.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54cfd37d-d947-4af6-ad5b-8ae40191912b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030b489643ab3158b07eea9cc5d435ba01da4f95/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed42310a-2f2d-4ab6-b135-069ea30086ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030b489643ab3158b07eea9cc5d435ba01da4f95/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c7deff1-a773-4571-8323-57578491ad7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030b489643ab3158b07eea9cc5d435ba01da4f95/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55e96bfb-b694-4a62-b832-a08fc3901397) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030b489643ab3158b07eea9cc5d435ba01da4f95/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 130 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fafce54-781e-469b-bcb6-b0db021d9d22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030b489643ab3158b07eea9cc5d435ba01da4f95/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-process.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c96d6cfd-5e6c-49c8-bf6f-6d7c98f766ee) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-ypalikila — APPROVED** [review]
Approved.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/analyze-your-apps-usage-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f971c82a9a4218ee6f8d3f215e67a088302e66b8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fanalyze-your-apps-usage-in-developer-portal.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43d20e03-dc33-440a-bbbe-cfcc3bc1c4ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f971c82a9a4218ee6f8d3f215e67a088302e66b8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/615f2514-cdac-48d2-a471-57b850d6dafc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f971c82a9a4218ee6f8d3f215e67a088302e66b8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-teams.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ce87267-bf3d-4db2-853f-32409f2d4f5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-workflow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f971c82a9a4218ee6f8d3f215e67a088302e66b8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-workflow.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9a18bbe-76d2-4fe6-bc25-26c9acee02f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f971c82a9a4218ee6f8d3f215e67a088302e66b8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-from-web-apps.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81de2e2f-3dc7-4efe-9854-d1bbe2fc5ff8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f971c82a9a4218ee6f8d3f215e67a088302e66b8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshared-channels.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52b18b5a-4db3-479e-b4df-6d802189e669) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f971c82a9a4218ee6f8d3f215e67a088302e66b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7999da9-4b5b-4163-83cd-0a218106662e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f971c82a9a4218ee6f8d3f215e67a088302e66b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32ea3e41-df61-4e70-83e2-73368885392d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f971c82a9a4218ee6f8d3f215e67a088302e66b8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 130 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6263df59-e087-436c-bc1a-eb83c88eaded) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f971c82a9a4218ee6f8d3f215e67a088302e66b8/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-process.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1e670c6-75a5-423c-a26f-0d4b4b9b33d6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
