### PR TITLE
[Doc Improvement][SEO Description update][3939751]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/test-team-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b29a77cfd4a7a0e26975ba20d66235000ac14dca/msteams-platform%2Fgraph-api%2Frsc%2Ftest-team-rsc-json-file.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d1bed76-b98a-4353-bf27-01951860a609) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365-quick-start-guide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b29a77cfd4a7a0e26975ba20d66235000ac14dca/msteams-platform%2Fm365-apps%2Factions-in-m365-quick-start-guide.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20db24e5-f17c-4f0a-bfc4-5488422ddb70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b29a77cfd4a7a0e26975ba20d66235000ac14dca/msteams-platform%2Fm365-apps%2Factions-in-m365.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bcc3dccc-97c3-4852-a0fb-cbc2de819775) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/build-actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b29a77cfd4a7a0e26975ba20d66235000ac14dca/msteams-platform%2Fm365-apps%2Fbuild-actions-in-m365.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3513ac27-8e78-4d32-84c5-1e87ae4ca3a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b29a77cfd4a7a0e26975ba20d66235000ac14dca/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92a767fd-2b9e-41ec-bc4f-b6252910c3c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b29a77cfd4a7a0e26975ba20d66235000ac14dca/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/940d2807-2bb5-4c0b-ab43-f8418e7a5d8b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-meeting-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b29a77cfd4a7a0e26975ba20d66235000ac14dca/msteams-platform%2Fm365-apps%2Fextend-m365-meeting-app.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27fa2c90-e0ee-45d0-a573-88c354cbd67a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b29a77cfd4a7a0e26975ba20d66235000ac14dca/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8fae28b0-4b3a-40d3-b048-a8d9c63c4fa7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b29a77cfd4a7a0e26975ba20d66235000ac14dca/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be4d876a-0e24-4a42-80e0-1385ce62894e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b29a77cfd4a7a0e26975ba20d66235000ac14dca/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3cd41710-5dad-4486-908a-5b514a672550) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/test-team-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ee87db7dd216aaf07d66f710f57cf9092345055/msteams-platform%2Fgraph-api%2Frsc%2Ftest-team-rsc-json-file.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71cac882-eed0-4a07-91ba-9f04f727ebbe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365-quick-start-guide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ee87db7dd216aaf07d66f710f57cf9092345055/msteams-platform%2Fm365-apps%2Factions-in-m365-quick-start-guide.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f26e3544-e2ca-4501-ad6e-d62912ce74bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ee87db7dd216aaf07d66f710f57cf9092345055/msteams-platform%2Fm365-apps%2Factions-in-m365.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b14d4b53-ecce-4eb1-86a2-47e96f0b78ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/build-actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ee87db7dd216aaf07d66f710f57cf9092345055/msteams-platform%2Fm365-apps%2Fbuild-actions-in-m365.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4fad7c89-2434-48de-9c67-4ff30d04e737) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ee87db7dd216aaf07d66f710f57cf9092345055/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5f62f2b-2b22-4705-8639-24311fe29ad8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ee87db7dd216aaf07d66f710f57cf9092345055/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53029946-d63f-4156-8497-5117662e2938) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-meeting-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ee87db7dd216aaf07d66f710f57cf9092345055/msteams-platform%2Fm365-apps%2Fextend-m365-meeting-app.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a53f7ec-8138-4720-adea-be85259ad45f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ee87db7dd216aaf07d66f710f57cf9092345055/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/222be262-df5b-4131-ab1c-e52cb77b30f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ee87db7dd216aaf07d66f710f57cf9092345055/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97eb1fa9-d17a-461e-a745-6366bfc06c9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ee87db7dd216aaf07d66f710f57cf9092345055/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26e8de6e-5da5-4002-81d7-dfd59a068b69) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/test-team-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fae666e18d2de195bccbeb23f46be6ae376b548/msteams-platform%2Fgraph-api%2Frsc%2Ftest-team-rsc-json-file.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/978dc572-b304-4715-848e-e461923b39f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365-quick-start-guide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fae666e18d2de195bccbeb23f46be6ae376b548/msteams-platform%2Fm365-apps%2Factions-in-m365-quick-start-guide.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7337c54-ad27-4578-9267-5153027c0565) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fae666e18d2de195bccbeb23f46be6ae376b548/msteams-platform%2Fm365-apps%2Factions-in-m365.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18bd51c5-48ce-4125-a444-881365e9a8d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/build-actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fae666e18d2de195bccbeb23f46be6ae376b548/msteams-platform%2Fm365-apps%2Fbuild-actions-in-m365.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/238b8fee-8a65-4571-aa02-6e23fae325da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fae666e18d2de195bccbeb23f46be6ae376b548/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b3d6d09-da2c-4433-810f-848d291a0040) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fae666e18d2de195bccbeb23f46be6ae376b548/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9430360f-a898-443c-88bb-e73b1aea102c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-meeting-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fae666e18d2de195bccbeb23f46be6ae376b548/msteams-platform%2Fm365-apps%2Fextend-m365-meeting-app.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0813d494-cc8c-47a9-904a-6e3faeeb4fc8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fae666e18d2de195bccbeb23f46be6ae376b548/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1e0d714-9c97-4079-a2a6-d5ba11b1b35b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fae666e18d2de195bccbeb23f46be6ae376b548/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16758415-1759-4eca-a2df-a3e6d9936eb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fae666e18d2de195bccbeb23f46be6ae376b548/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d605c1ac-a464-41c4-a7c9-36e8baccbd85) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-preethah — APPROVED** [review]
Approved.

**Review by v-deabira — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/test-team-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/234109749f96c7dda0854c86bea33ec6d6ae7f5f/msteams-platform%2Fgraph-api%2Frsc%2Ftest-team-rsc-json-file.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/afa8727a-f4a9-49b4-9050-978c5fe8a736) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365-quick-start-guide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/234109749f96c7dda0854c86bea33ec6d6ae7f5f/msteams-platform%2Fm365-apps%2Factions-in-m365-quick-start-guide.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23784ae9-21bb-421a-9e96-02e28b95e825) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/234109749f96c7dda0854c86bea33ec6d6ae7f5f/msteams-platform%2Fm365-apps%2Factions-in-m365.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/354c1aa9-4ce7-4df5-ae74-1573b9dfb966) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/build-actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/234109749f96c7dda0854c86bea33ec6d6ae7f5f/msteams-platform%2Fm365-apps%2Fbuild-actions-in-m365.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/808410d7-1859-4085-9bab-d18438af1e76) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/234109749f96c7dda0854c86bea33ec6d6ae7f5f/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3961c82-9d94-435c-b2aa-f3e42242155e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/234109749f96c7dda0854c86bea33ec6d6ae7f5f/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/422e27d2-3364-41cf-bf3f-d62eacde85e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-meeting-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/234109749f96c7dda0854c86bea33ec6d6ae7f5f/msteams-platform%2Fm365-apps%2Fextend-m365-meeting-app.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fb156ee-0a3e-458d-8b30-8cfac9ede97b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/234109749f96c7dda0854c86bea33ec6d6ae7f5f/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb670a37-c0b2-4308-9d57-a061626d903e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/234109749f96c7dda0854c86bea33ec6d6ae7f5f/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ebd04bd-5834-4e6a-b133-55fc1d7563f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/234109749f96c7dda0854c86bea33ec6d6ae7f5f/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec0537e3-bd3e-4dd0-842b-faf360dbd3a1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
