### PR TITLE
[Doc Improvement][Task module to dialogs for design your app files][3472443]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ea639c3a35a61f2e18b9bdae34e45734840a8d5/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 90 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/818aad1d-ef67-47ce-bc52-04402ee8c4e7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/34d32f86abba74c0192f046c1bd1b40851288059/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 90 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1627bd54-bce6-4527-97db-26bd4adeb9ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/34d32f86abba74c0192f046c1bd1b40851288059/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 84 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a16873d-7e48-44dc-a53c-8c6ac3675414) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2eee3603851c5da9a36c8cc929ef1d3038223581/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b5126e0-c280-4703-a4ea-2c3c1cf39da6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2eee3603851c5da9a36c8cc929ef1d3038223581/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 94 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b2fab28-4be0-4b2c-8e53-fc87bc17aa48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2eee3603851c5da9a36c8cc929ef1d3038223581/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 90 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e765d811-0914-4fe3-9206-32bc28a93478) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2eee3603851c5da9a36c8cc929ef1d3038223581/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 84 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60e39a5b-4beb-4356-9ea5-37eb372e9a15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2eee3603851c5da9a36c8cc929ef1d3038223581/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a905a7b5-a23e-4725-8775-7f229fcaf5a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2eee3603851c5da9a36c8cc929ef1d3038223581/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29b824e5-fbc3-46a6-abb7-ca5763b0074e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a478dbbe8aaabea3b352b1b39042dc6055e3de2e/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80c76df6-1406-452d-868f-d07b75630c5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a478dbbe8aaabea3b352b1b39042dc6055e3de2e/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 94 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6128de86-0a90-40d1-9331-7a6abbde67ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a478dbbe8aaabea3b352b1b39042dc6055e3de2e/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 90 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5b72ff0-7996-48d5-8e93-8fff1dfcd6ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a478dbbe8aaabea3b352b1b39042dc6055e3de2e/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 84 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/147a20ef-554c-45d5-ba58-412c29bced8c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a478dbbe8aaabea3b352b1b39042dc6055e3de2e/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d703c0a1-59b9-4070-9ebc-983615912c32) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a478dbbe8aaabea3b352b1b39042dc6055e3de2e/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da13eb77-4846-4fec-b91d-56bd9d6f174b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e87a735bc03aefb1f402a82edb60bb3fa8411d92/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7832b20d-4fd0-403a-bebe-c9f83f1f4897) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e87a735bc03aefb1f402a82edb60bb3fa8411d92/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 94 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/746d27f1-0513-45cc-945e-3dc1d6b3ebdd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e87a735bc03aefb1f402a82edb60bb3fa8411d92/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 90 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/070e0fc2-1f85-4a81-97d0-53ca855e88bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e87a735bc03aefb1f402a82edb60bb3fa8411d92/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 84 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a1fb28e-629b-41cf-a080-f2abb8431765) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e87a735bc03aefb1f402a82edb60bb3fa8411d92/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6296f4e-363b-4307-ae79-992ad3b4a49c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e87a735bc03aefb1f402a82edb60bb3fa8411d92/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7623965-bf83-4ea9-83a4-d94f360e2009) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/31883d13d7d829a5996fb04d90a46c4563439cc1/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73fbb0fa-c632-4f5b-b7e1-033bd8c4c45c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31883d13d7d829a5996fb04d90a46c4563439cc1/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 94 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2aa97b8a-1dd8-430b-80b3-ad0162845a85) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31883d13d7d829a5996fb04d90a46c4563439cc1/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 90 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47ea873a-35c0-484b-b671-97d36670ce0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31883d13d7d829a5996fb04d90a46c4563439cc1/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 84 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dd75d9c-615f-4af4-a164-0056193edcb0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31883d13d7d829a5996fb04d90a46c4563439cc1/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a8d2f79-4072-40b9-8394-662ee686f38a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/31883d13d7d829a5996fb04d90a46c4563439cc1/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/208ee683-cf1c-427c-815e-06688782822c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
