### PR TITLE
[Doc Improvement][Verify and fix casing and sign in][3008097]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df0de059aad2b66cc0cd6c8f9d341bc83739d5f7/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ff144b2-2f6d-41bf-a368-cffad9279a69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/sideload-and-test-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df0de059aad2b66cc0cd6c8f9d341bc83739d5f7/msteams-platform%2Ftoolkit%2Fsideload-and-test-app.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2855de4e-e3f7-4f52-bf27-e5ce8be28be5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df0de059aad2b66cc0cd6c8f9d341bc83739d5f7/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3ca5066-c654-4a89-933e-d0e6f728504d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df0de059aad2b66cc0cd6c8f9d341bc83739d5f7/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c2de56d-957e-46fa-ad95-7eba5aac4a28) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Integrate-with-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2767fee8149dff1da04afaa80ac5473a1ab917fa/msteams-platform%2Ftoolkit%2FIntegrate-with-developer-portal.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1839a1cc-a8d0-4e6e-976a-e042fcdf8a3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2767fee8149dff1da04afaa80ac5473a1ab917fa/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2512e94-29d1-4839-a947-23cb747db551) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2767fee8149dff1da04afaa80ac5473a1ab917fa/msteams-platform%2Ftoolkit%2Ffaq.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddaa69a6-6e7a-4546-958e-2d29102ea246) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2767fee8149dff1da04afaa80ac5473a1ab917fa/msteams-platform%2Ftoolkit%2Fpublish.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/989409d9-942f-4c76-8615-4c84b444a1c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/sideload-and-test-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2767fee8149dff1da04afaa80ac5473a1ab917fa/msteams-platform%2Ftoolkit%2Fsideload-and-test-app.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5de47160-8692-438e-9f73-ff1afbd4e1c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2767fee8149dff1da04afaa80ac5473a1ab917fa/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1dc4ead2-f36f-418b-9071-842932d48ed3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2767fee8149dff1da04afaa80ac5473a1ab917fa/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/429a384f-a14b-42b4-a3d2-5838a8fd3f63) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Integrate-with-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc022aaf61899f34d145db10aaf3e3d3f8df5131/msteams-platform%2Ftoolkit%2FIntegrate-with-developer-portal.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/920585cd-c711-43bd-93aa-ee408c47571a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc022aaf61899f34d145db10aaf3e3d3f8df5131/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3eb0855-72e5-4257-a958-b304569fdbe1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc022aaf61899f34d145db10aaf3e3d3f8df5131/msteams-platform%2Ftoolkit%2Ffaq.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0fe77e5f-ad31-4d84-a8fe-76c57569b4fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc022aaf61899f34d145db10aaf3e3d3f8df5131/msteams-platform%2Ftoolkit%2Fpublish.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0464e8c-98d5-4de5-b974-ff6e9ce587c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/sideload-and-test-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc022aaf61899f34d145db10aaf3e3d3f8df5131/msteams-platform%2Ftoolkit%2Fsideload-and-test-app.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cffa6f1d-43e2-4279-8b55-717b36ef1e99) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc022aaf61899f34d145db10aaf3e3d3f8df5131/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f83e40c-5976-4588-aefb-7fd015aeaa3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc022aaf61899f34d145db10aaf3e3d3f8df5131/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23cc4cae-4884-48a4-9a13-0dcfd7171533) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/21c5146ac8cb0637d477eb8c5550db8854cbd0a6/msteams-platform%2Ftoolkit%2Ffaq.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3db7eaaf-3a5e-4bc1-8e41-8a3619a37450) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/21c5146ac8cb0637d477eb8c5550db8854cbd0a6/msteams-platform%2Ftoolkit%2Fpublish.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7dcbcd1-815e-4752-bf9e-e8635e164a10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/21c5146ac8cb0637d477eb8c5550db8854cbd0a6/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/433972b3-0b1c-43a4-8561-756bea85c96d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/21c5146ac8cb0637d477eb8c5550db8854cbd0a6/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15a7a715-b0a3-4198-a78b-7bbb6a48c8a2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8e4fedebb88d8186cf2ad5db5672cf08ae865c2/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24dd7e56-35d4-493a-b20b-250955600958) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8e4fedebb88d8186cf2ad5db5672cf08ae865c2/msteams-platform%2Ftoolkit%2Ffaq.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e81ab3cd-7430-48f8-abfc-05fd5c04960f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8e4fedebb88d8186cf2ad5db5672cf08ae865c2/msteams-platform%2Ftoolkit%2Fpublish.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c686c8d-866b-4454-b1df-c196cd7fefbe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8e4fedebb88d8186cf2ad5db5672cf08ae865c2/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0eee5e33-15be-421e-9753-9576c5e7a6bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8e4fedebb88d8186cf2ad5db5672cf08ae865c2/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d994fe89-cbcd-47e7-8b74-021bac1ddfee) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-collaboration.md](https://github.com/MicrosoftDocs/msteams-docs/blob/09c579fd2c9091357ca3cd1d021d67dbf760d544/msteams-platform%2Ftoolkit%2FTeamsFx-collaboration.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75e21230-3f4a-4cf9-ac2a-20d3d98c04c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/09c579fd2c9091357ca3cd1d021d67dbf760d544/msteams-platform%2Ftoolkit%2Ffaq.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe91fbc0-cb78-48d0-8bc4-084ee1970254) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/09c579fd2c9091357ca3cd1d021d67dbf760d544/msteams-platform%2Ftoolkit%2Fpublish.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4672ad92-4d16-40ec-9580-fbf599b67b2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/09c579fd2c9091357ca3cd1d021d67dbf760d544/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2cccffeb-91a6-4bc5-9ecf-4fff42783141) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/09c579fd2c9091357ca3cd1d021d67dbf760d544/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 95 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a11e8dc-8329-4669-ad1c-37bf1467787e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
