### PR TITLE
[Bots][Insallupdateeventsadded][1208146]

### PR DESCRIPTION
**Pull request by KirtiPereira**

### CODE REVIEW

**Comment by KirtiPereira** [comment]
@ojasvichoudhary - please go through the draft and let me know your comments. 
**Please note**, builds are not being generated due to some technical glitch. Therefore, request you to check the **Files changed** tab for reviewing the updated section of the file.
Thank you.

**Comment by KirtiPereira** [comment]
Hi @ojasvichoudhary - kindly review and share your comments / approval on the PR.
Thank you.

**Comment by surbhigupta12** [comment]
Hi @ojasvichoudhary - kindly review and share your comments / approval on the PR.
Thank you.

**Comment by KirtiPereira** [comment]
Hi @ojasvichoudhary - gentle reminder to review and share your comments / approval on the PR.
Thank you.

**Review by ojasvichoudhary — DISMISSED** [review]

**Review by surbhigupta12 — DISMISSED** [review]
Approving the PR

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
