### PR TITLE
[Doc Improvement][SBS guide testing and update for Teams connector guide VS changes][3264916]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b6391ada7158901c659adcd7d0c7447e5ce147e3/msteams-platform%2Fsbs-teams-connectors.yml) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23ac90c1-1494-42d6-a5f6-a7131d289c5a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/31d38186ce3b152d09ce6cd68c864ba3bbc8cae1/msteams-platform%2Fsbs-teams-connectors.yml) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/461f465a-08c1-4b44-9574-47e3ebbe9084) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d64bb02e8f32dd0c744455134d1995d7ecd62404/msteams-platform%2Fsbs-teams-connectors.yml) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75bb6454-f46f-4bd3-8880-d810d5b5ea96) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/618ce744b6ec5db7da4bfa35bf836b82f6d1ab7c/msteams-platform%2Fsbs-teams-connectors.yml) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a06cea70-fe00-4a9e-bc07-e0873721e35d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c59ed332f8f207f5193d86b5c1d79c6db7895c97/msteams-platform%2Fsbs-teams-connectors.yml) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2600a9a6-88d1-4e08-aa7f-b74450219a42) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/10844e0924321f981285bb3b4db3fa2f7fba2ccb/msteams-platform%2Fsbs-teams-connectors.yml) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b51c942d-9f0e-441a-8214-4c18a3b6effa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/38f353b08a203ef687c832347ed4ee5616307ac2/msteams-platform%2Fsbs-teams-connectors.yml) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e304111-d73a-4730-80aa-797ebd35d762) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4d080254dff3d4eb35926622b31dffea81291aae/msteams-platform%2Fsbs-teams-connectors.yml) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/228774f6-b1ac-464e-b31c-9767d07cafa4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/17169fa0f96077aa1a80178aa33da79edefd5d7e/msteams-platform%2Fsbs-teams-connectors.yml) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cec18d7f-888b-42a4-88d6-d3a67057c47d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e8f6d10742e6d1ee45a57cc84c97dc6b2e43a8bb/msteams-platform%2Fsbs-teams-connectors.yml) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c672e8f5-d7c9-42e4-9513-3ed50703478b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/10252f0294680b85654fed2094bd6eb485f69cd8/msteams-platform%2Fsbs-send-proactive.yml) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a3f1dc7-b609-48b4-8c2b-eff2668b1e06) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/10252f0294680b85654fed2094bd6eb485f69cd8/msteams-platform%2Fsbs-teams-connectors.yml) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5dab9b9a-5fad-4dc1-8c3d-d96271a75e34) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c5ed1b492d54003e69a17c1ae50e29d1ac22109c/msteams-platform%2Fsbs-send-proactive.yml) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33283c19-78f8-45b8-a4e3-357d25731054) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c5ed1b492d54003e69a17c1ae50e29d1ac22109c/msteams-platform%2Fsbs-teams-connectors.yml) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0755cac9-f9f9-4562-9bce-f60b7181c265) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e71b9eb6a4a08d089019b893f492ccdb1f6a4ab6/msteams-platform%2Fsbs-send-proactive.yml) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d5e6cb0-1095-4ff8-a340-de8f85ad99d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e71b9eb6a4a08d089019b893f492ccdb1f6a4ab6/msteams-platform%2Fsbs-teams-connectors.yml) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/213e0769-fb0b-4ccb-b14e-03116186a644) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b87bef84694264f704797d152faa2acbb63ff077/msteams-platform%2Fsbs-send-proactive.yml) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/753511f8-d7a2-484b-be80-9769486e5022) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b87bef84694264f704797d152faa2acbb63ff077/msteams-platform%2Fsbs-teams-connectors.yml) | 88 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/812f7cc7-925c-46ac-abe2-d193d643a81c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b4fb9f1cc5ab34250312c24796b7442ebb2a3ac/msteams-platform%2Fsbs-send-proactive.yml) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/047f8ada-de33-489e-ba92-7a2a9647c7f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b4fb9f1cc5ab34250312c24796b7442ebb2a3ac/msteams-platform%2Fsbs-teams-connectors.yml) | 88 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77cdfb5e-bb35-430a-92a9-0e849bbdb56d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e7f042950e23fc0a21367a198bdb462d3fa336aa/msteams-platform%2Fsbs-send-proactive.yml) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dffc4493-9b41-46f2-93c7-dbca248008a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e7f042950e23fc0a21367a198bdb462d3fa336aa/msteams-platform%2Fsbs-teams-connectors.yml) | 88 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d882d836-119e-4ab0-ae84-fa27a7b4dd6e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/401da86f7b4b222fa3300e48efbe54b36a349f4d/msteams-platform%2Fsbs-send-proactive.yml) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/128b312c-e921-4ff4-974d-063f9eea8545) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/401da86f7b4b222fa3300e48efbe54b36a349f4d/msteams-platform%2Fsbs-teams-connectors.yml) | 88 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cf33bb7-faa1-45cf-8b85-e32cc19cf1d4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4888858e8b83f1ac63c7b375300867578ab6e2b8/msteams-platform%2Fsbs-send-proactive.yml) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85b2500b-25e0-403a-a41e-a2758d396b6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4888858e8b83f1ac63c7b375300867578ab6e2b8/msteams-platform%2Fsbs-teams-connectors.yml) | 88 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ec1bff8-da64-4a45-b720-39e9c06e15ed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4888858e8b83f1ac63c7b375300867578ab6e2b8/msteams-platform%2Fwhats-new.md) | 94 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bce4b045-375b-412a-97ec-8bb4762253fa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
