### PR TITLE
 [Doc Improvement][Teams 2.1 update][3417009]

### PR DESCRIPTION
**Pull request by v-bvishnu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f55c8021a4cfefb8f3f7c420b9eac135e37fa8f6/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-bot.md) | 86 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/506b61d3-3845-4efb-8169-2f5ed5251808) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f55c8021a4cfefb8f3f7c420b9eac135e37fa8f6/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/910c48d4-84ee-4c25-a4bc-f9af9be88335) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f55c8021a4cfefb8f3f7c420b9eac135e37fa8f6/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa5a70ec-53ed-48b1-bcce-c00464399439) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f55c8021a4cfefb8f3f7c420b9eac135e37fa8f6/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 98 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7a68112-32a3-4243-832f-0dd6ff0816aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f55c8021a4cfefb8f3f7c420b9eac135e37fa8f6/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 97 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f05bf09-7512-4158-818a-bc60447b6197) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/859de6023f09f5908629611f7842feb94e1ff67a/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-bot.md) | 86 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5cf8de1-a9f0-4a06-8b25-ce588cff23f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/859de6023f09f5908629611f7842feb94e1ff67a/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23012686-c691-43d1-9635-c9f0642fd026) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/859de6023f09f5908629611f7842feb94e1ff67a/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9465ead3-3eb4-44c9-aa30-fff18274871a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/859de6023f09f5908629611f7842feb94e1ff67a/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 96 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c366f55-962e-468c-b220-074486709c65) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/859de6023f09f5908629611f7842feb94e1ff67a/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 97 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51b57931-bff1-4731-80f6-e5170d4f9fc9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d0b551c75e68f185219e62c69b809146311027af/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-bot.md) | 86 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6caecf75-3df5-4105-819e-4512d99dcfd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d0b551c75e68f185219e62c69b809146311027af/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60540d14-b70c-4674-bef0-50c2a6050be7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d0b551c75e68f185219e62c69b809146311027af/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37dfdee7-b1f0-4de0-99ec-c180bdbcd636) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d0b551c75e68f185219e62c69b809146311027af/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 96 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e4a120a-02b8-4ca4-bb77-691c5439ae50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d0b551c75e68f185219e62c69b809146311027af/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 97 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87bb3563-8a88-4f8b-b975-6883c6e75975) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5491513f2f1d5141e7ee0ddbf02aee5122c818c/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-bot.md) | 86 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/583c3b43-5982-49d8-9f05-04adb5f376d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5491513f2f1d5141e7ee0ddbf02aee5122c818c/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9ab7c0a-04ee-4fca-89a7-a9d0f61508a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5491513f2f1d5141e7ee0ddbf02aee5122c818c/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6ad3e9a-0756-4d34-8312-53cea1858edc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98c268ead2bfd505ee8f0654b1395426298b5f09/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-bot.md) | 84 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a47ed33b-76a2-407c-a8d5-e2d39df5de85) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98c268ead2bfd505ee8f0654b1395426298b5f09/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0aa106bf-5f85-47bc-8964-3215da9ab7c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/98c268ead2bfd505ee8f0654b1395426298b5f09/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10dad0d5-122d-4a7d-8fcd-4f2c50e8ef89) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/21a6940871589d32af0f2205255437d41da38e27/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-bot.md) | 84 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7bf8bf3d-3c67-4202-a2f1-5278381eb7f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/21a6940871589d32af0f2205255437d41da38e27/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37599cc4-8951-4ff8-abc1-6c691f530a19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/21a6940871589d32af0f2205255437d41da38e27/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/505894b9-e02a-432f-9ca0-ac4e65994403) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/645616ff2b2b08b0b04d001e27d1d4dc44bc7ec6/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-bot.md) | 84 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbda7be3-7fc3-4b21-a4e0-244f0a0759ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/645616ff2b2b08b0b04d001e27d1d4dc44bc7ec6/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c686fa8a-b4ab-4a97-8d45-117826b6b36b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/645616ff2b2b08b0b04d001e27d1d4dc44bc7ec6/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/443031f4-239f-434c-8cde-fa7f0035f62f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b638a88cc0c4c727ca9ed20a998712caaac6667/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-bot.md) | 84 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5782689f-6a45-4a82-afec-66523425ff82) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b638a88cc0c4c727ca9ed20a998712caaac6667/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53efd9d9-9a31-4985-884d-b311fb5b16d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b638a88cc0c4c727ca9ed20a998712caaac6667/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdcfdc13-0d90-40b8-89ba-20ddc23bb335) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
