### PR TITLE
Doc update for Microsoft 365 Client Application IDs table

### PR DESCRIPTION
**Pull request by JoshuaPartlow**
Consolidates Microsoft 365 Client Application IDs (and associated note) into an include for single sourcing between topics.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/tabs/microsoft-365-client-application-ids.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b101b1db4c15788e234c4c57cc73316e4956e8cd/msteams-platform%2Fincludes%2Ftabs%2Fmicrosoft-365-client-application-ids.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96914e1b-eee8-425f-9330-424b07a261b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b101b1db4c15788e234c4c57cc73316e4956e8cd/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f0086ba-e029-4a11-ab0f-9241a70afe0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b101b1db4c15788e234c4c57cc73316e4956e8cd/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-register-aad.md) | 91 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aae2576e-24c3-4434-b498-d939b97ea7a1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by JoshuaPartlow** [comment]
@erikadoyle for awareness.

**Review by erikadoyle — APPROVED** [review]
Nice improvement, thanks!

**Review by v-npaladugu — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/tabs/microsoft-365-client-application-ids.md](https://github.com/MicrosoftDocs/msteams-docs/blob/13af1d22235623d436d5e98c741860e2b3cbad61/msteams-platform%2Fincludes%2Ftabs%2Fmicrosoft-365-client-application-ids.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c3c1e69-10a7-4194-98a9-e55cb0147d73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/13af1d22235623d436d5e98c741860e2b3cbad61/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba74d409-6454-4920-9b95-eae704a7fa2c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/13af1d22235623d436d5e98c741860e2b3cbad61/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-register-aad.md) | 92 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87ebc61a-59ba-4028-a972-31e798dc5bfb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
