### PR TITLE
remove extra whitespace

### PR DESCRIPTION
**Pull request by paul-cheung**

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[935593e](https://github.com/paul-cheung/msteams-docs/pull/561/commits/935593e0b05b60d4560c66419ecbf16460c29ecf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/apps/apps-package.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/apps/apps-package.md) | :warning:Warning | | [Details](#user-content-8952bf45-bdc47462)
[msteams-platform/concepts/connectors/connectors-using.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/connectors/connectors-using.md) | :warning:Warning | | [Details](#user-content-3fa6b002-bdc47462)
[msteams-platform/resources/schema/manifest-schema-migrate.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/resources/schema/manifest-schema-migrate.md) | :warning:Warning | | [Details](#user-content-1e1fdebf-bdc47462)
[msteams-platform/concepts/messaging-extensions/search-extensions.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/messaging-extensions/search-extensions.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | |

<a id="8952bf45-bdc47462"></a>
### [msteams-platform/concepts/apps/apps-package.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/apps/apps-package.md)
 - **Line 10**: **[Warning]** Invalid file link:(~/concepts/apps/apps-upload).
 - **Line 19**: **[Warning]** Invalid file link:(~/get-started/get-started-app-studio).
 - **Line 21**: **[Warning]** Invalid file link:(~/resources/schema/manifest-schema).
 - **Line 60**: **[Warning]** Invalid file link:(~/troubleshoot/troubleshoot).

<a id="3fa6b002-bdc47462"></a>
### [msteams-platform/concepts/connectors/connectors-using.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/connectors/connectors-using.md)
 - **Line 33**: **[Warning]** Invalid file link:(~/concepts/cards/cards).
 - **Line 186**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package#icons).
 - **Line 251**: **[Warning]** Invalid file link:(~/publishing/apps-publish).

<a id="1e1fdebf-bdc47462"></a>
### [msteams-platform/resources/schema/manifest-schema-migrate.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/resources/schema/manifest-schema-migrate.md)
 - **Line 9**: **[Warning]** Invalid file link:(~/resources/schema/manifest-schema-v04).
 - **Line 19**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package#icons).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904120558534899-561%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QPtm2dDh0%2B468DmE8a8w%2F%2FoMPaqp3x8FlmuEOmaRB30%3D&st=2019-04-12T05%3A55%3A24Z&se=2019-05-13T06%3A00%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[26e7d16](https://github.com/paul-cheung/msteams-docs/pull/561/commits/26e7d16a953ab0cd0b25d0506d4286ec7cd08306)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/connectors/connectors-using.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/connectors/connectors-using.md) | :warning:Warning | | [Details](#user-content-3fa6b002-8274d540)
[msteams-platform/resources/schema/manifest-schema-migrate.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/resources/schema/manifest-schema-migrate.md) | :warning:Warning | | [Details](#user-content-1e1fdebf-8274d540)
[msteams-platform/concepts/apps/apps-package.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/apps/apps-package.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/messaging-extensions/search-extensions.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/messaging-extensions/search-extensions.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | |

<a id="3fa6b002-8274d540"></a>
### [msteams-platform/concepts/connectors/connectors-using.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/connectors/connectors-using.md)
 - **Line 33**: **[Warning]** Invalid file link:(~/concepts/cards/cards).
 - **Line 186**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package#icons).
 - **Line 251**: **[Warning]** Invalid file link:(~/publishing/apps-publish).

<a id="1e1fdebf-8274d540"></a>
### [msteams-platform/resources/schema/manifest-schema-migrate.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/resources/schema/manifest-schema-migrate.md)
 - **Line 9**: **[Warning]** Invalid file link:(~/resources/schema/manifest-schema-v04).
 - **Line 19**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package#icons).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904121710296660-561%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=m3%2FCEZnTIrKldYvHlu2dU2t0AgnMrmS3I4xCBVmbgiw%3D&st=2019-04-12T17%3A07%3A06Z&se=2019-05-13T17%3A12%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[d40949d](https://github.com/paul-cheung/msteams-docs/pull/561/commits/d40949db6c88fde04fcbb2b17af3c3726f65731e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/resources/schema/manifest-schema-migrate.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/resources/schema/manifest-schema-migrate.md) | :warning:Warning | | [Details](#user-content-1e1fdebf-27d64994)
[msteams-platform/concepts/apps/apps-package.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/apps/apps-package.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/connectors/connectors-using.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/connectors/connectors-using.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/messaging-extensions/search-extensions.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/messaging-extensions/search-extensions.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | |

<a id="1e1fdebf-27d64994"></a>
### [msteams-platform/resources/schema/manifest-schema-migrate.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/resources/schema/manifest-schema-migrate.md)
 - **Line 9**: **[Warning]** Invalid file link:(~/resources/schema/manifest-schema-v04).
 - **Line 19**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package#icons).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904121712370397-561%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VPDnw46qm9Q%2BW3EMcy03VndTd8aejdVZpI4iUpO2phg%3D&st=2019-04-12T17%3A09%3A03Z&se=2019-05-13T17%3A14%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[8ae1549](https://github.com/paul-cheung/msteams-docs/pull/561/commits/8ae15493a1261300ea88682bdf1094764c84c0f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/apps/apps-package.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/apps/apps-package.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/connectors/connectors-using.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/connectors/connectors-using.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/messaging-extensions/search-extensions.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/concepts/messaging-extensions/search-extensions.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/schema/manifest-schema-migrate.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/resources/schema/manifest-schema-migrate.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/schema/manifest-schema.md](https://github.com/paul-cheung/msteams-docs/blob/remove-whitespace/msteams-platform/resources/schema/manifest-schema.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904121715168945-561%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WVLyC6tRpW43Ot8uE3vwwNIjQ4negsIhDgPA%2FX7CoLo%3D&st=2019-04-12T17%3A11%3A40Z&se=2019-05-13T17%3A16%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clearab** [comment]
Thanks for the help!

**Pull request merged**
