### PR TITLE
Improve doc per customer feedback

### PR DESCRIPTION
**Pull request by blackchoey**
This PR resolves 2 feedbacks:
1. Customer does not know where should put the `auth` property mentioned in this doc. This PR adds more context for the `auth` property.
2. Customer does not know where to get the real values for the properties. This PR makes the reference doc more obvious for customer's scenario.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2e341b490f0a743aa7d151b282ddc3fab13e71b/msteams-platform%2Ftoolkit%2Fprovision.md) | 95 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bc48105-75d8-44f2-9607-e66fbe0d9477) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1aae929dfbbcdcfa28bdf5d04c19468ad8bbd026/msteams-platform%2Ftoolkit%2Fprovision.md) | 95 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6edcbcc0-1314-4b37-9a2c-5de3cdbb1d80) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f06d608f1568edc1258b4c450caf0fb88006664/msteams-platform%2Ftoolkit%2Fprovision.md) | 95 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57137db8-c313-4104-9e91-fec73f955bbf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Review by MuyangAmigo — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1bb28e3870e1a7e859ee8c32aaf95957e9391307/msteams-platform%2Ftoolkit%2Fprovision.md) | 96 | 60 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ce3578a-3ddb-403b-b4d2-eaed54a4a92a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/331e9bca0563044be79a14e13c58dc055e301a36/msteams-platform%2Ftoolkit%2Fprovision.md) | 96 | 60 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff02f47f-dd40-4606-b419-8d35730cfa58) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
