### PR TITLE
[Doc Improvement][Tools and SDKs Teams Toolkit]

### PR DESCRIPTION
**Pull request by v-amprasad**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/67a7a755b096b75928fcb2d3a216bda724ff6853/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d82f5fae-2201-4a71-befb-36ae21b87bc0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6676ac2c8d7c01c9d7d86cd9c1daf20ac56dd7c7/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d3a5c4c-0cb9-458f-a143-d28defa7092a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6676ac2c8d7c01c9d7d86cd9c1daf20ac56dd7c7/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dca90ca4-8965-479f-a5f1-1b1b9bac3640) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa5f15fc8fe6cf419bae0c90fef656fa1f155c3/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/344f49e1-60b6-4797-bce8-c11c2ccbef3c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa5f15fc8fe6cf419bae0c90fef656fa1f155c3/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/387a23d3-cc4a-4a6b-bcb5-179c898acfd4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa5f15fc8fe6cf419bae0c90fef656fa1f155c3/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ddc189c-12fe-4a60-9933-19b850cc3079) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/886d387d0f4de24e3515ed2af61e2e34f39b9707/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f7ed0e6-58a0-4988-b4d3-92140df16e2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/886d387d0f4de24e3515ed2af61e2e34f39b9707/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f45043dc-4ef8-49ec-b3db-fd9ccb674710) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/886d387d0f4de24e3515ed2af61e2e34f39b9707/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9bcde6a5-57da-41d6-b6cb-63136e68ad65) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/953c9f7db9bda888d08990340c88eec9a8daf6da/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a1ba3ff-8016-48cb-8845-6393ff14403a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/953c9f7db9bda888d08990340c88eec9a8daf6da/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d734f6a-be31-4192-be7b-190fa21773a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/953c9f7db9bda888d08990340c88eec9a8daf6da/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9873c5e0-d88f-4466-8cc1-a504b34ed580) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8df803d8e00f32e7917be60b98d706602278c721/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77ce5d8f-d206-44e3-9630-f2bc0edf9d78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8df803d8e00f32e7917be60b98d706602278c721/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b575caaf-c787-4d6c-a62d-91142adf8f62) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8df803d8e00f32e7917be60b98d706602278c721/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db0c812d-d4c8-47df-a37b-a943e8980f32) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8df803d8e00f32e7917be60b98d706602278c721/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8104f462-48d5-4000-b194-fce73eddebca) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/867a706fcfdffb67c472f6b154f2e5cb4d9fbcb8/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/637349d6-ee6f-4496-b59e-d029d9dc3ac0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/867a706fcfdffb67c472f6b154f2e5cb4d9fbcb8/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e41ca787-09f9-4740-94b9-d81d41e6f062) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/867a706fcfdffb67c472f6b154f2e5cb4d9fbcb8/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7330262-4655-4bb8-a6be-590cd228c837) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]

**Pull request merged**
