### PR TITLE
[Doc Improvement][Update content-security-policy-headers]

### PR DESCRIPTION
**Pull request by v-shalinir**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/tabs/content-security-policy-headers.md](https://github.com/MicrosoftDocs/msteams-docs/blob/803d9da330319e95e19a471f0367d22871233552/msteams-platform%2Fincludes%2Ftabs%2Fcontent-security-policy-headers.md) | 82 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b10ca62-8f3b-412a-b698-02e37d30b6e4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/tabs/content-security-policy-headers.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93abf6982e070c6cd73960f45f3e9daa7589572e/msteams-platform%2Fincludes%2Ftabs%2Fcontent-security-policy-headers.md) | 84 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6559de66-95ea-4afd-88e6-8e2eb6026f4b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/review-copilot-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02f1a98ee5dc1023c791913fb6b3bd665b5215ed/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Freview-copilot-validation-guidelines.md) | 84 | 60 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08276a3f-eeaf-48b0-a8e1-23cfd271b49c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/content-security-policy-headers.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02f1a98ee5dc1023c791913fb6b3bd665b5215ed/msteams-platform%2Fincludes%2Ftabs%2Fcontent-security-policy-headers.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a0eff86-e462-4dcf-b9b4-238e69fcdf36) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/review-copilot-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32d329486e44be13429370b295f8cbd06cf95c7b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Freview-copilot-validation-guidelines.md) | 84 | 60 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/763f3884-2549-4c85-8f8a-31f9ac804f20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/content-security-policy-headers.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32d329486e44be13429370b295f8cbd06cf95c7b/msteams-platform%2Fincludes%2Ftabs%2Fcontent-security-policy-headers.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3c5cf75-d0a6-42ba-b3ce-e4a72af47b55) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Review by ramendhe — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/review-copilot-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/121a3eb4e399e69801a4d9b08e14d6c3db51cc6f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Freview-copilot-validation-guidelines.md) | 84 | 60 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c54cdc66-c0f7-415a-afa0-b4fe71af034d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/content-security-policy-headers.md](https://github.com/MicrosoftDocs/msteams-docs/blob/121a3eb4e399e69801a4d9b08e14d6c3db51cc6f/msteams-platform%2Fincludes%2Ftabs%2Fcontent-security-policy-headers.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc675313-cb9f-4f57-8cd7-7c837fb9a43d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-shalinir** [comment]
@ramendhe has approved the PR.

**Review by surbhigupta12 — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
