### PR TITLE
[Doc Improvement][Systemdefault is public preview][3591037]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6cafeada30bb754aaccead7c9e841e5e5e7463b/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cb69b48-fdfa-46c1-b363-afdb126b7ba5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e0a984b194dd527a3e3db0d4ca4519809a117876/msteams-platform%2Fmstdd-landing.yml) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f632b38-2249-48b0-835c-decb6b3ab6e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0a984b194dd527a3e3db0d4ca4519809a117876/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 91 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3bccb957-8656-458f-bcec-b85150c045a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0a984b194dd527a3e3db0d4ca4519809a117876/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 91 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/542e1d4e-3792-4667-9c72-667b42b930f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0a984b194dd527a3e3db0d4ca4519809a117876/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d45c09c5-567b-4dae-b82d-2ca215aa4a68) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0a984b194dd527a3e3db0d4ca4519809a117876/msteams-platform%2Fwhats-new.md) | 94 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e956e0c-5e82-4368-9be3-76685603b9f3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Review by luywang — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0b1ef16ad4bfe7ee09bcc1f1ef0ec5cebabcd90a/msteams-platform%2Fmstdd-landing.yml) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb17d2ed-2eb4-4cac-9c33-5e096aa17808) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b1ef16ad4bfe7ee09bcc1f1ef0ec5cebabcd90a/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 91 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09f63ca7-b8f8-4087-be6b-71edddb5b6c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b1ef16ad4bfe7ee09bcc1f1ef0ec5cebabcd90a/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 91 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/def3ccf1-7bd7-4560-b003-df41d59481dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b1ef16ad4bfe7ee09bcc1f1ef0ec5cebabcd90a/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3efd82c-e864-45df-9848-b76fcba04755) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b1ef16ad4bfe7ee09bcc1f1ef0ec5cebabcd90a/msteams-platform%2Fwhats-new.md) | 94 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccdff2a7-0f39-4d45-8aa2-73423e3e5e75) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bed674c29b818c92087a07c768c61b07dc19823b/msteams-platform%2Fmstdd-landing.yml) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/033f6e46-fe08-4d30-9cc2-3387918353c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bed674c29b818c92087a07c768c61b07dc19823b/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 91 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a59af816-3399-44f3-85e7-6d6e5e78df10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bed674c29b818c92087a07c768c61b07dc19823b/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 91 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae2011fd-fa32-4fb1-aff4-865d25912751) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bed674c29b818c92087a07c768c61b07dc19823b/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f43cb5ab-aa3d-4a9a-b0e8-c40158be83db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bed674c29b818c92087a07c768c61b07dc19823b/msteams-platform%2Fwhats-new.md) | 95 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e8c6510-1334-48e0-957e-f4552a945866) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4c9e6f25831b6742ec25e08216df62493e27d50e/msteams-platform%2Fmstdd-landing.yml) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a8ed12b-89c7-459c-b179-bf8316d4103b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c9e6f25831b6742ec25e08216df62493e27d50e/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 91 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b992ca72-47b0-41e5-b4d8-6b6d5fbd8f2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c9e6f25831b6742ec25e08216df62493e27d50e/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 91 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa1c294e-5079-4fe3-a02d-f67220ed48ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/send-activity-feed-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c9e6f25831b6742ec25e08216df62493e27d50e/msteams-platform%2Ftabs%2Fsend-activity-feed-notification.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ae2f541-7db3-4f61-a8a4-da25382483fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c9e6f25831b6742ec25e08216df62493e27d50e/msteams-platform%2Fwhats-new.md) | 95 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e385993c-4775-4195-ac45-1b2d7aaa51a2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
