### PR TITLE
[Doc Improvement][Update add authentication]

### PR DESCRIPTION
**Pull request by v-habibaumme**
minor edits

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b41ae8ce0343dbb230143dfed02da8a419af4eb3/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fadd-authentication.md) | 85 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c84e853d-7d02-45de-b8a1-fe29250dac4b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cec12471772f04a6f271eb7ca77ee4e87aa27118/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fadd-authentication.md) | 86 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb55e1ee-8664-4e74-ac12-a369a1f085d9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/07cef7886b0a833ed613dfd9d28af8e3a3cdbda3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b9c8013-e88f-4aaf-b6e8-d3d62dd10802) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/07cef7886b0a833ed613dfd9d28af8e3a3cdbda3/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fadd-authentication.md) | 86 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/167691ae-7184-435c-bf4a-954010d9b1a9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3d4525ad8a0a789adaed9632de8f343127aaf89/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18d9bc74-89cc-4511-870f-aac860f8efed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3d4525ad8a0a789adaed9632de8f343127aaf89/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fadd-authentication.md) | 86 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e866a10-b244-44b3-96d9-2579baf29b46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f3d4525ad8a0a789adaed9632de8f343127aaf89/msteams-platform%2Fresources%2Fbot-v3%2Fbots-test.md) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f0625d2-d079-4fbc-84fb-70b310c425d4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9bf4768587fc83aafe761dff73f594e734982031/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca1bfec9-d58a-455e-89eb-493ee88d7236) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9bf4768587fc83aafe761dff73f594e734982031/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fadd-authentication.md) | 86 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87965159-59f3-4697-b531-32dd90523996) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9bf4768587fc83aafe761dff73f594e734982031/msteams-platform%2Fresources%2Fbot-v3%2Fbots-test.md) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfd6d149-d8a7-4f8f-96e2-be71ff52b044) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9bf4768587fc83aafe761dff73f594e734982031/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04b4e0d2-1bf5-4077-a6ef-b6695df19198) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/teams-store-ranking-parameters.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e654f8a6a788b82e21069f2db37244929025d009/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fteams-store-ranking-parameters.md) | 86 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d38dab43-7cbf-4eef-8c90-f88abdebbde1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e654f8a6a788b82e21069f2db37244929025d009/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a69be75e-ce5d-4427-8656-e5e55c95c801) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e654f8a6a788b82e21069f2db37244929025d009/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fadd-authentication.md) | 86 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e3d6ecc-e14a-4b79-88a0-f7e2448b4b77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e654f8a6a788b82e21069f2db37244929025d009/msteams-platform%2Fresources%2Fbot-v3%2Fbots-test.md) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0de7f035-1f96-4b8e-8f14-63db110f2158) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e654f8a6a788b82e21069f2db37244929025d009/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3be6ff4e-53a5-425a-a4a9-4556e53e82e8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/teams-store-ranking-parameters.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3388808fa744c4bba90a4d65563be8942cc73680/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fteams-store-ranking-parameters.md) | 85 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4addd3da-13d2-4bfd-b24b-81b215130e18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3388808fa744c4bba90a4d65563be8942cc73680/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/211e5b3e-7d05-4f1d-8f73-f9a7fb6bc3f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3388808fa744c4bba90a4d65563be8942cc73680/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fadd-authentication.md) | 86 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b28ccb26-85f1-433f-9985-69380dc4928c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3388808fa744c4bba90a4d65563be8942cc73680/msteams-platform%2Fresources%2Fbot-v3%2Fbots-test.md) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea9f7b43-4062-4a70-ba8e-a495d720695d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3388808fa744c4bba90a4d65563be8942cc73680/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09084ee8-0c37-4ee9-897b-ded79b2a8320) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
