### PR TITLE
Update TOC.yml

### PR DESCRIPTION
**Pull request by divya-akula**
Issue ID#2859
Updated the table of contents to remove .md in the file url

### CODE REVIEW

**Comment by KirtiPereira** [comment]
@divya-akula - please add the file **UpgradeTeamsUsingYeoman.md** to this PR. Due to some reason the file is not showing in the master folder.
Also, add the screenshots to this PR itself, just to ensure that the images are visible.

**Comment by divya-akula** [comment]
@KirtiPereira I see it here
https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tutorials/UgradeTeamsUsingYeoman.md

any confusions?

**Comment by KirtiPereira** [comment]
@divya-akula - after merger the file path should be https://github.com/MicrosoftDocs/msteams-docs/master/msteams-platform/tutorials/UgradeTeamsUsingYeoman.md
The /blob should not be there. 
Therefore, requested you to add the file to the current PR. I'll also check and revert with an update, if any.
Thank you.

**Comment by KirtiPereira** [comment]
@divya-akula - the issue has been resolved through PR #2874 . Therefore, closing this PR.

**Pull request closed without merging**
