### PR TITLE
[Doc Improvement][Tools and SDKs-TTK-Revise provision cloud resources][2790643]

### PR DESCRIPTION
**Pull request by v-vpaliwal**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a7b26af5517fb8a679bd63254914e5735a3db47/msteams-platform%2Ftoolkit%2Fprovision.md) | 96 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02e5f1de-792d-48d6-9d36-bf903b30ddbb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/246ccfe7ea8d5ee7a2baabd3691954140e4a6213/msteams-platform%2Ftoolkit%2Fprovision.md) | 96 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b284b949-9ecf-4c61-8af6-629b5b5d12a7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82d17a8eeeb96c1cb6194d280f984a34738a491a/msteams-platform%2Ftoolkit%2Fprovision.md) | 96 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52e27dd8-4794-4ede-87a3-2892c7598604) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c231c7be3c33722f99c2cd292fc6a1c1663c239/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a42013ed-bf3d-4725-b5be-4928f4d515c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c231c7be3c33722f99c2cd292fc6a1c1663c239/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 98 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d977f92-d7e3-4b6c-bd9a-2f128587190c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c231c7be3c33722f99c2cd292fc6a1c1663c239/msteams-platform%2Ftoolkit%2Fprovision.md) | 96 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94a0ea84-06fb-400a-a617-987bb5c332b6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/42389d6baa94f59d9ec8517005e196d18bc544d6/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb1c72cc-b6c4-4a51-96cd-05ea43aae5d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/42389d6baa94f59d9ec8517005e196d18bc544d6/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 98 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d07a8dde-df79-4ca0-8026-78eac046d770) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/42389d6baa94f59d9ec8517005e196d18bc544d6/msteams-platform%2Ftoolkit%2Fprovision.md) | 95 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/566390f9-258b-4332-b32c-58428a72ccab) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e49b5d0030a9081e34c3d7c6959808efa6afe9af/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1337740-3aaa-46a3-9625-e9530793394f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e49b5d0030a9081e34c3d7c6959808efa6afe9af/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 98 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9756757-4818-4018-af55-828ca0e775b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e49b5d0030a9081e34c3d7c6959808efa6afe9af/msteams-platform%2Ftoolkit%2Fprovision.md) | 95 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1e84afe-a2c8-47f5-a57a-19c3418adb45) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/711b5ee7e7935e3995a4e32677bcfa5738ea7467/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e3185a2-6b47-4889-8b3a-663dd00fc1a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/711b5ee7e7935e3995a4e32677bcfa5738ea7467/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 98 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14b0b496-dad0-4019-be41-1d6803175242) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/711b5ee7e7935e3995a4e32677bcfa5738ea7467/msteams-platform%2Ftoolkit%2Fprovision.md) | 95 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75426e66-066b-4804-85a3-dd1dcd93d02f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6319d9f6f0abdc49c5aba12ae49cdc5da4955c9e/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/216720fc-f018-486b-bdc5-062a88822fe3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6319d9f6f0abdc49c5aba12ae49cdc5da4955c9e/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 98 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8dd1e673-52fc-474d-8277-8c4c3d06bfab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6319d9f6f0abdc49c5aba12ae49cdc5da4955c9e/msteams-platform%2Ftoolkit%2Fprovision.md) | 95 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba81c7ef-6e24-46bc-aad3-96210b64edeb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4a50c9c724302bf005b2dc7ecb722530cf02aa7/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/adb0f648-4cd8-424d-a8a1-8b79e769fcd5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4a50c9c724302bf005b2dc7ecb722530cf02aa7/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 98 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a8d987e-44d9-409c-9995-c8e0ad8f0fcb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4a50c9c724302bf005b2dc7ecb722530cf02aa7/msteams-platform%2Ftoolkit%2Fprovision.md) | 95 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4ac341f-c85e-449d-a4b2-7fc5557b07e0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7753d93c7efc81b23c685ad67c11c8f128f232cf/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b3ededd-d4e7-463f-b1fa-88b521ef1935) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7753d93c7efc81b23c685ad67c11c8f128f232cf/msteams-platform%2Ftoolkit%2Fprovision.md) | 94 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3e7431f-61e5-490a-9b3c-98ac22984e9b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b758a078c3922f82eba9a0b6bcc78e7f484d5761/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fdca624d-e881-43a7-b5dd-75c37a2ada66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b758a078c3922f82eba9a0b6bcc78e7f484d5761/msteams-platform%2Ftoolkit%2Fprovision.md) | 94 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18e66405-04c6-4cbb-8585-825a181c7eee) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-amprasad** [comment]
Visual Studio Code
* Move this link to see also from the intro: [how to provision Azure-based app](https://review.learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode%2Cvcode&tutorial-step=8).
* Delete "such as", as not required.
image
* Delete "that", as incorrect grammar:
image
*

**Comment by v-amprasad** [comment]
Visual Studio
* Remove full stop and add "or"
image

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20ec87de06cfd2fb5c70b6d55fb7fcd5d80beb32/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47333190-7436-4ea4-8fc6-95c817da7b9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20ec87de06cfd2fb5c70b6d55fb7fcd5d80beb32/msteams-platform%2Ftoolkit%2Fprovision.md) | 94 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54fff37f-a45c-4596-bf54-158b79c7ff5d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6842423c328f83f74e88f415183496c869c079dc/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65e1a63c-86fe-4ee2-a924-cc58dbfca423) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6842423c328f83f74e88f415183496c869c079dc/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10e70038-58bc-4969-b0d9-bdc7d2e32d5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6842423c328f83f74e88f415183496c869c079dc/msteams-platform%2Ftoolkit%2Fprovision.md) | 94 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2f62cb1-3ed5-4886-a74e-280e450d2337) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d59bd347c378795d1486fb17a126339b14a4aaa0/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5e80384-ba41-4b08-9431-1761b52ebac5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d59bd347c378795d1486fb17a126339b14a4aaa0/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c054fa04-ae3f-4008-a241-fb856e94446d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d59bd347c378795d1486fb17a126339b14a4aaa0/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34f31c6d-2faa-4384-bc02-74b33934fb82) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d59bd347c378795d1486fb17a126339b14a4aaa0/msteams-platform%2Ftoolkit%2Fprovision.md) | 94 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f31b9ce4-d8ee-4fd4-8565-a5623afd0bd2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c784068cf1d3db9664e41b1443ad28c894173c42/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34a2293e-9161-4fb0-84ef-fef5a633aefb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c784068cf1d3db9664e41b1443ad28c894173c42/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec076f74-4790-4fec-b2e8-68f2acaa479d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c784068cf1d3db9664e41b1443ad28c894173c42/msteams-platform%2Ftoolkit%2Fprovision.md) | 94 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b7fdc60-a6e0-4414-a4a1-f9cbb4e20d55) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]

**Pull request merged**
