### PR TITLE
[Doc Improvement][SEO Description update][3876699]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ae1351772b68e6d3a3bf45546dace6841deb449b/msteams-platform%2Fsbs-gs-spfx.yml) | 88 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5be47c3a-fcb3-4261-b14e-ec8ca4f1f059) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae1351772b68e6d3a3bf45546dace6841deb449b/msteams-platform%2Ftabs%2Fdesign%2Ftabs.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ecdad456-3a8e-40aa-8346-e7439640257c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae1351772b68e6d3a3bf45546dace6841deb449b/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5dcb7ff7-2d09-4ce5-8925-020d525267d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae1351772b68e6d3a3bf45546dace6841deb449b/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7bc0a355-a10c-4250-ac66-2961f303ca36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae1351772b68e6d3a3bf45546dace6841deb449b/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-library.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c6151b8-bf18-482b-b966-56c3a4a52b31) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/open-content-in-stageview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae1351772b68e6d3a3bf45546dace6841deb449b/msteams-platform%2Ftabs%2Fopen-content-in-stageview.md) | 82 | 69 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/736eb4ba-89c9-490c-b16f-faad17fae767) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae1351772b68e6d3a3bf45546dace6841deb449b/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/040e2e2f-316e-41a5-ba4f-41ed3b3ff53b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae1351772b68e6d3a3bf45546dace6841deb449b/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/275d5be3-4760-4586-b9dd-f8f1d0da033c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae1351772b68e6d3a3bf45546dace6841deb449b/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84f4ee94-cb5e-4f5a-acdd-5ed88e96cd53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae1351772b68e6d3a3bf45546dace6841deb449b/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61803844-d706-4558-9570-50704890c4a9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a455e7e61f465e1ecd1d3615d670e584eb4c3653/msteams-platform%2Fsbs-gs-spfx.yml) | 88 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d08bcc8c-aa6d-4188-a3df-19431621259c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a455e7e61f465e1ecd1d3615d670e584eb4c3653/msteams-platform%2Ftabs%2Fdesign%2Ftabs.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0aa2767-b24d-4549-a3ed-d5edda11c112) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a455e7e61f465e1ecd1d3615d670e584eb4c3653/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0599e99a-cc9d-41cc-a57a-230a3f3a0b1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a455e7e61f465e1ecd1d3615d670e584eb4c3653/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98bb227f-12a3-495f-99d4-a56834b5c6c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a455e7e61f465e1ecd1d3615d670e584eb4c3653/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-library.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d9d0e32-f9d8-4bfa-b00b-6d3a06ebb85d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/open-content-in-stageview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a455e7e61f465e1ecd1d3615d670e584eb4c3653/msteams-platform%2Ftabs%2Fopen-content-in-stageview.md) | 82 | 69 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42c3fd04-be59-4ac1-aad8-ed1e24948e0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a455e7e61f465e1ecd1d3615d670e584eb4c3653/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56ab0ad9-d055-4cd0-9a2f-8940ba4374cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a455e7e61f465e1ecd1d3615d670e584eb4c3653/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9002422e-7d36-48cd-8997-2185535eac86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a455e7e61f465e1ecd1d3615d670e584eb4c3653/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a330196e-5e2b-4469-a1da-778f3b079421) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a455e7e61f465e1ecd1d3615d670e584eb4c3653/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25af6ba3-cc7d-418a-a1e0-03da75f38956) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/15988e8e40162cb4388ca1e5a448d6228650c101/msteams-platform%2Fsbs-gs-spfx.yml) | 87 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/188aea89-fb76-4f2e-9fa5-0a1e9904cf8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15988e8e40162cb4388ca1e5a448d6228650c101/msteams-platform%2Ftabs%2Fdesign%2Ftabs.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79be6d99-cfbd-4bb2-b647-806ca0eea4fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15988e8e40162cb4388ca1e5a448d6228650c101/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ae9a333-0ead-4a9f-a308-2644173abf0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15988e8e40162cb4388ca1e5a448d6228650c101/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73253dcb-53bc-492d-b55b-ad5c994d8b1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15988e8e40162cb4388ca1e5a448d6228650c101/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-library.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9fb027e-735f-45ff-9247-9bed0c7c0bd5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/open-content-in-stageview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15988e8e40162cb4388ca1e5a448d6228650c101/msteams-platform%2Ftabs%2Fopen-content-in-stageview.md) | 82 | 69 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c009294-18ae-437b-824a-8704fa44da92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15988e8e40162cb4388ca1e5a448d6228650c101/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bd06db4-4e90-40ab-9b1d-949f53f42eda) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15988e8e40162cb4388ca1e5a448d6228650c101/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2c80f33-83d8-4fdc-b50e-97093dcc3863) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15988e8e40162cb4388ca1e5a448d6228650c101/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1330e9b-9480-4360-973a-bad6b525f17f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15988e8e40162cb4388ca1e5a448d6228650c101/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2886cf3-229c-4ac8-adc4-b068384019bf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a071a0a5689966735ac12e78d9fce4572f5cca1f/msteams-platform%2Fsbs-gs-spfx.yml) | 87 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a74a62e6-edc6-439e-b184-3f137b33e16d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a071a0a5689966735ac12e78d9fce4572f5cca1f/msteams-platform%2Ftabs%2Fdesign%2Ftabs.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93d46563-c991-40b6-95f9-5c1175de99ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a071a0a5689966735ac12e78d9fce4572f5cca1f/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53e70208-6880-481a-8e48-f38691decdd3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a071a0a5689966735ac12e78d9fce4572f5cca1f/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf783948-184b-486f-8061-d4fa8fa1adb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a071a0a5689966735ac12e78d9fce4572f5cca1f/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-library.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c45dfe50-d59d-4d94-a338-aef7b5346f96) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/open-content-in-stageview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a071a0a5689966735ac12e78d9fce4572f5cca1f/msteams-platform%2Ftabs%2Fopen-content-in-stageview.md) | 82 | 69 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9aa002f8-44a7-46cf-8188-99e6606dc623) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a071a0a5689966735ac12e78d9fce4572f5cca1f/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cf6046d-1e5d-49ef-8e21-1761c2ad8db2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a071a0a5689966735ac12e78d9fce4572f5cca1f/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3010ae0a-ceec-4846-9d57-5b01ab7cf5cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a071a0a5689966735ac12e78d9fce4572f5cca1f/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18e5c329-306c-430d-b2d4-7b11a6dea6e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a071a0a5689966735ac12e78d9fce4572f5cca1f/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20fc651e-77d6-41a0-bf2d-5f79218c5b5a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
