### PR TITLE
mm-teams-python-bot-auth

### PR DESCRIPTION
**Pull request by mmiele**
Added python snipppet place holders.

### CODE REVIEW

**Comment by clearab** [comment]
@mmiele Why is this using a different app manifest than the C# one? I don't believe it is necessary?

**Comment by mmiele** [comment]
@clearab I do not about the manifest; I did use what was in the Python code sample. Otherwise the article is ready.

**Comment by tracyboehrer** [comment]
> @mmiele Why is this using a different app manifest than the C# one? I don't believe it is necessary?

Assuming this is based on 46.teams-auth, the C# sample doesn't have a manifest in the project (looking at the master branch).  According to Eric, and the code, this sample can only effectively be run in Teams since it only responds to the OnTeamsSigninVerifyStateAsync.  

I have made a note to bring this up with the C# team after the holidays.  I believe that the C# sample is incomplete.  Prior to the official Teams integration, this bot existed, but handled the auth differently and could function in the emulator (as it overrode a different method).  I also believe that it should handle either case (Teams or emulator) for completeness (as 24.bot-authentication-msgraph does).

It appears the C# manifest referenced in the doc comes from 57.teams-conversation-bot.

Lastly, the PNG names are icon-color.png and icon-outline.png (the doc doesn't include the "icon-" prefix).

I would recommend documenting C# the same as Python, including the PNG name corrections, since at this point I think the Python version is more accurate.  i.e., We'll have to adjust both samples to be complete, which will then match the doc.

**Comment by tracyboehrer** [comment]
@mmiele Also, use the manifest from the master branch in Python for that sample.  At a minimum the validDomains is different from whats in the doc.

**Comment by clearab** [comment]
@mmiele please make the following changes:

- Step 1 under Prepare the bot sample code has a bad link. 
- Please remove the language specific manifests. It is unnecessary, and confusing. The C# manifest is the correct one, the Python manifest is missing the valid domains entry, and has a bunch of extraneous commands that are not necessary.

**Comment by mmiele** [comment]
@clearab Made the required fixes. The topic is ready to be merged.

**Pull request merged**
