### PR TITLE
Images for updating TeamsArticle

### PR DESCRIPTION
**Pull request by divya-akula**
Images for updating TeamsArticle

### CODE REVIEW

**Comment by KirtiPereira** [comment]
@divya-akula - what needs to be done in this PR?

**Comment by KirtiPereira** [comment]
@divya-akula - has the following file been wrongly added to the folder? If yes, please delete it from the folder.
msteams-platform/assets/UpdateTeamsImages/**testtodel**

**Comment by KirtiPereira** [comment]
Images only. Approved.

**Review by KirtiPereira — APPROVED** [review]
Approved, as this PR is linked to PR 2873

**Review by surbhigupta12 — APPROVED** [review]
Approved the PR

**Pull request merged**
