### PR TITLE
[BULK] DocuTune - Fix build validation issues: docs-link-absolute (part 2)

### PR DESCRIPTION
**Pull request by alexbuckgit**
**Global effort to fix build validation errors**

The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.

DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck

### CODE REVIEW

**Comment by alexbuckgit** [comment]
#docutune-draft

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-commandbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97c7b204fe15a69d90e02bd3e5d072caf8e3b4/msteams-platform%2Fsbs-gs-commandbot.yml) | 90 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13c3b9b4-10ea-4f5b-b1c5-7920c3b69d23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97c7b204fe15a69d90e02bd3e5d072caf8e3b4/msteams-platform%2Fsbs-gs-msgext.yml) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6439094d-d4ec-47ad-92d6-0d385e1e28bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97c7b204fe15a69d90e02bd3e5d072caf8e3b4/msteams-platform%2Fsbs-meetings-stage-view.yml) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b802a95b-4edf-4733-b886-2a1a5108e17c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97c7b204fe15a69d90e02bd3e5d072caf8e3b4/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 89 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c1e940e-071d-472d-aeb6-551d071cdfbc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4c97c7b204fe15a69d90e02bd3e5d072caf8e3b4/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 83 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/304bb56c-444f-4143-896c-df5ece206f8e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by JustPies** [comment]
#docutune-ready

**Comment by alexbuckgit** [comment]
@KCCross - Please merge.

**Comment by alexbuckgit** [comment]
Required changes will be handled via a different PR.

#docutune-abandoned

**Pull request closed without merging**
