### PR TITLE
[Messaging extensions][Add content][1468459]

### PR DESCRIPTION
**Pull request by Rajeshwari-v**
Added payload activity properties when invoked a task module from different places. Please review.

### CODE REVIEW

**Review by KirtiPereira — CHANGES_REQUESTED** [review]
@Rajeshwari-v - please do a self-review. For example, why is there a semi-colon in the following sentence?
|`type`| Type of request; must be `invoke`. |

**Review by Mallipriya-MSFT — COMMENTED** [review]
Reviewed and approved

**Review by Mallipriya-MSFT — APPROVED** [review]
Reviewed and approved

**Review by KirtiPereira — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]
Approving the PR.

**Pull request merged**
