### PR TITLE
[Doc Improvement][update what's new and landing page]

### PR DESCRIPTION
**Pull request by v-rpatkur**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/325e689c4120c92dd7cad03441fadf7dc0407360/msteams-platform/mstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ff3fecc-62e8-4550-9f69-593614ee27e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/325e689c4120c92dd7cad03441fadf7dc0407360/msteams-platform/whats-new.md) | 87 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dd24ed7-15f5-41cb-9cb1-99efec0c04d0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5ad52ae8997a0dcb22e52f6debdc85656f57d47e/msteams-platform/mstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c83c2aa4-5aec-4498-beeb-54377fbe4c93) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ad52ae8997a0dcb22e52f6debdc85656f57d47e/msteams-platform/whats-new.md) | 87 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8ebfdd2-5424-4a00-a2bc-6a0b2a26bbd8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4c8c9d726c4327ef9009502ebb948d11866f6f10/msteams-platform/mstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f2b05bd-fb15-40c4-80b1-672d6f752ef4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c8c9d726c4327ef9009502ebb948d11866f6f10/msteams-platform/whats-new.md) | 87 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60a45b6d-a91d-4b02-8e82-2d0fc06f88a2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]
Approved

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5bf281af64ab5c9171408e34e41c8e9dc761dd2a/msteams-platform/mstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36d2bd5a-33a0-45be-8b3b-e0246c4f21c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5bf281af64ab5c9171408e34e41c8e9dc761dd2a/msteams-platform/whats-new.md) | 87 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45853334-e059-4afc-8ba5-c66bc1c21cbd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/729158f89f81944c97edfcac9212b0656726e17d/msteams-platform/apps-in-teams-meetings/API-references.md) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e32039d-fd4b-4b03-abc8-5a608246ecf4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/729158f89f81944c97edfcac9212b0656726e17d/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5dc48170-14c7-4f4a-a65e-72951cfde1e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/729158f89f81944c97edfcac9212b0656726e17d/msteams-platform/bots/how-to/authentication/add-authentication.md) | 81 | 135 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c41c54a-a08c-49ac-9b34-4e66b6491ae6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/debug/locally-with-an-ide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/729158f89f81944c97edfcac9212b0656726e17d/msteams-platform/bots/how-to/debug/locally-with-an-ide.md) | 80 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af0636b6-a0ae-4959-8c5c-9d179a38974b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/729158f89f81944c97edfcac9212b0656726e17d/msteams-platform/get-started/get-started-overview.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3181de91-165d-4efd-b05b-add6f8b75a24) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/729158f89f81944c97edfcac9212b0656726e17d/msteams-platform/mstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bdf63ab5-9115-4118-a5bd-ce38adfbc05d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/729158f89f81944c97edfcac9212b0656726e17d/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | 83 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/870e0a56-1687-46c7-940b-0fd8b8a8d182) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/729158f89f81944c97edfcac9212b0656726e17d/msteams-platform/sbs-meeting-token-generator.yml) | 88 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e8426c2-dc4b-48f4-848b-f531711390a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/729158f89f81944c97edfcac9212b0656726e17d/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md) | 87 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87f931c5-53ae-4f59-8f32-bb107cee788f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/729158f89f81944c97edfcac9212b0656726e17d/msteams-platform/task-modules-and-cards/cards/cards-format.md) | 82 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14cd1a51-7c9d-479e-9bd8-58160948f4cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/729158f89f81944c97edfcac9212b0656726e17d/msteams-platform/whats-new.md) | 87 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f2bf2be-ead6-42a6-8c68-30663191bf6c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-rpatkur** [comment]
Closing the PR.

**Pull request closed without merging**
