### PR TITLE
Update capabilities-overview.md

### PR DESCRIPTION
**Pull request by v-habibaumme**
Minor format edit

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ad8aa9421a99a5056d8b5286652d0d734649d80/msteams-platform/concepts/capabilities-overview.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/041e7ba5-c0bb-4661-aaa7-c640720f4925) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ad8aa9421a99a5056d8b5286652d0d734649d80/msteams-platform/concepts/capabilities-overview.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75cfadf3-4389-4d4e-9fe7-c75c4ed14fc0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c4a263e3fd72ba858476b6e4858c25991e8ebcf/msteams-platform/concepts/capabilities-overview.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/beb38c6c-da9e-47b2-946e-d5b965814ff5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c4a263e3fd72ba858476b6e4858c25991e8ebcf/msteams-platform/concepts/design/enable-app-customization.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9b4f8fa-5be6-49fb-8cce-b5cadf122df7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d12ab5b8a3acacc2fd2e04842e419a9d175111a1/msteams-platform/apps-in-teams-meetings/teams-together-mode.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83a96b43-3cae-4375-bed7-6645d2a444f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d12ab5b8a3acacc2fd2e04842e419a9d175111a1/msteams-platform/concepts/capabilities-overview.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5eab85c-1d95-4746-aa2e-28fdef3a405e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d12ab5b8a3acacc2fd2e04842e419a9d175111a1/msteams-platform/concepts/design/enable-app-customization.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e34a3c7-dcc6-43b7-b6d6-05ba00bcc080) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aa93600da1ad191d76579ce5d0dee9b61c41e395/msteams-platform/apps-in-teams-meetings/teams-together-mode.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0cf514cf-2785-4a79-88e2-a7c498632b00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aa93600da1ad191d76579ce5d0dee9b61c41e395/msteams-platform/concepts/capabilities-overview.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c7a246f-3a8c-45c5-9428-683f04dd44fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aa93600da1ad191d76579ce5d0dee9b61c41e395/msteams-platform/concepts/design/enable-app-customization.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6ebe75d-6cf9-4129-849e-1b6220fcc55e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37ef567e842ce8c45379ec0647cab49845842cf9/msteams-platform/apps-in-teams-meetings/teams-together-mode.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d304da5-9686-4f65-b003-de2f6345e5f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37ef567e842ce8c45379ec0647cab49845842cf9/msteams-platform/concepts/capabilities-overview.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/900b00ca-ad71-4397-a96a-b4c9ab6cd022) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37ef567e842ce8c45379ec0647cab49845842cf9/msteams-platform/concepts/design/enable-app-customization.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab24bfbc-2330-44a0-ae88-9867e06d5492) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37ef567e842ce8c45379ec0647cab49845842cf9/msteams-platform/task-modules-and-cards/cards/cards-format.md) | 86 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4d7bd2b-192d-4ce2-8795-4c018fb83f84) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/805ec9c714d06a6057fb8c7017d8e90d36d16abe/msteams-platform/apps-in-teams-meetings/teams-together-mode.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9724ef0f-cfc8-44fb-a00f-53d9f50e6337) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/805ec9c714d06a6057fb8c7017d8e90d36d16abe/msteams-platform/concepts/capabilities-overview.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1b0e62a-2453-4e59-bc0d-7ab480aaad26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/805ec9c714d06a6057fb8c7017d8e90d36d16abe/msteams-platform/concepts/design/enable-app-customization.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59d3bc60-61e8-4758-a8bd-a34cf4fc95d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/805ec9c714d06a6057fb8c7017d8e90d36d16abe/msteams-platform/task-modules-and-cards/cards/cards-format.md) | 86 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c87bd639-3b46-4aea-bfa3-cc938a78669d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b6af0907e394df0da1e0ac5653767b929c27a1e/msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63b4edc4-1e93-4bb5-b024-cf2eb310c8e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b6af0907e394df0da1e0ac5653767b929c27a1e/msteams-platform/apps-in-teams-meetings/teams-together-mode.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/692fa138-b28f-485d-97c1-e34d883cf4b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b6af0907e394df0da1e0ac5653767b929c27a1e/msteams-platform/concepts/capabilities-overview.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5102e15-1847-42be-be0c-ac0e92b71f82) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b6af0907e394df0da1e0ac5653767b929c27a1e/msteams-platform/concepts/design/enable-app-customization.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c64fcc63-c8ec-4cf8-ae23-e477eecad997) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b6af0907e394df0da1e0ac5653767b929c27a1e/msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/Overview.md) | 83 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef1aefa5-3f96-495a-9e7b-322e8d306770) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8b6af0907e394df0da1e0ac5653767b929c27a1e/msteams-platform/task-modules-and-cards/cards/cards-format.md) | 86 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a72433c2-429a-4a43-85e2-254fe9ef9131) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by surbhigupta12** [comment]
Closing this PR as it is irrelevant.

**Pull request closed without merging**
