### PR TITLE
Doc Improvement][Teams 2.1 update][3455950]

### PR DESCRIPTION
**Pull request by v-vanv**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1ea09e9ca268bc624fa308115e816724647a4117/msteams-platform%2Fsbs-gs-msgext.yml) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c931a54-3c75-4dd3-9592-7fa8442fb49e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/prepare-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8b7c4a473cae4ed293456fb05e0c7a72c7bb41a/msteams-platform%2Fincludes%2Fget-started%2Fprepare-teams-toolkit.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8169892-00ef-4757-aeca-478b5963a140) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c8b7c4a473cae4ed293456fb05e0c7a72c7bb41a/msteams-platform%2Fsbs-gs-msgext.yml) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f55cdd9f-5e8b-4266-9e5d-9e5f467f6653) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/prepare-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc58a723f43f3f65e4f4f1ab7ffeeaa8c4a393af/msteams-platform%2Fincludes%2Fget-started%2Fprepare-teams-toolkit.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/831784db-6bee-48bd-8e73-64d47bc0dd41) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cc58a723f43f3f65e4f4f1ab7ffeeaa8c4a393af/msteams-platform%2Fsbs-gs-msgext.yml) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e3b43cb-5b78-4632-a537-32708cea1064) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/prepare-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/75997ddabca573617fd323436aa46f6fd3971b3a/msteams-platform%2Fincludes%2Fget-started%2Fprepare-teams-toolkit.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26380428-2729-42c4-9ef0-d0f5110ad29e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/75997ddabca573617fd323436aa46f6fd3971b3a/msteams-platform%2Fsbs-gs-msgext.yml) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19d3687d-165d-415b-8e02-7a193a24c3ec) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/prepare-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63fdfe7262e53dffc6aa0f8c96f9d430604c29cb/msteams-platform%2Fincludes%2Fget-started%2Fprepare-teams-toolkit.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/785b960c-d986-4f0b-a707-03fe90237a54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/63fdfe7262e53dffc6aa0f8c96f9d430604c29cb/msteams-platform%2Fsbs-gs-msgext.yml) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb34f397-ccd0-4a15-a832-b4ec0fdca0e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/63fdfe7262e53dffc6aa0f8c96f9d430604c29cb/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03db5c7e-10b9-4708-a7d3-75e16d0254f9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/prepare-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4ec999f998e1f67167c42271ca2c969a7e4f605/msteams-platform%2Fincludes%2Fget-started%2Fprepare-teams-toolkit.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/103fe180-5d97-4f1f-9357-d3f92dc7a84f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a4ec999f998e1f67167c42271ca2c969a7e4f605/msteams-platform%2Fsbs-gs-msgext.yml) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/171059ec-bc62-41dd-b985-8c463048c937) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a4ec999f998e1f67167c42271ca2c969a7e4f605/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99930920-d01a-486d-bdc3-fc5924388021) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
