### PR TITLE
[Doc Improvement][O365 Note][4198183]

### PR DESCRIPTION
**Pull request by v-bvishnu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f91e9bdb2eb8e8d2a13f007bbcb6db9dec1dd1f7/msteams-platform%2Fbots%2Fbot-features.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ccc9edc-c1b2-43d0-b2a5-198caec1217c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/interactive-notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f91e9bdb2eb8e8d2a13f007bbcb6db9dec1dd1f7/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Finteractive-notification-bot-in-teams.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/365165cf-e70a-470e-bd5a-db4eef961dd7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f91e9bdb2eb8e8d2a13f007bbcb6db9dec1dd1f7/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5f7b79d-9809-4fc4-8bca-f80d6671e032) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f91e9bdb2eb8e8d2a13f007bbcb6db9dec1dd1f7/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b6934f6-56ec-4bd5-ac1e-e365adb52051) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f91e9bdb2eb8e8d2a13f007bbcb6db9dec1dd1f7/msteams-platform%2Fconcepts%2Fdesign%2Funderstand-use-cases.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3de5a90d-e76d-41c7-bc5c-fe36f0d03822) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f91e9bdb2eb8e8d2a13f007bbcb6db9dec1dd1f7/msteams-platform%2Foverview-explore.md) | 87 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00f8cfdf-0a61-4763-a191-4584fe4e09ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f91e9bdb2eb8e8d2a13f007bbcb6db9dec1dd1f7/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00ed1e9b-3d81-453c-a1f5-cec32ed48e06) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f91e9bdb2eb8e8d2a13f007bbcb6db9dec1dd1f7/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bdc27c1b-635b-41ac-904c-1f3831e559e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f91e9bdb2eb8e8d2a13f007bbcb6db9dec1dd1f7/msteams-platform%2Fsbs-teams-connectors.yml) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb295fce-a8ac-4215-8f4b-2d22a223f1bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f91e9bdb2eb8e8d2a13f007bbcb6db9dec1dd1f7/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83665aa1-064d-40f1-8b9c-cdf81fc5b087) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45e9063deb5bac94015903ee502ce0cd6b85bf1f/msteams-platform%2Fbots%2Fbot-features.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb40e50a-df37-4efc-838b-b452728ff7e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/interactive-notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45e9063deb5bac94015903ee502ce0cd6b85bf1f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Finteractive-notification-bot-in-teams.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/822b87ad-3da8-4fbf-9334-d22e0f571305) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45e9063deb5bac94015903ee502ce0cd6b85bf1f/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aca6c7df-119d-4832-843a-4dbb78b398f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45e9063deb5bac94015903ee502ce0cd6b85bf1f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/487cf86a-892d-4bba-832c-640308fdae5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45e9063deb5bac94015903ee502ce0cd6b85bf1f/msteams-platform%2Fconcepts%2Fdesign%2Funderstand-use-cases.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e39d312-ce2a-45dc-99de-a99c07553c13) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45e9063deb5bac94015903ee502ce0cd6b85bf1f/msteams-platform%2Foverview-explore.md) | 87 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b7222d8-a078-44b8-b967-fa672eec9e88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45e9063deb5bac94015903ee502ce0cd6b85bf1f/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/329d0540-c313-4191-b67d-e557c045c05e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/45e9063deb5bac94015903ee502ce0cd6b85bf1f/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c842d852-b90c-4786-9243-e7e93c08bc12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/45e9063deb5bac94015903ee502ce0cd6b85bf1f/msteams-platform%2Fsbs-teams-connectors.yml) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00157566-77b8-4e6e-9656-30e3e08c91d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45e9063deb5bac94015903ee502ce0cd6b85bf1f/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cbe5b48-5a5f-4dae-bb35-e4e923f273aa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b1eddeb885b230a2ef158699e7110f962c6fb0f/msteams-platform%2Fbots%2Fbot-features.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/556b911b-63af-4c08-9fc5-00f34e07d3a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/interactive-notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b1eddeb885b230a2ef158699e7110f962c6fb0f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Finteractive-notification-bot-in-teams.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0201a9c5-fd7e-47d0-a7cb-9dd9f388763d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b1eddeb885b230a2ef158699e7110f962c6fb0f/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7561c4b-90e4-41d3-bbcf-5e96084c05b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b1eddeb885b230a2ef158699e7110f962c6fb0f/msteams-platform%2Fconcepts%2Fdesign%2Funderstand-use-cases.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1d440a6-a5f3-4cd6-bf6e-9b2729afc215) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b1eddeb885b230a2ef158699e7110f962c6fb0f/msteams-platform%2Foverview-explore.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c87bfafc-f44c-4da3-9b36-f6b48611b6ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b1eddeb885b230a2ef158699e7110f962c6fb0f/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32fc3a24-90d7-430a-bc3e-f821369d5693) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3b1eddeb885b230a2ef158699e7110f962c6fb0f/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/442036cd-3ed0-4737-8dc3-9fff367ff1b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3b1eddeb885b230a2ef158699e7110f962c6fb0f/msteams-platform%2Fsbs-teams-connectors.yml) | 85 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21737fa5-e9f1-4a1c-908e-b120a4968802) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b1eddeb885b230a2ef158699e7110f962c6fb0f/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 96 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bba9cb9-5307-4f3b-bfd4-452e240cb7a4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fe8797be78c6007bc678ba89db708c5279a677ad/msteams-platform%2Fbots%2Fbot-features.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/032c43c9-0b43-4bd6-9f2e-2dce49606b0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/interactive-notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fe8797be78c6007bc678ba89db708c5279a677ad/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Finteractive-notification-bot-in-teams.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ab40de3-505d-4623-8b75-8f9ca854d643) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fe8797be78c6007bc678ba89db708c5279a677ad/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e7473b6-75dc-4ba1-a923-e5810a8f7e80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fe8797be78c6007bc678ba89db708c5279a677ad/msteams-platform%2Fconcepts%2Fdesign%2Funderstand-use-cases.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa597101-1311-4567-b2fb-acdc0c07afac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fe8797be78c6007bc678ba89db708c5279a677ad/msteams-platform%2Foverview-explore.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94b2959c-8545-4ad6-88ce-259afbc6f299) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fe8797be78c6007bc678ba89db708c5279a677ad/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af9e836c-8af8-47e2-bb80-4a65890e9857) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fe8797be78c6007bc678ba89db708c5279a677ad/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2dd23a47-4176-46f6-952b-65ac152582b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fe8797be78c6007bc678ba89db708c5279a677ad/msteams-platform%2Fsbs-teams-connectors.yml) | 85 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6429ed8-96e5-402b-a005-8dd0d3a70355) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fe8797be78c6007bc678ba89db708c5279a677ad/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 96 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0cacbaef-4d58-4b37-97d7-a64eccfe7d1a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
