### PR TITLE
[Doc Improvement][Update Teams app manifest][2425961]

### PR DESCRIPTION
**Pull request by v-bdeepa**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df86f1b79f5871e02d8fa5810ba27323b4dfa163/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1aeb0a6d-5533-4102-b3cf-df5f9c9d2cc6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3a93eb5976941676bbfe56dbe541b1fdb13d2427/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dbd4bfa-ac93-483a-956f-3faaa660d325) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3a93eb5976941676bbfe56dbe541b1fdb13d2427/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b150610-71ac-436c-b466-3fffba95869f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3a93eb5976941676bbfe56dbe541b1fdb13d2427/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f271983c-e6c0-4098-bda3-0ef29005c6de) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/992867355e6d9051efcacbf85663d18fd35caf88/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7bec25e9-c2d8-4555-8608-5698d25cd2c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/992867355e6d9051efcacbf85663d18fd35caf88/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed09b106-a0fe-4887-9826-6fbae9ff20d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/992867355e6d9051efcacbf85663d18fd35caf88/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a690161c-b6ed-42be-b3ec-1e20add665c9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6da705cc5585b005232b9b6d4ce4a08adc72fed7/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3671f0ad-aa63-4da3-a112-773dccdd9ba0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6da705cc5585b005232b9b6d4ce4a08adc72fed7/msteams-platform%2Ftoolkit%2FTeamsFx-manifest-customization.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ec38690-8ffa-4299-8dd4-78afd38c942a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6da705cc5585b005232b9b6d4ce4a08adc72fed7/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c68fe835-c720-4094-ae04-0322954b8b4f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/879c8c3314c23fa4f2fcb9b7e48c1b2a18d68204/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c405195a-dc95-4ad2-bd3e-2455d82ab608) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/879c8c3314c23fa4f2fcb9b7e48c1b2a18d68204/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c77d5124-d329-4bb2-b900-3337cc90c67d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/879c8c3314c23fa4f2fcb9b7e48c1b2a18d68204/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e78cae5a-14ba-49a0-a8b0-ce7e829825d6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0b87cce5038bde1f1531d46b8698e647cfc76386/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1490da16-fe19-45a9-89ec-f993b852a937) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b87cce5038bde1f1531d46b8698e647cfc76386/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5c82e17-6f84-415c-9369-029a0f444d91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0b87cce5038bde1f1531d46b8698e647cfc76386/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ee90d63-aae6-40e8-882a-69fa714f2c41) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/99a5e83628baa118ba5da089c84e59b2dd76d223/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98506a99-1170-4870-ba9f-bf31b4acf8a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99a5e83628baa118ba5da089c84e59b2dd76d223/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08979d7b-533c-4613-a083-c14b6b8076a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99a5e83628baa118ba5da089c84e59b2dd76d223/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2c4d3b8-ef64-40c7-8455-4132d2d9be65) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0682681f3f7e9c02ca6583cfdba557c6f33ef555/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ede94c3-0bb3-4269-a7fb-ce0706d6a5ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0682681f3f7e9c02ca6583cfdba557c6f33ef555/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51d11130-80b8-4c6f-8d09-171234f3b4ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0682681f3f7e9c02ca6583cfdba557c6f33ef555/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/021a2275-e180-4a56-b087-6ee9cf7715ed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by zyxiaoyuer — APPROVED** [review]

**Review by v-abirade — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
