### PR TITLE
[Doc Update][Bot-based plugin branding update]

### PR DESCRIPTION
**Pull request by v-ypalikila**
updated branding to read copilot plugins as Plugins for Microsoft Copilot for Microsoft 365 and invoking message extensions in  Microsoft 365 Chat in Microsoft Teams.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/34fe70e0b6e24dab5dd80baaafa1dc541cb68c04/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08af1339-ca32-4d18-9cda-89aa6db26f89) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/34fe70e0b6e24dab5dd80baaafa1dc541cb68c04/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a5c6bb2-a849-4d2a-b3e4-ad68532f731b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/34fe70e0b6e24dab5dd80baaafa1dc541cb68c04/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 84 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b4a70fe-a02f-46cb-b28e-7793ef7f7483) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c3a8f0a16d1a6e48e356635da49d180b22131dd6/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ab104e6-b3f9-44e4-a197-40113df6b09a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3a8f0a16d1a6e48e356635da49d180b22131dd6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 93 | 112 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77e50d7d-c915-449d-99fc-c176a745e783) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3a8f0a16d1a6e48e356635da49d180b22131dd6/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16b8ed81-0758-443f-9f33-d0223d2efc19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/copilot-plugin-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3a8f0a16d1a6e48e356635da49d180b22131dd6/msteams-platform%2Fmessaging-extensions%2Fcopilot-plugin-faq.md) | 83 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c32f6b1f-1497-4440-a496-8acbb9a4d15a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3a8f0a16d1a6e48e356635da49d180b22131dd6/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e2a1b3a-06d2-49cd-ad47-a7b586a57d32) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3a8f0a16d1a6e48e356635da49d180b22131dd6/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11d492bb-936e-47a0-bc66-7eb09bfad66b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c3a8f0a16d1a6e48e356635da49d180b22131dd6/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 84 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ae11b7e-0bc6-41fb-8278-200bd9607c77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3a8f0a16d1a6e48e356635da49d180b22131dd6/msteams-platform%2Fteams-faq.md) | 90 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b20f8dc-ae03-4e77-9784-e6b8c95e75d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3a8f0a16d1a6e48e356635da49d180b22131dd6/msteams-platform%2Fwhats-new.md) | 94 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27ec7682-e0b9-44ec-89f1-5512b42f7c73) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d5313f6b6771a82d30d05f4ab9695a83a524ba8a/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5327aae-efcd-40b3-8ad8-ea130159772b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5313f6b6771a82d30d05f4ab9695a83a524ba8a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 93 | 112 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c54d168b-080f-477a-af18-73869b17571c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5313f6b6771a82d30d05f4ab9695a83a524ba8a/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08ae2a9a-83a2-4813-9ddc-ca8dd6d5c714) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/copilot-plugin-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5313f6b6771a82d30d05f4ab9695a83a524ba8a/msteams-platform%2Fmessaging-extensions%2Fcopilot-plugin-faq.md) | 83 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f804b078-709c-4527-89f3-88e17532f9ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5313f6b6771a82d30d05f4ab9695a83a524ba8a/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/402f77b5-8395-4742-8707-498e12283912) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5313f6b6771a82d30d05f4ab9695a83a524ba8a/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49ad6350-a488-4c15-978b-d090ee9e7e5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d5313f6b6771a82d30d05f4ab9695a83a524ba8a/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 85 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68efc730-7f63-4a1a-a13c-3d3b13a0cbeb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5313f6b6771a82d30d05f4ab9695a83a524ba8a/msteams-platform%2Fteams-faq.md) | 90 | 74 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc964bae-2e3c-43e5-8985-b6daa43a9464) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5313f6b6771a82d30d05f4ab9695a83a524ba8a/msteams-platform%2Fwhats-new.md) | 94 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2aceaced-ef27-4c52-ae3f-0a643dcb886e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d8169387082a71e5f4b213476938c325b765c050/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67d1fce6-9a3b-4472-8ca3-58ea5b401437) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8169387082a71e5f4b213476938c325b765c050/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 93 | 112 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43be583e-234c-47a9-8d0c-6b1436575f36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8169387082a71e5f4b213476938c325b765c050/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddf79a7e-775a-47c4-b099-47834f6bfba5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/copilot-plugin-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8169387082a71e5f4b213476938c325b765c050/msteams-platform%2Fmessaging-extensions%2Fcopilot-plugin-faq.md) | 83 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/840d91b7-8bd7-4b4c-b74b-0ebde4081898) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8169387082a71e5f4b213476938c325b765c050/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/008a07b9-61d9-445f-9ee9-852d3454b30d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8169387082a71e5f4b213476938c325b765c050/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3d98b93-5d16-42ff-877d-21bf823477e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d8169387082a71e5f4b213476938c325b765c050/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 85 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8ba5b90-a652-4e67-b3ca-67d6dafa881f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8169387082a71e5f4b213476938c325b765c050/msteams-platform%2Fteams-faq.md) | 90 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0a56cab-6dad-4c75-b312-8f3ee11b0269) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8169387082a71e5f4b213476938c325b765c050/msteams-platform%2Fwhats-new.md) | 94 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1b3bc96-59cc-4357-8dd3-141de6ad436c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
