### PR TITLE
[Doc Improvement][Build tab app using javascript sbs guide][2605191]

### PR DESCRIPTION
**Pull request by v-ksar**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9face42f9bd756beb89c22b654ccd63a8fd36866/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad13e52d-911e-4e6d-8df2-707083cf1dcb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9e63e38deb6674b57519482033cf1d2e8c01e6c9/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4883753a-a72e-4155-8adf-2519da245617) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82297a8d7d233a3a9450c3190aa82272960480a9/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df29023f-657c-48c1-9824-d308a6968043) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/82297a8d7d233a3a9450c3190aa82272960480a9/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64444c96-6985-4721-8359-53fe19313aeb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/55a06dfe97db1228a3e61ea7f4ccbb8387ea1fd2/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d591537e-32b9-49bf-8859-09b5714a8511) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/55a06dfe97db1228a3e61ea7f4ccbb8387ea1fd2/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1df8d662-1975-40f1-90fb-278ebf4fa63d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efd0abd7ea908697247cfa294fd283bd168f674e/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33120bc0-24ce-4064-b1a5-9c26d5532896) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/efd0abd7ea908697247cfa294fd283bd168f674e/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46e073c9-9680-4d42-9208-90f33575f8bb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fee784785bb48f2822af8fedc9d3769e9d006860/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1355084-4880-4a18-91bf-aa463e26f049) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fee784785bb48f2822af8fedc9d3769e9d006860/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e81dde00-fe5c-4322-ad2b-71b1930c735c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27ed924491afbbe97a9e99d7b26275d953b91797/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8627e809-652c-480a-97de-4bad8b4addb3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/27ed924491afbbe97a9e99d7b26275d953b91797/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad4cb087-95ba-4e11-9099-d222c684c3ed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4eb680fa607493ca00a44955564633fc53f471a5/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a53667a-f900-46c1-902e-9a63cef4a7ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4eb680fa607493ca00a44955564633fc53f471a5/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22f79df7-7f83-4cb8-98c1-e32b0ad7a576) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — DISMISSED** [review]
Approved

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ee1beb22acbf7f59882efae8c5c13cfd758506d/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b672fc6d-98ec-4a47-8288-e2caf6d84527) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2ee1beb22acbf7f59882efae8c5c13cfd758506d/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e5ce5e1-fcd9-48a8-a876-e11c498bc771) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]
Approved

**Pull request merged**
