### PR TITLE
[Doc-Improvement][Distribute-app-edits]

### PR DESCRIPTION
**Pull request by v-shalinirobinson**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/098991de3af5ccc96c8225ea506e10393f61c856/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59ca2f9f-ec8c-4d43-8009-aed7af898c09) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/098991de3af5ccc96c8225ea506e10393f61c856/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fd59dd4-88b5-49ba-8918-2b627828142f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06e09bb6a162ae25b530f0254cedf48198732737/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4128bfd0-73c7-4574-a80b-f49269f38a47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06e09bb6a162ae25b530f0254cedf48198732737/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0200245-c878-4cb1-8df4-bcbc18e8be93) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06e09bb6a162ae25b530f0254cedf48198732737/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eac22699-3c45-4e26-94f2-7e99adb32b5f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e125a6fcb34625e5b1cf75ce1210488a820b8f7b/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/034cf104-bd15-452f-801b-93123cf97b8e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e125a6fcb34625e5b1cf75ce1210488a820b8f7b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ec3fbfc-efdd-4374-8fda-1451a8a40e83) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e125a6fcb34625e5b1cf75ce1210488a820b8f7b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e372bf24-ddb0-484f-8d2f-ad12e4ee8a73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e125a6fcb34625e5b1cf75ce1210488a820b8f7b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ac97394-8d16-4de4-ae54-97cc1346e134) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e125a6fcb34625e5b1cf75ce1210488a820b8f7b/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d97b8c96-e525-433f-a562-3c6e12abc499) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f36d31239f7ba3974d25086ec81094708ce9cd1d/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e38c8101-8716-4b08-9385-f117de80cf9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f36d31239f7ba3974d25086ec81094708ce9cd1d/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91494605-1ad0-403d-bfc2-1a7ddcf0d132) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f36d31239f7ba3974d25086ec81094708ce9cd1d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/976ca241-aea4-43ce-a387-07182e289aa3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f36d31239f7ba3974d25086ec81094708ce9cd1d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c186787c-8a39-4c14-b263-aff23ec6c819) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f36d31239f7ba3974d25086ec81094708ce9cd1d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Foverview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3116580e-0a59-4538-94c2-38f8fc9965d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f36d31239f7ba3974d25086ec81094708ce9cd1d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94186497-ba7c-4313-a350-27c05416de57) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/903e6718abe026e956642a8e128cd75ad7498a74/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ba9aa79-0d42-412b-b90f-a5b8bd9b590b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/903e6718abe026e956642a8e128cd75ad7498a74/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b37d384-b15b-497d-8b3c-a9db04e16cfe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-publish-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/903e6718abe026e956642a8e128cd75ad7498a74/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-publish-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27fb7a08-2af5-4898-9c14-c6f94a6f3df2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/903e6718abe026e956642a8e128cd75ad7498a74/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a6e89c8-97a3-43e4-9ddd-2bf111b27cd5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/903e6718abe026e956642a8e128cd75ad7498a74/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Foverview.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d11e7b1-26bc-4c76-be39-a571fb4a9bee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/903e6718abe026e956642a8e128cd75ad7498a74/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 92 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/997bb4e9-fc42-4e85-ab82-be53c3d845d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/903e6718abe026e956642a8e128cd75ad7498a74/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acda03f9-3596-4cc6-8ab7-cba916d66193) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
