### PR TITLE
[Doc Improvement][Store install flow change part 5][3733098]

### PR DESCRIPTION
**Pull request by v-ramyas5**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4aa7e436958afe09984e78e35f55219c6f6591b9/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 107 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7fac0be1-51a7-4745-8a69-e2f8d3d4974e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4aa7e436958afe09984e78e35f55219c6f6591b9/msteams-platform%2Fsbs-bots-with-sso.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03a473f2-6fee-4777-a806-3f4f08f9ab78) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8a39e49dea7b4ec909b1bcb1b64d7f09379e0413/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 107 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3247f3a-9e88-4a93-a7b8-63508d05d8be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8a39e49dea7b4ec909b1bcb1b64d7f09379e0413/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 82 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1044bf67-aae8-40c9-b254-b12e9c6acf70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8a39e49dea7b4ec909b1bcb1b64d7f09379e0413/msteams-platform%2Fsbs-bots-with-sso.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d189b50f-cb14-4e8b-8148-a5022ad8be23) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cd6ff5ee59f3d2aa18542bc586932518c05dafbf/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 107 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a937fc42-ae83-4e85-991a-3a88823536bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cd6ff5ee59f3d2aa18542bc586932518c05dafbf/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 82 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/806458e8-9cb9-4304-8465-6bbc8929eadd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cd6ff5ee59f3d2aa18542bc586932518c05dafbf/msteams-platform%2Fsbs-bots-with-sso.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d7de0a5-4f1b-4e41-a637-b246be4112d1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c83ab3f503f39c2873c58531d926f010497e4bdb/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 107 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81c2324f-a92c-4e38-aa3c-fadd7000f249) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c83ab3f503f39c2873c58531d926f010497e4bdb/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 82 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9e31358-0587-415a-a2ff-ce34e301bd55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c83ab3f503f39c2873c58531d926f010497e4bdb/msteams-platform%2Fsbs-bots-with-sso.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44391cae-d6fc-4a35-bb09-2a3f8bee8f1a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d5627d86d9f4b9e3109e1466c0e8e119e910be/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 107 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1db69ca3-fed6-43de-85e6-e487f9affae6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d5627d86d9f4b9e3109e1466c0e8e119e910be/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 82 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/868ac89c-6c5f-415c-8767-7fcfcd6a45e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a6d5627d86d9f4b9e3109e1466c0e8e119e910be/msteams-platform%2Fsbs-bots-with-sso.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06fbb6f0-6559-47e9-8e58-b6ed1d3b4a45) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c0630e715724abe9792dd765a6072b5212b4ab61/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 108 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/960b0b61-eb95-42af-9601-b0f5b9301d12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c0630e715724abe9792dd765a6072b5212b4ab61/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 82 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b6eb1ad-363c-4637-9c3d-289becfa8355) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c0630e715724abe9792dd765a6072b5212b4ab61/msteams-platform%2Fsbs-bots-with-sso.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24f311f0-a28f-4d02-9674-b2e867d0affb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b7478494ff86bbff369fbfb6eabcbea18b7e16e8/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 108 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5372158-3593-4928-ab93-6cf5e08ffd68) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b7478494ff86bbff369fbfb6eabcbea18b7e16e8/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 82 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a565d432-afa2-482b-933e-0f2c061bef6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b7478494ff86bbff369fbfb6eabcbea18b7e16e8/msteams-platform%2Fsbs-bots-with-sso.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccb514a5-df66-49df-ad9c-edd4689aaebd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91080eaccc02b3208fd2ff43c766493fd882486f/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 108 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b22144c0-ae94-4130-ae66-932fc31b5ae5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91080eaccc02b3208fd2ff43c766493fd882486f/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 82 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/adda1fed-ddfa-4306-910f-bb80b83e5c3c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/91080eaccc02b3208fd2ff43c766493fd882486f/msteams-platform%2Fsbs-bots-with-sso.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/670efe31-054e-4a90-88c6-d7d0794f46ac) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/101badfb3d4ea9d35425b417cd22dce33c9a198b/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 108 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7dff1e3b-78d7-4d6a-8a8c-464eb6c89738) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/101badfb3d4ea9d35425b417cd22dce33c9a198b/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 82 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0ba018d-ab65-49ad-be47-0575b9d34fa5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/101badfb3d4ea9d35425b417cd22dce33c9a198b/msteams-platform%2Fsbs-bots-with-sso.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63176fde-7f93-4554-85de-33d0915d8793) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/18f5cd0d1d65ca08228e0e914b421c713e868298/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 108 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8dc266bd-4a0f-424d-bec4-2fea157e1738) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/18f5cd0d1d65ca08228e0e914b421c713e868298/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 82 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3da79de4-9e1c-494e-a3d4-c8163a50d098) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/18f5cd0d1d65ca08228e0e914b421c713e868298/msteams-platform%2Fsbs-bots-with-sso.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d991e99a-8b23-4d6b-90d8-d1c74c6199e5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9e1517a97c78958cbf352d6c560e225765ba71f3/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 108 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63281ca7-a6c5-4311-adab-09478b3375d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9e1517a97c78958cbf352d6c560e225765ba71f3/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 82 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c21f895c-5e0e-47f4-ade6-f5f40a9e5f7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9e1517a97c78958cbf352d6c560e225765ba71f3/msteams-platform%2Fsbs-bots-with-sso.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9de121c1-cc02-4a4d-a0c6-75c0d08aa367) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-preethah** [comment]
Approval received from Eric and Manav - [Store Inflow PRs for Approval](https://loop.cloud.microsoft/p/eyJ1IjoiaHR0cHM6Ly9taWNyb3NvZnQuc2hhcmVwb2ludC5jb20vdGVhbXMvRXh0ZW5zaWJpbGl0eWFuZEZ1bmRhbWVudGFscz9uYXY9Y3owbE1rWjBaV0Z0Y3lVeVJrVjRkR1Z1YzJsaWFXeHBkSGxoYm1SR2RXNWtZVzFsYm5SaGJITW1aRDFpSVRKVFNXNUNiRkZ5VGpCTE9DMUhXRTE1T1hGT2MxQjBTVFZUWTFjNFF6VkpiRnAwZVdOdmVUWmFjRXBhVWxKMFowVTBjVlpVY2tVNGQzSjJUREF0YUdRbVpqMHdNVWczUTBaRlMwZGFXall6TWxkS01scEhVa1JaVkU5WVdFOHlXRlJVU1VNMUptTTlKVEpHSm1ac2RXbGtQVEVtWVQxVVpXRnRjeVp3UFNVME1HWnNkV2xrZUNVeVJteHZiM0F0Y0dGblpTMWpiMjUwWVdsdVpYST0ifQ%3D%3D)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/21412ae93e06792ccc451ccaaeee2edbd0cf0a12/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 108 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d981e7cc-f2af-4c38-9422-a618076ad3fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/21412ae93e06792ccc451ccaaeee2edbd0cf0a12/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 82 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c65e2e35-c901-4e54-b5bb-bdc6dc2164bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/21412ae93e06792ccc451ccaaeee2edbd0cf0a12/msteams-platform%2Fsbs-bots-with-sso.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3abbae6e-383a-46b1-92bb-4cce1b52f582) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f00819b81d3608c69b73615792b39b188a27dafb/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 108 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2b51122-9d34-4004-9610-cc7c7636ff78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f00819b81d3608c69b73615792b39b188a27dafb/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 82 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aded4440-ce53-4fd8-b05b-676506aaa754) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f00819b81d3608c69b73615792b39b188a27dafb/msteams-platform%2Fsbs-bots-with-sso.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a62145c-898a-459c-88f0-cfa1222a80ea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
