### PR TITLE
[Doc Update][Message-extension-7][2377257]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43e82b1a1b05e11f29cc1e5f08bd9e2b463ce073/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56470d31-de15-4468-a806-57406f045aec) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/698ba576da381e625c446efb36e5f47cdff8817b/msteams-platform%2Ffeedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58cad63b-766e-41b2-a8d9-e63eb61cad0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/698ba576da381e625c446efb36e5f47cdff8817b/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/260ff96d-5f70-434d-b821-2695e8d6b18d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e6154ae828b09c86a88afab95725210d98d9b16/msteams-platform%2Ffeedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c298a35b-3f9a-4f35-ae4b-d700a6097522) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e6154ae828b09c86a88afab95725210d98d9b16/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3c4dfbb-d93b-469a-bb89-95b375984c32) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e6154ae828b09c86a88afab95725210d98d9b16/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2a344a9-5882-4ce5-80b3-23e5b3e9e818) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c9fe7134fe8629714eac66ee14f7676247f7ad8/msteams-platform%2Ffeedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6bbd345-553f-4d1d-a289-a5c13fc2da61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c9fe7134fe8629714eac66ee14f7676247f7ad8/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/120051a9-59a8-4135-ba82-10bfcbaf9f14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c9fe7134fe8629714eac66ee14f7676247f7ad8/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22cebd60-25b4-434f-818e-3ebabd07e990) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c9fe7134fe8629714eac66ee14f7676247f7ad8/msteams-platform%2Fwhats-new.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47348de5-9de7-4829-983f-976c2fc1223b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/974ba0a471cf7fa1cce7dabac1057d572bebbfee/msteams-platform%2Ffeedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e5c5516-990b-493a-806c-cce3948e86fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/974ba0a471cf7fa1cce7dabac1057d572bebbfee/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca9e7cd5-3985-40c7-a179-9375805b18a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/974ba0a471cf7fa1cce7dabac1057d572bebbfee/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f695cfbb-2fd5-498b-be73-443a2022ec27) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/974ba0a471cf7fa1cce7dabac1057d572bebbfee/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28a73b29-c636-4ec3-a723-79561e062f31) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/974ba0a471cf7fa1cce7dabac1057d572bebbfee/msteams-platform%2Fwhats-new.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce121044-552d-4388-bf83-9854995fb75b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54d839d0e2b37a95509b42699670bbd1f312a249/msteams-platform%2Ffeedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0be40a0-3613-4939-9c87-34278974a83c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54d839d0e2b37a95509b42699670bbd1f312a249/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a6faf91-45be-40f7-ad0b-7a76c5f0cbd8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/54d839d0e2b37a95509b42699670bbd1f312a249/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e662b2dd-6b28-4ece-85cb-3ccd6b8fc3ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54d839d0e2b37a95509b42699670bbd1f312a249/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d054ffe1-68b5-4c2d-8942-77eefb923fcd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54d839d0e2b37a95509b42699670bbd1f312a249/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a88bcbc4-1c71-4148-8177-494ec7fda4fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54d839d0e2b37a95509b42699670bbd1f312a249/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 82 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af01e11c-93ca-470f-baa4-c0afb69cc4e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54d839d0e2b37a95509b42699670bbd1f312a249/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b10bf80c-6c8d-41fd-814f-5324e5df3884) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54d839d0e2b37a95509b42699670bbd1f312a249/msteams-platform%2Ftoolkit%2Fdeploy.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0521450-3df2-4d53-a6db-112ec2a6f779) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54d839d0e2b37a95509b42699670bbd1f312a249/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cf86af4-e8e6-4755-b760-c432c839ba8a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54d839d0e2b37a95509b42699670bbd1f312a249/msteams-platform%2Fwhats-new.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee163e4e-55a6-43bc-9d5c-3fad4c17e522) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c23727d5d570fed91a2020e1d96a276d332c9f8/msteams-platform%2Ffeedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99dd655f-13c0-43f4-9a7f-5bb06699cb55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c23727d5d570fed91a2020e1d96a276d332c9f8/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2daf096-849f-464e-8c97-d056868e3b0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2c23727d5d570fed91a2020e1d96a276d332c9f8/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3798db8-4e1f-4037-ab8d-69cc4ff6c426) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c23727d5d570fed91a2020e1d96a276d332c9f8/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4e9e9f7-ca0c-41c2-8a40-b562b2601698) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c23727d5d570fed91a2020e1d96a276d332c9f8/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b0598ef-a4c4-4da9-b34d-fcc067742f35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c23727d5d570fed91a2020e1d96a276d332c9f8/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 82 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43b224af-fa22-4887-a751-5865beff15c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c23727d5d570fed91a2020e1d96a276d332c9f8/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b28de32f-4246-44fa-a9f5-f6e10876a347) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c23727d5d570fed91a2020e1d96a276d332c9f8/msteams-platform%2Ftoolkit%2Fdeploy.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08f097e5-2a4a-465b-9ba6-ba6c2d48ef6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c23727d5d570fed91a2020e1d96a276d332c9f8/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a2f2eb3-b5ec-4b54-a5e8-b56e214f8f47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c23727d5d570fed91a2020e1d96a276d332c9f8/msteams-platform%2Fwhats-new.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/894ed2ae-ad0a-41ad-8274-bbf8d6a769ac) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by stkong-sdk — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64f6e48c9ce0daf73b1928eca5eea516daec2783/msteams-platform%2Ffeedback.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb835322-dddd-4419-92a4-527e1555ca69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64f6e48c9ce0daf73b1928eca5eea516daec2783/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e79077a8-a283-440f-8373-059f4e1e3756) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/64f6e48c9ce0daf73b1928eca5eea516daec2783/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eeae7638-796c-4a43-b9eb-4df918ab9929) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64f6e48c9ce0daf73b1928eca5eea516daec2783/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2dcd063-e64e-4dc3-886f-47bf15b9bcf5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64f6e48c9ce0daf73b1928eca5eea516daec2783/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e182ad7-83ab-40f7-82a3-f218e7e47d09) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64f6e48c9ce0daf73b1928eca5eea516daec2783/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 86 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31165001-20e6-4bd2-9c25-5e158ed1e057) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64f6e48c9ce0daf73b1928eca5eea516daec2783/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e423c95-08a1-41ec-bfff-6046bcb20b8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64f6e48c9ce0daf73b1928eca5eea516daec2783/msteams-platform%2Ftoolkit%2Fdeploy.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f9e05f4-7cea-4f94-a3fb-d409dea78522) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64f6e48c9ce0daf73b1928eca5eea516daec2783/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe54b0e9-acb7-4d2e-857f-a9298f302920) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/64f6e48c9ce0daf73b1928eca5eea516daec2783/msteams-platform%2Fwhats-new.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2013a251-6a7d-4be3-924c-ab1ee090d370) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
