### PR TITLE
[Doc Improvement][Update the docs set with consistent app manifest terminology][3124756]

### PR DESCRIPTION
**Pull request by v-ganr**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0183c1f35107746cac82fe6e2184dfd2888231be/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c45f77a-ae00-4e81-a89f-2e3bf26bf4b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0183c1f35107746cac82fe6e2184dfd2888231be/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d67ce58-3c60-4cc9-a1e8-dd030a6997ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0183c1f35107746cac82fe6e2184dfd2888231be/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da35d1d5-0496-4a4f-a9d2-50a9da6b708e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee48b31a9bd404f98a46d55274bf3a8bcfd28cca/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43c4aec0-3430-472d-a0b2-72bde3776790) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee48b31a9bd404f98a46d55274bf3a8bcfd28cca/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8fece97f-0d94-4400-9b50-78515b104c53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee48b31a9bd404f98a46d55274bf3a8bcfd28cca/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f72f2bb-4f4f-4b50-aa13-e0e1599963ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee48b31a9bd404f98a46d55274bf3a8bcfd28cca/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0194e67-05b1-476d-bce0-b1a7583f100b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ee48b31a9bd404f98a46d55274bf3a8bcfd28cca/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 81 | 60 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/767eb816-7f4d-4694-af92-187b941cc4aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ee48b31a9bd404f98a46d55274bf3a8bcfd28cca/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 86 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21309a64-534a-43ff-8155-2b2b259f75e9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3513cdbaba0d95d5832593ec1d202b67f159ee6e/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/babee898-33d7-4ff6-94b0-cd1c55819779) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3513cdbaba0d95d5832593ec1d202b67f159ee6e/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84bedb36-c02c-4c66-bf84-cfbce5090652) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3513cdbaba0d95d5832593ec1d202b67f159ee6e/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9878cd79-6f94-410c-9c44-30f900ebdbec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3513cdbaba0d95d5832593ec1d202b67f159ee6e/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cdbe531-23eb-48e1-8db8-b8b89d7dac6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3513cdbaba0d95d5832593ec1d202b67f159ee6e/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 81 | 60 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b2b60f8-e447-40d3-b582-17cf869edce3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3513cdbaba0d95d5832593ec1d202b67f159ee6e/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 86 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f66322e7-8db6-4afb-9eba-12ec183e4b6f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by erikadoyle — APPROVED** [review]
Thank you @v-ganr, this looks good!

**Review by ChetanSharma-msft — APPROVED** [review]
Looks fine, approving it.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a38a345c0e37457ed7cebbb51bb6317bf859a30d/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bac58209-dab1-42b8-beab-44b898a23818) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a38a345c0e37457ed7cebbb51bb6317bf859a30d/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0db99074-a9b0-402a-8635-b8c89b6c922f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a38a345c0e37457ed7cebbb51bb6317bf859a30d/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93778d6c-c33b-4c56-b36c-7adc796426ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a38a345c0e37457ed7cebbb51bb6317bf859a30d/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aab19689-47c7-42bd-9015-79f1845d7315) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a38a345c0e37457ed7cebbb51bb6317bf859a30d/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 75 | 74 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bb038b6-246d-42d3-adad-ace7d39a544e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a38a345c0e37457ed7cebbb51bb6317bf859a30d/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 86 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/796df0ce-e481-4463-bcd4-52feb278cca2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c30c31d15b431e8291c2a0ab0d4c4520334a142/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d762386-e494-4c2d-9ab4-1aaa54cd2b1b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c30c31d15b431e8291c2a0ab0d4c4520334a142/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11c0cf7c-688f-4d5b-ab6a-63a2dcb0a3ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c30c31d15b431e8291c2a0ab0d4c4520334a142/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/532157e9-45c1-44fe-b9f6-c59b7b7d40c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c30c31d15b431e8291c2a0ab0d4c4520334a142/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4d733e2-37e2-416a-a10e-021547411716) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8c30c31d15b431e8291c2a0ab0d4c4520334a142/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 77 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef0a9161-9d15-4ea0-a152-217cdd40b323) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8c30c31d15b431e8291c2a0ab0d4c4520334a142/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 86 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f694eecb-cad3-4a2f-b936-a798f40f0010) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/989bbc89b62ff773fab6c4211dbc51ae536e9d42/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cd2eb16-22d3-449e-bc8d-8fa653f7c267) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/989bbc89b62ff773fab6c4211dbc51ae536e9d42/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67306398-7ee1-424a-bd84-a5745efd51e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/989bbc89b62ff773fab6c4211dbc51ae536e9d42/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c0ce55f-9582-4299-ba93-53a860898647) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/989bbc89b62ff773fab6c4211dbc51ae536e9d42/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/751ff33d-9061-45f4-a3f2-cc395d4b1773) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/989bbc89b62ff773fab6c4211dbc51ae536e9d42/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 79 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5048539a-278b-4330-948b-4c84e9e7e8dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/989bbc89b62ff773fab6c4211dbc51ae536e9d42/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 86 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93acc604-1539-453c-81b7-ddf454c345f3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b57e3cf65e33e5571318935fe0bac9c51cbc1de2/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25da4e87-02fa-42f7-92fb-428661112787) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b57e3cf65e33e5571318935fe0bac9c51cbc1de2/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a89bf4e-b1c8-4fbc-986d-ea9f5eed9bbe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b57e3cf65e33e5571318935fe0bac9c51cbc1de2/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8808a54d-98cc-45f3-8df4-36c5a3f8b8b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b57e3cf65e33e5571318935fe0bac9c51cbc1de2/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2f29b3a-fe60-4b7e-acb8-781ffdb825b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b57e3cf65e33e5571318935fe0bac9c51cbc1de2/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 79 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c23aba5-be80-4eb4-80d6-9839ebbbe6c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b57e3cf65e33e5571318935fe0bac9c51cbc1de2/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 86 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfac0a41-a5c5-444f-a14b-407ab06106ef) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/373a7dc978877234a2f05b00b0d1930db637c149/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07057184-c04e-4c13-86c2-6ad0184804c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/373a7dc978877234a2f05b00b0d1930db637c149/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0f8e4b1-9f68-4885-bba1-cc1e1ebcfcac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/373a7dc978877234a2f05b00b0d1930db637c149/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5edee507-ef08-4123-b23a-17d779736198) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/373a7dc978877234a2f05b00b0d1930db637c149/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 93 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35443817-c585-4f3f-9e49-b2e4d5a53284) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/373a7dc978877234a2f05b00b0d1930db637c149/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 75 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8db4bbd5-825a-47d4-b336-4aa7bd72eac6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/373a7dc978877234a2f05b00b0d1930db637c149/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 86 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4acc4f68-d697-4404-bb2e-b2a6e9c61736) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-deabira** [comment]
Closing the PR as the content has been added to PR #9328

**Pull request closed without merging**
