### PR TITLE
[Doc Improvement][Verify and fix casing and sign in][2987574]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/afc1a78f9ab88bf425bf6006028618d04ded2760/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1704350-fc7f-41c3-bb18-7c8ef631a79f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/afc1a78f9ab88bf425bf6006028618d04ded2760/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed9d8725-8d1a-4d98-be6a-d15f3206da6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/afc1a78f9ab88bf425bf6006028618d04ded2760/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86f9b289-595a-4f81-8c99-3b0556823182) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a2ddb9d761f63ea5bb92d4c604a6c481a85acc5/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82ca8274-1566-410e-9d16-cc9d1541596f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a2ddb9d761f63ea5bb92d4c604a6c481a85acc5/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2426bbcf-94c1-46bb-8f90-d8a65f8b7ba4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a2ddb9d761f63ea5bb92d4c604a6c481a85acc5/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2341243a-e484-4e25-ad4f-d0c678255c6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a2ddb9d761f63ea5bb92d4c604a6c481a85acc5/msteams-platform%2Ftoolkit%2Fdeploy.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c15bb42-7b87-4922-a72c-9c1eb7f3b29d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a2ddb9d761f63ea5bb92d4c604a6c481a85acc5/msteams-platform%2Ftoolkit%2Fprovision.md) | 96 | 60 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30dd790d-497f-4e71-baaa-cfd67eabcfb3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d7219659957e8b92ca67c9762b8c176ef1c39282/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ae884e2-998d-4d5b-ba88-800e4dc2490d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d7219659957e8b92ca67c9762b8c176ef1c39282/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b5379e4-c956-46cc-92e1-68823851a06b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d7219659957e8b92ca67c9762b8c176ef1c39282/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a150261-5abe-40c8-8305-0b16d8949136) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d7219659957e8b92ca67c9762b8c176ef1c39282/msteams-platform%2Ftoolkit%2Fdeploy.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1dab714e-782e-46df-928f-6ca6142f8e06) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d7219659957e8b92ca67c9762b8c176ef1c39282/msteams-platform%2Ftoolkit%2Fprovision.md) | 96 | 60 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/740e49df-1dbf-4fc1-9554-73b6b214b554) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d903b42dc93ae8dd704258ae79f266afe144cf5/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e6f2ea5-2d59-466f-89a9-c8eddbfc816b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d903b42dc93ae8dd704258ae79f266afe144cf5/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66b388b0-19eb-4650-9506-ed194dc84b66) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f15ca812318228b765e940a45f5202d22fbe7e9/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/294e7f0a-5fd0-48a3-9f0b-e6c1b47b9cef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f15ca812318228b765e940a45f5202d22fbe7e9/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d572733e-d0b3-4a9c-a883-72f8c63baf46) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-background-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c864cc4e08bb47aeace9810a29f2dfd9fe213d1/msteams-platform%2Ftoolkit%2Fdebug-background-process.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1187a946-9676-4678-9748-26ec553406fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c864cc4e08bb47aeace9810a29f2dfd9fe213d1/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00bd0fbe-064e-482c-8909-5e229f6f0034) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
