### PR TITLE
Mobile dev preview changes

### PR DESCRIPTION
**Pull request by clearab**

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[f0e140c](https://github.com/MicrosoftDocs/msteams-docs/pull/724/commits/f0e140c660ef0d5b92fdbceea8bfd829b87ad0fd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/authentication/authentication.md) | :warning:Warning | | [Details](#user-content-46698f8c-e22e85bf)
[msteams-platform/concepts/tabs/tabs-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-requirements.md) | :warning:Warning | | [Details](#user-content-33b5fda6-e22e85bf)
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/whats-new.md) | :warning:Warning | | [Details](#user-content-22e47ad6-e22e85bf)
[msteams-platform/concepts/apps/apps-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/apps/apps-update.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/authentication/auth-flow-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/authentication/auth-flow-bot.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/bots/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/bots/bots-with-tabs.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-content.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-static.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-static.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/resources/dev-preview/developer-preview-features.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/resources/dev-preview/developer-preview-intro.md) | :white_check_mark:Succeeded | |

<a id="46698f8c-e22e85bf"></a>
### [msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/authentication/authentication.md)
 - **Line 14**: **[Warning]** `````Invalid file link:(~/concepts/authentication/auth-oauth-card).`````
 - **Line 22**: **[Warning]** `````Invalid file link:(~/concepts/authentication/auth-flow-tab).`````
 - **Line 23**: **[Warning]** `````Invalid file link:(~/concepts/authentication/auth-flow-bot).`````
 - **Line 29**: **[Warning]** `````Invalid file link:(~/concepts/authentication/auth-tab-AAD).`````
 - **Line 30**: **[Warning]** `````Invalid file link:(~/concepts/authentication/auth-bot-AAD).`````
 - **Line 31**: **[Warning]** `````Invalid file link:(~/concepts/authentication/auth-silent-AAD).`````

<a id="33b5fda6-e22e85bf"></a>
### [msteams-platform/concepts/tabs/tabs-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-requirements.md)
 - **Line 19**: **[Warning]** `````Invalid file link:(~/resources/schema/manifest-schema#validdomains).`````
 - **Line 21**: **[Warning]** `````Invalid file link:(~/troubleshoot/troubleshoot).`````
 - **Line 36**: **[Warning]** `````Invalid file link:(~/concepts/tabs/tabs-configuration#determine-the-content-to-display-in-the-tab).`````

<a id="22e47ad6-e22e85bf"></a>
### [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/whats-new.md)
 - **Line 14**: **[Warning]** `````Invalid file link:(~/resources/developer-preview-intro.md).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201906161944100590-724%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a%2BMNhl4GML7%2FrqomU9jAjUi8EdsDRJc%2BooENeJd6eaU%3D&st=2019-06-16T19%3A40%3A22Z&se=2019-07-17T19%3A45%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[197d928](https://github.com/MicrosoftDocs/msteams-docs/pull/724/commits/197d92827400027c6a1384fc6b83279ab3148982)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/apps/apps-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/apps/apps-update.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/authentication/auth-flow-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/authentication/auth-flow-bot.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/bots/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/bots/bots-with-tabs.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-content.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-requirements.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-static.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-static.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/resources/dev-preview/developer-preview-features.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/resources/dev-preview/developer-preview-intro.md) | :white_check_mark:Succeeded | |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201906161953543239-724%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cVl%2BGjE6eojuHS75t546Ccw%2FSIJ0FP28ladVGoPppDA%3D&st=2019-06-16T19%3A49%3A53Z&se=2019-07-17T19%3A54%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[5d6c7bd](https://github.com/MicrosoftDocs/msteams-docs/pull/724/commits/5d6c7bd09791afdbd93600df7b64695660957162)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/publishing/apps-publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/publishing/apps-publish.md) | :warning:Warning | | [Details](#user-content-d4b0d992-fc5aa330)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/apps/apps-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/apps/apps-update.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/authentication/auth-flow-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/authentication/auth-flow-bot.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/bots/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/bots/bots-with-tabs.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-content.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-requirements.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-static.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-static.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/design/framework/mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/resources/design/framework/mobile.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/resources/dev-preview/developer-preview-features.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/resources/dev-preview/developer-preview-intro.md) | :white_check_mark:Succeeded | |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | |

<a id="d4b0d992-fc5aa330"></a>
### [msteams-platform/publishing/apps-publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/publishing/apps-publish.md)
 - **Line 11**: **[Warning]** `````Invalid file link:(~/resources/design/overview).`````
 - **Line 21**: **[Warning]** `````Invalid file link:(~/resources/schema/manifest-schema).`````
 - **Line 21**: **[Warning]** `````Invalid file link:(~/concepts/apps/apps-package).`````
 - **Line 23**: **[Warning]** `````Invalid file link:(~/resources/design/overview).`````
 - **Line 66**: **[Warning]** `````Invalid file link:(~/concepts/apps/apps-package).`````
 - **Line 66**: **[Warning]** `````Invalid file link:(~/publishing/office-store-checklist).`````
 - **Line 71**: **[Warning]** `````Invalid file link:(~/publishing/office-store-guidance).`````
 - **Line 108**: **[Warning]** `````Invalid file link:(~/resources/schema/manifest-schema#bots).`````
 - **Line 132**: **[Warning]** `````Invalid file link:(~/troubleshoot/troubleshoot#issues-with-packaging-and-uploading).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201906162352140607-724%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dfRa9FTzHCpqfAB7eExmJVHeDkbx52AMse491ROKHWM%3D&st=2019-06-16T23%3A48%3A32Z&se=2019-07-17T23%3A53%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[18e343f](https://github.com/MicrosoftDocs/msteams-docs/pull/724/commits/18e343fa7eedc140f38495506d2b01895b3b4370)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/publishing/apps-publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/publishing/apps-publish.md) | :warning:Warning | | [Details](#user-content-d4b0d992-3b7674f4)
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/apps/apps-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/apps/apps-update.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/authentication/auth-flow-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/authentication/auth-flow-bot.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/bots/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/bots/bots-with-tabs.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-content.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-requirements.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-static.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-static.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/design/framework/mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/resources/design/framework/mobile.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/resources/dev-preview/developer-preview-features.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/resources/dev-preview/developer-preview-intro.md) | :white_check_mark:Succeeded | |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | |

<a id="d4b0d992-3b7674f4"></a>
### [msteams-platform/publishing/apps-publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/publishing/apps-publish.md)
 - **Line 22**: **[Warning]** `````Invalid file link:(~/resources/design/overview).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C16%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201906162358450355-724%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eVIz62mJj0E44c3kZn5Ka6e5IFhf2injw8Lklp8Of%2Bs%3D&st=2019-06-16T23%3A55%3A01Z&se=2019-07-18T00%3A00%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[40709ef](https://github.com/MicrosoftDocs/msteams-docs/pull/724/commits/40709efb6fe2b67d587313bf305121237f074183)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/TOC.yml) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/apps/apps-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/apps/apps-update.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/authentication/auth-flow-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/authentication/auth-flow-bot.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/authentication/authentication.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/bots/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/bots/bots-with-tabs.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-content.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-content.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-requirements.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-requirements.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/tabs/tabs-static.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/concepts/tabs/tabs-static.md) | :white_check_mark:Succeeded | |
[msteams-platform/publishing/apps-publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/publishing/apps-publish.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/design/framework/mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/resources/design/framework/mobile.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/resources/dev-preview/developer-preview-features.md) | :white_check_mark:Succeeded | |
[msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/resources/dev-preview/developer-preview-intro.md) | :white_check_mark:Succeeded | |
[msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-mobile-dev-preview/msteams-platform/whats-new.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201906170001263402-724%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fzoeydJtZXhqX9l80jA%2BWv56G%2Fxj%2FjuyXgJK5q4TW1o%3D&st=2019-06-16T23%3A57%3A30Z&se=2019-07-18T00%3A02%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[6b6c7f5](https://github.com/MicrosoftDocs/msteams-docs/pull/724/commits/6b6c7f5c28ca58eb6bff6fcd333b19857a12cf93)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-901e4b33)

<a id="901e4b33"></a>
###
 - **[Error]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/msteams-docs, working directory: W:\42l1-s, target branch: master, target branch commit: 8b7e60cadc5408df2f50a3deea870cc44167482c, source commit: 6b6c7f5c28ca58eb6bff6fcd333b19857a12cf93.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C12%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201907122126038393-724%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4mN6kDe86Fr%2Bd48KMIyxZQlGxEC%2BzripMm2Z%2BlF8BVQ%3D&st=2019-07-12T21%3A21%3A19Z&se=2019-08-12T21%3A26%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clearab** [comment]
Closing and recreating.

**Pull request closed without merging**
