### PR TITLE
[Doc Improvement][Remove time and future ref: 9][3886830]

### PR DESCRIPTION
**Pull request by v-bvishnu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5e9332c213947d7a56106d62fa5b7ce4eeccda/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a2c4c3d-abd6-4009-bdcc-a7bf64929c04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5e9332c213947d7a56106d62fa5b7ce4eeccda/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 84 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/769d5764-653d-41e1-b0e8-bd73b9bf9d3e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/launch-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5e9332c213947d7a56106d62fa5b7ce4eeccda/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Flaunch-app.md) | 82 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2acbbcd7-06e9-4e54-ac87-d3978beaf262) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5e9332c213947d7a56106d62fa5b7ce4eeccda/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7b6f5da-8296-4bd2-9fb0-4d34f09fd293) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5e9332c213947d7a56106d62fa5b7ce4eeccda/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55add000-634c-45bd-a941-b65ee3f0e696) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5e9332c213947d7a56106d62fa5b7ce4eeccda/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e80181f9-58b6-4fa8-a884-477ab86ca75a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5e9332c213947d7a56106d62fa5b7ce4eeccda/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c13c9a1e-85c1-40f0-b43d-c17db4883b14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/messaging-extensions-common.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5e9332c213947d7a56106d62fa5b7ce4eeccda/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmessaging-extensions-common.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52f1246c-b2c5-4071-a027-baa5ff3c5404) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5e9332c213947d7a56106d62fa5b7ce4eeccda/msteams-platform%2Fincludes%2Ftabs%2Fdotnet-update-chan-grp-app.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1985cf26-5df0-493c-8352-e204a995cdf3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/teamjs-version-details.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5e9332c213947d7a56106d62fa5b7ce4eeccda/msteams-platform%2Fincludes%2Fteamjs-version-details.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ed0ebf3-9ac5-4544-8536-34d38616cd91) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7927ec2582bb7f64aab530b026557bc877e31269/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26e34cc3-37ff-4b14-83f6-7cd8375563ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7927ec2582bb7f64aab530b026557bc877e31269/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 84 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00b0392e-958a-4261-abc2-820494a5b8fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/launch-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7927ec2582bb7f64aab530b026557bc877e31269/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Flaunch-app.md) | 82 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7486eacd-5cc9-4b40-b7c0-133ba6e101cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7927ec2582bb7f64aab530b026557bc877e31269/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f74722a-3396-4c44-88fa-444b58ef97ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7927ec2582bb7f64aab530b026557bc877e31269/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4572c82-69d5-4338-badb-86366b9907fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7927ec2582bb7f64aab530b026557bc877e31269/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4212c21-67ff-4596-9949-52a97eeab9a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7927ec2582bb7f64aab530b026557bc877e31269/msteams-platform%2Fincludes%2Ftabs%2Fdotnet-update-chan-grp-app.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aecbb202-5180-4dfa-a6b6-b8aeedb69862) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/teamjs-version-details.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7927ec2582bb7f64aab530b026557bc877e31269/msteams-platform%2Fincludes%2Fteamjs-version-details.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dcefdafa-e666-4a7c-b4b3-70b69234f0ed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7af1643f4996613dff5cf381b5e987f221fa5cca/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4eed258c-e063-4603-b2a8-04add18252ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7af1643f4996613dff5cf381b5e987f221fa5cca/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 84 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7c42e04-cf38-4fd4-aa78-911e6a115332) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/launch-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7af1643f4996613dff5cf381b5e987f221fa5cca/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Flaunch-app.md) | 82 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c599c81-70e8-4a44-a223-4120e4a19643) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7af1643f4996613dff5cf381b5e987f221fa5cca/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 86 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87829931-88a3-417b-8240-a623765c244d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7af1643f4996613dff5cf381b5e987f221fa5cca/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d458d6b-b63d-4dd2-ab8c-0fa2e1cd8a30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7af1643f4996613dff5cf381b5e987f221fa5cca/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/090b2610-2519-478e-b743-bf9d4552f2a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7af1643f4996613dff5cf381b5e987f221fa5cca/msteams-platform%2Fincludes%2Ftabs%2Fdotnet-update-chan-grp-app.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4309f361-e4cd-4fbc-9bd5-7941c59ce61d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/teamjs-version-details.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7af1643f4996613dff5cf381b5e987f221fa5cca/msteams-platform%2Fincludes%2Fteamjs-version-details.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27645881-2bd2-4f83-821a-93eda3b0ff8c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-ypalikila — APPROVED** [review]
approved.

**Review by v-deabira — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/092256448e95db5f8c18bc1bf66c177e21070f73/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/136c50e1-3360-4726-acb9-00388c8950e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/092256448e95db5f8c18bc1bf66c177e21070f73/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 84 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41e90771-981d-45c6-8e3a-fa79547d56ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/launch-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/092256448e95db5f8c18bc1bf66c177e21070f73/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Flaunch-app.md) | 82 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e84144e7-6a23-4ec9-a041-fc9501283024) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/092256448e95db5f8c18bc1bf66c177e21070f73/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 86 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc92820f-9af2-4849-854d-74697e46313e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/092256448e95db5f8c18bc1bf66c177e21070f73/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 87 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62c05fc8-682b-4fce-9624-0d957a8139f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/092256448e95db5f8c18bc1bf66c177e21070f73/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/535b68d8-4b93-47aa-9fa6-39675ba02338) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/tabs/dotnet-update-chan-grp-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/092256448e95db5f8c18bc1bf66c177e21070f73/msteams-platform%2Fincludes%2Ftabs%2Fdotnet-update-chan-grp-app.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68ec299e-c739-4ce4-8a20-ca0883c97e61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/teamjs-version-details.md](https://github.com/MicrosoftDocs/msteams-docs/blob/092256448e95db5f8c18bc1bf66c177e21070f73/msteams-platform%2Fincludes%2Fteamjs-version-details.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42d11949-cc49-4e51-9546-4aa89916ef2a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
