### PR TITLE
[Doc Improvement][Anon user support for apps][3030295]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5c1d8bd87f9c1f66e4e536a22939313a81b06666/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29bb405b-f57f-4c99-b402-765959e11a9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c1d8bd87f9c1f66e4e536a22939313a81b06666/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba7a82ec-4589-413b-ab25-5806d151a8d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c1d8bd87f9c1f66e4e536a22939313a81b06666/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4b7e3f4-70ef-40e1-a931-dad92d80e37b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c1d8bd87f9c1f66e4e536a22939313a81b06666/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/467c2d2a-0835-4c5d-95ca-96d413039d70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c1d8bd87f9c1f66e4e536a22939313a81b06666/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 95 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cad21afa-b48f-42f1-ab9c-eeaafc480722) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c1d8bd87f9c1f66e4e536a22939313a81b06666/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9acbd3fc-0288-48ce-9e07-e9bfe6569b4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c1d8bd87f9c1f66e4e536a22939313a81b06666/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ab2ad26-036a-4eb8-802a-279c9128c64a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5c1d8bd87f9c1f66e4e536a22939313a81b06666/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f922515-928f-4e3c-a41d-4fd06b6c8803) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c1d8bd87f9c1f66e4e536a22939313a81b06666/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 93 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d7cbee6-e83d-465d-9efa-d6744f8b6f23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c1d8bd87f9c1f66e4e536a22939313a81b06666/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-overview.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32f16552-8ac9-4ac4-8bb1-fc128b415cf7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c1d8bd87f9c1f66e4e536a22939313a81b06666/msteams-platform%2Fwhats-new.md) | 94 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b43ca20b-6f66-4594-abea-ca4ec41c3382) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/44e5411075a01c269ec521d927b458e9d343cbef/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d198d23-c599-43a9-8d9c-d5f5a470ae63) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44e5411075a01c269ec521d927b458e9d343cbef/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 85 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6952097f-a7df-461c-83c8-46ecde55a9af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44e5411075a01c269ec521d927b458e9d343cbef/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1bef86f0-5a3a-4881-a8f6-1e60d85048d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44e5411075a01c269ec521d927b458e9d343cbef/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0309dfe0-670c-4f47-a214-bb6a72e44ce5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44e5411075a01c269ec521d927b458e9d343cbef/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31b8bddf-5637-4238-ae55-f8ff72a9c3ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44e5411075a01c269ec521d927b458e9d343cbef/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30a2062d-899f-4687-a800-b1c22a1b2e22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44e5411075a01c269ec521d927b458e9d343cbef/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b77c12a-ce3b-4965-b6e8-142e0299dd22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/44e5411075a01c269ec521d927b458e9d343cbef/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf1844e2-8a38-42a5-8dc0-9ed19e99fb53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44e5411075a01c269ec521d927b458e9d343cbef/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 90 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fa74767-4095-4330-b6df-560b96393963) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44e5411075a01c269ec521d927b458e9d343cbef/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-overview.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e89ab42-5d49-407e-9a1a-01ddd156b3fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44e5411075a01c269ec521d927b458e9d343cbef/msteams-platform%2Fwhats-new.md) | 93 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbdf6adc-9dcb-49be-b972-9917a7c58288) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1de1e661b07d5b665b18d57f553e8a62d2dfa743/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3c68e7f-a9d3-4276-87d9-f5d3c4f1f664) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de1e661b07d5b665b18d57f553e8a62d2dfa743/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 88 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2cd04fe5-198b-4807-a81b-ce934f90af0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de1e661b07d5b665b18d57f553e8a62d2dfa743/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70ec9239-16d6-4c97-b980-47b253e18792) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de1e661b07d5b665b18d57f553e8a62d2dfa743/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de075f8a-f501-46db-829e-9a7ec24bf974) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de1e661b07d5b665b18d57f553e8a62d2dfa743/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46816de9-b22d-4bbc-bcb3-66eb6807d032) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de1e661b07d5b665b18d57f553e8a62d2dfa743/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/415b9665-373a-4f6a-a782-d8cea7e97d0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de1e661b07d5b665b18d57f553e8a62d2dfa743/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15a71932-e5e1-4c04-9cdb-db06cb3d1798) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1de1e661b07d5b665b18d57f553e8a62d2dfa743/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64854462-8e33-466f-b3c0-decf6cb01cbe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de1e661b07d5b665b18d57f553e8a62d2dfa743/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 92 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d1e46d8-ca15-470c-95fa-ffcd43387bde) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de1e661b07d5b665b18d57f553e8a62d2dfa743/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-overview.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a35b2d4-f6bb-4f0c-86db-0c4d0e3d6200) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1de1e661b07d5b665b18d57f553e8a62d2dfa743/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5233961-5c2b-4e94-ae76-776874b297c8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-npaladugu** [comment]
Reverted the docs for Anon user support for apps feature. Feature crew informed not to remove the content but add a note. Raised a PR #8783 to update the note.

**Pull request closed without merging**
