### PR TITLE
[Doc Improvement][Verify and fix sign in and casing][3008097]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05104d9d0303d6b6e4131fe7853359324ad7c4ff/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 99 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a6a6d25-cf3c-44fb-bbea-e755e8c5605d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05104d9d0303d6b6e4131fe7853359324ad7c4ff/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7be417e7-1c6f-4000-bfa0-5a4cba581f3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05104d9d0303d6b6e4131fe7853359324ad7c4ff/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 93 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f1211a6-ba3c-499c-96ae-31f2bf5c33b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05104d9d0303d6b6e4131fe7853359324ad7c4ff/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 99 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0eccb417-bb45-4269-b4fc-e00702a545d4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec94145ce64f6d955612459a8fe3bc16074b1ba4/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0a97bbf-a6ca-48c8-af05-eb172dc540eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec94145ce64f6d955612459a8fe3bc16074b1ba4/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 99 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d3d527c-4eb6-4cc9-96f3-0bfe01c89ed0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec94145ce64f6d955612459a8fe3bc16074b1ba4/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1389e5d3-ccdf-47f9-8e90-ec576ac3c175) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec94145ce64f6d955612459a8fe3bc16074b1ba4/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 95 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0633f7f-e69b-4c35-bcab-2a299fca522e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec94145ce64f6d955612459a8fe3bc16074b1ba4/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 93 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a01c3f5-0c3e-4992-8b2d-53166e4f147a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec94145ce64f6d955612459a8fe3bc16074b1ba4/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 99 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/638d593d-91ea-4814-a345-0f2f25568b0a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ff6184e85b0eac20ac1e41ea0f45c6de68001db/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0360252e-0648-4e93-848f-db9338c8a2bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ff6184e85b0eac20ac1e41ea0f45c6de68001db/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 95 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/068fd391-d253-4a74-a9da-4793ec7a1afe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ff6184e85b0eac20ac1e41ea0f45c6de68001db/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 99 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94e34b76-f41e-4a54-937f-ac1d137cbe23) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e709d59afb8f1f50b007c65f798672c233ec65/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e0533d3-d0d5-402c-bb43-fcb18b4acd08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e709d59afb8f1f50b007c65f798672c233ec65/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 95 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3791bda3-cf75-4b00-b2a0-32aa12ac8234) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d5e709d59afb8f1f50b007c65f798672c233ec65/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 99 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e48afe19-36c1-44ee-8f4e-4229c28744a7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5df0e49a2ca7aa62fe255f59951e8c567a47f54d/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba3c9c45-ebf1-491a-a0a8-3c9f76362d89) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5df0e49a2ca7aa62fe255f59951e8c567a47f54d/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 95 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3ecf30c-138e-4843-8dd6-d781fd756f49) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
