### PR TITLE
[Doc feature][API based ME SBS][3340218]

### PR DESCRIPTION
**Pull request by v-ypalikila**
Create an SBS guide to build an API based message extension from using open API spec.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d38c9aba93b0fae889d6b610f957710f6851737a/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 88 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb52f44b-80c6-4348-aa91-8abe3ed973fd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b8ecb0ef09614e3c8c2ed551afec2ce4214179c/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 83 | 100 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4f8dedb-1f68-48d7-b084-dc0c364c64db) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1c706a499feba22747b65b9470c144f5737b8948/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 79 | 109 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ee1e5e0-5ef7-4180-ad35-c9b383ede32a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2c211a470e31c7f3c9a72911b53b294bc08e279d/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 81 | 97 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ab565ff-80cc-48b3-b826-6fb0c1f8dd76) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cea6dfd848879b563a0810edb98aff2aba81c086/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 118 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/333cc2c6-4beb-46ad-a15b-83b7d456e491) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2789bbfb5b14586e88df5d56e2cf3bf4c670c9fc/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 77 | 119 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/681fa748-f80b-4abd-a185-67242b344f06) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2851b3748d5bddc39f9ed411d3f98413f7d58f0a/msteams-platform%2Fsbs-api-based-message-extensions.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/757e9697e8b8b5899ede5aecfcb439f16896fe4b/msteams-platform%2Fsbs-api-based-message-extensions.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b5ce7ee14628b42e7825074e20e61912a730e551/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 80 | 97 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/afb601d0-8a9c-4624-a639-9c1c0784ea44) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7ca4dba2a78087b2ef776e0ea6c0da4195496171/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 78 | 95 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c37ee8b8-b9e4-44d3-a658-2cd993ec8110) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/940d1f7dcc45292af52e5e26fa5a0991fc20d0bc/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 79 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/028c715e-96bc-42f3-8a27-a87939eb9118) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9dab5dc346deef54537423894c409ae89bcb4e59/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 79 | 90 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f214226d-b1bd-439d-82d4-aec3e48e6e6d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8668a1036720ca79d0cc9f81c270396883fcfd05/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 78 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/864e4faa-725d-418c-9662-3f111acacf67) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2e10cd8d6aa72f92c023669504d5ef5d4c571f7b/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 78 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02854ec4-1a60-48f5-9a66-1679095e8001) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/22c83a6b1de9a48ff87acf789ada6872a3ce2476/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 79 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe35d96e-16bd-4633-9ea6-c607fdc91ded) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6791bf34f11770f20fb8bd61487dd111282dcfd6/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 79 | 91 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d8227df-b68f-4640-a32c-5db58e32d477) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/16c67782332a1a07098ca6fdc59d263e512d5b91/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 81 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5779a170-879d-478f-b7b9-f68b9df36696) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bc1b8a80362a67d6f7eaed987ac604aac1e29ffa/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 80 | 89 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b5344cb-7d30-471e-bedf-23b1092dfdc0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/49c7015a46650e91816b41baaad2eba53d44ff59/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 80 | 88 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4184684-f41b-4daf-9f9d-41c50bbb1694) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d6227a3c99f6dce3916e7346375fb98b223e3e81/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 81 | 88 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76766bd1-c854-4bef-809b-5b17d9739e3c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cce4269bec6b0f94efab007e5336bdc2791d31ef/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 81 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74fce13e-fecf-416f-b546-2f6fd816546c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/942a246476f83081445c2b5a08f8360f80679fb6/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 82 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48544933-99f2-4330-b1ea-907d3de62f09) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f42dd5a5f92ff900ba77daa753cd70e01a21aa15/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 82 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7314dca-25c6-4bcf-ad7c-36c53d6cfd59) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-api-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4ef1c47554ed2fbb332c6b697dd562b9f5f867e/msteams-platform%2Fmessaging-extensions%2Fbuild-api-based-message-extension.md) | 94 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49999f09-8456-46e1-9f3d-4a539a156e69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4ef1c47554ed2fbb332c6b697dd562b9f5f867e/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81c2c873-1f67-496c-badb-2654b80b4f64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c4ef1c47554ed2fbb332c6b697dd562b9f5f867e/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 82 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bcc50411-dd4e-4954-b513-4b77f30629d4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-api-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/039a7ae0d5e180bbe3518d5b1382fdd81ac1bf6b/msteams-platform%2Fmessaging-extensions%2Fbuild-api-based-message-extension.md) | 94 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2334f2a5-a723-46fc-9448-69de8e9efc04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/039a7ae0d5e180bbe3518d5b1382fdd81ac1bf6b/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4576346b-bd5b-4c2b-ad22-11c830e6ece1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/039a7ae0d5e180bbe3518d5b1382fdd81ac1bf6b/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 82 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d480ce13-0548-4d48-838f-cf44eabee9b9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-api-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85dac269c375788dffe8e014e81176ce91e19a41/msteams-platform%2Fmessaging-extensions%2Fbuild-api-based-message-extension.md) | 94 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fdbc197-f893-45ba-9cab-3cc1b61aa628) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85dac269c375788dffe8e014e81176ce91e19a41/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98a938b6-be48-4c4b-8659-5309086eb2d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/85dac269c375788dffe8e014e81176ce91e19a41/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 82 | 85 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/335baf3b-11d1-4bab-ae0c-c9d529d367c7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
