### PR TITLE
[Apps][Imageupdate-addcontent][1512111]

### PR DESCRIPTION
**Pull request by Rajeshwari-v**
Updated image.
Updated code section.

### CODE REVIEW

**Review by Nikitha-MSFT — DISMISSED** [review]
Reviewed and approved

**Review by KirtiPereira — CHANGES_REQUESTED** [review]
@Rajeshwari-v - you need to do a thorough self-review of the document. For example, We do not use **Once** as per MSTP instead we use **After**. Another example, why "will receive"? Should it not be **receives**?

**Review by KirtiPereira — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]
Approving the PR

**Pull request merged**
