### PR TITLE
[Doc Improvement] [Update links]

### PR DESCRIPTION
**Pull request by v-ksar**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bfb330fead41e74f56349177e205492c555007f8/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/afe8ee80-9f45-4904-8d6a-918c4a0bb8e0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ae13440e5079f9bb5352ef48489c6ca8c6ff8343/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81e53b53-530b-4d46-8cd1-de3a6015cd0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ae13440e5079f9bb5352ef48489c6ca8c6ff8343/msteams-platform%2Fsbs-gs-spfx.yml) | 94 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2364d2e-aecb-4d52-9029-9d899d9c1b5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae13440e5079f9bb5352ef48489c6ca8c6ff8343/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d75bf56-95fd-4d74-a051-f1925bc66ebf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae13440e5079f9bb5352ef48489c6ca8c6ff8343/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39190c4d-5dcf-4d2e-9e6a-0ace1cf7fb9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae13440e5079f9bb5352ef48489c6ca8c6ff8343/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eaa811ae-97dd-437f-a4bd-baae02ea8eb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae13440e5079f9bb5352ef48489c6ca8c6ff8343/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 85 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f61c772-e89b-4700-a155-e3a812b68075) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae13440e5079f9bb5352ef48489c6ca8c6ff8343/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/38e32269-c968-4e32-a73f-36702f10fe25) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2a72bd244abee007487b24ce195f1d5d489fe849/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3753c390-610e-4bca-b423-ac380f978687) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2a72bd244abee007487b24ce195f1d5d489fe849/msteams-platform%2Fsbs-gs-spfx.yml) | 94 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1342b7a1-81df-450d-a82a-dd5178552c4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a72bd244abee007487b24ce195f1d5d489fe849/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f90f911a-a969-43fe-b570-86ac4e5abf9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a72bd244abee007487b24ce195f1d5d489fe849/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82f7f949-7ca3-4969-94db-2fbc25fc0cd3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a72bd244abee007487b24ce195f1d5d489fe849/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c27d8d42-743b-493f-80af-64dc4ada1d6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a72bd244abee007487b24ce195f1d5d489fe849/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 85 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff467236-e00a-4473-9763-161b3dbddfdf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2a72bd244abee007487b24ce195f1d5d489fe849/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21530426-c125-4b2c-a124-b261130577c9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/26d9fff083084577b20677a382f75cfcfc6fe82e/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/697cba0f-bf2c-4749-8e1f-3afa573dd3bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/26d9fff083084577b20677a382f75cfcfc6fe82e/msteams-platform%2Fsbs-gs-spfx.yml) | 94 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6ca4062-5777-4796-aa7b-446ee8e7ea00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/26d9fff083084577b20677a382f75cfcfc6fe82e/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/520cd05e-760a-4e66-bb52-769a7694ef8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/26d9fff083084577b20677a382f75cfcfc6fe82e/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f751c3b3-9441-433a-ace5-2af8c77a591b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/26d9fff083084577b20677a382f75cfcfc6fe82e/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aad84d3a-5c7f-4f3e-8efc-3c1158b117db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/26d9fff083084577b20677a382f75cfcfc6fe82e/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 85 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c098cab-ef2a-4b4a-a804-b564ff68debd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/26d9fff083084577b20677a382f75cfcfc6fe82e/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f727670e-d84a-42e6-9c6b-c2ec1aa4e46a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c502e5d6a9ce067075cae380021b5db3137c90e8/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b27c5039-f598-4cbe-811c-143babbcc2bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c502e5d6a9ce067075cae380021b5db3137c90e8/msteams-platform%2Fsbs-gs-spfx.yml) | 94 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34eba14d-fd1b-4662-be97-44fd699e3b9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c502e5d6a9ce067075cae380021b5db3137c90e8/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f85dae4-582b-41f1-a266-79af355ca5b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c502e5d6a9ce067075cae380021b5db3137c90e8/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/056bb36d-ccd5-4dde-a062-d39d752d1d2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c502e5d6a9ce067075cae380021b5db3137c90e8/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/babc4394-2b78-4007-a058-362facdd238b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c502e5d6a9ce067075cae380021b5db3137c90e8/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 85 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/667b2264-526c-40ca-bce8-2e468fc3eec4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c502e5d6a9ce067075cae380021b5db3137c90e8/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab9ea98a-01db-4f39-8c5b-377be4af61ef) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/efbaaa21deae6a17e2ba5477f6580926ca32192b/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a8e9057-50d9-417a-a070-5ab2af530d35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/efbaaa21deae6a17e2ba5477f6580926ca32192b/msteams-platform%2Fsbs-gs-spfx.yml) | 94 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef460fa6-74f1-42da-a9ce-b3541abe0183) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/AAD-manifest-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efbaaa21deae6a17e2ba5477f6580926ca32192b/msteams-platform%2Ftoolkit%2FAAD-manifest-customization.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/412225b7-6d91-4338-abc7-966e938f42f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efbaaa21deae6a17e2ba5477f6580926ca32192b/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ec23065-2963-4b83-a502-69d506d8de44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efbaaa21deae6a17e2ba5477f6580926ca32192b/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0065ed5a-e9f9-48b5-8803-5b5eb65cba0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efbaaa21deae6a17e2ba5477f6580926ca32192b/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 85 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/837ac945-9a41-427e-abbb-336f3e67e7d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efbaaa21deae6a17e2ba5477f6580926ca32192b/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2320b715-7866-423c-a600-fafa315c1724) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-shalinirobinson — APPROVED** [review]
Approved.

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
