### PR TITLE
[Doc Improvement][SEO description update 14][3915820]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f77d11e36c6d8481f30e976d7f33397c313204f/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03f01c27-5beb-4573-bd70-0ae91f072611) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f77d11e36c6d8481f30e976d7f33397c313204f/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1052f523-1291-421b-9e0d-4b80a8aead68) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f77d11e36c6d8481f30e976d7f33397c313204f/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94eb7ce8-218e-403f-9f21-538bbdb30338) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/App-permissions/Teams-app-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f77d11e36c6d8481f30e976d7f33397c313204f/msteams-platform%2Fgraph-api%2FApp-permissions%2FTeams-app-permissions.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c583599-3f88-4bca-b89c-d8f259b699fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f77d11e36c6d8481f30e976d7f33397c313204f/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 86 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e34bb09-bea4-4325-87a9-625ad4d9172a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/api-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f77d11e36c6d8481f30e976d7f33397c313204f/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Fapi-transcripts.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/887e0130-844c-4367-b9fc-853ff0a436e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f77d11e36c6d8481f30e976d7f33397c313204f/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93327109-5e0a-4264-aff4-d7ca75e893fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f77d11e36c6d8481f30e976d7f33397c313204f/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/364d4a6b-8d5e-42f1-8572-e28779c206aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-chat-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f77d11e36c6d8481f30e976d7f33397c313204f/msteams-platform%2Fgraph-api%2Frsc%2Ftest-chat-rsc-json-file.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a96fe06-b32b-416c-b35a-3363847e61bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f77d11e36c6d8481f30e976d7f33397c313204f/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1cd74873-71df-4fa7-aef5-afa8d100e3e2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e370802d5af70b7b81f909bc74f38cf573cdbf1/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21f708e2-7cb8-4513-a0e2-1c2dc8b7a892) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e370802d5af70b7b81f909bc74f38cf573cdbf1/msteams-platform%2Fget-started%2Fglossary.md) | 90 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1ac28a1-5228-4b17-8c6f-6b09bd53a0fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e370802d5af70b7b81f909bc74f38cf573cdbf1/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbdb03ac-71c2-4930-aeaf-a6ed92a9ebf4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/App-permissions/Teams-app-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e370802d5af70b7b81f909bc74f38cf573cdbf1/msteams-platform%2Fgraph-api%2FApp-permissions%2FTeams-app-permissions.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19d5fa60-f10d-4fb1-aa85-00349547c8fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e370802d5af70b7b81f909bc74f38cf573cdbf1/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 86 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28187eb5-2d94-4557-93ae-2a0ae7e86119) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/api-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e370802d5af70b7b81f909bc74f38cf573cdbf1/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Fapi-transcripts.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d63f2b3f-bd6a-47df-b397-9d9007fda979) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e370802d5af70b7b81f909bc74f38cf573cdbf1/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/478300bc-87de-4131-8974-06df1131d5a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e370802d5af70b7b81f909bc74f38cf573cdbf1/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d8b4320-3c95-4b4f-b54a-56b5a30ff506) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-chat-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e370802d5af70b7b81f909bc74f38cf573cdbf1/msteams-platform%2Fgraph-api%2Frsc%2Ftest-chat-rsc-json-file.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21a6d3aa-00ee-41d5-8940-5387957a9037) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e370802d5af70b7b81f909bc74f38cf573cdbf1/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf0ef331-9505-43fd-a895-aca80eeebbd0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aed0c2ac6c6dd19c235d2b6c16512ea4e1cf8a48/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9dcd1014-1105-4cea-bed1-757625765d79) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aed0c2ac6c6dd19c235d2b6c16512ea4e1cf8a48/msteams-platform%2Fget-started%2Fglossary.md) | 89 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e210e91a-07c0-402b-bd98-316cc5d52190) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aed0c2ac6c6dd19c235d2b6c16512ea4e1cf8a48/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/910dc8de-a73a-4aaf-87ee-b0c6e864b22d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/App-permissions/Teams-app-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aed0c2ac6c6dd19c235d2b6c16512ea4e1cf8a48/msteams-platform%2Fgraph-api%2FApp-permissions%2FTeams-app-permissions.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/216a1bc3-d283-443f-a7b2-a5082fba2ecb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aed0c2ac6c6dd19c235d2b6c16512ea4e1cf8a48/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 86 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c03d65a-5e87-4137-973b-c10bd35dc20d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/api-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aed0c2ac6c6dd19c235d2b6c16512ea4e1cf8a48/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Fapi-transcripts.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bb0b0f2-31b6-4eb3-a4a4-564bc9d27fd1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aed0c2ac6c6dd19c235d2b6c16512ea4e1cf8a48/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29f4cad0-828c-43b1-a74e-c97cdfa1fbbc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aed0c2ac6c6dd19c235d2b6c16512ea4e1cf8a48/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/564d56a6-e9a3-4074-97ea-711dbc004cbc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-chat-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aed0c2ac6c6dd19c235d2b6c16512ea4e1cf8a48/msteams-platform%2Fgraph-api%2Frsc%2Ftest-chat-rsc-json-file.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6269249-bab8-48a0-98bc-782066889f66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aed0c2ac6c6dd19c235d2b6c16512ea4e1cf8a48/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f24d853e-7eb7-41a2-90b7-de34304aacfa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58eeb6abc13c05472e16f786d4cb78bde4bcf66e/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b494c4a-3403-4c80-9c7c-a6ef1a3a4b52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58eeb6abc13c05472e16f786d4cb78bde4bcf66e/msteams-platform%2Fget-started%2Fglossary.md) | 89 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60fdb508-4a84-4c08-b7f5-22fec97cd295) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58eeb6abc13c05472e16f786d4cb78bde4bcf66e/msteams-platform%2Fget-started%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e3121ec-2a52-410b-91be-5c878a53b094) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/App-permissions/Teams-app-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58eeb6abc13c05472e16f786d4cb78bde4bcf66e/msteams-platform%2Fgraph-api%2FApp-permissions%2FTeams-app-permissions.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0826f18b-e469-4421-b73d-83c8da9d3735) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/import-messages/import-external-messages-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58eeb6abc13c05472e16f786d4cb78bde4bcf66e/msteams-platform%2Fgraph-api%2Fimport-messages%2Fimport-external-messages-to-teams.md) | 86 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e079a4c7-570a-44a5-9180-4b8e5479c2fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/api-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58eeb6abc13c05472e16f786d4cb78bde4bcf66e/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Fapi-transcripts.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae7add34-51eb-4d29-a2a2-b092e50b5107) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58eeb6abc13c05472e16f786d4cb78bde4bcf66e/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c64c226-9a56-4585-952a-ee9c16c1a342) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58eeb6abc13c05472e16f786d4cb78bde4bcf66e/msteams-platform%2Fgraph-api%2Frsc%2Fresource-specific-consent.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a66c6950-95e2-4c2a-ae28-bed016a3ceae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-chat-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58eeb6abc13c05472e16f786d4cb78bde4bcf66e/msteams-platform%2Fgraph-api%2Frsc%2Ftest-chat-rsc-json-file.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3334dff3-d58f-44a6-801f-d8a1ace7a225) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58eeb6abc13c05472e16f786d4cb78bde4bcf66e/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a61e1897-372e-4844-a788-847953db969d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
