### PR TITLE
Fixed the incorrect html meta attributes

### PR DESCRIPTION
**Pull request by tony-xia**

### CODE REVIEW

**Comment by clearab** [comment]
Hi - I'm unable to determine if there is a standard in using 'property' or 'title' here - it seems both ways are generally acceptable. If you are aware of a standard for preferring one or the other, could you please point me towards it?

**Comment by tony-xia** [comment]
I guess we are talking about two questions:
1. My fix is for the attribute name. Normal attribute name for meta tag is `name`, only OpenGraph uses `property`.
2. Your concern is that we should use meta tag for title, or use just `<title>`. I think it depends on how Teams backend parses the page and extracts the title information.
please feel free to correct me if i got any misunderstanding. thanks

**Comment by clearab** [comment]
This file was moved with a recent merge.

**Comment by clearab** [comment]
Significant merge conflicts with this PR - moving the change to a new PR.

**Pull request closed without merging**
