### PR TITLE
[UpdateIndex.yml]

### PR DESCRIPTION
**Pull request by KirtiPereira**

### CODE REVIEW

**Review by sathya-raveendran — CHANGES_REQUESTED** [review]
Can we have the extensibility lookbook description modified per below - 

In order to serve as an inspiration for building apps on Teams platform, understanding the art of possible with various platform capabilities, Microsoft offers Teams Extensibility look book. The extensibility look book is a scenario library of Teams apps by industry.



Each scenario in this library is accompanied by a set of high-fidelity design mocks of concept apps to serve as inspiration for design and user experience. In addition, the look book highlights the design and architecture best practices followed in building each app.


For more information, see [extensibility look book](https://adoption.microsoft.com/extensibility-look-book/scenarios/)

**Comment by KirtiPereira** [comment]
@sathya-raveendran - please let us know if this works. Have modified your inputs, as we need to follow the MSTP guidelines.

Microsoft offers an extensibility look book, a scenarios library for Teams apps organized by industry. This book helps you build apps on Teams platform and understand different scenarios that are possible using the various Teams platform capabilities. It describes a business scenario, personas that contribute to it, and their challenges.

Each scenario in this library is accompanied by a set of high-fidelity design concept mocks, which can serve as an inspiration for designing your apps and enhancing user experience. In addition, the look book highlights the design and architecture best practices followed in building each app. For more information, see the extensibility look book.

**Review by sathya-raveendran — DISMISSED** [review]
Looks good to me

**Review by surbhigupta12 — APPROVED** [review]
Approving the PR

**Pull request merged**
