### PR TITLE
[Doc Feature][Suggested prompts][3754208]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ddf691828016d22f96a284162b3aa1165318abd/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 87 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/589b44e5-3158-4df9-b493-0e0f465aaf5f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-get-started.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b541e2d40b91b0e81ba17466b466b122ada6c8ad/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-get-started.md) | 89 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbf598f5-fff2-4f22-b7ad-0da50bb1a82b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b541e2d40b91b0e81ba17466b466b122ada6c8ad/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 86 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7158b69-4fd3-46ec-9c37-51b18e647349) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-get-started.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7e1b4f22b7141480c4296ae8cdddcb52ecc15fa/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-get-started.md) | 89 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22c53fc5-8cd6-4e50-afa1-0197da8e6639) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c7e1b4f22b7141480c4296ae8cdddcb52ecc15fa/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 87 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4083747f-35a8-46af-b84a-dd23218df7eb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-get-started.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2978aca8d17b5ca69dc032107cf6fdbf9866d56/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-get-started.md) | 89 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1652b8e9-55df-4cb4-9dde-5daf6bbdf601) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2978aca8d17b5ca69dc032107cf6fdbf9866d56/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/111f520b-598e-4e38-be9f-584c2214738e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-get-started.md](https://github.com/MicrosoftDocs/msteams-docs/blob/292a13cdf4b6a5d9a7319d93cf9df17eb1857c9c/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-get-started.md) | 89 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ecdfd25-c853-4a9b-9d1a-2b827b9752a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/292a13cdf4b6a5d9a7319d93cf9df17eb1857c9c/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cda169e-818f-4468-a1f0-c0a41c51bc10) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-get-started.md](https://github.com/MicrosoftDocs/msteams-docs/blob/410c18eebefd42d09f0f4a9c18a2123c2f5d3b43/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-get-started.md) | 89 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb17729d-c50e-4fa0-bf6b-f9077d6da783) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/410c18eebefd42d09f0f4a9c18a2123c2f5d3b43/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 86 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/888fd52b-a23f-485d-b472-eb0e10c46e36) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-get-started.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9dcdf5bf42c78de7752b53e7f3d4ff1e75df4f59/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-get-started.md) | 89 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10478b5b-77ee-49cf-90e2-16edeab2583a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9dcdf5bf42c78de7752b53e7f3d4ff1e75df4f59/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 84 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40c6a1c9-0f8c-47e0-8e0a-e46a92561c84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9dcdf5bf42c78de7752b53e7f3d4ff1e75df4f59/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 86 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/468bd330-bd3a-4c42-b1fe-7c17f9f9eced) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-get-started.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ed1bfa736ce4b8cc8d983866467ab820e29cdde/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-get-started.md) | 89 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a8f874b-2133-466b-b4fa-dc04fe2bfeb7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ed1bfa736ce4b8cc8d983866467ab820e29cdde/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 84 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b1dbcab-df35-45f8-ad9c-0425bff2c895) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ed1bfa736ce4b8cc8d983866467ab820e29cdde/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 86 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27621486-1d80-48f9-aed5-d37df8e47073) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-get-started.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17ba140edb7efbe240001a8d3e4331de52563c8a/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-get-started.md) | 89 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10e3ee5c-042c-403c-8069-9aae9ac50179) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17ba140edb7efbe240001a8d3e4331de52563c8a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 84 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4d64285-2c59-4fbb-b4ef-c53ac193bf05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/17ba140edb7efbe240001a8d3e4331de52563c8a/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 86 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71a9d191-bcd1-4c80-ac0e-299a05f35a71) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-get-started.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c09b3a7f8f121f7a3c7210235341d015acb14e09/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-get-started.md) | 89 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77a3e58d-6939-4e0d-953d-ea34fdf60623) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c09b3a7f8f121f7a3c7210235341d015acb14e09/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 84 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/767ca33a-69d3-4f02-941f-63031bee4e5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c09b3a7f8f121f7a3c7210235341d015acb14e09/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 87 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e9bbe15-bbd0-4027-ab56-9fe9986570e8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/939a37cf8c01ec9698ce4050dbc55c71143f7c69/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 84 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9cbf937c-a971-48f2-97fc-379d322479f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/939a37cf8c01ec9698ce4050dbc55c71143f7c69/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 87 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb13cb4b-92b9-488a-8e4a-287bb74c9a61) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d83404a8cf4488049ec060e46d397cf79bb5909a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 84 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b0fc87b-f003-47d5-b27c-161363d6aa49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d83404a8cf4488049ec060e46d397cf79bb5909a/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e6262de-6e5d-4b43-acc2-69ffae27140a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-npaladugu** [comment]
Closed this PR as this is a duplicate of PR 10866

**Pull request closed without merging**
