### PR TITLE
Border param not required separately for images and icons

### PR DESCRIPTION
**Pull request by ashishguptaiitb**

### CODE REVIEW

**Comment by v-habibaumme** [comment]
@ashishguptaiitb,

We'll check and fix them accordingly.

**Review by v-habibaumme — APPROVED** [review]
Approved

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9c86be0-aad8-4582-b6b2-6b452ada2fd1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac83b9b8-a78c-4aae-9620-0e02aaf21a9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d4134c7-cb4e-480b-988f-681df69d08ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fauthentication%2Fauthentication.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b50f55f-9aac-4ca3-9e73-e57272aafbec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/524225c2-6718-4734-8ebd-e7c22baeea0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a31b2fb9-489d-4d7b-a358-06c3fabc449f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa72b74f-e0f9-4fad-8ab2-99975c6142f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06fc66fd-8069-45ee-ae83-64639df2f3c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/activity-feed-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fdesign%2Factivity-feed-notifications.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67a8c3c6-710c-4ca8-9cc5-bbd3c363f8ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/app-structure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fdesign%2Fapp-structure.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8c5a132-0748-40b1-84b5-4af7a6272ee0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-advanced-ui-components.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0494040-3319-4361-9a02-adca166accf6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-basic-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-basic-ui-components.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1124a0d-9c42-41e1-87fe-16e99fd19f10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-fundamentals.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f1b4d73-9cd9-402f-8cf1-d71a6bc0ae53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-process.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87383bca-8330-42e3-ab68-a76254dae12b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-ui-templates.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb24ffa8-cd08-4da9-9d8d-2618ef29afd1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57ccbc14-608f-4251-a314-bedaf35becdb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/plan-to-monetize.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fdesign%2Fplan-to-monetize.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f15de838-d35c-4aac-833a-d1635269a661) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fconcepts%2Fdesign%2Funderstand-use-cases.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ecd33b2-e3a9-4d3a-80b7-622c578b2528) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/feedback.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Ffeedback.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a273b05-d600-452d-af28-3636e8ab6170) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/deploy-csharp-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fget-started%2Fdeploy-csharp-app-studio.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10571bcb-c72d-4012-9976-28bff486fbf7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/095fc68b-fe40-4b25-9eeb-4cccc5bfc29f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98a14836-0245-4d1b-948b-8e1d1a136f85) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 88 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26eb9dbc-eac8-4e4e-8cfa-79b98af6b7e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Foverview-explore.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dda1b60a-6466-4dc3-aac5-a2f4487948ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Foverview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4012f82c-7f00-405c-9c4f-a8ed78d84d7b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-story.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Foverview-story.md) | 85 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1d61921-c7b7-4c75-baaf-9d483ce6df01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Foverview.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ddf4a7a-07be-45e8-8cdd-8560b53ddc10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/removing-tab-margins.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fresources%2Fremoving-tab-margins.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4380123b-a4de-4b9b-923c-44d9a1a96981) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 95 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8286f84a-46b2-4bbb-a463-0f83d589b8d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e06fdb1f01d3907e80c1cbd2400f6461267671e6/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60ae6826-03d3-4a9f-9200-f951a197089d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Pull request merged**
