### PR TITLE
[Doc Improvement][Multitenant Term Corrections][3553328]

### PR DESCRIPTION
**Pull request by v-kushals**
- Updated incorrect usage of **multitenant**.
- Fixed the Acrolink score wherever necessary.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c81f5cf003f40639309e445890da53f810ecae6/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 89 | 89 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/909ddc9e-0919-4154-8dd6-fa5f8a894595) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c81f5cf003f40639309e445890da53f810ecae6/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75b5cb09-2140-4daf-94fc-4bb55aa2b1f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c81f5cf003f40639309e445890da53f810ecae6/msteams-platform%2Fget-started%2Fglossary.md) | 93 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54dcad73-dd03-43ea-b78a-f0ab8da0410b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c81f5cf003f40639309e445890da53f810ecae6/msteams-platform%2Fm365-apps%2Fpublish.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c7632f4-39b6-42e7-9970-a11a91b75097) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/enable-sso-for-your-adaptive-cards-universal-action.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c81f5cf003f40639309e445890da53f810ecae6/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fenable-sso-for-your-adaptive-cards-universal-action.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/424798c7-1c96-4d49-a0f0-e623f46d3620) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c81f5cf003f40639309e445890da53f810ecae6/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff3cb3dc-208e-4b49-b2e6-da00398d6f95) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c81f5cf003f40639309e445890da53f810ecae6/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 90 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97461810-874a-4a84-8f1e-153c6bcc713d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbf12dbce19d788c45470501fc569292b26482bb/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59d2d110-4a9c-4f2b-aa37-c18f6e6604a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbf12dbce19d788c45470501fc569292b26482bb/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c135f0d7-5f7a-4337-8b0c-07e12063e9a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbf12dbce19d788c45470501fc569292b26482bb/msteams-platform%2Fget-started%2Fglossary.md) | 93 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc86f7f6-957a-4b07-adce-e80d3c555ba2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbf12dbce19d788c45470501fc569292b26482bb/msteams-platform%2Fm365-apps%2Fpublish.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c467982-8fc9-479f-a779-d416ffc14cae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/enable-sso-for-your-adaptive-cards-universal-action.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbf12dbce19d788c45470501fc569292b26482bb/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fenable-sso-for-your-adaptive-cards-universal-action.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24b8b3da-0910-4d36-9cf3-631c34cb93ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbf12dbce19d788c45470501fc569292b26482bb/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b335239-94f8-4f2e-b7ea-1ce7f5717e7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbf12dbce19d788c45470501fc569292b26482bb/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 90 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/017b321e-ef27-40bb-8f96-81817ab4ec91) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5fa4cf64eb7465428fccb97604a58799d181b3e8/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb874067-8c36-435f-bd88-12582d16598d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5fa4cf64eb7465428fccb97604a58799d181b3e8/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/874f53cc-4c5a-40a4-8541-af157568adda) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5fa4cf64eb7465428fccb97604a58799d181b3e8/msteams-platform%2Fget-started%2Fglossary.md) | 93 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c8ce285-6b80-4bfd-88a1-80478b678f41) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5fa4cf64eb7465428fccb97604a58799d181b3e8/msteams-platform%2Fm365-apps%2Fpublish.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aba1a82f-a902-48bc-9148-5ab36e091256) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/enable-sso-for-your-adaptive-cards-universal-action.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5fa4cf64eb7465428fccb97604a58799d181b3e8/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fenable-sso-for-your-adaptive-cards-universal-action.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f811c3a0-d082-4918-8712-3942b0b63431) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5fa4cf64eb7465428fccb97604a58799d181b3e8/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92de32be-ac1a-47e9-bfb5-e94d0648ee04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5fa4cf64eb7465428fccb97604a58799d181b3e8/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 90 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/668ebbca-cd30-4446-ad4a-99f3e99b72d7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e49f4e47a532010bb0b9e3feaf301776d4bf05/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 81 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/438c02ce-efd3-4da1-afd1-c99acb9f2d48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e49f4e47a532010bb0b9e3feaf301776d4bf05/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d8d7499-73f6-49ef-8f9f-8e0dbea464b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e49f4e47a532010bb0b9e3feaf301776d4bf05/msteams-platform%2Fget-started%2Fglossary.md) | 93 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0642ecc6-a990-47de-aa08-91006e24b2e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e49f4e47a532010bb0b9e3feaf301776d4bf05/msteams-platform%2Fm365-apps%2Fpublish.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8a21bb8-1875-49ff-8b88-5f62f0c306a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/enable-sso-for-your-adaptive-cards-universal-action.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e49f4e47a532010bb0b9e3feaf301776d4bf05/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fenable-sso-for-your-adaptive-cards-universal-action.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a361b545-d83a-407f-a40d-ec23adb4a326) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e49f4e47a532010bb0b9e3feaf301776d4bf05/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a1bc534-848a-4b52-a341-eed1a5da52db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e49f4e47a532010bb0b9e3feaf301776d4bf05/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 90 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62889f81-d35a-4622-bdce-2b000aaccceb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71fada108e3d3e8511124c078e9a205e5236b433/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 93 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7b78d45-4315-4b24-afda-f3d2735af51d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/bot-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71fada108e3d3e8511124c078e9a205e5236b433/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-overview.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd67deaa-7b9d-461b-81e7-4b53f0a2b340) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71fada108e3d3e8511124c078e9a205e5236b433/msteams-platform%2Fget-started%2Fglossary.md) | 92 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1bf03b68-b15e-4200-b575-acbb448aebd7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71fada108e3d3e8511124c078e9a205e5236b433/msteams-platform%2Fm365-apps%2Fpublish.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e387d63e-4ff6-4c2d-9c90-74beb6670c55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/Universal-actions-for-adaptive-cards/enable-sso-for-your-adaptive-cards-universal-action.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71fada108e3d3e8511124c078e9a205e5236b433/msteams-platform%2Ftask-modules-and-cards%2Fcards%2FUniversal-actions-for-adaptive-cards%2Fenable-sso-for-your-adaptive-cards-universal-action.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d4c177e-39c5-4c40-a858-564f94618513) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71fada108e3d3e8511124c078e9a205e5236b433/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04b8bcd5-55e0-49ab-a404-523136b0eb29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71fada108e3d3e8511124c078e9a205e5236b433/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 90 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d92e8be0-c76c-42ef-a7d6-b07c52f5ed69) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
