### PR TITLE
[Doc Improvement][Tasks to dialogs for Test app][3457834]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c0041d66337fd5270f60911c8fae4a7ea8fb4d09/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b4b83a8-5a86-42f9-8dc5-347e5a6f183c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c649444abb85cdcc323c244ec21814951dcdabbd/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc4d953c-7fb0-48af-bb0d-79b50fe573b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c649444abb85cdcc323c244ec21814951dcdabbd/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b465c48b-cace-473d-b089-1fa47104dc4f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80f4c59cb4319b2d2e0f75e6d7f18b18836bf909/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75331921-968d-4b7d-9ed8-c0ecdf1ad47e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80f4c59cb4319b2d2e0f75e6d7f18b18836bf909/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f89c1ba-1a9e-4aea-971d-239c4470927c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80f4c59cb4319b2d2e0f75e6d7f18b18836bf909/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-overview.md) | 91 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64a59763-c6c5-4841-bfd9-de96b12e779b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by erikadoyle — CHANGES_REQUESTED** [review]
Looks good, but could we update "TeamsJS v.1.0" to "TeamsJS v1.x" to generalize across all minor versions?

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d298e433fff0472b7c9d9eb996ccb7fe9ddae263/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb26beb1-d062-4905-a426-18828fd01c54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d298e433fff0472b7c9d9eb996ccb7fe9ddae263/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a546a4d6-1dd9-4a37-bc21-9d32ca205631) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d298e433fff0472b7c9d9eb996ccb7fe9ddae263/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-overview.md) | 91 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3190c74e-dd97-4dd6-9ca4-d36243fefccf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d812d08d259fe0157939e805f70caf092e754d45/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9773a35-6a1d-400c-90ed-bd6d9fc43950) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d812d08d259fe0157939e805f70caf092e754d45/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8b21078-d9e3-46cc-95fb-579f9c80a040) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d812d08d259fe0157939e805f70caf092e754d45/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-overview.md) | 91 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85300996-cfae-437d-a356-0fb45ea9b079) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
