### PR TITLE
[Doc Update][Message-extension-3][2369901]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/bots/teams-bot-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c3ac5c021c7a3b40612ca86dc2e7d8ad1b7c1ebf/msteams-platform%2Fincludes%2Fbots%2Fteams-bot-samples.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3124e02-9f5e-46b8-a419-c13d67460b17) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/bots/teams-bot-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d07c66078278aa42fa5d2cb8716a0fba9ab3379c/msteams-platform%2Fincludes%2Fbots%2Fteams-bot-samples.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1a492ce-a8ab-42c1-874d-51d6f9dd661e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d07c66078278aa42fa5d2cb8716a0fba9ab3379c/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ccba5ac-41ef-4e8e-aa95-ec97eb3767a2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/bots/teams-bot-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25164f9177fc8260c811f40233b85b07744aa329/msteams-platform%2Fincludes%2Fbots%2Fteams-bot-samples.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d84fb747-e61a-44ae-8076-dea64880a3db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/25164f9177fc8260c811f40233b85b07744aa329/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f54189ca-d2c8-4602-9c05-552fe47160ed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/bots/teams-bot-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/13d13e328f873e25f6c540559b42dca7faeb7522/msteams-platform%2Fincludes%2Fbots%2Fteams-bot-samples.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b527e5ce-471c-4a5e-b7c1-b610dfe83521) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/v4-to-v3-pointer-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/13d13e328f873e25f6c540559b42dca7faeb7522/msteams-platform%2Fincludes%2Fv4-to-v3-pointer-me.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0dc6277-dd9d-4cf1-89a0-9fe7f8b83752) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/13d13e328f873e25f6c540559b42dca7faeb7522/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ddc2ba8-8e00-452f-a4c3-5384c20028a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/13d13e328f873e25f6c540559b42dca7faeb7522/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35a3b867-f292-4d21-b136-9ae112502d8c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/bots/teams-bot-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/adf543b0ae835a27ea650902056c0ae85c174fab/msteams-platform%2Fincludes%2Fbots%2Fteams-bot-samples.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25f6521d-e680-422c-98f6-ec7f089d37c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/v4-to-v3-pointer-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/adf543b0ae835a27ea650902056c0ae85c174fab/msteams-platform%2Fincludes%2Fv4-to-v3-pointer-me.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/387a3aa7-b0de-49d9-b092-128bf5746eeb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/adf543b0ae835a27ea650902056c0ae85c174fab/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fcreate-task-module.md) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d6d9892-06d0-45f1-b877-d14185dcc04a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/adf543b0ae835a27ea650902056c0ae85c174fab/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30d8356d-176d-4b7a-96f0-fa71b0b8a61b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/adf543b0ae835a27ea650902056c0ae85c174fab/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a4e232d-5488-49f7-8a95-635db1fe2031) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/bots/teams-bot-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f3965fc0273c67d5cfa6e2b644ff0995949e0d/msteams-platform%2Fincludes%2Fbots%2Fteams-bot-samples.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aad13df5-8149-4b19-af59-12efd32fe971) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/v4-to-v3-pointer-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f3965fc0273c67d5cfa6e2b644ff0995949e0d/msteams-platform%2Fincludes%2Fv4-to-v3-pointer-me.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/714d1ba8-f5a0-451a-8b28-9cfde3284f94) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f3965fc0273c67d5cfa6e2b644ff0995949e0d/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fcreate-task-module.md) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ceb7ce5f-c9d3-4c93-97c5-3605bf30b532) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f3965fc0273c67d5cfa6e2b644ff0995949e0d/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1b007a9-460c-4345-ad45-b35597800fac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f3965fc0273c67d5cfa6e2b644ff0995949e0d/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 88 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ac71c55-a00d-4767-96cc-f7ea4371386c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14f3965fc0273c67d5cfa6e2b644ff0995949e0d/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae229b84-6f12-4371-a959-cf83802fa32b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/bots/teams-bot-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa4df1db4a7e9314c147a53d04377cc4c07615e/msteams-platform%2Fincludes%2Fbots%2Fteams-bot-samples.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9c8a3f4-81db-4c81-a701-ae2d750f5c69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/v4-to-v3-pointer-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa4df1db4a7e9314c147a53d04377cc4c07615e/msteams-platform%2Fincludes%2Fv4-to-v3-pointer-me.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a66b8680-e1f6-4dd5-91dd-f58b8eabec03) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa4df1db4a7e9314c147a53d04377cc4c07615e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fcreate-task-module.md) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96f7f910-94af-446e-b60f-c3462c85bc9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa4df1db4a7e9314c147a53d04377cc4c07615e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2858d35a-8c18-4bb5-8f3a-033832f54ca2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa4df1db4a7e9314c147a53d04377cc4c07615e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 88 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b1fd655-8055-4c78-b679-805c8945cfa5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa4df1db4a7e9314c147a53d04377cc4c07615e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc93da2e-2b52-43a9-94e5-b5b7a82eff84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aa4df1db4a7e9314c147a53d04377cc4c07615e/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65c4e330-4392-4147-9b57-6821a263f6a3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/bots/teams-bot-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c9e4c2f214f79db163fb6265af42268794de88b/msteams-platform%2Fincludes%2Fbots%2Fteams-bot-samples.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa39e6ea-20df-41f7-bcb8-35db44729417) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/v4-to-v3-pointer-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c9e4c2f214f79db163fb6265af42268794de88b/msteams-platform%2Fincludes%2Fv4-to-v3-pointer-me.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98175cfa-0d0b-4884-952b-957f23a9180d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c9e4c2f214f79db163fb6265af42268794de88b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fcreate-task-module.md) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/542a61ed-cf90-4ab4-a03b-58b856ffe4ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c9e4c2f214f79db163fb6265af42268794de88b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b203531-3a94-48eb-af7b-d117cb5e6261) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c9e4c2f214f79db163fb6265af42268794de88b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 88 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f46099c-f7dd-4328-92f2-3a5cdba97163) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c9e4c2f214f79db163fb6265af42268794de88b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb2066d7-7f80-4f49-85ff-1378b8dc2216) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c9e4c2f214f79db163fb6265af42268794de88b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d06e119-f329-4b13-b88b-91f5d4a40c5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1c9e4c2f214f79db163fb6265af42268794de88b/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/213cd265-35b2-440b-ad0e-8c7714958e81) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9db805b9f418f3a953e50e83ae2b49b4131b9325/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fda115e4-d61e-426d-b615-60e4905bb0ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/bots/teams-bot-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9db805b9f418f3a953e50e83ae2b49b4131b9325/msteams-platform%2Fincludes%2Fbots%2Fteams-bot-samples.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3b19f6b-2797-4e93-85c6-a493c43ff25c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/v4-to-v3-pointer-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9db805b9f418f3a953e50e83ae2b49b4131b9325/msteams-platform%2Fincludes%2Fv4-to-v3-pointer-me.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e2acbf7-1911-4167-804a-3e0a285eae92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9db805b9f418f3a953e50e83ae2b49b4131b9325/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fcreate-task-module.md) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/455897e8-20db-49de-b571-8ba78b4c391c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9db805b9f418f3a953e50e83ae2b49b4131b9325/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 89 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b294831-8139-46ca-8caa-1d78150fbbcb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9db805b9f418f3a953e50e83ae2b49b4131b9325/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 88 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53e5957a-c5a1-49da-9eee-8016ab6e10ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9db805b9f418f3a953e50e83ae2b49b4131b9325/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d65a6656-fad2-492f-83c0-6b20b9be0567) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9db805b9f418f3a953e50e83ae2b49b4131b9325/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db0580cc-5157-4edd-a367-1468232711ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9db805b9f418f3a953e50e83ae2b49b4131b9325/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c51b2d5c-b178-4f14-ab7d-0d0a3b060b6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9db805b9f418f3a953e50e83ae2b49b4131b9325/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd2e614c-213b-4a0b-93b5-23df1a2299b7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by stkong-sdk — APPROVED** [review]

**Review by v-habibaumme — APPROVED** [review]
Approved

**Pull request merged**
