### PR TITLE
[Doc improvement][Images updated][3970730]

### PR DESCRIPTION
**Pull request by v-shalinir**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e37746979de812f58ac9a62f0cf32ab60633b1e/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50bd1de4-cab1-4a9d-b2c6-75bdcbbf3f00) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d3dd0fb883bb9eb8701862a836ed47d6d9007a32/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52c6f9f3-15bc-47af-99af-e7468d0d51d3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db0da30a48f6e7349653801383dc7cdead531d65/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac4ab47d-592b-4590-b13a-e5cacb4a7709) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6da6c959822cad15e216691fca812ba8cacb5458/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/191e7fb5-5533-4b50-b94b-dbf1c91af7e8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bcd198f99dc931625ad7b6951c55b19e0425ee82/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/480d817d-2f34-4ffb-9787-178a51312823) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da8e16ae89cf48a25eaa36ee683d5e1160f603f2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db7f9b52-48c0-42d8-b42e-d65e01be0da7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2e892420ed45ee440f5ce7ce5438eb672126437/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1b71e3e-00d2-4f74-904a-0861e86bd25f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2e892420ed45ee440f5ce7ce5438eb672126437/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9164f114-0e51-4bcc-a3e2-ecad7657b40d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71dd5b522ba491e61a0731ce27f06cd0ef03dd17/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f05ab8d-e52c-4fa3-9048-198e375cd8ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/71dd5b522ba491e61a0731ce27f06cd0ef03dd17/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d727f968-7729-4079-a4cd-d4bf6d43fc3b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/13e731774c876dbe4306ca8c7229b3b2d84216ed/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1b40f8c-a536-4889-8890-6f3fc284e38e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/13e731774c876dbe4306ca8c7229b3b2d84216ed/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ba4e469-74c0-496f-bbdb-97b1959ca206) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02e12bbc48ffe4715ae08cf00e270913df0601f4/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f332247-372d-4db4-9804-5c961fc78a9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02e12bbc48ffe4715ae08cf00e270913df0601f4/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d663b9f3-96c8-4925-8e53-6f70190b98d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02e12bbc48ffe4715ae08cf00e270913df0601f4/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2cb4a53e-bdbc-4f46-b82b-78aaeb606aa7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b0bd9b3d7bc0c3be116b1ae4fe822f121ff36cb/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72746d2b-e73b-4c6d-ba28-9a7d143e7a92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b0bd9b3d7bc0c3be116b1ae4fe822f121ff36cb/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61240b78-f27b-4326-a6db-6d9778de645e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b0bd9b3d7bc0c3be116b1ae4fe822f121ff36cb/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4d638a0-15a8-451f-a438-6bef6e52c299) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ed1653b1e08d41623a762630831b53d9a567848/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f30aefca-7dec-4c08-8f19-75f4d5bba9e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ed1653b1e08d41623a762630831b53d9a567848/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4d7ddc5-4686-466e-a1bc-e57452a58313) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ed1653b1e08d41623a762630831b53d9a567848/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec3e651e-056f-4fa8-9263-989f0e3fd33d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4ed1653b1e08d41623a762630831b53d9a567848/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-vs.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba2b9d06-0e11-46b2-9424-9eea9964179d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf34b8e8b6d506f8eef586b09ccf26a53c94ae54/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23a2e7c9-6f16-4918-b4b9-1de31cb79730) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf34b8e8b6d506f8eef586b09ccf26a53c94ae54/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7312fe6c-911a-4b84-83b4-353cac55e77a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf34b8e8b6d506f8eef586b09ccf26a53c94ae54/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6797036-9ed6-4cdd-ab94-590b39fec111) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf34b8e8b6d506f8eef586b09ccf26a53c94ae54/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-vs.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef2ee8cd-b920-410e-9770-cfb3bf73eee0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed270914af1ac2329d091e6f9be4de60420fea94/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1f36847-63cd-461d-bf89-c940d8f0eb22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed270914af1ac2329d091e6f9be4de60420fea94/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01cc9379-afa4-4b7f-b734-74ae04e9905a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed270914af1ac2329d091e6f9be4de60420fea94/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22f8e1db-8caf-4481-9baa-ad501e200956) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed270914af1ac2329d091e6f9be4de60420fea94/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-vs.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/127f8ad8-a6d7-43ac-a463-70640f0b0bfe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebb8ac792044f2a9974d05f935387b2bfdc4df09/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf4d5be5-d6a3-4064-9b98-2173549aff10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebb8ac792044f2a9974d05f935387b2bfdc4df09/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99af2129-d408-43c4-aa7a-2519ef765931) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebb8ac792044f2a9974d05f935387b2bfdc4df09/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f03e189d-529f-4df5-9835-2a996b10d0e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebb8ac792044f2a9974d05f935387b2bfdc4df09/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-vs.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14b432f1-80ca-4b88-8ff9-ef1955408ecc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d73d3613eb5d343eb3b2381964fc53c6da2ff0d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57fe9696-8176-460c-bcec-dacb41d0a181) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d73d3613eb5d343eb3b2381964fc53c6da2ff0d/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/294a2c01-6637-4f29-8142-2444cbe76282) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d73d3613eb5d343eb3b2381964fc53c6da2ff0d/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88681b9e-486f-4f5f-9425-e7c4c648e943) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d73d3613eb5d343eb3b2381964fc53c6da2ff0d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-vs.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f61fa8c9-589c-4bd6-bcb8-1e20fc5ecec1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/monetize-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a10874c6ec21974bff3a63e4634b2d8fca0d1ce7/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmonetize-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4f57b72-b26a-4887-9d3e-5250fc8b2771) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a10874c6ec21974bff3a63e4634b2d8fca0d1ce7/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91785c64-ac85-48d3-b9e3-899413591bb4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a10874c6ec21974bff3a63e4634b2d8fca0d1ce7/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf2d5397-edec-493f-8311-a7613ac1c06f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a10874c6ec21974bff3a63e4634b2d8fca0d1ce7/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-vs.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52507ea1-8a91-4860-93db-32613eafb90b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
