### PR TITLE
[Doc Feature][Bot-based message extension plugin updates][3454019]

### PR DESCRIPTION
**Pull request by v-ypalikila**
minor updates to bot-based message extension

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4d61be5fd0362ee2fa40b168fd690460acca1572/msteams-platform%2Findex.yml) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a84114b-c293-40de-9625-6d1a4723ae26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d61be5fd0362ee2fa40b168fd690460acca1572/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c91cd74-380d-421f-97e1-f4f74bfe7fd1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4d61be5fd0362ee2fa40b168fd690460acca1572/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 84 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e721e84-6f51-44ef-b3b7-7883f84f21bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d61be5fd0362ee2fa40b168fd690460acca1572/msteams-platform%2Fwhats-new.md) | 94 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7215645-a405-494d-ae6e-9a8c4b436203) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0aa020be13805e61fdfaf3b5f642958b0b732257/msteams-platform%2Findex.yml) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48dadc31-728e-4fcf-9489-6edbcc0baf94) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0aa020be13805e61fdfaf3b5f642958b0b732257/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12cd8be8-96e5-4d5f-840f-c729653c606c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/copilot-plugin-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0aa020be13805e61fdfaf3b5f642958b0b732257/msteams-platform%2Fmessaging-extensions%2Fcopilot-plugin-faq.md) | 83 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c39d2a8-9227-4a3d-8337-1acbcb0b826e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0aa020be13805e61fdfaf3b5f642958b0b732257/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b20c7bbb-95ea-45e8-ab91-ce2510a0adec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0aa020be13805e61fdfaf3b5f642958b0b732257/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 84 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/162f6146-0aa1-4459-af48-909d06488072) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0aa020be13805e61fdfaf3b5f642958b0b732257/msteams-platform%2Fteams-faq.md) | 90 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/000a732d-a95c-4dee-b7aa-a419f8cbea51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0aa020be13805e61fdfaf3b5f642958b0b732257/msteams-platform%2Fwhats-new.md) | 94 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8056b2e-d15b-4a96-9d09-6cfbe43dd3e9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7624fcdbb79fe626390352bb875bc8b989399cd5/msteams-platform%2Findex.yml) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6991112c-5f96-4247-a188-e9e774fd6a1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7624fcdbb79fe626390352bb875bc8b989399cd5/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d43cafd4-4658-44b0-83c5-4b16525b2106) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/copilot-plugin-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7624fcdbb79fe626390352bb875bc8b989399cd5/msteams-platform%2Fmessaging-extensions%2Fcopilot-plugin-faq.md) | 83 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f28248f-8e27-42e2-b7e0-03e06ffa2c41) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7624fcdbb79fe626390352bb875bc8b989399cd5/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc38edcc-5bdd-40aa-8efe-e099db26740a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7624fcdbb79fe626390352bb875bc8b989399cd5/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 84 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee719f37-7ea2-4206-b7b1-f677118967c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7624fcdbb79fe626390352bb875bc8b989399cd5/msteams-platform%2Fteams-faq.md) | 89 | 69 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fce0f1bf-9973-4510-9bd2-78fbb7af17cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7624fcdbb79fe626390352bb875bc8b989399cd5/msteams-platform%2Fwhats-new.md) | 94 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce6b9197-74f8-4cec-b27b-834f5ac74360) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e8ad4358b48bb7312f620300482daab2906a7991/msteams-platform%2Findex.yml) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/282c454d-b1ab-475c-83d7-2a0d70272ea6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8ad4358b48bb7312f620300482daab2906a7991/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79e7893e-d92f-4c02-87aa-781456252e3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/copilot-plugin-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8ad4358b48bb7312f620300482daab2906a7991/msteams-platform%2Fmessaging-extensions%2Fcopilot-plugin-faq.md) | 83 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ab67e4f-2d45-49c5-931b-1c09c8741a9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8ad4358b48bb7312f620300482daab2906a7991/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72da8766-ea49-484f-b033-1cbc41fe78b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e8ad4358b48bb7312f620300482daab2906a7991/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 84 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/308abc92-cc2a-48e3-89dc-7adc0c4ad491) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/teams-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8ad4358b48bb7312f620300482daab2906a7991/msteams-platform%2Fteams-faq.md) | 90 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86b33303-06a3-4207-bdad-488afa515d61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8ad4358b48bb7312f620300482daab2906a7991/msteams-platform%2Fwhats-new.md) | 94 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e5e33c1-17cc-479a-ae17-b4140b549baa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
