### PR TITLE
[Tabs][Code-update][1434615]

### PR DESCRIPTION
**Pull request by Rajeshwari-v**
Code correction in line no.70. Please review.

### CODE REVIEW

**Review by KirtiPereira — APPROVED** [review]
@Rajeshwari-v - Approved for merging.

**Review by Nikitha-MSFT — COMMENTED** [review]
Reviewed and approved.

**Review by Nikitha-MSFT — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]
Approving.

**Pull request merged**
