### PR TITLE
[Doc Improvement][Command bot in Teams conceptual doc][2755858]

### PR DESCRIPTION
**Pull request by v-amprasad**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6759b93bcb99b460be3dc714ee036ceb3bc0d677/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37873cf3-c24a-4187-94a2-ccbb60b6b7ff) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c911e6df1f7c27b4bf954b00c89e872a70ffa90/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/660bdcef-7f72-4f9d-8996-ad53ae2e87f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/workflow-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c911e6df1f7c27b4bf954b00c89e872a70ffa90/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fworkflow-bot-in-teams.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0412da01-2a1f-4170-a8be-528ee181fd63) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa2e10589516a3b255bb76917b98db08543ba208/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/212fa465-6504-4d26-bfc6-0dc3636effb2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/workflow-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa2e10589516a3b255bb76917b98db08543ba208/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fworkflow-bot-in-teams.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3fdb151-d538-43f1-afaa-7d7fe92466a7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/36e7e176f048c801ea4997d4c3da5fa74269cfa8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b46b772f-3762-4fff-a579-3ca014733fe1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/workflow-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/36e7e176f048c801ea4997d4c3da5fa74269cfa8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fworkflow-bot-in-teams.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de02b3df-3f0e-49fe-bd5c-3b2b9921a15b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3af090489ea64fa6009d7e4f575b1bb2f495581b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b94d223-3f3d-47f6-af82-33995da2af05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/workflow-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3af090489ea64fa6009d7e4f575b1bb2f495581b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fworkflow-bot-in-teams.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/343f2348-4e5a-4c49-900c-04bb19cbf41a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
