### PR TITLE
Add links to get start in app fundamentals

### PR DESCRIPTION
**Pull request by zyxiaoyuer**
add a link to 'get start' in see also part of app fundamentals pages.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01792583f6ced857d6c35070624eb537385f47ac/msteams-platform/concepts/capabilities-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18c5b07c-54d4-4aab-b02e-c8b0f23c568c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f66854f2f3fad34b5872da42bb5ff28924658d2b/msteams-platform/concepts/capabilities-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5edd3343-7c44-4bbd-981f-0ae684409baa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/extensibility-points.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f66854f2f3fad34b5872da42bb5ff28924658d2b/msteams-platform/concepts/extensibility-points.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd2a92d0-531d-45e2-a2b8-403cb814a253) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed5a3d0289dcbd683b60f704b59bf7ac91834e8e/msteams-platform/concepts/app-fundamentals-overview.md) | 84 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8866f56b-be62-4066-90f1-4b8514cc1193) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed5a3d0289dcbd683b60f704b59bf7ac91834e8e/msteams-platform/concepts/capabilities-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e12acb6c-5d4b-473f-a746-61b3de2a57b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/extensibility-points.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed5a3d0289dcbd683b60f704b59bf7ac91834e8e/msteams-platform/concepts/extensibility-points.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c8cfc41-8cfa-4747-9aeb-c058637c8be5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2abc98a0f15ccbda476a0120a3cc4171b400402/msteams-platform/concepts/app-fundamentals-overview.md) | 84 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7dfe625b-aa2c-400b-b5b5-2c912c39c9bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2abc98a0f15ccbda476a0120a3cc4171b400402/msteams-platform/concepts/capabilities-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eae5fad0-e0bc-42ff-8d09-150c0b2f7cb1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2abc98a0f15ccbda476a0120a3cc4171b400402/msteams-platform/concepts/design/understand-use-cases.md) | 80 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7aa3ec5b-ce96-4dc0-9828-0d86d1fc109e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/extensibility-points.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2abc98a0f15ccbda476a0120a3cc4171b400402/msteams-platform/concepts/extensibility-points.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eaa802ff-5e08-4c31-b628-bca578cad644) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/88686732a294d55a1aae232e489e4396889e243d/msteams-platform/concepts/app-fundamentals-overview.md) | 84 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e42fc12-c2a1-4ecd-93f6-b76dd877409f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/88686732a294d55a1aae232e489e4396889e243d/msteams-platform/concepts/capabilities-overview.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eaeae205-bf0c-4221-91db-4f0ca43c1cbe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/88686732a294d55a1aae232e489e4396889e243d/msteams-platform/concepts/design/map-use-cases.md) | 84 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61cf2a73-a73e-455c-9ec7-cd85551ec5df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/88686732a294d55a1aae232e489e4396889e243d/msteams-platform/concepts/design/understand-use-cases.md) | 80 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91b180b3-10a5-4e72-b999-80b84720d561) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/extensibility-points.md](https://github.com/MicrosoftDocs/msteams-docs/blob/88686732a294d55a1aae232e489e4396889e243d/msteams-platform/concepts/extensibility-points.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08d716e6-d13e-4f10-9b8f-5546580f19ea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]
Approved

**Pull request merged**
