### PR TITLE
[Doc Improvement][Metadata keywords changes-2][2333804]

### PR DESCRIPTION
**Pull request by v-dreddipogu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bad8e000b7d39009c30b51192efd2fe55a81b4c0/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e203f32-f37e-406d-a2d8-22acba7d3489) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bad8e000b7d39009c30b51192efd2fe55a81b4c0/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-fundamentals.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9d6feb1-13e3-433c-bcca-772a6128dbc5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bad8e000b7d39009c30b51192efd2fe55a81b4c0/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-overview.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9cc59170-0545-4ba4-9268-cb2caf10d30e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bad8e000b7d39009c30b51192efd2fe55a81b4c0/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-process.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42319408-9fe5-444a-aba3-1932267fdfd4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bad8e000b7d39009c30b51192efd2fe55a81b4c0/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57331312-4a23-48a0-abc9-68076e85c564) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/plan-responsive-tabs-for-teams-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bad8e000b7d39009c30b51192efd2fe55a81b4c0/msteams-platform%2Fconcepts%2Fdesign%2Fplan-responsive-tabs-for-teams-mobile.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28485588-7fa6-484f-bf64-6f2b28e2b9c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/plan-to-monetize.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bad8e000b7d39009c30b51192efd2fe55a81b4c0/msteams-platform%2Fconcepts%2Fdesign%2Fplan-to-monetize.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2ca9828-0c1b-4459-9057-d2b7d538d2e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/planning-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bad8e000b7d39009c30b51192efd2fe55a81b4c0/msteams-platform%2Fconcepts%2Fdesign%2Fplanning-checklist.md) | 88 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72c1693c-e553-4057-9d72-0294891534bd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7a0b9db-363d-46ef-be93-1082d3787755) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 93 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1156d5b1-ef9d-4a84-9b2e-7da710e7f6ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdec2048-f993-4bcf-9d61-404a2c36c4bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/app-structure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fconcepts%2Fdesign%2Fapp-structure.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c25ebb58-58bf-4755-8bc9-12eeca07a608) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-advanced-ui-components.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/916ce223-3457-41df-bcbe-017227cb5b50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-basic-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-basic-ui-components.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/adbbe53a-8405-4ab5-8296-4446f03d89cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-fundamentals.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/495e9e2d-9326-44ba-a9ad-e601076dcaef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-overview.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7d5021a-6c6d-40f8-830c-7c5522dd6c76) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-process.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d539499-2e60-4523-9f4c-ba4105e7b789) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-ui-templates.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e053d0c0-cefe-417c-be61-fc691a6b1f03) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e29e5abb-34d2-4d14-ad14-b1dc7ade133a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8580752d-7698-4575-a5cc-9d7b361996e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/plan-responsive-tabs-for-teams-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fconcepts%2Fdesign%2Fplan-responsive-tabs-for-teams-mobile.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41d13ed6-4ed0-46f2-941a-c1b23c3f3877) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/plan-to-monetize.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fconcepts%2Fdesign%2Fplan-to-monetize.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/292dfb07-c318-47c4-b068-e7ef2a92c917) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/planning-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fconcepts%2Fdesign%2Fplanning-checklist.md) | 88 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8b5fc5d-0308-4aea-a994-088aaad9ff07) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 90 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21f51380-c091-4d03-8ab5-9975803564cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Ftabs%2Fdesign%2Ftabs.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7483648e-686a-4c1d-bebf-8cecb1b86c2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91553a74ebd2484ca8ddfd2e8ae5cef3337fb1a/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f73465ff-aef2-46fa-a9e6-bc8aef7c3b14) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4c743a7-2676-4807-b961-ae79449fe0bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 93 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8a335a0-72e0-4bd0-801f-b53c61ed45b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89bddad4-0a51-4014-80f7-e44ec2ad8eb7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/activity-feed-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fdesign%2Factivity-feed-notifications.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1835d8e2-509f-444b-83e8-ba0b31070f29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/app-structure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fdesign%2Fapp-structure.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed5090a8-2f65-440f-80f9-1d1fcd1f3121) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-advanced-ui-components.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b253cc2-4083-464f-8633-fa767b54cc8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-basic-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-basic-ui-components.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbeaa4c8-3611-4750-a7e1-ff5921d2a15a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-fundamentals.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f96515e4-520d-4ebc-8ac8-bfdb51aec95e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-overview.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a84e46a9-0585-42a5-aa82-2010d044421c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-process.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e9175c7-9e04-47cf-89b5-57b65cf8e22b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-ui-templates.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00c15ca2-41cf-4110-be2c-4174de921528) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53c3ba4e-4617-4a5e-baf6-27b6c610b93e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4fd517d-e0b9-4598-8adb-8978ef99b13d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c97aed5-d1d2-4dd4-96b8-10a588a49b1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/plan-responsive-tabs-for-teams-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fdesign%2Fplan-responsive-tabs-for-teams-mobile.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80d14209-18a2-4d09-8385-4753bbc739fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/plan-to-monetize.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fdesign%2Fplan-to-monetize.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/abce16c0-914d-4888-802c-ff53efb4ace1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/planning-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fconcepts%2Fdesign%2Fplanning-checklist.md) | 88 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b53418ee-e63e-4861-beba-7cb383aa371b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 90 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/070739c9-28ed-4eb4-9b73-31cc2b8d4d57) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Ftabs%2Fdesign%2Ftabs.md) | 94 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/549bad44-7fd5-404f-b1ec-98c62dc49c69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed9848b1-66f2-429e-be87-1c839c008e2c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9fce4d5f6f5d2e6bcbcd766f6dac4ac5c24c60a6/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3c45042-a807-4c93-a0c1-a65c8e48ec40) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by surbhigupta12** [comment]
Closing this PR

**Pull request closed without merging**
