### PR TITLE
[Doc Improvement][Prerequisites and build environments]

### PR DESCRIPTION
**Pull request by v-tanmayirs**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5a229f3aefe7e07267a71a7ca924c0b9220e0f62/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/783758e0-1541-4ce5-b103-08abe194bf77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a229f3aefe7e07267a71a7ca924c0b9220e0f62/msteams-platform%2Ftoolkit%2Fprerequisites.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f2c9dd0-4ec9-4643-8a36-643f8fbaca25) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1ab7f71066fe012dbc33dd350665754d56e61c7d/msteams-platform%2FTOC.yml) | 97 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80b1f01a-6a96-4e5a-a323-67c7349890e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1ab7f71066fe012dbc33dd350665754d56e61c7d/msteams-platform%2Ftoolkit%2Fprerequisites.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6efc6b7-3937-42ec-ae70-d1d46ce20bd4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/292a9b2c9e61727728d1d600ba053b3db472d8e6/msteams-platform%2FTOC.yml) | 97 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9aadeba8-1055-4c8b-9209-1a504dad42e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/292a9b2c9e61727728d1d600ba053b3db472d8e6/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac462c7e-3b39-4ad8-8555-f9bd6962737d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/292a9b2c9e61727728d1d600ba053b3db472d8e6/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ea0b063-14b1-4d62-9f5c-c9b56e1ed9cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/prerequisites-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/292a9b2c9e61727728d1d600ba053b3db472d8e6/msteams-platform%2Ftoolkit%2Fprerequisites-tools.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cadc96c1-25d2-483d-bf21-378574649b81) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1e3490082e7c8df19d510c3882fa53910975f65a/msteams-platform%2FTOC.yml) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f6ce45b-7cd2-4590-9e9d-db8c5abd979d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e3490082e7c8df19d510c3882fa53910975f65a/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e94c5576-b6fd-4d09-8e1e-282c34b7cee9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e3490082e7c8df19d510c3882fa53910975f65a/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d648ccff-b585-412d-af16-dd4d5ecf6d96) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/prerequisites-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e3490082e7c8df19d510c3882fa53910975f65a/msteams-platform%2Ftoolkit%2Fprerequisites-tools.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0d25e59-9fbf-43dd-9bf5-b6ad1ca86c07) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e3490082e7c8df19d510c3882fa53910975f65a/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59b099a6-e1b7-40e5-9138-a97a090bfe61) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b051f75bc45d326f56189f420ce9b16f36f8c1d4/msteams-platform%2FTOC.yml) | 97 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2a79f60-d7ac-4132-b2ac-4bc10a65ce91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b051f75bc45d326f56189f420ce9b16f36f8c1d4/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2316ad0-6eb0-4867-a8df-77fe13bcbe37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/accounts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b051f75bc45d326f56189f420ce9b16f36f8c1d4/msteams-platform%2Ftoolkit%2Faccounts.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/048d3e2e-e088-4615-92ed-3faefbb9f5f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b051f75bc45d326f56189f420ce9b16f36f8c1d4/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7aeb0c34-c3e3-4027-a1df-2924a12f61b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b051f75bc45d326f56189f420ce9b16f36f8c1d4/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3108ca4-85f0-4d3d-9618-fd86fb794cfb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/abe4053c8e650b90c96b68719549bc4352db25a8/msteams-platform%2FTOC.yml) | 97 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2e45dda-a930-4351-9af1-fa1f2f86d8a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abe4053c8e650b90c96b68719549bc4352db25a8/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8770c751-2ee7-425a-80d2-d95b67167124) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/accounts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abe4053c8e650b90c96b68719549bc4352db25a8/msteams-platform%2Ftoolkit%2Faccounts.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2ebb8c2-ff16-41f7-aaaa-461237b1fba9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abe4053c8e650b90c96b68719549bc4352db25a8/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8506538-1738-4de0-9616-9356db3bcd0b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1e3563582c0e03d4016ecb54b845f1bc86ba6291/msteams-platform%2FTOC.yml) | 97 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28df3080-94d8-4045-8a91-d252392e49d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e3563582c0e03d4016ecb54b845f1bc86ba6291/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/667c9025-fb0e-477d-82a9-f1909b130385) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/accounts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e3563582c0e03d4016ecb54b845f1bc86ba6291/msteams-platform%2Ftoolkit%2Faccounts.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1623a512-3df2-495c-ba07-07c4a5143690) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1e3563582c0e03d4016ecb54b845f1bc86ba6291/msteams-platform%2Ftoolkit%2Fprovision.md) | 91 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c0588e6-f89a-4c0d-8ad1-540e6b390309) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-abirade** [comment]
Closing the PR due to multiple conflicts.

**Pull request closed without merging**
