### PR TITLE
[Doc Improvement][Update adaptive card tabs][3035352]

### PR DESCRIPTION
**Pull request by v-ypalikila**
Added not about deprecation of Adaptive card tabs.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dba0ba9244223af3108c7b5fd744ac3a373ab495/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/903f54ff-bbd2-4cda-a90c-06e760940b71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dba0ba9244223af3108c7b5fd744ac3a373ab495/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/848143f5-aa81-4c01-9cbe-883140574f4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dba0ba9244223af3108c7b5fd744ac3a373ab495/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a798a7ce-78a8-41cc-b7ea-6943a8129c53) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/02dc65d308e11162ebc19c08f8e14ffb06afe395/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 91 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0024e90-9555-409e-bd55-15940b6986fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02dc65d308e11162ebc19c08f8e14ffb06afe395/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97a49955-9e20-4831-bfcb-cbfa8b345dfb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02dc65d308e11162ebc19c08f8e14ffb06afe395/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45412722-0f25-4d2e-87fe-60f435e29cb9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/53e068a09f69ab311311a5e62a97223f7d0fd084/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ecdb453-72c1-48b9-903f-9e14162e3572) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53e068a09f69ab311311a5e62a97223f7d0fd084/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7497e99-f4fa-4b4d-b952-2774358ab507) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53e068a09f69ab311311a5e62a97223f7d0fd084/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ffb9e5e-2158-4627-8582-a5c45887470c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c15eec53184a6cf60f471ed1216767fe4eebd1ea/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ded235ed-f273-4e19-8085-1bf99431f655) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15eec53184a6cf60f471ed1216767fe4eebd1ea/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0c083c2-b76f-48bc-83e2-685a1b311e05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c15eec53184a6cf60f471ed1216767fe4eebd1ea/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e05853b7-cc40-4fe9-b298-6417c0394dc3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/70e82be168d97d13c0e6ca14f8ee2da9804f5df5/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 92 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2993966e-4703-412c-896d-3bfb9ea0047d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/70e82be168d97d13c0e6ca14f8ee2da9804f5df5/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89d2544a-72f1-4f8d-bae3-82f49664e346) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/70e82be168d97d13c0e6ca14f8ee2da9804f5df5/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/988a18a0-c10f-4ae2-bb42-de77911ec0ab) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f767e50557355ca0ce706bf2209556109c4d9c14/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12c95d64-36c6-44f6-9263-b63874d8c414) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f767e50557355ca0ce706bf2209556109c4d9c14/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04f7aa46-0096-40cc-8ae6-902fbe02f58b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f767e50557355ca0ce706bf2209556109c4d9c14/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65f2219b-fb68-4a44-8170-97878767c6c6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5f211f9fcc09c20a01b582e8a5fb38f61b7df2/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 92 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12deb9c6-1a5d-441b-986c-ebc72e6018dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5f211f9fcc09c20a01b582e8a5fb38f61b7df2/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5666f8dc-1e5e-46e8-a4ac-ff5fd51d73b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5f211f9fcc09c20a01b582e8a5fb38f61b7df2/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65a3914d-d4e6-43ea-9b23-564a5f829b36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a5f211f9fcc09c20a01b582e8a5fb38f61b7df2/msteams-platform%2Fwhats-new.md) | 94 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70afd907-dfe3-49ae-b054-5031244f44ed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35a50dbe8ac558be6db51c7543f9ef35dd2a4dbd/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 92 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c2edc09-6c25-414f-bc2e-8cf73294ca30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35a50dbe8ac558be6db51c7543f9ef35dd2a4dbd/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b585a59-8edf-4e41-bb06-d20c879ca09a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35a50dbe8ac558be6db51c7543f9ef35dd2a4dbd/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a69ee20-8acf-4bc7-a679-4deb03347ab4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35a50dbe8ac558be6db51c7543f9ef35dd2a4dbd/msteams-platform%2Fwhats-new.md) | 94 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70abf262-ee25-4c87-980f-ac8d387803b2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b90dddb59dde9870aabd70f310ab05e96d4b9126/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 92 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c34d6828-8969-4cff-898f-be3bd643b1fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b90dddb59dde9870aabd70f310ab05e96d4b9126/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c20bf98-e62d-49b8-a0c7-e7c35cba0cda) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b90dddb59dde9870aabd70f310ab05e96d4b9126/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be2dd1f2-b413-441d-ab94-fbf16d674931) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b90dddb59dde9870aabd70f310ab05e96d4b9126/msteams-platform%2Fwhats-new.md) | 94 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e274bec5-5301-4003-83ce-6d12ef997cc3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-tab-with-adaptive-cards.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4c1d8d0d787ba29d27fff790d2e8729f670ce615/msteams-platform%2Fsbs-tab-with-adaptive-cards.yml) | 92 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/389dcd22-aa8c-492a-b102-e04016ef8998) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c1d8d0d787ba29d27fff790d2e8729f670ce615/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66eb73ff-fae7-4acd-93e2-7e36aeacf015) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c1d8d0d787ba29d27fff790d2e8729f670ce615/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/452f643a-e2c6-4a4f-bf77-812e4f3b4b2a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c1d8d0d787ba29d27fff790d2e8729f670ce615/msteams-platform%2Fwhats-new.md) | 94 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/533551dd-44af-467d-958e-4276d9fef414) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by fw-himanshu** [comment]
@v-ypalikila @ydogandjiev When is this deprecation planned to be effective and what will happen to the apps that are using adaptive card tabs. We were building a feature for our bot using adaptive card tabs and need to reconsider whether we should release it now or rebuild it with web view tabs. Can you please advice us.

**Pull request merged**
