### PR TITLE
Share to teams initial documentation

### PR DESCRIPTION
**Pull request by clearab**

### CODE REVIEW

**Comment by clearab** [comment]
Not available in the TOC, creating dark release to be shared with select partners

**Comment by o365devx** [comment]
OPS Build status updates of commit _[0994de4](https://github.com/MicrosoftDocs/msteams-docs/pull/526/commits/0994de48668ac54c00a8a6c677d2ef3a8617c831)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-share-to-teams/msteams-platform/share-to-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C26%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903262049198200-526%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=n%2BjX8Erdx4SsQLrJxvh3zCr3JLGABufWqfEXnE3bszI%3D&st=2019-03-26T20%3A45%3A36Z&se=2019-04-26T20%3A50%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[698b066](https://github.com/MicrosoftDocs/msteams-docs/pull/526/commits/698b066da2d64e9945b9e3afb48cce864eb25d32)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-share-to-teams/msteams-platform/share-to-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C26%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903262113424656-526%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0GJxAny96Xf1Ylew7Zi%2BRoLVJ87Nez9vX5HYpjy%2Bvks%3D&st=2019-03-26T21%3A10%3A00Z&se=2019-04-26T21%3A15%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[31dfa8d](https://github.com/MicrosoftDocs/msteams-docs/pull/526/commits/31dfa8d41675c92edaed685b0000d35bc84c59ed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-share-to-teams/msteams-platform/share-to-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C26%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903262124496266-526%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PRghBeCF4tgWT2H1El3uXKFA6YmXiy%2FrTQ8%2Fq6L2tCA%3D&st=2019-03-26T21%3A21%3A14Z&se=2019-04-26T21%3A26%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[7eceb77](https://github.com/MicrosoftDocs/msteams-docs/pull/526/commits/7eceb775d98e3be27f96690b0c21bee8166e275c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/share-to-teams-popup.png](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-share-to-teams/msteams-platform/assets/images/share-to-teams-popup.png) | :white_check_mark:Succeeded | |
[msteams-platform/share-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac-share-to-teams/msteams-platform/share-to-teams.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903291812355006-526%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qcd6wAK2%2F2G6pcZc7ck3sk4wVAN%2FvhvgKJxedoXFicA%3D&st=2019-03-29T18%3A08%3A57Z&se=2019-04-29T18%3A13%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
