### PR TITLE
[Doc Improvement][SEO meta title - post publish check][3948824]

### PR DESCRIPTION
**Pull request by v-ramyas5**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/39cf9bf6d47837b2b3dc790addd497d8f8385a56/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 74 | 117 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/840f8b0b-06b4-4f44-9e86-67fe5d75714c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/39cf9bf6d47837b2b3dc790addd497d8f8385a56/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 79 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22b42d4d-aca0-4c32-833b-13fb7de7214c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/39cf9bf6d47837b2b3dc790addd497d8f8385a56/msteams-platform%2Fsbs-gs-notificationbot.yml) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13d10db2-eea5-4dbd-ae9d-3f151b47390e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/39cf9bf6d47837b2b3dc790addd497d8f8385a56/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb87e2b7-d9f4-4f93-b4ef-db316e041648) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/39cf9bf6d47837b2b3dc790addd497d8f8385a56/msteams-platform%2Fsbs-meeting-token-generator.yml) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/beba5288-f5ed-4140-9ff2-340c65b5fa18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/39cf9bf6d47837b2b3dc790addd497d8f8385a56/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 81 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f98f9e09-6820-485e-aee7-b0ea0b3c1ad1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/39cf9bf6d47837b2b3dc790addd497d8f8385a56/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7dd0f1f-e54b-43aa-8205-76043b260e29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/39cf9bf6d47837b2b3dc790addd497d8f8385a56/msteams-platform%2Fsbs-tab-device-permissions.yml) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aedaddeb-573d-4cf0-af86-5590fe62ff4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/39cf9bf6d47837b2b3dc790addd497d8f8385a56/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d75e147c-eaa0-4797-957b-f957c84266e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/add-single-sign-on-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39cf9bf6d47837b2b3dc790addd497d8f8385a56/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fadd-single-sign-on-vs.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7509ef75-44e7-425e-8465-551fb6525574) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c845e3f5900dca28e9c8b1893bee6d182acd6323/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 74 | 117 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ebda47ae-00ae-42a2-a79e-6a25795d0fc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c845e3f5900dca28e9c8b1893bee6d182acd6323/msteams-platform%2Fsbs-bots-with-sso.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04fa1793-9190-45b8-9839-3aaaf06474a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c845e3f5900dca28e9c8b1893bee6d182acd6323/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 79 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6bd1738-7bd8-464f-8fc1-2d75232c0f05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-commandbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c845e3f5900dca28e9c8b1893bee6d182acd6323/msteams-platform%2Fsbs-gs-commandbot.yml) | 88 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3272e106-9691-4660-935d-4572fd93900d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c845e3f5900dca28e9c8b1893bee6d182acd6323/msteams-platform%2Fsbs-gs-notificationbot.yml) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bb05fb7-9f17-4b8e-9aa4-5d6a9172baff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c845e3f5900dca28e9c8b1893bee6d182acd6323/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a288b6d-9574-461a-aedb-f6d450185d60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c845e3f5900dca28e9c8b1893bee6d182acd6323/msteams-platform%2Fsbs-meeting-token-generator.yml) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6ce333f-e692-4c49-86df-b2ecdcd8466a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c845e3f5900dca28e9c8b1893bee6d182acd6323/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 81 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af67b9b4-f8f2-4104-9c37-3d6edbe31a94) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c845e3f5900dca28e9c8b1893bee6d182acd6323/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2da6237-ea99-4336-bc3b-bdea6df54d5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c845e3f5900dca28e9c8b1893bee6d182acd6323/msteams-platform%2Fsbs-tab-device-permissions.yml) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fc71bbf-9fa0-4f10-9f51-5a929a1ea70e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c845e3f5900dca28e9c8b1893bee6d182acd6323/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/925a733b-6689-4ee4-84ec-51cbd16959d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c845e3f5900dca28e9c8b1893bee6d182acd6323/msteams-platform%2Fsbs-teams-live-share.yml) | 86 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a829b2a4-b7d6-40a1-a4ec-e866ae564638) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/add-single-sign-on-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c845e3f5900dca28e9c8b1893bee6d182acd6323/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fadd-single-sign-on-vs.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c841fd7a-6b80-46ee-9254-5d9ce2a68b13) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62d6e8326d1220f9d98fae1fc8fb8cc8b4a0070d/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 74 | 117 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8026e04-955b-458a-9517-9c91d35d74ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62d6e8326d1220f9d98fae1fc8fb8cc8b4a0070d/msteams-platform%2Fsbs-bots-with-sso.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fabba26-cd41-45fa-9fc3-08bfb2aab493) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62d6e8326d1220f9d98fae1fc8fb8cc8b4a0070d/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 79 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a764866-e1f7-4f7f-9a42-c0ab4cc62bb2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-commandbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62d6e8326d1220f9d98fae1fc8fb8cc8b4a0070d/msteams-platform%2Fsbs-gs-commandbot.yml) | 88 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e062960-1e65-4c0b-b71d-b2d03d60a37e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62d6e8326d1220f9d98fae1fc8fb8cc8b4a0070d/msteams-platform%2Fsbs-gs-notificationbot.yml) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce66f33e-de27-48af-8291-7975516acc83) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62d6e8326d1220f9d98fae1fc8fb8cc8b4a0070d/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d5cff54-5959-4d30-aba5-199d5307f35c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62d6e8326d1220f9d98fae1fc8fb8cc8b4a0070d/msteams-platform%2Fsbs-meeting-token-generator.yml) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c1e0955-a610-422e-86aa-0a5fdb2d3052) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62d6e8326d1220f9d98fae1fc8fb8cc8b4a0070d/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 81 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3c15ca0-76b1-4828-8e07-5c65f6e0f721) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62d6e8326d1220f9d98fae1fc8fb8cc8b4a0070d/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d996b71a-fa86-43f2-9511-81f9bfef736c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62d6e8326d1220f9d98fae1fc8fb8cc8b4a0070d/msteams-platform%2Fsbs-tab-device-permissions.yml) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ba4e190-e76c-47d5-af90-adb465c3223e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62d6e8326d1220f9d98fae1fc8fb8cc8b4a0070d/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccd00468-4086-45c5-b61f-6dca514ab6c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62d6e8326d1220f9d98fae1fc8fb8cc8b4a0070d/msteams-platform%2Fsbs-teams-live-share.yml) | 86 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c710635-d552-41bc-a3fe-139d8e84e0a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/add-single-sign-on-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/62d6e8326d1220f9d98fae1fc8fb8cc8b4a0070d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fadd-single-sign-on-vs.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/032c4589-8f2d-485f-9b8e-2919760803f6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-api-based-message-extensions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/02629749646f1f73dcc7479b456192cdf40c3942/msteams-platform%2Fsbs-api-based-message-extensions.yml) | 74 | 117 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eb3ef034-762b-403f-af10-8199b846a428) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/02629749646f1f73dcc7479b456192cdf40c3942/msteams-platform%2Fsbs-bots-with-sso.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2feac9d0-7576-4211-8e2f-6b82a4fbd4d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/02629749646f1f73dcc7479b456192cdf40c3942/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 79 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e3eb5b5-e640-446f-ae10-e3d3755be6de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-commandbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/02629749646f1f73dcc7479b456192cdf40c3942/msteams-platform%2Fsbs-gs-commandbot.yml) | 88 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01945d46-aba7-45c7-92f4-1b1ff5ca729b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/02629749646f1f73dcc7479b456192cdf40c3942/msteams-platform%2Fsbs-gs-notificationbot.yml) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/efdd3313-1324-499b-b79b-b70dad41785c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/02629749646f1f73dcc7479b456192cdf40c3942/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02f9e324-da7a-4f51-9f66-4d23463659d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/02629749646f1f73dcc7479b456192cdf40c3942/msteams-platform%2Fsbs-meeting-token-generator.yml) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f976126-2bdf-4c4a-bb41-6737f0b488fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/02629749646f1f73dcc7479b456192cdf40c3942/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 81 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42c28b99-6440-4cbe-b86d-cf2542069e44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/02629749646f1f73dcc7479b456192cdf40c3942/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a9c53f9-1b50-42ca-98d0-8c0631307876) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/02629749646f1f73dcc7479b456192cdf40c3942/msteams-platform%2Fsbs-tab-device-permissions.yml) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56b2f29a-1ba7-463b-8a5c-12c297880139) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/02629749646f1f73dcc7479b456192cdf40c3942/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61617400-bc19-478d-8933-0e36436de707) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-live-share.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/02629749646f1f73dcc7479b456192cdf40c3942/msteams-platform%2Fsbs-teams-live-share.yml) | 86 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f0f84ee-3190-4cb5-a1fb-78947cf0488d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/add-single-sign-on-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02629749646f1f73dcc7479b456192cdf40c3942/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fadd-single-sign-on-vs.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd24015f-b1a8-4462-8cb0-2a0aed017e35) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
