### PR TITLE
[Doc Issue][use existing bot]

### PR DESCRIPTION
**Pull request by Namitha-23**
Adding reference for using an existing bot to debug a Teams app.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f9f4a0caa5508e0b024fc78aa9ba311cb6092d9/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59b116a9-241d-4ce3-856c-ae7542535dd7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7fd9fa168f707cc974c312fe7637095458e6908e/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/555237cc-e1e4-4ca4-8ef7-3095141b649b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32db272e5a210d8f0b9dd8506901b00c60a599c4/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bab09e8-96e7-4298-be8f-0b3f81544e59) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6696c160999a64e810e9adb0432a18844de16db5/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f1aff2e-9c39-40eb-8eb4-7569f20cf4ef) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3238a2cf49a72e8b2e627bdbd34b53dd7b8e3534/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c1ba0a8-7479-473a-b0ca-8c79e92bee50) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6706b4b31ad9d248e960c16bb38d05be9a5af6dd/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1601951-ba7a-480a-8121-347115d08780) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/132fa1b2ee8c4fdecaf7e2635d8df8942662f0af/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11224fb8-4784-4ad1-adcf-5cb76e19b0a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/132fa1b2ee8c4fdecaf7e2635d8df8942662f0af/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52655911-8b03-4aa0-a2fe-11d02d2d915f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea49b674c95930060cf483fbd3457c40521b871a/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73c36f7b-18f7-4779-8423-3452efb66867) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea49b674c95930060cf483fbd3457c40521b871a/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dde6ebf5-18d8-4783-ba6a-ab1cdba44390) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by MuyangAmigo — APPROVED** [review]

**Review by v-habibaumme — APPROVED** [review]
Approved

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7382f33bcf906947b4561defb11c7b3794810ebe/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f586aeb0-711f-4692-9111-f7d8e1b766e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7382f33bcf906947b4561defb11c7b3794810ebe/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92e26e94-c0d3-4d79-bd3a-e3f3ef82270b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5d8952b5b4e538f23649c1ddea9faf62c974d54b/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b6f7310-1e20-42b9-9e25-f1e1f6fe0f54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5d8952b5b4e538f23649c1ddea9faf62c974d54b/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58acec78-dafd-4ce2-af3e-b5080b276e60) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d0863e9996c8d6557f8c80682448dd83006f91a9/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f42feb2c-6d7c-43f8-a751-926196c0170a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d0863e9996c8d6557f8c80682448dd83006f91a9/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9e9f950-9185-4787-9c0f-2565669f9a16) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db0e150c881822662813a6e7bd1ba5fb04ed1789/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6e7f2ac-b782-4ae8-8f21-0c1e026f107b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db0e150c881822662813a6e7bd1ba5fb04ed1789/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17d9a954-97f2-4f79-85dd-c54cd8d2f29a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f1a92ad48a2f74a0e6b7e5a4106095db37a5328/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c750e14-16c1-4122-b86b-de719c26549f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f1a92ad48a2f74a0e6b7e5a4106095db37a5328/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cea058d7-1c12-4596-bceb-f046444a39a6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
