### PR TITLE
[Doc Issue][Teams Toolkit Doc bug-fix, use formal Azure service name][2697174]

### PR DESCRIPTION
**Pull request by summzhan**
"Azure functions" => "Azure Functions"
"Azure storage" => "Azure Storage"
"Azure app service" => "Azure App Service"

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1797d4ca4e4c5f049ee5c50869bef04226892f2a/msteams-platform%2Ftoolkit%2Fdeploy.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35fc6157-66ba-45e5-90df-eb0a66d057c3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/96f12db27c3faa2d461241c42335befc4f44f40c/msteams-platform%2Ftoolkit%2Fdeploy.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6923bacb-2944-42bc-ba71-3aa68cde2539) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c367b3d50deda54d83c9837279e7336eb81d90f/msteams-platform%2Ftoolkit%2Fdeploy.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e8a146f-1036-48ed-9195-dcb4d25a4c2c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47a341d505527b22054c321f33e278ec16c091cf/msteams-platform%2Ftoolkit%2Fdeploy.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4ee8314-479e-492b-af01-73260d75b938) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47a341d505527b22054c321f33e278ec16c091cf/msteams-platform%2Ftoolkit%2Fdeploy.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc09981b-eee1-4c53-8573-a2f174444f36) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-habibaumme** [comment]
@summzhan, 

Request you to please sign the CLA agreement without which we won't be able to merge the PR:

sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/MicrosoftDocs/msteams-docs?pullRequest=7192) before we can accept your contribution.

❌ summzhan [sign now](https://cla.opensource.microsoft.com/MicrosoftDocs/msteams-docs?pullRequest=7192)
You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/MicrosoftDocs/msteams-docs?pullRequest=7192) it.

**Comment by summzhan** [comment]
@surbhigupta12 , could you please help me merge this PR?

**Comment by summzhan** [comment]
> @summzhan,
> 
> Request you to please sign the CLA agreement without which we won't be able to merge the PR:
> 
> sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/MicrosoftDocs/msteams-docs?pullRequest=7192) before we can accept your contribution.
> 
> ❌ summzhan [sign now](https://cla.opensource.microsoft.com/MicrosoftDocs/msteams-docs?pullRequest=7192) You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/MicrosoftDocs/msteams-docs?pullRequest=7192) it.

@v-habibaumme , Thanks for reminder, I have just notice your comments and signed up for CLA. Please proceed to merge it,.

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
