### PR TITLE
Teams toolkit update - updated screenshots and minor text to reflect toolkit GA

### PR DESCRIPTION
**Pull request by mobajemu-msft**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33de0b440f47e1d541d0f5187d4098c10b764188/msteams-platform%2Fsbs-gs-javascript.yml) | 90 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/458d4c1c-44cc-418d-99e8-85073dff2ce4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33de0b440f47e1d541d0f5187d4098c10b764188/msteams-platform%2Fsbs-gs-spfx.yml) | 94 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fcc0e67-c930-4ba2-807d-a546829fe531) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33de0b440f47e1d541d0f5187d4098c10b764188/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 83 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/997962fb-3c7b-41cf-8229-8a4bd0496220) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33de0b440f47e1d541d0f5187d4098c10b764188/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfd44726-2117-4968-ae9a-dc3ddbc29091) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33de0b440f47e1d541d0f5187d4098c10b764188/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70bf9146-66dd-4dc0-8fe7-ff6ec10e6b9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33de0b440f47e1d541d0f5187d4098c10b764188/msteams-platform%2Fsbs-meetings-stage-view.yml) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f4f9cea-9838-41a9-8f0b-31aa0786ef37) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by mobajemu-msft** [comment]
updated screenshots and text under the "Enable sideloading option" section
added note tag under "set up local environment" on how to prevent error of "file name too-long" error
included additional screenshot under section "Update the Azure AD app registration"
and other minor miscellaneous changes

**Comment by erikadoyle** [comment]
@surbhigupta12 when you have a chance, would you mind reviewing? Thanks!

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cc4b97d376d7f314fbcbda00e922404c55d1e2fa/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32ff706a-5289-463f-8dbe-2a42180be7c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-spfx.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cc4b97d376d7f314fbcbda00e922404c55d1e2fa/msteams-platform%2Fsbs-gs-spfx.yml) | 94 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d40529f-e913-4da6-8d59-7c28b6609ba8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cc4b97d376d7f314fbcbda00e922404c55d1e2fa/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 83 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97ea715d-9e01-4779-b8dd-d3bb418ae3d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cc4b97d376d7f314fbcbda00e922404c55d1e2fa/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/901574b5-faf4-410d-9f0b-22cb4a7aa365) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cc4b97d376d7f314fbcbda00e922404c55d1e2fa/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16771e3e-a226-413d-8afd-003aba4558b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cc4b97d376d7f314fbcbda00e922404c55d1e2fa/msteams-platform%2Fsbs-meetings-stage-view.yml) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36729f0e-11e0-4d7c-a746-a37aaa937782) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2a5f7f8-894c-48d7-823c-2341ddce1f00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87844fed-28ef-4dca-9230-0ec3b0926cb7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/enable-and-configure-your-app-for-teams-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fapps-in-teams-meetings%2Fenable-and-configure-your-app-for-teams-meetings.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/880ead2b-5c68-413f-a39d-f1ed108227df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 98 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3dc90d62-3aeb-4822-b3fc-270b15396d2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/863d17cd-6efa-4344-8c41-232242172530) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-capabilities.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3c0f5da-dd9c-423b-9724-5e0f19678015) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-faq.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5d374e7-d895-400b-a9f7-296b117371c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-media-capabilities.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52928746-a857-4272-ba3c-5dae0c5a1a08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d548c1ca-8c52-4e1e-ac13-e56d698b921b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-quick-start.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15ca483a-7010-4733-915a-9ad899043915) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-tutorial.md) | 94 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d08572f0-83b0-464b-8e00-829d0eef1c2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fapps-in-teams-meetings%2Fteams-together-mode.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44bd0605-e758-40a9-9798-ba4b32b91ac2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fc64114-2dda-4764-a000-b122b38d7ce8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fbots%2Fhow-to%2Fformat-your-bot-messages.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1878be4-2347-4b2e-9aef-f07182eebdfb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-links.md) | 90 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/deb77fc7-3d7e-41bd-ab7d-028786699bcc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96e95ed3-0fad-464a-aa85-c666238bd7a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2462c06b-0e99-45df-a5ec-d34971f72863) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 93 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d726f2c-48c8-4201-9322-b97231fe204c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab32f873-de5f-424e-a9cc-01f948669992) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/sdk-include.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fincludes%2Fsdk-include.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9af8f4d-f20a-45c8-b659-5bc8bae04aaf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Findex.yml) | 94 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae0e1624-a279-4248-b329-80d2c683f644) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63866c8c-358a-46f2-a75a-2ef664d0b5fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Foverview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0ad2b02-bf6a-46a7-b7ed-0592877ddaf0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/faqs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fresources%2Ffaqs.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3febd7c-55a3-43ff-abb0-c9e2fa91aca7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df252bab-f624-43d2-ae50-993c76735402) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/partner-apps-for-moodle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fresources%2Fpartner-apps-for-moodle.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1d03a9a-b210-498b-ba83-00efd9032059) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 83 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8a36efb-28e8-49fb-8aa2-bad26b006d30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd6fef31-024c-4fe9-ab42-bd24f0e7c6f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fsbs-bots-with-sso.yml) | 88 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b124cb51-0b02-4efa-bf52-808cbab4b439) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4a03e9de23c95cbcfea7f096383ef14174fc29cd/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75c3a521-c4c9-4784-b633-5d2c435500a6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-abirade** [comment]
We have taken inputs and shifted the content to PR #6496.

**Pull request merged**
