### PR TITLE
[Doc Improvement][Error handling messages][3465855]

### PR DESCRIPTION
**Pull request by v-bvishnu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9ec5ce6fa264c12f6e659489a4f3b499665b4163/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04591572-66d0-4fff-9eb3-01607817e906) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ec5ce6fa264c12f6e659489a4f3b499665b4163/msteams-platform%2Ferror-handling-messages.md) | 80 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc555eb2-c3db-403c-bfa7-c1f851625188) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0ec8c7ca52d057d072d1bb7fb321f6f352468144/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2258d760-91d1-43f8-9309-970b7e52077b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ec8c7ca52d057d072d1bb7fb321f6f352468144/msteams-platform%2Ferror-handling-messages.md) | 80 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5996402-828a-4958-9b76-eb5e7db5a863) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a2f10e6f6074769adbe392fe0eccff7c3731d71a/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/224d2b77-542a-4b99-9a7c-86d5a4cf2629) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2f10e6f6074769adbe392fe0eccff7c3731d71a/msteams-platform%2Ferror-handling-messages.md) | 78 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1622de9-5f90-4ace-af84-74f485791a5e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab3012388e9e0004ffd82df0fd24d1c3e38c4de9/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f2bf751-8e65-46ae-8b69-697714cb1592) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab3012388e9e0004ffd82df0fd24d1c3e38c4de9/msteams-platform%2Ferror-handling-messages.md) | 76 | 69 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5371bead-0f6d-4697-98e9-c0b7d05a529c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/94e48675280e939624604c7511feb312f5f5d655/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d010230-390f-4b61-a4ce-d3923bc4d654) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94e48675280e939624604c7511feb312f5f5d655/msteams-platform%2Ferror-handling-messages.md) | 77 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6dc18ef-e01d-4a12-bcc1-6b1d1e29eba5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/500b4fcf27ee15f04a42362bc03544dfe0f7bfd6/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/569db29b-c4f2-4d5b-83c4-67bf768218b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/500b4fcf27ee15f04a42362bc03544dfe0f7bfd6/msteams-platform%2Ferror-handling-messages.md) | 74 | 177 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c8e7814-8aa5-4a98-b87a-fa808f9d9cc5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/45983cdaae8972365c975c586c9b2d792e77d091/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa4a661c-4874-4b04-812a-e4865ec88e29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/45983cdaae8972365c975c586c9b2d792e77d091/msteams-platform%2Ferror-handling-messages.md) | 73 | 210 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03494810-f17b-4b42-b0e4-05351ce5c79c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8dceda5965a61ac0a11862b629239730bbab0e1e/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7d6108a-2053-47c0-93b8-3c4429abc5ed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8dceda5965a61ac0a11862b629239730bbab0e1e/msteams-platform%2Ferror-handling-messages.md) | 73 | 308 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e31f68d-02c6-43d8-974b-2fcd4d9aaa19) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aece44fbaae82a946743569779c17f4233c3a29c/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b840dd24-abf2-4fb2-8140-6d1a0a58324f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aece44fbaae82a946743569779c17f4233c3a29c/msteams-platform%2Ferror-handling-messages.md) | 73 | 308 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b85ec304-8d1f-4814-bd36-b7ec70fdff01) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/18b0d1b4837079b6fafec883167d2d30d26d4bd5/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4fe2da8a-ea82-43bc-9217-b34d497beb94) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/18b0d1b4837079b6fafec883167d2d30d26d4bd5/msteams-platform%2Ferror-handling-messages.md) | 73 | 308 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c76d339e-9115-4a32-b084-5b4f224d2885) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9b51825e6226a5fc7eca2d4d6bc92d8faf25a502/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e755bf27-c7f8-42d7-8c3c-b556624463a7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b51825e6226a5fc7eca2d4d6bc92d8faf25a502/msteams-platform%2Ferror-handling-messages.md) | 82 | 197 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5210944b-1a9f-4b83-adea-20cce48f66b5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/08c5ed73700aca0b0d9ec0653e205d32d6855348/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe2e189d-0561-4a8f-abca-23a122779187) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08c5ed73700aca0b0d9ec0653e205d32d6855348/msteams-platform%2Ferror-handling-messages.md) | 82 | 196 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe6768fe-b509-4102-a48b-a1a6bc05287e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/829e5fee0edee44f963f8f9b46fc8ef5a7b3ca73/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/375ec015-aae2-4f40-9350-8e3518c7f060) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/829e5fee0edee44f963f8f9b46fc8ef5a7b3ca73/msteams-platform%2Ferror-handling-messages.md) | 82 | 196 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/161d1c23-7f0b-4e0d-9e40-4c7e88ab7828) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a9defb09582cf575737f261187bb4cf8d7749a34/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa454d13-7b3a-4616-a6b1-bf21670c34d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9defb09582cf575737f261187bb4cf8d7749a34/msteams-platform%2Ferror-handling-messages.md) | 82 | 196 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0965eea9-ca9a-4008-a402-32e28b780427) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/268e6cfb7fe680846124cdcb3444fa403e120fb1/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d02976aa-f9fb-436c-ada8-3ea6a65c7edf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/error-handling-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/268e6cfb7fe680846124cdcb3444fa403e120fb1/msteams-platform%2Ferror-handling-messages.md) | 82 | 193 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03164c64-04ae-4c8a-9cbe-a787bcef7073) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by surbhigupta12** [comment]
Closing this PR as the work is taken up in PR #9620

**Pull request closed without merging**
