### PR TITLE
[Doc Improvement][Stageview to multi-window]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/open-content-in-stageview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7053d2a663d584fe2a4d908129e5e4ee757ffec0/msteams-platform%2Ftabs%2Fopen-content-in-stageview.md) | 82 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba3250a0-c2db-47dc-be0c-cf56dab91448) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by aaronmah — CHANGES_REQUESTED** [review]
@v-npaladugu we change the title in the left navigation as well

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/587304e6dc7b4857cac0d6abc2375f854d9db78e/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee2c042b-03ca-4000-961e-29c9be15ccd7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/open-content-in-stageview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/587304e6dc7b4857cac0d6abc2375f854d9db78e/msteams-platform%2Ftabs%2Fopen-content-in-stageview.md) | 82 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6974eaf2-46e2-497b-a9ae-71ac87096b30) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by aaronmah — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5f68c6d91c8647cc4d6160269319be5ca06e24dd/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bcbe505-e75f-409c-bef9-6708ba8eb5c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/open-content-in-stageview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f68c6d91c8647cc4d6160269319be5ca06e24dd/msteams-platform%2Ftabs%2Fopen-content-in-stageview.md) | 82 | 68 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f34567a-24f9-494d-b839-429e4da95b4b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
