### PR TITLE
[EditedContent]

### PR DESCRIPTION
**Pull request by GubbaPallavi**
Edited in last line.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/first-app-blazor.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ddc0242b1ae4733172cdd2867ee462b8f34f8eb/msteams-platform/get-started/first-app-blazor.md) | 84 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e36cd1ed-865e-4a04-b454-8ef899d8cf17) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/first-app-blazor.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a659c8074b3d09bb436cfdfe1966135d5b58cc7d/msteams-platform/get-started/first-app-blazor.md) | 86 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4acee71e-cb6d-44e1-8248-b7db8a8185f8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/first-app-blazor.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5db5ba93d3e647498c566b69e8db7a9320b5792/msteams-platform/get-started/first-app-blazor.md) | 86 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10a96a7d-098b-463a-86ec-0a05a0a83486) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/enable-SSO-auth-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5db5ba93d3e647498c566b69e8db7a9320b5792/msteams-platform/messaging-extensions/how-to/enable-SSO-auth-me.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6675e26-fb7c-4fc5-8f25-cbbef2deaa07) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]
Approved

**Comment by surbhigupta12** [comment]
Test PR

**Pull request closed without merging**
