### PR TITLE
Update locally-with-an-ide.md

### PR DESCRIPTION
**Pull request by YannickRe**
Fix the ngrok command

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/debug/locally-with-an-ide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebc15f72b165ac0279df9a9effe52ed08d277b56/msteams-platform%2Fbots%2Fhow-to%2Fdebug%2Flocally-with-an-ide.md) | 78 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba555bce-48fb-4879-b56b-803e01434171) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by surbhigupta12** [comment]
Changes incorporated in another PR.

**Comment by surbhigupta12** [comment]
@YannickRe, the change is reflected on live site:

https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/debug/locally-with-an-ide#debug-your-bot-locally

image

**Comment by YannickRe** [comment]
@surbhigupta12 Please check my PR again. The live site (and your screenshot) shows one dash `-host-header` but my PR updates it to **TWO** dashes: `--host-header`.
I can assure you that one dash is not correct ;)

**Comment by surbhigupta12** [comment]
So sorry. That's a miss from my side. I'd update it right away.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/debug/locally-with-an-ide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebc15f72b165ac0279df9a9effe52ed08d277b56/msteams-platform%2Fbots%2Fhow-to%2Fdebug%2Flocally-with-an-ide.md) | 78 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10167a88-1de0-4cb9-b9aa-c19519938965) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by YannickRe** [comment]
@surbhigupta12 Thank you for fixing this, but why did you not merge my PR? It's taking away the recognition from me, and that's not really encouraging me to provide fixes in the future.

**Comment by surbhigupta12** [comment]
Hi @YannickRe,

We've updated:

https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/debug/locally-with-an-ide#debug-your-bot-locally

image

**Comment by YannickRe** [comment]
I know YOU fixed it, taking the credit of the PR. You could have just accepted MY PR, have MY name show in the contributors list.
It is just a tiny typo update, but I found it, went through the effort of forking, updating and PR'ing. Your actions discourage any future contributions.

**Comment by surbhigupta12** [comment]
@YannickRe, that was not at all our intention. We are extremely apologetic for this. We reopened the PR and the Acrolinx score was <80 resulting in build failure.  intention was to help and not to take the credit at all. We highly appreciate all the contributions.

**Comment by YannickRe** [comment]
Thank you for recognizing this. I have no responsibility over the Acrolinx score, it should not block simple fixes like this.
If it does, there should be a better solution.

**Comment by surbhigupta12** [comment]
The Acrolinx score is a validation to ensure that the overall content quality of the article is met. It was not specific to the change you made. We'd look into how to handle this better.

Thank you for your understanding and we look forward to more contributions from your end. We'd guarantee you'd have a better experience.

Thank you.

**Pull request closed without merging**
