### PR TITLE
[Doc Feature][Update shared channels][1700949]

### PR DESCRIPTION
**Pull request by v-bdeepa**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/353867c539189a47211eb3f55148520160317731/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2822d0cf-98ea-406d-80d4-59d57ae64e29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/Shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/353867c539189a47211eb3f55148520160317731/msteams-platform%2Fconcepts%2Fbuild-and-test%2FShared-channels.md) | 78 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a434496-ab49-4280-ab7a-555b69658d64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/353867c539189a47211eb3f55148520160317731/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1bb418e-d9f9-4ba4-b469-2efb16d018df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/353867c539189a47211eb3f55148520160317731/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0dfaa161-f39f-4ab7-8ab9-6d4371cfb23f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/353867c539189a47211eb3f55148520160317731/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d3c9c90-16f7-4f56-967f-b2a167ac67de) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb793186e1eca36832011a656bb20662f5fa1fc8/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66e99142-5162-4d2f-95ad-1fa3bc3c56db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/Shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb793186e1eca36832011a656bb20662f5fa1fc8/msteams-platform%2Fconcepts%2Fbuild-and-test%2FShared-channels.md) | 78 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd761325-7ae9-4f2a-aeae-9fdd34bd6277) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb793186e1eca36832011a656bb20662f5fa1fc8/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00ce2e00-a81d-40a7-a211-1d200374f703) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb793186e1eca36832011a656bb20662f5fa1fc8/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9c64862-e1ab-4fa6-b2b7-ae37ecf6bd22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb793186e1eca36832011a656bb20662f5fa1fc8/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a7228f3-1eb6-4cd7-9409-32c1b8f10259) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c5238e2df19da227be02955369560241b1f8109/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1887e60f-56f0-4b82-b6d9-0fe5dcb0d3a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/Shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c5238e2df19da227be02955369560241b1f8109/msteams-platform%2Fconcepts%2Fbuild-and-test%2FShared-channels.md) | 83 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4ff48be-ab0d-4b35-bdf0-b45de9f4535b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c5238e2df19da227be02955369560241b1f8109/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aeb0fba4-131e-44bf-a17a-9c8740355b98) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c5238e2df19da227be02955369560241b1f8109/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a390044c-be3b-4e8e-a0d8-c94e71af47d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c5238e2df19da227be02955369560241b1f8109/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed6d26fc-463e-42d8-873b-8fe28f55fc0c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4674f054e35018461eb7e94dc9b73bdfe88e2416/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36b29bb4-d607-438d-bc0f-81617a64edc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/Shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4674f054e35018461eb7e94dc9b73bdfe88e2416/msteams-platform%2Fconcepts%2Fbuild-and-test%2FShared-channels.md) | 83 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/181e68c5-f892-47ec-8c22-32bc1a0cad8c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4674f054e35018461eb7e94dc9b73bdfe88e2416/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f20808a3-ff75-4dd3-b2a0-fda881333bee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4674f054e35018461eb7e94dc9b73bdfe88e2416/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bb11390-8a70-47b9-999e-dfd5338a6665) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4674f054e35018461eb7e94dc9b73bdfe88e2416/msteams-platform%2Fwhats-new.md) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b358feb8-fdb6-47e7-848b-9945c7077dab) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by surbhigupta12** [comment]
Duplicate of PR #3828

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c48f87778b5b7082d1632b9fa1e5a7f894f4e367/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/480ca248-9970-48a3-b01d-3394ab476a80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/Shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c48f87778b5b7082d1632b9fa1e5a7f894f4e367/msteams-platform%2Fconcepts%2Fbuild-and-test%2FShared-channels.md) | 83 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a80e660-82bf-4f24-aed8-141147ed755c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c48f87778b5b7082d1632b9fa1e5a7f894f4e367/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 89 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc9dfb74-0b43-459c-83be-e28dc1398d3e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c48f87778b5b7082d1632b9fa1e5a7f894f4e367/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d416f9a-8416-40a6-a1b3-2aecac2575be) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by joeyglocke** [comment]
approved

**Review by joeyglocke — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c11cd9862c116ab22c5e19c281d87c154fc23cc7/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45227284-ad75-4148-a053-3ccb44158649) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/Shared-channels.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c11cd9862c116ab22c5e19c281d87c154fc23cc7/msteams-platform%2Fconcepts%2Fbuild-and-test%2FShared-channels.md) | 83 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88326eb2-3404-4e6e-9cb5-f318391017c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c11cd9862c116ab22c5e19c281d87c154fc23cc7/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 89 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b30eedf-b789-4b24-bf8a-0fba3978f483) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c11cd9862c116ab22c5e19c281d87c154fc23cc7/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/416b9edc-7208-422b-9803-5b0a92ab5b9b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-abirade** [comment]
The content has been merged with PR #6502

**Pull request closed without merging**
