### PR TITLE
[Doc Improvement][SBS Messaging extension action commands]

### PR DESCRIPTION
**Pull request by v-bdeepa**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/81b6ce04c8ee18deb217779e3365dfb701cc4e7e/msteams-platform/sbs-messagingextension-actioncommands.yml) | 85 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f8a9ab8-416a-49dc-92ae-dab38fa66616) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33a5c2e22fbfa74f109ca680a7cc9271db937b42/msteams-platform/sbs-messagingextension-actioncommands.yml) | 85 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ec016e2-a0ec-4dfb-97e8-cd6ccbd98d8d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2b4953b161e9372f0a1f80e60b2d0c1a839ea8e1/msteams-platform/sbs-messagingextension-actioncommands.yml) | 85 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6258fbcd-3c29-4151-bbbd-65c558f1ebcd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7d84ae4ad7d15cd0860b2d313fea773cdc17242d/msteams-platform/sbs-messagingextension-actioncommands.yml) | 85 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9738bca-bb4f-4cc6-9b17-aa100cafb2b0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/161f72c7b67bb99450f7e34c1f1a59baad958bcf/msteams-platform/sbs-messagingextension-actioncommands.yml) | 85 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f0d2c51-a3b9-42ed-8ac2-68fea4c9376e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/604fc3fa6386cde778cb3184189d52548c058238/msteams-platform/sbs-messagingextension-actioncommands.yml) | 85 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9197dbc-c8ac-4e15-9dea-0f211bbfab9a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/72f2712cb4b5dcc8162b279405794ceceffa8add/msteams-platform/sbs-messagingextension-actioncommands.yml) | 85 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aed60506-3315-4c71-91a8-80e73c019a47) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.md](https://github.com/MicrosoftDocs/msteams-docs/blob/85900965963b6173f03831f83579530951029b09/msteams-platform/sbs-messagingextension-actioncommands.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f56ae82b-a713-4f16-8ee5-e5823a28b78c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-actioncommands.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/85900965963b6173f03831f83579530951029b09/msteams-platform/sbs-messagingextension-actioncommands.yml) | 85 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84f6f824-1d4f-40e5-a9c7-22d4c5f0c9d6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d0181d7999efacd9407514c931c837336ab5088e/msteams-platform/sbs-messagingextension-actioncommands.md) | 96 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69b9e074-089a-412a-8958-7cb4c76328fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-actioncommands.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d0181d7999efacd9407514c931c837336ab5088e/msteams-platform/sbs-messagingextension-actioncommands.yml) | 85 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7402963-1bb0-41a4-9f2e-8eaf0e941ca4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95941ec90ef245298ad00d23b2559b0b9b0b717b/msteams-platform/sbs-messagingextension-actioncommands.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad01adfc-1de0-4643-8e99-b9ec5795cc1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-actioncommands.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/95941ec90ef245298ad00d23b2559b0b9b0b717b/msteams-platform/sbs-messagingextension-actioncommands.yml) | 85 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c5f1861-713a-42d2-a799-643596246f4b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58ffbad186964472c7739cd76b599122a8e37c3c/msteams-platform/sbs-messagingextension-actioncommands.md) | 97 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73ac866d-717f-43c9-b8c1-71073a6b56b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-actioncommands.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/58ffbad186964472c7739cd76b599122a8e37c3c/msteams-platform/sbs-messagingextension-actioncommands.yml) | 85 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/966213b5-3d25-432a-9e58-09df6a19db91) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d78796fa7c424e8eddf4971bcc866e8afef07dac/msteams-platform/sbs-messagingextension-actioncommands.md) | 97 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d481da9-dd3b-46f2-91c8-ab2434955887) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-actioncommands.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d78796fa7c424e8eddf4971bcc866e8afef07dac/msteams-platform/sbs-messagingextension-actioncommands.yml) | 85 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d332096c-e9eb-4d10-bd26-6131ba3053a4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aab2eccb7086c25e534127dbc00d3252ff6fed9f/msteams-platform/sbs-messagingextension-actioncommands.md) | 97 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c843c4f-aab9-4d26-8594-d15cf8850437) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.md](https://github.com/MicrosoftDocs/msteams-docs/blob/920f4847e0f797a4a8098f472becb5b2d60bb5fe/msteams-platform/sbs-messagingextension-actioncommands.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a675488-150c-4a41-a8ed-9aa2a030d88c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d3e9e3d172c4367695d871eb485d25a67069b35/msteams-platform/sbs-messagingextension-actioncommands.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bab94fa-f802-45eb-b729-9b4f50e0cade) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e68442eb3b7a0c44a56e89e6e14d17b96858ced4/msteams-platform/sbs-messagingextension-actioncommands.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3db97ad-f58b-496a-9305-7b0d9d7f6758) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.md](https://github.com/MicrosoftDocs/msteams-docs/blob/63f5aecef29fa58ac24645b20230c4f84c1e0449/msteams-platform/sbs-messagingextension-actioncommands.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/929c05d3-ec2a-4ee1-b5b2-cc01f40d32c9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.md](https://github.com/MicrosoftDocs/msteams-docs/blob/26e7cb2352b07192de59dc2970edff722167baf1/msteams-platform/sbs-messagingextension-actioncommands.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6200f6a0-9552-4fe1-b3dc-da7a518ff759) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextensionaction.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/26e7cb2352b07192de59dc2970edff722167baf1/msteams-platform/sbs-messagingextensionaction.yml) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebef7ca5a69e93e1f1d9657f5ac2f8e9642db630/msteams-platform/sbs-messagingextension-actioncommands.md) | 96 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e092696-36ed-40e6-8169-d183c8d240c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextensionaction.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ebef7ca5a69e93e1f1d9657f5ac2f8e9642db630/msteams-platform/sbs-messagingextensionaction.yml) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8534b358-715a-463f-b656-aa1c1557bc08) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd1b21acd09ccdc828db68780ed9372264d932a3/msteams-platform/sbs-messagingextension-actioncommands.md) | 95 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c04ae7a-23f7-4725-a35f-ffb74e7429d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextensionaction.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bd1b21acd09ccdc828db68780ed9372264d932a3/msteams-platform/sbs-messagingextensionaction.yml) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe6c5842-5788-4272-818c-8925613d0474) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextensionaction.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/861411fe1a911af30b40bacf3a7a5e7ff5da4abb/msteams-platform/sbs-messagingextensionaction.yml) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4e7b047-6180-4fe8-9255-53086c5433b9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextensionaction.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/861411fe1a911af30b40bacf3a7a5e7ff5da4abb/msteams-platform/sbs-messagingextensionaction.yml) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ef61aca-7f03-48a1-9dd9-9db8b5d316fc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextensionaction.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1d102ef04cc7bbf7d19ad7a1ca9b94fb3732d5fd/msteams-platform/sbs-messagingextensionaction.yml) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4b99249-0365-4917-b0b9-314fa93bd772) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextensionaction.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bfa00e41a79c7aa2aff467034c0f42f5a72198b8/msteams-platform/sbs-messagingextensionaction.yml) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a090190-742a-452f-a03e-0804d66f7abd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextension-actioncommands.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee33a843dc86f67c58ad2c34f26b97db0cfe680e/msteams-platform/sbs-messagingextension-actioncommands.md) | 95 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/031b467d-0a9e-4f7b-96bb-f1f8de269d39) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextensionaction.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ee33a843dc86f67c58ad2c34f26b97db0cfe680e/msteams-platform/sbs-messagingextensionaction.yml) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b57a821-3909-4c0a-913e-dd7a466f7d21) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-messagingextensionaction.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0def41a14fd4d05d5f3e0f6771e60e9518b4965d/msteams-platform/sbs-messagingextensionaction.yml) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2f81ff3-fa5b-497d-bae5-93fbacd26e2c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-bdeepa** [comment]
Closing the PR as outdated.

**Pull request closed without merging**
