### PR TITLE
[Doc Improvement][Correct errors, resize images in M365 content][3633732]

### PR DESCRIPTION
**Pull request by erikadoyle**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4aa83281fceabd0420465f9045692c080898d4e2/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a8ee139-3dab-4513-9c49-d59eb713bd23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4aa83281fceabd0420465f9045692c080898d4e2/msteams-platform%2Fm365-apps%2Foverview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2f62a09-07c2-4e07-857d-565db775f6e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4aa83281fceabd0420465f9045692c080898d4e2/msteams-platform%2Fm365-apps%2Fpublish.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/201e3f64-126f-4886-8a3e-1dfee9f211de) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-vanv — CHANGES_REQUESTED** [review]
msteams-platform/m365-apps/images/outlook-mobile-android-more.png - Reduce the resolution of the image.

microsoftteams/platform/m365-apps/images/outlook-desktop-more-apps.png - Reduce the resolution of the image.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d25b3226eb029e8b8eb0d531c5c20ce947922b91/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08fdfda4-248a-4c04-b942-dd8eebbb52b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d25b3226eb029e8b8eb0d531c5c20ce947922b91/msteams-platform%2Fm365-apps%2Foverview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18fcf9a0-7e30-4fe6-9d7e-4474fe795bf1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d25b3226eb029e8b8eb0d531c5c20ce947922b91/msteams-platform%2Fm365-apps%2Fpublish.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03eb23ec-4918-4fe9-aa57-d549707fa7b5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2832bfe8bc1395d8eba53523284c44bb8a6f4edd/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12bf55f2-7d14-4984-b248-78813998f87b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2832bfe8bc1395d8eba53523284c44bb8a6f4edd/msteams-platform%2Fm365-apps%2Foverview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1523cf6-f10a-45f2-9e95-926fdee06cb1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2832bfe8bc1395d8eba53523284c44bb8a6f4edd/msteams-platform%2Fm365-apps%2Fpublish.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8825a71-4b74-4e26-80ee-a267edba22f7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5fbe49a83b82d3ddb58d3a3ba2fce5975619d34/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/daa2a5be-52c7-436c-af79-ca24c39bcf86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5fbe49a83b82d3ddb58d3a3ba2fce5975619d34/msteams-platform%2Fm365-apps%2Foverview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4200671c-ec8f-4be8-a344-85b89a0c7d34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5fbe49a83b82d3ddb58d3a3ba2fce5975619d34/msteams-platform%2Fm365-apps%2Fpublish.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b22d261f-ee26-4764-9006-242208a50264) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5fbe49a83b82d3ddb58d3a3ba2fce5975619d34/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79b71bcd-c930-4127-94a7-986ce8eb4315) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5fbe49a83b82d3ddb58d3a3ba2fce5975619d34/msteams-platform%2Fm365-apps%2Foverview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/031481c5-5839-41b6-8a7a-71ed66cf6cdb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b5fbe49a83b82d3ddb58d3a3ba2fce5975619d34/msteams-platform%2Fm365-apps%2Fpublish.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83fcadbe-2b0e-4d79-8660-a5c2a3fbb847) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1cd9adc601c65af0c47aeb013ba1db790bf64f5/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa82e88e-1d1a-4b65-b218-4b8a9b2970ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1cd9adc601c65af0c47aeb013ba1db790bf64f5/msteams-platform%2Fm365-apps%2Foverview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12f52da2-6398-44f8-8e70-93eedfa55699) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1cd9adc601c65af0c47aeb013ba1db790bf64f5/msteams-platform%2Fm365-apps%2Fpublish.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aaed0758-45eb-4832-8da0-20ee65016eb2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3a74cd587ebb60f4c79d808a9923e0a5197f34de/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ac59451-b6cb-4a0a-90ba-7399d00d311f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3a74cd587ebb60f4c79d808a9923e0a5197f34de/msteams-platform%2Fm365-apps%2Foverview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/094c939e-a5e7-4024-b851-75038b5dd47b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3a74cd587ebb60f4c79d808a9923e0a5197f34de/msteams-platform%2Fm365-apps%2Fpublish.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b0b410e-4cd6-4f49-a6a5-4ba76dab445f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-vanv — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
