### PR TITLE
[Doc Improvement][Update custom copilots][3803712]

### PR DESCRIPTION
**Pull request by v-ganr**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4027d602c191600e29048f106de1f3b5736ead46/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b553d07f-62a1-43d9-95b2-e4cf7580d112) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-a-basic-AI-chatbot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4027d602c191600e29048f106de1f3b5736ead46/msteams-platform%2Ftoolkit%2Fbuild-a-basic-AI-chatbot-in-teams.md) | 95 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c2ee39d-0c5a-4c28-9ee3-6c4501185f89) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-an-AI-agent-in-Teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4027d602c191600e29048f106de1f3b5736ead46/msteams-platform%2Ftoolkit%2Fbuild-an-AI-agent-in-Teams.md) | 93 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b37c854e-8b7d-460f-9250-4269d5d6b597) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a911e1ef2c122d5fb31597b4c2a2cdc3c21d49b/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3ed5eb0-60f9-4c98-bcbc-9f05ef551546) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-a-basic-AI-chatbot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a911e1ef2c122d5fb31597b4c2a2cdc3c21d49b/msteams-platform%2Ftoolkit%2Fbuild-a-basic-AI-chatbot-in-teams.md) | 95 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e221299-5b93-483d-8246-4ad7c4996a29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-an-AI-agent-in-Teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a911e1ef2c122d5fb31597b4c2a2cdc3c21d49b/msteams-platform%2Ftoolkit%2Fbuild-an-AI-agent-in-Teams.md) | 93 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/371d3dfa-6105-4819-81f2-282225057a60) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86d8996a6678587be9686ea337998d4ce4c50d54/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/713ba16b-29ae-464b-bf0b-9dc2bc84671f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-a-basic-AI-chatbot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86d8996a6678587be9686ea337998d4ce4c50d54/msteams-platform%2Ftoolkit%2Fbuild-a-basic-AI-chatbot-in-teams.md) | 95 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0609ba02-8116-40c9-9eec-848dbd137610) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-an-AI-agent-in-Teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86d8996a6678587be9686ea337998d4ce4c50d54/msteams-platform%2Ftoolkit%2Fbuild-an-AI-agent-in-Teams.md) | 93 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dff14cdd-1795-4db6-80d7-9e1ad6334851) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/22d2d1ffa43a21a69b62bc6008229e6ca4b5f164/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ee61191-e5f4-40a0-9c37-8bb1aaf48084) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-a-basic-AI-chatbot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/22d2d1ffa43a21a69b62bc6008229e6ca4b5f164/msteams-platform%2Ftoolkit%2Fbuild-a-basic-AI-chatbot-in-teams.md) | 95 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e05b099-7885-467d-98d4-b70c240223ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-an-AI-agent-in-Teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/22d2d1ffa43a21a69b62bc6008229e6ca4b5f164/msteams-platform%2Ftoolkit%2Fbuild-an-AI-agent-in-Teams.md) | 93 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b29b7b45-5fe7-47c7-9c48-14e776c6b1a6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
