### PR TITLE
[doc-enhancement][Delete obsolete files]

### PR DESCRIPTION
**Pull request by v-shalinirobinson**
Deleted:
1. /resources/m365-plugins/openid-connect.md
2. /resources/getting-help.md

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4e951a5698bd01512dcb00923a6ca7f300ba1ad2/msteams-platform%2Fsbs-gs-javascript.yml) | 93 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5063e7de-7a40-45ac-b346-33431b9f5fd0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/partner-apps-for-moodle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06e27162a8858fff893c12149dfcb02e41bb752e/msteams-platform%2Fresources%2Fpartner-apps-for-moodle.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37a59d79-0e62-4db2-a127-4285f164f69c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/06e27162a8858fff893c12149dfcb02e41bb752e/msteams-platform%2Fsbs-gs-javascript.yml) | 93 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4ae4085-7ad4-44b7-8d1e-1c44c4883884) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3761ca5faba3d4b4f676369e85d417d864a3f121/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bdcd5031-6edc-49a1-a073-7caa67230b7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3761ca5faba3d4b4f676369e85d417d864a3f121/msteams-platform%2Fget-started%2Fget-started-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2ab85be-c887-4cac-94a3-8862b45eb49a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3761ca5faba3d4b4f676369e85d417d864a3f121/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fa023e5-0896-4c5e-b559-c173d462687e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/partner-apps-for-moodle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3761ca5faba3d4b4f676369e85d417d864a3f121/msteams-platform%2Fresources%2Fpartner-apps-for-moodle.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75583d92-a571-4834-88ef-d421ad433d60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-blazor.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3761ca5faba3d4b4f676369e85d417d864a3f121/msteams-platform%2Fsbs-gs-blazor.yml) | 96 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20540949-003d-40e1-ab15-3a9c7da624bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3761ca5faba3d4b4f676369e85d417d864a3f121/msteams-platform%2Fsbs-gs-javascript.yml) | 93 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23c13798-3107-4a8a-a112-31fb308fac5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3761ca5faba3d4b4f676369e85d417d864a3f121/msteams-platform%2Fwhats-new.md) | 93 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72250cf5-7b83-4590-8f9f-0b294686802d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/601d82086e8a44fa5621da93145eecac69ef743b/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be64e645-589b-42f0-aaea-9f7086786af1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/601d82086e8a44fa5621da93145eecac69ef743b/msteams-platform%2Fget-started%2Fget-started-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82611420-e691-4de2-9b79-f1eba75dfa1f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/partner-apps-for-moodle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/601d82086e8a44fa5621da93145eecac69ef743b/msteams-platform%2Fresources%2Fpartner-apps-for-moodle.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1d78775-a7fe-4dbd-9dd9-0d5046aa3f6d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/601d82086e8a44fa5621da93145eecac69ef743b/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 96 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc2d56e6-3497-4558-8d94-2db95dad8c4e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/601d82086e8a44fa5621da93145eecac69ef743b/msteams-platform%2Fsbs-gs-javascript.yml) | 93 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d0abf57-c83a-494d-8549-51284fd17997) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/601d82086e8a44fa5621da93145eecac69ef743b/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f79c96f7-594c-4fac-b1a9-e47e1f32b1e7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/abe3d267d29ea1dbfdb6743f3fadf907e54ad1b7/msteams-platform%2FTOC.yml) | 98 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb7e9c0c-79b4-4410-ada7-258a9dda87a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abe3d267d29ea1dbfdb6743f3fadf907e54ad1b7/msteams-platform%2Fget-started%2Fget-started-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/020d7cd2-7db4-4261-ad3a-23346e8b9110) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/abe3d267d29ea1dbfdb6743f3fadf907e54ad1b7/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/886583d5-076d-49d3-ad06-7a04190a229d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/partner-apps-for-moodle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abe3d267d29ea1dbfdb6743f3fadf907e54ad1b7/msteams-platform%2Fresources%2Fpartner-apps-for-moodle.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eabc8cbb-5a23-4d51-80ed-3b523c996dc8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-blazorupdate.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/abe3d267d29ea1dbfdb6743f3fadf907e54ad1b7/msteams-platform%2Fsbs-gs-blazorupdate.yml) | 96 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/023cde56-d59a-44b8-882d-590e4624615c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/abe3d267d29ea1dbfdb6743f3fadf907e54ad1b7/msteams-platform%2Fsbs-gs-javascript.yml) | 93 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83326c9f-12b2-4b92-86c5-b7a7266e772d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abe3d267d29ea1dbfdb6743f3fadf907e54ad1b7/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b961ca57-d0dc-40c4-b84f-81d737cc10d9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
