### PR TITLE
[Doc Improvement][Update links in Tools and SDK for Visual Studio]

### PR DESCRIPTION
**Pull request by v-ksar**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/21ce85c411fb4ba10359f0755cc6a7d66fc9a33b/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55be8a60-7094-43ca-b8b3-9992c8a6ff0a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/03e3d18873720b622f0cb8126a21a071bfeeebce/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e03e4c0a-2542-4124-b5cb-953dfb17942c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ad7e45225910e8852a37313af0c1227283c42016/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b718e1c-54d9-4655-9661-3019e9cdfc4d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8f998d9b9a4ee3acfbe7504d9c9e710afe2d530b/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc42c200-8d77-4a3f-a04b-9a5b403f6823) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2ca70960d22a6ef28965e5a9776c184428efa341/msteams-platform%2FTOC.yml) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/074d2aa1-e92d-4f3b-b79d-4e2698ad1ad2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2ca70960d22a6ef28965e5a9776c184428efa341/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5fcb711f-6e51-424e-96ad-e930b764fdae) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f72a0ca58e2c9a4f61384d143400c28df62887c0/msteams-platform%2FTOC.yml) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f412b6a3-d0fe-40b3-84ae-9d27ed30796a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f72a0ca58e2c9a4f61384d143400c28df62887c0/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f20f4d28-03ad-4431-9dd1-0487695b2faf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c5fcb4580f06485c79826d9a59544a5d7b0ddbbe/msteams-platform%2FTOC.yml) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d99826f-b79a-4cc5-9833-fd8e0b78d1c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c5fcb4580f06485c79826d9a59544a5d7b0ddbbe/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/462bb08b-ffda-4e8e-903d-87693b69a15b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c5fcb4580f06485c79826d9a59544a5d7b0ddbbe/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1aebde8-50d1-4f30-bab5-de1732253cc5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-overview-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c5fcb4580f06485c79826d9a59544a5d7b0ddbbe/msteams-platform%2Ftoolkit%2Fteams-toolkit-overview-visual-studio.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2216c7bf-100f-40dc-8b69-58706a3d5fd2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c5fcb4580f06485c79826d9a59544a5d7b0ddbbe/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f30a9d4-47b8-4412-80b7-abb8d3fc6422) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e0f0be7b3e08cc59c1e29150f8f43554811cb7fb/msteams-platform%2FTOC.yml) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc3443dc-b308-4751-8e90-391d428b985c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e0f0be7b3e08cc59c1e29150f8f43554811cb7fb/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af1f3382-95d3-48cb-9f4f-a65a505dde74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e0f0be7b3e08cc59c1e29150f8f43554811cb7fb/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/209a9c4b-276d-457a-94be-44f6aba4c805) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Provision cloud resources using Visual Studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0f0be7b3e08cc59c1e29150f8f43554811cb7fb/msteams-platform%2Ftoolkit%2FProvision%20cloud%20resources%20using%20Visual%20Studio.md) | 97 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd7d00ff-d23a-41a0-9635-c3c81246f1d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-teams-app-for-Visual-Studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0f0be7b3e08cc59c1e29150f8f43554811cb7fb/msteams-platform%2Ftoolkit%2Fcreate-new-teams-app-for-Visual-Studio.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db54aeb7-749c-40e4-bb7c-42615965e820) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-teams-app-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0f0be7b3e08cc59c1e29150f8f43554811cb7fb/msteams-platform%2Ftoolkit%2Fdebug-teams-app-visual-studio.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd346ba8-e171-4910-989d-aa50159e8a0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-overview-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0f0be7b3e08cc59c1e29150f8f43554811cb7fb/msteams-platform%2Ftoolkit%2Fteams-toolkit-overview-visual-studio.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5dad31cf-3b16-4b95-acf2-7bca303a0db0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0f0be7b3e08cc59c1e29150f8f43554811cb7fb/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7724a4b-7ccf-4b7d-b358-3ac14df13397) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e5ee016b93bbb5ef620cbbc006bac25346dee9cd/msteams-platform%2FTOC.yml) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8c9441e-3075-46fd-b15a-a8bf1b5d347f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e5ee016b93bbb5ef620cbbc006bac25346dee9cd/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33d9bb52-d0e4-4c15-84a2-0b1ee5aaccc0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e5ee016b93bbb5ef620cbbc006bac25346dee9cd/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b700826f-4a55-480c-92a4-f4657e247c69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Deploy Teams app to the cloud using Visual Studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5ee016b93bbb5ef620cbbc006bac25346dee9cd/msteams-platform%2Ftoolkit%2FDeploy%20Teams%20app%20to%20the%20cloud%20using%20Visual%20Studio.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63089cb1-544a-45ab-b1db-44a5f45f1d82) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Provision cloud resources using Visual Studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5ee016b93bbb5ef620cbbc006bac25346dee9cd/msteams-platform%2Ftoolkit%2FProvision%20cloud%20resources%20using%20Visual%20Studio.md) | 97 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8df26d1-4314-48ec-ab8a-38b59e6caf37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/VS-TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5ee016b93bbb5ef620cbbc006bac25346dee9cd/msteams-platform%2Ftoolkit%2FVS-TeamsFx-preview-and-customize-app-manifest.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d2ccfcf-e2a7-4a28-ac93-579f13b29965) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-teams-app-for-Visual-Studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5ee016b93bbb5ef620cbbc006bac25346dee9cd/msteams-platform%2Ftoolkit%2Fcreate-new-teams-app-for-Visual-Studio.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1835f3a7-91cf-4ce3-8b8f-a08e686554a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-teams-app-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5ee016b93bbb5ef620cbbc006bac25346dee9cd/msteams-platform%2Ftoolkit%2Fdebug-teams-app-visual-studio.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ef4579b-0cd7-4981-a91d-f7956b96b466) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-overview-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5ee016b93bbb5ef620cbbc006bac25346dee9cd/msteams-platform%2Ftoolkit%2Fteams-toolkit-overview-visual-studio.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8d01a2a-8980-4915-b717-35d9f9d70b8c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5ee016b93bbb5ef620cbbc006bac25346dee9cd/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0acded49-5d8b-48bd-94f4-44e4e5645931) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e1b9435d7563ec01368f40663696714709b6617f/msteams-platform%2FTOC.yml) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58d7bb67-8a93-4b2f-8884-131800410370) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e1b9435d7563ec01368f40663696714709b6617f/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e0246ac-cb4c-4dae-957d-6b3e14be91c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e1b9435d7563ec01368f40663696714709b6617f/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5a39af1-1a73-463c-b777-4975a47616e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Deploy Teams app to the cloud using Visual Studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1b9435d7563ec01368f40663696714709b6617f/msteams-platform%2Ftoolkit%2FDeploy%20Teams%20app%20to%20the%20cloud%20using%20Visual%20Studio.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55caec48-7ad6-4ba6-879e-3cc29239e75f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Provision cloud resources using Visual Studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1b9435d7563ec01368f40663696714709b6617f/msteams-platform%2Ftoolkit%2FProvision%20cloud%20resources%20using%20Visual%20Studio.md) | 97 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a13bb1fe-38d5-454e-98d1-64b0ab4a2d70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/VS-TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1b9435d7563ec01368f40663696714709b6617f/msteams-platform%2Ftoolkit%2FVS-TeamsFx-preview-and-customize-app-manifest.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fea6347a-c018-4c56-b890-d6829489615d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-teams-app-for-Visual-Studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1b9435d7563ec01368f40663696714709b6617f/msteams-platform%2Ftoolkit%2Fcreate-new-teams-app-for-Visual-Studio.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a125580-6054-4399-bee0-9dbec9a2122d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-teams-app-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1b9435d7563ec01368f40663696714709b6617f/msteams-platform%2Ftoolkit%2Fdebug-teams-app-visual-studio.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f153addd-1a2d-41e7-97af-deb2369e909b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-overview-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1b9435d7563ec01368f40663696714709b6617f/msteams-platform%2Ftoolkit%2Fteams-toolkit-overview-visual-studio.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8306248a-1ba4-4e81-b189-f3de15c79f1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1b9435d7563ec01368f40663696714709b6617f/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04154d22-ef81-45f2-8a5d-d4b8438c97b0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
