### PR TITLE
[Doc Improvement] [Duplicate images removed ph5]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6adf9aa5e682bae955405e201e1641fe276a12c6/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 83 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86bda27c-d7f7-40af-84a9-92a79d106249) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6adf9aa5e682bae955405e201e1641fe276a12c6/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1b642c2-e024-4bcf-868b-337c94bad422) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6adf9aa5e682bae955405e201e1641fe276a12c6/msteams-platform%2Fsbs-meetingextension-action.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bdad849e-f545-478b-9491-ff0f3bea25dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6adf9aa5e682bae955405e201e1641fe276a12c6/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd846efd-1996-462a-bb5b-e8eaec8252d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6adf9aa5e682bae955405e201e1641fe276a12c6/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b19f6e5d-ae93-493a-92b3-1640c4051122) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2120809ee73cda233b839d6d67553ebea2bdc046/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 83 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d48d686-07b0-49ea-8b02-5f549565be86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2120809ee73cda233b839d6d67553ebea2bdc046/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13c08254-4cb8-434c-8a6a-0be4526d2323) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2120809ee73cda233b839d6d67553ebea2bdc046/msteams-platform%2Fsbs-meetingextension-action.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2166d541-9013-439f-9b35-d08136fe9033) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2120809ee73cda233b839d6d67553ebea2bdc046/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96cda755-3b41-478c-8a3b-e1979c86f51d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2120809ee73cda233b839d6d67553ebea2bdc046/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4899d5b9-84b5-4883-b3f4-86b977cd5baf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1434ec666e1e104060399163b4619cd1b2b69c8e/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 83 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e8fee1a-66d3-43a7-93ce-f66c08d4d807) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1434ec666e1e104060399163b4619cd1b2b69c8e/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 83 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00c3b29b-fd0c-4450-aeb9-578eb8fe2962) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1434ec666e1e104060399163b4619cd1b2b69c8e/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20702838-4faf-4d18-a489-25f972559f25) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1434ec666e1e104060399163b4619cd1b2b69c8e/msteams-platform%2Fsbs-meetingextension-action.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/404f23c8-a315-4137-bcac-9bb5d5b49f48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1434ec666e1e104060399163b4619cd1b2b69c8e/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/701bc32c-ecbf-489e-b905-0a707eeb4d30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1434ec666e1e104060399163b4619cd1b2b69c8e/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c4cd8f9-a2b5-43d7-b727-889194fe3a0d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by ashishguptaiitb** [comment]
The image `selectscope.png` has 3-4 dupes. Please remove.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2858ef8ac62ef44dcea84b3705f602e34c50b238/msteams-platform%2Fsbs-meetingextension-action.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/736d9ae6-7203-4682-a9fc-a0b9b5f3dff8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2858ef8ac62ef44dcea84b3705f602e34c50b238/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10d8d212-2935-4be0-a56e-34307fbcdc4f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d85531cadb346e588fd139c985a738694c959aa4/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 83 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3bc1c43-850e-4f9b-8aa6-2d059693c719) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d85531cadb346e588fd139c985a738694c959aa4/msteams-platform%2Fsbs-meeting-token-generator.yml) | 88 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a164852e-879f-47cf-b370-8d77928af238) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d85531cadb346e588fd139c985a738694c959aa4/msteams-platform%2Fsbs-meetingextension-action.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/881ce615-89f7-4d2e-9021-38713ef9c24d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d85531cadb346e588fd139c985a738694c959aa4/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b5684d1-94c9-4f5f-93f8-d6f2f9b80f0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d85531cadb346e588fd139c985a738694c959aa4/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/082268fc-8fd6-4131-9421-edd2439cb401) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-sdhakshina** [comment]
@ashishguptaiitb 

Conflicts are resolved. Duplicate image "selectscope.png" removed.

**Review by ashishguptaiitb — APPROVED** [review]

**Pull request merged**
