### PR TITLE
Update docfx.json

### PR DESCRIPTION
**Pull request by lindalu-MSFT**
UHFHeaderId had a typo, lower case d

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[22652f7](https://github.com/MicrosoftDocs/msteams-docs/pull/485/commits/22652f746f0595675d0b5e0cf5addf40a4abc6e1)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[22652f7](https://github.com/MicrosoftDocs/msteams-docs/pull/485/commits/22652f746f0595675d0b5e0cf5addf40a4abc6e1)_: 

:clock10: **Full build**: average full build time is _28 sec(s)_ [calculated from last _3_ build(s)]

> Note: A full build takes more time than an incremental build. This is the expected behavior of the build system.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[22652f7](https://github.com/MicrosoftDocs/msteams-docs/pull/485/commits/22652f746f0595675d0b5e0cf5addf40a4abc6e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/docfx.json](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-2/msteams-platform/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903052212097082-485%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=eg3SJhV2vZnlNEDVNu1YGI6vje1%2Bv%2FMZ55KuraeSpzQ%3D&st=2019-03-05T22%3A08%3A39Z&se=2019-04-05T22%3A13%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@clearab Can you merge this so we can verify?

**Comment by clearab** [comment]
This doesn't render any header at all:

https://review.docs.microsoft.com/en-us/microsoftteams/platform/overview?branch=lindalu-MSFT-patch-2

I've opened a conversation with the docs folks on Teams and cc'd you. 
https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1551823654560?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1551823654560&teamName=Docs%20Support&channelName=General&createdTime=1551823654560

The header you're trying to reference doesn't appear to work with docs.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[e37b603](https://github.com/MicrosoftDocs/msteams-docs/pull/485/commits/e37b603b5e71ca5763d723266bd88252bc317c8b)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[e37b603](https://github.com/MicrosoftDocs/msteams-docs/pull/485/commits/e37b603b5e71ca5763d723266bd88252bc317c8b)_: 

:clock10: **Full build**: average full build time is _32 sec(s)_ [calculated from last _4_ build(s)]

> Note: A full build takes more time than an incremental build. This is the expected behavior of the build system.

**Comment by lindalu-MSFT** [comment]
@clearab Andrew, Arvind suggested we try the global office header to be sure that works. WE know it works on other Docs docsets. Can you try this one?

**Comment by o365devx** [comment]
OPS Build status updates of commit _[e37b603](https://github.com/MicrosoftDocs/msteams-docs/pull/485/commits/e37b603b5e71ca5763d723266bd88252bc317c8b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/docfx.json](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-2/msteams-platform/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903052224564056-485%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=L6dTxia6NpvTJj1hxV%2BQUa%2BJlHl9rI%2FIDvMwHGFBoXo%3D&st=2019-03-05T22%3A21%3A10Z&se=2019-04-05T22%3A26%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[21f16b7](https://github.com/MicrosoftDocs/msteams-docs/pull/485/commits/21f16b7aae0e7237b7acd14fe062b6379e775f57)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[21f16b7](https://github.com/MicrosoftDocs/msteams-docs/pull/485/commits/21f16b7aae0e7237b7acd14fe062b6379e775f57)_: 

:clock10: **Full build**: average full build time is _28 sec(s)_ [calculated from last _5_ build(s)]

> Note: A full build takes more time than an incremental build. This is the expected behavior of the build system.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[21f16b7](https://github.com/MicrosoftDocs/msteams-docs/pull/485/commits/21f16b7aae0e7237b7acd14fe062b6379e775f57)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/docfx.json](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-2/msteams-platform/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903052228287394-485%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6bIQOkVsCbsS14BoRPDq3soM2chD%2BXzd31vbTqJvm8g%3D&st=2019-03-05T22%3A24%3A56Z&se=2019-04-05T22%3A29%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clearab** [comment]
So the OfficeDev:
image

Or existing TeamsDocs one:
image

I prefer the Office Dev one

**Comment by lindalu-MSFT** [comment]
OK it turns out that I need to submit a bug to CEAPEX to “connect” the DEV_MicrosoftTeams header I created in Compass to the back-end code. Once that’s done, you can use "uhfHeaderId": "MSDocsHeader-Dev_MicrosoftTeams",

So in the meantime, feel free to use "uhfHeaderId": "MSDocsHeader-Dev_Office", so at least Office Dev Center heading appears and not the default Windows header, which is not very useful!

THANKS, and sorry for the churn.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[d26690b](https://github.com/MicrosoftDocs/msteams-docs/pull/485/commits/d26690bda1066c2f9776b67d07af1249ce230ef1)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[d26690b](https://github.com/MicrosoftDocs/msteams-docs/pull/485/commits/d26690bda1066c2f9776b67d07af1249ce230ef1)_: 

:clock10: **Full build**: average full build time is _32 sec(s)_ [calculated from last _6_ build(s)]

> Note: A full build takes more time than an incremental build. This is the expected behavior of the build system.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[d26690b](https://github.com/MicrosoftDocs/msteams-docs/pull/485/commits/d26690bda1066c2f9776b67d07af1249ce230ef1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/docfx.json](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-2/msteams-platform/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903052247538411-485%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2gjt7QTMtpJUav6izs7GV2aGhb8LdcIRqBC0SasZ5kg%3D&st=2019-03-05T22%3A44%3A16Z&se=2019-04-05T22%3A49%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
