### PR TITLE
[Doc Improvement][icons 1]

### PR DESCRIPTION
**Pull request by v-psambrani**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0d5bf3d355ea5dee223b02f1d661a13ea2383ef/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/091408de-bfeb-43ad-a414-e0154be60dd6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b8a667401eb1877d0183f533ac89f27b2f866f48/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 94 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9aa6ab0-20bd-4933-84d4-48f0d660f9cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b8a667401eb1877d0183f533ac89f27b2f866f48/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a8f6f7a-11b1-48d3-b0b9-e08888108ae3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01c471bf7f062e905aecd010d7e4ea9d025d7ac3/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 94 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4799826f-d538-401f-8692-a5edd4512896) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01c471bf7f062e905aecd010d7e4ea9d025d7ac3/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05bf009e-88df-44a0-a784-126653943325) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da873b7b-8dee-446a-84fa-8cfae190f864) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 94 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddcbaff3-11da-4ce3-8eea-b96ab98c3776) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34edf2e7-d187-49de-8561-51ba3fcfe4d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2fb5de0-4b7f-4995-9077-a0365453e174) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fapps-in-teams-meetings%2Fteams-together-mode.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0aca85e6-bf5a-4386-84fa-433c3dcacd9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/call-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcall-notifications.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd86953e-94c1-4388-bc33-125a7aaa765c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b887cd5-66fa-4b44-8f99-775b22f37fa4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/real-time-media-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fbots%2Fcalls-and-meetings%2Freal-time-media-concepts.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d666e94-bcfb-41b2-9314-b91d10e84ac1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 95 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba602062-ef3e-4de2-9687-e83e42545fe2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fbots%2Fcalls-and-meetings%2Frequirements-considerations-application-hosted-media-bots.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffd6c280-50ea-4701-b737-882676eedfe8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acaea376-65f1-4c81-93cc-eb3d3f74e8b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3891ab8-f719-4bc0-9a06-18f02dc14bbd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fauth-aad-sso-bots.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/526b38e5-dd52-419a-8af5-19afd1e66ce5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa93841a-dcb4-42e0-b3ff-927b91596192) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af4f3513-8902-43ab-95e1-f96fd924faf2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cda7dcb4-bb94-4efb-beaa-45e654eb6032) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e292700c-8bd8-4e2a-af42-aba6f5beaf5a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/109c5250-8c60-46aa-9267-99b980ea2473) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/debug/locally-with-an-ide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d486de969218dea31a032ebfdde5595cf87eb8c3/msteams-platform%2Fbots%2Fhow-to%2Fdebug%2Flocally-with-an-ide.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d3db4ea-7f03-491c-a495-5a260dd1e3d0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fapps-in-teams-meetings%2FAPI-references.md) | 89 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03235229-c9ac-4794-a847-2b08e9563793) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fapps-in-teams-meetings%2Fdesign%2Fdesigning-apps-in-meetings.md) | 94 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8869075-2160-4544-ac55-9a9847d31faa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-app-extensibility.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-app-extensibility.md) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00bff574-3f83-415e-adcc-ca0d7ef83bb1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-overview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba25e72b-06ef-424e-80ba-430adf30c8c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fapps-in-teams-meetings%2Fteams-together-mode.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81bfd2d6-bb92-4f4b-8293-5438d09efb17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fbot-basics.md) | 88 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e2f952b-6c31-401b-90e6-a59982da9b9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fbot-features.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1c23db8-bccf-4bed-9d4a-16ac34f01d77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/call-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcall-notifications.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83f39b76-94db-41d1-9420-3cfd041d8371) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/edef40a9-2bd8-4ead-ae30-2a37bec76881) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/real-time-media-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fcalls-and-meetings%2Freal-time-media-concepts.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/914d1023-2116-4184-8c3f-512b1ba833ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 95 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58c12550-a840-4af4-97c6-c8f000611227) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/requirements-considerations-application-hosted-media-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fcalls-and-meetings%2Frequirements-considerations-application-hosted-media-bots.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/907bfa95-e281-41cb-96b8-5d4a57e128ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a01f61fd-d50f-4052-8cf5-5ed81da94614) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fhow-to%2Fadd-power-virtual-agents-bot-to-teams.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b08a4bc5-6b02-4a4f-b2b4-df2adc6beee0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f305eaf2-2adf-41e5-ac79-2799b8d8b2dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fauth-aad-sso-bots.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/438c28ab-d3d2-4229-9981-75404ff23f59) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fhow-to%2Fbots-filesv4.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0f47839-8f9d-47fd-9c1c-7220078c96c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84b42f40-3d18-45f6-8472-57d445b07e16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39d648be-5f34-4362-8095-89a64675db4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-basics.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d10e092c-dcec-488b-9c66-d0e34043228f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/001712d9-e996-4b60-af09-b0a12e14b3f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0401df4-dadc-4e2f-b824-d2dde40ef17a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/create-a-bot-commands-menu.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fhow-to%2Fcreate-a-bot-commands-menu.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c05f9d9e-6445-4be8-8ec3-9a176194c1be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/debug/locally-with-an-ide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fhow-to%2Fdebug%2Flocally-with-an-ide.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff08ae2f-575d-45a7-bbc6-7dc79db9abb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fhow-to%2Fget-teams-context.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e4e1d51-3e2a-4b8e-8393-6fd28dbef1eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/rate-limit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fhow-to%2Frate-limit.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2fb766a4-d6ae-4068-a9c6-bc01770df275) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cea9a86af1d7332da8fb55f99e2dfff90371c7c1/msteams-platform%2Fbots%2Fwhat-are-bots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f86ea8d4-7656-433d-b790-a8d3e678e6fd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Pull request closed without merging**
