### PR TITLE
[Doc improvement][SEO Metatitle To be deleted]

### PR DESCRIPTION
**Pull request by v-ramyas5**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1084ff30155a79307c5360cf7ca48695eef20cd2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74dec390-c63d-4e9b-8e03-d1994e898fb9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668e9ed4584030ddab346641eed5e60d43176fc2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83ea508d-c572-4343-9487-be9b8d563e3e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668e9ed4584030ddab346641eed5e60d43176fc2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 128 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6caba1c-f3bc-439d-bb00-19389d4a1c4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/update-apple-store-team-connect-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668e9ed4584030ddab346641eed5e60d43176fc2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fupdate-apple-store-team-connect-id.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b1d3c78-7e09-4dda-87dd-1abd0f893ab1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668e9ed4584030ddab346641eed5e60d43176fc2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/592ed722-4497-479e-ac90-d1d3570d2f23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668e9ed4584030ddab346641eed5e60d43176fc2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fresolve-submission-issues.md) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e243c5a6-8470-49ba-880b-f5eea5190ec6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/app-structure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668e9ed4584030ddab346641eed5e60d43176fc2/msteams-platform%2Fconcepts%2Fdesign%2Fapp-structure.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/559a0b5c-9ee0-4c7f-8646-b15b267b44ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668e9ed4584030ddab346641eed5e60d43176fc2/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-advanced-ui-components.md) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d275f97a-0445-4ddd-8cef-3144ffca8bc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-artwork-store.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668e9ed4584030ddab346641eed5e60d43176fc2/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-artwork-store.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b419660-4bed-4022-8f3a-55987d19be8e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-basic-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668e9ed4584030ddab346641eed5e60d43176fc2/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-basic-ui-components.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d0b2a37-fa1d-454b-bdd3-bb077ad50b9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-icon-store-appbar.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668e9ed4584030ddab346641eed5e60d43176fc2/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-icon-store-appbar.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c82fc76e-4e73-4cfc-a7d1-9a3a6acadde6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-light-box-view.md](https://github.com/MicrosoftDocs/msteams-docs/blob/668e9ed4584030ddab346641eed5e60d43176fc2/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-light-box-view.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d0ae7ff-9406-4356-95ab-342d80f0ea2d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7642d77b83749aab9a69a6a6dfdc1b4c86a99038/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 89 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16b75660-2a6e-4618-9fba-9146b4b45104) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7642d77b83749aab9a69a6a6dfdc1b4c86a99038/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 128 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/960bd483-9d2a-43ee-b913-c2cbc844243c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/update-apple-store-team-connect-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7642d77b83749aab9a69a6a6dfdc1b4c86a99038/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fupdate-apple-store-team-connect-id.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3805bcba-ef69-48a1-9c30-9598497265bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7642d77b83749aab9a69a6a6dfdc1b4c86a99038/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2882b3b2-d799-4da4-9600-b773714bddec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7642d77b83749aab9a69a6a6dfdc1b4c86a99038/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fresolve-submission-issues.md) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7aa89ee6-6d6f-4373-b845-7fc8fc17a490) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/app-structure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7642d77b83749aab9a69a6a6dfdc1b4c86a99038/msteams-platform%2Fconcepts%2Fdesign%2Fapp-structure.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da4e33bb-abbf-4a79-8396-840d1447a186) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7642d77b83749aab9a69a6a6dfdc1b4c86a99038/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-advanced-ui-components.md) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e583d95-c5e1-404f-99ff-1bee351aab6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-artwork-store.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7642d77b83749aab9a69a6a6dfdc1b4c86a99038/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-artwork-store.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21f45584-476d-483d-bce1-98355e2e8a26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-basic-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7642d77b83749aab9a69a6a6dfdc1b4c86a99038/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-basic-ui-components.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc94520b-16c7-491c-ae43-cc0116ae52f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-icon-store-appbar.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7642d77b83749aab9a69a6a6dfdc1b4c86a99038/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-icon-store-appbar.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/894b28c8-6107-4c68-9f0c-22fd2e9f2dd0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-light-box-view.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7642d77b83749aab9a69a6a6dfdc1b4c86a99038/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-light-box-view.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03cb9cc1-e688-43dd-a844-13bc79f58f00) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/teams-store-validation-guidelines.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c056ba4cc49742026f3c5d255b20386e884d9fb0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fteams-store-validation-guidelines.md) | 91 | 128 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44e27a4c-4963-419e-997f-cc3476214b96) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/update-apple-store-team-connect-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c056ba4cc49742026f3c5d255b20386e884d9fb0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fupdate-apple-store-team-connect-id.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a7fe253-2e19-448e-a1e3-68f93ed3580a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c056ba4cc49742026f3c5d255b20386e884d9fb0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea2833b2-03a3-4d19-aa13-da6c692379d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/resolve-submission-issues.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c056ba4cc49742026f3c5d255b20386e884d9fb0/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fresolve-submission-issues.md) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23317e86-dba1-4ff9-8dc5-653265040d1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/app-structure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c056ba4cc49742026f3c5d255b20386e884d9fb0/msteams-platform%2Fconcepts%2Fdesign%2Fapp-structure.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15ae14eb-a232-4412-950d-36575c2b0b72) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c056ba4cc49742026f3c5d255b20386e884d9fb0/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-advanced-ui-components.md) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dec68d7a-a5d7-43f5-a51c-6d5b1631c6c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-artwork-store.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c056ba4cc49742026f3c5d255b20386e884d9fb0/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-artwork-store.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6c77d6f-5027-4870-b2d0-a11f7d246eea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-basic-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c056ba4cc49742026f3c5d255b20386e884d9fb0/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-basic-ui-components.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a9ee4f9-63c5-4aad-87c7-c23ebd5854c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-icon-store-appbar.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c056ba4cc49742026f3c5d255b20386e884d9fb0/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-icon-store-appbar.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c30dffa-7fa8-41f9-90f0-f6bbdc950422) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-light-box-view.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c056ba4cc49742026f3c5d255b20386e884d9fb0/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-light-box-view.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4c6c9cf-b096-46a9-ad55-5326c7820296) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-ramyas5** [comment]
Redundant. Fixed in another PR.

**Pull request closed without merging**
