### PR TITLE
Consistency and terminology improvements

### PR DESCRIPTION
**Pull request by erikadoyle**
Minor edits to improve formatting and make terminology and branding more consistent.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90e804447729c96dab27ce1b832f7686c7d79ae2/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 92 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16998c74-0150-4647-a573-2206f36973bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90e804447729c96dab27ce1b832f7686c7d79ae2/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98ec41f1-a160-412e-b07a-8b2d86c1573c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90e804447729c96dab27ce1b832f7686c7d79ae2/msteams-platform/m365-apps/overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b91b562-7781-4794-819d-3a5147a32fb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90e804447729c96dab27ce1b832f7686c7d79ae2/msteams-platform/m365-apps/prerequisites.md) | 92 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dacd0eda-652d-4ad7-bc4c-e167ea340017) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/using-teams-client-sdk-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90e804447729c96dab27ce1b832f7686c7d79ae2/msteams-platform/m365-apps/using-teams-client-sdk-preview.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8cdc77c-17c9-4e23-94f8-a7a752c3cf70) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1fdda58612b9000045640abc4430ac1d584c3921/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 92 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a27aa53-0eb6-49a7-8120-17cf7c133105) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1fdda58612b9000045640abc4430ac1d584c3921/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04fbbf49-c8e0-4224-be46-0a6132a6d262) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1fdda58612b9000045640abc4430ac1d584c3921/msteams-platform/m365-apps/overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8556c219-29b6-403a-b33d-98bbe1ae273b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1fdda58612b9000045640abc4430ac1d584c3921/msteams-platform/m365-apps/prerequisites.md) | 92 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02f820ce-40aa-452a-818c-7e08ddc28c69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/using-teams-client-sdk-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1fdda58612b9000045640abc4430ac1d584c3921/msteams-platform/m365-apps/using-teams-client-sdk-preview.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d728847e-3c8c-4cce-a032-9503cff9ef49) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ab94014d6c3ac2b16518a653f30d0c406085308/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 92 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b3774ed-c426-4df4-acd4-150f460415da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ab94014d6c3ac2b16518a653f30d0c406085308/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/565d249c-ade7-4b35-a614-83fa6aee5b28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ab94014d6c3ac2b16518a653f30d0c406085308/msteams-platform/m365-apps/overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02b57109-2ff4-49a1-9690-2a4aad682808) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ab94014d6c3ac2b16518a653f30d0c406085308/msteams-platform/m365-apps/prerequisites.md) | 92 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d61d45e4-f61f-4aeb-8984-5a36de7935a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/using-teams-client-sdk-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ab94014d6c3ac2b16518a653f30d0c406085308/msteams-platform/m365-apps/using-teams-client-sdk-preview.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4a76141-e757-45e9-ab23-090a0f0411ad) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f457b5821c55feacaf156547f0881c69343d4f3/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 92 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70c4347c-47cb-4dff-9f0e-a35f071871a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f457b5821c55feacaf156547f0881c69343d4f3/msteams-platform/m365-apps/extend-m365-teams-personal-tab.md) | 93 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a3cea67-d083-4d09-96b3-e97ebfc6fe84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f457b5821c55feacaf156547f0881c69343d4f3/msteams-platform/m365-apps/overview.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1449413-a243-48cc-b8c9-8382b4a64b84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f457b5821c55feacaf156547f0881c69343d4f3/msteams-platform/m365-apps/prerequisites.md) | 92 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20bb35e1-b77f-46a8-a4ce-71ac4f64cadf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/using-teams-client-sdk-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4f457b5821c55feacaf156547f0881c69343d4f3/msteams-platform/m365-apps/using-teams-client-sdk-preview.md) | 84 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f014bcf-0ce8-4fb9-ab58-210350ac1bd6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
