### PR TITLE
[Doc update][AI library QSG]

### PR DESCRIPTION
**Pull request by v-ypalikila**
updated

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/conversation-ai-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/463394997e14f7206f2b1daa98db48a097de4b7b/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fconversation-ai-quick-start.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/173eb4f0-ff9e-4530-a08c-a36763611df7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/conversation-ai-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00d389d174357f517f34045b64811e2a9a77e9d3/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fconversation-ai-quick-start.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ea1f46c-96f1-4e47-9340-e4d6edd5809e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/Teams conversational AI/conversation-ai-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/62da1fa79612f930cb4d4e806dfebef296edf328/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fconversation-ai-quick-start.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af8cbdd1-d070-48aa-aa92-37461e06b254) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/830829e773225526cbb2d64a5626a0f537fe3518/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea3a2be9-b15b-42df-95f9-b29b8ba45d82) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/Teams conversational AI/assistants-api-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/830829e773225526cbb2d64a5626a0f537fe3518/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fassistants-api-quick-start.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28266a90-df6e-4c3b-a2a4-e4aac5714c1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/Teams conversational AI/conversation-ai-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/830829e773225526cbb2d64a5626a0f537fe3518/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fconversation-ai-quick-start.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed7dcac9-69e6-4320-8152-cbc6d6e895cc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/317054a02a0befe679f21f9297339dfc23f190aa/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34e424a6-4e25-460a-a263-2c744745603c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/Teams conversational AI/assistants-api-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/317054a02a0befe679f21f9297339dfc23f190aa/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fassistants-api-quick-start.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09f584cc-0ea1-4fda-9b3e-034387a0c5ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/Teams conversational AI/conversation-ai-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/317054a02a0befe679f21f9297339dfc23f190aa/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fconversation-ai-quick-start.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef44bca0-e665-4307-a607-3d316bc6b985) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/80b1b625cbe6bdc6f070c539411a17b1f40d8fea/msteams-platform%2FTOC.yml) | 96 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20e553e2-4be3-45be-bde6-0dbbe6d1993f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/Teams-AI-library-tutorial.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/80b1b625cbe6bdc6f070c539411a17b1f40d8fea/msteams-platform%2FTeams-AI-library-tutorial.yml) | 80 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92255588-f15c-4b2a-8fb3-b438cc3ce703) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/Teams conversational AI/assistants-api-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80b1b625cbe6bdc6f070c539411a17b1f40d8fea/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fassistants-api-quick-start.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95070004-07f4-488e-bb72-49f999e6b26b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/Teams conversational AI/conversation-ai-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80b1b625cbe6bdc6f070c539411a17b1f40d8fea/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fconversation-ai-quick-start.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8b88343-48a3-4f18-a2fe-ace6b11bc126) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
