### PR TITLE
Update CICD pipeline default CLI version

### PR DESCRIPTION
**Pull request by Siglud**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3f64b42be0c0dfeb2593b61fe38f10e938a81846/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 86 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c797530-d3d8-494a-9a6c-5d9b9f80e0ad) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4310d55e87fb1e49724ed63afd310d919d749146/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 89 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0e6b1bd-d096-4ce1-b952-45306861e4b4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c622a4752286205e86b04e7963c43b88fb07db90/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 89 | 51 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/753e69ef-8e7a-41d5-b00b-b7af5b544132) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/use-CICD-template.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4037045c8e48e62dba4eecc5bf876449849caba5/msteams-platform%2Ftoolkit%2Fuse-CICD-template.md) | 90 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e9de43d-4ecd-4aed-b5f6-a458d9dc6a68) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
