### PR TITLE
V rodriguezd 1310881 document fixes

### PR DESCRIPTION
**Pull request by v-rodriguezd**
Document fixes for issues 2150, 2133 and 2035

### CODE REVIEW

**Review by heath-hamilton — COMMENTED** [review]
Hi @v-rodriguezd, I have a couple questions regarding updates to build-first-app-overview.md:

- I wonder if the new note should come at the end of the procedure? It seems this would be your next option only after you've checked Teams for custom app uploading and signed up for an M365 test account.
- "While registering your app ...": Is "registering your app" referring to sideloading/uploading? If not, this is a new concept we aren't fully explaining in this topic.

**Comment by v-rodriguezd** [comment]
> Hi @v-rodriguezd, I have a couple questions regarding updates to build-first-app-overview.md:
> 
> * I wonder if the new note should come at the end of the procedure? It seems this would be your next option only after you've checked Teams for custom app uploading and signed up for an M365 test account.
> * "While registering your app ...": Is "registering your app" referring to sideloading/uploading? If not, this is a new concept we aren't fully explaining in this topic.

I have made the change. Please let me know if it's  correct.

**Comment by heath-hamilton** [comment]
H @v-rodriguezd, looks good! I would just recommend updating the first part of the note (see below).

**Current**: "To enable custom teams apps and turn on custom app uploading, refer ..."

**Suggested revision**: "If you still can't sideload apps, refer to ..."

Hope this helps--please let me know if you have questions.

**Comment by v-rodriguezd** [comment]
> H @v-rodriguezd, looks good! I would just recommend updating the first part of the note (see below).
> 
> **Current**: "To enable custom teams apps and turn on custom app uploading, refer ..."
> 
> **Suggested revision**: "If you still can't sideload apps, refer to ..."
> 
> Hope this helps--please let me know if you have questions.

Resolved

**Review by laujan — APPROVED** [review]

**Pull request merged**
