### PR TITLE
[Doc Feature][Live Charts & Graphs][3758775]

### PR DESCRIPTION
**Pull request by v-kushals**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f20a634fc92d83f78cc01622880e173836ec51db/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 67 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c7fe9e5-d722-457b-a6e9-0ea92ae0b2d9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bd8655a0d69d51bcca1f33d0622455408aa4f93/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 81 | 73 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d1af819-ec75-4c96-adcd-c9b788df47ad) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd7f00ee32d42f51c2280b377a5d97958d8cf6a3/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b69b418e-1d4f-4ca7-aa6d-ee336a75ccb4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6116c032bb1ab449940de6424ccf2fadbc806e9b/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97bb99cb-9a22-4a14-9683-09004715c268) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ecfed3676a0995a5b8ada518b74155df65e60408/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29885a99-c196-4a1a-8031-b3b26b81f326) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd67364818faffef7832504af51f64fe5d2dc02b/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61f45b51-5580-41e5-b9d5-b48d106634ec) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6f2fbf39914b672a430ea999177dd34dd79dcca/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/409f654e-15ea-4663-8b7e-3faad6c0e20e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ffd7719e75d1e1110e5bfdb7497570c7bc9d634b/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 92 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce50843d-894a-4127-ae21-50abc8bea758) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66774cda8ce0107f2bedac29528101cfccc98f80/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 92 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc6156e3-75f1-404a-a0d7-6ec7d639b1c5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec73a44b4063975f9ca95f30bcb574475271ff09/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 95 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16dd515d-4920-4bb4-a5d7-85fa6f6b7e2f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cff291a62b0f2c3301dfb89fe661be81da0de181/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6ff1686-06f6-4da3-97a2-c78d2bd0741b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fadb9ebabb8e6ab538304915155047fbfd86f36a/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee1fb618-a316-466f-86bd-107cdbcfb73c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/00bb673463a7cdb59ed3be6137ad7eab0e04ad0f/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7020971a-d6e0-46a4-a118-98488a834aea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20bd1efa1d0eae159940354b6061cfe6d1630cfb/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b72cf17-27ef-4d7a-886c-e573e1c7cba4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3a5218b31b88be9f05d5152a09ae361fe2fd88a6/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6648b4d-002c-463c-9f3b-14291fef295f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/417ceab548f463a25a00e8f681e82d0fa002edb6/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f1c8aa9-b7be-45fa-b7d9-603940233285) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bd022f2159d93d031b6f0eed277daeccfdd3187f/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c7fc207-1b18-44d7-a787-2a32b96ddfad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd022f2159d93d031b6f0eed277daeccfdd3187f/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0320356b-7203-454e-9f69-f7101b24b65b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c381b995bca8467ce0b184a02c2a1753cc54632e/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4f83e5c-f121-4ed2-9679-2bcd1a5eb4c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c381b995bca8467ce0b184a02c2a1753cc54632e/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/982eef1e-b10a-4dad-9b39-05f573b70d37) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/eb51d38e784ce28225168271f49ae3e8a7b6e781/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3527f8c7-4201-4dee-911b-d7953d01c979) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eb51d38e784ce28225168271f49ae3e8a7b6e781/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec62aebf-e6ca-4fd4-868e-395d4d314746) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e79c9af6c21ead264e68d1b525f801d802a088f4/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/475ff18f-47a6-4f4d-b917-d30dd4d06955) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e79c9af6c21ead264e68d1b525f801d802a088f4/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ab712a9-47cc-4228-9440-2e53a6ad316f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/16dd8fc36ccc3e65986e201956b6ebc4bad222b9/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/995f92a1-5305-4429-8b75-da491bdc29ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/16dd8fc36ccc3e65986e201956b6ebc4bad222b9/msteams-platform%2Fmstdd-landing.yml) | 87 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eed5fb32-983e-4540-bbbd-5a9b2c1157e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16dd8fc36ccc3e65986e201956b6ebc4bad222b9/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d42559c-2b60-4a45-90b5-9a2d8beb84d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16dd8fc36ccc3e65986e201956b6ebc4bad222b9/msteams-platform%2Fwhats-new.md) | 90 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f9c3913-4b61-4ec3-8584-b5e22b8bf336) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f633f3ad262a0b3b0c828568574622f2e9d4af31/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b399796-9b36-4aab-aafb-ecfe4af8bac3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f633f3ad262a0b3b0c828568574622f2e9d4af31/msteams-platform%2Fmstdd-landing.yml) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c0b131b-2d20-4968-81f5-16b99ca3f9ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f633f3ad262a0b3b0c828568574622f2e9d4af31/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b282ee3-14a3-48ea-809e-4e4fe4567985) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f633f3ad262a0b3b0c828568574622f2e9d4af31/msteams-platform%2Fwhats-new.md) | 90 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d8ac69c-2c41-4ba6-972a-72d20aaae8aa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by surbhigupta12** [comment]
Approved by FPM (David)

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b6fa9a9b2ffa7b1117b403fbbc5e82c7a0cc9cb6/msteams-platform%2FTOC.yml) | 91 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90dd4a1e-4e0c-4445-812f-dff9d915d414) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b6fa9a9b2ffa7b1117b403fbbc5e82c7a0cc9cb6/msteams-platform%2Fmstdd-landing.yml) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d6d316d-f422-421b-beef-9635e815d3d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/charts-in-adaptive-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6fa9a9b2ffa7b1117b403fbbc5e82c7a0cc9cb6/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcharts-in-adaptive-cards.md) | 99 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2025c74-9f65-49db-830c-606ed03b781e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b6fa9a9b2ffa7b1117b403fbbc5e82c7a0cc9cb6/msteams-platform%2Fwhats-new.md) | 90 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23b31a76-dc49-4e08-b5bc-55fc12a21e0a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
