### PR TITLE
[Doc Improvement][See also section update 2][3844140]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4098443a0e0a3536d133dea6aa17f7f2b6012af/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/280138fd-ba63-4ec5-8644-043395aa1af8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/app-growth-lifecycle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4098443a0e0a3536d133dea6aa17f7f2b6012af/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fapp-growth-lifecycle.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c420f80d-f37d-419c-9074-25f40acbcceb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/build-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4098443a0e0a3536d133dea6aa17f7f2b6012af/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fbuild-app.md) | 88 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a55a8edf-20ad-4133-931e-0ba61d1bee4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4098443a0e0a3536d133dea6aa17f7f2b6012af/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 84 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8d09a2e-c921-46bb-8acb-28e87dab779d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/launch-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4098443a0e0a3536d133dea6aa17f7f2b6012af/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Flaunch-app.md) | 82 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04f77c1a-8993-4fb6-b47c-426016b4b9aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/overview-app-growth.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4098443a0e0a3536d133dea6aa17f7f2b6012af/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Foverview-app-growth.md) | 81 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/900cc118-0906-4c7f-8136-d93b010dd3e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4098443a0e0a3536d133dea6aa17f7f2b6012af/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 82 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5efbd5da-7e89-4682-88ad-def47e2a762e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4098443a0e0a3536d133dea6aa17f7f2b6012af/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98aab24a-bebf-494f-8606-0dd7f05fecf1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4098443a0e0a3536d133dea6aa17f7f2b6012af/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-partner-center-dev-account.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1376a599-7c8d-41f5-a4c4-1ea1cfc5b152) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4098443a0e0a3536d133dea6aa17f7f2b6012af/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ceae8e71-9a42-4a24-926a-e929d558e096) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4098443a0e0a3536d133dea6aa17f7f2b6012af/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/113e0162-4ba0-4ded-8775-349c2a70bdaf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4098443a0e0a3536d133dea6aa17f7f2b6012af/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68ca6bb4-98d8-4eb2-a95b-3de5e8c2a410) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72d0e57245ab7c9eb299b9aee5d7143217048371/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1674d0c-46df-4c37-984f-279ae2649bc9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/app-growth-lifecycle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72d0e57245ab7c9eb299b9aee5d7143217048371/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fapp-growth-lifecycle.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd4cdc81-5b94-4228-9779-b6ad0ab35e50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/build-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72d0e57245ab7c9eb299b9aee5d7143217048371/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fbuild-app.md) | 88 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3559b9f-d463-41d6-babe-a95972ebb9f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72d0e57245ab7c9eb299b9aee5d7143217048371/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 84 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7647e762-47d0-4992-8020-62d370285501) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/launch-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72d0e57245ab7c9eb299b9aee5d7143217048371/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Flaunch-app.md) | 82 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e4c618a-c831-40b1-bd9c-8a6b0e067170) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/overview-app-growth.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72d0e57245ab7c9eb299b9aee5d7143217048371/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Foverview-app-growth.md) | 81 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1334e93f-5fea-433d-89c8-4916749b5cef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72d0e57245ab7c9eb299b9aee5d7143217048371/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 82 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fbaad44-e937-44bb-9a30-a4b5582f47ed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72d0e57245ab7c9eb299b9aee5d7143217048371/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/caf26b67-cecf-4e77-942f-5e8830657462) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72d0e57245ab7c9eb299b9aee5d7143217048371/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-partner-center-dev-account.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bc0fe50-d75d-4087-96c6-c93e103bdb50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72d0e57245ab7c9eb299b9aee5d7143217048371/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b6079ab-7066-416f-a6ee-cc5b859b40ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/72d0e57245ab7c9eb299b9aee5d7143217048371/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bf8ebfa-ff64-42a3-9001-49fb5a6d023f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37bb64b96a49ab109ae468d3121f205612ca2bba/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0b0e8f6-0613-4376-9997-95d773d1fcdd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/app-growth-lifecycle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37bb64b96a49ab109ae468d3121f205612ca2bba/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fapp-growth-lifecycle.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e704dd4-1be9-439c-a14e-e1a8dc2f16cf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/build-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37bb64b96a49ab109ae468d3121f205612ca2bba/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fbuild-app.md) | 88 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f9454b3-056b-4f49-8b46-9a754467db60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37bb64b96a49ab109ae468d3121f205612ca2bba/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 84 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ebb95db-0ca8-4941-bb63-ca8838601c1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/launch-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37bb64b96a49ab109ae468d3121f205612ca2bba/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Flaunch-app.md) | 82 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/051519fb-fcfb-4ef6-95d7-171ebc6e1d7f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/overview-app-growth.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37bb64b96a49ab109ae468d3121f205612ca2bba/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Foverview-app-growth.md) | 81 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f38721f-82b9-4b1a-93f8-1f6e752cf3e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37bb64b96a49ab109ae468d3121f205612ca2bba/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 82 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88c15610-760d-4e87-854c-da73168a4c16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37bb64b96a49ab109ae468d3121f205612ca2bba/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/886c950b-5320-459b-bfdc-5ea8b340c256) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37bb64b96a49ab109ae468d3121f205612ca2bba/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-partner-center-dev-account.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9eda1842-162a-40e6-9dee-d84c9e54d508) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37bb64b96a49ab109ae468d3121f205612ca2bba/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/656f7609-06ee-4197-98e5-321d575607e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/37bb64b96a49ab109ae468d3121f205612ca2bba/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3180266-67ac-4a69-a5a5-d81d5e1acfe8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd8a882c2f6690c4744a3990c5c490a191df12f2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fapps-upload.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8fcfd1a4-667a-4cbf-99ef-44e4c0dc8fc7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/app-growth-lifecycle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd8a882c2f6690c4744a3990c5c490a191df12f2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fapp-growth-lifecycle.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fcb309c-a426-4e3b-8fd8-24d2ce787345) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/build-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd8a882c2f6690c4744a3990c5c490a191df12f2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fbuild-app.md) | 88 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/867daba7-8c03-420e-8f03-f99476bfed52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd8a882c2f6690c4744a3990c5c490a191df12f2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 84 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f76c8218-830c-400a-bd24-d421a27a2cc9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/launch-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd8a882c2f6690c4744a3990c5c490a191df12f2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Flaunch-app.md) | 82 | 66 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d77e9d65-131a-4625-9737-117e81d050da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/overview-app-growth.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd8a882c2f6690c4744a3990c5c490a191df12f2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Foverview-app-growth.md) | 81 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6605b0c7-882b-418f-b314-5da7502b9557) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd8a882c2f6690c4744a3990c5c490a191df12f2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 82 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47f60a31-35fa-420f-9744-0bdacc36db9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/Test-preview-for-monetized-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd8a882c2f6690c4744a3990c5c490a191df12f2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2FTest-preview-for-monetized-apps.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18aa6ae7-5369-41c0-b440-5db73679deb9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd8a882c2f6690c4744a3990c5c490a191df12f2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-partner-center-dev-account.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd0326ef-b8d4-47f4-a85f-0f21d9932e0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd8a882c2f6690c4744a3990c5c490a191df12f2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 88 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28fece49-122e-4ad2-b6a2-2769776996e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd8a882c2f6690c4744a3990c5c490a191df12f2/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 92 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87bb0eab-dd90-4a44-a056-84187989cb49) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
