### PR TITLE
[Doc Improvement][How-to guides - Tab and Bot capabilities][4189572]

### PR DESCRIPTION
**Pull request by v-kushals**
#10412 
#10486

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ec48df6be626b1643a034e06e745581e4e740ec1/msteams-platform%2FTOC.yml) | 93 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/796b8223-84c9-4351-a112-e8b9f8e3fb5a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-how-to-guides-vsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec48df6be626b1643a034e06e745581e4e740ec1/msteams-platform%2Ftoolkit%2Fadd-how-to-guides-vsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccd409b5-ccc8-4bd2-96dd-8b3e5e39d94e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-message-extension-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec48df6be626b1643a034e06e745581e4e740ec1/msteams-platform%2Ftoolkit%2Fconfigure-message-extension-capability.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c50e98a0-ffab-4abb-adbf-d7bc6770f729) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-tab-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ec48df6be626b1643a034e06e745581e4e740ec1/msteams-platform%2Ftoolkit%2Fconfigure-tab-capability.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b415d0de-55c2-4681-906c-e0ceb43be1be) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/92729b47f540ce20833d6af29ba7446ebdf802e9/msteams-platform%2FTOC.yml) | 93 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17076ef0-b620-4095-bd16-f9900b8f2a95) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-how-to-guides-vsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92729b47f540ce20833d6af29ba7446ebdf802e9/msteams-platform%2Ftoolkit%2Fadd-how-to-guides-vsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e70fe2e7-5244-48b4-ae5a-2026d213c897) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-message-extension-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92729b47f540ce20833d6af29ba7446ebdf802e9/msteams-platform%2Ftoolkit%2Fconfigure-message-extension-capability.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae4a3764-a144-4a7d-bc3d-ec101305b8e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-tab-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92729b47f540ce20833d6af29ba7446ebdf802e9/msteams-platform%2Ftoolkit%2Fconfigure-tab-capability.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ee50914-5048-4ecb-b188-8f6e541558b3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/80961ef4389f4da30343303d97ed8ed40143aea3/msteams-platform%2FTOC.yml) | 93 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e49eae36-b446-46b4-94a6-060052295510) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-how-to-guides-vsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80961ef4389f4da30343303d97ed8ed40143aea3/msteams-platform%2Ftoolkit%2Fadd-how-to-guides-vsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2916e0d-10d4-4e8b-9c87-df73bdbe0148) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-message-extension-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80961ef4389f4da30343303d97ed8ed40143aea3/msteams-platform%2Ftoolkit%2Fconfigure-message-extension-capability.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ef82c21-a59b-46a5-90ca-73aa21569dc7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-tab-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80961ef4389f4da30343303d97ed8ed40143aea3/msteams-platform%2Ftoolkit%2Fconfigure-tab-capability.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b92d153b-7740-4e5f-9181-46589b4ccda3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by V-bvishnu5 — APPROVED** [review]
Approved.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f0ef767ffe261dc64ac7a88d734dc35c10ab45fe/msteams-platform%2FTOC.yml) | 93 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/735aaab9-564c-4986-9be6-5ef0d751f401) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-how-to-guides-vsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0ef767ffe261dc64ac7a88d734dc35c10ab45fe/msteams-platform%2Ftoolkit%2Fadd-how-to-guides-vsc.md) | 85 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/184e2e4a-072c-41a7-856a-cf01ab373f9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-message-extension-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0ef767ffe261dc64ac7a88d734dc35c10ab45fe/msteams-platform%2Ftoolkit%2Fconfigure-message-extension-capability.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/555d081f-b89f-405f-8ce1-b523c1844d61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-tab-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0ef767ffe261dc64ac7a88d734dc35c10ab45fe/msteams-platform%2Ftoolkit%2Fconfigure-tab-capability.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d129d846-f707-40a0-be13-b6ed78dbebb0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/922acd12b42fd3050f1d3a48e3cd0130a5ffbd30/msteams-platform%2FTOC.yml) | 93 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e92989a6-32f1-427b-8c45-1c55d4782784) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-how-to-guides-vsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/922acd12b42fd3050f1d3a48e3cd0130a5ffbd30/msteams-platform%2Ftoolkit%2Fadd-how-to-guides-vsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2443db72-5e0a-4b42-9033-97498d99d7d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-message-extension-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/922acd12b42fd3050f1d3a48e3cd0130a5ffbd30/msteams-platform%2Ftoolkit%2Fconfigure-message-extension-capability.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccde2be3-b051-4ead-a86d-16b393a821d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-tab-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/922acd12b42fd3050f1d3a48e3cd0130a5ffbd30/msteams-platform%2Ftoolkit%2Fconfigure-tab-capability.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/649e6caf-5c27-4841-8977-d4be0adf0a7e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/35c2e5e089d838ed8d1722483f341bdb5f2efdcd/msteams-platform%2FTOC.yml) | 93 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ee82725-aa51-4e14-bca1-83894eeeb2dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-how-to-guides-vsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35c2e5e089d838ed8d1722483f341bdb5f2efdcd/msteams-platform%2Ftoolkit%2Fadd-how-to-guides-vsc.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cbb3c937-e1d5-4873-a2a8-f6fca59a0708) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-message-extension-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35c2e5e089d838ed8d1722483f341bdb5f2efdcd/msteams-platform%2Ftoolkit%2Fconfigure-message-extension-capability.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cac4107-46da-4ae3-a0ac-3dafc2826319) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/configure-tab-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35c2e5e089d838ed8d1722483f341bdb5f2efdcd/msteams-platform%2Ftoolkit%2Fconfigure-tab-capability.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15b29ac2-a7c7-420a-b6f6-657bcea144b4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
