### PR TITLE
[Doc Improvement][Tasks to dialogs in tools and SDK][3472445]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2284710ed2f476ec1c0b2f54ab8240dcb63258e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48b75c77-63b2-4d8b-8ca1-0b74f26c3112) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-your-Teams-app-test-tool.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f2284710ed2f476ec1c0b2f54ab8240dcb63258e/msteams-platform%2Ftoolkit%2Fdebug-your-Teams-app-test-tool.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c261cb1-3943-4449-86c9-a542a7188ef1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32d0c36b08c82cb4e0405a1118547e50cfdc846c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3b5606a-49e6-4376-b4a0-c2a552bfa6dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32d0c36b08c82cb4e0405a1118547e50cfdc846c/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-library.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a82efd9-8988-4cf4-bfc5-aeebf9584e55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-your-Teams-app-test-tool.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32d0c36b08c82cb4e0405a1118547e50cfdc846c/msteams-platform%2Ftoolkit%2Fdebug-your-Teams-app-test-tool.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29b87e9d-1a75-4965-843a-583e39a7da37) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f78c15fa7fbcc89fee5fb4f75e2d9881ed71e20/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc131faf-7149-4501-9627-f1c90807dbef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f78c15fa7fbcc89fee5fb4f75e2d9881ed71e20/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-library.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1032b229-465c-4da2-8ec3-f87e65e883a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-your-Teams-app-test-tool.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5f78c15fa7fbcc89fee5fb4f75e2d9881ed71e20/msteams-platform%2Ftoolkit%2Fdebug-your-Teams-app-test-tool.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64ae03d4-9e2f-4ac4-b88f-e604a430acb9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08db42853fa321bde54c40bfb4b6b599fed98994/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9ddac37-613e-4cdd-8cc0-8617ebb0f852) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08db42853fa321bde54c40bfb4b6b599fed98994/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-library.md) | 89 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c91a06e-8ad3-479f-a675-fb458fde775f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-your-Teams-app-test-tool.md](https://github.com/MicrosoftDocs/msteams-docs/blob/08db42853fa321bde54c40bfb4b6b599fed98994/msteams-platform%2Ftoolkit%2Fdebug-your-Teams-app-test-tool.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/986598f3-3672-47af-94b6-010997130a46) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a23aedb6e13a25a912ce0d68fe8c4d6a05356cd4/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/682831f8-b887-4b14-92ab-874de78aadfc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a23aedb6e13a25a912ce0d68fe8c4d6a05356cd4/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-library.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64da6da6-f7a7-4835-be78-7cc940d8fb66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-your-Teams-app-test-tool.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a23aedb6e13a25a912ce0d68fe8c4d6a05356cd4/msteams-platform%2Ftoolkit%2Fdebug-your-Teams-app-test-tool.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52261011-ae23-46ed-bd65-8fe19de59d09) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c68de31d38e0f458b91ac9a095c79e7e4f6cce08/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1501c194-bfb9-493a-9f97-ca2cc977ae81) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c68de31d38e0f458b91ac9a095c79e7e4f6cce08/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-library.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be1db16a-e0fd-44ea-9ee1-dcc4c92a3b1b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-your-Teams-app-test-tool.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c68de31d38e0f458b91ac9a095c79e7e4f6cce08/msteams-platform%2Ftoolkit%2Fdebug-your-Teams-app-test-tool.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48e61cd3-abea-441a-8bf5-4060a939af72) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/manage-your-apps-in-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7a93d5cf3a8c2ee9e41f4b07eaa5031bb311f362/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fmanage-your-apps-in-developer-portal.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/414480d2-8026-4658-a0b9-5258df71a930) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/using-teams-client-library.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7a93d5cf3a8c2ee9e41f4b07eaa5031bb311f362/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-library.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e461820-530f-4043-891d-5fb6b23464f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-your-Teams-app-test-tool.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7a93d5cf3a8c2ee9e41f4b07eaa5031bb311f362/msteams-platform%2Ftoolkit%2Fdebug-your-Teams-app-test-tool.md) | 97 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f243c324-b747-4166-9b25-8ad79620bc72) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
