### PR TITLE
[Doc Improvement][SEO description update 11][3876711]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/launch-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc89b1ebe0073edd91eddac3b9321eecbdae5203/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Flaunch-app.md) | 82 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca75cc16-78a5-4f8c-8c29-fdf9636ac0cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/overview-app-growth.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc89b1ebe0073edd91eddac3b9321eecbdae5203/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Foverview-app-growth.md) | 81 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7159e7de-3dc8-4ee7-977c-02b0ee4fdb42) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/scale-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc89b1ebe0073edd91eddac3b9321eecbdae5203/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fscale-app.md) | 80 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df6e8ca1-41c9-4670-baed-0f1458e849c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc89b1ebe0073edd91eddac3b9321eecbdae5203/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 83 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c8340bd-78a1-4c2b-b424-be2f7c1272b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc89b1ebe0073edd91eddac3b9321eecbdae5203/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-partner-center-dev-account.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34257607-a56b-4cf5-8730-b6bea3a125fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc89b1ebe0073edd91eddac3b9321eecbdae5203/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 87 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9bd81f31-f106-4736-83b3-9d24b20c534e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc89b1ebe0073edd91eddac3b9321eecbdae5203/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84cc1972-4148-4ca3-b435-4b5d2973ee92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc89b1ebe0073edd91eddac3b9321eecbdae5203/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/faf8f7a1-6cf9-42f3-8573-93fdc6f9bb12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/app-structure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc89b1ebe0073edd91eddac3b9321eecbdae5203/msteams-platform%2Fconcepts%2Fdesign%2Fapp-structure.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bec61c07-13a0-4ca2-8560-68e703e21426) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-app-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc89b1ebe0073edd91eddac3b9321eecbdae5203/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-app-notification.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5aece891-1a5d-4732-93d0-ab09ff201d6d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/launch-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01c0f0627a24744e369ea040d1f0e8f882269786/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Flaunch-app.md) | 82 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b0823ab-2f91-4166-a1d3-6c859ee761a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/overview-app-growth.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01c0f0627a24744e369ea040d1f0e8f882269786/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Foverview-app-growth.md) | 81 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e85f580d-cc8b-4c7f-9f8d-0d13b816028e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/scale-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01c0f0627a24744e369ea040d1f0e8f882269786/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fscale-app.md) | 80 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/682079c3-7611-447d-a2a5-53624143690b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01c0f0627a24744e369ea040d1f0e8f882269786/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 83 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c20dfdb4-8782-4bf5-b593-580fd93d2aad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01c0f0627a24744e369ea040d1f0e8f882269786/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-partner-center-dev-account.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f224797e-0935-40bf-859f-e940bbe4e8b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01c0f0627a24744e369ea040d1f0e8f882269786/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 87 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ddad292-943b-4429-8c07-ffba83708f92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01c0f0627a24744e369ea040d1f0e8f882269786/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b29bc2e-81c9-48d6-84b1-2671e5bbc995) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01c0f0627a24744e369ea040d1f0e8f882269786/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a062bf51-64f8-4393-9913-89dad3e4022e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/app-structure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01c0f0627a24744e369ea040d1f0e8f882269786/msteams-platform%2Fconcepts%2Fdesign%2Fapp-structure.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91c69471-f886-45b5-9d4b-83aba02c38f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-app-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01c0f0627a24744e369ea040d1f0e8f882269786/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-app-notification.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ab5718a-3c8f-4039-a643-dcb86e1ba729) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/launch-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15fd545ae4354f85b707527d3ee3c68ef803ea9c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Flaunch-app.md) | 82 | 63 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/917894a2-4765-455c-988f-e04cd6e87f90) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/overview-app-growth.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15fd545ae4354f85b707527d3ee3c68ef803ea9c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Foverview-app-growth.md) | 81 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ac16692-aa1a-4ec1-abe9-f194fc1374fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/scale-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15fd545ae4354f85b707527d3ee3c68ef803ea9c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fscale-app.md) | 80 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8062cd6e-9fe3-470c-8945-60e044c3f9d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15fd545ae4354f85b707527d3ee3c68ef803ea9c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 83 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0d44e04-584f-448b-a5a0-5db765f97717) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15fd545ae4354f85b707527d3ee3c68ef803ea9c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-partner-center-dev-account.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af325a9f-a7dd-4345-b3e3-eb787c7bcf0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/end-user-purchase-experience.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15fd545ae4354f85b707527d3ee3c68ef803ea9c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fend-user-purchase-experience.md) | 87 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1816e7c0-32c0-4322-9622-11edca960c3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/in-app-purchase-flow.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15fd545ae4354f85b707527d3ee3c68ef803ea9c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fin-app-purchase-flow.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12af8953-3531-4d41-bab3-cd0875d25a94) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/manage-third-party-apps-license.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15fd545ae4354f85b707527d3ee3c68ef803ea9c/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fmanage-third-party-apps-license.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2fd25525-de15-4fd8-a032-f58bb75d0f23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/app-structure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15fd545ae4354f85b707527d3ee3c68ef803ea9c/msteams-platform%2Fconcepts%2Fdesign%2Fapp-structure.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20190f17-3212-4b85-8a21-3f55d4eea791) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-app-notification.md](https://github.com/MicrosoftDocs/msteams-docs/blob/15fd545ae4354f85b707527d3ee3c68ef803ea9c/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-app-notification.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a79467f-6332-4abb-ad01-5fe55817f44f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Review by v-ypalikila — APPROVED** [review]
approved.

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
