### PR TITLE
[Doc Improvement][Authentication FAQ]

### PR DESCRIPTION
**Pull request by v-shalinirobinson**
Add FAQ page for Authentication

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/authentication/authentication-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b54b6f5d8f1c9f7671cbfffb3ff4619d331df2e/msteams-platform/concepts/authentication/authentication-faq.md) | 71 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b69f5666-66c3-4e5d-b8bc-55a2d70fa936) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/authentication/authentication-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/122603e92cc1ec596ce24b82e403163cd184362f/msteams-platform/concepts/authentication/authentication-faq.md) | 87 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0cf85060-8648-497b-91df-51fa5df61ba4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1a6cd50d97776806db42f740fb129f63712cd968/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5425e9d-04fd-48c0-bd32-e469124c0dde) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/authentication-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a6cd50d97776806db42f740fb129f63712cd968/msteams-platform/concepts/authentication/authentication-faq.md) | 87 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1523107-8973-4c81-89c9-7e06102c08ae) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4cbf41af697e737d4fd3f17ab7f95af063d6fd7a/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73e4f925-8dc9-43f3-a3b2-ac7c57baa595) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/authentication-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4cbf41af697e737d4fd3f17ab7f95af063d6fd7a/msteams-platform/concepts/authentication/authentication-faq.md) | 87 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ba7bc33-58c9-434c-b25e-babb2105daa7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/53ee975f88e4aad06b10e6d7b20e029b3eefa947/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbe1ad2e-43c7-46dd-8a03-fcc62456da3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/authentication-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53ee975f88e4aad06b10e6d7b20e029b3eefa947/msteams-platform/concepts/authentication/authentication-faq.md) | 87 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3cc29fb3-c6e0-4c61-93ef-85d741f5b652) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a3a68ef4fb9efe209e59cd493beb895fd41a53b6/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa6e6208-39a8-420e-bd86-3644b4f4ac02) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/authentication-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3a68ef4fb9efe209e59cd493beb895fd41a53b6/msteams-platform/concepts/authentication/authentication-faq.md) | 87 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95e3d60d-9a51-4e0b-892a-1cc6a5e452eb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7a199e7ca0b72efa46b8a9e3177069e9eda4ad17/msteams-platform/TOC.yml) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a142233-6ccc-48eb-bc6a-bd4797878c93) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/authentication-faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7a199e7ca0b72efa46b8a9e3177069e9eda4ad17/msteams-platform/concepts/authentication/authentication-faq.md) | 87 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19758ece-02d4-4cc6-b726-9d965c9cc5fa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-shalinirobinson** [comment]
This PR is being closed for now and will be started afresh after SSO implementation sections are revamped.

**Pull request closed without merging**
