### PR TITLE
[Docenhancement][Device capabilities-Added note][1838632]

### PR DESCRIPTION
**Pull request by Rajeshwari-v**
Added a note. Please review.

### CODE REVIEW

**Comment by Rajeshwari-v** [comment]
@lokimeyburg , please review and approve the PR.

**Review by lokimeyburg — APPROVED** [review]
LGTM :shipit:

**Review by shuchauh — APPROVED** [review]
Approved

**Review by v-abirade — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
