### PR TITLE
[Doc Improvement][analytics-link-etc]

### PR DESCRIPTION
**Pull request by v-shalinirobinson**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee7d6df0e8289b470f360b0a9084f15906bdb8e2/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be2ef398-241c-4479-9d2b-1c0a34860732) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/plan-code-instrumentation.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee7d6df0e8289b470f360b0a9084f15906bdb8e2/msteams-platform%2Fconcepts%2Fdesign%2Fplan-code-instrumentation.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce623cc1-b80d-4955-bb4b-40e931af83a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/strategize-measure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee7d6df0e8289b470f360b0a9084f15906bdb8e2/msteams-platform%2Fconcepts%2Fdesign%2Fstrategize-measure.md) | 90 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a37c7176-8d55-4983-964c-5cc1820eb1f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ee7d6df0e8289b470f360b0a9084f15906bdb8e2/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d8c1d25-58a4-4357-b3c8-9130e273d3a7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d661378dc4b4cc3a418dca965ef9e9a86392ac7c/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b91a13d5-4800-4b0b-89c4-c70140be61e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/plan-code-instrumentation.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d661378dc4b4cc3a418dca965ef9e9a86392ac7c/msteams-platform%2Fconcepts%2Fdesign%2Fplan-code-instrumentation.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74741333-a36e-4d6b-b6ed-95aa97e43f4b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/strategize-measure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d661378dc4b4cc3a418dca965ef9e9a86392ac7c/msteams-platform%2Fconcepts%2Fdesign%2Fstrategize-measure.md) | 90 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfb4e59e-bef3-4bbf-bd11-5eca9e3cd680) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d661378dc4b4cc3a418dca965ef9e9a86392ac7c/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ed7104c-2dd4-4926-847e-dfa85459db47) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4701a885e85f5d1f6ba333d217bcff87db1c6bc/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a720ae75-48fe-451b-a101-df2d19dcec2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/plan-code-instrumentation.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4701a885e85f5d1f6ba333d217bcff87db1c6bc/msteams-platform%2Fconcepts%2Fdesign%2Fplan-code-instrumentation.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/edce1770-fa51-4060-bc7e-f697e0191c12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/strategize-measure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4701a885e85f5d1f6ba333d217bcff87db1c6bc/msteams-platform%2Fconcepts%2Fdesign%2Fstrategize-measure.md) | 90 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29741749-69bf-4002-ad4a-93173325ef1f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b89ea92e9be256e96c0d6d9e76c17237c06afa5/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 90 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0944b107-1516-4ff8-891a-b631c3a262c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/plan-code-instrumentation.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b89ea92e9be256e96c0d6d9e76c17237c06afa5/msteams-platform%2Fconcepts%2Fdesign%2Fplan-code-instrumentation.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fce06aad-541f-4af0-92c3-505398d3f325) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/strategize-measure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5b89ea92e9be256e96c0d6d9e76c17237c06afa5/msteams-platform%2Fconcepts%2Fdesign%2Fstrategize-measure.md) | 90 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/061ff7e4-7948-4952-9a86-1128996d338e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c350ac9fd727519541c0c8c394578f226baacc4/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 90 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b631500-3ba2-479c-a943-71b857d3ec6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/plan-code-instrumentation.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c350ac9fd727519541c0c8c394578f226baacc4/msteams-platform%2Fconcepts%2Fdesign%2Fplan-code-instrumentation.md) | 90 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74f581de-870c-4e2a-9c8f-0281501dd3bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/strategize-measure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c350ac9fd727519541c0c8c394578f226baacc4/msteams-platform%2Fconcepts%2Fdesign%2Fstrategize-measure.md) | 90 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98c38f4c-b770-4ab8-9ca9-c45781e58191) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4c350ac9fd727519541c0c8c394578f226baacc4/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56334c0b-d28b-4fa8-91b1-591e47450243) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
