### PR TITLE
Consistent ME terminology

### PR DESCRIPTION
**Pull request by erikadoyle**
Update instances of "message extension" to "messag**ing** extension" for consistency with existing Teams terminology.

### CODE REVIEW

**Comment by erikadoyle** [comment]
Hi @surbhigupta12, when you get a chance, would you mind taking a quick look and helping me merge this? Thank you!

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43a0effab0ea740062db60b3bcc346c762386b2e/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 89 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed21b22f-9cac-4d6b-8e7a-662fe8bcbfa1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43a0effab0ea740062db60b3bcc346c762386b2e/msteams-platform/m365-apps/prerequisites.md) | 93 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/888a67ef-7155-4c80-a426-8f11919fad59) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43a0effab0ea740062db60b3bcc346c762386b2e/msteams-platform/m365-apps/extend-m365-teams-message-extension.md) | 89 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7faf426e-a570-44b5-a3ae-163783db5346) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43a0effab0ea740062db60b3bcc346c762386b2e/msteams-platform/m365-apps/prerequisites.md) | 93 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a5d8fe1-196d-4022-843a-bc23db3da51b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
