### PR TITLE
[Doc Improvement][SBS guides update]

### PR DESCRIPTION
**Pull request by v-sreenivasv**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/97cff959e1f2eb521118f9e4d6e63dcaf7b6a7c6/msteams-platform/sbs-bots-with-sso.yml) | 87 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/770a9400-a53e-4c85-a248-815f37523da4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/97cff959e1f2eb521118f9e4d6e63dcaf7b6a7c6/msteams-platform/sbs-meeting-content-bubble.yml) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e949b95-48a8-479a-94b3-3e297b4421dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/97cff959e1f2eb521118f9e4d6e63dcaf7b6a7c6/msteams-platform/sbs-meeting-token-generator.yml) | 88 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60c092fe-4cc0-4ae3-bbf8-2f2c16d3f6bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/97cff959e1f2eb521118f9e4d6e63dcaf7b6a7c6/msteams-platform/sbs-meetings-sidepanel.yml) | 84 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b926c0c8-3a5e-4604-9faf-5fcab7557e6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/97cff959e1f2eb521118f9e4d6e63dcaf7b6a7c6/msteams-platform/sbs-meetings-stage-view.yml) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a644a561-472d-4c35-a56c-6946b44015d3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a8c555a06f1410953b898137bd9076146439c6f3/msteams-platform/sbs-bots-with-sso.yml) | 87 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b9fc35c-b4cf-40a8-9512-b759d7053463) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a8c555a06f1410953b898137bd9076146439c6f3/msteams-platform/sbs-meeting-content-bubble.yml) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b42411e8-3249-4781-9c23-aa1d545a25df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a8c555a06f1410953b898137bd9076146439c6f3/msteams-platform/sbs-meeting-token-generator.yml) | 88 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a52188b-304d-4a23-bdd7-b7ab5fddd0d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a8c555a06f1410953b898137bd9076146439c6f3/msteams-platform/sbs-meetings-sidepanel.yml) | 84 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd6040a5-c02e-465d-b9fa-e2fbb2633b1e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-stage-view.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a8c555a06f1410953b898137bd9076146439c6f3/msteams-platform/sbs-meetings-stage-view.yml) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4318b53f-50d0-4dac-af53-0a7d120c18d0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
