### PR TITLE
Update dashboard related docs with latest style design

### PR DESCRIPTION
**Pull request by huimiu**
We recently made adjustments to the style definition in the dashboard template of the Teams toolkit. Therefore, I would like to modify the relevant documentation through this PR.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7efd61597e97e7da9cb8c087ba41032bd7e60c37/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 84 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2ace25a-9739-487d-949e-f1ac7c205c9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7efd61597e97e7da9cb8c087ba41032bd7e60c37/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 93 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef0f383a-2439-4ad5-8abc-50e7812a6389) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fe013588a748ffda2bdb0baf8984147d882eb740/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 84 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e27c3f7-746c-42ae-bc6f-533465a16915) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fe013588a748ffda2bdb0baf8984147d882eb740/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 93 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f453356-a194-4d7e-b26f-d3752cc07b68) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by huimiu** [comment]
Hey @surbhigupta12, would you be willing to review this PR for me, please? I would greatly appreciate any feedback you may have.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ad7280d3dc91aacc158ae8b3e0dfd89e45fd5a18/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 84 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c39cf5e2-b3a3-439a-a3c6-f72a1872fc9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad7280d3dc91aacc158ae8b3e0dfd89e45fd5a18/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a88f874-6373-4a4c-b4d9-a179a1b83cb6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/96d580bba020e369a923652d195828c6d0e17862/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 84 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94fec13f-4198-4989-8fc0-dcd6023c401f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/96d580bba020e369a923652d195828c6d0e17862/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7178c896-6994-4f84-aa8e-64217ce73544) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/90d0fc24d27edc93e489291fd998ad74c1cb0742/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 84 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b383083-5839-468f-9394-261e4bb0321c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d0fc24d27edc93e489291fd998ad74c1cb0742/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68552721-23c4-47c9-bd4e-d016ceeb2f8f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by surbhigupta12** [comment]
Thank you. The PR looks good.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/90d0fc24d27edc93e489291fd998ad74c1cb0742/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 84 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65711370-376d-482d-8599-3c848c87b4e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/Build-a-dashboard-tab-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d0fc24d27edc93e489291fd998ad74c1cb0742/msteams-platform%2Ftabs%2Fhow-to%2FBuild-a-dashboard-tab-app.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6437d24f-f4f9-406c-8930-3b71313c9aa8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Pull request merged**
