### PR TITLE
[doc-bug][table-fix]

### PR DESCRIPTION
**Pull request by v-shalinirobinson**
table border fix

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e39187767ba23fdd920bf6793e3bdbde82257006/msteams-platform/get-started/glossary.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d390162-0f5e-49bc-9e1d-af2980a90045) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fee19129bb8a6c2f4bde780c8b682d1dce03c86f/msteams-platform/concepts/design/map-use-cases.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e70ed2f-397d-48b9-ae4f-51a404afd081) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/planning-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fee19129bb8a6c2f4bde780c8b682d1dce03c86f/msteams-platform/concepts/design/planning-checklist.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2febcc4f-9e33-4268-8544-e5fab3d8ba1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fee19129bb8a6c2f4bde780c8b682d1dce03c86f/msteams-platform/get-started/glossary.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/256d574e-36d5-4136-a917-09a09641c18d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fee19129bb8a6c2f4bde780c8b682d1dce03c86f/msteams-platform/overview-explore.md) |   |   | [link]( ) | [:warning:](# "Could not check with Acrolinx&#10;Please close and reopen pull request") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fee19129bb8a6c2f4bde780c8b682d1dce03c86f/msteams-platform/overview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c0eb960-2dec-42ef-ad78-6c3efc166508) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fee19129bb8a6c2f4bde780c8b682d1dce03c86f/msteams-platform/overview.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf180f71-8315-4d8c-9e8b-9c67cc1e7eee) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5109fee6e8ac7be059e1760d7859a4a4d3d74713/msteams-platform/concepts/design/map-use-cases.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5f968e2-fbbf-4ba0-8630-5b4a2f617321) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/planning-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5109fee6e8ac7be059e1760d7859a4a4d3d74713/msteams-platform/concepts/design/planning-checklist.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/500bdef8-f1d4-400e-a12f-06964794c77e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5109fee6e8ac7be059e1760d7859a4a4d3d74713/msteams-platform/get-started/glossary.md) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5904f31c-fe93-4818-8496-81d149a536fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5109fee6e8ac7be059e1760d7859a4a4d3d74713/msteams-platform/overview-explore.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ca1b87f-470c-4b17-ba58-cca81371c59f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-solution.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5109fee6e8ac7be059e1760d7859a4a4d3d74713/msteams-platform/overview-solution.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be16e00e-24d1-417e-a954-f6111ce1e610) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5109fee6e8ac7be059e1760d7859a4a4d3d74713/msteams-platform/overview.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5e1e9cf-386f-47c6-9593-61a88d7fa006) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5109fee6e8ac7be059e1760d7859a4a4d3d74713/msteams-platform/sbs-gs-csharp.yml) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e1796eb-c696-4237-acbd-1bbac6cdf2aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5109fee6e8ac7be059e1760d7859a4a4d3d74713/msteams-platform/sbs-gs-javascript.yml) | 93 | 83 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec1075f1-b3ab-49b1-bde0-0b849fc7f68a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
