### PR TITLE
[Doc Improvement][Live site review and update][3836215]

### PR DESCRIPTION
**Pull request by v-bvishnu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/669cd77d6fcf1db0f768e9560c18727434638ece/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41a07461-8018-414b-a94d-0813fa511aec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/669cd77d6fcf1db0f768e9560c18727434638ece/msteams-platform%2Fbots%2Fhow-to%2Fget-teams-context.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90df7250-191b-45d1-8767-f352b121b2db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/adaptive-card-previewer-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/669cd77d6fcf1db0f768e9560c18727434638ece/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fadaptive-card-previewer-vs.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a452666-784b-4e60-bcba-76bf36ee522b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-artwork-store.md](https://github.com/MicrosoftDocs/msteams-docs/blob/669cd77d6fcf1db0f768e9560c18727434638ece/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-artwork-store.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b272bc68-5b85-4e20-8404-ec59cf236e55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/669cd77d6fcf1db0f768e9560c18727434638ece/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-fundamentals.md) | 87 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4c1b6ad-a12f-4be9-8ee6-91587a03292a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/669cd77d6fcf1db0f768e9560c18727434638ece/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-ui-templates.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7755b0f-18a6-44e0-b84d-9dfbac9766d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/strategize-measure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/669cd77d6fcf1db0f768e9560c18727434638ece/msteams-platform%2Fconcepts%2Fdesign%2Fstrategize-measure.md) | 87 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e735dc15-e2fa-4880-8ae4-85568b4bba49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/669cd77d6fcf1db0f768e9560c18727434638ece/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9bc889c3-2add-44f3-bd3e-4ea300f4502c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/669cd77d6fcf1db0f768e9560c18727434638ece/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0079251a-20f5-46e2-a47a-8b9e92baf68a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/669cd77d6fcf1db0f768e9560c18727434638ece/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/984d0b42-0ca3-4e00-9f2b-fc61403d67c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/669cd77d6fcf1db0f768e9560c18727434638ece/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4610f03e-58f0-4f41-bf4f-458880370dcf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-your-Teams-app-test-tool-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/669cd77d6fcf1db0f768e9560c18727434638ece/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-your-Teams-app-test-tool-vs.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41b71901-eb07-441b-86e5-11efe7515743) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd9e215265a32298efe2126cf87062cf0f9a0db2/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f90ef78-629b-4bd5-b368-afe96d4878d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd9e215265a32298efe2126cf87062cf0f9a0db2/msteams-platform%2Fbots%2Fhow-to%2Fget-teams-context.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/419791fa-ae73-42b0-a7ab-efa29c41a1de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/adaptive-card-previewer-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd9e215265a32298efe2126cf87062cf0f9a0db2/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fadaptive-card-previewer-vs.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6c17108-48f1-4c4b-a0a9-c33b6fd22043) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-artwork-store.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd9e215265a32298efe2126cf87062cf0f9a0db2/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-artwork-store.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2f704f6-c414-4a76-a42b-be4d2bd6ecb3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd9e215265a32298efe2126cf87062cf0f9a0db2/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-fundamentals.md) | 87 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/278fbd96-14a2-48d8-9aa8-e452b11cd6d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd9e215265a32298efe2126cf87062cf0f9a0db2/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-ui-templates.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d3c9a98-40d4-4417-9939-9fad3b384df6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/strategize-measure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd9e215265a32298efe2126cf87062cf0f9a0db2/msteams-platform%2Fconcepts%2Fdesign%2Fstrategize-measure.md) | 87 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d088dab-7b6a-4160-a469-1d037695c8f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd9e215265a32298efe2126cf87062cf0f9a0db2/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87576a7e-fb7c-4916-a17b-9cab8791ff2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd9e215265a32298efe2126cf87062cf0f9a0db2/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2adc786a-ca5a-419e-a2d8-12b006407f92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd9e215265a32298efe2126cf87062cf0f9a0db2/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec31e147-eca8-4bee-a6d0-f0c91067222a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd9e215265a32298efe2126cf87062cf0f9a0db2/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a009aee-b3ff-428f-a35a-2cb0eb53a5cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-your-Teams-app-test-tool-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd9e215265a32298efe2126cf87062cf0f9a0db2/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-your-Teams-app-test-tool-vs.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bed39314-fc63-4015-a40a-371f42e4eb97) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16d38fa5fd56da7a16ccb5145f4a9d03808640b6/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9355f638-ae86-4b9b-8e3d-6b9093dfd4c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16d38fa5fd56da7a16ccb5145f4a9d03808640b6/msteams-platform%2Fbots%2Fhow-to%2Fget-teams-context.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71d8dd86-2728-4786-83e6-008e1ac1d417) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/adaptive-card-previewer-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16d38fa5fd56da7a16ccb5145f4a9d03808640b6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fadaptive-card-previewer-vs.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76a571bc-7444-41ec-a7bc-3e17d3891424) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-artwork-store.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16d38fa5fd56da7a16ccb5145f4a9d03808640b6/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-artwork-store.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6a749ec-796e-4704-931f-4a1f2d4b01bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16d38fa5fd56da7a16ccb5145f4a9d03808640b6/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-fundamentals.md) | 87 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e72e6eb7-9a1d-4ffa-864c-37c34145af9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16d38fa5fd56da7a16ccb5145f4a9d03808640b6/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-ui-templates.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3194924-3dc8-4396-ba01-f4a63d6bf7aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/strategize-measure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16d38fa5fd56da7a16ccb5145f4a9d03808640b6/msteams-platform%2Fconcepts%2Fdesign%2Fstrategize-measure.md) | 87 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85842baa-564e-472b-a22b-6c8a2a413f68) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16d38fa5fd56da7a16ccb5145f4a9d03808640b6/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3048b37f-3cc7-4494-ba80-80f9dedb1614) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16d38fa5fd56da7a16ccb5145f4a9d03808640b6/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08369b78-a6c9-4b26-a66d-f2e5a3fb0528) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16d38fa5fd56da7a16ccb5145f4a9d03808640b6/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f012bca5-f6a9-4141-9f91-d6077ead57f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16d38fa5fd56da7a16ccb5145f4a9d03808640b6/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f872fb0-3ec8-46e5-90c8-f77b1fae5219) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-your-Teams-app-test-tool-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/16d38fa5fd56da7a16ccb5145f4a9d03808640b6/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-your-Teams-app-test-tool-vs.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74234368-26c9-4232-88e5-6e3abda4f672) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f903e8383073944cb120f568c40b6c455408f214/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91b36b16-be0b-4ddb-b7eb-27a13bcaa508) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f903e8383073944cb120f568c40b6c455408f214/msteams-platform%2Fbots%2Fhow-to%2Fget-teams-context.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90b11388-ec50-4074-9709-6bcd77b5ca1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/adaptive-card-previewer-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f903e8383073944cb120f568c40b6c455408f214/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fadaptive-card-previewer-vs.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34db81ae-75d4-4409-89da-7aa6fc345f48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-artwork-store.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f903e8383073944cb120f568c40b6c455408f214/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-artwork-store.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5b843e2-989b-4801-b51c-71d6cc844b96) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f903e8383073944cb120f568c40b6c455408f214/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-fundamentals.md) | 87 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f12d707b-b32c-4253-8f54-c3361c0ee9f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f903e8383073944cb120f568c40b6c455408f214/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-ui-templates.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9baf0583-0c7e-4041-929b-64de57d2937d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/strategize-measure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f903e8383073944cb120f568c40b6c455408f214/msteams-platform%2Fconcepts%2Fdesign%2Fstrategize-measure.md) | 87 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f4eb4b6-6cbb-4aea-b0bb-169315f84891) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f903e8383073944cb120f568c40b6c455408f214/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/723cad9e-c1df-416c-af2b-5e07b513a9d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f903e8383073944cb120f568c40b6c455408f214/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/451d29f9-3eff-41e5-a0c8-1eb04d261c4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f903e8383073944cb120f568c40b6c455408f214/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a8446f1-4791-48ec-941a-699046facf58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f903e8383073944cb120f568c40b6c455408f214/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/caef95b3-b5c0-4212-b9a4-96a6c372c367) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-your-Teams-app-test-tool-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f903e8383073944cb120f568c40b6c455408f214/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-your-Teams-app-test-tool-vs.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61abbafb-f793-4d59-8898-d7e26ec502e8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7499c5939c98932430268c15542253e0707023/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8993c6f-745b-4aa6-bcc2-77480d969d3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7499c5939c98932430268c15542253e0707023/msteams-platform%2Fbots%2Fhow-to%2Fget-teams-context.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16cd890c-c741-47c4-96ba-fbe1461473fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/adaptive-card-previewer-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7499c5939c98932430268c15542253e0707023/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fadaptive-card-previewer-vs.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acbd53fd-db37-4593-82ba-92327b6436c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-artwork-store.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7499c5939c98932430268c15542253e0707023/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-artwork-store.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a6e80d4-8232-4490-bada-4695a419156c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7499c5939c98932430268c15542253e0707023/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-fundamentals.md) | 87 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9fce9e1a-fff4-4a2a-8b50-7f1c0b79ed9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7499c5939c98932430268c15542253e0707023/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-ui-templates.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1252a8b6-e873-42e2-8fb4-56148921bc45) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/strategize-measure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7499c5939c98932430268c15542253e0707023/msteams-platform%2Fconcepts%2Fdesign%2Fstrategize-measure.md) | 87 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbed742c-83ac-4417-952c-e925d366b36e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7499c5939c98932430268c15542253e0707023/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7192540e-53f1-4a1a-af38-3d5ca3dc49b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7499c5939c98932430268c15542253e0707023/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2ed9368-e843-4377-82c3-71b4b0e2f034) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/respond-to-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7499c5939c98932430268c15542253e0707023/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Frespond-to-search.md) | 89 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/015ce5a0-577b-4c94-94fe-617908f337d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7499c5939c98932430268c15542253e0707023/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/865541f1-1ce0-49fe-a5ef-8d72310076f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-your-Teams-app-test-tool-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7499c5939c98932430268c15542253e0707023/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-your-Teams-app-test-tool-vs.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a1af699-0264-42d0-945a-b04a335c2ced) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
