### PR TITLE
[doc-improvement] [link-update-tools-and-SDK]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f0d9fa69dfea80910a5fc6381369f4b7076279e/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-sdk.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3858b4d4-b2e5-4980-aa27-79c9e3b3c2b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f0d9fa69dfea80910a5fc6381369f4b7076279e/msteams-platform%2Ftoolkit%2Fvisual-studio-overview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59a9f87d-2513-4103-a210-e72a56b9429e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4c7464252b803ace6e288f0bf04af7f9fd3e4e0/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-sdk.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4511855d-c565-4740-aed4-2d15a43c5a52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4c7464252b803ace6e288f0bf04af7f9fd3e4e0/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5f36d83-e2c4-4486-97b4-e1848eb99a05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4c7464252b803ace6e288f0bf04af7f9fd3e4e0/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89bd1c21-83cd-4baf-b484-54fa27040c07) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4c7464252b803ace6e288f0bf04af7f9fd3e4e0/msteams-platform%2Ftoolkit%2Fvisual-studio-overview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee986f13-267f-41a8-9934-882ec860f7c3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab6cd2283cd7314b0cee639ae39a3a86eea1ba57/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-sdk.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f69ff9ab-e660-46e3-b231-e0eafc3d2dab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab6cd2283cd7314b0cee639ae39a3a86eea1ba57/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e28a41cb-ab81-4c8b-896a-2d83ccf7cb58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab6cd2283cd7314b0cee639ae39a3a86eea1ba57/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/564b0bf0-7b05-45ab-a728-09e07bd49208) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab6cd2283cd7314b0cee639ae39a3a86eea1ba57/msteams-platform%2Ftoolkit%2Fvisual-studio-overview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/779b69e1-529a-4960-82ee-6f0a8e276456) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Review by surbhigupta12 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a24d52b49d0fd0f19a4566b5d920ecbba51d125f/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-sdk.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9037a26-0af6-478a-a549-20d38b3e93b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a24d52b49d0fd0f19a4566b5d920ecbba51d125f/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03ca58fd-0dcf-45dc-910b-f28473bec37f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a24d52b49d0fd0f19a4566b5d920ecbba51d125f/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af81d1a0-ec96-4e5f-a043-a8efbb240eef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a24d52b49d0fd0f19a4566b5d920ecbba51d125f/msteams-platform%2Ftoolkit%2Fvisual-studio-overview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95359bb0-62af-4490-b580-035748b38911) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/using-teams-client-sdk.md](https://github.com/MicrosoftDocs/msteams-docs/blob/249c34aefba5a80acb31c5e06bd94902aa373507/msteams-platform%2Ftabs%2Fhow-to%2Fusing-teams-client-sdk.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3c334aa-b297-424f-b5df-9a75fbb15c64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/249c34aefba5a80acb31c5e06bd94902aa373507/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 90 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d10a156d-9ca8-4424-833c-1f7d0ae06d36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/249c34aefba5a80acb31c5e06bd94902aa373507/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29ad8428-2794-47f4-8fdf-9733a56871b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/249c34aefba5a80acb31c5e06bd94902aa373507/msteams-platform%2Ftoolkit%2Fvisual-studio-overview.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f62e886c-93ba-490a-88ae-576cb247124d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
