### PR TITLE
Bot Builder V4 works with Teams bots

### PR DESCRIPTION
**Pull request by EricDahlvang**
Remove the note stating Bot Framework v4 does not work with Teams.

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[46b9a57](https://github.com/EricDahlvang/msteams-docs/pull/671/commits/46b9a572c999802bcc9de07c1834f3c4d4487ebc)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[46b9a57](https://github.com/EricDahlvang/msteams-docs/pull/671/commits/46b9a572c999802bcc9de07c1834f3c4d4487ebc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/bots/bots-create.md](https://github.com/EricDahlvang/msteams-docs/blob/patch-1/msteams-platform/concepts/bots/bots-create.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C22%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201905222323100186-671%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WBEFROFTylBv%2BuBTRraiJOHFmvO9O7JxM0c6jn1ZlpQ%3D&st=2019-05-22T23%3A19%3A27Z&se=2019-06-22T23%3A24%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[1c43465](https://github.com/EricDahlvang/msteams-docs/pull/671/commits/1c434658da77aea215939349f4bb99ac9ce59c31)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/bots/bots-create.md](https://github.com/EricDahlvang/msteams-docs/blob/patch-1/msteams-platform/concepts/bots/bots-create.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C24%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201905242310051195-671%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=BRZRC3xr2Y8YeP22JlmkIw5CbDNy9evTM0AQxbCixaQ%3D&st=2019-05-24T23%3A06%3A19Z&se=2019-06-24T23%3A11%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[853c324](https://github.com/EricDahlvang/msteams-docs/pull/671/commits/853c32497cd238d59f9dfc0ea48e404e3a0075ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/bots/bots-create.md](https://github.com/EricDahlvang/msteams-docs/blob/patch-1/msteams-platform/concepts/bots/bots-create.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C24%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201905242310475595-671%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=DzXuaEIYDvtG0Barwg%2FAHY2Y5ONvA0YfzSO7t4JPzss%3D&st=2019-05-24T23%3A07%3A47Z&se=2019-06-24T23%3A12%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by EricDahlvang** [comment]
Thanks @clearab

**Pull request merged**
