### PR TITLE
[Doc Improvement][SEO description update 15][3939752]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-api-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d4548af91cb583e47a661fe28efce01a427c63/msteams-platform%2Fmessaging-extensions%2Fbuild-api-based-message-extension.md) | 92 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6b09343-7c51-496f-ac95-92ea92b5c90f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/59d4548af91cb583e47a661fe28efce01a427c63/msteams-platform%2Fmstdd-landing.yml) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ab79be3-093a-415d-b792-62921994cd48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/promote-app-adoption.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d4548af91cb583e47a661fe28efce01a427c63/msteams-platform%2Fpromote-app-adoption.md) | 90 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f927176a-269c-43fa-a90f-f54de3181be2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/qsg-bot-configuration-experience.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/59d4548af91cb583e47a661fe28efce01a427c63/msteams-platform%2Fqsg-bot-configuration-experience.yml) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9127eb1d-3f97-42cc-a5f0-ab03eb8e1347) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d4548af91cb583e47a661fe28efce01a427c63/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-channel.md) | 89 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/672c3190-5f79-4549-bee5-75ccff7ca40a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-personal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d4548af91cb583e47a661fe28efce01a427c63/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-personal.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a04991a9-4905-4965-ad10-ac29c2b5ec7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d4548af91cb583e47a661fe28efce01a427c63/msteams-platform%2Fresources%2Fbot-v3%2Fbots-cards.md) | 92 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c5c0e38-dd59-4462-ab21-1261bf610e81) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d4548af91cb583e47a661fe28efce01a427c63/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f557a39-6ab4-43c6-ad51-753ee915cd8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-menus.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59d4548af91cb583e47a661fe28efce01a427c63/msteams-platform%2Fresources%2Fbot-v3%2Fbots-menus.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd087878-7a51-488c-93fa-fd9096be7a25) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-api-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75868c9f2b84afe476665951f49e4bdd8a2d8d6/msteams-platform%2Fmessaging-extensions%2Fbuild-api-based-message-extension.md) | 92 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c775f1d3-4b24-48a0-ab08-05c303e9a983) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d75868c9f2b84afe476665951f49e4bdd8a2d8d6/msteams-platform%2Fmstdd-landing.yml) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86443f51-f984-4ef1-849b-15704a432ac3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/promote-app-adoption.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75868c9f2b84afe476665951f49e4bdd8a2d8d6/msteams-platform%2Fpromote-app-adoption.md) | 90 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/014fe69a-fbb4-4387-8218-922baa51a739) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/qsg-bot-configuration-experience.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d75868c9f2b84afe476665951f49e4bdd8a2d8d6/msteams-platform%2Fqsg-bot-configuration-experience.yml) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8206b767-993e-4c31-8a5b-2fd256296cef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75868c9f2b84afe476665951f49e4bdd8a2d8d6/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-channel.md) | 89 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e727e1a-a6a8-4d71-8810-0771dcd7d8e7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-personal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75868c9f2b84afe476665951f49e4bdd8a2d8d6/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-personal.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f489b63-e0e3-438a-9d71-96c1a6021bdc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75868c9f2b84afe476665951f49e4bdd8a2d8d6/msteams-platform%2Fresources%2Fbot-v3%2Fbots-cards.md) | 92 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec3a6f22-4ec8-4aa9-b0b5-2b0af2f9903a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75868c9f2b84afe476665951f49e4bdd8a2d8d6/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9187a740-a37b-49a4-9c19-0c0f29baac08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-menus.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d75868c9f2b84afe476665951f49e4bdd8a2d8d6/msteams-platform%2Fresources%2Fbot-v3%2Fbots-menus.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8306485-e4fb-47a0-8810-9aae46ffdbcf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-api-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e07cac9c3a98a75fedfda2fd34d21424e04db53f/msteams-platform%2Fmessaging-extensions%2Fbuild-api-based-message-extension.md) | 92 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0709d22a-67fc-4b97-a4ac-184c48835737) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e07cac9c3a98a75fedfda2fd34d21424e04db53f/msteams-platform%2Fmstdd-landing.yml) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf69cd19-bcfd-46ed-8011-822db5d3c555) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/promote-app-adoption.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e07cac9c3a98a75fedfda2fd34d21424e04db53f/msteams-platform%2Fpromote-app-adoption.md) | 90 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02a4ef47-e248-4983-b203-2ca27f3d8082) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/qsg-bot-configuration-experience.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e07cac9c3a98a75fedfda2fd34d21424e04db53f/msteams-platform%2Fqsg-bot-configuration-experience.yml) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/efccaee9-3a29-4f54-be32-8a56ae3ddc80) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e07cac9c3a98a75fedfda2fd34d21424e04db53f/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-channel.md) | 89 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0acd9028-5457-4951-ad8d-f3300b2393a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-personal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e07cac9c3a98a75fedfda2fd34d21424e04db53f/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-personal.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/186898ca-6da4-4818-bebf-0b90a587f716) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e07cac9c3a98a75fedfda2fd34d21424e04db53f/msteams-platform%2Fresources%2Fbot-v3%2Fbots-cards.md) | 92 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d73a7a3-22d3-49eb-97ac-511f4167b1f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e07cac9c3a98a75fedfda2fd34d21424e04db53f/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/270aec07-ae28-49f9-9982-92b8b4ac8ad8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-menus.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e07cac9c3a98a75fedfda2fd34d21424e04db53f/msteams-platform%2Fresources%2Fbot-v3%2Fbots-menus.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8a70b07-57e9-4a6d-82e0-bfd52e6ce5f1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-api-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d02f2fd3eee971d619e2e5177c11c574b260dda/msteams-platform%2Fmessaging-extensions%2Fbuild-api-based-message-extension.md) | 92 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/becc9c7e-de2b-4b4c-a067-0c0026a849c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8d02f2fd3eee971d619e2e5177c11c574b260dda/msteams-platform%2Fmstdd-landing.yml) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b6ed495-7724-4e2a-8bc9-874f463a809a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/promote-app-adoption.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d02f2fd3eee971d619e2e5177c11c574b260dda/msteams-platform%2Fpromote-app-adoption.md) | 90 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8126946-2735-4c45-a5e7-541570d16258) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/qsg-bot-configuration-experience.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8d02f2fd3eee971d619e2e5177c11c574b260dda/msteams-platform%2Fqsg-bot-configuration-experience.yml) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e04d4bfb-0726-472e-bfa8-7b1edd3f9b27) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d02f2fd3eee971d619e2e5177c11c574b260dda/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-channel.md) | 89 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21b9522e-7c62-4f25-8132-f760810b58d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-personal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d02f2fd3eee971d619e2e5177c11c574b260dda/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-personal.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0d3260e-e8ac-4125-96ab-7324eaad864f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d02f2fd3eee971d619e2e5177c11c574b260dda/msteams-platform%2Fresources%2Fbot-v3%2Fbots-cards.md) | 92 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b84d2301-10b8-4b04-b6c4-367d3fc3ae67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-create.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d02f2fd3eee971d619e2e5177c11c574b260dda/msteams-platform%2Fresources%2Fbot-v3%2Fbots-create.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c44e3e5-1c74-484f-a3f9-011ad752d1d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-menus.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d02f2fd3eee971d619e2e5177c11c574b260dda/msteams-platform%2Fresources%2Fbot-v3%2Fbots-menus.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00a0b6cc-230e-4f21-a285-5b2c3598a069) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
