### PR TITLE
[Doc Improvement][Tools and SDK-TTK-Create multi capability app][2756191]

### PR DESCRIPTION
**Pull request by v-vpaliwal**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d1eebf88938a1955262271e1e6ea30644fa9be2/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4fcb674c-cdd5-4a9e-93b9-82afac1c5e10) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c093a98e57d76a17887a4115a55db045ec5f4bd/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e66ad773-4646-4696-91e0-0a8291db2264) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c54f3c64b44cea526c9311c19c9f57ca006b3af1/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b1eed7f-7dc2-4be3-b4cf-f8ba7cc9e686) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0d91a45ef0258ff28bbbcca984cd0c6eb5c16e6c/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d6ad077-80ea-4fe9-b6fe-01ab7bdb5c0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0d91a45ef0258ff28bbbcca984cd0c6eb5c16e6c/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f57b0dc-9957-4a7f-bca1-fbdf6bc7aba0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20527fabb890432faaa4ba258187d5fb17890452/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77356efe-3c18-4f20-85f9-1f242861f189) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20527fabb890432faaa4ba258187d5fb17890452/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81e2bca9-6b82-426d-8c35-61ef8a2c5265) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6973d13e09001546af6c3f106455cb649409619b/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8fdc6c3e-a735-4363-a439-9e22dabfee90) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6973d13e09001546af6c3f106455cb649409619b/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/950d314e-d736-4ca0-8bef-fa7f18878d7e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-amprasad** [comment]
image
"in the following ways:" would be better.

**Comment by v-amprasad** [comment]
image
Can you reduce this image size. and crop the bottom part of the image below the second UI.

**Comment by v-amprasad** [comment]
image

Remove Microsoft as it is not a first mention.

**Comment by v-amprasad** [comment]
image

Please remove Microsoft from the main heading of the article. Instead add in the first paragraph before first Teams app mention.

**Comment by v-amprasad** [comment]
image
Can you write business needs instead of development needs?

**Comment by v-amprasad** [comment]
image

Make A & B in upper case for Activity Bar in step number 2 as per the UI.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35d38fa9baf0470e189d8fe987f7a5fdd09fe7ad/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cdc8037-bbcf-401b-975c-7798c1d4dd18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35d38fa9baf0470e189d8fe987f7a5fdd09fe7ad/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffeb5b24-3d5c-41ae-87c8-ae952912e4ae) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd946af13609729155716fd4fe25a9516c978d22/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39187af1-b86e-49c8-8b62-1a3a6546523b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd946af13609729155716fd4fe25a9516c978d22/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63def9ba-3666-406a-97ce-8fe273a15042) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27431c27d56bce266bf29ed176864d0efafecdc0/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9f6b7f6-d1c2-4bd0-a9f9-c0670c902111) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/27431c27d56bce266bf29ed176864d0efafecdc0/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/836c06cc-66ef-4307-95dd-a97b5783dffb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1ee44297734d00bb77fcca61f7bf98cd70df7e4a/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/461a0eeb-6ff5-446e-ad37-f05dce36f15a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1ee44297734d00bb77fcca61f7bf98cd70df7e4a/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfa58526-0196-4d83-8d9c-a6e22b8b9133) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c25e6e7d7789294000b98250a7e52a3be209c1c/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ec2f553-70a0-4378-8ca0-09253bac610f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c25e6e7d7789294000b98250a7e52a3be209c1c/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6e86095-bdd4-447e-aba8-32b2afdef8d5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/747bb6bdeaec4a7f39f6de0b20fdb136ab27fcdb/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bafd985d-781c-4f75-bae3-63c0adbee94e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/747bb6bdeaec4a7f39f6de0b20fdb136ab27fcdb/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6717c1a-7887-4bb9-b8fb-c2bd541e7aba) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6f3b6c2b8388efb8baaebddaec68f3f0747f18e/msteams-platform%2Ftoolkit%2Fadd-capability.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2269920-8e2b-42c0-a6c4-a254731f6d03) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6f3b6c2b8388efb8baaebddaec68f3f0747f18e/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51bdda24-32c8-4910-a24a-08b28aa78391) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
