### PR TITLE
[Doc Improvement][Tools and SDks-TTK-Add signle sign-on to Teams app]

### PR DESCRIPTION
**Pull request by v-vpaliwal**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9b8cbb1ce803c9fd45a74a8f512097c8a38192f7/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/934af4e4-0a54-4aab-bf69-b6529758440a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47d1ca5cde75731667a7de61ffbd5d807a8c4efe/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc45c5bc-d531-4f9e-8106-666e0c95def3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2e656a3bce026bf6187e062d13c71c44cf1a7aa/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 95 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/582f78dd-06eb-4749-b11a-e4c1d5ad440b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/634bace73dd1acad463a7c439d4ff3e196581616/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29541d8a-2e71-4c1d-874b-957d369ad7ca) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7340111fdcdc990ab0f132052991181062f40f03/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e556074-8491-41c1-8a8c-4ff4e7a6b3fb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-amprasad** [comment]
For "Add SSO using Visual Studio Code" steps:
1. Make A & B in upper case for Activity Bar in step number 2 as per the UI.
2. Can you reduce this image size. and crop the bottom part of the image below the second UI?

**Comment by v-amprasad** [comment]
image

Change "we" to you in the note.

**Comment by v-amprasad** [comment]
Under Bot project, below **update your app** and **add a new SSO command to the bot (Optional)**. The steps are numbered which needs a colon before the steps.

**Comment by v-amprasad** [comment]
image

Can you add the following before credentials:

**Comment by v-amprasad** [comment]
spelling correction. Change it to how.
image

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/202eeb203fa6f4a6f1640fa7aff5d6b5a9d0a9fc/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45549a6b-3d12-4c97-b71e-1977a8e9a74c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-single-sign-on.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f0cd3165eade5c719bbd536dd9dac32388041e1/msteams-platform%2Ftoolkit%2Fadd-single-sign-on.md) | 95 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee0da2c1-e23d-40d3-9d38-7c9dbf29ae63) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
