### PR TITLE
[Doc Improvement][Azure AD to Entra image fixes][3468386]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac0c6830e16126eb101c72c4183e361659d258d0/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/673911d3-409f-4add-ab32-7a1e52c6f665) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac0c6830e16126eb101c72c4183e361659d258d0/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-format.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b386595-6772-43e4-9883-18d4877ff8ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac0c6830e16126eb101c72c4183e361659d258d0/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b5d0193-263c-409a-bda1-fe92420b5103) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac0c6830e16126eb101c72c4183e361659d258d0/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/228f9e44-8213-4900-a8fa-6c9501f87955) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/877dc9b35e85aab5fd242fa9f14e2a683a57f781/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5dd9af10-5c95-49eb-8a25-ca8afadcf946) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/877dc9b35e85aab5fd242fa9f14e2a683a57f781/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-format.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/752acd42-1f24-4b7b-ab62-4a8d85d541c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/877dc9b35e85aab5fd242fa9f14e2a683a57f781/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02540da5-3d50-484b-a682-8246f63412b1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/877dc9b35e85aab5fd242fa9f14e2a683a57f781/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/adf63bad-1ebe-452f-a7db-8e1aab445ffd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/23fb4abb9626400f8decb5ddae325e5a53989362/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b89c3b23-f29c-4582-8a40-8631a6471b26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/23fb4abb9626400f8decb5ddae325e5a53989362/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-format.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6844069-3aa2-4d57-9f11-0f6bb31a55ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/23fb4abb9626400f8decb5ddae325e5a53989362/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3067684b-0570-4f56-bda8-ecd6f2216d3f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/23fb4abb9626400f8decb5ddae325e5a53989362/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c8d385c-c572-498d-82a2-b031c1833f4c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/878439548044c3df7790d3c6e8635e7b582c1e54/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4873f68-e170-4e35-9afb-2dd8dc352369) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/878439548044c3df7790d3c6e8635e7b582c1e54/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-format.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b1345f0-3d0a-4c9b-98ef-d8a51965aacb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/878439548044c3df7790d3c6e8635e7b582c1e54/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a9e98a4-8315-4b59-8f4a-d535356cb288) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/878439548044c3df7790d3c6e8635e7b582c1e54/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f65c130-4a49-4884-85ec-119523e70e0e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/197d07d2082e583705a1464ac8c88eb234f74ece/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aab6ffeb-30d1-412d-82b2-9d95064b6e49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/197d07d2082e583705a1464ac8c88eb234f74ece/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-format.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b65ccdd2-18cd-4a64-bb0a-de8544d18b32) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/197d07d2082e583705a1464ac8c88eb234f74ece/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0fc9ae59-0eae-407f-9228-a917b3d99c6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/197d07d2082e583705a1464ac8c88eb234f74ece/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f3b82d1-5b86-490f-94ad-0fb97ef595d5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b003e6ec512ab9ed5e7375f2304202c7f86926a/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43c311cc-1f28-4b9f-b07e-9f733f16c0bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b003e6ec512ab9ed5e7375f2304202c7f86926a/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-format.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef090b51-de3e-4966-815e-243a346c5860) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b003e6ec512ab9ed5e7375f2304202c7f86926a/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a4c688d-fc64-45a5-a8aa-a542465f508b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b003e6ec512ab9ed5e7375f2304202c7f86926a/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ebd86623-1157-436c-aea2-a599cdebac75) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b003e6ec512ab9ed5e7375f2304202c7f86926a/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 93 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f332105c-5cdb-4552-92b7-04644c358683) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56e5289f3c2288bd3e5cabc7cfb59f6e4fd474a2/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ce0f3e2-ac56-467a-b47f-c192cc55f6cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56e5289f3c2288bd3e5cabc7cfb59f6e4fd474a2/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-format.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/816b73fe-394f-4a64-98ee-15e74a8efb4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56e5289f3c2288bd3e5cabc7cfb59f6e4fd474a2/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e57a033-ecc5-4c61-9231-3092985a9e8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56e5289f3c2288bd3e5cabc7cfb59f6e4fd474a2/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f788d145-11e7-44d4-9ee0-68d64e7fdda4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/56e5289f3c2288bd3e5cabc7cfb59f6e4fd474a2/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 93 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eef5a2a0-1cf3-4f75-8e36-5dd7ce6358c9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99b969b4db237ba141e585b6dce5a70b50c934f9/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3d2edbe-ca96-4eb9-8b99-74ff4163bac9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99b969b4db237ba141e585b6dce5a70b50c934f9/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-format.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/891dc7eb-e361-416a-8e20-28a957dbc05c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99b969b4db237ba141e585b6dce5a70b50c934f9/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3e5227a-ff8d-49bf-a05b-1e492fdf521b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99b969b4db237ba141e585b6dce5a70b50c934f9/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b7480b0-173f-4003-ad13-6146a8a1b374) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99b969b4db237ba141e585b6dce5a70b50c934f9/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 93 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a1fceb0-43bd-4be9-9713-cbe5cd27201f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8e8f195db0e28eea90ac29430e4a7c59504a6d6/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e757938-780a-4e68-89c5-40bdaaa862ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8e8f195db0e28eea90ac29430e4a7c59504a6d6/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fcards-format.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d860ea8-2206-4b6a-8ccf-a54ee0c59846) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8e8f195db0e28eea90ac29430e4a7c59504a6d6/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0983272-3032-4cb6-a5f6-25e55fda206c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8e8f195db0e28eea90ac29430e4a7c59504a6d6/msteams-platform%2Ftoolkit%2Fprovision.md) | 92 | 64 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84b44777-0628-4b0d-b29d-3a5f0e1ef07b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8e8f195db0e28eea90ac29430e4a7c59504a6d6/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 93 | 62 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21fd12ca-ae89-4a19-a7dd-0bac9e472960) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
