### PR TITLE
[Doc Improvement][SBS edits and UI changes][2885096]

### PR DESCRIPTION
**Pull request by v-silakshmi**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a3d160e77aebcaa772cca661590f3ad463a24104/msteams-platform%2Fsbs-bots-with-sso.yml) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d06fe3b-1f28-4aa5-89b8-535bc586c94a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a3d160e77aebcaa772cca661590f3ad463a24104/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 87 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47b17be3-77ca-4798-aa53-b4583ecff181) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a3d160e77aebcaa772cca661590f3ad463a24104/msteams-platform%2Fsbs-tab-device-permissions.yml) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dcd87056-9a3d-42bd-b36e-7b2063a042ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a3d160e77aebcaa772cca661590f3ad463a24104/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e4cf2b4-24f5-412e-b39e-a831176f4541) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c431e20477a45d90424ef1f42a9cc801b277d959/msteams-platform%2Fsbs-bots-with-sso.yml) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e328a00-772d-4e8f-b9ba-6e791d888daa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c431e20477a45d90424ef1f42a9cc801b277d959/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 87 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fdde325-ec43-4235-8d0f-1e9c6969eb4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c431e20477a45d90424ef1f42a9cc801b277d959/msteams-platform%2Fsbs-tab-device-permissions.yml) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28fcf46c-494d-48e6-8af3-e5f5efe8bd46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c431e20477a45d90424ef1f42a9cc801b277d959/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab9f89d5-a163-481d-954b-9531c0895510) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d6fb799a0fa69624665d46db60391cc5fc9a7ce2/msteams-platform%2Fsbs-bots-with-sso.yml) | 91 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/852bb6bd-823c-46ab-bd37-e006d49e93ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d6fb799a0fa69624665d46db60391cc5fc9a7ce2/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 87 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a0f7072-654c-4e76-a9e4-5f7ca876a7c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d6fb799a0fa69624665d46db60391cc5fc9a7ce2/msteams-platform%2Fsbs-tab-device-permissions.yml) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b17e2892-daab-4f88-a461-851b19074287) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d6fb799a0fa69624665d46db60391cc5fc9a7ce2/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a522477-2ef2-484e-900f-74d4f554e1f0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dc1f550077637d37e83773517ae0b221b3d31c75/msteams-platform%2Fsbs-bots-with-sso.yml) | 86 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ecd9d52-d319-42c2-9a65-4954a8412e5a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dc1f550077637d37e83773517ae0b221b3d31c75/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 81 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90b7c4a0-04c5-4839-8124-cf77bf09ebdf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dc1f550077637d37e83773517ae0b221b3d31c75/msteams-platform%2Fsbs-tab-device-permissions.yml) | 86 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53038d0d-f7ed-4db2-8cbb-6f128aaaa473) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dc1f550077637d37e83773517ae0b221b3d31c75/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 84 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10b5058d-96cc-45ec-b474-ab0cf885f46d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5bc012708d8178e7d405b01e546ea722d8692c9b/msteams-platform%2Fsbs-bots-with-sso.yml) | 86 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2b390fa-5138-4cf9-8f71-8fb8efa6d07b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5bc012708d8178e7d405b01e546ea722d8692c9b/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 81 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90a260ba-b974-4a64-9cba-4a3d4bb200f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5bc012708d8178e7d405b01e546ea722d8692c9b/msteams-platform%2Fsbs-tab-device-permissions.yml) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7807c94c-f3b6-4500-93c1-46fbb6513de4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5bc012708d8178e7d405b01e546ea722d8692c9b/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 84 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc71abd1-dcae-4b51-a43b-446a82998ee5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/617cb87a2516211244cc74fd7a9caad95ad2b93d/msteams-platform%2Fsbs-bots-with-sso.yml) | 86 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/392fd4df-2623-4d1d-b017-1f543b76cc08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/617cb87a2516211244cc74fd7a9caad95ad2b93d/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 82 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05798a72-39bf-4550-87aa-4c49731008ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/617cb87a2516211244cc74fd7a9caad95ad2b93d/msteams-platform%2Fsbs-tab-device-permissions.yml) | 85 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/afecc2a2-01f0-4d2d-b42a-a564fcf0e53e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/617cb87a2516211244cc74fd7a9caad95ad2b93d/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 84 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ef47b98-05ae-41ef-8a4f-c58bcb7c2f22) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2381530f9ed2c39c17852d2e1102248ca4ece80e/msteams-platform%2Fsbs-bots-with-sso.yml) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3917f611-28b5-4b87-8500-97cc80e4f966) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2381530f9ed2c39c17852d2e1102248ca4ece80e/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ae27bc4-596a-4c0a-9f46-7057d859e18f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2381530f9ed2c39c17852d2e1102248ca4ece80e/msteams-platform%2Fsbs-tab-device-permissions.yml) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44c934f2-e6e6-4a86-8570-e6df67832022) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2381530f9ed2c39c17852d2e1102248ca4ece80e/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1fa0df3-e41b-4c34-838a-b5c932562ecc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9661091516171169aac5bb4586ee6569da63fda5/msteams-platform%2Fsbs-bots-with-sso.yml) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd4de3b2-d34b-4df7-89a0-df26fc47834a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9661091516171169aac5bb4586ee6569da63fda5/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db0446f1-e618-46d0-aba1-c884ff72a313) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9661091516171169aac5bb4586ee6569da63fda5/msteams-platform%2Fsbs-tab-device-permissions.yml) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2d1a6cd-5ac5-47d0-bee2-0757ce47efad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9661091516171169aac5bb4586ee6569da63fda5/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fa96006-6946-436b-b2ae-1c2128d08c91) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/594d02fb87d061e0a847826b4da2eb9c17740632/msteams-platform%2Fsbs-bots-with-sso.yml) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56fcf254-cf8a-4b54-8628-d23ab18bd97f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/594d02fb87d061e0a847826b4da2eb9c17740632/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 87 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e2fc769-48a3-4c7c-81cb-6b6d7299d8e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tab-device-permissions.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/594d02fb87d061e0a847826b4da2eb9c17740632/msteams-platform%2Fsbs-tab-device-permissions.yml) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9af7d5c-af67-48e7-af0f-b34a542b9789) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/594d02fb87d061e0a847826b4da2eb9c17740632/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 89 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ebc600f7-4a20-48e2-acb9-4523fb303972) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
