### PR TITLE
Samples page

### PR DESCRIPTION
**Pull request by charlesprakash**
Contains the list of all samples for MS teams.

### CODE REVIEW

**Comment by charlesprakash** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fsamples%2Fcode-samples.md)

<a name="msteams-platform%2Fsamples%2Fcode-samples.md"></a>
### [msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md)
 - **Line 47**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).
 - **Line 48**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).
 - **Line 73**: **[Warning]** Invalid file link:(~/).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C20%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201711202102241824-13%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=F%2BswBf0HSRWVW2roksfs173BlaRnJk1FrnkoJdBSFtU%3D&st=2017-11-20T20%3A58%3A13Z&se=2017-12-21T21%3A03%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by msftdherron** [comment]
I'd suggest removing the TBD section for now until we have some content.

**Comment by charlesprakash** [comment]
Removed the TBD section. I recall Bill saying that some samples are out of date. Anybody know about them?

**Comment by charlesprakash** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fsamples%2Fcode-samples.md)

<a name="msteams-platform%2Fsamples%2Fcode-samples.md"></a>
### [msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md)
 - **Line 47**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).
 - **Line 48**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C21%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201711211725426246-13%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Q7KQsRi7tCq0AWx6ro9TUJH%2B%2Bf%2FO4%2FGM2SG8zEWkHy0%3D&st=2017-11-21T17%3A21%3A29Z&se=2017-12-22T17%3A26%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by charlesprakash** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fsamples%2Fcode-samples.md)

<a name="msteams-platform%2Fsamples%2Fcode-samples.md"></a>
### [msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md)
 - **Line 47**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).
 - **Line 48**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C27%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201711272307215641-13%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3yldlq01CZXsAFAm6zxNklGGS12yS%2Bk%2FhWC%2BktzCOZQ%3D&st=2017-11-27T23%3A03%3A46Z&se=2017-12-28T23%3A08%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by charlesprakash** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fsamples%2Fcode-samples.md)

<a name="msteams-platform%2Fsamples%2Fcode-samples.md"></a>
### [msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md)
 - **Line 47**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).
 - **Line 48**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C28%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201711282247020940-13%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=soEliZd%2B5xE1BfjenDqpnqSvuCpQJOrhZJFQdXhyjR8%3D&st=2017-11-28T22%3A42%3A55Z&se=2017-12-29T22%3A47%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by charlesprakash** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fsamples%2Fcode-samples.md)

<a name="msteams-platform%2Fsamples%2Fcode-samples.md"></a>
### [msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md)
 - **Line 47**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).
 - **Line 48**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201711290019249933-13%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1NJae2YfXEeQ91KIVuqMIdy7qprLjRH9lu%2BUjqQlsCU%3D&st=2017-11-29T00%3A15%3A17Z&se=2017-12-30T00%3A20%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by charlesprakash** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fsamples%2Fcode-samples.md)
[.markdownlint.json](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/.markdownlint.json) | :white_check_mark:Succeeded | |

<a name="msteams-platform%2Fsamples%2Fcode-samples.md"></a>
### [msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md)
 - **Line 47**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).
 - **Line 48**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201711290021416482-13%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QBmMH96n2SzXDR84UCZa28Px6L01D1JbLLiZhlFPHw8%3D&st=2017-11-29T00%3A17%3A41Z&se=2017-12-30T00%3A22%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by charlesprakash** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fsamples%2Fcode-samples.md)
[.markdownlint.json](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/.markdownlint.json) | :white_check_mark:Succeeded | |

<a name="msteams-platform%2Fsamples%2Fcode-samples.md"></a>
### [msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md)
 - **Line 50**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).
 - **Line 51**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201711290044506693-13%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8VBL8PIQ3g%2FnZuow90YyHhh4Y7e7ozRYvgyR1R7F%2FZU%3D&st=2017-11-29T00%3A45%3A47Z&se=2017-12-30T00%3A50%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by charlesprakash** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fsamples%2Fcode-samples.md)
[.markdownlint.json](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/.markdownlint.json) | :white_check_mark:Succeeded | |

<a name="msteams-platform%2Fsamples%2Fcode-samples.md"></a>
### [msteams-platform/samples/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/prakash-samplesIndex/msteams-platform/samples/code-samples.md)
 - **Line 50**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).
 - **Line 51**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201711290050461734-13%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yKgGiP8A9gcB%2FcTWRAOUUhyBImp485mVXXMAhk72%2Bu8%3D&st=2017-11-29T00%3A49%3A34Z&se=2017-12-30T00%3A54%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
