### PR TITLE
[Doc Improvement][AI SDK- support][4173168]

### PR DESCRIPTION
**Pull request by v-shalinir**
Adding links for support and feedback pages for AI SDK topic.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/teams-conversational-ai/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06b420feb5a5d616d788b923692053fa8a2757c5/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fteams-conversation-ai-overview.md) | 91 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c682b19-3302-48ee-bf1b-0046a34a91c5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/teams-conversational-ai/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c899f0856b14811c2281a63eee10dfdee529a83/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fteams-conversation-ai-overview.md) | 91 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65031bfa-12a8-485f-8abb-85d3f8051931) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/teams-conversational-ai/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bf681f576ca8341bb144714822ac025c45f1f510/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fteams-conversation-ai-overview.md) | 91 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34409c21-407d-4cf4-930b-64641b410f2f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by aacebo — APPROVED** [review]

**Review by predeep009 — APPROVED** [review]

**Review by Wajeed-msft — APPROVED** [review]

**Review by TheBluLion — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/teams-conversational-ai/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0cf3a089834b0f54c393be02d2216439d575d7b6/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fteams-conversation-ai-overview.md) | 91 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7875c13-82e8-4fe3-b07b-0d526e97e626) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/teams-conversational-ai/teams-conversation-ai-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9342c7ae57ce8e3d795ba319d94e9d365583c33e/msteams-platform%2Fbots%2Fhow-to%2Fteams-conversational-ai%2Fteams-conversation-ai-overview.md) | 91 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcbc0e3e-ee0d-4148-a6fd-2535654c6b3b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
