### PR TITLE
[Doc Improvement][webhook note updated][3937634]

### PR DESCRIPTION
**Pull request by v-bvishnu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/deprecation-note.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b230044802cdd12145d0c1507595e2d938b79cfc/msteams-platform%2Fincludes%2Fdeprecation-note.md) | 81 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d5dae70-6359-47fe-9939-0a58d8042b19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b230044802cdd12145d0c1507595e2d938b79cfc/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fadd-incoming-webhook.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65e25bf1-25f2-4b55-a513-10403822d66f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b230044802cdd12145d0c1507595e2d938b79cfc/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc82c017-d2d0-4cc9-92fc-d3b2a1a37327) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b230044802cdd12145d0c1507595e2d938b79cfc/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-using.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f84d6b2-12f9-4d61-8944-0566a4cb6127) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b230044802cdd12145d0c1507595e2d938b79cfc/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ada4b037-9ba4-4e4a-a387-328161f85644) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/deprecation-note.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20e8f23773d1ccd49c5b965e485fe7d7fdc9d7c/msteams-platform%2Fincludes%2Fdeprecation-note.md) | 86 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2942e91-13c1-482e-9c7c-90932888a506) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20e8f23773d1ccd49c5b965e485fe7d7fdc9d7c/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fadd-incoming-webhook.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d3cc53f-769d-408d-be9c-e428ca3da1bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20e8f23773d1ccd49c5b965e485fe7d7fdc9d7c/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/339ce8de-c5c3-493b-963a-90087dc728bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20e8f23773d1ccd49c5b965e485fe7d7fdc9d7c/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-using.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3a1f1fd-6d59-4ab7-b97d-8fbff6f1d316) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e20e8f23773d1ccd49c5b965e485fe7d7fdc9d7c/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74596b1f-a646-4d09-922e-714083dea60b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/deprecation-note.md](https://github.com/MicrosoftDocs/msteams-docs/blob/346eff667d7d3c1c3305bd787e5debcc869b9d2e/msteams-platform%2Fincludes%2Fdeprecation-note.md) | 86 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df73e2e0-9304-4713-9aa9-de9f1861e4c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/346eff667d7d3c1c3305bd787e5debcc869b9d2e/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fadd-incoming-webhook.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d140a15-0477-4584-a2d4-9777122a1bff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/346eff667d7d3c1c3305bd787e5debcc869b9d2e/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7bca6742-2bc2-4b7b-92cc-a560911334a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/346eff667d7d3c1c3305bd787e5debcc869b9d2e/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-using.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ec50f2f-3eff-4799-be68-7f3e8e545f9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/346eff667d7d3c1c3305bd787e5debcc869b9d2e/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73b873b0-c56c-48ea-b8f3-c0c749d6e19b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/deprecation-note.md](https://github.com/MicrosoftDocs/msteams-docs/blob/544ebd820c6c6e734a76fe42e4d5fd490b82db88/msteams-platform%2Fincludes%2Fdeprecation-note.md) | 93 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eef07595-8b3d-4c47-81a1-bc1cd8be83e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/544ebd820c6c6e734a76fe42e4d5fd490b82db88/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fadd-incoming-webhook.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fc120d9-cf92-4293-9eb5-8a0401c53a5d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/544ebd820c6c6e734a76fe42e4d5fd490b82db88/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90a933ff-49a6-41f5-a0fc-1359620a2a35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/544ebd820c6c6e734a76fe42e4d5fd490b82db88/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-using.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c72184a8-9b81-4e22-88b2-cd984abfe228) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/544ebd820c6c6e734a76fe42e4d5fd490b82db88/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95a573d1-064b-42ae-b4c4-0b2bb40827c6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/deprecation-note.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d292b23be7393018a7e48a34bf188a679a944eb/msteams-platform%2Fincludes%2Fdeprecation-note.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf06dabf-7c1a-4efb-88ed-74e47bbbcdf1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d292b23be7393018a7e48a34bf188a679a944eb/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fadd-incoming-webhook.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89c558a8-2d24-44e2-8009-e8013947c63a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d292b23be7393018a7e48a34bf188a679a944eb/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c721bb7-3dc3-42ec-a38d-afc2bb090164) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d292b23be7393018a7e48a34bf188a679a944eb/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-using.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9aa420aa-ff85-44ac-b72e-6b5eee896e8a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d292b23be7393018a7e48a34bf188a679a944eb/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e72e228-59af-4c67-8064-be4c182467af) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by trenthazy — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/deprecation-note.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0462d1b17644378159260bb906fbfead9570a30/msteams-platform%2Fincludes%2Fdeprecation-note.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83863b6e-580d-4625-b2a6-1ca8f2080685) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0462d1b17644378159260bb906fbfead9570a30/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fadd-incoming-webhook.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/322fbd6b-c6df-482a-b7bd-1dbc7c29b5a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0462d1b17644378159260bb906fbfead9570a30/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bc26b78-9376-4c21-a64c-5930136b3340) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0462d1b17644378159260bb906fbfead9570a30/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-using.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d227501-e901-4b64-b5ca-f19dae5d8406) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0462d1b17644378159260bb906fbfead9570a30/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14d4d244-3af7-40f2-a07d-bef0ebc83451) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/deprecation-note.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a0fa8e46364fe62e8757b3f6c051cefb4bfcb3c/msteams-platform%2Fincludes%2Fdeprecation-note.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aea76feb-c93e-41ff-976f-1c6838f0b955) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a0fa8e46364fe62e8757b3f6c051cefb4bfcb3c/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fadd-incoming-webhook.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/854e9854-9bb3-45c5-a2e5-074a0f5fc6cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a0fa8e46364fe62e8757b3f6c051cefb4bfcb3c/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-creating.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3532b151-171a-417a-9050-188869f09fc8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a0fa8e46364fe62e8757b3f6c051cefb4bfcb3c/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fconnectors-using.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/209cfc39-aaa4-46d0-8f46-7592b0169832) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a0fa8e46364fe62e8757b3f6c051cefb4bfcb3c/msteams-platform%2Fwebhooks-and-connectors%2Fwhat-are-webhooks-and-connectors.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/941cee53-81f8-4b0f-af95-6340a1a22ce6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
