### PR TITLE
replaced obsolete links

### PR DESCRIPTION
**Pull request by NormSohl**
Vishrut pointed out some obsolete links earlier today.  These are fixed in this branch.

### CODE REVIEW

**Comment by charlesprakash** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/get-started/design.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fget-started%2Fdesign.md)
[msteams-platform/publishing/apps-publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/publishing/apps-publish.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fpublishing%2Fapps-publish.md)
[msteams-platform/scenarios/bots-channel-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/scenarios/bots-channel-conversations.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fscenarios%2Fbots-channel-conversations.md)
[msteams-platform/scenarios/bots-personal-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/scenarios/bots-personal-conversations.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fscenarios%2Fbots-personal-conversations.md)

<a name="msteams-platform%2Fget-started%2Fdesign.md"></a>
### [msteams-platform/get-started/design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/get-started/design.md)
 - **Line 49**: **[Warning]** Invalid file link:(~/concepts/bots/bots-notifications).

<a name="msteams-platform%2Fpublishing%2Fapps-publish.md"></a>
### [msteams-platform/publishing/apps-publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/publishing/apps-publish.md)
 - **Line 10**: **[Warning]** Invalid file link:(~/publishing/apps-package).
 - **Line 10**: **[Warning]** Invalid file link:(~/resources/schema/manifest-schema).
 - **Line 13**: **[Warning]** Invalid file link:(~/resources/design/overview).
 - **Line 51**: **[Warning]** Invalid file link:(~/publishing/apps-package).
 - **Line 51**: **[Warning]** Invalid file link:(~/publishing/office-store-checklist).
 - **Line 56**: **[Warning]** Invalid file link:(~/publishing/office-store-guidance).
 - **Line 89**: **[Warning]** Invalid file link:(~/resources/schema/manifest-schema#bots).

<a name="msteams-platform%2Fscenarios%2Fbots-channel-conversations.md"></a>
### [msteams-platform/scenarios/bots-channel-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/scenarios/bots-channel-conversations.md)
 - **Line 11**: **[Warning]** Invalid file link:(~/publishing/apps-package).
 - **Line 11**: **[Warning]** Invalid file link:(~/concepts/apps/apps-sideload).
 - **Line 22**: **[Warning]** Invalid file link:(~/concepts/apps/apps-overview).
 - **Line 32**: **[Warning]** Invalid file link:(~/concepts/bots/bots-conversations#teams-channel-data).
 - **Line 73**: **[Warning]** Invalid file link:(~/concepts/bots/bots-notifications#team-member-or-bot-addition).
 - **Line 75**: **[Warning]** Invalid file link:(~/scenarios/bots-personal-conversations#starting-a-11-conversation).
 - **Line 75**: **[Warning]** Invalid file link:(~/concepts/bots/bots-context#fetching-the-team-roster).
 - **Line 83**: **[Warning]** Invalid file link:(~/resources/design/overview).
 - **Line 140**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).
 - **Line 225**: **[Warning]** Invalid file link:(~/concepts/bots/bots-context).

<a name="msteams-platform%2Fscenarios%2Fbots-personal-conversations.md"></a>
### [msteams-platform/scenarios/bots-personal-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/scenarios/bots-personal-conversations.md)
 - **Line 9**: **[Warning]** Invalid file link:(~/scenarios/bots-channel-conversations).
 - **Line 21**: **[Warning]** Invalid file link:(~/concepts/bots/bots-notifications#team-member-or-bot-addition).
 - **Line 21**: **[Warning]** Invalid file link:(~/scenarios/bots-channel-conversations).
 - **Line 21**: **[Warning]** Invalid file link:(~/concepts/bots/bots-context#fetching-the-team-roster).
 - **Line 115**: **[Warning]** Invalid file link:(~/resources/design/overview).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201712142355136560-22%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xuOLoOamdEZnArKORFhSvTE9e6d6GgKi5WwJWmhPpwo%3D&st=2017-12-14T23%3A51%3A22Z&se=2018-01-14T23%3A56%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by charlesprakash** [comment]
@billbliss Done. If you guys are OK, please approve this change and I can squash and merge it. Also, we need the samples repo to be made public as well.

**Comment by charlesprakash** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/get-started/design.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fget-started%2Fdesign.md)
[msteams-platform/publishing/apps-publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/publishing/apps-publish.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fpublishing%2Fapps-publish.md)
[msteams-platform/scenarios/bots-channel-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/scenarios/bots-channel-conversations.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fscenarios%2Fbots-channel-conversations.md)
[msteams-platform/scenarios/bots-personal-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/scenarios/bots-personal-conversations.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fscenarios%2Fbots-personal-conversations.md)

<a name="msteams-platform%2Fget-started%2Fdesign.md"></a>
### [msteams-platform/get-started/design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/get-started/design.md)
 - **Line 11**: **[Warning]** Invalid file link:(~/resources/design/overview).
 - **Line 49**: **[Warning]** Invalid file link:(~/concepts/bots/bots-notifications).

<a name="msteams-platform%2Fpublishing%2Fapps-publish.md"></a>
### [msteams-platform/publishing/apps-publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/publishing/apps-publish.md)
 - **Line 10**: **[Warning]** Invalid file link:(~/publishing/apps-package).
 - **Line 10**: **[Warning]** Invalid file link:(~/resources/schema/manifest-schema).
 - **Line 13**: **[Warning]** Invalid file link:(~/resources/design/overview).
 - **Line 51**: **[Warning]** Invalid file link:(~/publishing/apps-package).
 - **Line 51**: **[Warning]** Invalid file link:(~/publishing/office-store-checklist).
 - **Line 56**: **[Warning]** Invalid file link:(~/publishing/office-store-guidance).
 - **Line 89**: **[Warning]** Invalid file link:(~/resources/schema/manifest-schema#bots).

<a name="msteams-platform%2Fscenarios%2Fbots-channel-conversations.md"></a>
### [msteams-platform/scenarios/bots-channel-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/scenarios/bots-channel-conversations.md)
 - **Line 11**: **[Warning]** Invalid file link:(~/publishing/apps-package).
 - **Line 11**: **[Warning]** Invalid file link:(~/concepts/apps/apps-sideload).
 - **Line 22**: **[Warning]** Invalid file link:(~/concepts/apps/apps-overview).
 - **Line 32**: **[Warning]** Invalid file link:(~/concepts/bots/bots-conversations#teams-channel-data).
 - **Line 73**: **[Warning]** Invalid file link:(~/concepts/bots/bots-notifications#team-member-or-bot-addition).
 - **Line 75**: **[Warning]** Invalid file link:(~/scenarios/bots-personal-conversations#starting-a-11-conversation).
 - **Line 75**: **[Warning]** Invalid file link:(~/concepts/bots/bots-context#fetching-the-team-roster).
 - **Line 83**: **[Warning]** Invalid file link:(~/resources/design/overview).
 - **Line 140**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).
 - **Line 225**: **[Warning]** Invalid file link:(~/concepts/bots/bots-context).

<a name="msteams-platform%2Fscenarios%2Fbots-personal-conversations.md"></a>
### [msteams-platform/scenarios/bots-personal-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/Norm-designguidelines/msteams-platform/scenarios/bots-personal-conversations.md)
 - **Line 9**: **[Warning]** Invalid file link:(~/scenarios/bots-channel-conversations).
 - **Line 21**: **[Warning]** Invalid file link:(~/concepts/bots/bots-notifications#team-member-or-bot-addition).
 - **Line 21**: **[Warning]** Invalid file link:(~/scenarios/bots-channel-conversations).
 - **Line 21**: **[Warning]** Invalid file link:(~/concepts/bots/bots-context#fetching-the-team-roster).
 - **Line 115**: **[Warning]** Invalid file link:(~/resources/design/overview).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C15%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201712152004405292-22%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=pY5DXcBmo2CqCE5NjuIL40y8QPzprABx2dJnEBpxZbQ%3D&st=2017-12-15T20%3A00%3A32Z&se=2018-01-15T20%3A05%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by NormSohl** [comment]
made bill's change

**Pull request merged**
