### PR TITLE
[Doc improvement][TOC Visual Studio update][3094895]

### PR DESCRIPTION
**Pull request by v-bvishnu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/58614ec512d044d5ad5261f34a8ae1c7ae7cec2d/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27e74ce2-e31e-432f-b5e4-5b845b30eac3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58614ec512d044d5ad5261f34a8ae1c7ae7cec2d/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59708edb-5303-4da5-9a1f-b55f76a233ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58614ec512d044d5ad5261f34a8ae1c7ae7cec2d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-v4.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05ac230e-a977-4c06-a383-34e0ba7dc077) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/tools-prerequisites-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58614ec512d044d5ad5261f34a8ae1c7ae7cec2d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ftools-prerequisites-v4.md) | 98 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d91251e-eed6-4884-adcd-b1ea07889148) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58614ec512d044d5ad5261f34a8ae1c7ae7cec2d/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29fde780-8872-4b3b-8f10-cd2a58ff36af) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9d3f6c9ba0ff528651421e1139d1c8d4ab56e5c6/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d74b4d3a-856b-4f93-b58f-ae4c44ec0ecd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d3f6c9ba0ff528651421e1139d1c8d4ab56e5c6/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ba9cd18-158f-44bf-b53f-91a35590e764) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d3f6c9ba0ff528651421e1139d1c8d4ab56e5c6/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-v4.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/954c8dd5-fe5a-49c3-aa28-6b477065c150) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/tools-prerequisites-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d3f6c9ba0ff528651421e1139d1c8d4ab56e5c6/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ftools-prerequisites-v4.md) | 98 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23a98bfb-7e1f-49ff-a34c-d2ce2c9af8db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d3f6c9ba0ff528651421e1139d1c8d4ab56e5c6/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2f2a258-fc8e-4e75-b104-6ef4d640d6c0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b277c1a35abc83f43bda72245f82f35066e6d7ee/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/532484b0-64b3-490d-b149-b38cd536079f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b277c1a35abc83f43bda72245f82f35066e6d7ee/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8e0a7cc-00de-4ad4-bd0a-23ca130c1639) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b277c1a35abc83f43bda72245f82f35066e6d7ee/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-v4.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3987d8d-38df-4446-bd8c-a33fcc513041) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/tools-prerequisites-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b277c1a35abc83f43bda72245f82f35066e6d7ee/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ftools-prerequisites-v4.md) | 98 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10644b8d-ec52-4a67-a4ef-5005ad12c699) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b277c1a35abc83f43bda72245f82f35066e6d7ee/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f3ebc83-4868-4a00-b2a5-a89a386af19b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/05d2be17ddc4fe061770497d3661c016220c7441/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/296a6228-578d-423d-ac5d-3ec6031b9709) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-How-to guides-v5.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05d2be17ddc4fe061770497d3661c016220c7441/msteams-platform%2Ftoolkit%2Fadd-How-to%20guides-v5.md) | 94 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fe2bfa6c-338d-42d8-bcd4-35b80bf5249b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05d2be17ddc4fe061770497d3661c016220c7441/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4cde676-bfe8-4fe9-8e70-d95a3306bfa9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/add-capability-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05d2be17ddc4fe061770497d3661c016220c7441/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fadd-capability-v4.md) | 100 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/583f0272-d180-46c1-8933-a0ccf3b173cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05d2be17ddc4fe061770497d3661c016220c7441/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-v4.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c563f86-0487-4062-918e-cf99b713d90c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/tools-prerequisites-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05d2be17ddc4fe061770497d3661c016220c7441/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ftools-prerequisites-v4.md) | 98 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4d16bfd-6987-4bbb-93c0-f88778c35e7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/tools-prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/05d2be17ddc4fe061770497d3661c016220c7441/msteams-platform%2Ftoolkit%2Ftools-prerequisites.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/918972fc-d1b8-49c0-a663-fc368bb658a9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
