### PR TITLE
[Doc Improvement][SEO meta description update][3939546]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5248ea7433275d11bf8bb983513e6af574a9679b/msteams-platform%2Fsbs-gs-notificationbot.yml) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29f095b9-7360-43cc-b65e-91946fbf1a75) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5248ea7433275d11bf8bb983513e6af574a9679b/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e051bded-8744-47b4-ba40-88bea39d8732) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5248ea7433275d11bf8bb983513e6af574a9679b/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/525f16f5-8238-44f8-8901-a1136e7c77d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5248ea7433275d11bf8bb983513e6af574a9679b/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcef1108-0ff4-4d62-874e-a18593405156) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4dc27c73a42fff2be29d7ebf16449c4a294f521a/msteams-platform%2Fsbs-bots-with-sso.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/772f196d-f6b1-458d-87b2-7376eec3b30a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4dc27c73a42fff2be29d7ebf16449c4a294f521a/msteams-platform%2Fsbs-calling-and-meeting.yml) | 88 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2421907a-b412-4248-ab19-abf6c0e029c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4dc27c73a42fff2be29d7ebf16449c4a294f521a/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 79 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/364d225d-8b47-4151-9061-44bd16ed6b24) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4dc27c73a42fff2be29d7ebf16449c4a294f521a/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7b367eb-370c-4d82-a60d-3e0236837eb0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-graphactivity-feedbroadcast.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4dc27c73a42fff2be29d7ebf16449c4a294f521a/msteams-platform%2Fsbs-graphactivity-feedbroadcast.yml) | 89 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3473c9df-8ec7-49c4-b4c2-96ee08128dec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-commandbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4dc27c73a42fff2be29d7ebf16449c4a294f521a/msteams-platform%2Fsbs-gs-commandbot.yml) | 88 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/838eb0be-5986-44ce-bfd9-4fc402c4e0bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4dc27c73a42fff2be29d7ebf16449c4a294f521a/msteams-platform%2Fsbs-gs-notificationbot.yml) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1eb8f000-d4bc-4ef7-b7b1-13050882457d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4dc27c73a42fff2be29d7ebf16449c4a294f521a/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd279d79-b36e-4d55-ba28-ff9086203a46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4dc27c73a42fff2be29d7ebf16449c4a294f521a/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d48e111a-9b67-41ce-a411-4a0e2d7df4fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4dc27c73a42fff2be29d7ebf16449c4a294f521a/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c61e4b6-7e4d-403c-8087-8831fb36468e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fe0dd39a359bec943e615fa3d4c748c6d82f20b3/msteams-platform%2Fsbs-bots-with-sso.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/871b9017-a016-4bc1-bf70-fe724e9cc99f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fe0dd39a359bec943e615fa3d4c748c6d82f20b3/msteams-platform%2Fsbs-calling-and-meeting.yml) | 88 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c538d85-d617-493c-81c2-5d4be7ac4bd3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fe0dd39a359bec943e615fa3d4c748c6d82f20b3/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 79 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd36005a-7053-47d9-93d8-dfc1af4c07ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fe0dd39a359bec943e615fa3d4c748c6d82f20b3/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6e18ad9-8622-4283-b107-83e61a1b439d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-graphactivity-feedbroadcast.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fe0dd39a359bec943e615fa3d4c748c6d82f20b3/msteams-platform%2Fsbs-graphactivity-feedbroadcast.yml) | 89 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18eea136-f6da-4e03-851e-c207a721e58f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-commandbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fe0dd39a359bec943e615fa3d4c748c6d82f20b3/msteams-platform%2Fsbs-gs-commandbot.yml) | 88 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5852d93e-b0a3-4a77-b7fd-e95b40928cc6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fe0dd39a359bec943e615fa3d4c748c6d82f20b3/msteams-platform%2Fsbs-gs-notificationbot.yml) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57eb7aad-e63d-46a8-b4b9-44d62a05937f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fe0dd39a359bec943e615fa3d4c748c6d82f20b3/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2db81350-2e95-462d-a38f-f82de41e6736) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fe0dd39a359bec943e615fa3d4c748c6d82f20b3/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a03f7ce5-a0ae-42b3-b240-e8898f04b0b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fe0dd39a359bec943e615fa3d4c748c6d82f20b3/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3e10cb93-c918-4d81-99ff-ecbde7a4e459) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-sdhakshina — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c2093e60f96ed34e85390cf5c334008b9eb36599/msteams-platform%2Fsbs-bots-with-sso.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8db9a651-e266-4b0f-9921-813ec2d808bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c2093e60f96ed34e85390cf5c334008b9eb36599/msteams-platform%2Fsbs-calling-and-meeting.yml) | 88 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e32c28e6-2267-4bfb-9dee-972fda287aab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c2093e60f96ed34e85390cf5c334008b9eb36599/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f27a64b-f3a1-4127-ab48-9488de8b51f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-graphactivity-feedbroadcast.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c2093e60f96ed34e85390cf5c334008b9eb36599/msteams-platform%2Fsbs-graphactivity-feedbroadcast.yml) | 89 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ecef52b-da3d-475e-acf0-6658a73219cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-commandbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c2093e60f96ed34e85390cf5c334008b9eb36599/msteams-platform%2Fsbs-gs-commandbot.yml) | 88 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd1ad439-26ec-4db4-94f6-14e6265b604f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c2093e60f96ed34e85390cf5c334008b9eb36599/msteams-platform%2Fsbs-gs-notificationbot.yml) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d572e0c-e054-4d6c-a1dd-4a9c355289b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c2093e60f96ed34e85390cf5c334008b9eb36599/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d88717e-34b0-4c73-8a96-6d9ef9635b63) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c2093e60f96ed34e85390cf5c334008b9eb36599/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a81db72c-cde5-4308-afba-0594af57ebcf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c2093e60f96ed34e85390cf5c334008b9eb36599/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b26e507c-6e7f-46ea-8323-7c701df81ad5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ccdf3f89b93d36221701a42b99584f5fcdac2b7f/msteams-platform%2Fsbs-bots-with-sso.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da90208e-f34a-4495-920a-a01433c62eb0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ccdf3f89b93d36221701a42b99584f5fcdac2b7f/msteams-platform%2Fsbs-calling-and-meeting.yml) | 88 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdc97438-ba01-4666-893b-1fa9da71c05a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ccdf3f89b93d36221701a42b99584f5fcdac2b7f/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf52dd00-588c-4b7f-a634-8f166f8f3cc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-graphactivity-feedbroadcast.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ccdf3f89b93d36221701a42b99584f5fcdac2b7f/msteams-platform%2Fsbs-graphactivity-feedbroadcast.yml) | 89 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad876cfa-72ba-4def-bb59-07c1a86073a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-commandbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ccdf3f89b93d36221701a42b99584f5fcdac2b7f/msteams-platform%2Fsbs-gs-commandbot.yml) | 88 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5227e27-ee64-4603-9d6c-91be75096e27) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ccdf3f89b93d36221701a42b99584f5fcdac2b7f/msteams-platform%2Fsbs-gs-notificationbot.yml) | 85 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5bf78d8-2984-426a-b1fe-f4b9a9982fa2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ccdf3f89b93d36221701a42b99584f5fcdac2b7f/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5135caa3-2e8d-44ce-9b0f-235994bb344c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ccdf3f89b93d36221701a42b99584f5fcdac2b7f/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 85 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b872ba4f-1adb-4edf-975a-f88e705c2e72) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ccdf3f89b93d36221701a42b99584f5fcdac2b7f/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/070a0314-9f0f-4bf7-b153-192b6db97670) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
