### PR TITLE
[Doc Improvement][Remove currently in public developer preview][2844817]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/839f9703870e48a7ae6684c44acdd8006702030d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd5b0b9b-f168-45a0-b648-27d1d2393a49) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9253ce6599bbfc1c28368be45c659bbc993289a2/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 93 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f779ee9-7653-4134-aa38-da3f74b9fe64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9253ce6599bbfc1c28368be45c659bbc993289a2/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/caa0e8d7-60c5-40c3-9817-96e5d161f171) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9253ce6599bbfc1c28368be45c659bbc993289a2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81b74d0d-8b81-4a82-a798-8190c3bd2fa0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-control.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9253ce6599bbfc1c28368be45c659bbc993289a2/msteams-platform%2Fsamples%2Fcollaboration-control.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57ad4ea0-7aee-490f-9413-047dd9df6056) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8ae1c5ac66c859ebd1250a67234f1ab85cebdde/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 93 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/314357a9-7d9d-4fa8-8fb4-b9f8fb35f6de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8ae1c5ac66c859ebd1250a67234f1ab85cebdde/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b94e08a-75a6-4992-bdbf-5057ece98ebb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8ae1c5ac66c859ebd1250a67234f1ab85cebdde/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56ac89f4-38fc-4269-b8b1-2aea79f3a6d2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8ae1c5ac66c859ebd1250a67234f1ab85cebdde/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5107543f-bcc2-45ec-996e-0cffdd6581c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-control.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8ae1c5ac66c859ebd1250a67234f1ab85cebdde/msteams-platform%2Fsamples%2Fcollaboration-control.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8665093e-7fd6-4bb1-a256-c298e332ddcd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8ae1c5ac66c859ebd1250a67234f1ab85cebdde/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3023305e-1d8e-4722-a09d-7f2612224df1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c8ae1c5ac66c859ebd1250a67234f1ab85cebdde/msteams-platform%2Fwhats-new.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09700a5c-1f17-4fd7-89a0-d2f88df87a0e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9728048529a1cf2654ec84fe069b97447ffdf674/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 93 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1aa87fc7-acc7-438d-bbf2-0eb693fca508) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9728048529a1cf2654ec84fe069b97447ffdf674/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cc7c4b9-c982-4adf-9cf3-8ad907c20309) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9728048529a1cf2654ec84fe069b97447ffdf674/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87d53bc7-9b7c-480f-8e7d-695b8222c9cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9728048529a1cf2654ec84fe069b97447ffdf674/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9ef7831-6810-4fc0-bba6-cd719836e845) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-control.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9728048529a1cf2654ec84fe069b97447ffdf674/msteams-platform%2Fsamples%2Fcollaboration-control.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f74fa17-4e91-405d-83a0-3b1e905ce4cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9728048529a1cf2654ec84fe069b97447ffdf674/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7052dc88-fe56-4477-ba9d-cae50a788488) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9728048529a1cf2654ec84fe069b97447ffdf674/msteams-platform%2Fwhats-new.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20e7307c-225a-4089-b594-305224800e33) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by surbhigupta12 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fc15047c18b6a301e4c4990b846fdb40cfe4e72/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 93 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94712520-bb10-4001-8d84-a48a412441ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fc15047c18b6a301e4c4990b846fdb40cfe4e72/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/061d6c4a-52b1-4af7-b0e0-f9c7357f7b9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fc15047c18b6a301e4c4990b846fdb40cfe4e72/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55a2cd09-de09-49f6-bf68-93c9e6ba593b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fc15047c18b6a301e4c4990b846fdb40cfe4e72/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00a354c4-3c07-477c-8032-afb37bdee0cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-control.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fc15047c18b6a301e4c4990b846fdb40cfe4e72/msteams-platform%2Fsamples%2Fcollaboration-control.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1412fa30-45b7-4e05-b64b-9089d8cbd437) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fc15047c18b6a301e4c4990b846fdb40cfe4e72/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08b9ab40-8703-402d-9ae5-06263745f340) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4fc15047c18b6a301e4c4990b846fdb40cfe4e72/msteams-platform%2Fwhats-new.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b46cb383-1883-4f53-a4e3-9726ab7aadac) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/381f69dd25939b203746ad97b243053086c76809/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 93 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6a59a10-82bc-4ae3-ac37-ed9e41b35bb1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/381f69dd25939b203746ad97b243053086c76809/msteams-platform%2Fapps-in-teams-meetings%2Fteams-apps-in-meetings.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49dd0e39-ed5d-41b0-a334-3182a0e41c85) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/381f69dd25939b203746ad97b243053086c76809/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/daad8c6a-5c1c-4efd-bbed-6359a37bd67e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/381f69dd25939b203746ad97b243053086c76809/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f400a9a-6791-4ccb-a5f7-dc5bb8648539) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-control.md](https://github.com/MicrosoftDocs/msteams-docs/blob/381f69dd25939b203746ad97b243053086c76809/msteams-platform%2Fsamples%2Fcollaboration-control.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/272edd52-9843-4a4e-bbdd-352313e64f0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/381f69dd25939b203746ad97b243053086c76809/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2dd91b1c-76fd-428d-bef1-3e716bf2f4ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/381f69dd25939b203746ad97b243053086c76809/msteams-platform%2Fwhats-new.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89789776-dfd5-47d0-a732-c6ab9b1844b6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-ypalikila — APPROVED** [review]
Approved.

**Pull request merged**
