### PR TITLE
[Doc Feature][Allow apps to be available on mobile without WebsiteURL]

### PR DESCRIPTION
**Pull request by v-rmvv**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b36f70b419b8c221013a242a5ec962c554f376e4/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2dd3bec8-2314-4d97-9d89-872a25025247) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b36f70b419b8c221013a242a5ec962c554f376e4/msteams-platform%2Ftabs%2Fdesign%2Ftabs-mobile.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4368a748-c85c-4d54-b565-8eda99562cd1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d5475c71a56261eb91dd6bcdfd76f750a83a6b1/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69da0e3c-694d-45c2-a351-f311e4da1c55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d5475c71a56261eb91dd6bcdfd76f750a83a6b1/msteams-platform%2Ftabs%2Fdesign%2Ftabs-mobile.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c180d4d6-a052-49b4-af7f-17a0b49bf199) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ee341780f99848097752a4fd1b6ac73ff8829d/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c7c404f-00c3-404b-b19c-098414e864be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/49ee341780f99848097752a4fd1b6ac73ff8829d/msteams-platform%2Ftabs%2Fdesign%2Ftabs-mobile.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/568d9933-0f39-4fc3-a6c8-c3f39956b52f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e770686fff27e7910ebc5d53fdf147f8f5baafd/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4d3b610-dd79-46d8-9172-9f94b3e728eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7e770686fff27e7910ebc5d53fdf147f8f5baafd/msteams-platform%2Ftabs%2Fdesign%2Ftabs-mobile.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce468dde-6118-4720-9d3b-c31e6dd77652) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9234978edb5b825e09908b8c3b2ad615cc0f6adf/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee7462dc-a1fd-429b-a1e0-1e4b4feb808b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9234978edb5b825e09908b8c3b2ad615cc0f6adf/msteams-platform%2Ftabs%2Fdesign%2Ftabs-mobile.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f51b0f9-2a21-4a7f-950d-f15560375bc1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by AnkitaMaths — CHANGES_REQUESTED** [review]
If `websiteUrl` is available in the app manifest file, the tab opens in a browser outside Teams. </br> If `websiteUrl` isn’t available in the app manifest file, the tab isn’t accessible on Teams mobile. However, `websiteUrl` is still accessible on Desktop and web. |

Can you change last line to:
However, tab is still accessible on Desktop and web. |

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12da5422de5409c3b015d4c797fb63c7ff03e8d7/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a375a0e-7d2a-4028-9284-953a2d0799f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12da5422de5409c3b015d4c797fb63c7ff03e8d7/msteams-platform%2Ftabs%2Fdesign%2Ftabs-mobile.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e65089ef-6afa-439b-862f-71e572c036dc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/03e9a3cbf24672d6b984baab14f652e2656e2b2d/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55bef5b1-8797-427e-9391-e3eb37c7cfb9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/03e9a3cbf24672d6b984baab14f652e2656e2b2d/msteams-platform%2Ftabs%2Fdesign%2Ftabs-mobile.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58eaf316-6a71-472a-ac8f-678716def214) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-rmvv** [comment]
> If `websiteUrl` is available in the app manifest file, the tab opens in a browser outside Teams. If `websiteUrl` isn’t available in the app manifest file, the tab isn’t accessible on Teams mobile. However, `websiteUrl` is still accessible on Desktop and web. |
> 
> Can you change last line to: However, tab is still accessible on Desktop and web. |

Updated as requested.

**Review by AnkitaMaths — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/glossary.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d43ff37f4a82070b10dd15864601101d6cd144c7/msteams-platform%2Fget-started%2Fglossary.md) | 95 | 61 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9edc70e9-4a2b-4a64-a57b-e430cbdb2c9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/design/tabs-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d43ff37f4a82070b10dd15864601101d6cd144c7/msteams-platform%2Ftabs%2Fdesign%2Ftabs-mobile.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44f8ce47-66df-44e5-906f-6aa73b07e60d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
