### PR TITLE
Update overview-analytics.md

### PR DESCRIPTION
**Pull request by v-shalinirobinson**
Included mention for LOB developers as well to make this complete.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/77b037a03bcc83bda71667ddbdad698ca504ac7a/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 89 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd288e2c-ac94-44f2-95f8-54224e0c1d75) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c33d903cc1a6771acb60f6d3f28be0133f745feb/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67582483-cf0b-4bfc-b22d-47dd280d0f0e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/419ec873e026b36f4875a1d6d4f4e28a3554cd1b/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b936ee4-7bf3-4849-b421-eeb56d6abb21) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by vishrutshuklaMSFT** [comment]
Looks good, thanks. Let's publish.

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
