### PR TITLE
[Doc Improvement][Grow your app localization content update]

### PR DESCRIPTION
**Pull request by v-ypalikila**
Added Localize your app to support demand in global markets

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a32ec7598dd918fd1873618e01328b56f16c5a8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e09cd30-8eef-471a-a170-8c0f9b766c2d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e99319f531bb1fd0c1cc3b089733a0869a97fb48/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83de3bb4-0eff-41b1-85a0-b66b7bd25c5a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by vishrutshuklaMSFT** [comment]
Looks good, thanks

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/067eba2be169acf5e182c04379797d4d34b1b535/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 89 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f429cb89-b4d8-4295-8194-86f7c8552df4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by vishrutshuklaMSFT — DISMISSED** [review]
Approving

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3cfc9b0a791880b37c8999cd94e0bcdf5dba70ab/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 89 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e656c9bf-75e0-4b05-ab1d-5a5cb9960394) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/scale-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3cfc9b0a791880b37c8999cd94e0bcdf5dba70ab/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fscale-app.md) | 87 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0693384a-1da7-4c8a-ac2c-12eb4b09b5aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3cfc9b0a791880b37c8999cd94e0bcdf5dba70ab/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0eeaa62-7afe-4992-914d-0ec1d28645a7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/app-growth-lifecycle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80d5f8ae47f80b60c5cd8b123f9e8a3d424c375d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fapp-growth-lifecycle.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f72d3e9-6a54-4909-87a4-fca22842bfce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80d5f8ae47f80b60c5cd8b123f9e8a3d424c375d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 89 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88caf7f0-bfb3-4e77-ba77-cc024c2c7fe0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/overview-app-growth.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80d5f8ae47f80b60c5cd8b123f9e8a3d424c375d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Foverview-app-growth.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b111aeb-2a8e-4ef1-80b5-dd48f2e827ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/scale-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80d5f8ae47f80b60c5cd8b123f9e8a3d424c375d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fscale-app.md) | 87 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9fc4874b-3f61-4d15-b973-ef0e45959c41) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80d5f8ae47f80b60c5cd8b123f9e8a3d424c375d/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e841d6b-0f41-4fa3-87c8-9cce1e4166fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/promote-app-adoption.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80d5f8ae47f80b60c5cd8b123f9e8a3d424c375d/msteams-platform%2Fpromote-app-adoption.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd5f31a7-0435-4f65-96b2-e2d048703b6c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/app-growth-lifecycle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/533566aa12650ae935d9cfe2d6d2f2f0e10e0b25/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fapp-growth-lifecycle.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4a63a91-a5b0-4798-b4bb-28823f93a62d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/533566aa12650ae935d9cfe2d6d2f2f0e10e0b25/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6139ba3-6f73-4310-9ab4-494ea27550c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/overview-app-growth.md](https://github.com/MicrosoftDocs/msteams-docs/blob/533566aa12650ae935d9cfe2d6d2f2f0e10e0b25/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Foverview-app-growth.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1c867b2-2705-46c9-b6b8-962443d8de58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/scale-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/533566aa12650ae935d9cfe2d6d2f2f0e10e0b25/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fscale-app.md) | 90 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/051b11d1-ec41-446f-abe8-4275a7523ff6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/533566aa12650ae935d9cfe2d6d2f2f0e10e0b25/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f16dda2-fdcb-4414-8ef9-51ea6a261060) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/promote-app-adoption.md](https://github.com/MicrosoftDocs/msteams-docs/blob/533566aa12650ae935d9cfe2d6d2f2f0e10e0b25/msteams-platform%2Fpromote-app-adoption.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfdc4ae9-80ee-4eb3-b0ae-a892f758039f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/app-growth-lifecycle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2b17c9e260aa54034c23c4b2ced06f964aeb1d8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fapp-growth-lifecycle.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e4da91f-11e3-4505-9254-fa94c8a5c9b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2b17c9e260aa54034c23c4b2ced06f964aeb1d8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/770807b7-f2b3-45f7-9bb0-799398437f5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/overview-app-growth.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2b17c9e260aa54034c23c4b2ced06f964aeb1d8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Foverview-app-growth.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a71a0193-5cdc-4eda-ad09-fb3708ecfa56) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/scale-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2b17c9e260aa54034c23c4b2ced06f964aeb1d8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fscale-app.md) | 90 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7177cb60-c3b8-42d4-a980-a4f2d8623d9b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2b17c9e260aa54034c23c4b2ced06f964aeb1d8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc3e231f-ceaf-4374-85d5-f88d7349645c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/promote-app-adoption.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e2b17c9e260aa54034c23c4b2ced06f964aeb1d8/msteams-platform%2Fpromote-app-adoption.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b69d94f-f719-4368-9440-3bb9858966a8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/app-growth-lifecycle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0796ec60db45388dcd4d78c85448d75175336879/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fapp-growth-lifecycle.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85f743da-7ed3-487e-af09-4bada8206cf9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0796ec60db45388dcd4d78c85448d75175336879/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c9b0ebb-8264-4ef4-8ceb-6675030cfb42) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/overview-app-growth.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0796ec60db45388dcd4d78c85448d75175336879/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Foverview-app-growth.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65a534cf-21f1-4c86-b43b-ebb667c0664d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/scale-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0796ec60db45388dcd4d78c85448d75175336879/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fscale-app.md) | 90 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10b15ad8-6907-4da5-b560-b80d79b15c43) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0796ec60db45388dcd4d78c85448d75175336879/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c77d0257-7c0f-452a-b4e6-64bbffd3525e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/promote-app-adoption.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0796ec60db45388dcd4d78c85448d75175336879/msteams-platform%2Fpromote-app-adoption.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba84d351-85a3-4054-883f-11f0ed2ebdc2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by vishrutshuklaMSFT — APPROVED** [review]
Looks good.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/app-growth-lifecycle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/786b6bdb5f5cae84fc1d19eac30fe053d9363e5f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fapp-growth-lifecycle.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ce1b5ad-9127-48d6-9835-b135b344e18a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/786b6bdb5f5cae84fc1d19eac30fe053d9363e5f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0eaf6a76-472a-4f1b-951d-ecccb85c88b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/overview-app-growth.md](https://github.com/MicrosoftDocs/msteams-docs/blob/786b6bdb5f5cae84fc1d19eac30fe053d9363e5f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Foverview-app-growth.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4717fbb1-ee07-4bbe-bd59-c242f66dbd4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/scale-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/786b6bdb5f5cae84fc1d19eac30fe053d9363e5f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fscale-app.md) | 90 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31e35f67-9718-4f23-8d23-c602bfa445a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/786b6bdb5f5cae84fc1d19eac30fe053d9363e5f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1f51e98-86e6-4ad9-bb63-d48ec2977617) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/promote-app-adoption.md](https://github.com/MicrosoftDocs/msteams-docs/blob/786b6bdb5f5cae84fc1d19eac30fe053d9363e5f/msteams-platform%2Fpromote-app-adoption.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41a70eec-aedd-4201-b1ee-aaa9d7b40145) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/app-growth-lifecycle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eab15f1bd131ff167cf9396a112b0d4d771a5911/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fapp-growth-lifecycle.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e837561a-2c5b-4717-a84f-4ebc903e83c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/gain-traction.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eab15f1bd131ff167cf9396a112b0d4d771a5911/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fgain-traction.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90cd1713-6aed-41b9-8d83-6bb16756d4d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/overview-app-growth.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eab15f1bd131ff167cf9396a112b0d4d771a5911/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Foverview-app-growth.md) | 90 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67b326c8-fc39-4ff9-a0ae-34380bd78b8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/scale-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eab15f1bd131ff167cf9396a112b0d4d771a5911/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fscale-app.md) | 90 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98b331b4-2cb5-4ce9-8b1c-741c4d5cfd39) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/succeed.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eab15f1bd131ff167cf9396a112b0d4d771a5911/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fsucceed.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/716b07d0-413e-46b9-afe9-72adf47632ff) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/promote-app-adoption.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eab15f1bd131ff167cf9396a112b0d4d771a5911/msteams-platform%2Fpromote-app-adoption.md) | 93 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e13548b-a7da-49f5-a84a-1f3f307f0e51) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
