### PR TITLE
Doc improvement teams light theme2

### PR DESCRIPTION
**Pull request by v-vanisreeth**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-bot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8300ea43a505a66c39a72a3de463fdf56f617a56/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-bot-v4.yml) | 88 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/150efaba-c83c-4664-adf4-fbac0ce86071) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fnotification-bot-in-teams.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cafe7186-4bcf-40b0-839e-ecc343c198c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99490a68-b4ea-4479-812a-421bc9707cc5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/prepare-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Fincludes%2Fget-started%2Fprepare-teams-toolkit.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bec5797-5fde-4601-9792-9f34ffeecb20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Fsbs-gs-msgext.yml) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ebb15fa6-aa61-43c2-b6d1-9aa6071af479) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/459b086c-84d8-463b-896f-c37f14fcca23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-tab-aad.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be1ce067-885c-4579-aa7f-0121023a1026) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1d9c607-c5fd-4088-a198-a39ad5a9e80a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/publish-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fpublish-v4.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01d5d350-3e96-406d-8f41-890ad55d4d95) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-bot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-bot-v4.yml) | 88 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91616323-727a-435c-a5b6-e346437ef729) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-commandbot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-commandbot-v4.yml) | 88 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ef608eb-db02-4451-95f3-ffe2a10f2edb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-csharp-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-csharp-v4.yml) | 86 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11f4c2c5-7e7f-425b-a624-8d5539b41af9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-javascript-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-javascript-v4.yml) | 88 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab994dc8-9615-48b8-b747-23d8a84718c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-msgext-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-msgext-v4.yml) | 85 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d0d3f93-dc6e-4cc7-9078-b09261a347d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-notificationbot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-notificationbot-v4.yml) | 87 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a27a6ed1-579f-491c-86eb-488d86ac28c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fadd-outgoing-webhook.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bab11dcc-d7b5-477d-b4bf-a27476d2ea7b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc746bd12fa349725d4cf7255e81d24ea38c46c/msteams-platform%2Fwhats-new.md) | 94 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6f7a10b-ac51-4542-9634-58c20b6de8b2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fnotification-bot-in-teams.md) | 95 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47aacc2d-6f86-4b2d-bca3-df215a1ebfa9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 96 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/417eaf7f-861b-4843-b3c1-6600819cf00a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/prepare-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Fincludes%2Fget-started%2Fprepare-teams-toolkit.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1de7cc3-f184-4fba-9600-5b1d74cb8d7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Fsbs-gs-msgext.yml) | 87 | 48 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfd41f6c-acd8-4db8-a9fa-6b2cd6aedf7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50d02462-601b-4f3d-8b46-f47bdd6efc45) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-tab-aad.md) | 90 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e44d1e9-7160-4215-adcf-984510790088) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31c098a4-6459-4a8c-8fb0-5dfb80091460) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/publish-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fpublish-v4.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e27ac490-eafc-4e4f-b58c-6e66fd8f8c2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-bot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-bot-v4.yml) | 88 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f076be5-f4cb-4aca-831e-c2382d309d58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-commandbot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-commandbot-v4.yml) | 88 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/504efebe-5209-4dc1-9ae2-00cc76dd7412) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-csharp-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-csharp-v4.yml) | 86 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab4241d4-a279-4e63-9258-280f571e1973) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-javascript-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-javascript-v4.yml) | 88 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6d4d3d1-01fc-41ad-a070-71f821b74053) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-msgext-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-msgext-v4.yml) | 85 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8cd9cd6c-96ae-48f3-9608-f2bcf5543614) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-notificationbot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-notificationbot-v4.yml) | 87 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4726edc6-66cf-4e04-9c01-14afbd28ca5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/add-outgoing-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Fwebhooks-and-connectors%2Fhow-to%2Fadd-outgoing-webhook.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddc88e00-6865-4ba1-854c-c9a8f965f50c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3721aa1dc87ea72a2c7e2e4803e7ed3d6ccf2bcd/msteams-platform%2Fwhats-new.md) | 94 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab2448cc-a0e5-4ce5-b475-0f7c84025dff) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-deabira** [comment]
Closing the PR as it is wrongly created a PR from the branch which was closed/merged.

**Pull request closed without merging**
