### PR TITLE
[DocUpdate][Added table]

### PR DESCRIPTION
**Pull request by v-vasudhab**
Please review

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ca58077d767378b065f04be4d5d67ac9adc90eb/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e039889-3cf5-4253-9e9f-555f3f013226) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/77a39b8e2726a358dd53ba716f2eae27268e9564/msteams-platform/bots/bot-basics.md) | 83 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65eb0cbd-dc06-442d-b6eb-57b2692b7773) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a1b105236a973d3c2bf91c19c54cbf03efb8fe2/msteams-platform/bots/bot-basics.md) | 83 | 50 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f33c6da0-342c-49b3-8c9d-0cb39d00d2f5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9eb69b78663feadf7cd11de81f775ce5880eb7ac/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9daf6e41-d192-4d39-9474-ae6f831c2e2f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95f1b8ee1f363f8e3d86c6b6b5a27cdd2f1a54ef/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccd4f33e-09f0-4830-925e-08b2e3e174fe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/80ec2eb809c16bfc816f636691e820169a9377e4/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40147492-d9f1-4f88-9156-3a7afd38a7b2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/46f48650b0720d7e119c8788a71fd7eff61a98dd/msteams-platform/bots/bot-basics.md) | 82 | 55 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96bbdad6-71e9-46fb-bf88-9e7c6a90fcb4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e7f03a021a2bae38b60e1445025a5adf62dad96d/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85f10e09-18bd-4ccf-8b63-bee3b12db290) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/717373d41c71a5d06bf7a37d650f0e5764242424/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc7e8c89-67ab-4cc6-a12e-4ec600429d82) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea5e474d890982972d41882f9a83c1c90b692eac/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/399f9ed5-3c40-4c45-9fa9-66f0e13ffb16) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-abirade** [comment]
Closed

**Pull request closed without merging**
