### PR TITLE
[Doc Improvement][Link updates]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a48d20fdc49d340a0d671690baf2d3efb7ffa6c/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5494e17e-51d8-4b27-b41f-377d0d8ce4a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0a48d20fdc49d340a0d671690baf2d3efb7ffa6c/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 75 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bce6043-9bec-45ab-861d-66fcb530b099) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a48d20fdc49d340a0d671690baf2d3efb7ffa6c/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 89 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f7e40c4-a1bf-4fcb-9fba-7555a6a72d6a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/119600f35c9746b4d2aec618b85ae7f74910ef46/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75740891-0800-41f9-8fd7-d65bd65da7a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/119600f35c9746b4d2aec618b85ae7f74910ef46/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 75 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/804037a4-cedb-4c5f-aaa0-94969728c75f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/119600f35c9746b4d2aec618b85ae7f74910ef46/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 89 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2aeb55fd-f5f2-4d5d-97d2-641c2d3c4beb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4d00f439fdaa8eab2d1f02f79cc8089dcd351c6/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0395a952-dbe8-4f3f-9e6d-1a9da3c1989a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d4d00f439fdaa8eab2d1f02f79cc8089dcd351c6/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 75 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8fa9310e-c1fd-4968-a933-7cf21e28972f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4d00f439fdaa8eab2d1f02f79cc8089dcd351c6/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 89 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c899dca-8d20-4a33-864b-567e4fffcc2b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7591d411284d75c8e8e6b51ae6222e850263ee5/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84094e56-ac60-469e-aa17-778ec52c1e65) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b7591d411284d75c8e8e6b51ae6222e850263ee5/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 75 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c3d8e9f-7fb7-47e0-a7f2-715d6a88a7ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7591d411284d75c8e8e6b51ae6222e850263ee5/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 89 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65d29d9a-457b-4ff0-860e-616f99170155) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by summzhan — APPROVED** [review]

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7591d411284d75c8e8e6b51ae6222e850263ee5/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/915334d8-8a90-4625-818d-f7d9ed98b34a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b7591d411284d75c8e8e6b51ae6222e850263ee5/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 75 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fb88e5d-aa94-4588-9240-2b38e35fba71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b7591d411284d75c8e8e6b51ae6222e850263ee5/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 89 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cf7a94e-af62-48db-8f6e-30838ebd63a1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60bcf4df0b9caeae467f53f23e185d3974638c41/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e73923a0-6618-4895-ba54-866b298b66ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/60bcf4df0b9caeae467f53f23e185d3974638c41/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 75 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7749e50f-e192-457e-8e54-9425430ad180) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60bcf4df0b9caeae467f53f23e185d3974638c41/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 89 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee5b95c6-c6a7-4d8c-93d6-6d8005a24338) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12f37219148f91e6978e6284661d3723d836ad9c/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47665696-480f-431b-9b4d-92cf23e61708) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/12f37219148f91e6978e6284661d3723d836ad9c/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 76 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98260e8c-cd8f-4212-bdd4-1f6b1995cf5a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/12f37219148f91e6978e6284661d3723d836ad9c/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 89 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/697ee248-062d-4efa-a582-019c846b15eb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/879c7165174574fb96f339501ed67a90538975e1/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc239f09-ae23-463c-96bc-d3909c0e3652) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/879c7165174574fb96f339501ed67a90538975e1/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 76 | 74 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e53bef58-f83b-43f0-aac0-d3d9dea59267) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/879c7165174574fb96f339501ed67a90538975e1/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 89 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d199239-c05b-4b06-9a04-86b27a59e5f2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f17fcb716ae4ab9fd3e0cda42123bf5b97eaf45/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5596e403-21ec-4c9b-98ed-384e25d93773) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9f17fcb716ae4ab9fd3e0cda42123bf5b97eaf45/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 78 | 59 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a78ffb5f-9272-4272-891c-ecb9c4ce6fca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f17fcb716ae4ab9fd3e0cda42123bf5b97eaf45/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 89 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa316448-f80f-402a-a5e0-088f391b4dd9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3ba87c54d4d71ec8dd6e75de1cc991cd9a881b18/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3155e9b-29d4-42bf-bb1e-6e979df2e33e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3ba87c54d4d71ec8dd6e75de1cc991cd9a881b18/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 79 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b51afec8-daca-4cfd-b996-ea053e66678b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3ba87c54d4d71ec8dd6e75de1cc991cd9a881b18/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 89 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19432081-5737-440e-8576-b7abca7681bb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f73c2ee521ad074dd764b78e878aac9437b0ff5b/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f0b80e5-6c7b-41c0-8e45-c6d5bbb9b037) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f73c2ee521ad074dd764b78e878aac9437b0ff5b/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 80 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2a034a8-3174-4a67-860e-af59bc92d9ca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f73c2ee521ad074dd764b78e878aac9437b0ff5b/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 89 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a317c93-6323-46bb-8b73-70df7227d88e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/choose-what-suits-you.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54bba565f5f3ff6f32ab0140f7a536a4f3e0ae44/msteams-platform%2Fget-started%2Fchoose-what-suits-you.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0f07d58-577f-4aae-9037-26434af07379) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/54bba565f5f3ff6f32ab0140f7a536a4f3e0ae44/msteams-platform%2Fsbs-create-dashboard-widget-graph-api-call-in-Teams-toolkit.yml) | 80 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1e2d56e-b0ec-40af-8178-44af99c58f10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/54bba565f5f3ff6f32ab0140f7a536a4f3e0ae44/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 89 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3837e7d-3661-4615-8f22-16d1b10cde1b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
