### PR TITLE
Create personal-apps.md

### PR DESCRIPTION
**Pull request by jfjstone**

### CODE REVIEW

**Comment by charlesprakash** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[personal-apps.md](https://github.com/jfjstone/msteams-docs/blob/JJ-Personal-apps/personal-apps.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C29%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201804291656453550-149%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=FbD67NSJlU4NV6afNG%2Bz3wpGbEhkaO%2B5kZ1SmXJiq3w%3D&st=2018-04-29T16%3A53%3A13Z&se=2018-05-30T16%3A58%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by charlesprakash** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[personal-apps.md](https://github.com/jfjstone/msteams-docs/blob/JJ-Personal-apps/personal-apps.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C30%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201804302327286088-149%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=O6YjfzEek7UK04xSXEj4VZy2R15dn%2BfmmzEtgXdAtX4%3D&st=2018-04-30T23%3A23%3A35Z&se=2018-05-31T23%3A28%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Personal-apps-App-flyout.png](https://github.com/jfjstone/msteams-docs/blob/JJ-Personal-apps/msteams-platform/assets/images/Personal-apps-App-flyout.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Personal-apps-Bot.png](https://github.com/jfjstone/msteams-docs/blob/JJ-Personal-apps/msteams-platform/assets/images/Personal-apps-Bot.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Personal-apps-MY-tab.png](https://github.com/jfjstone/msteams-docs/blob/JJ-Personal-apps/msteams-platform/assets/images/Personal-apps-MY-tab.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Personal-apps-Recent-tab.png](https://github.com/jfjstone/msteams-docs/blob/JJ-Personal-apps/msteams-platform/assets/images/Personal-apps-Recent-tab.png) | :white_check_mark:Succeeded | |
[personal-apps.md](https://github.com/jfjstone/msteams-docs/blob/JJ-Personal-apps/personal-apps.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201807031955362524-149%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SH7JazAUsHu07ZEepjSbg%2FefojQD6ny1GaTpLDmmCHw%3D&st=2018-07-03T19%3A51%3A40Z&se=2018-08-03T19%3A56%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/Personal-apps-App-flyout.png](https://github.com/jfjstone/msteams-docs/blob/JJ-Personal-apps/msteams-platform/assets/images/Personal-apps-App-flyout.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Personal-apps-Bot.png](https://github.com/jfjstone/msteams-docs/blob/JJ-Personal-apps/msteams-platform/assets/images/Personal-apps-Bot.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Personal-apps-MY-tab.png](https://github.com/jfjstone/msteams-docs/blob/JJ-Personal-apps/msteams-platform/assets/images/Personal-apps-MY-tab.png) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/Personal-apps-Recent-tab.png](https://github.com/jfjstone/msteams-docs/blob/JJ-Personal-apps/msteams-platform/assets/images/Personal-apps-Recent-tab.png) | :white_check_mark:Succeeded | |
[personal-apps.md](https://github.com/jfjstone/msteams-docs/blob/JJ-Personal-apps/personal-apps.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201807032140366879-149%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8hgFkw%2Bhc1l7lVwapH4E4Q7xiYmuwl8TjEQKamxHiDY%3D&st=2018-07-03T21%3A37%3A09Z&se=2018-08-03T21%3A42%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
