### PR TITLE
[Docbug][videoformat][3872]

### PR DESCRIPTION
**Pull request by v-rodriguezd**
Added details for video format and added in best practices for video. Please review.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d754314e03ddb6f0f73b1c83eab878100675d4b/msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md) | 98 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/277e9db3-ef61-4402-b0ad-83ef282ea352) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-abirade** [comment]
Hi @ramendhe,

Request you tom please approve the PR.

**Review by ramendhe — APPROVED** [review]

**Review by v-abirade — APPROVED** [review]
Approved.

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
