### PR TITLE
[Doc Improvement][Casing and sign in fixes][3008097]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/626e232d2518ef679eee84deb6c5aec525cf8495/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14802bb4-8092-491a-8d95-bc37c0d73f71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/626e232d2518ef679eee84deb6c5aec525cf8495/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/febefdc3-8136-4ecb-859d-1bdfab238bc7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/626e232d2518ef679eee84deb6c5aec525cf8495/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97558b27-4dbe-4dbf-857f-f70269a1e276) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-in-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/626e232d2518ef679eee84deb6c5aec525cf8495/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-in-meeting.md) | 93 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7042044d-18c2-4aa9-b0f5-154ac0ac1fdb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b3a169298d7cb6848d5e778430aea0713dd5e9ad/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec4e3f7a-bfd0-4ff0-ada1-162ac85d4801) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b3a169298d7cb6848d5e778430aea0713dd5e9ad/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64ca4e2d-8492-4dcd-838b-1830ff93a13f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b3a169298d7cb6848d5e778430aea0713dd5e9ad/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e13f83ec-ecf6-4cc9-94a9-27160d92011e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b3a169298d7cb6848d5e778430aea0713dd5e9ad/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-capabilities.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48402387-acec-4299-8a2c-ca640fdacc31) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-how-to/how-to-custom-azure-fluid-relay.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b3a169298d7cb6848d5e778430aea0713dd5e9ad/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-how-to%2Fhow-to-custom-azure-fluid-relay.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc312c28-7142-4bd5-a2b5-bb95682c9b5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b3a169298d7cb6848d5e778430aea0713dd5e9ad/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/862d8cb6-2f0f-4ced-88ca-ee0c3cff66d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-quick-start.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b3a169298d7cb6848d5e778430aea0713dd5e9ad/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-quick-start.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3bc3c083-8027-4ddd-ae90-3956cd92aa0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b3a169298d7cb6848d5e778430aea0713dd5e9ad/msteams-platform%2Fapps-in-teams-meetings%2Fteams-together-mode.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e57b083e-223b-4024-bf6c-d65e500dff1a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-in-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b3a169298d7cb6848d5e778430aea0713dd5e9ad/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-in-meeting.md) | 93 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8470186-e01c-45ea-b33b-3f6c0483033d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b3a169298d7cb6848d5e778430aea0713dd5e9ad/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 97 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58067f67-eb90-487e-8f69-6f30f2a66602) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b3a169298d7cb6848d5e778430aea0713dd5e9ad/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 99 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db01e1fb-bd4e-447b-9b0e-0563947cf1db) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9eaedc01f9420b36a6247e5f045de5e9726d3e8e/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-capabilities.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/064ee3e2-44ab-4308-ace2-c0ce262463e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9eaedc01f9420b36a6247e5f045de5e9726d3e8e/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1dc1042b-f2f6-4103-bbdf-ec0011ba69e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9eaedc01f9420b36a6247e5f045de5e9726d3e8e/msteams-platform%2Fapps-in-teams-meetings%2Fteams-together-mode.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42653ebe-b655-4bbe-a5b6-7727af639093) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47928b785e61dc6fc95cb1473aca86dab96e4a1d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-capabilities.md) | 93 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f225bf90-bebe-466a-b086-9d351a399d09) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-live-share-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47928b785e61dc6fc95cb1473aca86dab96e4a1d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-live-share-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6596536f-2238-48fa-80fc-a1128972a7c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/teams-together-mode.md](https://github.com/MicrosoftDocs/msteams-docs/blob/47928b785e61dc6fc95cb1473aca86dab96e4a1d/msteams-platform%2Fapps-in-teams-meetings%2Fteams-together-mode.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c395c217-95f2-4c0c-94ba-c856282d532a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
