### PR TITLE
[Doc Improvement][Adding space after see Virtual Assistant and skills architecture]

### PR DESCRIPTION
**Pull request by v-spharish**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/62cd45b1959a01589cfd8d549b0dd0111b6b58ca/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99a18647-bf06-47c0-a6c6-0b60dc8b1303) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-with-collaboration-controls.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e9d1204673c541c8f33de8d7ff9fc9a2741edab3/msteams-platform%2Fsamples%2Fapp-with-collaboration-controls.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/624d0936-025e-4b72-bd9d-24eb4ba26c0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e9d1204673c541c8f33de8d7ff9fc9a2741edab3/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87e57634-efe9-4ee9-8999-0d55fdc6de40) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0e0c472c90323545163e09fb4514aa604d9bcc7f/msteams-platform%2Fsamples%2Fapp-templates.md) | 91 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a54f6926-1b5e-468f-97c0-9bc149f9c1df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-with-collaboration-controls.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0e0c472c90323545163e09fb4514aa604d9bcc7f/msteams-platform%2Fsamples%2Fapp-with-collaboration-controls.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c2af987-e4d2-4ee8-b5f2-9885a592bde1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0e0c472c90323545163e09fb4514aa604d9bcc7f/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ebe59bd-aad1-4a4b-8b0f-60b502d1c062) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee08ec7b399f878faafad1c6ab5ddf3dc68aa9fe/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79066fd7-9bf0-4c95-a68b-2a6e0b5b5c7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee08ec7b399f878faafad1c6ab5ddf3dc68aa9fe/msteams-platform%2Fsamples%2Fapp-templates.md) | 91 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48ca1296-4004-46cf-947a-e378527e3b55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-with-collaboration-controls.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee08ec7b399f878faafad1c6ab5ddf3dc68aa9fe/msteams-platform%2Fsamples%2Fapp-with-collaboration-controls.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f00e723-3e99-44bf-bbc4-fe21c8fab2bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee08ec7b399f878faafad1c6ab5ddf3dc68aa9fe/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22363d3c-e0a6-401c-9f49-4001206c1ac3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/m365-plugins/m365-plugins-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad71e3d01a3d516c2fb469585be3f5ba8adb1913/msteams-platform%2Fresources%2Fm365-plugins%2Fm365-plugins-overview.md) | 94 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e087bd6d-d4e8-46c8-bcab-51c475bf5e14) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad71e3d01a3d516c2fb469585be3f5ba8adb1913/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 94 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc2da898-7054-44c6-86ad-9db71083438e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad71e3d01a3d516c2fb469585be3f5ba8adb1913/msteams-platform%2Fsamples%2Fapp-templates.md) | 91 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a510340-0413-4bfd-bf28-a7f40b8a2933) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-with-collaboration-controls.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad71e3d01a3d516c2fb469585be3f5ba8adb1913/msteams-platform%2Fsamples%2Fapp-with-collaboration-controls.md) | 92 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/275a59f2-9802-4263-8c9f-5b40075c004c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad71e3d01a3d516c2fb469585be3f5ba8adb1913/msteams-platform%2Fsamples%2Fvirtual-assistant.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1e4a869-8dbc-48d5-9446-fb172ad78470) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tabs-in-sharepoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad71e3d01a3d516c2fb469585be3f5ba8adb1913/msteams-platform%2Ftabs%2Fhow-to%2Ftabs-in-sharepoint.md) | 92 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee912f71-d9b9-4bfb-a1e8-82760f7e7739) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
