### PR TITLE
[BULK] DocuTune - Add ms.custom tag "has-azure-ad-ps-ref" to track Azure AD PowerShell references

### PR DESCRIPTION
**Pull request by alexbuckgit**
[BULK] DocuTune - Add ms.custom tag "has-azure-ad-ps-ref" to track Azure AD PowerShell references

CorrelationId: 1960a274-3b36-46bb-86ce-f92e1539efdf

#docutune

### CODE REVIEW

**Comment by alexbuckgit** [comment]
#docutune-ready

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1aed7a89e0a9bcc3ea38d3eb1f0d17f627746c13/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-data.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a0b32e7-acb7-48e3-aec7-c55286f295b7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by msewaweru** [comment]
@surbhigupta12 - requesting for your assistance in merging this PR. This is a DocuTune generated update to add a custom metadata tag to files that have references to PowerShell modules that are planned for deprecation (Azure AD PowerShell and MSOnline). This will help us track files that have these references and the work going on in that area. Let me know if you need further clarification.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/test-data.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea7323a23a044bb73be284e141b927e5ea0f2851/msteams-platform%2Fconcepts%2Fbuild-and-test%2Ftest-data.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8a32fab-c097-4a51-8e64-bc484764ded8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
