### PR TITLE
[Doc Improvement][Branding issues][3939691]

### PR DESCRIPTION
**Pull request by v-kushals**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0a4aaabf88f85370e88e9937da9269038d8b7f3e/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d726d4ad-b5de-417e-8d10-bf398ff02c95) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a4aaabf88f85370e88e9937da9269038d8b7f3e/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b0e1588-02b9-4eae-849e-d040f7c3246d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8c591a477425472c35be17497fa0db0d9649169f/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c57ee23-e10b-46bc-af20-2ea21000e581) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c591a477425472c35be17497fa0db0d9649169f/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34af5311-2ee9-433d-87fc-556f5bc7bfce) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ebfc9b86a77b621048f9162a3ca58e547ded28f2/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc4c9c2a-9b7d-4866-8af7-247e04a68e71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebfc9b86a77b621048f9162a3ca58e547ded28f2/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cbc6ff0d-03d4-4a07-840f-650068b607dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ebfc9b86a77b621048f9162a3ca58e547ded28f2/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b14c733-3917-4ee0-b491-d10e3c0d7163) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6eb7ee05a6733d1bd507f2594a380b3f26949b73/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d416715e-f1ed-445c-9d52-717e290fada2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6eb7ee05a6733d1bd507f2594a380b3f26949b73/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9808883-c0b6-4b67-88ea-2276cb23a2c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6eb7ee05a6733d1bd507f2594a380b3f26949b73/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0066d732-2200-417d-a51e-1e1f1b610fc8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/967fdc8ddc24241f39e16335f0c591d52fec234c/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7be4628c-aa33-4e92-b467-5cf12522ae0b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/967fdc8ddc24241f39e16335f0c591d52fec234c/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5d1f225-0f0c-4ed5-a403-a45a5a4a2ea5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/967fdc8ddc24241f39e16335f0c591d52fec234c/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0a0d7b9-33bb-433b-92af-d64e9370f3d2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f34c07199f136f9c33e7bf83adeb860a34505511/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29bb9044-9bb0-4dec-9ae1-9fd19407047e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f34c07199f136f9c33e7bf83adeb860a34505511/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfaef11c-fd56-46e2-a80b-4b37ad977d33) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f34c07199f136f9c33e7bf83adeb860a34505511/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a1dcd94-1668-4ed0-bf17-da1398cff729) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f34c07199f136f9c33e7bf83adeb860a34505511/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88ce2125-71d0-43f6-b908-ff3e66275779) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab351a2c3dc3ec1bd5ffe17d0ea0a34a23410a2a/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59131224-e6e1-4827-9daa-e8296fa13bbc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab351a2c3dc3ec1bd5ffe17d0ea0a34a23410a2a/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bbcbb6e-f7fc-4dc6-af73-f5913b0d5b22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab351a2c3dc3ec1bd5ffe17d0ea0a34a23410a2a/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1838f4e6-3d80-4c84-9c2c-5862f92e51e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ab351a2c3dc3ec1bd5ffe17d0ea0a34a23410a2a/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 93 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3058574d-a900-4b0e-8549-0f2ffef38e42) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3a54a16f09e4890c9a463f3fa6e6595f5b22ede7/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a22750b1-cabc-4e3b-a7aa-df01d568d7cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3a54a16f09e4890c9a463f3fa6e6595f5b22ede7/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8b06774-051e-41c3-bab6-099d50c50412) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3a54a16f09e4890c9a463f3fa6e6595f5b22ede7/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c00902ff-8384-4b13-a1f5-61f9dc294dc7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — DISMISSED** [review]

**Review by Wajeed-msft — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/cb6cf60fd93ac1395fdfb39b462ad25312c80b95/msteams-platform%2FTOC.yml) | 97 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90ca7caa-403e-4790-933b-6d4e55c62523) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb6cf60fd93ac1395fdfb39b462ad25312c80b95/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3b11ac4-69f3-4209-b73c-a0ea1394b3d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb6cf60fd93ac1395fdfb39b462ad25312c80b95/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7133a35c-f827-402d-8512-a31e34ce9b41) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
