### PR TITLE
fixed typo

### LINKED ISSUE #277: Spelling mistake in the document
Hi Teams - the document looks great could you pls correct the spelling for "Text Area" at the end of the document under the section **Controls**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c181f8cb-871f-09f5-1210-352afeaf0271
* Version Independent ID: 2a62e83d-0dd5-0cff-e45f-73d451f10b63
* Content: [Get started with App Studio for Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-app-studio)
* Content Source: [msteams-platform/get-started/get-started-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

### PR DESCRIPTION
**Pull request by bcwood**
Fixed typo under Controls section: "Test Areas" -> "Text Areas"

Fixes #277

### CODE REVIEW

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/get-started-app-studio.md](https://github.com/bcwood/msteams-docs/blob/patch-1/msteams-platform/get-started/get-started-app-studio.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fget-started%2Fget-started-app-studio.md)

<a name="msteams-platform%2Fget-started%2Fget-started-app-studio.md"></a>
### [msteams-platform/get-started/get-started-app-studio.md](https://github.com/bcwood/msteams-docs/blob/patch-1/msteams-platform/get-started/get-started-app-studio.md)
 - **Line 15**: **[Warning]** Invalid file link:(~/get-started/get-started-nodejs).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201810031918547412-278%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=73g72mLv1DXZK4ZlnBwsILT7qTfc6024ok0aLJjM%2F3M%3D&st=2018-10-03T19%3A15%3A21Z&se=2018-11-03T19%3A20%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/get-started/get-started-app-studio.md](https://github.com/bcwood/msteams-docs/blob/patch-1/msteams-platform/get-started/get-started-app-studio.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C3%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201810031928469684-278%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sNKnMeZNo%2F%2F4JXFCEIcJtQixnfAoHznJ5RVbn1XqpPE%3D&st=2018-10-03T19%3A25%3A09Z&se=2018-11-03T19%3A30%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by billbliss** [comment]
The typo fix was great, but the change to the path name to get-started-nodejs was not - that's our convention for links, and the .md extension is not used (that link is resolved by the publishing system).

I just did a separate fix to the master directly. Thanks though!

**Comment by bcwood** [comment]
Ok thanks. I wasn't sure on the link, but got confused with the "invalid file link" warning above after the initial PR.

**Comment by billbliss** [comment]
Yes it's an unfortunate artifact of how our publishing platform works. It gives a bunch of warnings and we ignore most of them which is bad, but we don't have a choice. Impossible to know that you were doing the right thing!

**Pull request closed without merging**
