### PR TITLE
[Test PR]

### PR DESCRIPTION
**Pull request by GubbaPallavi**
Please review.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/21113c15c0ed817aa75c23729fc716e1dc22d630/msteams-platform/get-started/code-samples.md) | 84 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90978de9-b2d1-4cca-9fcc-07fb9b07b229) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/testfile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02bc7ef66f10d5ce9a0be1e970dfa88873dc5571/msteams-platform/apps-in-teams-meetings/testfile.md) | 94 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2808483-4dd8-4667-90f5-23134c5da9e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/02bc7ef66f10d5ce9a0be1e970dfa88873dc5571/msteams-platform/get-started/code-samples.md) | 84 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/360e17c7-8ffd-49e4-b362-92c87aebf31a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/testfile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93a9c7fc0182b0e5d025eddb3679cc39be2c5dcd/msteams-platform/apps-in-teams-meetings/testfile.md) | 93 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac68907a-744c-4512-ba84-63e6421051ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93a9c7fc0182b0e5d025eddb3679cc39be2c5dcd/msteams-platform/get-started/code-samples.md) | 84 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2df5b05d-e7de-4f0f-b5ba-fe3537f6a73a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78c14c9ade2356f42fa62bc2d4be56f9b7c4ed5a/msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc767c9d-540d-40fe-8d22-fb5b2f8c709f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/testfile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78c14c9ade2356f42fa62bc2d4be56f9b7c4ed5a/msteams-platform/apps-in-teams-meetings/testfile.md) | 93 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fdfc4a43-167f-45cd-b2bb-2e63bc47d95f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/78c14c9ade2356f42fa62bc2d4be56f9b7c4ed5a/msteams-platform/get-started/code-samples.md) | 84 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0a53c03-2803-420f-a88b-247b60ad5791) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c50c9f2b246a37dc25378dd5e6e328bc65311b9/msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d4df0fe-0c64-46df-8902-26bd1cedf9ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/testfile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c50c9f2b246a37dc25378dd5e6e328bc65311b9/msteams-platform/apps-in-teams-meetings/testfile.md) | 93 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01d2ec79-6220-4549-a426-48504b0f21fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7c50c9f2b246a37dc25378dd5e6e328bc65311b9/msteams-platform/get-started/code-samples.md) | 84 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6f71189-d666-4f63-b1f1-c3fbc26977f9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d8f49713846d3aa1e241684d8ab7ca89dab5e9/msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md) | 90 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae4dafd9-45c7-4f88-8637-75c49b159c18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/testfile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d8f49713846d3aa1e241684d8ab7ca89dab5e9/msteams-platform/apps-in-teams-meetings/testfile.md) | 93 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d219c45e-65ed-4605-8b03-74b0dd94f68b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/code-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90d8f49713846d3aa1e241684d8ab7ca89dab5e9/msteams-platform/get-started/code-samples.md) | 84 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbd72913-b0c3-40cb-bffa-cb13e2c41693) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by surbhigupta12** [comment]
Test PR

**Pull request closed without merging**
