### PR TITLE
[Docenhancement][Featuresupporttable]

### PR DESCRIPTION
**Pull request by v-rodriguezd**
Added features table for support of different cards.

### CODE REVIEW

**Comment by nbokil** [comment]
We need to update this table as follows:

- Add a new column for Message Extension Preview: Only hero & thumbnail cards supported there today
- Rename "Message Extensions" column to "Message Extension Result"
- Update incoming webhook to support all card types except for signin card
- Add some note that for adaptive cards in incoming webhooks, there is limited functionality as listed in the note here: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards#adaptive-cards-and-incoming-webhooks

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2b14b064c36a1673ddb6ce12758095d1bc38dbe/msteams-platform/task-modules-and-cards/cards/cards-reference.md) | 90 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb8b8020-14bb-47ae-89a3-a850b232388f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by nbokil** [comment]
Could you please move the "message extensions preview" column before the "message extensions results" column so they are next to each other?

Can we also make the capitalization & plural nouns consistent? Change it to "Bots", "Message Extension Previews", "Message Extension Results", "Task Modules", "Outgoing Webhooks", "Incoming Webhooks", "O365 Connectors"

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7baac0c133d47bb982c75e1d0dc24fac4951a72b/msteams-platform/task-modules-and-cards/cards/cards-reference.md) | 90 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4591757-01ff-41f7-9ff8-aa100f93b821) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-rodriguezd** [comment]
> Could you please move the "message extensions preview" column before the "message extensions results" column so they are next to each other?
> 
> Can we also make the capitalization & plural nouns consistent? Change it to "Bots", "Message Extension Previews", "Message Extension Results", "Task Modules", "Outgoing Webhooks", "Incoming Webhooks", "O365 Connectors"

@nbokil please note that we do not use Title casing in tables and titles. For now am keeping "Message extension preview", "Message extension results", and "Task modules" as lowercase as otherwise we will have to change throughout all documents. Please confirm.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5abffeb364316211d233b203a2b771072e48cb4c/msteams-platform/task-modules-and-cards/cards/cards-reference.md) | 90 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f05b1f53-933b-46cd-a8fa-9513e0d9410e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by nbokil — APPROVED** [review]
This looks good, thanks!

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
