### PR TITLE
[Doc Improvement][Teams Toolkit overview, sideload and test app, and publish your Teams app][2528202]

### PR DESCRIPTION
**Pull request by v-ksar**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ec2a0b05cac0f8ab02d82b1f517dffbde434492/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bed788b-bba6-4eb9-b6dd-07ccd499c113) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44fc737e413b8fa5483dc17921e2887596ab9e45/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf92cf97-89f1-4a70-aaa4-aaf4517babca) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3438d84ac1ea6da2e17d3e91a8d1bbfcc7fee899/msteams-platform%2Ftoolkit%2Fpublish.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8da7ef0-679a-4524-9a8f-a75dbdb26712) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/sideload-and-test-app-in-Teams-environment.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3438d84ac1ea6da2e17d3e91a8d1bbfcc7fee899/msteams-platform%2Ftoolkit%2Fsideload-and-test-app-in-Teams-environment.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77163edf-bc62-41d3-961d-60f7eca80ea7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3438d84ac1ea6da2e17d3e91a8d1bbfcc7fee899/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 88 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36272ad8-9ec1-4ed2-ae97-10b1016f7c7e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a824bac5c19219150b007ab8903bb91be7de99fa/msteams-platform%2Ftoolkit%2Fpublish.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e035882e-fd63-4997-92ce-d5d16e4d5d2a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/sideload-and-test-app-in-Teams-environment.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a824bac5c19219150b007ab8903bb91be7de99fa/msteams-platform%2Ftoolkit%2Fsideload-and-test-app-in-Teams-environment.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ede32a3-6d47-48be-8c39-f9f75f5a9891) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a824bac5c19219150b007ab8903bb91be7de99fa/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 88 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e1397d1-717a-4a52-9171-cd84cb8a5a4a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9855024a4ce2521a5678fe3f15f0e9c7ddf18fe6/msteams-platform%2Ftoolkit%2Fpublish.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4832ac4f-0886-4889-bba4-933b1e0b8ead) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/sideload-and-test-app-in-Teams-environment.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9855024a4ce2521a5678fe3f15f0e9c7ddf18fe6/msteams-platform%2Ftoolkit%2Fsideload-and-test-app-in-Teams-environment.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ac94732-15bd-45a7-804d-8f4fb8917f02) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9855024a4ce2521a5678fe3f15f0e9c7ddf18fe6/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/086a3b64-6489-46d7-9daa-3fb67e23c56b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e35de25a6e37b56924d0f205ce74be5beba9b796/msteams-platform%2Ftoolkit%2Fpublish.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f90a87f5-346f-414d-9ca9-e05986b49651) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/sideload-and-test-app-in-Teams-environment.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e35de25a6e37b56924d0f205ce74be5beba9b796/msteams-platform%2Ftoolkit%2Fsideload-and-test-app-in-Teams-environment.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6db05f72-add8-410d-84dd-1a46be97fec9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e35de25a6e37b56924d0f205ce74be5beba9b796/msteams-platform%2Ftoolkit%2Fteams-toolkit-fundamentals.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f229871e-fc8e-436c-9cdd-11f9e0e02226) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-abirade** [comment]
The doc has been merged with PR #6470

**Pull request closed without merging**
