### PR TITLE
[Doc Improvement][O365 deprecated note][3937634]

### PR DESCRIPTION
**Pull request by v-bvishnu**
Deprecated note added.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/675a32de9f3b0684ac0df414f3b6fe1da915674b/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42806e15-15ed-4d07-b203-85b93cb5e61c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/interactive-notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/675a32de9f3b0684ac0df414f3b6fe1da915674b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Finteractive-notification-bot-in-teams.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd269051-8b19-4829-a076-c3d7eb3d5114) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/675a32de9f3b0684ac0df414f3b6fe1da915674b/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17264612-dd52-4544-a994-d10611ab86de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/675a32de9f3b0684ac0df414f3b6fe1da915674b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b763c6e8-b6bd-4d64-b59f-00194552770e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/675a32de9f3b0684ac0df414f3b6fe1da915674b/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6d67615-bc66-48b6-9367-f60b02eb5de3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/675a32de9f3b0684ac0df414f3b6fe1da915674b/msteams-platform%2Fconcepts%2Fdesign%2Funderstand-use-cases.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05f99243-885b-4595-a304-2785b61da788) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/675a32de9f3b0684ac0df414f3b6fe1da915674b/msteams-platform%2Fresources%2Fbot-v3%2Fbots-overview.md) | 84 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b82c368-1ceb-40c6-aa85-f1cb1687a269) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/675a32de9f3b0684ac0df414f3b6fe1da915674b/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e0ff533-7eeb-4d2a-a45e-b85b7aa5fa36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/675a32de9f3b0684ac0df414f3b6fe1da915674b/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/075c79f1-b2d5-4038-a77a-a5309f8a42e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/675a32de9f3b0684ac0df414f3b6fe1da915674b/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 100 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c64fe3b0-378a-4e79-999a-6336de29af01) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3acd0de51233150be3f0bf556c571cfe3cd35570/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d095e55-950c-4dd6-901f-0cf5ef3f9439) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/interactive-notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3acd0de51233150be3f0bf556c571cfe3cd35570/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Finteractive-notification-bot-in-teams.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/997b7930-45e8-4128-834e-4bbb1eb6d08c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3acd0de51233150be3f0bf556c571cfe3cd35570/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff7497e4-89f6-4189-bf98-35fce6b1cef2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3acd0de51233150be3f0bf556c571cfe3cd35570/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1aea343a-a39d-4644-8537-e209d713dcd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3acd0de51233150be3f0bf556c571cfe3cd35570/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a973d4ea-a210-47bb-91ae-0b33b3db60d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3acd0de51233150be3f0bf556c571cfe3cd35570/msteams-platform%2Fconcepts%2Fdesign%2Funderstand-use-cases.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d0c2f5b-4083-4ba6-a19f-cd2405d8a93b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3acd0de51233150be3f0bf556c571cfe3cd35570/msteams-platform%2Fresources%2Fbot-v3%2Fbots-overview.md) | 84 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a321eb35-a4c2-4200-9b84-576256a0176a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3acd0de51233150be3f0bf556c571cfe3cd35570/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47f81391-8a74-45e2-9576-4e1d564214ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3acd0de51233150be3f0bf556c571cfe3cd35570/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dbb4fc7-b63e-496a-9be8-02cd438885e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3acd0de51233150be3f0bf556c571cfe3cd35570/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae41fc1e-c0d9-4a90-b6eb-75c258b59e28) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ce24c7c43d43fa8bfd9fb060668ce807b4cd492/msteams-platform%2Fbots%2Fbot-features.md) | 91 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6996779-b3eb-442e-8491-ce2dc1f81144) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/interactive-notification-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ce24c7c43d43fa8bfd9fb060668ce807b4cd492/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Finteractive-notification-bot-in-teams.md) | 91 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/585bc961-ca58-4b9e-9a59-f607388d291d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ce24c7c43d43fa8bfd9fb060668ce807b4cd492/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fd16121-7b46-4d7f-8d0f-b921d9a32dbf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ce24c7c43d43fa8bfd9fb060668ce807b4cd492/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ccc621d-71e4-4003-9f81-212cfe9ed838) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ce24c7c43d43fa8bfd9fb060668ce807b4cd492/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0acdf390-bfd0-4790-8caf-e3080b879b57) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ce24c7c43d43fa8bfd9fb060668ce807b4cd492/msteams-platform%2Fresources%2Fbot-v3%2Fbots-overview.md) | 84 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf9e8af6-f7fc-4a5c-8b46-ff3b422215e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrating-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ce24c7c43d43fa8bfd9fb060668ce807b4cd492/msteams-platform%2Fsamples%2Fintegrating-web-apps.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90c4e9aa-dcb8-4d86-9d67-ae7e4e61d3e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6ce24c7c43d43fa8bfd9fb060668ce807b4cd492/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01b6b6e6-9099-4713-a0e6-f6bc1e2b5675) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-npaladugu — APPROVED** [review]

**Review by Wajeed-msft — APPROVED** [review]

**Comment by surbhigupta12** [comment]
Closing this PR as the changes are made in #11554

**Pull request closed without merging**
