### PR TITLE
[Doc improvement][Address Markdown warnings Ph-2][2288360]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/apps-in-teams-meetings/API-references.md) | 92 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d25170d6-1ba9-4bf0-8ded-0d0fee7f797e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/concepts/authentication/authentication.md) | 87 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cfce4ca-1a0b-4b83-8880-d1d322c30c2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/app-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/concepts/build-and-test/app-studio-overview.md) | 84 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9bfd768-a860-45d5-94c2-818fb593fc32) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c3235d8-ef4d-49d0-bcd6-670c331c6b6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/concepts/build-and-test/teams-developer-portal.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/835341d9-05a5-465b-9a8b-2261c3693d34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9300cbbd-6db5-4c2c-b22a-81cf71e175c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | 82 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e45a3e97-9553-4d69-8d5a-018baa52e719) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/resources/dev-preview/developer-preview-intro.md) | 80 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e3b70fa-4adb-49b6-a3d7-6e65d6d563e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/tabs/how-to/access-teams-context.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/120b67dd-abe9-4a20-bcd4-8a3830b6d9c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md) | 81 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f591b4c0-f6ff-4b0a-9829-ae6dc22332a2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b58ffbc5-9dbe-458c-a911-e08faf143913) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | 86 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ac7c3b4-dd22-43cc-80d5-f7bdf234bcce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5177725a-6ae6-46ad-869a-9f90589b5a29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/task-modules-and-cards/cards/design-effective-cards.md) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/955478f6-8c89-49e6-9d75-bf7b0bc2290c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/132225d0-8a10-4028-8bbb-c102d729b6eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b144203ce4ed702c81d777c2255b5152da4317e9/msteams-platform/whats-new.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10fd0b6b-e04c-4d95-b17c-c1666f06047a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/apps-in-teams-meetings/API-references.md) | 92 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e327606f-fc16-4285-ab06-f4a6c9bec782) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/concepts/authentication/authentication.md) | 87 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/efcb8f0d-1911-466c-ab70-f74f43825f8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/app-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/concepts/build-and-test/app-studio-overview.md) | 84 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0dac0b0b-8a78-409c-a2e0-ca8c7d9592a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b331f81-f94c-4ed0-b133-481aef038925) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/concepts/build-and-test/teams-developer-portal.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33c6a54e-cfd1-4480-9d05-a8c3941168ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56c93560-d181-4254-8c1b-2673634b8317) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | 82 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1af474d5-69d2-4a2d-b9b9-c45f1b24afe6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/resources/dev-preview/developer-preview-intro.md) | 80 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6493552-21cc-48d5-a4e8-85dc4e73132d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/tabs/how-to/access-teams-context.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3baa31ac-780f-4719-84fb-f0c74ac4c739) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md) | 81 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/213e30dc-984d-4549-a6fe-a38695bfc073) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51397e43-eed8-4980-aa58-c0dc9e0eb5fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | 86 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bc4e41b-fe43-4a5a-8d3d-921ac9f300aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5be32071-acb4-44f3-9766-f4d00b471333) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/task-modules-and-cards/cards/design-effective-cards.md) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75ee67bf-1cfb-410f-99fc-ab4cbbcf3b6d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f19de69-fb53-4373-b87f-b95f83e7c658) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5dd61311f656e16db0a0b951a3bbaa9edd06f60b/msteams-platform/whats-new.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37ce82b3-1e0f-4737-b01b-35d391e18f29) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/apps-in-teams-meetings/API-references.md) | 92 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7a983ca-2b4c-4dad-aa57-4cde03e525d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/bots/bot-features.md) | 86 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c550dcc0-607e-4ace-a7ad-fb50ed35f5b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/concepts/authentication/authentication.md) | 87 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0c0459c-3d61-4cf6-b59f-dd2f6faa8a60) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/app-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/concepts/build-and-test/app-studio-overview.md) | 84 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2724eb2-db46-4daf-8b08-59646435e937) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d318c66-1ad9-4af3-a042-1888c289be2c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/concepts/build-and-test/teams-developer-portal.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d66b1b27-8d39-4649-9439-5750f872d28f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfc0d80f-5f3c-4bcb-90d7-0bc2db4123f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | 82 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac97cf43-3cab-4a84-a559-db161b9a1e01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/resources/dev-preview/developer-preview-intro.md) | 80 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf97eb1e-6d63-4042-9027-1b8ce0513497) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/tabs/how-to/access-teams-context.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f84cfa8-02bc-4522-b5f6-f3fa61c82b6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md) | 81 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a29376eb-511e-4c0d-8d67-777e7f07d45b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffdc3d03-62ca-44e0-bd3a-52554b1bfbb1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | 86 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e4ac0bf-8b02-4a27-b571-d9e5ef974dc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fefaae73-9fe7-4dcb-9937-53bf1b607b49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/task-modules-and-cards/cards/design-effective-cards.md) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25d8b680-a697-49c2-832b-96bb9368f169) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a16fb15-8693-4376-ab30-775995783468) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9290028d58cc8eb8c9bdd2d1739fd740b3df4258/msteams-platform/whats-new.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0fa3f59-b35d-4d0d-9479-01c98be4308b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/API-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/apps-in-teams-meetings/API-references.md) | 92 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be0c0ed8-442c-4745-86dd-9d63f73f4d9b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/bots/bot-features.md) | 86 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d1b9858-65b2-466b-be97-51f4417e55e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/concepts/authentication/authentication.md) | 87 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f523f29c-24f2-456f-a070-586d98225bcc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/app-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/concepts/build-and-test/app-studio-overview.md) | 84 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/423f0d4c-ab0a-4021-a92b-6e2dff33c8fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/concepts/build-and-test/prepare-your-o365-tenant.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4b2cc0e-eb23-4bd7-93bc-b66bc34c18d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/concepts/build-and-test/teams-developer-portal.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/efd153a2-ffc5-4117-8412-81ccb8a05d76) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/concepts/device-capabilities/native-device-permissions.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0dec7f5-20f7-435b-9428-e7ba0c8f55f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/resources/bot-v3/bot-conversations/bots-conversations.md) | 82 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53ca250b-4109-4c18-b693-822b8ddb3074) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/resources/dev-preview/developer-preview-intro.md) | 80 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffea6eac-4fed-4e58-b85d-e7f9bb15b88e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/tabs/how-to/access-teams-context.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c7eacb6-e605-41bc-8dec-f166e0f9b44b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/tabs/how-to/authentication/auth-tab-aad.md) | 81 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51e617cf-039a-4664-ae3d-2e549c9c8ef6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47da41a5-388d-4ad6-8be3-3b8efd0c4e4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/tabs/how-to/create-tab-pages/content-page.md) | 86 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89109eb2-cfbc-463c-ac3a-4fa5de7d9198) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/cards-actions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/task-modules-and-cards/cards/cards-actions.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2037ecc1-676f-4b6a-8e79-3758db6d3469) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/task-modules-and-cards/cards/design-effective-cards.md) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14839ed3-cbfa-4943-8c1b-363a4b6d9168) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/webhooks-and-connectors/how-to/connectors-creating.md) | 91 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3cf456ed-14fa-4dec-9024-01de599e3c35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/53f80532bcf4775c432085eba2ac88231f0121d4/msteams-platform/whats-new.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17837a19-4e3e-4646-bac8-9cf5455e730b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
