### PR TITLE
[Doc Improvement][SEO meta description update][3915735]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3bc63923dbf54fc92ec359a449820e1479169b1c/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 93 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ce663db-443f-4ce0-8dcc-1d63b084546a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3bc63923dbf54fc92ec359a449820e1479169b1c/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76307de3-8639-49bb-9a1d-8ef1fcd88b11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3bc63923dbf54fc92ec359a449820e1479169b1c/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59dcc439-5590-4e61-bb9c-5013520e57c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3bc63923dbf54fc92ec359a449820e1479169b1c/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/319fa716-c2f1-42d4-a7b0-49339e766f9e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3bc63923dbf54fc92ec359a449820e1479169b1c/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45226e61-6a86-4aec-a493-b48cf446c104) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-your-Teams-app-test-tool.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3bc63923dbf54fc92ec359a449820e1479169b1c/msteams-platform%2Ftoolkit%2Fdebug-your-Teams-app-test-tool.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de58be6b-44df-4766-9dcc-00a399dce3ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy-Teams-app-to-container-service.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3bc63923dbf54fc92ec359a449820e1479169b1c/msteams-platform%2Ftoolkit%2Fdeploy-Teams-app-to-container-service.md) | 92 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e25d4ed-66d8-49df-9d13-d74dca04fa50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3bc63923dbf54fc92ec359a449820e1479169b1c/msteams-platform%2Ftoolkit%2Fdeploy.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f470b3f-a050-4501-aeea-5f7632d9d7e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/explore-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3bc63923dbf54fc92ec359a449820e1479169b1c/msteams-platform%2Ftoolkit%2Fexplore-Teams-Toolkit.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b4d9c26-3240-4764-a206-f6fbdaad57e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3bc63923dbf54fc92ec359a449820e1479169b1c/msteams-platform%2Ftoolkit%2Ffaq.md) | 85 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/126086a9-6072-4bff-846f-a5d4ea1ae52f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1c03809b69d5e18039c1f21339b63bcce11057/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 93 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ea5ec83-966a-4798-adbb-f1e0257a4f7f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1c03809b69d5e18039c1f21339b63bcce11057/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70df6aea-7dd6-42fa-ab74-2c4a66a2f265) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1c03809b69d5e18039c1f21339b63bcce11057/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5979737a-d34d-4b61-b594-8895d3464b0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1c03809b69d5e18039c1f21339b63bcce11057/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/246f51fb-3989-4e74-8edd-1fd423783ae9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1c03809b69d5e18039c1f21339b63bcce11057/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e26d920e-8e6b-4c86-9177-fd9634baf443) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-your-Teams-app-test-tool.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1c03809b69d5e18039c1f21339b63bcce11057/msteams-platform%2Ftoolkit%2Fdebug-your-Teams-app-test-tool.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d9a56e0-5357-46f8-be5d-d880b2c78799) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy-Teams-app-to-container-service.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1c03809b69d5e18039c1f21339b63bcce11057/msteams-platform%2Ftoolkit%2Fdeploy-Teams-app-to-container-service.md) | 92 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6705abd-524e-44f7-81ed-1cfb64e76799) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1c03809b69d5e18039c1f21339b63bcce11057/msteams-platform%2Ftoolkit%2Fdeploy.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a8af734-1106-412e-b4f9-c59282ba56af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/explore-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1c03809b69d5e18039c1f21339b63bcce11057/msteams-platform%2Ftoolkit%2Fexplore-Teams-Toolkit.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e88319a2-ad6c-4915-b1c6-29e4e9533e0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed1c03809b69d5e18039c1f21339b63bcce11057/msteams-platform%2Ftoolkit%2Ffaq.md) | 85 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/728a516d-8502-4089-b038-3215ae7ce1b0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e1184a3f4e239201a8ae91663b2a169362298bd/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 93 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7ee6338-e97c-45f6-b022-004f2131853b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e1184a3f4e239201a8ae91663b2a169362298bd/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8230fe6c-cccf-414c-b4ef-3da80d5facf1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e1184a3f4e239201a8ae91663b2a169362298bd/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/feee19f9-d5a8-41fd-b848-6a01c6d34b61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e1184a3f4e239201a8ae91663b2a169362298bd/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65046136-29dd-4ac9-bb86-b75743899be9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e1184a3f4e239201a8ae91663b2a169362298bd/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45002634-6c6b-453a-9612-30e00d07b7af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-your-Teams-app-test-tool.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e1184a3f4e239201a8ae91663b2a169362298bd/msteams-platform%2Ftoolkit%2Fdebug-your-Teams-app-test-tool.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af2f8cf0-4b86-417c-8f8d-d76cc007e84e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy-Teams-app-to-container-service.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e1184a3f4e239201a8ae91663b2a169362298bd/msteams-platform%2Ftoolkit%2Fdeploy-Teams-app-to-container-service.md) | 92 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7924e9ea-db70-4313-b3c8-b52d5919913b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e1184a3f4e239201a8ae91663b2a169362298bd/msteams-platform%2Ftoolkit%2Fdeploy.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81f1250c-d49b-4f88-97c5-216dac3bb0c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/explore-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e1184a3f4e239201a8ae91663b2a169362298bd/msteams-platform%2Ftoolkit%2Fexplore-Teams-Toolkit.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e94145e2-e120-4343-a185-295af3025a21) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2e1184a3f4e239201a8ae91663b2a169362298bd/msteams-platform%2Ftoolkit%2Ffaq.md) | 85 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50bef224-c565-4546-9684-6cfac7ef33d0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6e8a7aae20a6cf217ca75baa347be0efcb9d359/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 93 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd37b4d3-ff25-499f-9521-100cb559d8ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6e8a7aae20a6cf217ca75baa347be0efcb9d359/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcbc0ca8-1a99-42d5-9f2e-39d9da4eeefa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6e8a7aae20a6cf217ca75baa347be0efcb9d359/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39964a57-2a39-4ee2-8b80-e5609e28d492) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6e8a7aae20a6cf217ca75baa347be0efcb9d359/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c96a88b9-0e0a-4ade-b7d3-cdd7a06a05cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6e8a7aae20a6cf217ca75baa347be0efcb9d359/msteams-platform%2Ftoolkit%2Fdebug-overview.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e94c868c-08b0-4f88-bc6e-b18915665fa2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-your-Teams-app-test-tool.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6e8a7aae20a6cf217ca75baa347be0efcb9d359/msteams-platform%2Ftoolkit%2Fdebug-your-Teams-app-test-tool.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/968f8f16-9355-41fd-9b92-34e3f203b249) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy-Teams-app-to-container-service.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6e8a7aae20a6cf217ca75baa347be0efcb9d359/msteams-platform%2Ftoolkit%2Fdeploy-Teams-app-to-container-service.md) | 92 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/232f4b69-9992-4a66-a781-e2862c028d16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6e8a7aae20a6cf217ca75baa347be0efcb9d359/msteams-platform%2Ftoolkit%2Fdeploy.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d07667f-3da2-401a-aac2-49affc8ed9ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/explore-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6e8a7aae20a6cf217ca75baa347be0efcb9d359/msteams-platform%2Ftoolkit%2Fexplore-Teams-Toolkit.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c003952-95b8-4bc8-9ca8-cb60e134cfe3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6e8a7aae20a6cf217ca75baa347be0efcb9d359/msteams-platform%2Ftoolkit%2Ffaq.md) | 85 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d60acade-770a-498d-a21a-2095cb6285d7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
