### PR TITLE
fix link

### PR DESCRIPTION
**Pull request by paul-cheung**

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[f2a84cb](https://github.com/paul-cheung/msteams-docs/pull/569/commits/f2a84cbe2d6c99977fb5984b1fe7eb777e76f31c)_: 

:clock10: **Pending**: waiting for processors ([30](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 30 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[f2a84cb](https://github.com/paul-cheung/msteams-docs/pull/569/commits/f2a84cbe2d6c99977fb5984b1fe7eb777e76f31c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/apps/apps-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-overview.md) | :warning:Warning | | [Details](#user-content-c3c35d81-85527ca1)

<a id="c3c35d81-85527ca1"></a>
### [msteams-platform/concepts/apps/apps-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-overview.md)
 - **Line 15**: **[Warning]** Invalid file link:(~/concepts/tabs/tabs-overview).
 - **Line 16**: **[Warning]** Invalid file link:(~/concepts/bots/bots-overview).
 - **Line 17**: **[Warning]** Invalid file link:(~/concepts/connectors/connectors).
 - **Line 18**: **[Warning]** Invalid file link:(~/concepts/compose-extensions).
 - **Line 19**: **[Warning]** Invalid file link:(~/concepts/activity-feed).
 - **Line 22**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 24**: **[Warning]** Invalid file link:(~/get-started/get-started-app-studio).
 - **Line 26**: **[Warning]** Invalid file link:(~/resources/design/overview).
 - **Line 26**: **[Warning]** Invalid file link:(~/concepts/apps/apps-design).
 - **Line 28**: **[Warning]** Invalid file link:(~/concepts/apps/apps-upload).
 - **Line 30**: **[Warning]** Invalid file link:(~/publishing/apps-publish).
 - **Line 36**: **[Warning]** Invalid file link:(~/get-started/get-started-dotnet-app-studio).
 - **Line 37**: **[Warning]** Invalid file link:(~/get-started/get-started-nodejs-app-studio).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904170144107436-569%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=x8DFO1eR1Qs3xoBr3kEGZA9cu81L2sbO0n08yW5ecXk%3D&st=2019-04-17T01%3A41%3A41Z&se=2019-05-18T01%3A46%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[5fdf1fe](https://github.com/paul-cheung/msteams-docs/pull/569/commits/5fdf1feaecdcb6252af8e1357b8b4203599a42f2)_: 

:clock10: **Pending**: waiting for processors ([9](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[5fdf1fe](https://github.com/paul-cheung/msteams-docs/pull/569/commits/5fdf1feaecdcb6252af8e1357b8b4203599a42f2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/apps/apps-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-overview.md) | :warning:Warning | | [Details](#user-content-c3c35d81-12afef48)
[msteams-platform/concepts/apps/apps-upload.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-upload.md) | :warning:Warning | | [Details](#user-content-0a22493f-12afef48)

<a id="c3c35d81-12afef48"></a>
### [msteams-platform/concepts/apps/apps-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-overview.md)
 - **Line 15**: **[Warning]** Invalid file link:(~/concepts/tabs/tabs-overview).
 - **Line 16**: **[Warning]** Invalid file link:(~/concepts/bots/bots-overview).
 - **Line 17**: **[Warning]** Invalid file link:(~/concepts/connectors/connectors).
 - **Line 18**: **[Warning]** Invalid file link:(~/concepts/compose-extensions).
 - **Line 19**: **[Warning]** Invalid file link:(~/concepts/activity-feed).
 - **Line 22**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 24**: **[Warning]** Invalid file link:(~/get-started/get-started-app-studio).
 - **Line 26**: **[Warning]** Invalid file link:(~/resources/design/overview).
 - **Line 26**: **[Warning]** Invalid file link:(~/concepts/apps/apps-design).
 - **Line 28**: **[Warning]** Invalid file link:(~/concepts/apps/apps-upload).
 - **Line 30**: **[Warning]** Invalid file link:(~/publishing/apps-publish).
 - **Line 36**: **[Warning]** Invalid file link:(~/get-started/get-started-dotnet-app-studio).
 - **Line 37**: **[Warning]** Invalid file link:(~/get-started/get-started-nodejs-app-studio).

<a id="0a22493f-12afef48"></a>
### [msteams-platform/concepts/apps/apps-upload.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-upload.md)
 - **Line 15**: **[Warning]** Invalid file link:(~/resources/dev-preview/developer-preview).
 - **Line 17**: **[Warning]** Invalid file link:(~/concepts/bots/bots-test#adding-a-bot-for-personal-chat-only).
 - **Line 23**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 50**: **[Warning]** Invalid file link:(~/resources/dev-preview/developer-preview).
 - **Line 85**: **[Warning]** Invalid file link:(~/concepts/tabs/tabs-configuration).
 - **Line 107**: **[Warning]** Invalid file link:(~/concepts/connectors/connectors).
 - **Line 128**: **[Warning]** Invalid file link:(~/resources/schema/manifest-schema).
 - **Line 128**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 130**: **[Warning]** Invalid file link:(~/troubleshoot/troubleshoot).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C17%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904170149417823-569%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GCp0TMlU%2Bx6pMkJgMHfU3FG9Cg%2FPIqQ8F%2BiUpOfra1w%3D&st=2019-04-17T01%3A45%3A56Z&se=2019-05-18T01%3A50%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[b65fee7](https://github.com/paul-cheung/msteams-docs/pull/569/commits/b65fee7b8970bb0c250d2ea69413b10bf52b9ae6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/apps/apps-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-overview.md) | :warning:Warning | | [Details](#user-content-c3c35d81-7b9311f8)
[msteams-platform/concepts/apps/apps-upload.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-upload.md) | :warning:Warning | | [Details](#user-content-0a22493f-7b9311f8)

<a id="c3c35d81-7b9311f8"></a>
### [msteams-platform/concepts/apps/apps-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-overview.md)
 - **Line 26**: **[Warning]** Invalid file link:(~/concepts/apps/apps-design).

<a id="0a22493f-7b9311f8"></a>
### [msteams-platform/concepts/apps/apps-upload.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-upload.md)
 - **Line 15**: **[Warning]** Invalid file link:(~/resources/dev-preview/developer-preview).
 - **Line 17**: **[Warning]** Invalid file link:(~/concepts/bots/bots-test#adding-a-bot-for-personal-chat-only).
 - **Line 23**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 50**: **[Warning]** Invalid file link:(~/resources/dev-preview/developer-preview).
 - **Line 85**: **[Warning]** Invalid file link:(~/concepts/tabs/tabs-configuration).
 - **Line 107**: **[Warning]** Invalid file link:(~/concepts/connectors/connectors).
 - **Line 128**: **[Warning]** Invalid file link:(~/resources/schema/manifest-schema).
 - **Line 128**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 130**: **[Warning]** Invalid file link:(~/troubleshoot/troubleshoot).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904191946589157-569%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BVEQ6Kpf89Jm%2F184H%2F44aEZRlkU5DpFWNzul4ey4B3o%3D&st=2019-04-19T19%3A43%3A21Z&se=2019-05-20T19%3A48%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[cd244ad](https://github.com/paul-cheung/msteams-docs/pull/569/commits/cd244ad64778a799a2148d0406fba09b11aa8708)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/apps/apps-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-overview.md) | :warning:Warning | | [Details](#user-content-c3c35d81-23254b28)
[msteams-platform/concepts/apps/apps-upload.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-upload.md) | :warning:Warning | | [Details](#user-content-0a22493f-23254b28)

<a id="c3c35d81-23254b28"></a>
### [msteams-platform/concepts/apps/apps-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-overview.md)
 - **Line 26**: **[Warning]** Invalid file link:(~/concepts/apps/apps-design).

<a id="0a22493f-23254b28"></a>
### [msteams-platform/concepts/apps/apps-upload.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-upload.md)
 - **Line 17**: **[Warning]** Illegal link: `&lt;a href=&quot;concepts/bots/bots-test.md#adding-a-bot-for-personal-chat-only&quot;&gt;Adding a bot for personal chat only&lt;/a&gt;` -- missing bookmark. The file concepts/bots/bots-test.md doesn&#39;t contain a bookmark named adding-a-bot-for-personal-chat-only.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904191953097125-569%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UpnIzEzsj9pk3oiC%2FV2S6AzjyCwIP91laqeK1caAo8M%3D&st=2019-04-19T19%3A49%3A19Z&se=2019-05-20T19%3A54%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[6bf9966](https://github.com/paul-cheung/msteams-docs/pull/569/commits/6bf9966699304bbe50fe4f1b5456ae88c1aa73f7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/apps/apps-upload.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-upload.md) | :warning:Warning | | [Details](#user-content-0a22493f-6b7b51dd)
[msteams-platform/concepts/apps/apps-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-overview.md) | :white_check_mark:Succeeded | |

<a id="0a22493f-6b7b51dd"></a>
### [msteams-platform/concepts/apps/apps-upload.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-upload.md)
 - **Line 17**: **[Warning]** Illegal link: `&lt;a href=&quot;concepts/bots/bots-test.md#adding-a-bot-for-personal-chat-only&quot;&gt;Adding a bot for personal chat only&lt;/a&gt;` -- missing bookmark. The file concepts/bots/bots-test.md doesn&#39;t contain a bookmark named adding-a-bot-for-personal-chat-only.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904191953457148-569%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=EHTUnAmcqVvc3N0Ay%2FlspmbI2QekIA%2BUPPzGromxVT8%3D&st=2019-04-19T19%3A50%3A36Z&se=2019-05-20T19%3A55%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[71fb598](https://github.com/paul-cheung/msteams-docs/pull/569/commits/71fb59835bc30ac6892aeb956f3faca25dabf09d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/apps/apps-overview.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-overview.md) | :white_check_mark:Succeeded | |
[msteams-platform/concepts/apps/apps-upload.md](https://github.com/paul-cheung/msteams-docs/blob/fix-link/msteams-platform/concepts/apps/apps-upload.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201904191956206681-569%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5%2FQNj%2BfA47rlIYL2SlC%2FnBSBjdgr2fOpS0BaSAKUi7M%3D&st=2019-04-19T19%3A52%3A30Z&se=2019-05-20T19%3A57%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clearab** [comment]
Thanks again @paul-cheung!

**Pull request merged**
