### PR TITLE
[Doc Update][Add Sample Prompts]

### PR DESCRIPTION
**Pull request by v-ypalikila**
Updated sample prompts content

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dde480656c906f4361ddd990511fb48851496073/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 93 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59f57958-0085-43b7-a50e-3b46292d8bb3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af176ab336ffa1b4cc243b9971832f4c0c0f6b3a/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 93 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e71062e-9e3d-4033-8c92-e5182aae70f8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59ef43d948a70c952c8482a8178db8f99e1efa36/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 93 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e0c8a67-b8be-4d27-aa13-4b736d6e5503) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/59ef43d948a70c952c8482a8178db8f99e1efa36/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 85 | 122 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a28afa6d-ea03-4ce0-a96e-309cafe82d85) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e903fdd54eaf7909a90ff0e8a27b4eed6f475d19/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 93 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc613d65-eb71-4317-91ca-29b00cb6b6c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e903fdd54eaf7909a90ff0e8a27b4eed6f475d19/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 133 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39a91124-3815-428a-a49f-52ad2ac352e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e903fdd54eaf7909a90ff0e8a27b4eed6f475d19/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 85 | 122 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b91fcf37-0bef-41f4-b7e1-19d49f06c1a2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c9eb3360f1966ef9daa1afce3b9aa894a718f532/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 93 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80d79f50-a2eb-4396-bb89-dedfacd2bb17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c9eb3360f1966ef9daa1afce3b9aa894a718f532/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 133 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e98aa29-9f62-44e6-864d-3b5d79e287e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c9eb3360f1966ef9daa1afce3b9aa894a718f532/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 85 | 122 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99db9767-483e-479b-9241-3938475eb711) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dac21a5f0899ec1692ee4bbcdbe902db22e3652/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 93 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3db056e-7a88-4afe-ae79-29ef618a5dc7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dac21a5f0899ec1692ee4bbcdbe902db22e3652/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 133 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a69a04c-76f9-43aa-b65a-acd021432f49) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dac21a5f0899ec1692ee4bbcdbe902db22e3652/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 85 | 122 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3daba1d9-80c0-46e2-b8e7-13e7417d898b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf3abe962770f8fa00a20ef37571c18f42505399/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 93 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/149ecc5c-6a30-4d31-9f5b-4bebc999b138) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf3abe962770f8fa00a20ef37571c18f42505399/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 85 | 122 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f89c9287-38ae-41e8-bc88-c4c544aa9070) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/46d4e18eb8c61b79e2ba08647718a5a45eb9268d/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 93 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ffda48d-ab91-43f4-a6c8-26d2a6a56813) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/46d4e18eb8c61b79e2ba08647718a5a45eb9268d/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema.md) | 85 | 122 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c574c473-fc4f-4797-9f39-978b3d9b1a34) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0a3bfa81f7e2ee2349c22f439028f7d9d77b327/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 93 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccf6a39b-45a5-41a2-a047-5eb20be397a3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
