### PR TITLE
[Doc Improvement][Teams 2.1 update][3427661]

### PR DESCRIPTION
**Pull request by v-vanv**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1cac01d2559213327d1108c2dc4da28464daf494/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 87 | 96 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/490deb0a-9538-403f-987b-0dcb44cc4197) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ef402957223f2ae622813b08d09620d3888c528/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 90 | 75 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ad6b810-995b-469b-994f-8166b64b070b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/af1871d0eeaa7ecb01acc1fc802f3e1b9f4954ad/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 90 | 75 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d26de69-21ae-407c-bb0e-954f6dc88632) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d178adf47bd408d263f18c8470fe1f1c7467214b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96e0d99f-bb9b-4468-a4fd-0ee77cffe927) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d178adf47bd408d263f18c8470fe1f1c7467214b/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 90 | 75 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b97daeb-5855-4742-87ec-691e9a7de83a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b620a02cacca786ffbba89aba2606838ea9a9827/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17c68d83-2555-4a3f-aa82-c4fcee61008f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b620a02cacca786ffbba89aba2606838ea9a9827/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 90 | 75 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3175d019-9e97-4e34-ae7e-3f763885f093) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f9d2d908ff4c109220d8ad111c1440523aa1433/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bf6c784-75dc-483c-8cc6-47f52c832853) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f9d2d908ff4c109220d8ad111c1440523aa1433/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 90 | 75 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea89bc44-a4b2-4997-8140-52c37384a8a2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bf20ec8a995ec5d33dfc851865ed8c23372e7c2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85df6e56-87b2-42fe-b5d7-d0c5faeac317) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4bf20ec8a995ec5d33dfc851865ed8c23372e7c2/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 90 | 75 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/934449f4-7adb-4590-8560-0739f7d7d3c1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d12d6d3fad3ab268447725f5c3895890f453cf7/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1288bf8a-1709-4460-9b38-b6cf18cbed83) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2d12d6d3fad3ab268447725f5c3895890f453cf7/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 90 | 72 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/482e4552-d496-4ca1-bd0a-4153565fc5c5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b674eedcbf6f7f3feada8d3dd7524f5178468b4/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/027daca5-5648-4ada-8c3b-0f2b5298adc6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b674eedcbf6f7f3feada8d3dd7524f5178468b4/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 89 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cbb5b90d-98f5-4447-b719-c05355fd2b26) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/channel-messages-with-rsc.md](https://github.com/MicrosoftDocs/msteams-docs/blob/69b62b0292dd25e3085177e68f7999ab71abcd1d/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-messages-with-rsc.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf8d8de7-78ad-41cb-b361-0029e3e8ddf6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-channel-group-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/69b62b0292dd25e3085177e68f7999ab71abcd1d/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-channel-group-tab.md) | 89 | 77 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c98ccb5-a4e1-4985-98d4-a4967bbf6271) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
