### PR TITLE
[Doc Feature][Decide between ME and add-in]

### PR DESCRIPTION
**Pull request by Rick-Kirkham**
DO NOT MERGE.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/273e47acebd9ddbea44b8b9e8acc2987834b9d60/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74519d67-f5cd-4b49-8b66-f641184a7f70) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/273e47acebd9ddbea44b8b9e8acc2987834b9d60/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 88 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34b7813b-6bc1-48bd-9975-508341c41376) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/752eb44bce73bb2c5eaeab11742a2d7e4b268edc/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d08e8863-8c17-4dac-a687-71333a7bf3eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/752eb44bce73bb2c5eaeab11742a2d7e4b268edc/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 88 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf114ea2-976d-4748-b071-d82f36045068) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7ef0c1ef57a921167aea6787c8ca7e9da557f92d/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/651294a6-be2d-434d-b0ac-2e97ea3cd5c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ef0c1ef57a921167aea6787c8ca7e9da557f92d/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/945d68a0-2516-43e2-a289-878d6c2d2fbb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f42558aaf5d224cdb907d958a9655cee1d83b7c6/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c37a3718-16dd-4806-b666-4e2548a79c53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f42558aaf5d224cdb907d958a9655cee1d83b7c6/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef08959d-baef-48d6-8d55-f48201cb910f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/82ae2f6f19793069eca37db843df5649e8dc84d5/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01105270-cb28-4c58-9ebc-c889f9e33df2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/82ae2f6f19793069eca37db843df5649e8dc84d5/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8a652e8-35b1-4bd1-a3c2-44e6386af490) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/630d7140ef48507bccd04024aab686544c607984/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/572e3cdd-ca63-4bcc-b565-da00cb16db25) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/630d7140ef48507bccd04024aab686544c607984/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/875c6145-5e21-4aaf-aef1-8d75f181b391) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/95a4f32d3f506e42b6b5215600d08d2cd8418172/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/324dc781-333a-4c94-a933-8b2ffad22d6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95a4f32d3f506e42b6b5215600d08d2cd8418172/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9bee1b79-fc57-4bc4-b3ec-f3ad9a8d8ac5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2631cacb3a408f9c71faba8d49215a3ae8e2aa69/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fadfc012-083c-4408-9a63-c4088c7a8428) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2631cacb3a408f9c71faba8d49215a3ae8e2aa69/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf6d343a-661e-42c2-a3a6-a9968c7cd29c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9f3dce0b45c4e030332b35a3288c7b3213b2f202/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24817526-fc49-482e-bad9-0d6bfce7b581) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9f3dce0b45c4e030332b35a3288c7b3213b2f202/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62c3e12c-74bd-4a0c-a32f-4cfa3cbfebaa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ad636f56eb94e2c234e5958591f5f8bc47300fb2/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2b31ab63-acae-4f6a-813d-1d1b9ccaf73c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ad636f56eb94e2c234e5958591f5f8bc47300fb2/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c9ba8db-3744-4104-8024-f249e8b67cd5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3c67df9975dd96bcb7855f22f427f24ce9b105b7/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d535b8c1-c152-4561-b06d-5a7ddb258613) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3c67df9975dd96bcb7855f22f427f24ce9b105b7/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd72cbcc-0c99-4751-8406-8869b565c433) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b10e103b7f9b54ae62c3ca8304b0712b577b13b9/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/73f41be9-b397-4c25-9fe8-b98b130eec6c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b10e103b7f9b54ae62c3ca8304b0712b577b13b9/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e27fa6d8-1ab9-4a03-ab5b-a073d64e5e77) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c24ff11a1c4600b5beb853f56c61a5533706ba33/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c53d5285-c28a-45b1-9353-65902d834dfe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c24ff11a1c4600b5beb853f56c61a5533706ba33/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef139ef6-faa4-4107-8ee3-e1b042909cf7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-ypalikila — APPROVED** [review]
Approved.

**Pull request merged**
