### PR TITLE
[Doc Improvement][Updating the notes, tips and important][2894679]

### PR DESCRIPTION
**Pull request by v-spharish**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f87f99ebfd8746abef4dc4b0db67f1249d1652/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8419018e-e390-4833-9672-514b5346d3a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f87f99ebfd8746abef4dc4b0db67f1249d1652/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/796cefba-bede-4f32-953c-258cb91c2bc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f87f99ebfd8746abef4dc4b0db67f1249d1652/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6f2914c-895b-44a3-99ac-66a994a6d39b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f87f99ebfd8746abef4dc4b0db67f1249d1652/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/572dae5c-5f42-49f9-8763-6e790d60aaad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/universal-actions-for-search-based-message-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f87f99ebfd8746abef4dc4b0db67f1249d1652/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Funiversal-actions-for-search-based-message-extensions.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f332efb-ff3c-4dbc-aacd-ecbf52cae457) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d4f87f99ebfd8746abef4dc4b0db67f1249d1652/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9985bd69-0c81-4eee-a009-7520a997054c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030943b006837eb35afbcfdd941b9b1c191a266c/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26f798fe-ce85-4fb4-97f0-286ca8f43da1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030943b006837eb35afbcfdd941b9b1c191a266c/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fad22ab-f399-457c-9a55-ecfa4c1a529b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030943b006837eb35afbcfdd941b9b1c191a266c/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f088d18-cad1-4f67-a782-8d7d2bd8981e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030943b006837eb35afbcfdd941b9b1c191a266c/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/227335e6-dadc-4570-81b5-f19bc9fb4271) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/universal-actions-for-search-based-message-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030943b006837eb35afbcfdd941b9b1c191a266c/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Funiversal-actions-for-search-based-message-extensions.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/115740e9-6f8d-4a69-8081-b6b8d33c8788) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/030943b006837eb35afbcfdd941b9b1c191a266c/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e022943-e4dd-4a9d-a52b-e3f6a417bac7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/03eeb398204f47f8453261ec1cf3924bbf01308a/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53e37fac-335e-4df7-b125-4dfab5574b95) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/03eeb398204f47f8453261ec1cf3924bbf01308a/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36c25aad-d8c4-4deb-a5e3-aa2537db6325) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/03eeb398204f47f8453261ec1cf3924bbf01308a/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 92 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/daf9a9c9-6d1c-496f-91a7-02a166ab1c7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/03eeb398204f47f8453261ec1cf3924bbf01308a/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42af3e25-840a-4d52-998f-482545676a8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/universal-actions-for-search-based-message-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/03eeb398204f47f8453261ec1cf3924bbf01308a/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Funiversal-actions-for-search-based-message-extensions.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8eddddb-64e0-47d7-a777-b20cd25e795a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/03eeb398204f47f8453261ec1cf3924bbf01308a/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca532e33-7486-4102-9fab-828fbd20e763) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc8a338235813aba587cb78231a22b72d8ccc7c8/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15aa201d-6e8f-4e05-829a-22a48c9c8df5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc8a338235813aba587cb78231a22b72d8ccc7c8/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3102f49c-ef87-4c6f-8bdf-0a9d379169fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc8a338235813aba587cb78231a22b72d8ccc7c8/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db53f296-83b9-4bfe-8fb2-7580fe656416) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc8a338235813aba587cb78231a22b72d8ccc7c8/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50596b9d-dc44-415a-bf53-cda15ee22520) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/universal-actions-for-search-based-message-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc8a338235813aba587cb78231a22b72d8ccc7c8/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Funiversal-actions-for-search-based-message-extensions.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bfc6856-d8f6-491f-b3a1-7c016fff65c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc8a338235813aba587cb78231a22b72d8ccc7c8/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4018d411-e23d-46c4-a352-46d7bf43d119) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c7940a697986b6cd949cd2fa0599360a379eac0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e9065dd-90e0-45ce-aa53-c5a4adf34fd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c7940a697986b6cd949cd2fa0599360a379eac0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df62b094-e71e-4152-a599-aed5314239ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c7940a697986b6cd949cd2fa0599360a379eac0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4408443-9db8-4eec-b50d-bd44e29ee58b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c7940a697986b6cd949cd2fa0599360a379eac0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f630e633-e41b-406e-98f9-c77b30cfe4c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/universal-actions-for-search-based-message-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c7940a697986b6cd949cd2fa0599360a379eac0/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Funiversal-actions-for-search-based-message-extensions.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12530113-b38b-49ae-9b91-50cb234c39e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6c7940a697986b6cd949cd2fa0599360a379eac0/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3d1a671-92f0-4d6c-8f99-5bc5ed121eea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/daf3bd5ed3271916a4c1126f4211c54551aec23b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fdbdb40d-de08-4c12-875a-cd63890658ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/daf3bd5ed3271916a4c1126f4211c54551aec23b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c63ff88-ccd3-4349-8583-bd29bd92b730) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/daf3bd5ed3271916a4c1126f4211c54551aec23b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0ee54f6-171a-465f-8f4c-5947fd83b831) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/daf3bd5ed3271916a4c1126f4211c54551aec23b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a78a2a32-df2f-46be-93fe-b7a410c02186) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/universal-actions-for-search-based-message-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/daf3bd5ed3271916a4c1126f4211c54551aec23b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Funiversal-actions-for-search-based-message-extensions.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f24448b-c74b-45f6-acf6-1fe7d120822f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/daf3bd5ed3271916a4c1126f4211c54551aec23b/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 93 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/336503b9-047f-441c-a491-b9c9ef05ffdd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7602bb6a1246e1d59c398554bfe89ab3fed9afcf/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 83 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77798b7b-daeb-4625-884d-38adca27956a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7602bb6a1246e1d59c398554bfe89ab3fed9afcf/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 87 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/69f5ad9d-4279-4795-98d1-feb99bbac732) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7602bb6a1246e1d59c398554bfe89ab3fed9afcf/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 85 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e216d43d-5a31-49e8-83f4-8d7beeb58429) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7602bb6a1246e1d59c398554bfe89ab3fed9afcf/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb1ae8d5-c8e3-4999-b446-7d6eaadb4452) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/universal-actions-for-search-based-message-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7602bb6a1246e1d59c398554bfe89ab3fed9afcf/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Funiversal-actions-for-search-based-message-extensions.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d78d2f9f-7ac9-4dfe-bca8-248e1a04a79a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7602bb6a1246e1d59c398554bfe89ab3fed9afcf/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 83 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2443fe4f-311f-4529-8a5c-f4cc6dd3abe0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f5c74b90dd5b7963f4023c7b26b9519837c09f4/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 83 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13653adb-4476-4dfd-a465-7f2e8e8560d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f5c74b90dd5b7963f4023c7b26b9519837c09f4/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 87 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14477277-6636-4d53-ba9b-3c0183ecfdbd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f5c74b90dd5b7963f4023c7b26b9519837c09f4/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Flink-unfurling.md) | 83 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ccf9bae-a454-4c31-8465-55ce47bd2836) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/define-search-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f5c74b90dd5b7963f4023c7b26b9519837c09f4/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Fdefine-search-command.md) | 88 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f3a7599-3ee2-40ba-8cad-0fb4d7833cf7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/search-commands/universal-actions-for-search-based-message-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f5c74b90dd5b7963f4023c7b26b9519837c09f4/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fsearch-commands%2Funiversal-actions-for-search-based-message-extensions.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6aa4c207-b916-42ae-a8de-2a25d0af009b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f5c74b90dd5b7963f4023c7b26b9519837c09f4/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 84 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65a4c57a-876d-44bf-8c7b-04bf08772ac0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by surbhigupta12** [comment]
Closing this

**Pull request closed without merging**
