### PR TITLE
Update landing page (Teams Dev Hub)

### PR DESCRIPTION
**Pull request by lindalu-MSFT**

### CODE REVIEW

**Comment by o365devx** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/assets/images/landing-page/MSTeams-Dev-build-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-build-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-client-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-client-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-getstarted-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-getstarted-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-intro-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-intro-400x140.svg) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201809141656107150-242%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BwyCdu888rLoCDgGghV%2F2w6J6X3VXbovxJ%2Bdue8IRGA%3D&st=2018-09-14T16%3A52%3A21Z&se=2018-10-15T16%3A57%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/index.md](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/index.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Findex.md)
[msteams-platform/assets/images/landing-page/MSTeams-Dev-build-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-build-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-client-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-client-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-getstarted-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-getstarted-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-intro-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-intro-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/includes/landing-page.html](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/includes/landing-page.html) | :white_check_mark:Succeeded | |

<a name="msteams-platform%2Findex.md"></a>
### [msteams-platform/index.md](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/index.md)
 - **Line 0**: **[Warning]** Invalid file link:(~/assets/images/landing-page/MSTeams-Dev-getstarted400x140.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/resources/design/overview).
 - **Line 0**: **[Warning]** Invalid file link:(~/assets/images/landing-page/MSTeams-Dev-client.svg).
 - **Line 0**: **[Warning]** Invalid file link:(~/javascript/api/overview/msteams-client).
 - **Line 0**: **[Warning]** Invalid file link:(~/concepts/apps/apps-overview).
 - **Line 0**: **[Warning]** Invalid file link:(~/overview).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201809141728114203-242%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LD1WBbLrJ%2Be3LG%2FbAXtis1ukYYG%2BT%2B9E9jbPxfC%2FoHk%3D&st=2018-09-14T17%3A24%3A29Z&se=2018-10-15T17%3A29%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/index.md](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/index.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Findex.md)
[msteams-platform/assets/images/landing-page/MSTeams-Dev-build-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-build-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-client-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-client-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-getstarted-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-getstarted-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-intro-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-intro-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/includes/landing-page.html](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/includes/landing-page.html) | :white_check_mark:Succeeded | |

<a name="msteams-platform%2Findex.md"></a>
### [msteams-platform/index.md](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/index.md)
 - **Line 0**: **[Warning]** Invalid file link:(~/resources/design/overview).
 - **Line 0**: **[Warning]** Invalid file link:(~/javascript/api/overview/msteams-client).
 - **Line 0**: **[Warning]** Invalid file link:(~/concepts/apps/apps-overview).
 - **Line 0**: **[Warning]** Invalid file link:(~/overview).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201809141735268678-242%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=WWfxx9XSZk8emxbzF7Ylt6A3k7cFLjtbcp9uSe63Rgk%3D&st=2018-09-14T17%3A31%3A44Z&se=2018-10-15T17%3A36%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/index.md](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/index.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Findex.md)
[msteams-platform/assets/images/landing-page/MSTeams-Dev-build-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-build-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-client-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-client-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-getstarted-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-getstarted-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-intro-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-intro-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/includes/landing-page.html](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/includes/landing-page.html) | :white_check_mark:Succeeded | |

<a name="msteams-platform%2Findex.md"></a>
### [msteams-platform/index.md](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/index.md)
 - **Line 0**: **[Warning]** Invalid file link:(~/resources/design/overview).
 - **Line 0**: **[Warning]** Invalid file link:(~/concepts/apps/apps-overview).
 - **Line 0**: **[Warning]** Invalid file link:(~/overview).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C14%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201809141741582353-242%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5nwOQY2PCxLMksts7Fsf2SQS0HRDkdcMhFiFUbjVprs%3D&st=2018-09-14T17%3A38%3A15Z&se=2018-10-15T17%3A43%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/index.md](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/index.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Findex.md)
[msteams-platform/assets/images/landing-page/MSTeams-Dev-build-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-build-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-client-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-client-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-getstarted-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-getstarted-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/assets/images/landing-page/MSTeams-Dev-intro-400x140.svg](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/assets/images/landing-page/MSTeams-Dev-intro-400x140.svg) | :white_check_mark:Succeeded | |
[msteams-platform/includes/landing-page.html](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/includes/landing-page.html) | :white_check_mark:Succeeded | |

<a name="msteams-platform%2Findex.md"></a>
### [msteams-platform/index.md](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/index.md)
 - **Line 0**: **[Warning]** Invalid file link:(~/resources/design/overview).
 - **Line 0**: **[Warning]** Invalid file link:(~/concepts/apps/apps-overview).
 - **Line 0**: **[Warning]** Invalid file link:(~/overview).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C19%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201809192053128087-242%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=80spjQurmUs7virjJN1igEFVGun8CYHGTjIuOWix7hQ%3D&st=2018-09-19T20%3A49%3A33Z&se=2018-10-20T20%3A54%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
Thanks, does @NormSohl publish changes to live?

**Comment by NormSohl** [comment]
Yes, usually.  We try to keep it down to one or two times a day - and I was out yesterday.  Will push this morning.

**Pull request merged**
