### PR TITLE
[Doc Improvement][Update plugin sample with npm][3629045]

### PR DESCRIPTION
**Pull request by v-ypalikila**
updated

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/782aeb5d7c87438a479fcb3540350f7b9a14e972/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 88 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9927b18f-d9ee-4a97-bc66-44a4bce97397) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f5cb958012ab1464ca36fdeaa732acbd0d4f9f9a/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 88 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29d9a462-6007-4689-bf61-a8684c97231f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb275ab6b127699688bc52c95ede19fe5a67e678/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 88 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc82da80-0f95-41c9-8aa9-617f405a0407) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/30f534af4c63898ab76fdb3234907228fd0dbdf6/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 88 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a94a3c97-be83-4c02-8116-8b8b0d404f66) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/96fb646fd678821e98769e548f4778ffa2a7eb32/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 88 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b8074b2-ad2c-4266-ae4d-5dd8beed47f7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b3b3750bfa901f881105aa6f7ed2bb9d562d711/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 88 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1c6927d-eb07-464d-9926-23299feff9f2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by girliemac — DISMISSED** [review]
👍  LGTM - If you have a chance, please edit the [step-by-step section](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-messagingextension-searchcommand-plugin) separately too. Thank you!

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fa712004950551100e06345f2cf96293c685238/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 88 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16a90369-b6b5-4933-a82f-e422220aef04) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1b3741480b56b55653e2eee69b0aacef969db133/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 88 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a212cce8-0094-4788-b83a-c634e4dd153b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1b3741480b56b55653e2eee69b0aacef969db133/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 81 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63227ab6-048e-4f07-a00c-1f4f3985eb85) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-ypalikila** [comment]
Hi @girliemac , I've updated the SBS guide with images and instructions with npm search as an example.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a962b32f7261f455a5b69b954f647b7d037ecc4/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 88 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aaa94df4-90f1-4beb-aeb1-a56bff1285ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5a962b32f7261f455a5b69b954f647b7d037ecc4/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 81 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/825f8f5d-b2e8-4557-b0a1-118ec361c187) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac7d84376257053248cf24873751b74d28209ab4/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 88 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8bbea1e-ffeb-473f-b6ed-27939e780562) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ac7d84376257053248cf24873751b74d28209ab4/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 81 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1bd938ce-f72b-4c2d-8231-35bf20a48a9e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b581e3860aa40ffa79c9ae0599a4e9786b582190/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 88 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4baf8b4f-1e7b-4542-b704-b4d7a0cb57cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b581e3860aa40ffa79c9ae0599a4e9786b582190/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 81 | 92 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36483c65-515f-47cc-a675-a4c725d2daf3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
