### PR TITLE
[Doc Improvement][Call Transcript API to GA][3309947]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a60e3e233974f2b21177366db8895a72deaa28fa/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7849d7c1-6bc3-4370-9048-9e1fd2775780) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a60e3e233974f2b21177366db8895a72deaa28fa/msteams-platform%2Fwhats-new.md) | 94 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4223c2eb-c3a8-408d-ab09-150a02c6c65e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6b993d32521ba5dbe6a16420de5d8b3581c427eb/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b529affb-afc1-4f58-9baa-e62ef442fec8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b993d32521ba5dbe6a16420de5d8b3581c427eb/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e4aa050-071e-4979-a2ff-184bdea52dac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6b993d32521ba5dbe6a16420de5d8b3581c427eb/msteams-platform%2Fwhats-new.md) | 94 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd447592-6b9f-488f-b47d-1b398a712c3f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/de69de2e401d76ba482eac3dd1b99c5522736db3/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9c45a2f-9287-43d5-b85c-4fd5d97b227b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de69de2e401d76ba482eac3dd1b99c5522736db3/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf163551-7479-4284-8816-f22f9b29f0e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/de69de2e401d76ba482eac3dd1b99c5522736db3/msteams-platform%2Fwhats-new.md) | 94 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a7dd4a1-f2f8-4253-a5a1-5edf22c698ed) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8473d7eb67916aa45b5543ffcbc0fce5c327c980/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc7cace5-3889-4d97-a027-a3ea08aefe36) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8473d7eb67916aa45b5543ffcbc0fce5c327c980/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ed64c47-6667-4b17-abe4-04ac1c72a0d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8473d7eb67916aa45b5543ffcbc0fce5c327c980/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4931a212-52b8-42f3-9494-b9256122332f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8473d7eb67916aa45b5543ffcbc0fce5c327c980/msteams-platform%2Fwhats-new.md) | 94 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f36380b-0662-4b78-9791-ae03fcad0227) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/36b26471de8bb020d239aa0fc8ee3cacbd97e94c/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b71a439-5918-4fe9-83f1-b66f3cb8d779) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/36b26471de8bb020d239aa0fc8ee3cacbd97e94c/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ec704de-b552-4b3e-ba08-3d5f1e889784) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/36b26471de8bb020d239aa0fc8ee3cacbd97e94c/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d8b1c3f-34af-40b3-ad7d-2c1d94a15b66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/36b26471de8bb020d239aa0fc8ee3cacbd97e94c/msteams-platform%2Fwhats-new.md) | 94 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8461155c-d67a-4444-b061-813dd8d24aa4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8f6bedb3a4b16ae270883be4f3726bf0c03a63e8/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb368ab4-4247-4235-af6a-0e50d7b0a46d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f6bedb3a4b16ae270883be4f3726bf0c03a63e8/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1cff2ef6-2d25-4db8-89e7-0f492bb0af7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8f6bedb3a4b16ae270883be4f3726bf0c03a63e8/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54601284-1f52-42d3-b9af-e1d174cc0468) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f6bedb3a4b16ae270883be4f3726bf0c03a63e8/msteams-platform%2Fwhats-new.md) | 94 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06036fee-bffa-4ea3-a573-221818073a45) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2b4ba8bba28aed903275ce8fdf9fd52177a565a5/msteams-platform%2FTOC.yml) | 99 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0ed89a9-a633-4f44-8aa1-2350fe9ec460) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/overview-transcripts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2b4ba8bba28aed903275ce8fdf9fd52177a565a5/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Foverview-transcripts.md) | 100 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c96b52bd-4fb8-4727-9630-84b83c01ab7f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2b4ba8bba28aed903275ce8fdf9fd52177a565a5/msteams-platform%2Fmstdd-landing.yml) | 89 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/595ed073-b15b-4cb1-a2f6-2652d7af90f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2b4ba8bba28aed903275ce8fdf9fd52177a565a5/msteams-platform%2Fwhats-new.md) | 94 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fea10d92-fabb-4a31-8832-fd3c9a2ad6c1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
