### PR TITLE
[Doc Improvement][Mask sensitive information in SBS][3532161]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/aaeff3e93011042f20bd1c0e953cb1e5a776172d/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40b3c212-c80c-4ca4-8a7b-61e7801152fb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e2a0174b3f2e4381ef4de9922d31ccfa1ff127f/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/609eebc4-e605-49d7-9438-7e141417ffd8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/721070561a5e5058b73eb4bbef018db0e4dbf03b/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21ca438f-5a1e-414e-b4a7-0f424a0796be) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/257d8f0b3ccbb2ee4776c0d26472f850e3d699fc/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed161b89-5d13-4ff4-bec7-e3c4585b42b1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-api-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e6b4cf849168505660184b00800471fdb12d613/msteams-platform%2Fincludes%2Fget-started%2Fazure-api-permissions.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd089e32-4db0-4388-bced-8de53063f83b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5e6b4cf849168505660184b00800471fdb12d613/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8334dcd-aa52-4307-a700-5e666ec12e74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5e6b4cf849168505660184b00800471fdb12d613/msteams-platform%2Fsbs-gs-msgext.yml) | 85 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94f4680a-a4bd-4ef6-8be9-81397bc5384a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-api-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/77252c1cc1de3892d7b385a100b377dfdb2c522a/msteams-platform%2Fincludes%2Fget-started%2Fazure-api-permissions.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39eced7d-e98f-4bc7-902c-3441d0a174db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/77252c1cc1de3892d7b385a100b377dfdb2c522a/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b30c6fa0-dfd6-415c-bb66-35816ac7f1ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/77252c1cc1de3892d7b385a100b377dfdb2c522a/msteams-platform%2Fsbs-gs-msgext.yml) | 85 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21df7d92-1e43-464b-ab13-2c8b532a9673) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-api-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d74752645466b6ecdc0c3745b5d1a90d6bdca3a4/msteams-platform%2Fincludes%2Fget-started%2Fazure-api-permissions.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c7006f0-6df4-4c4a-8dbe-f1d07f1681af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d74752645466b6ecdc0c3745b5d1a90d6bdca3a4/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2b9cc6d-83d4-4956-b1cc-58c6de70bf4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d74752645466b6ecdc0c3745b5d1a90d6bdca3a4/msteams-platform%2Fsbs-gs-msgext.yml) | 85 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cd9b536-2eae-4fef-ab5b-1e3127e19392) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
