### PR TITLE
[Doc Improvement][Update get started javascript]

### PR DESCRIPTION
**Pull request by v-bdeepa**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-msg.md](https://github.com/MicrosoftDocs/msteams-docs/blob/67400eb8390af2309b9cd749315c5862f274c0a6/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-msg.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/af40d8ed-931b-494a-8e7c-16a78f01dc54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/67400eb8390af2309b9cd749315c5862f274c0a6/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb0280c0-3d2d-4d43-b929-a5c0648ba75c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0215d25034c1cb926c349c693aa6bc4aaeb58709/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/265168e1-5182-4ee5-be55-b88a28f5339e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0215d25034c1cb926c349c693aa6bc4aaeb58709/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d3926d8-e6af-4487-a65e-765bf03eadad) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/755a28c457afa2f30e4788eb259135cf4f18e542/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 87 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad954301-a315-4b2e-a5a8-09f4e112b415) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/755a28c457afa2f30e4788eb259135cf4f18e542/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/217fcf85-77c7-4137-8854-cb6b6c643d48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/755a28c457afa2f30e4788eb259135cf4f18e542/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/869b5f75-eb85-4b66-8be4-acf3acaa7993) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/62743922bd87e0edf7deddd3f4baa7e36802bd1d/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 87 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f72985b7-40c3-434f-8fb0-4e025da49efd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/62743922bd87e0edf7deddd3f4baa7e36802bd1d/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4de90d2-39a6-4122-a5b3-a8cee5fe7648) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62743922bd87e0edf7deddd3f4baa7e36802bd1d/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a0dc72f-9bd5-4b78-a7d5-4f25ad33dd06) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62743922bd87e0edf7deddd3f4baa7e36802bd1d/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/630f6058-55ed-4bcd-a3d1-7e1b84bef878) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/682b925235afb1b4b2dfb8b3ae79abcd153937bd/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions-tab.md) | 87 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14ac2d1c-a12e-4588-a8b2-a7489416ce1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/682b925235afb1b4b2dfb8b3ae79abcd153937bd/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 88 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f55b936-521d-468b-b451-665e6fb68a54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/682b925235afb1b4b2dfb8b3ae79abcd153937bd/msteams-platform%2Fsbs-gs-javascript.yml) | 91 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97bff05c-6967-4b26-ad76-79adade46f2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-msgext.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/682b925235afb1b4b2dfb8b3ae79abcd153937bd/msteams-platform%2Fsbs-gs-msgext.yml) | 91 | 45 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09206629-bda6-4819-8532-68b35002115b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
