### PR TITLE
[Doc Improvement][Tasks to dialogs for Tabs][3480216]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d7e777a13e56ba08d7070ac58240544ef959fa8/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df767f78-390b-4b14-a47d-5b7a6bdaeed1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d7e777a13e56ba08d7070ac58240544ef959fa8/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1882388-9b7c-4789-9a5c-1e6ba8e1edfc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d7e777a13e56ba08d7070ac58240544ef959fa8/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a80987f7-d551-4424-958e-65db108e07ea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/045f66c18e555f2f2ecc7f1c2e757b67467925bf/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bed2b35-5df7-4182-b89c-e99fdae34782) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/app-caching.md](https://github.com/MicrosoftDocs/msteams-docs/blob/045f66c18e555f2f2ecc7f1c2e757b67467925bf/msteams-platform%2Ftabs%2Fhow-to%2Fapp-caching.md) | 86 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aeb7793a-712b-4f97-b788-8039a25a7bcd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/045f66c18e555f2f2ecc7f1c2e757b67467925bf/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bf5b710-3f68-4775-a737-a81ad5fc8389) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/045f66c18e555f2f2ecc7f1c2e757b67467925bf/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ae3d38f-5ffe-4007-95ef-f6a19b43e675) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/045f66c18e555f2f2ecc7f1c2e757b67467925bf/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58bcfe0e-019c-4531-aaa5-0a464e3a1c98) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9056805cec28992a2120fc9fb12cb9b5c3737d5/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc9dcf93-3b8c-450c-9c03-c9d132fa282c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/app-caching.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9056805cec28992a2120fc9fb12cb9b5c3737d5/msteams-platform%2Ftabs%2Fhow-to%2Fapp-caching.md) | 86 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8382012-0d70-4d43-9a4a-215cef61ea7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9056805cec28992a2120fc9fb12cb9b5c3737d5/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0daed524-b57c-4247-aae5-294982361b61) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9056805cec28992a2120fc9fb12cb9b5c3737d5/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3f3d45b-be68-467e-ae15-5be1ce06c3b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a9056805cec28992a2120fc9fb12cb9b5c3737d5/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48e035aa-0b36-43ef-a2a8-9bb5dd942404) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4fccb33ae9326a0a71a17330f74790fb2cea806/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be92d245-6ff0-4523-9f87-ebf0c508615e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/app-caching.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4fccb33ae9326a0a71a17330f74790fb2cea806/msteams-platform%2Ftabs%2Fhow-to%2Fapp-caching.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/928a9c3b-f3d2-4044-8764-3f2d5546f40b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4fccb33ae9326a0a71a17330f74790fb2cea806/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ea28a50-40f1-4c70-bf01-0746e827acb4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4fccb33ae9326a0a71a17330f74790fb2cea806/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c668b389-023c-493b-ae87-85ae01807cdb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4fccb33ae9326a0a71a17330f74790fb2cea806/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a89c4d5-993f-49e4-831e-48c6a23dea9d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
