### PR TITLE
[Doc Update][Message-extension-5][2369904]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/951c3a56237176d73b3b1f8c1972d3352c15216d/msteams-platform%2Fconcepts%2Fauthentication%2Fauthentication.md) | 87 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/624e2e38-d827-4914-ba02-4bd21ca454c9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c7de0ecd9dafbb94c68b59dcb317e46adb4d260/msteams-platform%2Fconcepts%2Fauthentication%2Fauthentication.md) | 87 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97dfc8b3-1868-465c-828b-bdb0aa3ce4ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c7de0ecd9dafbb94c68b59dcb317e46adb4d260/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-aad-sso.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3bf06509-97d1-4ce9-b317-bf14aa11da87) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c7de0ecd9dafbb94c68b59dcb317e46adb4d260/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-tab-aad.md) | 81 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e390656a-ad08-4852-a174-d57d474e2568) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2bf2c40ba02e0fb5908848dbc14d1e1d2f043fe1/msteams-platform%2Fconcepts%2Fauthentication%2Fauthentication.md) | 87 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f73cfd51-2229-4f6b-8168-5dbd6217152b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2bf2c40ba02e0fb5908848dbc14d1e1d2f043fe1/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fadd-authentication.md) | 85 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85595ea4-a7dc-4a9f-9863-87297197e8a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/enable-SSO-auth-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2bf2c40ba02e0fb5908848dbc14d1e1d2f043fe1/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fenable-SSO-auth-me.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8986603-f78f-498c-8b38-b8c64f371359) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2bf2c40ba02e0fb5908848dbc14d1e1d2f043fe1/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-aad-sso.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd6c5f48-291f-4370-9b23-f1efd77f19bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2bf2c40ba02e0fb5908848dbc14d1e1d2f043fe1/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-tab-aad.md) | 81 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7ffab79-9f90-461c-a1de-887ab9892f95) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/debug/locally-with-an-ide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6f20b0e290702ac608e3f13909fa95ceee28f489/msteams-platform%2Fbots%2Fhow-to%2Fdebug%2Flocally-with-an-ide.md) | 81 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9fbb03c4-6ba5-4c8f-8fc6-4ae7daa31ae7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6f20b0e290702ac608e3f13909fa95ceee28f489/msteams-platform%2Fconcepts%2Fauthentication%2Fauthentication.md) | 87 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc839478-ce12-498f-a8a5-5f900176a43e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6f20b0e290702ac608e3f13909fa95ceee28f489/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2dc21f0-9f87-41aa-a33a-71bd3aea5d8b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6f20b0e290702ac608e3f13909fa95ceee28f489/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90428cb3-2f78-4233-bfc7-1b27a02734cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6f20b0e290702ac608e3f13909fa95ceee28f489/msteams-platform%2Fm365-apps%2Foverview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb9b0e75-040e-41f8-a8d1-dd6dd7253db2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6f20b0e290702ac608e3f13909fa95ceee28f489/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 94 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78d0aa8b-48f2-45ee-9783-fe3b4aa12641) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6f20b0e290702ac608e3f13909fa95ceee28f489/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fadd-authentication.md) | 85 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/edba7c25-e472-43d4-b3a0-3fefa3dd0bd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/enable-SSO-auth-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6f20b0e290702ac608e3f13909fa95ceee28f489/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fenable-SSO-auth-me.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2a75ce3-63c4-4b74-bec1-561ec13a9dec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6f20b0e290702ac608e3f13909fa95ceee28f489/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-aad-sso.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3739d398-f28d-4a20-8f9a-a1cc5fd9c505) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6f20b0e290702ac608e3f13909fa95ceee28f489/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-tab-aad.md) | 81 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a632e9b-9543-4200-85ae-6ac72985e05b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/debug/locally-with-an-ide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58787a508237adeb1b98a353778c94b520d8582e/msteams-platform%2Fbots%2Fhow-to%2Fdebug%2Flocally-with-an-ide.md) | 81 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72a13bbf-0484-4a92-8af9-440036da7ddc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58787a508237adeb1b98a353778c94b520d8582e/msteams-platform%2Fconcepts%2Fauthentication%2Fauthentication.md) | 87 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7462fa0e-a7c5-4cf2-ab9d-71f19d493b5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58787a508237adeb1b98a353778c94b520d8582e/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 89 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3cbcad88-3b30-4160-b743-5b054dc1b1c2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58787a508237adeb1b98a353778c94b520d8582e/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbc6aa73-12fa-4d20-9b20-f7a89c04fefd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58787a508237adeb1b98a353778c94b520d8582e/msteams-platform%2Fm365-apps%2Foverview.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd1dd1f1-89ac-4d48-96d6-ac24fe830c5a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58787a508237adeb1b98a353778c94b520d8582e/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 94 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc63d274-21a4-441d-adcd-b9fc1b802aeb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58787a508237adeb1b98a353778c94b520d8582e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fadd-authentication.md) | 85 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79fdcf04-bb35-4f0a-a7eb-a8e3030a0f3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/enable-SSO-auth-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58787a508237adeb1b98a353778c94b520d8582e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Fenable-SSO-auth-me.md) | 88 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b91ba441-8d44-4b4f-83e8-71f64869c950) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-aad-sso.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58787a508237adeb1b98a353778c94b520d8582e/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-aad-sso.md) | 94 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4301c2a1-5f8f-40f4-be6b-2f5c937325f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-tab-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58787a508237adeb1b98a353778c94b520d8582e/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Fauth-tab-aad.md) | 81 | 40 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/524d470c-70e2-4b5c-bb02-a7e2c75e1965) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by stkong-sdk — APPROVED** [review]

**Review by v-habibaumme — APPROVED** [review]
Approved

**Pull request merged**
