### PR TITLE
[Doc Improvement][Update tasks to dialogs for message extensions][3480217]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d86697acd1258b8e5254177878c98eebdb82b641/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4896491d-acb0-4007-9f5e-7ad6b1bf676e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d86697acd1258b8e5254177878c98eebdb82b641/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 85 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c544f58-a580-4457-90f5-49c4b43c3178) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/97cffaa71b19eac9b9078c41840dce4c83c2ec2e/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f68edc8f-c918-481d-b23e-650466578f88) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97cffaa71b19eac9b9078c41840dce4c83c2ec2e/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/431879a4-8a8f-48fa-bf7f-e3a17528b708) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97cffaa71b19eac9b9078c41840dce4c83c2ec2e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fcreate-task-module.md) | 94 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f3d56aa-6ff4-4dee-aad9-c47b96a734e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97cffaa71b19eac9b9078c41840dce4c83c2ec2e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09b58039-dfbc-46c3-850b-3e98c6803b7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97cffaa71b19eac9b9078c41840dce4c83c2ec2e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 87 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/240ce4b3-da6e-4bdb-bc1f-abcb657c31d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/97cffaa71b19eac9b9078c41840dce4c83c2ec2e/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 85 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3af1c120-0fd3-404d-9e29-bc5f4cf8c7e3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ae4bf143b802babe1fcc7ac12e10706b764c5a39/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a76d22b-8131-4dc3-b66c-b44491fadad7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae4bf143b802babe1fcc7ac12e10706b764c5a39/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 90 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a89964a-8d26-4a20-b509-e06f741051f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae4bf143b802babe1fcc7ac12e10706b764c5a39/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fcreate-task-module.md) | 94 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3bf54f6f-f46a-4538-b017-0fb22eee86fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae4bf143b802babe1fcc7ac12e10706b764c5a39/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4a8cca8-614c-478f-8bc3-3d8b00506806) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae4bf143b802babe1fcc7ac12e10706b764c5a39/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 87 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48c9861c-92f8-4c4a-b943-17f9a3718874) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ae4bf143b802babe1fcc7ac12e10706b764c5a39/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 85 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fb5ef24-b8b1-449a-9a3d-0445d43d70c4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a2e505306d02d669a29b2d5dab108c49777a9e1e/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5caaa2be-8fbb-4629-8f2c-6db5f57f3095) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2e505306d02d669a29b2d5dab108c49777a9e1e/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb46b753-8932-46a6-a3db-7277c71cabe8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2e505306d02d669a29b2d5dab108c49777a9e1e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fcreate-task-module.md) | 94 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a37fbb9-94ec-48f1-bee2-e9736555b095) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2e505306d02d669a29b2d5dab108c49777a9e1e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6cc56d8f-ccaf-40b8-8c06-c05da6737ed5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2e505306d02d669a29b2d5dab108c49777a9e1e/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 87 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f26cc85-0833-41b5-951c-f51acc407062) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a2e505306d02d669a29b2d5dab108c49777a9e1e/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 85 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbfbb79e-2aeb-4bda-86de-67bc49133a00) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/308db2d92d958ec56e0d1a53a471e170cbddaf3f/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a602b6dc-170a-4bf2-bb30-00213be6dd69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/308db2d92d958ec56e0d1a53a471e170cbddaf3f/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7fa2dc89-cbf4-490e-ac7a-a434cd45c17a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/308db2d92d958ec56e0d1a53a471e170cbddaf3f/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fcreate-task-module.md) | 94 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6661a8f-6261-458d-8fbb-04bf5d9487b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/308db2d92d958ec56e0d1a53a471e170cbddaf3f/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4ad58edb-b5e9-40ae-b136-01ba0b4089ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/308db2d92d958ec56e0d1a53a471e170cbddaf3f/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 87 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b765d383-9b30-4f50-8a16-05963f18f730) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/308db2d92d958ec56e0d1a53a471e170cbddaf3f/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 85 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f4acf3c-c31f-4524-836c-5f378f431e23) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/dc2f2d445ab7aa2aac600874c9bb4128d027b16b/msteams-platform%2FTOC.yml) | 99 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48ac2826-4fbc-4dbe-a0fe-039758a452d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/high-quality-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc2f2d445ab7aa2aac600874c9bb4128d027b16b/msteams-platform%2Fmessaging-extensions%2Fhigh-quality-message-extension.md) | 91 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4722b9fa-1276-4e3c-97ef-c5ba8f771d03) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/create-task-module.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc2f2d445ab7aa2aac600874c9bb4128d027b16b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fcreate-task-module.md) | 94 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce8abce4-a90e-4a83-ad42-6af5d71c694d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/define-action-command.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc2f2d445ab7aa2aac600874c9bb4128d027b16b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Fdefine-action-command.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/338a20c5-325b-4a3d-a2d3-3288a21d68a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/how-to/action-commands/respond-to-task-module-submit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc2f2d445ab7aa2aac600874c9bb4128d027b16b/msteams-platform%2Fmessaging-extensions%2Fhow-to%2Faction-commands%2Frespond-to-task-module-submit.md) | 87 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80030137-0ebf-4867-921f-839b67c08d6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/what-are-messaging-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dc2f2d445ab7aa2aac600874c9bb4128d027b16b/msteams-platform%2Fmessaging-extensions%2Fwhat-are-messaging-extensions.md) | 85 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9036cb93-4a4c-4bff-9b9d-bad4a61f2c51) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
