### PR TITLE
[Doc Improvement][Update Teams Toolkit overview for Visual Studio]

### PR DESCRIPTION
**Pull request by zyxiaoyuer**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/teams-toolkit-overview-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/439953de4d7e67e796be50052a9bf0d714a666b9/msteams-platform%2Ftoolkit%2Fteams-toolkit-overview-visual-studio.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80579390-dfc7-4797-9010-20b79df4002b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0ce871aa838be345c8f76d8719e30a03abba62de/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85ec5e5e-ecda-4201-aca6-a9151e5b00d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-overview-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ce871aa838be345c8f76d8719e30a03abba62de/msteams-platform%2Ftoolkit%2Fteams-toolkit-overview-visual-studio.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/edfda8f9-cf52-41b7-a6fd-d45a888c304a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2ab96e46a4e1cc46e4c510c0cc5d6f474da93655/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e0c1898-4749-40cf-8a7e-fab9773883d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ab96e46a4e1cc46e4c510c0cc5d6f474da93655/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a92789a2-6e87-4697-9ec2-ed875c4df689) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-overview-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2ab96e46a4e1cc46e4c510c0cc5d6f474da93655/msteams-platform%2Ftoolkit%2Fteams-toolkit-overview-visual-studio.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96d007f2-85be-4281-8b46-f2058fa36fd9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/92382bc9b1dccd6f7ebeeab1f6ef3804301f748b/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9508c033-f211-4698-8da6-8ee133c03470) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92382bc9b1dccd6f7ebeeab1f6ef3804301f748b/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19918c81-50af-4ea4-8a04-26173f19de81) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-overview-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92382bc9b1dccd6f7ebeeab1f6ef3804301f748b/msteams-platform%2Ftoolkit%2Fteams-toolkit-overview-visual-studio.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13f36b6b-8a7f-4ffd-ae00-8fdcf3ab6d1e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e822159f4764e83531bd641db162f8b01659c48c/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8e66067-253d-419b-ab58-64cc81bfe275) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e822159f4764e83531bd641db162f8b01659c48c/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25f06c8b-1cd3-43b7-8c9e-959d9f3c983e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-overview-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e822159f4764e83531bd641db162f8b01659c48c/msteams-platform%2Ftoolkit%2Fteams-toolkit-overview-visual-studio.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ac54a64-b844-4674-af8b-d27947dd8384) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1da1330fb1878f27480c51645050ea2bd69b67a1/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6dcdb61-3412-490a-be1c-f81ecfa11cd1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1da1330fb1878f27480c51645050ea2bd69b67a1/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11e78c1b-609a-4a1a-8e6c-0b852772204b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-overview-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1da1330fb1878f27480c51645050ea2bd69b67a1/msteams-platform%2Ftoolkit%2Fteams-toolkit-overview-visual-studio.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a46e8a0e-5173-49b7-9e0b-dfa24ad95864) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]
Approved.

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
