### PR TITLE
[Doc-Enhancement][test-auth-structure]

### PR DESCRIPTION
**Pull request by v-shalinirobinson**
test PR to experiment with auth structure

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/authentication/sso-register-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4c4e65a0ddfc7ffcd558763f731cb5a32b29b5ca/msteams-platform%2Fconcepts%2Fauthentication%2Fsso-register-test.md) | 88 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b756c5b4-91ab-4151-b52e-517e8ca797aa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/authentication/sso-code-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc8860b119d92997a0f9097e0224598746b84ce/msteams-platform%2Fconcepts%2Fauthentication%2Fsso-code-test.md) | 87 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94152edc-e5f4-4fd3-ae42-eaed3a2f03c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/sso-register-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6dc8860b119d92997a0f9097e0224598746b84ce/msteams-platform%2Fconcepts%2Fauthentication%2Fsso-register-test.md) | 77 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de75f3c8-6902-4a26-b280-abe5597df0bf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/authentication/sso-code-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/499beb4e73caecace66337dd6c5b776aeb72b65d/msteams-platform%2Fconcepts%2Fauthentication%2Fsso-code-test.md) | 87 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a07b8642-c4d2-4ccb-949c-33ed1e93d9ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/sso-register-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/499beb4e73caecace66337dd6c5b776aeb72b65d/msteams-platform%2Fconcepts%2Fauthentication%2Fsso-register-test.md) | 77 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74ed9ad6-bdec-4da7-9f77-19a3f4aeba75) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8d349ae60eadba1eacd7f476e0d32df210bf299f/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1fcdcbb-aa48-42b8-8100-1e9234db6dd7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/sso-code-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d349ae60eadba1eacd7f476e0d32df210bf299f/msteams-platform%2Fconcepts%2Fauthentication%2Fsso-code-test.md) | 87 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6a410a8-dc9f-4c6f-b88e-129a17da2ca5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/sso-register-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8d349ae60eadba1eacd7f476e0d32df210bf299f/msteams-platform%2Fconcepts%2Fauthentication%2Fsso-register-test.md) | 77 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1b6ef4f-c525-4c2e-a3b5-60a2adcf2f94) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bc6db06af0e53ae96c9591f85b8caf929804f931/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9911695-f43e-4dde-9945-0fd8e975f044) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/sso-code-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc6db06af0e53ae96c9591f85b8caf929804f931/msteams-platform%2Fconcepts%2Fauthentication%2Fsso-code-test.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be8ffd16-b1ed-4fc1-9c6c-1f6ae8c38d73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/authentication/sso-register-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bc6db06af0e53ae96c9591f85b8caf929804f931/msteams-platform%2Fconcepts%2Fauthentication%2Fsso-register-test.md) | 80 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50108553-b942-4faa-8ab0-ff72556bf9b2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-shalinirobinson** [comment]
Tested structure.

**Pull request closed without merging**
