### PR TITLE
[Doc Improvement][Manifest-version-localization][2473243]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d8b5e7bf2b26672e8bc6c35ad782606a12f4b8b/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/390529bd-a7be-49c6-93b9-5c062b72bf52) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Comment by svrooij** [comment]
Does this pr also fixes the incorrect version in the localization samples?

**Comment by Wajeed-msft** [comment]
> Does this pr also fixes the incorrect version in the localization samples?

@svrooij - We will raise separate PR for sample code in Microsoft Teams Samples repo. 

@AbhijeetThakur-msft could you please share the link of PR for samples in [Teams Samples Repo](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-localization) to [GitHub issue](https://github.com/MicrosoftDocs/msteams-docs/issues/6122).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2ed0539a27b7c219ace3d42ceea118ff5d937f3/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2404cbaf-1f09-4582-a1f3-0aa83c545caa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Comment by AbhijeetThakur-msft** [comment]
@Wajeed-msft 
PR link for localized manifest: https://github.com/OfficeDev/Microsoft-Teams-Samples/pull/373

**Pull request merged**
