### PR TITLE
[Doc Improvement][AC-based Loop components fixes][3951083]

### PR DESCRIPTION
**Pull request by v-kushals**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d1d2ad0d07f035fe323413e88448fb5430a743e9/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/798724a1-f15b-4f61-97cf-5e8368f3ee70) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e875aa856fa56a03d9cdbc06292a08e2d21dbdf6/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91e224a9-f909-45bb-808b-695790cd6f64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e875aa856fa56a03d9cdbc06292a08e2d21dbdf6/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95274851-ecdc-4aac-9ae6-7270077e8ee7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c6d79019b8deb5ccaa10ecc930c28f49d09f24e5/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3850f953-93a0-4e6b-86ef-693f29e6ed9d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c6d79019b8deb5ccaa10ecc930c28f49d09f24e5/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bcdcd33-53ab-4cd6-b9d9-62cd2c0fd638) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/651e8d65534cfa5242bd98a66bd690a286fcc552/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25a4084b-96c7-4de7-aa2f-542d5d3deaee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/651e8d65534cfa5242bd98a66bd690a286fcc552/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80845239-fe24-4110-b679-bde2542b5ada) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/877ab663e9264ddaaaee2e40ecda4016cbab3e34/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f066acf5-c52b-4629-b27a-6b3f21bef71a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/877ab663e9264ddaaaee2e40ecda4016cbab3e34/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31e2404a-ccda-42ea-a724-2684eb9dda98) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7507205eeb7c793950b8fbe954fbbdb90bb24d/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f99a459e-4c81-4d28-be3b-d31b989521a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/design-loop-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5a7507205eeb7c793950b8fbe954fbbdb90bb24d/msteams-platform%2Fm365-apps%2Fdesign-loop-components.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b02af34c-cc65-4500-a5eb-5cbf935c3d95) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
