### PR TITLE
[Doc Improvement][Update 400 words articles][4050364]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/645f1ebba30062fb53cbf6cf81e0e273a5ecb169/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 100 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/210a75c8-88af-44b3-b46c-8be1614e2b76) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d9f4806b6e49c6edc83606cb0cfb7ed59faf02d/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 100 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acff0bfe-f546-4321-9cda-ad996dfe756d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/28173ceaf942e34a60f209bd450b8245d8e6a035/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eaaafc44-6a5c-4d45-a737-022d7cae877c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28173ceaf942e34a60f209bd450b8245d8e6a035/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 100 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/61f1fd6a-75e2-43bd-b3b2-9eeee0abbc17) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fa8020c0a687f7aa4e8ffe49ac94296a4bc9a522/msteams-platform%2FTOC.yml) | 92 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48c77ccd-bb04-4566-9326-6f21306b6fbb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fa8020c0a687f7aa4e8ffe49ac94296a4bc9a522/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 100 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be93bfaf-2821-4a98-803c-20ab5bd7bca4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c41117c21ee1ca9b474c2c83729497d54d3946be/msteams-platform%2FTOC.yml) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f719e584-4174-45c6-85ee-47381fe273f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c41117c21ee1ca9b474c2c83729497d54d3946be/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 100 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a12a2c29-252b-400c-b641-537665114f71) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/95b1ccdc0ecf3f4bc3a1c1242de99247bb078fd2/msteams-platform%2FTOC.yml) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/983b9e87-a2ac-4da1-9ef1-b5fd76ce5e6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95b1ccdc0ecf3f4bc3a1c1242de99247bb078fd2/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3b1897c-216d-431e-8d4a-70c6c102e00a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/771012e2a23248df3cac69e9e505a1dfcc463e26/msteams-platform%2FTOC.yml) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/573f026f-6cf1-4cb6-80eb-1725a55d332c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-resource.md](https://github.com/MicrosoftDocs/msteams-docs/blob/771012e2a23248df3cac69e9e505a1dfcc463e26/msteams-platform%2Ftoolkit%2Fadd-resource.md) | 97 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79995fd4-1eac-4676-aa59-f3b12b8b8ff1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
