### PR TITLE
[Doc Updates][Message-extensions][2369899]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/535b9b77379f9f5ad685bb735d21b0f4f9c1ff29/msteams-platform%2Fget-started%2Fget-started-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/290d4f35-22ea-4ccb-a184-b05a5045110c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/535b9b77379f9f5ad685bb735d21b0f4f9c1ff29/msteams-platform%2Foverview-explore.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c18d7e99-650d-4824-b858-ba004045196d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/535b9b77379f9f5ad685bb735d21b0f4f9c1ff29/msteams-platform%2Foverview.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/efcf75ca-e590-4a8d-b571-9936fd3df1f2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2b1b7da2eb656a86f3c211b268ba7c0ca2cf0bd6/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ceee382-4daa-4c01-b3fa-5d7fed39f9f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2b1b7da2eb656a86f3c211b268ba7c0ca2cf0bd6/msteams-platform%2Fconcepts%2Fdesign%2Funderstand-use-cases.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e209606-6fce-471f-a01c-a35d3042f824) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2b1b7da2eb656a86f3c211b268ba7c0ca2cf0bd6/msteams-platform%2Fget-started%2Fget-started-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18fd8698-aab4-4c71-8031-450ef829c6f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2b1b7da2eb656a86f3c211b268ba7c0ca2cf0bd6/msteams-platform%2Foverview-explore.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ea9880d-f7e6-41ac-96bc-30b73d371660) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2b1b7da2eb656a86f3c211b268ba7c0ca2cf0bd6/msteams-platform%2Foverview.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a74d6f8-ea60-4738-8659-6dcca5b58896) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/068975fd995de36aac2cb18b42ce12ce3817451b/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fe92919-262d-4567-bce4-8d1d22d221b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/068975fd995de36aac2cb18b42ce12ce3817451b/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fd6f0b9-d631-4297-988a-9eef06ebe8f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/068975fd995de36aac2cb18b42ce12ce3817451b/msteams-platform%2Fconcepts%2Fdesign%2Funderstand-use-cases.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03133765-832a-48f2-9fe0-066cd152114a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/068975fd995de36aac2cb18b42ce12ce3817451b/msteams-platform%2Fget-started%2Fget-started-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a753a996-7057-4598-84d8-a88e2b4fcc0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/068975fd995de36aac2cb18b42ce12ce3817451b/msteams-platform%2Foverview-explore.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4e3eaf5-d48d-4364-b0ac-39317b355518) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/068975fd995de36aac2cb18b42ce12ce3817451b/msteams-platform%2Foverview.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c935a58-c8e2-4dbc-8906-7407fd759340) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba4a28dee2efc0c5ef503d61177479cbe1ea849b/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c343554-0581-42cb-97be-2dce56710023) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/app-structure.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba4a28dee2efc0c5ef503d61177479cbe1ea849b/msteams-platform%2Fconcepts%2Fdesign%2Fapp-structure.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60c5bdcf-a0d6-47d7-bb83-ef7852b8743b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba4a28dee2efc0c5ef503d61177479cbe1ea849b/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-overview.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c189a2bb-945a-4806-a120-eb1cc5703993) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba4a28dee2efc0c5ef503d61177479cbe1ea849b/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bca5792f-f7ba-4888-8ddb-3162b92c9517) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/plan-responsive-tabs-for-teams-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba4a28dee2efc0c5ef503d61177479cbe1ea849b/msteams-platform%2Fconcepts%2Fdesign%2Fplan-responsive-tabs-for-teams-mobile.md) | 95 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9791a99-02e0-4007-bbb0-05d195f0d60c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/planning-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba4a28dee2efc0c5ef503d61177479cbe1ea849b/msteams-platform%2Fconcepts%2Fdesign%2Fplanning-checklist.md) | 88 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f680059-2f36-4035-b70c-9deb5179dbf4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/understand-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba4a28dee2efc0c5ef503d61177479cbe1ea849b/msteams-platform%2Fconcepts%2Fdesign%2Funderstand-use-cases.md) | 95 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/350c0992-eb85-4965-b064-b4b773595a8e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/get-started/get-started-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba4a28dee2efc0c5ef503d61177479cbe1ea849b/msteams-platform%2Fget-started%2Fget-started-overview.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33f8802d-ff17-4e86-8fca-300c51d3cd24) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview-explore.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba4a28dee2efc0c5ef503d61177479cbe1ea849b/msteams-platform%2Foverview-explore.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e2d51e5-4d81-4d5c-bbd6-2e2ac35bf230) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba4a28dee2efc0c5ef503d61177479cbe1ea849b/msteams-platform%2Foverview.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9990bea-d22c-4d93-8983-8f1504c61bd0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by stkong-sdk — APPROVED** [review]

**Review by v-habibaumme — APPROVED** [review]
Approved

**Pull request merged**
