### PR TITLE
[Doc Improvement][Update webapplicationinfo code - Update manifest for SSO][3249601]

### PR DESCRIPTION
**Pull request by v-vanv**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01206f689e350c553e2f0ec1d5f7be0b0b20d081/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b04a678-4576-42e2-b384-a57c441daf84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01206f689e350c553e2f0ec1d5f7be0b0b20d081/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba1b6444-7e6e-45d2-a861-b2ae0e62dfb2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/77bcb1d3a34e0769430b85de088381e63283d191/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36b2d432-ff57-44fb-a77e-ba6dc872c42b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/77bcb1d3a34e0769430b85de088381e63283d191/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e77af39-3987-4892-a170-c53bdfb3e0ad) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/655f58fb89152c4359c14451e30977386f790001/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23c1c27b-5145-430d-b691-b16f6a084c3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/655f58fb89152c4359c14451e30977386f790001/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d494ebd5-0563-44bd-9a38-74eb2ce91916) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Prasad-MSFT — APPROVED** [review]
Changes look fine. So, approving the PR

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e53d8d99d54781eb636ec33b4bed7f8a89efbc2/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f34e2b81-a536-4927-a842-86d0a1fb1e13) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e53d8d99d54781eb636ec33b4bed7f8a89efbc2/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c5f43b0-1ca6-4229-b8e0-0d3648b24fa5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/authentication/bot-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/364d8ebbee75bdbf2dffc6b67d317a676b13f97d/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fbot-sso-manifest.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8a1454f-9d58-4eda-93ef-364dcf65657d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/tab-sso-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/364d8ebbee75bdbf2dffc6b67d317a676b13f97d/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-manifest.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3890eec4-ce76-4ebd-9b90-ecfc744730b6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
