### PR TITLE
[Doc Improvement][Create bot app with Javascript][2396762]

### PR DESCRIPTION
**Pull request by v-bdeepa**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d7bda1568652f1532cdc33b71154f8f2f7491b7b/msteams-platform%2Fsbs-gs-bot.yml) | 92 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/626d2993-41f1-4d87-977c-9119678d1897) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c0f29bf4794075267b5a45aa10e42f86a50f5fca/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4e902cf-941a-43d1-8868-e09733e3bda7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bbafd8657226a33851c59b282d588ef1ca900ac9/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05e7fe2c-654e-48ad-9f13-eefbe92fbd1e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eb8bd6d62ece1d63ff00baffd50e1ca5f760c722/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5186811-9c7f-42c5-ad41-b9e8a07dfb25) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/eb8bd6d62ece1d63ff00baffd50e1ca5f760c722/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09e233f9-8f60-41ac-aa5e-9d9e10236310) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1138fb99aaa31d9d785ab7c59daaec518bdd6054/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ab4569b0-f1fd-46ed-a3fa-d2e94f7bdafb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1138fb99aaa31d9d785ab7c59daaec518bdd6054/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4baa43e6-ae88-4c6a-9458-5e97643640e7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2c501e50f5df90428ec5a610e96d82a07ac74e0/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/901d3cb1-4a92-4469-8104-ae2277e91acf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c2c501e50f5df90428ec5a610e96d82a07ac74e0/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/765c287d-6c2f-4198-8184-6fd8562a8f1c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0506011ec8037c5a348b109a95651bf3275018db/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4cc193c-9d9e-418a-8e89-b3550a92607c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0506011ec8037c5a348b109a95651bf3275018db/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b42c5223-5949-4839-b9da-185a07aefce5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/88ef75fd64a30fd8ec3ea1bcc0c9cae4e093f77b/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce2ec8fa-32b6-456e-a61a-88cadce07028) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/88ef75fd64a30fd8ec3ea1bcc0c9cae4e093f77b/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9012bbd4-570c-4239-b585-e5a189eafb18) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6eeaf9030b6e8f3844564ce54672ffb94dc3ae44/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8eddedd-286c-4d6a-906a-211864902475) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6eeaf9030b6e8f3844564ce54672ffb94dc3ae44/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db625e5c-1dba-47c5-b6e9-415288eca773) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7fc6c91ebb9a3a1ad907190a717a61667b31ab65/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7f974f0-a031-4222-a056-5aed5441a7a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7fc6c91ebb9a3a1ad907190a717a61667b31ab65/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a84d411-1ec6-4333-bc98-c9e6883ab9cb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/92e64048ab595187a55a795a794c0679f05a9352/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e29ad294-12d6-4b3b-8c43-c35199fa3367) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/92e64048ab595187a55a795a794c0679f05a9352/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/daa9f8c2-36d5-4c84-83b8-e2904d5bd209) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/01f328ce46a3e5ec28fda759865bfa5733086a3f/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/201e4b71-4c09-435d-9151-10534a8e3aaa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/01f328ce46a3e5ec28fda759865bfa5733086a3f/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0913628-6781-48fa-bcba-ed2d8fdc6d70) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by zyxiaoyuer — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/62ce8180ab54faf2515ba300f04c86463d6bc6f9/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35fb64bb-bf8d-49ca-a77a-7a8ab4c5966a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/62ce8180ab54faf2515ba300f04c86463d6bc6f9/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fb6191b-8291-4b53-b243-81d5943801fa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a80d6586270848859bcde5fe93b03e86d8ff84df/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6e1ddf78-3cbe-4c81-b0a9-7a5faa305cec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a80d6586270848859bcde5fe93b03e86d8ff84df/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/349bb588-5dfd-4d20-8ee0-de61487079ef) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/820c302f3d2df662379e9a9c8201ae18b1977e19/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7161b72c-1eff-47c2-82da-56d37bf8e18f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/820c302f3d2df662379e9a9c8201ae18b1977e19/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44bddc18-b3aa-479c-9832-81177841e5a5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/azure-provisioning-instructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4e6ff556a2be657e7cdfadfbd2f807060ac040f7/msteams-platform%2Fincludes%2Fget-started%2Fazure-provisioning-instructions.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b6a7e3d-5087-4821-972c-8904195b8718) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4e6ff556a2be657e7cdfadfbd2f807060ac040f7/msteams-platform%2Fsbs-gs-bot.yml) | 91 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4aeda64d-9a26-4885-bf2a-eca51449bc24) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
