### PR TITLE
[Doc Improvement][Integrate device capabilities revise see also section] 

### PR DESCRIPTION
**Pull request by v-vvchaganti**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/device-capabilities-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e882ba4ef96a7ec596e7c060c5dd249fb431dbbc/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fdevice-capabilities-overview.md) | 89 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c47d5ac9-fede-4e2a-9a62-af7db8d143b0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2047178eff60edf5c842da1e638efbcdd2b00636/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f0bcf35-ad6c-4f17-acf0-d23306c4bd04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2047178eff60edf5c842da1e638efbcdd2b00636/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e432f9f-a166-4807-8198-2e17fa047c78) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2047178eff60edf5c842da1e638efbcdd2b00636/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 93 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff1ab8d5-25aa-4dcf-a6ea-b48cf8e509c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2047178eff60edf5c842da1e638efbcdd2b00636/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/398ea48c-f2c4-47f4-bbf1-1c9bf777d2e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2047178eff60edf5c842da1e638efbcdd2b00636/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 94 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f41f8b5-268e-43d8-9895-c67bbf0d4b7d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74932f6ee4c1de63528af2b3aeb84c24e407ad01/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/351a76c5-bb39-4458-9497-dfc8d4ebbb03) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74932f6ee4c1de63528af2b3aeb84c24e407ad01/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5291f80f-0c51-43c8-8bab-81fc85f0afc1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74932f6ee4c1de63528af2b3aeb84c24e407ad01/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 93 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/faaa022b-3eea-4df8-afc9-b952b70f787e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74932f6ee4c1de63528af2b3aeb84c24e407ad01/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd9a9c97-21bb-4891-b4cd-ba03a1f0757d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74932f6ee4c1de63528af2b3aeb84c24e407ad01/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 94 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f5d69a9-24e0-4ed4-b4e0-f0dd01879f1c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c789fe2368360df9daf5a0e8587adc0e820ea8bc/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0eb0ecf-0633-4d0e-ba4d-7a4da95011c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c789fe2368360df9daf5a0e8587adc0e820ea8bc/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df35a2f7-6627-4b19-af38-bfbcc630c369) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c789fe2368360df9daf5a0e8587adc0e820ea8bc/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 93 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c005834-8b54-4520-a34d-98de194303ba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c789fe2368360df9daf5a0e8587adc0e820ea8bc/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfdb4ec3-d1e1-4826-9faa-0f8e1edc7606) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c789fe2368360df9daf5a0e8587adc0e820ea8bc/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 94 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8258fca-e98f-4f1c-a116-d0c156334dcf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d134d4b4b061722f1c53795d28029e7ea4bfb8f5/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d1baeb4-e648-48a1-a65c-0f25ebe60571) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d134d4b4b061722f1c53795d28029e7ea4bfb8f5/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0679901-f971-4e73-8186-734b6342cf64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d134d4b4b061722f1c53795d28029e7ea4bfb8f5/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 93 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b9c07ba-6eed-4bcd-a28d-5cf887a834a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d134d4b4b061722f1c53795d28029e7ea4bfb8f5/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/552a2e74-7d63-4c6f-ab0a-25b3d184f9f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d134d4b4b061722f1c53795d28029e7ea4bfb8f5/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 94 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90171c11-3fbc-4e20-970b-75c19838dbf3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90130287fbb105e4af5e28ecc7feb8d550ffe499/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d30e161-55c7-4dbd-82c5-6c0f62f22935) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90130287fbb105e4af5e28ecc7feb8d550ffe499/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e9bc064-fb32-4b2e-96db-0c0d27edae44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90130287fbb105e4af5e28ecc7feb8d550ffe499/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0f5d57c-341d-46bf-b44a-c700799bdf0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90130287fbb105e4af5e28ecc7feb8d550ffe499/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/890e1805-71f0-4509-900a-ffbea972cc29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90130287fbb105e4af5e28ecc7feb8d550ffe499/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 94 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45c7957a-4524-4bb0-a892-e0104b5ff429) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ed1907b6cc851925b17ef5b29ebd4fa7464c901/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee9e1097-aaab-4042-941e-fb0bb1eb50ed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ed1907b6cc851925b17ef5b29ebd4fa7464c901/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4302e47-eab6-4536-8be4-205172c31ae3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ed1907b6cc851925b17ef5b29ebd4fa7464c901/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d0a3196-cca4-4cd6-b6ae-fa1557008e54) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ed1907b6cc851925b17ef5b29ebd4fa7464c901/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/478b185d-1375-4ab2-b0f7-e21b4f32d0fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8ed1907b6cc851925b17ef5b29ebd4fa7464c901/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 94 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da92f084-da26-482e-b1cf-b54ae238b3d7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/device-capabilities/location-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06fa092822a5736df1ddb64cc279c7e96ba5b6d1/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Flocation-capability.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb00cd05-267d-4acf-94eb-90054bea1fec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/media-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06fa092822a5736df1ddb64cc279c7e96ba5b6d1/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fmedia-capabilities.md) | 98 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b75f89a-36a4-454e-8ebf-73706214c8a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/native-device-permissions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06fa092822a5736df1ddb64cc279c7e96ba5b6d1/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fnative-device-permissions.md) | 91 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42f11331-55fc-4fee-a81e-75d89d15134e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/people-picker-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06fa092822a5736df1ddb64cc279c7e96ba5b6d1/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fpeople-picker-capability.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4629fe4-34b0-4491-abb1-f157fec2dd9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/device-capabilities/qr-barcode-scanner-capability.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06fa092822a5736df1ddb64cc279c7e96ba5b6d1/msteams-platform%2Fconcepts%2Fdevice-capabilities%2Fqr-barcode-scanner-capability.md) | 94 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd5d78b3-acd3-4200-b46b-b72e4373846f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-abirade** [comment]
Closing the PR.

**Pull request closed without merging**
