### PR TITLE
Distro updates, including new table.

### PR DESCRIPTION
**Pull request by heath-hamilton**

### CODE REVIEW

**Comment by heath-hamilton** [comment]
@vikramjit-singh-chug Please see the updated text regarding apps listed in the Teams store. Thinking about this more, I formatted the info in tables, which may make it clearer.

**Review by vikramjit-singh-chug — APPROVED** [review]
This is great @heath-hamilton!
Thanks :)

**Comment by heath-hamilton** [comment]
Ready to merge, @surbhigupta12.

**Review by surbhigupta12 — APPROVED** [review]
Approved.

**Pull request merged**
