### PR TITLE
UI kit fall 2021 updates

### PR DESCRIPTION
**Pull request by heath-hamilton**
This update includes:

* New shared meeting stage designs
* Updated alert and notification bar designs
* New calendar UI template
* Minor fixes

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ade05b8ef5f1129cdbdcbd80654134e35420489/msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md) | 94 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e13fa5ca-cf7d-4e5f-83f6-a106ec2ae8ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ade05b8ef5f1129cdbdcbd80654134e35420489/msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3eb0ce2a-43ab-432c-bd09-a8762ca20b77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-basic-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ade05b8ef5f1129cdbdcbd80654134e35420489/msteams-platform/concepts/design/design-teams-app-basic-ui-components.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65c2f2bb-a91d-47ae-875d-fb97875a7d86) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5ade05b8ef5f1129cdbdcbd80654134e35420489/msteams-platform/concepts/design/design-teams-app-ui-templates.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e2367a4-d299-4d7c-86a1-fdf1f6ef9dcb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93fc6a7180548a98182d0f04a339b5d93536b2ef/msteams-platform/apps-in-teams-meetings/design/designing-apps-in-meetings.md) | 94 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09814527-2795-449c-a9c8-62883701485a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93fc6a7180548a98182d0f04a339b5d93536b2ef/msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e347b3e-1608-4ea9-b6fa-42d08431dca5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-basic-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93fc6a7180548a98182d0f04a339b5d93536b2ef/msteams-platform/concepts/design/design-teams-app-basic-ui-components.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa3b6a33-ed50-4f05-9a58-e0f7fb9eec67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/93fc6a7180548a98182d0f04a339b5d93536b2ef/msteams-platform/concepts/design/design-teams-app-ui-templates.md) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1495ec1b-16d9-455a-a3fc-8ed69bc0f3d7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by heath-hamilton** [comment]
@surbhigupta12 This PR can merge once the latest UI kit publishes.

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
