### PR TITLE
[Doc Feature][Visual studio 17.7 doc updates]

### PR DESCRIPTION
**Pull request by v-bvishnu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a6ae328b5492155e2bc7fa71336bbc0021259c9d/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/869d6e0d-b5d5-4572-9234-ae2cee667717) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6ae328b5492155e2bc7fa71336bbc0021259c9d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8319743d-1b1c-464c-8146-6516474d250a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/deploy-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6ae328b5492155e2bc7fa71336bbc0021259c9d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdeploy-vs.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9306fe3d-b9f1-4a9b-88d9-210c70e14fc5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a6ae328b5492155e2bc7fa71336bbc0021259c9d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 95 | 54 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd653e28-9d31-4cf9-ac5e-3400df5d495c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9da841dd1537da4ffa5721796e1ea4262bdba027/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0cb8468-e2e8-4e6f-9ac8-7f6ea385cfd4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9da841dd1537da4ffa5721796e1ea4262bdba027/msteams-platform%2Ftoolkit%2Fdeploy.md) | 97 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ba4793a-bdd2-4831-ac5f-37c07f1c3f52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9da841dd1537da4ffa5721796e1ea4262bdba027/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67445445-4dc5-45ef-842d-eaa32365a787) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/deploy-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9da841dd1537da4ffa5721796e1ea4262bdba027/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdeploy-vs.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01bdb711-5726-42cc-b946-e42d75618be8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9da841dd1537da4ffa5721796e1ea4262bdba027/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 95 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7af4d548-2287-4b1e-9809-30e4125eb6b5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/6659986e333d4de534acb73457652a8bf52298ce/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f6720a4-5564-4b6e-9e89-375289dd1de4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6659986e333d4de534acb73457652a8bf52298ce/msteams-platform%2Ftoolkit%2Fdeploy.md) | 97 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84df733c-cee2-4037-93e3-33991e547420) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6659986e333d4de534acb73457652a8bf52298ce/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb116b0f-361d-4f4a-99b5-c89f613562cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/deploy-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6659986e333d4de534acb73457652a8bf52298ce/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdeploy-vs.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41c598b5-a44a-43af-8204-e54bbc989963) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6659986e333d4de534acb73457652a8bf52298ce/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 95 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8fdfda21-fa97-4bcf-9a8f-03af7f7495be) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/75d578e812fc92ed8e2fe9c914e34d2b73ea9b47/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3513dce3-5e4f-490d-847e-b9bd1da45014) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/75d578e812fc92ed8e2fe9c914e34d2b73ea9b47/msteams-platform%2Ftoolkit%2Fdeploy.md) | 97 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/616a0163-9ae8-4b56-8bd0-66f670e73736) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/75d578e812fc92ed8e2fe9c914e34d2b73ea9b47/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d103f247-0884-4c91-bb8c-7ed4f1668689) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/deploy-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/75d578e812fc92ed8e2fe9c914e34d2b73ea9b47/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdeploy-vs.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0cea6f51-2a7b-4300-87ea-ebf039817ed6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/75d578e812fc92ed8e2fe9c914e34d2b73ea9b47/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 95 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed51ebed-4060-44f5-8c7b-4a1a9bd3e257) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/09c8bfe50a9ee2874bae0383c2dcebb0b1902193/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a59f9e56-1a03-470d-bad0-85fa2e456d5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/09c8bfe50a9ee2874bae0383c2dcebb0b1902193/msteams-platform%2Ftoolkit%2Fdeploy.md) | 97 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d0455a0-989e-4122-9850-b67d4543bbad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/09c8bfe50a9ee2874bae0383c2dcebb0b1902193/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dece07bb-f69b-487a-89e6-9d1e9b7f5826) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/deploy-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/09c8bfe50a9ee2874bae0383c2dcebb0b1902193/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdeploy-vs.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02f58634-1506-4216-85d0-e3389611c4e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/09c8bfe50a9ee2874bae0383c2dcebb0b1902193/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 95 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97af7caa-7462-4474-a3f6-aef5ec9b1283) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0dae7a2bc64d4e9f751f69cf36e183e1cdbd31df/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a867156-1c4b-4c99-9a0d-d14723246d5d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dae7a2bc64d4e9f751f69cf36e183e1cdbd31df/msteams-platform%2Ftoolkit%2Fdeploy.md) | 97 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/216c8a08-a9c3-4be9-9c40-22046ce4914a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dae7a2bc64d4e9f751f69cf36e183e1cdbd31df/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5659313-6ea2-4f84-ae77-d57597a06e3e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/deploy-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dae7a2bc64d4e9f751f69cf36e183e1cdbd31df/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdeploy-vs.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1630f73b-ee7e-4897-b2aa-4965f33ee219) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0dae7a2bc64d4e9f751f69cf36e183e1cdbd31df/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 95 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3352adc-f460-4b66-94a2-49c0498285e8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f8c28ad5df110e3c64de6e97b016018a4689eb8c/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50fdc5fe-c673-45f0-be14-06f3af309b09) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8c28ad5df110e3c64de6e97b016018a4689eb8c/msteams-platform%2Ftoolkit%2Fdeploy.md) | 97 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9089ef97-de8a-4625-b556-41638309bbe0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8c28ad5df110e3c64de6e97b016018a4689eb8c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0e7c28e-0fdb-4d85-b990-b8fcd12e0f8e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/deploy-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8c28ad5df110e3c64de6e97b016018a4689eb8c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdeploy-vs.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb6a158b-9e57-470d-83ad-63d6b3ade300) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8c28ad5df110e3c64de6e97b016018a4689eb8c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 95 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fba51f47-ec67-49d6-85c8-881ba85cca30) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bd762ae220c4067dccf4ddffc834b85ee4ffec04/msteams-platform%2FTOC.yml) | 99 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3401aec-fd49-4a3e-8048-fabdb2b8c61b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd762ae220c4067dccf4ddffc834b85ee4ffec04/msteams-platform%2Ftoolkit%2Fdeploy.md) | 97 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9a28729-37d8-47fc-9f2e-86a1f816f905) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd762ae220c4067dccf4ddffc834b85ee4ffec04/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 97 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b53548bd-36f3-402a-9f27-aa274d4deed1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/deploy-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd762ae220c4067dccf4ddffc834b85ee4ffec04/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdeploy-vs.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc5c7635-5096-4d9d-b254-6e6817a8ac16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bd762ae220c4067dccf4ddffc834b85ee4ffec04/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 95 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8132012f-dcc2-44f6-b476-83b765aba0d5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
