### PR TITLE
[Doc Improvement][SEO description update 12][3885116]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4379a5205f44249069169719142886cb8f5008f9/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-advanced-ui-components.md) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/767e7211-93c0-4b3b-9089-f5c7e4cfe83c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-artwork-store.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4379a5205f44249069169719142886cb8f5008f9/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-artwork-store.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc6611b4-e3a0-4200-9dfb-66015658ca9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4379a5205f44249069169719142886cb8f5008f9/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-fundamentals.md) | 80 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5fd17cb8-8cae-49b1-ba2d-fec97845d99d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-icon-store-appbar.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4379a5205f44249069169719142886cb8f5008f9/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-icon-store-appbar.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8081f38-f3c7-43d4-9620-6e76734a1462) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-layout-scaling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4379a5205f44249069169719142886cb8f5008f9/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-layout-scaling.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfaae3d5-3201-43a1-828f-ca96a389d208) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-light-box-view.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4379a5205f44249069169719142886cb8f5008f9/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-light-box-view.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4767a1e7-bc0f-4183-88b3-e64a25f72fcd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4379a5205f44249069169719142886cb8f5008f9/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-process.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c47aee13-af7e-4f96-a3b7-72e545b0a4df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-shape-elevation.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4379a5205f44249069169719142886cb8f5008f9/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-shape-elevation.md) | 82 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97427d72-57d9-4112-92e7-ce1ac144cb6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-type.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4379a5205f44249069169719142886cb8f5008f9/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-type.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9fdc66e9-424f-4f74-a134-c0471b038f26) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4379a5205f44249069169719142886cb8f5008f9/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e12dcaf6-e34f-412c-abc5-fe9088c64dcd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44fef3580dc6f69823a80c8385bf456094437515/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-advanced-ui-components.md) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43975337-5654-424b-9710-22fc8dcb6d30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-artwork-store.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44fef3580dc6f69823a80c8385bf456094437515/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-artwork-store.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/577c5120-0909-4a67-9829-e4f3758faf1b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44fef3580dc6f69823a80c8385bf456094437515/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-fundamentals.md) | 80 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/499451f9-0a1b-4019-8414-908ac25c80c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-icon-store-appbar.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44fef3580dc6f69823a80c8385bf456094437515/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-icon-store-appbar.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ffd0868-0850-4177-a1f8-844edc2cd2f9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-layout-scaling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44fef3580dc6f69823a80c8385bf456094437515/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-layout-scaling.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb40ae1b-ab7a-41ba-b112-51f51d489606) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-light-box-view.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44fef3580dc6f69823a80c8385bf456094437515/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-light-box-view.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4682a699-ae02-4db3-b248-d8a1bda31e6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44fef3580dc6f69823a80c8385bf456094437515/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-process.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed6e89f1-44c9-4c19-b043-cd014f086b00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-shape-elevation.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44fef3580dc6f69823a80c8385bf456094437515/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-shape-elevation.md) | 82 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2167063a-af13-4834-a7c8-b6c3f3b8f962) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-type.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44fef3580dc6f69823a80c8385bf456094437515/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-type.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e9cdcde-f489-4e71-a79f-2f4e6ad53b3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/44fef3580dc6f69823a80c8385bf456094437515/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70e37ef6-b9b6-4d2e-ab75-8ccf5e8d4e51) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ce0f6dae1bedd4d11d9c33c0b3ad28919f5a87a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-advanced-ui-components.md) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b3cf63e-e649-4ce8-8b3b-e5f04e134af4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-artwork-store.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ce0f6dae1bedd4d11d9c33c0b3ad28919f5a87a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-artwork-store.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0a5135c-6ed9-48f4-932b-ca6dc4d12ff9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ce0f6dae1bedd4d11d9c33c0b3ad28919f5a87a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-fundamentals.md) | 80 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3da1a57b-9af0-4a05-a5cc-0f9e8edbb87a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-icon-store-appbar.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ce0f6dae1bedd4d11d9c33c0b3ad28919f5a87a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-icon-store-appbar.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be35546e-cddf-448b-a0a4-81bae71ea57d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-layout-scaling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ce0f6dae1bedd4d11d9c33c0b3ad28919f5a87a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-layout-scaling.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b9842022-1d55-4e29-af70-a9a5a12ae872) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-light-box-view.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ce0f6dae1bedd4d11d9c33c0b3ad28919f5a87a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-light-box-view.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4603ba31-8dff-46e4-ac18-64891e8bfa8c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ce0f6dae1bedd4d11d9c33c0b3ad28919f5a87a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-process.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c6da436-121b-4a80-9315-cc6fc0c2df67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-shape-elevation.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ce0f6dae1bedd4d11d9c33c0b3ad28919f5a87a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-shape-elevation.md) | 82 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f36baed0-7b09-476c-a138-7148a09f85bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-type.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ce0f6dae1bedd4d11d9c33c0b3ad28919f5a87a/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-type.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87f030bc-f4c6-4fe0-af01-0813dec16c0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ce0f6dae1bedd4d11d9c33c0b3ad28919f5a87a/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ae16cc9-9fbb-4983-9752-2273a6d736cf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/design-teams-app-advanced-ui-components.md](https://github.com/MicrosoftDocs/msteams-docs/blob/740f607d7df4cb973e94fcfde63bdccbb85b9395/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-advanced-ui-components.md) | 85 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6674a718-4f95-4a33-9c55-6492a285121f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-artwork-store.md](https://github.com/MicrosoftDocs/msteams-docs/blob/740f607d7df4cb973e94fcfde63bdccbb85b9395/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-artwork-store.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/810383ed-93dc-4d59-98d8-5c5465ad86b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/740f607d7df4cb973e94fcfde63bdccbb85b9395/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-fundamentals.md) | 80 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/709bf653-a9ee-4849-81f9-dadfd511fc01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-icon-store-appbar.md](https://github.com/MicrosoftDocs/msteams-docs/blob/740f607d7df4cb973e94fcfde63bdccbb85b9395/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-icon-store-appbar.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/354e7773-9fea-460b-84b1-3b892d570fac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-layout-scaling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/740f607d7df4cb973e94fcfde63bdccbb85b9395/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-layout-scaling.md) | 93 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d3f87c2-8cac-4240-8d8d-4736e4fec9ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-light-box-view.md](https://github.com/MicrosoftDocs/msteams-docs/blob/740f607d7df4cb973e94fcfde63bdccbb85b9395/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-light-box-view.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05d4b705-3c80-417c-a92f-7dacc5969b0e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-process.md](https://github.com/MicrosoftDocs/msteams-docs/blob/740f607d7df4cb973e94fcfde63bdccbb85b9395/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-process.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d68d9e7c-54f4-44e4-9bc7-616cdf997e63) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-shape-elevation.md](https://github.com/MicrosoftDocs/msteams-docs/blob/740f607d7df4cb973e94fcfde63bdccbb85b9395/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-shape-elevation.md) | 82 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ff99bc3-729a-4264-936d-2d392b030606) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-type.md](https://github.com/MicrosoftDocs/msteams-docs/blob/740f607d7df4cb973e94fcfde63bdccbb85b9395/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-type.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f3a58d1a-10f0-46e0-9b90-9a891a9c2f7f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/enable-app-customization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/740f607d7df4cb973e94fcfde63bdccbb85b9395/msteams-platform%2Fconcepts%2Fdesign%2Fenable-app-customization.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/488a97c4-35ba-4193-9b0e-7a3c51253251) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
