### PR TITLE
[Doc Improvement][SEO meta title update 3][3947113]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed99347436e06302a21a76a9a4597cd82c1ae8a1/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bf0a97e-c6ea-4dca-9c8f-57ba6d40b284) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed99347436e06302a21a76a9a4597cd82c1ae8a1/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d142036f-2c74-4f34-9bb9-a2d2fd00887b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed99347436e06302a21a76a9a4597cd82c1ae8a1/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0068ed9d-0d7a-4378-a856-7f0140688c1c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed99347436e06302a21a76a9a4597cd82c1ae8a1/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6e583ca-f928-4d19-92b4-bb8b7d156534) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed99347436e06302a21a76a9a4597cd82c1ae8a1/msteams-platform%2Fsamples%2Fvirtual-tables-api.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fec723c-c1bc-45ea-b25d-3c5812846c67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ed99347436e06302a21a76a9a4597cd82c1ae8a1/msteams-platform%2Fsbs-send-proactive.yml) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d2ed71e-0f1d-4f1f-8852-e5759849aeaf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed99347436e06302a21a76a9a4597cd82c1ae8a1/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa3d1a20-8b45-42fd-95b9-a4a860a2aba0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed99347436e06302a21a76a9a4597cd82c1ae8a1/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7439a8d9-5a2b-4278-9d9b-b7343f01f040) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed99347436e06302a21a76a9a4597cd82c1ae8a1/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 93 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4435a314-6d0a-4134-b37d-673a8b4f946d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed99347436e06302a21a76a9a4597cd82c1ae8a1/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d57cd03-91c1-4532-9e9e-f095bf0e232a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Review by v-sdhakshina — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdf5c4524325938c7fe2be3f53ed4f2a12102c62/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93152070-74f5-43d8-92fd-f785f23b627d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdf5c4524325938c7fe2be3f53ed4f2a12102c62/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77bf7b52-5044-4909-84c9-784274667e08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdf5c4524325938c7fe2be3f53ed4f2a12102c62/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3de14d2e-406f-404c-bcc3-f7e4c461f3eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdf5c4524325938c7fe2be3f53ed4f2a12102c62/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4afad788-8cf8-42dd-b990-b320dcd149c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdf5c4524325938c7fe2be3f53ed4f2a12102c62/msteams-platform%2Fsamples%2Fvirtual-tables-api.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a959356d-56b4-4ddd-be2d-114accc40c8c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fdf5c4524325938c7fe2be3f53ed4f2a12102c62/msteams-platform%2Fsbs-send-proactive.yml) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b90b9d44-76b8-43e4-a37c-572d1a397cc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdf5c4524325938c7fe2be3f53ed4f2a12102c62/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86c4ad11-2f1b-4cf8-b7a5-8e97062b02fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdf5c4524325938c7fe2be3f53ed4f2a12102c62/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0392cab9-cb50-4c9f-9866-bd18d900c7e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdf5c4524325938c7fe2be3f53ed4f2a12102c62/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 93 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0d3a2e7-2534-46a3-aced-f6c188b4bd74) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdf5c4524325938c7fe2be3f53ed4f2a12102c62/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/afb5911d-18cc-4507-8769-809bef10fdae) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce4a1e06b931ec5c3b971409b9b5abcc80454bd0/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e8d7137-07e0-4f56-be67-c74a5953c79a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce4a1e06b931ec5c3b971409b9b5abcc80454bd0/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a223d538-65e1-46ce-be52-862a60764d50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce4a1e06b931ec5c3b971409b9b5abcc80454bd0/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5593c541-c7c2-4756-bb0e-8455a46212b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce4a1e06b931ec5c3b971409b9b5abcc80454bd0/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72f13d5f-bdc7-43ca-a4ca-c9202b926ba2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce4a1e06b931ec5c3b971409b9b5abcc80454bd0/msteams-platform%2Fsamples%2Fvirtual-tables-api.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bce77d0-b163-48f7-ad9d-35fa37b72b55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ce4a1e06b931ec5c3b971409b9b5abcc80454bd0/msteams-platform%2Fsbs-send-proactive.yml) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8155eaf-5506-44b9-9ebd-8b37f6a2db98) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce4a1e06b931ec5c3b971409b9b5abcc80454bd0/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21432f17-f0a5-4183-97fd-a6d76626c2e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce4a1e06b931ec5c3b971409b9b5abcc80454bd0/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de2b9681-1040-4c9f-ab84-0d2485247537) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce4a1e06b931ec5c3b971409b9b5abcc80454bd0/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 93 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fccdaf5-2ca4-4ff8-9e29-dc018c1e0212) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce4a1e06b931ec5c3b971409b9b5abcc80454bd0/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba2e4161-d6de-449f-a64e-3cbeb9cf08e1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66db7831bd6908c343fb9923be15bbb70be49fb7/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ca65e8c-377a-44d3-97c8-abf2115cbdb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66db7831bd6908c343fb9923be15bbb70be49fb7/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63333a73-5c21-40ab-8f9f-574fc72527c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66db7831bd6908c343fb9923be15bbb70be49fb7/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfb7e7d2-996c-4798-83c8-900b2dcafdcf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66db7831bd6908c343fb9923be15bbb70be49fb7/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a9f322f-64f4-48fd-86b4-84664ce694d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66db7831bd6908c343fb9923be15bbb70be49fb7/msteams-platform%2Fsamples%2Fvirtual-tables-api.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72b9937a-a25d-4654-9702-40079671de04) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/66db7831bd6908c343fb9923be15bbb70be49fb7/msteams-platform%2Fsbs-send-proactive.yml) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da53803d-0aa7-4d92-beb6-30c27da2e221) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66db7831bd6908c343fb9923be15bbb70be49fb7/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9b78817-74ba-4a6b-928f-d5575c32591b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66db7831bd6908c343fb9923be15bbb70be49fb7/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5acb43d0-2cb3-48d9-ac25-54f34e434b23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66db7831bd6908c343fb9923be15bbb70be49fb7/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 93 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d148e07f-9409-4cf4-a7d6-d587263c82a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/66db7831bd6908c343fb9923be15bbb70be49fb7/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01189731-99a7-453d-914c-7f04822cbdc3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93d67bdbf187503779bd5569e62357da9337fc4/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 90 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d8f6e31-c703-4bc1-872e-59becf7d1022) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/command-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93d67bdbf187503779bd5569e62357da9337fc4/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fcommand-bot-in-teams.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f675b617-ebe5-4ecf-a5fe-fa9b36bef015) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93d67bdbf187503779bd5569e62357da9337fc4/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0281c92-3f6e-46cd-8e39-cc9442e7afe4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/integrate-web-apps-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93d67bdbf187503779bd5569e62357da9337fc4/msteams-platform%2Fsamples%2Fintegrate-web-apps-overview.md) | 90 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6271c9f-a516-46fb-906f-84a25078e3d3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93d67bdbf187503779bd5569e62357da9337fc4/msteams-platform%2Fsamples%2Fvirtual-tables-api.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d29abb13-3db4-48ad-82ce-d8c49f976984) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-send-proactive.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b93d67bdbf187503779bd5569e62357da9337fc4/msteams-platform%2Fsbs-send-proactive.yml) | 91 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d5e1142-b2c5-4aed-a386-0507be0c0c76) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93d67bdbf187503779bd5569e62357da9337fc4/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-personal-tab.md) | 93 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8495d8e5-ee9d-45a6-a3c7-0c1ecfdd6764) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/content-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93d67bdbf187503779bd5569e62357da9337fc4/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fcontent-page.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b106319d-8ea5-4ce6-a865-cb26e5e3fe75) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/build-a-RAG-bot-in-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93d67bdbf187503779bd5569e62357da9337fc4/msteams-platform%2Ftoolkit%2Fbuild-a-RAG-bot-in-teams.md) | 93 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b18ca008-20f5-4ec5-be8d-6546831de6cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b93d67bdbf187503779bd5569e62357da9337fc4/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3875e159-e466-44e2-890e-139a02006d6c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
