### PR TITLE
[Doc Improvement][SEO1 meta title update for same H1][3948816]

### PR DESCRIPTION
**Pull request by v-ramyas5**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e75fff88f585d5226b5faec758956df9cd878a39/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6607ea02-0323-46d6-a938-44a757702abe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e75fff88f585d5226b5faec758956df9cd878a39/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd260d2d-d5fb-43f0-bbc8-c3c0874775e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/bot-copilot-handoff.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e75fff88f585d5226b5faec758956df9cd878a39/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fbot-copilot-handoff.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfaac4ad-2237-491b-acc4-2f28741fcc5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e75fff88f585d5226b5faec758956df9cd878a39/msteams-platform%2Fbots%2Fhow-to%2Fformat-your-bot-messages.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2850be9-1f23-414a-9f07-c5be1da70201) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-api-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e75fff88f585d5226b5faec758956df9cd878a39/msteams-platform%2Fmessaging-extensions%2Fbuild-api-based-message-extension.md) | 92 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6161794d-f1db-4212-a5ff-e98b282a0080) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e75fff88f585d5226b5faec758956df9cd878a39/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64764c72-1a66-4a88-9cb0-f14cf03cbd31) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e75fff88f585d5226b5faec758956df9cd878a39/msteams-platform%2Ftabs%2Fhow-to%2Fdeveloper-tools.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4297fae7-676b-40a2-b01b-767fde348dce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/dynamic-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e75fff88f585d5226b5faec758956df9cd878a39/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdynamic-search.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7f17a80-2a4e-4bc8-b137-f066d02afcdc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e75fff88f585d5226b5faec758956df9cd878a39/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 90 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d96517c-77c2-43f9-bc9b-ab85ae023da5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e75fff88f585d5226b5faec758956df9cd878a39/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aff6dd4f-4fe3-445e-9970-35f797599ddc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48d2f26965b082e1b04a6f69625f6a93e193ef1c/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35c1fbb1-b6c3-417e-bd2e-1ce341239912) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48d2f26965b082e1b04a6f69625f6a93e193ef1c/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a292a353-690f-4402-ba57-9668212c196f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/bot-copilot-handoff.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48d2f26965b082e1b04a6f69625f6a93e193ef1c/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fbot-copilot-handoff.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b61fc2fb-e95d-498e-b288-6dc54acbe063) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48d2f26965b082e1b04a6f69625f6a93e193ef1c/msteams-platform%2Fbots%2Fhow-to%2Fformat-your-bot-messages.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f249728-ead1-4e3b-b96c-9f084a58ae55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-api-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48d2f26965b082e1b04a6f69625f6a93e193ef1c/msteams-platform%2Fmessaging-extensions%2Fbuild-api-based-message-extension.md) | 92 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bcaffd3-b1c2-483b-b1df-8f22a4107b5b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48d2f26965b082e1b04a6f69625f6a93e193ef1c/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cc07b7c-6d27-4eda-b234-2cc050ce249b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48d2f26965b082e1b04a6f69625f6a93e193ef1c/msteams-platform%2Ftabs%2Fhow-to%2Fdeveloper-tools.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31019ad4-7699-419b-a9ae-dcce0c9fc721) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/dynamic-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48d2f26965b082e1b04a6f69625f6a93e193ef1c/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdynamic-search.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/440dc397-2975-422a-8b7f-c100ae8163bc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48d2f26965b082e1b04a6f69625f6a93e193ef1c/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 90 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/622b05e0-02d2-4fef-a8a5-577841a4f52a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48d2f26965b082e1b04a6f69625f6a93e193ef1c/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/266fcd63-8e07-44ef-a7a1-a4c6295b29ef) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcb944b085429bb657aec5df7532dd4d6b331fae/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2f89d6c-93f9-4a26-90af-70d2ac849ae5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcb944b085429bb657aec5df7532dd4d6b331fae/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6d87d26-7681-431d-8deb-d2b6006e602b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/bot-copilot-handoff.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcb944b085429bb657aec5df7532dd4d6b331fae/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fbot-copilot-handoff.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e936a45c-8bd3-4a32-bfdf-028e4969d2d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcb944b085429bb657aec5df7532dd4d6b331fae/msteams-platform%2Fbots%2Fhow-to%2Fformat-your-bot-messages.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4e72fea-c9f5-42e5-9941-7fd5c4248435) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-api-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcb944b085429bb657aec5df7532dd4d6b331fae/msteams-platform%2Fmessaging-extensions%2Fbuild-api-based-message-extension.md) | 92 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/834538b4-b791-4af9-9900-c822dd5ca515) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcb944b085429bb657aec5df7532dd4d6b331fae/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20fc3b60-d1d9-44a7-8352-c411ccb6743b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcb944b085429bb657aec5df7532dd4d6b331fae/msteams-platform%2Ftabs%2Fhow-to%2Fdeveloper-tools.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a19e3db-fecf-4f6d-bc2a-b1ddf794241f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/dynamic-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcb944b085429bb657aec5df7532dd4d6b331fae/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdynamic-search.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/672bb768-9fbb-40c1-b2c3-fded8453cdfb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcb944b085429bb657aec5df7532dd4d6b331fae/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 90 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9b1e75d-6a9c-4bbf-aac7-5d276085dd18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dcb944b085429bb657aec5df7532dd4d6b331fae/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f8a8e09-1d37-4598-8014-cc8bcb394fee) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8d51249a67e24939103c268e0ee0bcbceb750e2/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68f3a342-6018-442b-b0ad-3f2e36ee91b8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8d51249a67e24939103c268e0ee0bcbceb750e2/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae27efb8-06d0-4bdb-a5b9-49433c539cad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/bot-copilot-handoff.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8d51249a67e24939103c268e0ee0bcbceb750e2/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fbot-copilot-handoff.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13eb8b99-4578-4c4e-b73a-b73ac3e62571) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8d51249a67e24939103c268e0ee0bcbceb750e2/msteams-platform%2Fbots%2Fhow-to%2Fformat-your-bot-messages.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a81573c9-b0af-4616-90a1-c5266e4b2adb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-api-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8d51249a67e24939103c268e0ee0bcbceb750e2/msteams-platform%2Fmessaging-extensions%2Fbuild-api-based-message-extension.md) | 92 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1635c47-478f-47ce-80ea-1667103b2d69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8d51249a67e24939103c268e0ee0bcbceb750e2/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c11c8be5-bc0b-4898-b8f9-564a86142691) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8d51249a67e24939103c268e0ee0bcbceb750e2/msteams-platform%2Ftabs%2Fhow-to%2Fdeveloper-tools.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/684c0ab9-e4b0-4461-ab50-370858ff6215) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/dynamic-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8d51249a67e24939103c268e0ee0bcbceb750e2/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdynamic-search.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/010d536f-9c43-434f-aa1d-de7b0eb30480) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8d51249a67e24939103c268e0ee0bcbceb750e2/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 90 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee2145d8-bbf6-411c-bdbc-74258ddaf6fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f8d51249a67e24939103c268e0ee0bcbceb750e2/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d6b8ef6-dc8f-4890-a85a-dfaf61b455de) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-preethah — APPROVED** [review]
Approved.

**Review by Wajeed-msft — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc2165666daeced51e300fbd7ad918e73eecc00b/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 92 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d85fd46-87b0-4422-9ef8-11c66c8c9843) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/authentication/add-authentication.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc2165666daeced51e300fbd7ad918e73eecc00b/msteams-platform%2Fbots%2Fhow-to%2Fauthentication%2Fadd-authentication.md) | 90 | 58 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6d566e18-a5a8-4353-ae4f-7a0450ee1121) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/bot-copilot-handoff.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc2165666daeced51e300fbd7ad918e73eecc00b/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fbot-copilot-handoff.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b098a6b7-f87f-449a-bb86-edcefa71b7a7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/format-your-bot-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc2165666daeced51e300fbd7ad918e73eecc00b/msteams-platform%2Fbots%2Fhow-to%2Fformat-your-bot-messages.md) | 95 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f24ade57-6fc8-421b-b333-507bf708f191) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/build-api-based-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc2165666daeced51e300fbd7ad918e73eecc00b/msteams-platform%2Fmessaging-extensions%2Fbuild-api-based-message-extension.md) | 92 | 53 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94b1db92-6f4e-494e-8c3e-bed33522637f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc2165666daeced51e300fbd7ad918e73eecc00b/msteams-platform%2Ftabs%2Fhow-to%2Faccess-teams-context.md) | 94 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f39c9369-c01c-4625-a817-387f92a297fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/developer-tools.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc2165666daeced51e300fbd7ad918e73eecc00b/msteams-platform%2Ftabs%2Fhow-to%2Fdeveloper-tools.md) | 87 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06f13153-17c6-43fc-9c13-125947983341) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/dynamic-search.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc2165666daeced51e300fbd7ad918e73eecc00b/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdynamic-search.md) | 93 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/82533ff5-7a1b-46d8-9d0c-df1d6f9bd3d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc2165666daeced51e300fbd7ad918e73eecc00b/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 90 | 71 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88ed6d9e-b791-4bfd-a61d-cf04008ef721) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cc2165666daeced51e300fbd7ad918e73eecc00b/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7eef2b9e-a6be-49a7-8dbe-fcad16664adc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
