### PR TITLE
[Doc Improvement][SEO meta description update][3939720]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/collaboration-controls-limitations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58e328aab60aa94aab4d4c68b2f69011cd7bac8f/msteams-platform%2Fsamples%2Fcollaboration-controls-limitations.md) | 83 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa4adb6c-4a32-4a7c-b75b-a73f4d32a43e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/configure-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58e328aab60aa94aab4d4c68b2f69011cd7bac8f/msteams-platform%2Fsamples%2Fconfigure-tasks.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bd104e9-30f8-488b-ba42-e69bed6d5d1a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-table-entity-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/58e328aab60aa94aab4d4c68b2f69011cd7bac8f/msteams-platform%2Fsamples%2Fvirtual-table-entity-references.md) | 80 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2b108ec-1f32-48f9-91bf-a1e3b27701b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-msg-ext-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/58e328aab60aa94aab4d4c68b2f69011cd7bac8f/msteams-platform%2Fsbs-api-msg-ext-ttk.yml) | 80 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5fb0e7a4-6fad-4174-8cf1-1851c2e28815) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/58e328aab60aa94aab4d4c68b2f69011cd7bac8f/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 81 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1a2a6cf-3dae-45e0-9d35-61e4f8ed5d18) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/58e328aab60aa94aab4d4c68b2f69011cd7bac8f/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 80 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78537dfd-d6f5-4838-99a4-182bdce7a17b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e4e41f8839355871d2fde286a8435268bae7af58/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8c5f2fa6-f0eb-4ad3-a2ff-7b9da088f3ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-updates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e4e41f8839355871d2fde286a8435268bae7af58/msteams-platform%2Fresources%2Fteams-updates.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c2792076-eb10-4cfd-b5a0-421853ee7ec0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e4e41f8839355871d2fde286a8435268bae7af58/msteams-platform%2Fresources%2Ftroubleshoot.md) | 84 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1041547c-ae00-4356-88b2-74f6f66d2b35) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e4e41f8839355871d2fde286a8435268bae7af58/msteams-platform%2Fsamples%2Fapp-templates.md) | 86 | 104 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b8a45f2-e111-4773-a29c-1697fa0a6b7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-controls-limitations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e4e41f8839355871d2fde286a8435268bae7af58/msteams-platform%2Fsamples%2Fcollaboration-controls-limitations.md) | 84 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5395973-fd69-4736-b47c-5d8afa583f58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/configure-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e4e41f8839355871d2fde286a8435268bae7af58/msteams-platform%2Fsamples%2Fconfigure-tasks.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d75c5a45-0312-45ad-a754-9e55f7d6c10e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-table-entity-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e4e41f8839355871d2fde286a8435268bae7af58/msteams-platform%2Fsamples%2Fvirtual-table-entity-references.md) | 80 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1203e808-05c4-4aac-8e4a-1a2de2da7d48) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-msg-ext-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e4e41f8839355871d2fde286a8435268bae7af58/msteams-platform%2Fsbs-api-msg-ext-ttk.yml) | 80 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f35550f3-e6a8-4d81-911e-dece07f1251b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e4e41f8839355871d2fde286a8435268bae7af58/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 81 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/047a1384-1fe5-4e7f-96c7-a47e80825d34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e4e41f8839355871d2fde286a8435268bae7af58/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 80 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b573f8b4-b2c5-4e23-9a5a-ecf7350b3c9d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4cb2395595fc5ce0e53e9aef43da8a5265ccf1d/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f66faa05-2005-4c02-a9ed-d72b3c5eb611) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-updates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4cb2395595fc5ce0e53e9aef43da8a5265ccf1d/msteams-platform%2Fresources%2Fteams-updates.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f53c091-5a40-4142-bd45-62e4783c2378) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4cb2395595fc5ce0e53e9aef43da8a5265ccf1d/msteams-platform%2Fresources%2Ftroubleshoot.md) | 84 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6dd212c2-7dd0-4605-a3d1-3570d95ae908) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4cb2395595fc5ce0e53e9aef43da8a5265ccf1d/msteams-platform%2Fsamples%2Fapp-templates.md) | 86 | 104 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cfbab2af-2bdd-48fa-b6cf-f149c67dbb05) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-controls-limitations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4cb2395595fc5ce0e53e9aef43da8a5265ccf1d/msteams-platform%2Fsamples%2Fcollaboration-controls-limitations.md) | 84 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7049a9d7-4425-4e7f-b65b-188d5be4eae7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/configure-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4cb2395595fc5ce0e53e9aef43da8a5265ccf1d/msteams-platform%2Fsamples%2Fconfigure-tasks.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2ad46fa-242d-49f5-b0dc-46d826cf806e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-table-entity-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a4cb2395595fc5ce0e53e9aef43da8a5265ccf1d/msteams-platform%2Fsamples%2Fvirtual-table-entity-references.md) | 80 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b63e374f-17f3-4868-9b35-9e41d45bf5a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-msg-ext-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a4cb2395595fc5ce0e53e9aef43da8a5265ccf1d/msteams-platform%2Fsbs-api-msg-ext-ttk.yml) | 80 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7f2f3c1-b342-4fe3-83e3-504b87f7753d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a4cb2395595fc5ce0e53e9aef43da8a5265ccf1d/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 81 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95d91d83-60b8-46c4-a577-ade21d6d5146) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a4cb2395595fc5ce0e53e9aef43da8a5265ccf1d/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 80 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21ac0c8c-52dc-4993-95f4-431e31d6e065) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdc37936b3c3d202e7507bd3796092a6e2409d46/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd47ef1e-2b0e-4321-b50a-cd08b82f9774) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-updates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdc37936b3c3d202e7507bd3796092a6e2409d46/msteams-platform%2Fresources%2Fteams-updates.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bbeecf4-a846-422e-95a0-a2ebc0bfe637) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdc37936b3c3d202e7507bd3796092a6e2409d46/msteams-platform%2Fresources%2Ftroubleshoot.md) | 84 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a5603b65-f693-4b68-9f7d-df6c420619d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdc37936b3c3d202e7507bd3796092a6e2409d46/msteams-platform%2Fsamples%2Fapp-templates.md) | 86 | 104 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5da5310-f97f-415f-b431-bf87c5f60895) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-controls-limitations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdc37936b3c3d202e7507bd3796092a6e2409d46/msteams-platform%2Fsamples%2Fcollaboration-controls-limitations.md) | 84 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f942dc28-2184-4411-af21-faec39c3d1bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/configure-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdc37936b3c3d202e7507bd3796092a6e2409d46/msteams-platform%2Fsamples%2Fconfigure-tasks.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f01f276-026e-4eff-bb0b-8b70058b9980) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-table-entity-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fdc37936b3c3d202e7507bd3796092a6e2409d46/msteams-platform%2Fsamples%2Fvirtual-table-entity-references.md) | 80 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cba1867-f744-4f97-b7ec-7e0d874d14d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-msg-ext-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fdc37936b3c3d202e7507bd3796092a6e2409d46/msteams-platform%2Fsbs-api-msg-ext-ttk.yml) | 80 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/248fd3ba-dea8-4737-8f17-6e70a2b76aae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fdc37936b3c3d202e7507bd3796092a6e2409d46/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 81 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a645e588-f19d-4661-a1d1-3e52392b722e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/fdc37936b3c3d202e7507bd3796092a6e2409d46/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 80 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5cb8e1db-289e-4928-9de8-df52feb7e8dd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-sdhakshina — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/teams-contributor-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c05bf5b07d85307a7f4d2b5ec83c8edec4034bd2/msteams-platform%2Fresources%2Fteams-contributor-reference.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc92ec0d-bbb3-4156-9a33-69054038466f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-updates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c05bf5b07d85307a7f4d2b5ec83c8edec4034bd2/msteams-platform%2Fresources%2Fteams-updates.md) | 95 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28fe2928-32eb-4fcf-bcf4-f22ade7af37f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/troubleshoot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c05bf5b07d85307a7f4d2b5ec83c8edec4034bd2/msteams-platform%2Fresources%2Ftroubleshoot.md) | 84 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70aa9648-d3a9-430b-a3ae-bbd02300e1f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c05bf5b07d85307a7f4d2b5ec83c8edec4034bd2/msteams-platform%2Fsamples%2Fapp-templates.md) | 86 | 104 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f48cf2f-bb77-4bbd-8b35-2bdaf1b4ed66) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-controls-limitations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c05bf5b07d85307a7f4d2b5ec83c8edec4034bd2/msteams-platform%2Fsamples%2Fcollaboration-controls-limitations.md) | 84 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/147c88d2-dfc3-40e7-a8c4-50add7b78ac0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/configure-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c05bf5b07d85307a7f4d2b5ec83c8edec4034bd2/msteams-platform%2Fsamples%2Fconfigure-tasks.md) | 89 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc4bd7a9-8ea1-4634-a538-5bb892497ad9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-table-entity-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c05bf5b07d85307a7f4d2b5ec83c8edec4034bd2/msteams-platform%2Fsamples%2Fvirtual-table-entity-references.md) | 80 | 93 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8127594-4e6e-4859-801a-17098c7bcbba) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-api-msg-ext-ttk.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c05bf5b07d85307a7f4d2b5ec83c8edec4034bd2/msteams-platform%2Fsbs-api-msg-ext-ttk.yml) | 80 | 76 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e36e0d3-15b0-4fa5-bba2-741e927936fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c05bf5b07d85307a7f4d2b5ec83c8edec4034bd2/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 81 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/274232be-f294-41e2-9fc5-efeefd4df3d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c05bf5b07d85307a7f4d2b5ec83c8edec4034bd2/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 80 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e363bf95-7f91-48aa-bc17-6a3d98abf55a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
