### PR TITLE
Update office-store-appro

### PR DESCRIPTION
**Pull request by prkosh**

### CODE REVIEW

**Comment by prkosh** [comment]
1. Added the point on the app to be Whitelisted by Teamsubm@microsoft.com
2. Edited Sign out recommendation

**Comment by o365devx** [comment]
Docs Build status updates of commit _[6435228](https://github.com/prkosh/msteams-docs/pull/829/commits/6435228b29cc25b9abac18e9e12b4334824d3c21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/publishing/office-store-approval.md](https://github.com/prkosh/msteams-docs/blob/patch-3/msteams-platform/publishing/office-store-approval.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C25%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201907250500364039-829%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=A4pwWxhBADk7u3iyGpqUgDaIvuXaxUH6mfEsw5ncRds%3D&st=2019-07-25T04%3A56%3A42Z&se=2019-08-25T05%3A01%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clearab** [comment]
Moving to a branch and a single PR with additional changes.

**Comment by prkosh** [comment]
hey Andrew - please let me know when all the changes are published. Will share it with the OCP and Partners

**Comment by clearab** [comment]
Hi - just published today

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
