### PR TITLE
[Doc Improvement][Extend Teams apps across Microsoft 365 see also]

### PR DESCRIPTION
**Pull request by v-jganga**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9dc61fe38da9e60735043729c0eda69af70ede62/msteams-platform%2Fm365-apps%2Foverview.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8506f4b3-8612-49d8-a50c-ae33cade60cd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/258f9a001079244757e2672ab755fef2d3fe4261/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 98 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2ba8ddfa-a402-44a6-9473-19cd5847b5e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/258f9a001079244757e2672ab755fef2d3fe4261/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49194449-4a5a-4fb6-9670-de32cd1daae6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/258f9a001079244757e2672ab755fef2d3fe4261/msteams-platform%2Fm365-apps%2Foverview.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/488a8396-4a0f-45e8-b002-dacbfbbd3412) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/258f9a001079244757e2672ab755fef2d3fe4261/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 92 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19205398-df45-43f5-b00b-fca50a0ac659) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/258f9a001079244757e2672ab755fef2d3fe4261/msteams-platform%2Fm365-apps%2Fpublish.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0533498-2ac4-4bf3-8f53-2a3193b84b27) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5e2ada9cce316806fce7c6325613060e41f2d7a/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 98 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/686437ff-df99-4a6f-9ba9-ca71d8cda536) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5e2ada9cce316806fce7c6325613060e41f2d7a/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea7c5b18-66bc-48ce-be7a-755fc2d5f9c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5e2ada9cce316806fce7c6325613060e41f2d7a/msteams-platform%2Fm365-apps%2Foverview.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d7a4ac3-c3fa-4c96-8fed-4d9fcad1c2ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5e2ada9cce316806fce7c6325613060e41f2d7a/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 92 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0263be70-2bf8-44cd-810a-de8ff4364901) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5e2ada9cce316806fce7c6325613060e41f2d7a/msteams-platform%2Fm365-apps%2Fpublish.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bff08423-74b6-48d9-9d0d-a6ebc0cb6f74) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5e2ada9cce316806fce7c6325613060e41f2d7a/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 98 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bb58053-0b02-4222-9840-9016dfb6cd34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5e2ada9cce316806fce7c6325613060e41f2d7a/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/758704da-ff49-440f-b14f-6c2f3b03547c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5e2ada9cce316806fce7c6325613060e41f2d7a/msteams-platform%2Fm365-apps%2Foverview.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95833731-9fed-4274-ac95-edc90f0ba2d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5e2ada9cce316806fce7c6325613060e41f2d7a/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 92 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/714177d8-e4f0-4739-b919-4d382226dece) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e5e2ada9cce316806fce7c6325613060e41f2d7a/msteams-platform%2Fm365-apps%2Fpublish.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c415245-8dbc-4360-9d8d-05d91747f3d8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76486148ebb23622c39a958300bbcef377dcbb47/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 98 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1274f856-8414-445a-a601-45486dccaa28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76486148ebb23622c39a958300bbcef377dcbb47/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 95 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45034b89-14fd-4410-a51f-0b7aa6c2fc9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76486148ebb23622c39a958300bbcef377dcbb47/msteams-platform%2Fm365-apps%2Foverview.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f43c85a-2719-4edb-ab61-21e04e374202) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76486148ebb23622c39a958300bbcef377dcbb47/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 92 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2c8c08a-e923-45a3-97a5-40deb68f0a19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/76486148ebb23622c39a958300bbcef377dcbb47/msteams-platform%2Fm365-apps%2Fpublish.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c41af97-85ce-4639-95f3-a9aed761edba) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e058c9be82119365199343f13db4b18b13471f69/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 98 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f37c4c8-86c1-4abc-97a1-03cca2073d1a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e058c9be82119365199343f13db4b18b13471f69/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 95 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28c4c589-c66b-4384-ae57-896ad8ccc811) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e058c9be82119365199343f13db4b18b13471f69/msteams-platform%2Fm365-apps%2Foverview.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64bfe87e-91f7-4a5a-a5a5-a9be5feb6f21) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e058c9be82119365199343f13db4b18b13471f69/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 92 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b70ba5f-cf28-4584-867d-bd7954866942) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e058c9be82119365199343f13db4b18b13471f69/msteams-platform%2Fm365-apps%2Fpublish.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c75c2f63-b2f5-42bf-b3b2-cb98032c9102) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a76d71e8df2735a71a83627abf849b0e72394c0/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 98 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f18fbd95-acdc-4239-b84c-07c028958fbb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a76d71e8df2735a71a83627abf849b0e72394c0/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 95 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/96660783-347f-410b-ade9-085d1d65b4b4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a76d71e8df2735a71a83627abf849b0e72394c0/msteams-platform%2Fm365-apps%2Foverview.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfc09a6f-1c63-4168-859c-8d04a61ef410) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a76d71e8df2735a71a83627abf849b0e72394c0/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 92 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e3b525b-9431-475b-9899-f6265335a3fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a76d71e8df2735a71a83627abf849b0e72394c0/msteams-platform%2Fm365-apps%2Fpublish.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/abd842ee-c8b2-47a7-9bf2-29811fc390ac) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fcb8eab326f9fa417284b5a34c04bb74d117ddd/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 98 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/336bda6b-430f-4197-8139-0bc7217c97f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fcb8eab326f9fa417284b5a34c04bb74d117ddd/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 95 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c74cc4a-9607-4e19-be79-543b2b3ce8a9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fcb8eab326f9fa417284b5a34c04bb74d117ddd/msteams-platform%2Fm365-apps%2Foverview.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87de02fc-bb06-488f-9e14-dd0b2f75e444) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fcb8eab326f9fa417284b5a34c04bb74d117ddd/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 92 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c5c127c5-c5c7-4348-af01-fd65d88e2ae8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fcb8eab326f9fa417284b5a34c04bb74d117ddd/msteams-platform%2Fm365-apps%2Fpublish.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18ee0649-fba9-4a5a-a4dd-6792d105ba55) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
