### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by dneu**
Change "App Studo" -> "App Studio"

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[7573b9d](https://github.com/dneu/msteams-docs/pull/483/commits/7573b9d86c2df5a05c44c29dbfda6098b2906ad7)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[7573b9d](https://github.com/dneu/msteams-docs/pull/483/commits/7573b9d86c2df5a05c44c29dbfda6098b2906ad7)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[7573b9d](https://github.com/dneu/msteams-docs/pull/483/commits/7573b9d86c2df5a05c44c29dbfda6098b2906ad7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/bots/bots-create.md](https://github.com/dneu/msteams-docs/blob/patch-2/msteams-platform/concepts/bots/bots-create.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fconcepts%2Fbots%2Fbots-create.md)

<a name="msteams-platform%2Fconcepts%2Fbots%2Fbots-create.md"></a>
### [msteams-platform/concepts/bots/bots-create.md](https://github.com/dneu/msteams-docs/blob/patch-2/msteams-platform/concepts/bots/bots-create.md)
 - **Line 14**: **[Warning]** Invalid file link:(~/get-started/get-started).
 - **Line 20**: **[Warning]** Invalid file link:(~/get-started/get-started-app-studio).
 - **Line 36**: **[Warning]** Invalid file link:(~/resources/general/debug).
 - **Line 40**: **[Warning]** Invalid file link:(~/concepts/apps/apps-package).
 - **Line 40**: **[Warning]** Invalid file link:(~/concepts/apps/apps-upload).
 - **Line 41**: **[Warning]** Invalid file link:(~/concepts/apps/apps-overview#map-your-scenario-to-teams-capabilities).
 - **Line 41**: **[Warning]** Invalid file link:(~/concepts/tabs/tabs-overview).
 - **Line 42**: **[Warning]** Invalid file link:(~/publishing/apps-publish#appsource).
 - **Line 42**: **[Warning]** Invalid file link:(~/publishing/apps-publish#microsoft-teams-tenant-app-catalog).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903051539481090-483%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=IFe55VoWR7TvHEPwGAJS4nOjROtHl0WHzRx7Gu9mSJw%3D&st=2019-03-05T15%3A36%3A00Z&se=2019-04-05T15%3A41%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[9c5339c](https://github.com/dneu/msteams-docs/pull/483/commits/9c5339c7aa7183a8dbd671427e8946be2d873403)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[9c5339c](https://github.com/dneu/msteams-docs/pull/483/commits/9c5339c7aa7183a8dbd671427e8946be2d873403)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[9c5339c](https://github.com/dneu/msteams-docs/pull/483/commits/9c5339c7aa7183a8dbd671427e8946be2d873403)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/bots/bots-create.md](https://github.com/dneu/msteams-docs/blob/patch-2/msteams-platform/concepts/bots/bots-create.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fconcepts%2Fbots%2Fbots-create.md)

<a name="msteams-platform%2Fconcepts%2Fbots%2Fbots-create.md"></a>
### [msteams-platform/concepts/bots/bots-create.md](https://github.com/dneu/msteams-docs/blob/patch-2/msteams-platform/concepts/bots/bots-create.md)
 - **Line 36**: **[Warning]** Invalid file link:(~/resources/general/debug).
 - **Line 41**: **[Warning]** Illegal link: `[other capabilities](~/concepts/apps/apps-overview.md#map-your-scenario-to-teams-capabilities)` -- missing bookmark. The file concepts/apps/apps-overview.md doesn&#39;t contain a bookmark named map-your-scenario-to-teams-capabilities.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903051808559740-483%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Dugq93pOn6rLJubmMuCJ89XgyAzT%2Fo%2BAqIUE4kQYbw4%3D&st=2019-03-05T18%3A05%3A05Z&se=2019-04-05T18%3A10%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[ce76736](https://github.com/dneu/msteams-docs/pull/483/commits/ce767363ad73dfe783a0cd1b94e1580b00591cb3)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[ce76736](https://github.com/dneu/msteams-docs/pull/483/commits/ce767363ad73dfe783a0cd1b94e1580b00591cb3)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[ce76736](https://github.com/dneu/msteams-docs/pull/483/commits/ce767363ad73dfe783a0cd1b94e1580b00591cb3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/bots/bots-create.md](https://github.com/dneu/msteams-docs/blob/patch-2/msteams-platform/concepts/bots/bots-create.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903051818327164-483%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GF27Z4LvCbe5llUPUsbT1t%2F%2FVMIm5pEJp6VSk%2BWWaZU%3D&st=2019-03-05T18%3A14%3A41Z&se=2019-04-05T18%3A19%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clearab** [comment]
Thanks!

**Pull request merged**
