### PR TITLE
[Doc Improvement][Enhancing images as per guidelines 2][2445172]

### PR DESCRIPTION
**Pull request by v-psambrani**

### CODE REVIEW

**Comment by ashishguptaiitb** [comment]
Hi @v-psambrani , @v-habibaumme , please safekeep the original, high resolution images before downsampling.

Also, some of the mobile screenshots can be further reduced in size. Those are pretty long (vertically) and still occupy entire page when scrolling the article.

**Comment by ashishguptaiitb** [comment]
The image mobile-add-during-meeting.png is still too large. The article requires 1 page scroll just to scroll past the screenshot. I believe it can be downsampled further or it can be updated.

**Comment by ashishguptaiitb** [comment]
To preview how the updated images look in the article, see https://review.docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/design/designing-apps-in-meetings?branch=pr-en-us-6138 

@v-habibaumme , @v-psambrani

**Comment by ashishguptaiitb** [comment]
Please re-look at `add-mex-app.png`. Are all areas of Store that is displayed required in this screenshot?

@v-psambrani , @v-habibaumme

**Comment by v-psambrani** [comment]
> The image `mobile-add-during-meeting.png` is still too large. The article requires 1 page scroll just to scroll past the screenshot. I believe it can be downsampled further or it can be updated.
> 
> @v-habibaumme , @v-psambrani

Resolved

**Comment by v-psambrani** [comment]
> Same comment as above for `mobile-use-in-meeting-dialog.png` image.

Resolved

**Comment by v-psambrani** [comment]
> Please re-look at `add-mex-app.png`. Shall we display the visible-as-of-now Store UI in this screenshot?
> 
> @v-psambrani , @v-habibaumme

We were unable to take that screenshot now.

**Review by ashishguptaiitb — APPROVED** [review]

**Pull request merged**
