### PR TITLE
[Doc Improvement][Review collaboration controls][2645610]

### PR DESCRIPTION
**Pull request by v-habibaumme**
Reviewing and editing the docs as per the standards.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d16dc35a205830bde4f1896e692f598cbe41ba1f/msteams-platform%2Fsamples%2Fapp-templates.md) | 91 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e331068-d3cc-41e9-a02b-cfc25a4b92e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-controls-limitations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d16dc35a205830bde4f1896e692f598cbe41ba1f/msteams-platform%2Fsamples%2Fcollaboration-controls-limitations.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/703bc255-95ac-4688-a187-498d670623d5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9325c2dba245c316122922ba700dc9abb4e4acb0/msteams-platform%2Fsamples%2Fapp-templates.md) | 91 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5dc753f-174f-4089-be18-8f6f4b78d6eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-controls-limitations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9325c2dba245c316122922ba700dc9abb4e4acb0/msteams-platform%2Fsamples%2Fcollaboration-controls-limitations.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a3bd40c-df74-4f6c-9875-f33d73f14db7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd2911e4c798313a2cdd76f3f4154ab7ddad09d9/msteams-platform%2Fsamples%2Fapp-templates.md) | 91 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ee6707a-e31f-4f09-bd63-c2088be1b5f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-controls-limitations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd2911e4c798313a2cdd76f3f4154ab7ddad09d9/msteams-platform%2Fsamples%2Fcollaboration-controls-limitations.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3a945d8-2f1c-4a6c-b503-632a88a04f06) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-table-entity-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd2911e4c798313a2cdd76f3f4154ab7ddad09d9/msteams-platform%2Fsamples%2Fvirtual-table-entity-references.md) | 91 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b078a9be-a4e7-45cd-aa15-93acede726da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd2911e4c798313a2cdd76f3f4154ab7ddad09d9/msteams-platform%2Fsamples%2Fvirtual-tables-api.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/514a08da-1d24-4c5f-9f39-a429ba9f773e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-for-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cd2911e4c798313a2cdd76f3f4154ab7ddad09d9/msteams-platform%2Fsamples%2Fvirtual-tables-for-tasks.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bba8a75-27a9-43a3-a9fd-2ee5deeb1782) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df4eda8b921d5810fe695dba3019b7a1356c7f9a/msteams-platform%2Fsamples%2Fapp-templates.md) | 91 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1b86c27-3f93-45c9-8ea2-c44aa18d9c58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-controls-limitations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df4eda8b921d5810fe695dba3019b7a1356c7f9a/msteams-platform%2Fsamples%2Fcollaboration-controls-limitations.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75b081f0-7920-408b-85e1-13c45449cb64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-table-entity-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df4eda8b921d5810fe695dba3019b7a1356c7f9a/msteams-platform%2Fsamples%2Fvirtual-table-entity-references.md) | 91 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f6a0f64-0b8c-4aff-adc0-92ee54afd078) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df4eda8b921d5810fe695dba3019b7a1356c7f9a/msteams-platform%2Fsamples%2Fvirtual-tables-api.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c01bc9ba-1abe-4a95-a334-1c3f983c236a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-for-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/df4eda8b921d5810fe695dba3019b7a1356c7f9a/msteams-platform%2Fsamples%2Fvirtual-tables-for-tasks.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec516ba3-d5cb-47b4-8ce6-26c3c1edae40) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4d51d57a0334b7a6fe78d72b8775b00eba83c36/msteams-platform%2Fsamples%2Fapp-templates.md) | 91 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ecee5f5-ad7a-4112-95d9-1dd4b427342a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-controls-limitations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4d51d57a0334b7a6fe78d72b8775b00eba83c36/msteams-platform%2Fsamples%2Fcollaboration-controls-limitations.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cf2f443-306a-40ca-85b4-c907927a8ef2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-table-entity-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4d51d57a0334b7a6fe78d72b8775b00eba83c36/msteams-platform%2Fsamples%2Fvirtual-table-entity-references.md) | 91 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef2022b5-2032-4cdd-8063-72ad91d6b6a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4d51d57a0334b7a6fe78d72b8775b00eba83c36/msteams-platform%2Fsamples%2Fvirtual-tables-api.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bad12d42-447c-4fbd-93c4-60e43c7f9dcd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-for-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4d51d57a0334b7a6fe78d72b8775b00eba83c36/msteams-platform%2Fsamples%2Fvirtual-tables-for-tasks.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/091d3f28-db13-44ee-880a-a4f0b0459662) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/faf207f05b5816e3e2dc08ffb12debe9323444a4/msteams-platform%2Fsamples%2Fapp-templates.md) | 91 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/138af278-00d5-4af1-b821-14e413dcf1e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-controls-limitations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/faf207f05b5816e3e2dc08ffb12debe9323444a4/msteams-platform%2Fsamples%2Fcollaboration-controls-limitations.md) | 89 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a55ef62e-e016-4a64-bd8b-1400cd4ccfbd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/configure-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/faf207f05b5816e3e2dc08ffb12debe9323444a4/msteams-platform%2Fsamples%2Fconfigure-tasks.md) | 87 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6d7ea1f-c810-42b9-9fc9-8889b3e97da4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-table-entity-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/faf207f05b5816e3e2dc08ffb12debe9323444a4/msteams-platform%2Fsamples%2Fvirtual-table-entity-references.md) | 91 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/434d70ed-3fe1-4152-9575-95114d964f4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/faf207f05b5816e3e2dc08ffb12debe9323444a4/msteams-platform%2Fsamples%2Fvirtual-tables-api.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d6935cf-4e59-45db-98f2-07b62b012423) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-for-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/faf207f05b5816e3e2dc08ffb12debe9323444a4/msteams-platform%2Fsamples%2Fvirtual-tables-for-tasks.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1d82046-e580-4895-bc80-864e70d1be76) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fa740b88396afcfac5051ad59f9daf303e2731e/msteams-platform%2Fsamples%2Fapp-templates.md) | 91 | 47 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53cc6e5f-23f6-40b6-b64f-a5c1428156fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/collaboration-controls-limitations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fa740b88396afcfac5051ad59f9daf303e2731e/msteams-platform%2Fsamples%2Fcollaboration-controls-limitations.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75ed0bf8-3539-4d70-babc-9e086bc04e8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/configure-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fa740b88396afcfac5051ad59f9daf303e2731e/msteams-platform%2Fsamples%2Fconfigure-tasks.md) | 90 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54f4ec35-90a8-49dc-a20a-96317c56d4ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-table-entity-references.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fa740b88396afcfac5051ad59f9daf303e2731e/msteams-platform%2Fsamples%2Fvirtual-table-entity-references.md) | 91 | 39 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/937b1b05-444a-4a69-88e3-f00b84e5aa7d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-api.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fa740b88396afcfac5051ad59f9daf303e2731e/msteams-platform%2Fsamples%2Fvirtual-tables-api.md) | 90 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90f46cb4-65ed-4350-ad11-ba7f74ba0bad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/virtual-tables-for-tasks.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8fa740b88396afcfac5051ad59f9daf303e2731e/msteams-platform%2Fsamples%2Fvirtual-tables-for-tasks.md) | 92 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51f98aeb-e35b-4cae-ac82-4690458771fb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
