### PR TITLE
[Doc enhancement][Add-links-to-auto-answer-teams-calls][2309517]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/call-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1aa528279bb29f452f3c960eb6ce143659f4978e/msteams-platform/bots/calls-and-meetings/call-notifications.md) | 87 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/efc4c004-f8fe-435e-9c00-557e258c58ea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/call-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a93d0f061d7abe3e1afa904e44361fdbb2f644d1/msteams-platform/bots/calls-and-meetings/call-notifications.md) | 87 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3175761e-1db0-45e0-94a9-36618694300a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/call-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbc2ce56311a7fd5e7df444d6617121684beaa02/msteams-platform/bots/calls-and-meetings/call-notifications.md) | 87 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/791bb832-b5ff-4481-8caa-a3e94c73de9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbc2ce56311a7fd5e7df444d6617121684beaa02/msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9f0c548f-4fd2-4a80-9a82-36aa4ca7813c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]
Approved

**Pull request merged**
