### PR TITLE
[Doc improvement][SEO9 metatitle update][3876690]

### PR DESCRIPTION
**Pull request by v-ramyas5**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/promote-app-adoption.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2909b81c4d7df749707c1b16e740de92c649d3ca/msteams-platform%2Fpromote-app-adoption.md) | 90 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4f6596a-8a36-4e92-84a6-b90de489117b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/qsg-bot-configuration-experience.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2909b81c4d7df749707c1b16e740de92c649d3ca/msteams-platform%2Fqsg-bot-configuration-experience.yml) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2987745e-1de3-4aea-b28f-cab1674c256a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2909b81c4d7df749707c1b16e740de92c649d3ca/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-channel.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85c635ea-1162-49e7-ae49-81b67a46a765) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2909b81c4d7df749707c1b16e740de92c649d3ca/msteams-platform%2Fresources%2Fbot-v3%2Fbots-context.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49e58b93-2c41-48cb-9664-96fafd67d2c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-text-formats.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2909b81c4d7df749707c1b16e740de92c649d3ca/msteams-platform%2Fresources%2Fbot-v3%2Fbots-text-formats.md) | 92 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a895ce7-ecdc-42e7-9666-a3704358eec2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2909b81c4d7df749707c1b16e740de92c649d3ca/msteams-platform%2Fresources%2Fdev-preview%2Fdeveloper-preview-intro.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90092e6d-392e-4898-a7d3-cab017c20030) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2909b81c4d7df749707c1b16e740de92c649d3ca/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a7e6f12-fea5-475b-b21d-762e17c8357f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2909b81c4d7df749707c1b16e740de92c649d3ca/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 132 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db155012-3942-4db3-9402-cb947907e8fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2909b81c4d7df749707c1b16e740de92c649d3ca/msteams-platform%2Fresources%2Fteam-chat-member-api-changes.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dbbc7f1b-9a0a-4808-bb08-ecb9688bb84f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-updates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2909b81c4d7df749707c1b16e740de92c649d3ca/msteams-platform%2Fresources%2Fteams-updates.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3f6496f-93a8-47bb-a0c4-8b6dab57ccea) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/promote-app-adoption.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e74341494aadca96da98e015a52821652338a106/msteams-platform%2Fpromote-app-adoption.md) | 90 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e41f759b-1d7c-45c8-800a-c1b767869f5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/qsg-bot-configuration-experience.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e74341494aadca96da98e015a52821652338a106/msteams-platform%2Fqsg-bot-configuration-experience.yml) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ef69eda-38bd-4c11-a041-014700351719) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e74341494aadca96da98e015a52821652338a106/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-channel.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e302a0d9-2bab-4c32-96b0-056153b7ccb0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e74341494aadca96da98e015a52821652338a106/msteams-platform%2Fresources%2Fbot-v3%2Fbots-context.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d125e1d6-6858-422e-93b2-d1297d507b73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-text-formats.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e74341494aadca96da98e015a52821652338a106/msteams-platform%2Fresources%2Fbot-v3%2Fbots-text-formats.md) | 92 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbd0f3fe-07e2-48cf-be29-4971543404e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e74341494aadca96da98e015a52821652338a106/msteams-platform%2Fresources%2Fdev-preview%2Fdeveloper-preview-intro.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed03e6d5-3438-4622-8652-6919d21237e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e74341494aadca96da98e015a52821652338a106/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9acd765f-4474-43ec-a509-6032573c6077) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e74341494aadca96da98e015a52821652338a106/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 132 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/308253f5-2b10-465b-bd2f-817e1fe071bf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e74341494aadca96da98e015a52821652338a106/msteams-platform%2Fresources%2Fteam-chat-member-api-changes.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c6f2896-17a5-4d7c-bbf3-6500415a787a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-updates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e74341494aadca96da98e015a52821652338a106/msteams-platform%2Fresources%2Fteams-updates.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f707f801-bbc5-4c6a-a3bb-cd15ff0c4262) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/promote-app-adoption.md](https://github.com/MicrosoftDocs/msteams-docs/blob/331f29ac382f5507c1634ad4990f0bae44037cff/msteams-platform%2Fpromote-app-adoption.md) | 90 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1021df82-face-4021-9083-096496fb5c00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/qsg-bot-configuration-experience.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/331f29ac382f5507c1634ad4990f0bae44037cff/msteams-platform%2Fqsg-bot-configuration-experience.yml) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bdb9ac6a-70af-4545-bec3-394252aa31f7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/331f29ac382f5507c1634ad4990f0bae44037cff/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-channel.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8faa4ea-6a61-4485-b867-a9c9781c2436) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/331f29ac382f5507c1634ad4990f0bae44037cff/msteams-platform%2Fresources%2Fbot-v3%2Fbots-context.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05065551-4d46-49b0-9a50-d9815ffb571f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-text-formats.md](https://github.com/MicrosoftDocs/msteams-docs/blob/331f29ac382f5507c1634ad4990f0bae44037cff/msteams-platform%2Fresources%2Fbot-v3%2Fbots-text-formats.md) | 92 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06b93075-40c5-4be5-96c1-893819fb5139) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/331f29ac382f5507c1634ad4990f0bae44037cff/msteams-platform%2Fresources%2Fdev-preview%2Fdeveloper-preview-intro.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e60b2366-2e4b-4489-baee-ba62bb114260) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/331f29ac382f5507c1634ad4990f0bae44037cff/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f5742f34-000a-4d1c-8486-c96d89f0d49d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/331f29ac382f5507c1634ad4990f0bae44037cff/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 132 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8729154-33b2-4bc1-bb55-5c105f964396) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/331f29ac382f5507c1634ad4990f0bae44037cff/msteams-platform%2Fresources%2Fteam-chat-member-api-changes.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/564f8ba5-d000-419e-b25a-a245f59fba1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-updates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/331f29ac382f5507c1634ad4990f0bae44037cff/msteams-platform%2Fresources%2Fteams-updates.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2ca625c-6c89-4a30-83df-d58a6c70ba69) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/promote-app-adoption.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4467209cbe16f2537c92afd09be205f44d1adf21/msteams-platform%2Fpromote-app-adoption.md) | 90 | 52 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c548e251-4788-4a15-9710-ba8cfd8f0f6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/qsg-bot-configuration-experience.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4467209cbe16f2537c92afd09be205f44d1adf21/msteams-platform%2Fqsg-bot-configuration-experience.yml) | 84 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b7d468d-14c4-4085-b058-cf74b24ee781) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bot-conversations/bots-conv-channel.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4467209cbe16f2537c92afd09be205f44d1adf21/msteams-platform%2Fresources%2Fbot-v3%2Fbot-conversations%2Fbots-conv-channel.md) | 89 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36e9766e-22b4-40a6-860d-4e04d3c8c10a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4467209cbe16f2537c92afd09be205f44d1adf21/msteams-platform%2Fresources%2Fbot-v3%2Fbots-context.md) | 92 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21db9f40-8f47-4d59-a73d-ca9332e53a4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-text-formats.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4467209cbe16f2537c92afd09be205f44d1adf21/msteams-platform%2Fresources%2Fbot-v3%2Fbots-text-formats.md) | 92 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/79310830-95e3-45f2-b43a-8c5b7a64a712) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4467209cbe16f2537c92afd09be205f44d1adf21/msteams-platform%2Fresources%2Fdev-preview%2Fdeveloper-preview-intro.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eaff63b5-77b6-4c3c-ae2e-820090263ef0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4467209cbe16f2537c92afd09be205f44d1adf21/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 89 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d8297c5-0344-4691-8529-7b65e0a586b9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4467209cbe16f2537c92afd09be205f44d1adf21/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 132 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/804cb4a8-4eda-437f-b0ae-6f0cb0ef9a2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4467209cbe16f2537c92afd09be205f44d1adf21/msteams-platform%2Fresources%2Fteam-chat-member-api-changes.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6078ed42-0303-4518-a35e-d39f3950baf1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/teams-updates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4467209cbe16f2537c92afd09be205f44d1adf21/msteams-platform%2Fresources%2Fteams-updates.md) | 91 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df346908-1f59-4fb9-a9b3-f9ec82aff0f8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
