### PR TITLE
[Doc Improvement][Update create a partner center account][2607350]

### PR DESCRIPTION
**Pull request by v-ypalikila**
Redirected Update Apple  Store Connect Team ID on Partner Center to to Teams store submission article.

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2055ea1b96976d9cb32e662e32d99665555ddd22/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-partner-center-dev-account.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/136e67ee-894b-45d8-a5dc-e85a9a4984cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2055ea1b96976d9cb32e662e32d99665555ddd22/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d739d7e2-ac96-441d-9aa0-ce8bf050d44e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e3f82c02f283b753647fd603c078aa6305101db/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-partner-center-dev-account.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b5539ad-66ab-4ad0-b3ae-62057acfbce1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3e3f82c02f283b753647fd603c078aa6305101db/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d99f11c9-9df7-40d1-a360-a629c05a9829) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0abe36605516d8c920acdc27d45114e0d18d57fd/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-partner-center-dev-account.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b215bbe6-61c7-4aa2-9474-3a0d9fbe7e4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0abe36605516d8c920acdc27d45114e0d18d57fd/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 97 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/798baf79-c0a2-404e-a842-80dea1ee4c9a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/34017ecd8176fb01d63866cefcd9840de40369c3/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf6529a7-3c15-4d28-aed6-032b5314e7a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md](https://github.com/MicrosoftDocs/msteams-docs/blob/34017ecd8176fb01d63866cefcd9840de40369c3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-partner-center-dev-account.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5e7766e-38fa-44b9-aeb7-bf3cfb79eeaf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/34017ecd8176fb01d63866cefcd9840de40369c3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 99 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33ec4eb0-1a93-4cca-a9de-5e6556e3aa95) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/update-apple-store-team-connect-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/34017ecd8176fb01d63866cefcd9840de40369c3/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fupdate-apple-store-team-connect-id.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a48acf47-475c-4c8c-af2e-60a88833348f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/34017ecd8176fb01d63866cefcd9840de40369c3/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a516f6e2-ebcc-44ba-8e6d-c045a86c4c80) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/68a1c9d33400873f3b32088c61a0630d4e0677a6/msteams-platform%2FTOC.yml) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1ae0bc1-8501-45ad-87df-0ddbce087187) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-links.md](https://github.com/MicrosoftDocs/msteams-docs/blob/68a1c9d33400873f3b32088c61a0630d4e0677a6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-links.md) | 92 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b47c3bb-0316-45be-aef8-1fc99179db24) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/create-partner-center-dev-account.md](https://github.com/MicrosoftDocs/msteams-docs/blob/68a1c9d33400873f3b32088c61a0630d4e0677a6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fcreate-partner-center-dev-account.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29b9cd8c-992a-45cb-9ea9-dbdf64349f91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/submission-checklist.md](https://github.com/MicrosoftDocs/msteams-docs/blob/68a1c9d33400873f3b32088c61a0630d4e0677a6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fsubmission-checklist.md) | 99 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0fce83df-5767-4396-8b43-07843af42989) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/update-apple-store-team-connect-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/68a1c9d33400873f3b32088c61a0630d4e0677a6/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Fupdate-apple-store-team-connect-id.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0006003f-89ef-4367-8515-b05fcc58cd5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/mstdd-landing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/68a1c9d33400873f3b32088c61a0630d4e0677a6/msteams-platform%2Fmstdd-landing.yml) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce71847b-a2ba-4634-9001-64590b939044) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
