### PR TITLE
[Doc Improvement][SEO meta title update 2][3947112]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/call-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea167734db9bf979d9984fd7fd37f96dc2764ae8/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcall-notifications.md) | 86 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97350531-3e0d-450d-89fd-7b43eca7d44b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea167734db9bf979d9984fd7fd37f96dc2764ae8/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5e9f30c-af3a-42f6-aa83-76b41a69cd5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea167734db9bf979d9984fd7fd37f96dc2764ae8/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 85 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2383f0a2-5164-449b-903a-8e77cfaa1193) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea167734db9bf979d9984fd7fd37f96dc2764ae8/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/610f35d3-8fba-4fdc-ba22-137ae39f2436) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/app-growth-lifecycle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea167734db9bf979d9984fd7fd37f96dc2764ae8/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fapp-growth-lifecycle.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e8a7735-cb49-49cc-a6a4-a60bc78b64ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea167734db9bf979d9984fd7fd37f96dc2764ae8/msteams-platform%2Fm365-apps%2Factions-in-m365.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/45152f48-780c-49c3-a5c3-edca503302ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/build-actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea167734db9bf979d9984fd7fd37f96dc2764ae8/msteams-platform%2Fm365-apps%2Fbuild-actions-in-m365.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb4b51fe-bd2e-42f3-b686-ec7b5ebb0d6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ea167734db9bf979d9984fd7fd37f96dc2764ae8/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 81 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4b07b46-0a9b-4e1b-8fdc-0ba89528e1cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ea167734db9bf979d9984fd7fd37f96dc2764ae8/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d45d747c-9f8a-45d8-87f3-434bd0be9c68) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea167734db9bf979d9984fd7fd37f96dc2764ae8/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d54f3a62-980d-49da-8346-d1231f8cb3ce) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — DISMISSED** [review]

**Review by v-sdhakshina — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/call-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7de9d1356071cd32d5e3c9e0b730004894be4253/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcall-notifications.md) | 86 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87fa644e-eac3-4cf0-951c-289eb1ee32ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7de9d1356071cd32d5e3c9e0b730004894be4253/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf15b7a5-88cc-4ff6-9e9d-0739c00b7e06) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7de9d1356071cd32d5e3c9e0b730004894be4253/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 85 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34af5185-a148-4579-a32d-0a58c2cddc7b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7de9d1356071cd32d5e3c9e0b730004894be4253/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05f0dda3-cb6c-443d-9331-8ba9b0645017) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/app-growth-lifecycle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7de9d1356071cd32d5e3c9e0b730004894be4253/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fapp-growth-lifecycle.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4797520-7fa2-43f8-a393-5bb761912b98) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7de9d1356071cd32d5e3c9e0b730004894be4253/msteams-platform%2Fm365-apps%2Factions-in-m365.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2e77c9bd-1b74-4c36-8020-eeda4671f321) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/build-actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7de9d1356071cd32d5e3c9e0b730004894be4253/msteams-platform%2Fm365-apps%2Fbuild-actions-in-m365.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3170d966-961c-4f7b-93d7-d9352ce013e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7de9d1356071cd32d5e3c9e0b730004894be4253/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 81 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/162bf125-e0d7-42f3-9091-c65bd07cc1a7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7de9d1356071cd32d5e3c9e0b730004894be4253/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7db324d-e43f-4066-9129-baf3fc8065fc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7de9d1356071cd32d5e3c9e0b730004894be4253/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d9249d2-151d-477a-9d91-ebe595a7cc34) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/call-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/730798a0ff8a1be4ffc949f4b45e589aabaa1804/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcall-notifications.md) | 86 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d9de400-8f8d-4910-8ff3-fea0ce60f39f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/730798a0ff8a1be4ffc949f4b45e589aabaa1804/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad47c68f-ac65-4491-ab32-579c281bf71c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/730798a0ff8a1be4ffc949f4b45e589aabaa1804/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 85 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/77e9eb9a-15c4-4b6c-ac9c-0a14204a2256) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/730798a0ff8a1be4ffc949f4b45e589aabaa1804/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b7d807b3-15d0-40f7-a4bf-87c66664a70e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/app-growth-lifecycle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/730798a0ff8a1be4ffc949f4b45e589aabaa1804/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fapp-growth-lifecycle.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b2b536b-5e79-4c4c-a319-3a20b614dc53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/730798a0ff8a1be4ffc949f4b45e589aabaa1804/msteams-platform%2Fm365-apps%2Factions-in-m365.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/948527f4-92e0-41a4-9547-ba9d5cc80de1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/build-actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/730798a0ff8a1be4ffc949f4b45e589aabaa1804/msteams-platform%2Fm365-apps%2Fbuild-actions-in-m365.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5819b37e-b063-4e93-9236-ebade9ddaae2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/730798a0ff8a1be4ffc949f4b45e589aabaa1804/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 81 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c72f96a-ac35-4c29-83ca-0eb682734a53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/730798a0ff8a1be4ffc949f4b45e589aabaa1804/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/19f01cb6-4395-46c8-ab5d-e22dc60a26da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/730798a0ff8a1be4ffc949f4b45e589aabaa1804/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98c6a3c5-5aeb-439e-831c-61a5add4645a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/call-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3259163fde2f82e1a1a3b9d9a1f5b2489588ab66/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcall-notifications.md) | 86 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3194c5c-c0d7-441e-824d-a01cbc2ab3af) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3259163fde2f82e1a1a3b9d9a1f5b2489588ab66/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/006d9130-359a-4a85-95bd-69bc1e5ab6db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/conversation-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3259163fde2f82e1a1a3b9d9a1f5b2489588ab66/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fconversation-messages.md) | 85 | 44 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3fc7a0cc-e552-4e83-bcc7-db61f183b414) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3259163fde2f82e1a1a3b9d9a1f5b2489588ab66/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fteams-developer-portal.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9100fe4-850c-48d2-bb85-c3bb92ff3ce5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/app-growth/app-growth-lifecycle.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3259163fde2f82e1a1a3b9d9a1f5b2489588ab66/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fapp-growth%2Fapp-growth-lifecycle.md) | 86 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33765c06-7aa0-4f29-99c2-5d624232483c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3259163fde2f82e1a1a3b9d9a1f5b2489588ab66/msteams-platform%2Fm365-apps%2Factions-in-m365.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/356fa624-84e4-469c-9e39-394d03dfb084) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/build-actions-in-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3259163fde2f82e1a1a3b9d9a1f5b2489588ab66/msteams-platform%2Fm365-apps%2Fbuild-actions-in-m365.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17d56fe2-e148-42c2-a9ef-90540871ca53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3259163fde2f82e1a1a3b9d9a1f5b2489588ab66/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 81 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2bc627ac-7e05-49d8-9c0c-b2ec67f36378) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-conversation-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3259163fde2f82e1a1a3b9d9a1f5b2489588ab66/msteams-platform%2Fsbs-teams-conversation-bot.yml) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9edc4ec5-9def-42df-be56-551b0f3673c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/people-picker.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3259163fde2f82e1a1a3b9d9a1f5b2489588ab66/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fpeople-picker.md) | 94 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00259db9-a3a6-424f-8615-99a182e61861) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
