### PR TITLE
[Doc Improvement][Remove pre-release instances][3916499]

### PR DESCRIPTION
**Pull request by v-kushals**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8a4543958c72d139b03ace84665925224d00eff6/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 131 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e3db49d-8324-4a62-9069-ec6d31d454fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8a4543958c72d139b03ace84665925224d00eff6/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 87 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddb1706d-99b1-4245-8c9a-c4ade6d13f76) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8a4543958c72d139b03ace84665925224d00eff6/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aaada0d0-da69-47e7-b071-d86ce24c9f2a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/617365ed4d2a6b225abdc774750b5ead0e8dd566/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 94 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/646f4a55-27c6-49df-9853-25bca935dfeb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/617365ed4d2a6b225abdc774750b5ead0e8dd566/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 131 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffc8fb1a-56a2-4637-bb34-19c6511afb94) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/617365ed4d2a6b225abdc774750b5ead0e8dd566/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 87 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5af09be7-0402-4728-9eb0-1f428a6441c5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-your-Teams-app-test-tool.md](https://github.com/MicrosoftDocs/msteams-docs/blob/617365ed4d2a6b225abdc774750b5ead0e8dd566/msteams-platform%2Ftoolkit%2Fdebug-your-Teams-app-test-tool.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/636e7fe0-9217-4ac7-959d-8475a2551e1a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/617365ed4d2a6b225abdc774750b5ead0e8dd566/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6422111e-721d-4c76-849a-37ee0222d222) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/messaging-extensions/build-bot-based-plugin.md](https://github.com/MicrosoftDocs/msteams-docs/blob/880b41888cb186e556ff8d390c5d2df79f6d9827/msteams-platform%2Fmessaging-extensions%2Fbuild-bot-based-plugin.md) | 94 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d11f236a-701d-4413-8492-810a37656b8f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/880b41888cb186e556ff8d390c5d2df79f6d9827/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 131 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1bc3c62b-4c0a-4cb9-9665-ec01124b5d46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand-plugin.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/880b41888cb186e556ff8d390c5d2df79f6d9827/msteams-platform%2Fsbs-messagingextension-searchcommand-plugin.yml) | 87 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1762c64-d48c-4025-a33a-09b02944a231) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-your-Teams-app-test-tool.md](https://github.com/MicrosoftDocs/msteams-docs/blob/880b41888cb186e556ff8d390c5d2df79f6d9827/msteams-platform%2Ftoolkit%2Fdebug-your-Teams-app-test-tool.md) | 92 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8dc8bdd7-a862-4494-af72-63660f898c77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/880b41888cb186e556ff8d390c5d2df79f6d9827/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27b4ac65-638f-4415-b568-3133b378505f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Review by v-ypalikila — APPROVED** [review]
approved.

**Pull request merged**
