### PR TITLE
[Doc Improvement][Update Tools and SDK revamp for Visual Studio]

### PR DESCRIPTION
**Pull request by v-ksar**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-teams-app-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c4556fd8dd2a50535e861f60d68b4b9c5c345a22/msteams-platform%2Ftoolkit%2Fdebug-teams-app-visual-studio.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e9de24e-bcb4-4169-9d3a-94a426713316) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/debug-teams-app-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a46cc1066efb63a509a4c8b962b38458cf12627/msteams-platform%2Ftoolkit%2Fdebug-teams-app-visual-studio.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d696013-8996-4101-b786-c9cf1e75071c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3d695d9a66ea4a7d714427b27fb3ef99bd5ec423/msteams-platform%2FTOC.yml) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa0422c0-e6a8-426f-a006-bb178af56dfa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/VS-TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d695d9a66ea4a7d714427b27fb3ef99bd5ec423/msteams-platform%2Ftoolkit%2FVS-TeamsFx-preview-and-customize-app-manifest.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6ba238aa-7396-4615-9d86-546523e3d816) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-teams-app-for-Visual-Studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d695d9a66ea4a7d714427b27fb3ef99bd5ec423/msteams-platform%2Ftoolkit%2Fcreate-new-teams-app-for-Visual-Studio.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d684f063-fad9-462d-baed-c836b58348be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-teams-app-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d695d9a66ea4a7d714427b27fb3ef99bd5ec423/msteams-platform%2Ftoolkit%2Fdebug-teams-app-visual-studio.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a579a33-6e89-4858-9d41-2d6fa38037b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy-teams-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d695d9a66ea4a7d714427b27fb3ef99bd5ec423/msteams-platform%2Ftoolkit%2Fdeploy-teams-app.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/051613a2-2b47-4616-ba6f-df124313c7e5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision-cloud-resources.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d695d9a66ea4a7d714427b27fb3ef99bd5ec423/msteams-platform%2Ftoolkit%2Fprovision-cloud-resources.md) | 97 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97809b1a-241d-46e3-9293-c173ccc9b1c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-overview-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3d695d9a66ea4a7d714427b27fb3ef99bd5ec423/msteams-platform%2Ftoolkit%2Fteams-toolkit-overview-visual-studio.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e5cb018-12ea-4751-9659-3c617cdf1d0e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/TOC.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/36ef71fecffac20546f899ea186d1b0ecb964356/msteams-platform%2FTOC.yml) | 98 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07ab2dd8-eb79-414f-b408-136764090ce6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/VS-TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/36ef71fecffac20546f899ea186d1b0ecb964356/msteams-platform%2Ftoolkit%2FVS-TeamsFx-preview-and-customize-app-manifest.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54bee686-1608-4d95-90ab-37e065fb37bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-teams-app-for-Visual-Studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/36ef71fecffac20546f899ea186d1b0ecb964356/msteams-platform%2Ftoolkit%2Fcreate-new-teams-app-for-Visual-Studio.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70f731d7-afaa-46fb-b988-20257c9dbf9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-teams-app-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/36ef71fecffac20546f899ea186d1b0ecb964356/msteams-platform%2Ftoolkit%2Fdebug-teams-app-visual-studio.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e4b8f626-63f1-4cc9-b0c8-9647d588af46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/deploy-teams-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/36ef71fecffac20546f899ea186d1b0ecb964356/msteams-platform%2Ftoolkit%2Fdeploy-teams-app.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57819b64-4cbc-4297-918f-57e5f2e73257) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/provision-cloud-resources.md](https://github.com/MicrosoftDocs/msteams-docs/blob/36ef71fecffac20546f899ea186d1b0ecb964356/msteams-platform%2Ftoolkit%2Fprovision-cloud-resources.md) | 97 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dda400b1-34d5-4f3a-ac1c-8af4fbe2abde) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-overview-visual-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/36ef71fecffac20546f899ea186d1b0ecb964356/msteams-platform%2Ftoolkit%2Fteams-toolkit-overview-visual-studio.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d85ee55c-e2e1-4d90-95cf-e669b51b5b9f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
