### PR TITLE
Doc update tab navigation

### PR DESCRIPTION
**Pull request by JoshuaPartlow**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/365bee83a1c73e8f5c052a68dd5322ecf2d91c5e/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6be2a28-ccfc-4bc4-8b71-d7ffebf42523) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-navigation.md](https://github.com/MicrosoftDocs/msteams-docs/blob/365bee83a1c73e8f5c052a68dd5322ecf2d91c5e/msteams-platform%2Ftabs%2Fhow-to%2Ftab-navigation.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b3a3865-2e2a-4c70-88ca-041316b3b9fe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c907fe1a4d44ead882d2dacfd55feb5e20af307/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24da7279-9c4e-4156-b63f-fd31263081b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-navigation.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8c907fe1a4d44ead882d2dacfd55feb5e20af307/msteams-platform%2Ftabs%2Fhow-to%2Ftab-navigation.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13f2d786-cc11-4f64-89d5-cbb166e4f964) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7a0697822a0467debbdf89b0b47308cc05184c4a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0efbc8c2-8617-491b-a365-d554fd6aaab4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-navigation.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7a0697822a0467debbdf89b0b47308cc05184c4a/msteams-platform%2Ftabs%2Fhow-to%2Ftab-navigation.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d63991f1-593a-411f-babe-520923342064) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f47b2ac4adc427395694d43ee380006ce26d5ec/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2330d4db-e92b-42cf-adb4-9f2377d028a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/tab-navigation.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0f47b2ac4adc427395694d43ee380006ce26d5ec/msteams-platform%2Ftabs%2Fhow-to%2Ftab-navigation.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e7475d7-77d7-466e-bdd9-8a58037a77b9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
