### PR TITLE
[Doc update][Message-extension-9]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2b71be502688229f84a652c7a5a5616c59dcdd5b/msteams-platform%2Findex.yml) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/951921ca-ea74-485b-9368-84017730c7de) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33b08d66f3e39f57f78f93942cd87403592b2e3b/msteams-platform%2Findex.yml) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b5210152-1151-40a9-9fe0-da64fcb89ba8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33b08d66f3e39f57f78f93942cd87403592b2e3b/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6eb029ea-7dc5-47be-8515-02310307c682) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33b08d66f3e39f57f78f93942cd87403592b2e3b/msteams-platform%2Fsbs-gs-javascript.yml) | 93 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a8a85614-d475-4e0a-858a-fcd08b64a2f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-nodejs.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33b08d66f3e39f57f78f93942cd87403592b2e3b/msteams-platform%2Fsbs-gs-nodejs.yml) | 92 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d04b80ae-a7b9-49e2-80aa-3107615175e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33b08d66f3e39f57f78f93942cd87403592b2e3b/msteams-platform%2Fsbs-meetingextension-action.yml) | 86 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c7ef1da-c82e-46c9-b5d8-f6ecaa437ca0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33b08d66f3e39f57f78f93942cd87403592b2e3b/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 84 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/882d37e4-17d7-4bfd-9db4-0f03225de3bb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/33b08d66f3e39f57f78f93942cd87403592b2e3b/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac8d860b-240c-44e1-b89e-d5f5ccfa4939) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/bots/teams-bot-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/88da1c2e6e7edb2b6072e66ace76c8087c5ffb38/msteams-platform%2Fincludes%2Fbots%2Fteams-bot-samples.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b2c4e85-4fe3-4bc8-8000-ed48ff3ab806) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/get-started-use-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/88da1c2e6e7edb2b6072e66ace76c8087c5ffb38/msteams-platform%2Fincludes%2Fget-started%2Fget-started-use-app-studio.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29a98885-ceef-4867-b14c-720c5e97ee1b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extension-command-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/88da1c2e6e7edb2b6072e66ace76c8087c5ffb38/msteams-platform%2Fincludes%2Fmessaging-extension-command-schema.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7de4d4e6-d984-40dc-93a4-43ee0be787e8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/learn-more.md](https://github.com/MicrosoftDocs/msteams-docs/blob/88da1c2e6e7edb2b6072e66ace76c8087c5ffb38/msteams-platform%2Fincludes%2Fmessaging-extensions%2Flearn-more.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92c11ec8-ffb7-46da-9e0b-a742fdae2407) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/messaging-extensions-common.md](https://github.com/MicrosoftDocs/msteams-docs/blob/88da1c2e6e7edb2b6072e66ace76c8087c5ffb38/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmessaging-extensions-common.md) | 84 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca848e78-f6e2-41cc-b704-d3bf14cc9c29) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/v3-to-v4-pointer-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/88da1c2e6e7edb2b6072e66ace76c8087c5ffb38/msteams-platform%2Fincludes%2Fv3-to-v4-pointer-me.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/317e75dd-76eb-4541-871b-1fad812f13f4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/88da1c2e6e7edb2b6072e66ace76c8087c5ffb38/msteams-platform%2Findex.yml) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ab39142-6e83-4e18-8ff8-ff9f69c7cd84) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/88da1c2e6e7edb2b6072e66ace76c8087c5ffb38/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49feca83-4044-41e2-bd75-bb03c7a034a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/88da1c2e6e7edb2b6072e66ace76c8087c5ffb38/msteams-platform%2Fsbs-gs-javascript.yml) | 93 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42505f6d-f8a8-4823-bcc3-828c6b653e63) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-nodejs.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/88da1c2e6e7edb2b6072e66ace76c8087c5ffb38/msteams-platform%2Fsbs-gs-nodejs.yml) | 92 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/206a8846-dc8d-416c-a3e2-891fb9a39da3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/88da1c2e6e7edb2b6072e66ace76c8087c5ffb38/msteams-platform%2Fsbs-meetingextension-action.yml) | 86 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d7954be-ab39-4c0d-9eed-169fbcb67ceb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/88da1c2e6e7edb2b6072e66ace76c8087c5ffb38/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 84 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e6e1553-edbd-45dd-b9cc-5f20f1f0fd28) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/88da1c2e6e7edb2b6072e66ace76c8087c5ffb38/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51773714-6ed0-4ce2-a8da-9bf0f7988522) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/bots/teams-bot-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/146dafde1d4e40ef95bb31a3e76010c8b3b32667/msteams-platform%2Fincludes%2Fbots%2Fteams-bot-samples.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39a8b15c-7b7a-4445-9109-8941c70bb7c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/get-started-use-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/146dafde1d4e40ef95bb31a3e76010c8b3b32667/msteams-platform%2Fincludes%2Fget-started%2Fget-started-use-app-studio.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85c6396b-6cff-4f40-b032-ec38c883d805) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extension-command-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/146dafde1d4e40ef95bb31a3e76010c8b3b32667/msteams-platform%2Fincludes%2Fmessaging-extension-command-schema.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f575b64-e414-4873-af18-d9ac3edb77fe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/learn-more.md](https://github.com/MicrosoftDocs/msteams-docs/blob/146dafde1d4e40ef95bb31a3e76010c8b3b32667/msteams-platform%2Fincludes%2Fmessaging-extensions%2Flearn-more.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef0ec094-a823-4951-837c-280dd09a2177) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/messaging-extensions-common.md](https://github.com/MicrosoftDocs/msteams-docs/blob/146dafde1d4e40ef95bb31a3e76010c8b3b32667/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmessaging-extensions-common.md) | 84 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08caad50-a8c7-4f1f-954c-bec3471fb279) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/v3-to-v4-pointer-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/146dafde1d4e40ef95bb31a3e76010c8b3b32667/msteams-platform%2Fincludes%2Fv3-to-v4-pointer-me.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a2f0285-7349-4394-a05e-f821cc2b9d42) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/v4-to-v3-pointer-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/146dafde1d4e40ef95bb31a3e76010c8b3b32667/msteams-platform%2Fincludes%2Fv4-to-v3-pointer-me.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9583cd2-655b-4640-a3e7-161c7fb956dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/146dafde1d4e40ef95bb31a3e76010c8b3b32667/msteams-platform%2Findex.yml) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78afa8cb-3e11-4efb-9a4e-cd3acb9f3bb2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/146dafde1d4e40ef95bb31a3e76010c8b3b32667/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8b435bb-f68f-4924-baea-27e9de1a203b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/146dafde1d4e40ef95bb31a3e76010c8b3b32667/msteams-platform%2Fsbs-gs-javascript.yml) | 93 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ec750a5-9456-4e99-a8a3-c3370c6b7b15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-nodejs.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/146dafde1d4e40ef95bb31a3e76010c8b3b32667/msteams-platform%2Fsbs-gs-nodejs.yml) | 92 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42e0a0c2-6750-497b-8257-bd63744d1681) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/146dafde1d4e40ef95bb31a3e76010c8b3b32667/msteams-platform%2Fsbs-meetingextension-action.yml) | 86 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbc6f25b-2102-420a-ae7e-fbb2af2cd501) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/146dafde1d4e40ef95bb31a3e76010c8b3b32667/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 84 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d48c2c7e-78b0-4921-8328-188cadf02acb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/146dafde1d4e40ef95bb31a3e76010c8b3b32667/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c68c30d-fc91-4164-9a36-4c7dece1482b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by stkong-sdk — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/bots/teams-bot-samples.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c200ca7a3363baa5aa85d66fdbb6b0e991fca3f/msteams-platform%2Fincludes%2Fbots%2Fteams-bot-samples.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ab2e754-62f4-4636-a5a6-1b88fd4619aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/get-started/get-started-use-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c200ca7a3363baa5aa85d66fdbb6b0e991fca3f/msteams-platform%2Fincludes%2Fget-started%2Fget-started-use-app-studio.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80fee002-8aa0-46aa-9331-18dcf39c9fc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extension-command-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c200ca7a3363baa5aa85d66fdbb6b0e991fca3f/msteams-platform%2Fincludes%2Fmessaging-extension-command-schema.md) | 86 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf87d1ea-51f7-4634-81ec-96ce8e841b47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/learn-more.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c200ca7a3363baa5aa85d66fdbb6b0e991fca3f/msteams-platform%2Fincludes%2Fmessaging-extensions%2Flearn-more.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f2bd0429-e71c-4879-ab3d-1e122b9710c3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/messaging-extensions/messaging-extensions-common.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c200ca7a3363baa5aa85d66fdbb6b0e991fca3f/msteams-platform%2Fincludes%2Fmessaging-extensions%2Fmessaging-extensions-common.md) | 84 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0fb1bf76-5505-4b8f-b6de-d3578199ded6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/v3-to-v4-pointer-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c200ca7a3363baa5aa85d66fdbb6b0e991fca3f/msteams-platform%2Fincludes%2Fv3-to-v4-pointer-me.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b843af4-4bee-488d-858f-4bcb2adde259) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/includes/v4-to-v3-pointer-me.md](https://github.com/MicrosoftDocs/msteams-docs/blob/5c200ca7a3363baa5aa85d66fdbb6b0e991fca3f/msteams-platform%2Fincludes%2Fv4-to-v3-pointer-me.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3881e59-d088-418e-b181-bc2ba53053c9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/index.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5c200ca7a3363baa5aa85d66fdbb6b0e991fca3f/msteams-platform%2Findex.yml) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8eef40f-9292-4dbe-a65c-5f6dd6652c3b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-csharp.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5c200ca7a3363baa5aa85d66fdbb6b0e991fca3f/msteams-platform%2Fsbs-gs-csharp.yml) | 95 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5836e35c-11c9-46c9-a522-a6a2bedcbe08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-javascript.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5c200ca7a3363baa5aa85d66fdbb6b0e991fca3f/msteams-platform%2Fsbs-gs-javascript.yml) | 93 | 84 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f164efeb-79b4-4463-93da-7da93875958a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-gs-nodejs.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5c200ca7a3363baa5aa85d66fdbb6b0e991fca3f/msteams-platform%2Fsbs-gs-nodejs.yml) | 92 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0628e07f-d3bf-4fbe-84ad-69490c5087a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5c200ca7a3363baa5aa85d66fdbb6b0e991fca3f/msteams-platform%2Fsbs-meetingextension-action.yml) | 86 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9c43aae-16c6-49aa-9f11-2f1d6cd770a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5c200ca7a3363baa5aa85d66fdbb6b0e991fca3f/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 84 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8907cf9-1f26-4309-82ca-eb1c14c23715) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-tabs-and-messaging-extensions-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/5c200ca7a3363baa5aa85d66fdbb6b0e991fca3f/msteams-platform%2Fsbs-tabs-and-messaging-extensions-with-sso.yml) | 86 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a40806ef-b943-4d14-9bb9-830e53de3913) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
