### PR TITLE
[Doc improvement][SEO13 meta title update][3876694]

### PR DESCRIPTION
**Pull request by v-ramyas5**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e1add019142e6578c921f3a1097e085583a3d5/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/935620a1-b696-431e-89e3-be9c03324060) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e1add019142e6578c921f3a1097e085583a3d5/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eea02dfb-313f-4ffe-86aa-6e9ce915c172) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/TeamsFx-preview-and-customize-app-manifest-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e1add019142e6578c921f3a1097e085583a3d5/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2FTeamsFx-preview-and-customize-app-manifest-vs.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ac7280f-5c62-438c-956b-16f6e07ecedd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e1add019142e6578c921f3a1097e085583a3d5/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-v4.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2604924d-1738-4992-b5ef-87a5f35fe229) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/create-new-project-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e1add019142e6578c921f3a1097e085583a3d5/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fcreate-new-project-vs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95f78237-3515-4cce-86af-280e86b9186f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e1add019142e6578c921f3a1097e085583a3d5/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3b8fff6-9e08-484a-b4c3-c3c29c757a01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-local-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e1add019142e6578c921f3a1097e085583a3d5/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-local-vs.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6b87a56-4962-4744-87b2-7309a210031a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-overview-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e1add019142e6578c921f3a1097e085583a3d5/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-overview-vs.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b44d780-a85b-48d6-af63-b91757057024) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-your-Teams-app-test-tool-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e1add019142e6578c921f3a1097e085583a3d5/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-your-Teams-app-test-tool-vs.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4516c3d1-d177-48e0-9f00-d3ca0641029e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d9e1add019142e6578c921f3a1097e085583a3d5/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 89 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4c4c54a-e8fe-4ed7-87ba-adee28ec63e7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e08162545547fc09cd5938365abd2f4706419081/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/549c55b9-cc24-4190-bb5e-c5ede6f28fa9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e08162545547fc09cd5938365abd2f4706419081/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e93cd210-85e9-4254-b3a7-2773cf79f6ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/TeamsFx-preview-and-customize-app-manifest-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e08162545547fc09cd5938365abd2f4706419081/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2FTeamsFx-preview-and-customize-app-manifest-vs.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0cf38707-3509-4681-a656-b0a6335cee69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e08162545547fc09cd5938365abd2f4706419081/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-v4.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fddb27e-b4e2-4014-9d85-26cfcfc74f64) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/create-new-project-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e08162545547fc09cd5938365abd2f4706419081/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fcreate-new-project-vs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2c500bd-f39f-4577-9d5c-4bdc578f5b4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e08162545547fc09cd5938365abd2f4706419081/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5312d866-322b-42cc-8313-4c7781f283cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-local-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e08162545547fc09cd5938365abd2f4706419081/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-local-vs.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/64dc8598-7e1b-45b2-8a36-c751703aae1a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-overview-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e08162545547fc09cd5938365abd2f4706419081/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-overview-vs.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6b2150c4-87da-4317-98bd-96398f7fda6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-your-Teams-app-test-tool-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e08162545547fc09cd5938365abd2f4706419081/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-your-Teams-app-test-tool-vs.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/732f6e61-b7ae-4bad-a7ef-bfd8e5b1ea16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e08162545547fc09cd5938365abd2f4706419081/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 89 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95403440-f6f4-461a-9643-34e12a3c9908) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-existing-aad-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e08162545547fc09cd5938365abd2f4706419081/msteams-platform%2Ftoolkit%2Fuse-existing-aad-app.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3775925-e515-417e-a1c2-eb0ec68b7da1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32951431631e346fe7781e70e70c91344a87be12/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7207531-ab91-45d7-8b52-65cdda0ce42a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32951431631e346fe7781e70e70c91344a87be12/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7966deed-e9c9-4406-bf02-0b4463dbd719) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/TeamsFx-preview-and-customize-app-manifest-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32951431631e346fe7781e70e70c91344a87be12/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2FTeamsFx-preview-and-customize-app-manifest-vs.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6b73df1-8e7a-4605-b1b2-97e1852ca5e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32951431631e346fe7781e70e70c91344a87be12/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-v4.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7762b241-4382-4d0a-802f-7e2540b58a27) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/create-new-project-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32951431631e346fe7781e70e70c91344a87be12/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fcreate-new-project-vs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/47449a05-9b36-47ee-988c-e2328968eab0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32951431631e346fe7781e70e70c91344a87be12/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1df04cd-83a0-4754-a05b-eeef129fa01c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-local-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32951431631e346fe7781e70e70c91344a87be12/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-local-vs.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a936acf1-ce4a-44e8-ae52-b57dd49458b2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-overview-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32951431631e346fe7781e70e70c91344a87be12/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-overview-vs.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94c27a22-9698-4a44-b37c-f8bfb778bb75) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-your-Teams-app-test-tool-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32951431631e346fe7781e70e70c91344a87be12/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-your-Teams-app-test-tool-vs.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/943029c1-c711-4d61-9798-9836accb7698) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32951431631e346fe7781e70e70c91344a87be12/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 89 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ff2af2a-a1bf-44b0-9ac0-dc7d821534f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-existing-aad-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/32951431631e346fe7781e70e70c91344a87be12/msteams-platform%2Ftoolkit%2Fuse-existing-aad-app.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/770762b5-06d9-4f79-b1f0-568d6a6b79d8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ec0ed2b5f6ab936b0b0073f3fd9811d3dec0619/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a3af5c9a-7569-4d13-bfef-179ddd926830) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ec0ed2b5f6ab936b0b0073f3fd9811d3dec0619/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d107ec8-578d-4c8c-84cf-cee7c11a577e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/TeamsFx-preview-and-customize-app-manifest-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ec0ed2b5f6ab936b0b0073f3fd9811d3dec0619/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2FTeamsFx-preview-and-customize-app-manifest-vs.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/427d56ea-87b9-45b7-9960-4901b70b9322) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ec0ed2b5f6ab936b0b0073f3fd9811d3dec0619/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-v4.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8bb7e786-fa66-4699-a467-8fbe89a67a2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/create-new-project-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ec0ed2b5f6ab936b0b0073f3fd9811d3dec0619/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fcreate-new-project-vs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31c72881-f8f2-49be-97e1-917083a4e047) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ec0ed2b5f6ab936b0b0073f3fd9811d3dec0619/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef3e57f2-0804-4c4e-ab2e-5ffc58351aac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-local-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ec0ed2b5f6ab936b0b0073f3fd9811d3dec0619/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-local-vs.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/273c1366-1ec0-4eef-a982-afada0c3f42c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-overview-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ec0ed2b5f6ab936b0b0073f3fd9811d3dec0619/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-overview-vs.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/601040a4-237d-46c0-9410-9393e7ea3e72) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-your-Teams-app-test-tool-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ec0ed2b5f6ab936b0b0073f3fd9811d3dec0619/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-your-Teams-app-test-tool-vs.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/066e70ba-329f-4652-8fb9-39ea61e563a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ec0ed2b5f6ab936b0b0073f3fd9811d3dec0619/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 89 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b48fe792-7736-4e2e-a3e2-fff18f67ae63) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-existing-aad-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ec0ed2b5f6ab936b0b0073f3fd9811d3dec0619/msteams-platform%2Ftoolkit%2Fuse-existing-aad-app.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/03c973ed-8b8d-40a2-b139-6ce83668b266) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/TeamsFx-multi-env.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81ebdf425cb410285227b9dcc4efd10595fc7b10/msteams-platform%2Ftoolkit%2FTeamsFx-multi-env.md) | 92 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76085a42-efeb-44ec-9a29-47abbf5b4d0c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81ebdf425cb410285227b9dcc4efd10595fc7b10/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e8980fde-f83f-4faf-a430-d9fa3e51292d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/TeamsFx-preview-and-customize-app-manifest-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81ebdf425cb410285227b9dcc4efd10595fc7b10/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2FTeamsFx-preview-and-customize-app-manifest-vs.md) | 96 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d80b2ba-3eca-41a8-a926-0fee9b67708a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/build-environments-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81ebdf425cb410285227b9dcc4efd10595fc7b10/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fbuild-environments-v4.md) | 91 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/649be6ff-10b4-4e6e-b9c7-e71254ca7f55) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/create-new-project-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81ebdf425cb410285227b9dcc4efd10595fc7b10/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fcreate-new-project-vs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/420fac9e-57c7-43aa-bac1-22d8513edf71) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-background-process-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81ebdf425cb410285227b9dcc4efd10595fc7b10/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-background-process-v4.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fce3439e-8efd-4e72-a2d7-8760cb041a5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-local-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81ebdf425cb410285227b9dcc4efd10595fc7b10/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-local-vs.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6382f39-b059-4601-83a6-965535229155) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-overview-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81ebdf425cb410285227b9dcc4efd10595fc7b10/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-overview-vs.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b5b8223-bc02-45d4-8b5d-0e9492b80dfe) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/debug-your-Teams-app-test-tool-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81ebdf425cb410285227b9dcc4efd10595fc7b10/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fdebug-your-Teams-app-test-tool-vs.md) | 95 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1fd8d0ae-cbcf-4f95-a154-65f17a8bf39d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/provision-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81ebdf425cb410285227b9dcc4efd10595fc7b10/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fprovision-vs.md) | 89 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c4e1187-f07f-4d90-8b79-a80008965d34) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/use-existing-aad-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/81ebdf425cb410285227b9dcc4efd10595fc7b10/msteams-platform%2Ftoolkit%2Fuse-existing-aad-app.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84e2c1b7-f971-4e80-bf4d-af1d43d1289b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
