### PR TITLE
[Doc Improvement][SBS guide prerequisites update-2]

### PR DESCRIPTION
**Pull request by v-amprasad**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/58a55e298487991ec31402ced0d2cf47d00a5b35/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 86 | 30 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/15038b6a-af01-4ecf-9bd3-d0febc3c95a4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/101001b8457988c55124ed6fa8db03e605d48d29/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 87 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30c124c2-bfb9-4cdb-ad07-917f5208009a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f732e30a959760751fda0236c4620cfb69981e06/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 87 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a582ceb-dc40-4c84-9b6f-efe5358b0297) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-graphactivity-feedbroadcast.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f732e30a959760751fda0236c4620cfb69981e06/msteams-platform%2Fsbs-graphactivity-feedbroadcast.yml) | 86 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80b73047-7af7-44bc-8039-87fa03572951) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f5466f8784aa135523600dc517ae9e2e228b8852/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 87 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9469788c-8c8f-47ff-beba-248c63b093ea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-graphactivity-feedbroadcast.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f5466f8784aa135523600dc517ae9e2e228b8852/msteams-platform%2Fsbs-graphactivity-feedbroadcast.yml) | 86 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66119c39-70bb-4734-bd7c-d4ee7324a6d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f5466f8784aa135523600dc517ae9e2e228b8852/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 86 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3493185-5659-4b2b-8d3a-194cf1e5e405) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4f4ff96050e881cac9d0257f1f5518ceee91bac7/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 84 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/080f4d61-d19c-4ae4-8fe4-3a85dfb3e7ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4f4ff96050e881cac9d0257f1f5518ceee91bac7/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 87 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5854fff2-f05b-412d-8837-1748bde16731) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-graphactivity-feedbroadcast.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4f4ff96050e881cac9d0257f1f5518ceee91bac7/msteams-platform%2Fsbs-graphactivity-feedbroadcast.yml) | 86 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a8b9026-2195-4a7f-93bb-47d739e728dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4f4ff96050e881cac9d0257f1f5518ceee91bac7/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 86 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d4ea1b2-4ed3-43bd-9d25-b0aa0134d9fc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab23b2f1e09acd65408ebacc619088e72d73fc90/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 84 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7aa4554d-7273-4451-9e99-e45c475e3fa4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab23b2f1e09acd65408ebacc619088e72d73fc90/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 87 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1dab76c0-0aac-49dc-8544-61f7e4b02455) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-graphactivity-feedbroadcast.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab23b2f1e09acd65408ebacc619088e72d73fc90/msteams-platform%2Fsbs-graphactivity-feedbroadcast.yml) | 86 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e3e61ed-4249-4203-9b74-d91230a96145) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab23b2f1e09acd65408ebacc619088e72d73fc90/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 86 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/934e9d85-3232-4c11-a6de-b12c3310f774) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ab23b2f1e09acd65408ebacc619088e72d73fc90/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/657c03a9-1eb3-433e-a3de-cea4a972790a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e939bcf8665aac0d40b26ea5486b4f7ab2350439/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 84 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e923bd3-4529-48ed-a319-9e6e8371b78d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e939bcf8665aac0d40b26ea5486b4f7ab2350439/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 87 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b1f154c-e12c-4a5b-8d1e-1e6b3bdaa01e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-graphactivity-feedbroadcast.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e939bcf8665aac0d40b26ea5486b4f7ab2350439/msteams-platform%2Fsbs-graphactivity-feedbroadcast.yml) | 86 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35120b97-4e18-4c9a-9a9f-d0b1f036e275) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e939bcf8665aac0d40b26ea5486b4f7ab2350439/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 86 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1543c423-7ae0-499f-bce2-336dcde30bf2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e939bcf8665aac0d40b26ea5486b4f7ab2350439/msteams-platform%2Fsbs-meetingextension-action.yml) | 87 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bad3878d-db64-427c-a932-0264d22f53cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e939bcf8665aac0d40b26ea5486b4f7ab2350439/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2b87fe5-dcac-4a71-b0fb-0487839b0804) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/45202ff235befc84dc594a159491fd15768ac230/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 84 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a8ed055-2f0e-404f-92ac-a48edf5c9fb5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/45202ff235befc84dc594a159491fd15768ac230/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 87 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22469360-2a2a-4586-adcd-60394bc7a9e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-graphactivity-feedbroadcast.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/45202ff235befc84dc594a159491fd15768ac230/msteams-platform%2Fsbs-graphactivity-feedbroadcast.yml) | 86 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac553028-a658-40ea-b327-0a8e9af2073b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/45202ff235befc84dc594a159491fd15768ac230/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 86 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a8c6a8d-2396-4cdd-810f-70ffeaba8216) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/45202ff235befc84dc594a159491fd15768ac230/msteams-platform%2Fsbs-meetingextension-action.yml) | 87 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2518fa89-f967-4951-ad0b-dd2b8b87d0ed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/45202ff235befc84dc594a159491fd15768ac230/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89b1491a-c91b-48d1-a5f0-a26464b5821d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/45202ff235befc84dc594a159491fd15768ac230/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6516972d-8995-43f4-88e2-a0c18d52ada3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bff9e7a8f690b50f40f8c7c19236738ce6366f9f/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 87 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7ab6dc83-f4af-4842-af91-559583947aa9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bff9e7a8f690b50f40f8c7c19236738ce6366f9f/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 84 | 43 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80c8e689-b52d-4746-bf67-38125cbf6985) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bff9e7a8f690b50f40f8c7c19236738ce6366f9f/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 87 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/969dbb16-2c7e-4827-89e2-53cbb0de3491) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-graphactivity-feedbroadcast.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bff9e7a8f690b50f40f8c7c19236738ce6366f9f/msteams-platform%2Fsbs-graphactivity-feedbroadcast.yml) | 86 | 41 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df8115a9-06c1-4557-9d4e-14e6c17205a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bff9e7a8f690b50f40f8c7c19236738ce6366f9f/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 86 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/edbfe13c-a28c-42fd-bed7-0e922b82d610) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bff9e7a8f690b50f40f8c7c19236738ce6366f9f/msteams-platform%2Fsbs-meetingextension-action.yml) | 87 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7056f06c-9c17-4082-a8b6-21036b152f5f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bff9e7a8f690b50f40f8c7c19236738ce6366f9f/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 85 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9051225c-d632-4416-8fd6-2a9852a0316c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bff9e7a8f690b50f40f8c7c19236738ce6366f9f/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 86 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/abb79abf-7ea6-41ae-b110-e18eedc2d506) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-teams-connectors.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/bff9e7a8f690b50f40f8c7c19236738ce6366f9f/msteams-platform%2Fsbs-teams-connectors.yml) | 87 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/290963ec-e1b8-4498-a4ff-838f9c91529d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-abirade** [comment]
Closing the PR as it has been merged with PR #7077.

**Pull request closed without merging**
