### PR TITLE
[Doc Improvement][TeamsJS support matrix updates for 10_2023][3418449]

### PR DESCRIPTION
**Pull request by mobajemu-msft**
TeamsJS support matrix updates for 10/2023 include:
* Remove all Outlook preview asterisks for Outlook desktop, Android and iOS
* For all tables: add new "Teams preview" column for web, with duplicate support data as Teams preview for desktop columns.
* Outlook Win 32, Teams Mobile for iOS and Android supports pages.adaptiveCard and pages.adaptiveCard.bot
* geoLocation works on Outlook Win32
* Search works in Teams web and Desktop GA
* Calendar works in Outlook web/OWA
* Chat and Call work in Outlook Web and preview
* Sharing no longer is supported in Teams for both iOS and Android
* Video is no longer supported in Teams Web and Teams desktop GA
* Call and Chat work in Teams desktop preview
* Pages.CurrentApp works in Teams desktop preview, Outlook desktop GA, Outlook Web, M365 iOS and Android, and Outlook iOS
* pages.tabs, pages.appButton, stageView, and sharing no longer supported for Teams iOS and Android
* New updates across "Outlook desktop preview" (aka Outlook Monarch isSupported) columns:

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b8eb9b5bf9237826297769ff1be5aae87da693b6/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7a0a426-8e2e-470c-b64d-e9421da4942e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/20ac3bc57834c0432b79a782bf3493bfd3a4aa07/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6385fa3c-a6e6-4966-9269-a54d31efaf0c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by erikadoyle — COMMENTED** [review]
The [Teams-only capabilities](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/teamsjs-support-m365?branch=pr-en-us-9831#teams-only-capabilities) table now has some checkmarks showing in Outlook web and New Outlook Windows columns. Could we remove these?

**Review by erikadoyle — COMMENTED** [review]
[Preview capabilities awaiting host support](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/teamsjs-support-m365?branch=pr-en-us-9831#preview-capabilities-awaiting-host-support) still lists "search" as a capability without host support, but when you click on the link, the support table shows that Outlook now supports. Could we remove 'search' from this list? (Looks like it was already added as a row to the [Cross-host capabilities](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/teamsjs-support-m365?branch=pr-en-us-9831#cross-host-capabilities) table)

**Review by erikadoyle — COMMENTED** [review]
Whoops, looks like this didn't get updated in the [pages](https://review.learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/teamsjs-support-m365?branch=pr-en-us-9831#pages) support table:

- Outlook Win 32, Teams Mobile for iOS and Android supports `pages.adaptiveCard` and `pages.adaptiveCard.bot`

**Review by erikadoyle — CHANGES_REQUESTED** [review]
Don't forget to attend to the build warning too (in the first 2 cases, you might need to add sections for those sub-capabilities (w/description from its API reference doc, link to reference doc, link to sample code (if available).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c5308bba0763b63e6d6d02d7e6c3b27e33d26470/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/31a9de83-cae3-4110-92be-8172b0bac73f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/09b90f10ee9532911b858eeca1e71b57ee9d672d/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e536381e-2888-4131-ac9d-079641de5462) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbca1266ba38cbdfffc0f28b0dab3130ea5194bb/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/76b3c836-dcb7-48bc-a37e-d8e07f587168) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/eaa93957800335f87ab65617146aa1343548244e/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f88d703-90d7-4de3-bb7e-7160da65a085) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90013c3d65cb74b50fb7948516ec9171463ce670/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1739251-d534-4815-808d-a3791d810a1a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1483fdad16efdab75391dfe5b918f1e2bede2dee/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6dafb6d-be30-465d-82ef-cb1da88b06e8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by erikadoyle — CHANGES_REQUESTED** [review]
Oh shoot, sorry! There is one more fix. Just realized the list of updates I passed on to you had an error:

> Outlook Win 32, Teams Mobile for iOS and Android supports pages.adaptiveCard and pages.adaptiveCard.bot

. . . should have said **dialog.adaptiveCard** and **dialog.adaptiveCard.bot**. Could we remove the 2 new sections (pages.adaptiveCard, pages.adaptiveCard.bot) with missing links? And then update the respective rows in **dialog** section by adding support for Outlook desktop, Teams iOS, and Teams Android. Then this will be good to merge!

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f348e131147c2a22cf05ee2b872445d20cd229d6/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/acb46489-c42a-4b10-91e1-609ea0995757) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/86f112fddf78587989964e0bfeddc29b4f72fbeb/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e0a27d42-8e87-41a4-96e3-1fdc6cccc496) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/52daac3ac4a9e7e35436245f158d0db84eab73a2/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e227a1b0-c0fc-4155-bfcf-56c34f5405c6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by erikadoyle — APPROVED** [review]
Thank you @mobajemu-msft! This is ready to push

**Comment by erikadoyle** [comment]
@surbhigupta12 these are reviewed and ready to publish. Could someone please help us push live? Thank you!

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c74d902259a9e07f3265957bacc6379bf144fa1/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09e05927-c9c1-4bb9-b025-8b0c40e300fe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3cf57f9e7c8ead4513971931be4c5c34ae96ce1f/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 94 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ddf20f8-a766-4a2a-bdad-e5f38fbea463) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
