### PR TITLE
[Doc Improvement][SEO6 meta title update for same H1][3948825]

### PR DESCRIPTION
**Pull request by v-ramyas5**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/967013c58847ca632529ebf6aec6ca8380dc042c/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 87 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d4a3979d-7647-4040-bde4-c4c341f084ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-core-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/967013c58847ca632529ebf6aec6ca8380dc042c/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-core-capabilities.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f47f25d4-f312-4968-9265-0c910a253070) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/967013c58847ca632529ebf6aec6ca8380dc042c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c405bec5-0951-4b80-b165-01e9dcbc6a1f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-in-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/967013c58847ca632529ebf6aec6ca8380dc042c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-in-meeting.md) | 90 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/430fec15-369a-4060-ba3b-5ad6aa3e8d33) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/967013c58847ca632529ebf6aec6ca8380dc042c/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5482b28e-ae22-4309-8e09-5164e4b55588) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/967013c58847ca632529ebf6aec6ca8380dc042c/msteams-platform%2Fsbs-meetingextension-action.yml) | 81 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eddfa86b-ec60-4e37-bfaf-1462cd75bcc2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/app-caching.md](https://github.com/MicrosoftDocs/msteams-docs/blob/967013c58847ca632529ebf6aec6ca8380dc042c/msteams-platform%2Ftabs%2Fhow-to%2Fapp-caching.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30164c68-9541-4737-ae6b-08c2f1b6575a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/967013c58847ca632529ebf6aec6ca8380dc042c/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 100 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1e548b52-df82-4313-ba86-13f6af3b7f06) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-local.md](https://github.com/MicrosoftDocs/msteams-docs/blob/967013c58847ca632529ebf6aec6ca8380dc042c/msteams-platform%2Ftoolkit%2Fdebug-local.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ea553d8-11c9-48a3-9d72-166fb0c5041f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/967013c58847ca632529ebf6aec6ca8380dc042c/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46d3da66-4d2c-4347-8936-a172a4f9f607) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/explore-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/967013c58847ca632529ebf6aec6ca8380dc042c/msteams-platform%2Ftoolkit%2Fexplore-Teams-Toolkit.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1ec01eb8-a1c7-4f5e-843e-d33cfeb55fc1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bc4a462ce2bbde27ca1f61160659425af3cb626/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 87 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/809c97bc-5fde-4b75-90b9-dca78e5f56ef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-core-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bc4a462ce2bbde27ca1f61160659425af3cb626/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-core-capabilities.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24711104-1139-49d4-8bb7-30e97a0699ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bc4a462ce2bbde27ca1f61160659425af3cb626/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a8dfe14-2f30-47a1-941a-5ee0512a7026) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-in-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bc4a462ce2bbde27ca1f61160659425af3cb626/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-in-meeting.md) | 90 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60ccd6c5-ace3-4440-95db-54f9d9ed781d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7bc4a462ce2bbde27ca1f61160659425af3cb626/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0bfd5dc1-8482-4e16-9629-dca2d31cfcd1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/7bc4a462ce2bbde27ca1f61160659425af3cb626/msteams-platform%2Fsbs-meetingextension-action.yml) | 81 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/297a4173-d4f5-4077-83e4-39e8cbfa1cfc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/app-caching.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bc4a462ce2bbde27ca1f61160659425af3cb626/msteams-platform%2Ftabs%2Fhow-to%2Fapp-caching.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d05db7e8-e63c-45c5-bce4-d38fb42563dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bc4a462ce2bbde27ca1f61160659425af3cb626/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 100 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9ca72a0a-be03-4614-9ac6-47e3b76b8673) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bc4a462ce2bbde27ca1f61160659425af3cb626/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d3f67382-d04c-4b83-81a5-7e01c2a47d9a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/explore-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7bc4a462ce2bbde27ca1f61160659425af3cb626/msteams-platform%2Ftoolkit%2Fexplore-Teams-Toolkit.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f39bff1-4109-44fc-a45a-eb0df9ea221e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a96e1b0800896ddef8e99d779b7d44df0894c0f/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 87 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9178e2c5-a2fe-414e-8437-a0adfa158907) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-core-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a96e1b0800896ddef8e99d779b7d44df0894c0f/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-core-capabilities.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3dcc45b-e31e-48cf-9c1b-77a95a9b3035) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a96e1b0800896ddef8e99d779b7d44df0894c0f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7f91706-5ef6-4d1b-b196-a0694c6d4a73) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-in-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a96e1b0800896ddef8e99d779b7d44df0894c0f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-in-meeting.md) | 90 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4fd2366c-30d0-4670-9eb0-fbad4f245ef9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1a96e1b0800896ddef8e99d779b7d44df0894c0f/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/364193a6-0600-4b5d-a6bc-c1413ff199e1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1a96e1b0800896ddef8e99d779b7d44df0894c0f/msteams-platform%2Fsbs-meetingextension-action.yml) | 81 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/30f07cb6-930d-4fa4-8571-1f9ed161d9c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/app-caching.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a96e1b0800896ddef8e99d779b7d44df0894c0f/msteams-platform%2Ftabs%2Fhow-to%2Fapp-caching.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41563c50-2220-4ca1-91b3-beaa4af44c53) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a96e1b0800896ddef8e99d779b7d44df0894c0f/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 100 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/156134fa-277e-48a3-9c06-d48595a4ea2a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a96e1b0800896ddef8e99d779b7d44df0894c0f/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b2277d7-9722-4b06-b362-9c5dea9d6105) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/explore-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a96e1b0800896ddef8e99d779b7d44df0894c0f/msteams-platform%2Ftoolkit%2Fexplore-Teams-Toolkit.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4093e85c-a2e5-4a79-8203-c82d4c6ccabc) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9efbff51cfad7a521ce26a342afcf0cc85f1136c/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 87 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad1d8469-29ea-48d0-9ab4-315f6b9adbdf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-core-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9efbff51cfad7a521ce26a342afcf0cc85f1136c/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-core-capabilities.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28e649b3-5eaf-44f5-9d24-d095f2b8c42b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9efbff51cfad7a521ce26a342afcf0cc85f1136c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4677d9f-65f3-44b9-8810-e0a08baf54eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-in-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9efbff51cfad7a521ce26a342afcf0cc85f1136c/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-in-meeting.md) | 90 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac1cb23d-5288-411d-b2dc-ec6b423409d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9efbff51cfad7a521ce26a342afcf0cc85f1136c/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 90 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fcf00311-98a6-4df6-b1d9-a936f87e7f5a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/9efbff51cfad7a521ce26a342afcf0cc85f1136c/msteams-platform%2Fsbs-meetingextension-action.yml) | 81 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26eb7f43-b7ef-4d82-aa78-7cb9c01d6d3b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/app-caching.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9efbff51cfad7a521ce26a342afcf0cc85f1136c/msteams-platform%2Ftabs%2Fhow-to%2Fapp-caching.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb9017a5-fc78-4b8c-a3b5-fed9f44142ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9efbff51cfad7a521ce26a342afcf0cc85f1136c/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 100 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83ad5bea-18d6-4a3d-9bb0-2892dd0d313d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9efbff51cfad7a521ce26a342afcf0cc85f1136c/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/81096069-964c-4df1-815f-f6131a92aad8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/explore-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9efbff51cfad7a521ce26a342afcf0cc85f1136c/msteams-platform%2Ftoolkit%2Fexplore-Teams-Toolkit.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c8db984d-20ab-4a85-8d49-3848a7addd69) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1332d395d2d27dba64fd758e90e38f4f1ba32f6/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 87 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bae408de-371d-4439-8666-ac7a75e507df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-core-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1332d395d2d27dba64fd758e90e38f4f1ba32f6/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-core-capabilities.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0649fd7e-568b-42fc-8e17-89a7dcaa60d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1332d395d2d27dba64fd758e90e38f4f1ba32f6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/25536146-acef-417b-9ddf-0fa130a4c2d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-in-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1332d395d2d27dba64fd758e90e38f4f1ba32f6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-in-meeting.md) | 90 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/beb6ff4a-c4ce-4ede-b4c2-21381e553001) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e1332d395d2d27dba64fd758e90e38f4f1ba32f6/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/976c8e74-71bd-46cd-b121-0927df2c07f1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e1332d395d2d27dba64fd758e90e38f4f1ba32f6/msteams-platform%2Fsbs-meetingextension-action.yml) | 81 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee776743-d5fb-4416-96a5-6a4d67e4ac00) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/app-caching.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1332d395d2d27dba64fd758e90e38f4f1ba32f6/msteams-platform%2Ftabs%2Fhow-to%2Fapp-caching.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/edcfd4b2-3572-45a6-8041-0b91aa7900cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1332d395d2d27dba64fd758e90e38f4f1ba32f6/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/66cfabdd-cede-4170-9c35-c5893239d074) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1332d395d2d27dba64fd758e90e38f4f1ba32f6/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/72aff361-4832-4b42-85c8-7b1d86d8bc67) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/explore-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1332d395d2d27dba64fd758e90e38f4f1ba32f6/msteams-platform%2Ftoolkit%2Fexplore-Teams-Toolkit.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d65f3c5a-e9e2-4bd7-9960-2a8ea4b1febe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-preethah — APPROVED** [review]
Approved.

**Review by Wajeed-msft — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-tabs-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28453e323d1868e4e7d0df623c4e82c87c319353/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-tabs-for-meeting.md) | 87 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0dafa604-5db0-40a1-b6ba-ab68de831850) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/Teams conversational AI/how-conversation-ai-core-capabilities.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28453e323d1868e4e7d0df623c4e82c87c319353/msteams-platform%2Fbots%2Fhow-to%2FTeams%20conversational%20AI%2Fhow-conversation-ai-core-capabilities.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7fdc048f-aa54-4300-87f3-5e419b111eca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28453e323d1868e4e7d0df623c4e82c87c319353/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-localization.md) | 90 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb0d0964-aeab-4f29-99c4-1982a00edc37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-in-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28453e323d1868e4e7d0df623c4e82c87c319353/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-in-meeting.md) | 90 | 25 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/39595cb4-95a9-4b7b-b6e0-4683b1c14301) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/28453e323d1868e4e7d0df623c4e82c87c319353/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d94a3b2-bd52-49af-937e-d443c4453a58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/28453e323d1868e4e7d0df623c4e82c87c319353/msteams-platform%2Fsbs-meetingextension-action.yml) | 81 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0f5ade41-b609-4694-8aa8-f1fcb0cdc64b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/app-caching.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28453e323d1868e4e7d0df623c4e82c87c319353/msteams-platform%2Ftabs%2Fhow-to%2Fapp-caching.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff29c35d-0847-4a03-b169-102150fc167d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28453e323d1868e4e7d0df623c4e82c87c319353/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-cards.md) | 98 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/52f26561-192d-41d3-96bc-c7a8dbcb9110) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/debug-mobile.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28453e323d1868e4e7d0df623c4e82c87c319353/msteams-platform%2Ftoolkit%2Fdebug-mobile.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a6700887-ad2e-4d8c-a192-911da3b2ec09) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/explore-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/28453e323d1868e4e7d0df623c4e82c87c319353/msteams-platform%2Ftoolkit%2Fexplore-Teams-Toolkit.md) | 89 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/625317c1-487e-4815-b691-e4930beca0e6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
