### PR TITLE
[Doc Improvement][SBS update generate meeting token][3292268] 

### PR DESCRIPTION
**Pull request by v-bvishnu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/messaging-endpoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2958efe5326021a0958b247f4021b5ca5907e30b/msteams-platform%2Fincludes%2Fget-started%2Fmessaging-endpoint.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7022b05b-ce8f-4ce8-90fa-a9532d31edb1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/2958efe5326021a0958b247f4021b5ca5907e30b/msteams-platform%2Fsbs-meeting-token-generator.yml) | 95 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cbe8e212-2641-4e03-9a95-0af003e2d77b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/messaging-endpoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1ead33c2f9c470c9f7105d28763168762c4cacf6/msteams-platform%2Fincludes%2Fget-started%2Fmessaging-endpoint.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc421910-392f-4261-9cf2-41404995b532) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/1ead33c2f9c470c9f7105d28763168762c4cacf6/msteams-platform%2Fsbs-meeting-token-generator.yml) | 94 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e7f27c1-f435-423c-8585-225ac4dda2b8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/messaging-endpoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/008c70160cb67c48a715f82dec923c032534e75d/msteams-platform%2Fincludes%2Fget-started%2Fmessaging-endpoint.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85d3a274-d232-41e3-9821-a689ad36a679) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/008c70160cb67c48a715f82dec923c032534e75d/msteams-platform%2Fsbs-meeting-token-generator.yml) | 94 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f74ecd7e-6dc6-4a9f-b79e-4109b6a6e4eb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/messaging-endpoint.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c45b7c31cbf641ee3de0a72df3880ba48b3f6d89/msteams-platform%2Fincludes%2Fget-started%2Fmessaging-endpoint.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0d892f80-068c-4058-88d9-703abc7bd8f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/c45b7c31cbf641ee3de0a72df3880ba48b3f6d89/msteams-platform%2Fsbs-meeting-token-generator.yml) | 94 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/424080b7-9dba-4c2f-9f71-1597c8b7bed9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
