### PR TITLE
[Doc Improvement][Task module to dialog explicit files][2956875]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/06846130e16883b0f43904622a2109e728059467/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/54918dd5-8f27-4ab9-b88e-abf6343a13e9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39627228f16ce679eb3d65383988fa12d382b07d/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2b40c97-aa84-4f53-ba93-c454098da378) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39627228f16ce679eb3d65383988fa12d382b07d/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5aed13fb-a007-4f90-abd1-e0d49a8ea0bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/39627228f16ce679eb3d65383988fa12d382b07d/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/88c519de-c89f-4f81-b4f7-a54375bab9d1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by erikadoyle — CHANGES_REQUESTED** [review]
Looks good, but could we update "TeamsJS v.1.0" to "TeamsJS v1.x" (to cover all minor versions, not just 1.0)?

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94b1819187ca871c7465340f31598b5b78793281/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/089f0e37-a800-47fb-8c54-e4aafd47bf02) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94b1819187ca871c7465340f31598b5b78793281/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/34053251-a117-4e37-abf2-445cd1c3c8e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94b1819187ca871c7465340f31598b5b78793281/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb4acf5b-88be-4583-a1c1-dd53b4535dbe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f2b23130067ee7174c74cb3b471a778fb1740af/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/447a13c4-dff9-467d-9492-54a9f00c2928) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f2b23130067ee7174c74cb3b471a778fb1740af/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1053a94-f666-4367-82e5-a39b24c83793) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1f2b23130067ee7174c74cb3b471a778fb1740af/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/872215dc-8d3f-4622-9364-0d21d29a6b52) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dad2e16211beaf5c964537118af46dd30ff4e56/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1afc0fb0-6c10-42a3-ac03-e166131da239) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dad2e16211beaf5c964537118af46dd30ff4e56/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/58031eb8-3ad5-411f-a386-1447f01f8790) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dad2e16211beaf5c964537118af46dd30ff4e56/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e20f8825-5c16-47a4-8df2-a5992806ac8c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c85b1305668950475b8df60befbbbf455023747/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd496303-1241-43b7-ba00-8566e361b369) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c85b1305668950475b8df60befbbbf455023747/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63b443c7-b87c-4ec5-9179-cc6143cfb9d8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2c85b1305668950475b8df60befbbbf455023747/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/570e6dd7-d72f-4918-9209-e829ef3e4670) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0176725638181eb550cbd553eab801ba03c52520/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/beb288c0-fff7-4552-be05-f3be27443357) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0176725638181eb550cbd553eab801ba03c52520/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1bc325e-5f0f-4047-848f-9c9219992ef8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0176725638181eb550cbd553eab801ba03c52520/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20ac9a27-5a56-4e06-8dc5-92f8f62aa766) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/570a8dc5768c6e12ec299f8e2889bf192d82afab/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b762150f-82cd-44db-81ca-53e71ae3e74c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/570a8dc5768c6e12ec299f8e2889bf192d82afab/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba08fc21-9b51-4491-a37d-043d19916a32) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/570a8dc5768c6e12ec299f8e2889bf192d82afab/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/046e016d-a832-4358-b3b4-28c99ed81e24) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8db5c456e09cf5134455fddbb0788244d3d1327/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd6bf759-0da5-4fba-88c9-b1e49d919da2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8db5c456e09cf5134455fddbb0788244d3d1327/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/454633df-b2d9-4c39-908f-cb51d13bd41e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8db5c456e09cf5134455fddbb0788244d3d1327/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1001278c-afdf-40d7-90e5-9df497d43f15) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca83e77ffa650048ee27ce34f86ed029855e5711/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9aac3e80-2189-4e7c-97da-d2154be957d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca83e77ffa650048ee27ce34f86ed029855e5711/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/931af514-a60a-4ff5-bf4a-c95429700a51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ca83e77ffa650048ee27ce34f86ed029855e5711/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56d7974c-89a3-40f9-8a54-1f7178d874f7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e9dfa1af40831d26323bc65939f77cf1d1604a6a/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/650b560f-c399-4dd3-b856-c0242a5e9bb1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e9dfa1af40831d26323bc65939f77cf1d1604a6a/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ea098a94-3284-4e73-a988-87221e3ab4a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e9dfa1af40831d26323bc65939f77cf1d1604a6a/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a15511a-b74d-4693-a5bc-a8c684b44549) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/77fdd11aa289c4c75191069b95cb58c635f2576b/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c84a771-7e6c-437f-b5a7-8b51f611948a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/77fdd11aa289c4c75191069b95cb58c635f2576b/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4775ec1-1e29-4bb5-a5b7-deee23aba23a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/77fdd11aa289c4c75191069b95cb58c635f2576b/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89abefbc-0dd0-4dfb-a26c-43d1bb4d39a1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bdac8406c72117e7126454310f3149a791b539ed/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/090321a2-3ff9-43cf-8f77-2d5deb342410) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bdac8406c72117e7126454310f3149a791b539ed/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71632e0f-75ac-436c-b3ef-108b61e35cb4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bdac8406c72117e7126454310f3149a791b539ed/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01fe4adb-a43a-4195-81e3-fe5237f165d4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d82add3f75613bbbac0e342bc65cecf8e3a84281/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98da8aa2-c3cf-4f28-a78b-4602e95ab2da) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d82add3f75613bbbac0e342bc65cecf8e3a84281/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8a77d7af-eef6-4ff6-b91d-108b24c0eed5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d82add3f75613bbbac0e342bc65cecf8e3a84281/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05f4e73c-87ba-4533-96ea-e35bade782ff) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e69d72daf5842b3cac5be00d921bb860a6f9ef6/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca6b4957-cb36-4549-a8db-086dddb46029) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e69d72daf5842b3cac5be00d921bb860a6f9ef6/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/94aea60a-b8ba-41e8-9cc1-be59f05d7719) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e69d72daf5842b3cac5be00d921bb860a6f9ef6/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/334110cd-68a9-47ad-a583-04260add6d20) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ebb4c6e5cc0fcd354a997c1e4fbaf6f095f54aa/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a4ee6e9-dcf3-4eef-bf45-9f5ae4a58597) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ebb4c6e5cc0fcd354a997c1e4fbaf6f095f54aa/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ed79626-1988-4725-beb4-484c3e143528) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0ebb4c6e5cc0fcd354a997c1e4fbaf6f095f54aa/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b96fdea-2404-490a-94e9-6ef4622f9703) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/map-use-cases.md](https://github.com/MicrosoftDocs/msteams-docs/blob/781f5951631daecdbab2a33fd677dcde407b8065/msteams-platform%2Fconcepts%2Fdesign%2Fmap-use-cases.md) | 98 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ef8e2573-7d0b-41b2-a478-cfa9c3698d2b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/781f5951631daecdbab2a33fd677dcde407b8065/msteams-platform%2Foverview.md) | 96 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e41075d4-cfd7-4ca8-a587-2daa5defb845) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/samesite-cookie-update.md](https://github.com/MicrosoftDocs/msteams-docs/blob/781f5951631daecdbab2a33fd677dcde407b8065/msteams-platform%2Fresources%2Fsamesite-cookie-update.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2e41bb5-c508-4eab-8cad-f4e0eb28f660) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
