### PR TITLE
[Doc improvement](see also4)

### PR DESCRIPTION
**Pull request by v-rpatkur**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2bfc40063e5dfa66d25da939ec042d5cc2951dfa/msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec54401d-ae9b-4b67-840c-a8140932fb9c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2bfc40063e5dfa66d25da939ec042d5cc2951dfa/msteams-platform/concepts/build-and-test/apps-localization.md) | 79 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b1b489ca-0a90-4944-814d-cf5f47de59a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2bfc40063e5dfa66d25da939ec042d5cc2951dfa/msteams-platform/resources/dev-preview/developer-preview-intro.md) | 84 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7d64944-2bb3-40de-9f89-42c36ff0260e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2bfc40063e5dfa66d25da939ec042d5cc2951dfa/msteams-platform/resources/schema/localization-schema.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d67d6a2-20c1-4044-979c-1bb37165ce6f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2bfc40063e5dfa66d25da939ec042d5cc2951dfa/msteams-platform/samples/app-templates.md) | 84 | 104 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ab4537f-97ca-4555-96f0-3c7f61152fd6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2bfc40063e5dfa66d25da939ec042d5cc2951dfa/msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8452b206-2100-4c03-97dc-3c6bb4845cc2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2d4db8a6ce270dd31fa94f37d8ba8480113115a/msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4e06532-977c-4971-82b1-d2cca7d208b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2d4db8a6ce270dd31fa94f37d8ba8480113115a/msteams-platform/concepts/build-and-test/apps-localization.md) | 80 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ca58949-bb36-4043-b855-d50e0418c713) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2d4db8a6ce270dd31fa94f37d8ba8480113115a/msteams-platform/resources/dev-preview/developer-preview-intro.md) | 84 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/588d12ae-57e2-4373-8faa-f0378596dc12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2d4db8a6ce270dd31fa94f37d8ba8480113115a/msteams-platform/resources/schema/localization-schema.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8d379581-57b5-454c-9d3c-bef83cbf6051) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2d4db8a6ce270dd31fa94f37d8ba8480113115a/msteams-platform/samples/app-templates.md) | 84 | 104 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b34d0a53-37d3-47dc-ae6f-4975a5fd7596) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2d4db8a6ce270dd31fa94f37d8ba8480113115a/msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63feefcd-747c-40d7-93da-6027d1ae8f24) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90045209e39ae52f26d768b440412feb343a800d/msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/097001a3-8964-4a4f-a09f-28bb6b5b5df6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90045209e39ae52f26d768b440412feb343a800d/msteams-platform/concepts/build-and-test/apps-localization.md) | 80 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0824c76-5f9e-45cc-a097-2ed72a66fccf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90045209e39ae52f26d768b440412feb343a800d/msteams-platform/resources/dev-preview/developer-preview-intro.md) | 84 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0e692aff-2fb0-46aa-8d9c-785020d29c3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90045209e39ae52f26d768b440412feb343a800d/msteams-platform/resources/schema/localization-schema.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e518546f-27db-481f-9153-b911427106f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90045209e39ae52f26d768b440412feb343a800d/msteams-platform/samples/app-templates.md) | 84 | 104 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c1e34991-203f-415d-bdd4-13426c68a8cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/90045209e39ae52f26d768b440412feb343a800d/msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c0e2b8f5-d461-4c20-aadc-718250b0d2d3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a09ad1319aeb560811e6bd97978a2a08ef4dda4/msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md) | 88 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/583b807c-2bfb-4cc4-819c-d5794e945df9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-localization.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a09ad1319aeb560811e6bd97978a2a08ef4dda4/msteams-platform/concepts/build-and-test/apps-localization.md) | 80 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3918d9a-c07f-4633-8e24-f3359c800cbd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/dev-preview/developer-preview-intro.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a09ad1319aeb560811e6bd97978a2a08ef4dda4/msteams-platform/resources/dev-preview/developer-preview-intro.md) | 84 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3973c2ef-9eda-4eca-a8f7-bce11cd44548) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a09ad1319aeb560811e6bd97978a2a08ef4dda4/msteams-platform/resources/schema/localization-schema.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0c4b3ab7-1390-419e-ba88-6685ed8943e3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/samples/app-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a09ad1319aeb560811e6bd97978a2a08ef4dda4/msteams-platform/samples/app-templates.md) | 84 | 104 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2757665f-2d73-4daf-a512-4cca80cefdd3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0a09ad1319aeb560811e6bd97978a2a08ef4dda4/msteams-platform/webhooks-and-connectors/what-are-webhooks-and-connectors.md) | 88 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aa2666a7-de2e-4cb3-a4d4-71c496a1179a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]
Approved

**Pull request merged**
