### PR TITLE
[Doc Improvement] [Update Branding and SEO][3715679]

### PR DESCRIPTION
**Pull request by v-ganr**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/95188104ddda96b30b16664ea6a1df838a4c6f53/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1aca21c0-0e88-4433-a3b1-7aedbdb976e6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ac8d5009652f31ccfd22dd84ca0395983937485/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fabf6996-d720-4608-ae5a-d3289de81d08) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9ac8d5009652f31ccfd22dd84ca0395983937485/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e937694b-c611-41a3-b288-fe4f1c6f7850) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/398a645432d2986660571dd7156177eab7681f2d/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b8434ce7-56f8-44c6-8e95-7354a345beb8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/398a645432d2986660571dd7156177eab7681f2d/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9d91700e-1960-417d-a447-7d9d2c918864) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/398a645432d2986660571dd7156177eab7681f2d/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d2e9dc61-d7af-42e2-9bdf-8acab5e7f814) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed0170dbdb1965562aa34d21821030623feae33d/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5af61a04-9a93-477c-b255-05d84510f38a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed0170dbdb1965562aa34d21821030623feae33d/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f596b175-7b10-4bee-91ac-d4828e0d9e1a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed0170dbdb1965562aa34d21821030623feae33d/msteams-platform%2Ftoolkit%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/728ed050-4d9e-43a8-b696-c775a66e43d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ed0170dbdb1965562aa34d21821030623feae33d/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8502610-a486-439d-9e74-8b099620bb5a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14fd633c57cbca505908c7607e92261d68b6ce6c/msteams-platform%2Ftoolkit%2Ffaq.md) | 86 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f13a59f9-3f1b-424a-bb20-8c1b1da50372) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14fd633c57cbca505908c7607e92261d68b6ce6c/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0d5cfd9-d13f-410f-b4f1-684c74f08227) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14fd633c57cbca505908c7607e92261d68b6ce6c/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e3d3e914-cf37-4c36-9480-3277d6538cc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14fd633c57cbca505908c7607e92261d68b6ce6c/msteams-platform%2Ftoolkit%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98a417cb-2932-4c85-badb-8cd790d15a7f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/14fd633c57cbca505908c7607e92261d68b6ce6c/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c039bc5c-09d9-4e59-a136-f371fbc7aebe) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3e357a2ff25f7680f7b0a85ee91e231fde9005/msteams-platform%2Ftoolkit%2Ffaq.md) | 86 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be8e4582-7a38-4246-b331-8888e119882b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3e357a2ff25f7680f7b0a85ee91e231fde9005/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7014cf6c-b030-48de-b552-71488f372564) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3e357a2ff25f7680f7b0a85ee91e231fde9005/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8764432a-e08b-4b84-9743-31bc64135c07) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3e357a2ff25f7680f7b0a85ee91e231fde9005/msteams-platform%2Ftoolkit%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a2c778c-817b-492b-a60e-73d676eecc4d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3e357a2ff25f7680f7b0a85ee91e231fde9005/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/df105471-4bf9-42be-81bd-ce279d79a9b3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/teams-toolkit-fundamentals-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8f3e357a2ff25f7680f7b0a85ee91e231fde9005/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fteams-toolkit-fundamentals-vs.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/014ab291-59dc-4f11-89fb-4d276fe6c59e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f017f54426eae667d592d101d223141a9c8d10bb/msteams-platform%2Ftoolkit%2Ffaq.md) | 86 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c8bb186-643e-427b-8167-81fff2058c63) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f017f54426eae667d592d101d223141a9c8d10bb/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/74118e77-dfda-4292-8950-f3e7f4495b6d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f017f54426eae667d592d101d223141a9c8d10bb/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aea45a14-01f4-4480-a26a-4419830b845b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f017f54426eae667d592d101d223141a9c8d10bb/msteams-platform%2Ftoolkit%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8273d79e-845d-4bf0-b4d8-904bd33bd971) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f017f54426eae667d592d101d223141a9c8d10bb/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a622662-626d-4575-a5be-e649505862f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/explore-Teams-Toolkit-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f017f54426eae667d592d101d223141a9c8d10bb/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fexplore-Teams-Toolkit-vs.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eacbbb75-86bb-4390-a9d7-e6f1aac84908) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/install-Teams-Toolkit-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f017f54426eae667d592d101d223141a9c8d10bb/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Finstall-Teams-Toolkit-vs.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f4a39bc-e427-4dd6-8007-de1dc6c9ca9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/teams-toolkit-fundamentals-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f017f54426eae667d592d101d223141a9c8d10bb/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fteams-toolkit-fundamentals-vs.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd89480c-a4ea-47ec-b58a-ed22fd7c4bb7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6e3791988294fa5e54caae88901c0c7d91303d1/msteams-platform%2Ftoolkit%2Ffaq.md) | 86 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c071ed04-6d67-4f81-826d-d2623ef50562) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6e3791988294fa5e54caae88901c0c7d91303d1/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1944714f-6368-4dec-97fe-e60c46be8a16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6e3791988294fa5e54caae88901c0c7d91303d1/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ce813f77-4ed1-447c-bd4e-6a554d7beacc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6e3791988294fa5e54caae88901c0c7d91303d1/msteams-platform%2Ftoolkit%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ae5fe6a8-86f5-45a1-9394-10fa9c707a90) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6e3791988294fa5e54caae88901c0c7d91303d1/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84183a0d-7297-443a-990f-92ca6ee11cd7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/explore-Teams-Toolkit-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6e3791988294fa5e54caae88901c0c7d91303d1/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fexplore-Teams-Toolkit-vs.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0372a1cf-9c01-4659-91be-53fce5c8122e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/install-Teams-Toolkit-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6e3791988294fa5e54caae88901c0c7d91303d1/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Finstall-Teams-Toolkit-vs.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e8a3c9c-e9dd-4722-b265-ef921b1b70e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/teams-toolkit-fundamentals-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6e3791988294fa5e54caae88901c0c7d91303d1/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fteams-toolkit-fundamentals-vs.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7fcf1a5-e12d-4ef3-9491-cb6420653e24) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/tools-prerequisites-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d6e3791988294fa5e54caae88901c0c7d91303d1/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ftools-prerequisites-v4.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75b0b7e7-960c-4406-8177-0a9005f63770) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd023aaad47b567b5f34eb1f2474ad76fdf0381d/msteams-platform%2Ftoolkit%2Ffaq.md) | 86 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b8f7ca3-5b4d-4ee6-8ea1-1f44c6f9ad5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish-your-teams-apps-using-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd023aaad47b567b5f34eb1f2474ad76fdf0381d/msteams-platform%2Ftoolkit%2Fpublish-your-teams-apps-using-developer-portal.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cc385e54-8651-4adc-923a-1d8abee6baef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd023aaad47b567b5f34eb1f2474ad76fdf0381d/msteams-platform%2Ftoolkit%2Fpublish.md) | 92 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/be1370e2-e639-45a5-985d-8d9885a3a039) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/teams-toolkit-tutorial.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd023aaad47b567b5f34eb1f2474ad76fdf0381d/msteams-platform%2Ftoolkit%2Fteams-toolkit-tutorial.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a913e44-d8f9-4436-9410-133ef6e78560) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/test-app-behavior.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd023aaad47b567b5f34eb1f2474ad76fdf0381d/msteams-platform%2Ftoolkit%2Ftest-app-behavior.md) | 100 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ecd6a8e1-f0c5-4b6d-b8f9-c1a3fa3c99d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/create-new-project-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd023aaad47b567b5f34eb1f2474ad76fdf0381d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fcreate-new-project-vs.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b064abd0-f82a-4334-bb5c-4c3f9013038f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/explore-Teams-Toolkit-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd023aaad47b567b5f34eb1f2474ad76fdf0381d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fexplore-Teams-Toolkit-vs.md) | 90 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5128b517-0198-4693-a87d-501ed6fa3f01) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/install-Teams-Toolkit-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd023aaad47b567b5f34eb1f2474ad76fdf0381d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Finstall-Teams-Toolkit-vs.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ba40b693-5324-401e-a8b4-4b555cc4a573) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/teams-toolkit-fundamentals-vs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd023aaad47b567b5f34eb1f2474ad76fdf0381d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fteams-toolkit-fundamentals-vs.md) | 97 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5f4dc43d-17a8-4b0d-8c4e-afdf3be98d9f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/tools-prerequisites-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fd023aaad47b567b5f34eb1f2474ad76fdf0381d/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ftools-prerequisites-v4.md) | 93 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/570e8c49-f4f4-46c0-a6e6-90b36ae91caa) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by surbhigupta12** [comment]
Closing this PR

**Pull request closed without merging**
