### PR TITLE
Test branch

### PR DESCRIPTION
**Pull request by v-vidhyarani**
Testing

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cfec10644fcf779135ff250e75869126d5c60b65/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/da2ca900-d4d5-47d2-a884-9cebbe985391) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/da9e8a3abf2377b71872d88f586539d6a5860083/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c405c612-487d-4bc0-b3d2-4c4f662f7dd4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d1c8468fb1d1912367afa3a2a8c935eaf08439f/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4cb336fc-90dc-41f1-962a-f2b9d96c58d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4d1c8468fb1d1912367afa3a2a8c935eaf08439f/msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md) | 84 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f33ffdcc-1fcf-4655-8ae7-a2360d389691) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3bd9376182f4be0cadea690fb5019a9b2b7ccac/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bfbad79-964e-41e7-9c4f-6668048b968e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3bd9376182f4be0cadea690fb5019a9b2b7ccac/msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md) | 84 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2911735e-2873-46c1-995c-40d938379688) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a3bd9376182f4be0cadea690fb5019a9b2b7ccac/msteams-platform/bots/how-to/bots-filesv4.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6f3da88e-c383-4be4-b235-74e20068b7be) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/630171560dd8fe7197cb3b3c3a15915e40ba7a9d/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/22e37180-3ee6-49c6-ba86-046153e6c3f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/630171560dd8fe7197cb3b3c3a15915e40ba7a9d/msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md) | 84 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/67e5bb7f-af3a-4636-8384-9ce9cb1b0471) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/630171560dd8fe7197cb3b3c3a15915e40ba7a9d/msteams-platform/bots/how-to/bots-filesv4.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8cd6c89-70aa-4287-afbb-714e9854e947) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9697824a9f3a2aa53283a2e54be6236aa3278a8a/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e963ad01-54ff-4063-94ff-166164b4efc4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9697824a9f3a2aa53283a2e54be6236aa3278a8a/msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md) | 86 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d57801f9-c458-47e9-a2ec-8f1392e02e69) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9697824a9f3a2aa53283a2e54be6236aa3278a8a/msteams-platform/bots/how-to/bots-filesv4.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9bb6dc23-290b-405f-80c0-b23be5f2353e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cdb04cb11a59d587d69e40e06cf445310e64cb61/msteams-platform/apps-in-teams-meetings/teams-apps-in-meetings.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd30bfac-b712-4257-8547-772d90ea96bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cdb04cb11a59d587d69e40e06cf445310e64cb61/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/84985979-8f5d-4e7a-95a7-6d36bc3045a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cdb04cb11a59d587d69e40e06cf445310e64cb61/msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md) | 86 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9cc331e5-75b9-4a24-a157-4f06a5691035) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cdb04cb11a59d587d69e40e06cf445310e64cb61/msteams-platform/bots/how-to/bots-filesv4.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a343fa4-b209-4836-8e77-2988b4d87a89) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We do not currently enforce a minimum score for content merged to the default branch. This will change in the future.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/68c78c879326a469b9fb4d28879a3926e58b272d/msteams-platform/bots/bot-basics.md) | 84 | 49 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5eb55002-19e7-4945-9b7c-3bfb4487c2d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md](https://github.com/MicrosoftDocs/msteams-docs/blob/68c78c879326a469b9fb4d28879a3926e58b272d/msteams-platform/bots/how-to/add-power-virtual-agents-bot-to-teams.md) | 86 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c406320b-f311-4b20-a63b-09821efbaba4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/bots-filesv4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/68c78c879326a469b9fb4d28879a3926e58b272d/msteams-platform/bots/how-to/bots-filesv4.md) | 93 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5eb9abdc-3cad-454d-bca2-e382ad976525) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by v-abirade** [comment]
Closed

**Pull request closed without merging**
