### PR TITLE
Updates Visual Studio Overview for Teams Toolkit

### PR DESCRIPTION
**Pull request by therealjohn**
Updates documentation for VS 2022 instructions and includes screenshots to match.

### CODE REVIEW

**Comment by therealjohn** [comment]
#sign-off

**Comment by therealjohn** [comment]
@surbhigupta12 @v-abirade Please review and let me know if anything needs to changed. Thanks!

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3fc383a35d9158adcaf2f42491feca09f42c6a45/msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md) | 87 | 24 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a14b82c0-ea6a-4fab-acd8-b2e38544b018) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/what-are-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3fc383a35d9158adcaf2f42491feca09f42c6a45/msteams-platform/bots/what-are-bots.md) | 96 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c6193ec-0f1e-4350-8243-b4bcadf55c0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/authentication/auth-silent-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3fc383a35d9158adcaf2f42491feca09f42c6a45/msteams-platform/tabs/how-to/authentication/auth-silent-aad.md) | 95 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59673e79-616f-4f1b-a520-b6e19699e57d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/visual-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3fc383a35d9158adcaf2f42491feca09f42c6a45/msteams-platform/toolkit/visual-studio-overview.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7333a998-816d-4dfc-8396-14cc381d9b27) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/visual-studio-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/761c962c562cbda338988d686b71917f270cda7f/msteams-platform/toolkit/visual-studio-overview.md) | 92 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e468dad-1f82-4033-9483-4525ce1bdfeb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-abirade — APPROVED** [review]
Approved

**Pull request merged**
