### PR TITLE
Update docfx.json

### PR DESCRIPTION
**Pull request by lindalu-MSFT**
Fix UHFHeader metadata typo

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[9d79b4b](https://github.com/MicrosoftDocs/msteams-docs/pull/479/commits/9d79b4ba6099716e1a6e331b7a84f726f085a2a4)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[9d79b4b](https://github.com/MicrosoftDocs/msteams-docs/pull/479/commits/9d79b4ba6099716e1a6e331b7a84f726f085a2a4)_: 

:clock10: **Full build**: average full build time is _24 sec(s)_ [calculated from last _1_ build(s)]

> Note: A full build takes more time than an incremental build. This is the expected behavior of the build system.

**Comment by lindalu-MSFT** [comment]
Header is not appearing in the docs, I think due to a typo in the "uhfHeaderID": "MSDocsHeader-Dev_MicrosoftTeams". I think the "Dev_" shouldn't be there... at least that's how it's working for other repos (ie. Outlook-dev-docs and office-js-docs-pr)

**Comment by o365devx** [comment]
OPS Build status updates of commit _[9d79b4b](https://github.com/MicrosoftDocs/msteams-docs/pull/479/commits/9d79b4ba6099716e1a6e331b7a84f726f085a2a4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/concepts/messaging-extensions/messaging-extensions-common.md](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/concepts/messaging-extensions/messaging-extensions-common.md) | :warning:Warning | | [Details](#user-content-msteams-platform%2Fconcepts%2Fmessaging-extensions%2Fmessaging-extensions-common.md)
[msteams-platform/docfx.json](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/docfx.json) | :white_check_mark:Succeeded | |

<a name="msteams-platform%2Fconcepts%2Fmessaging-extensions%2Fmessaging-extensions-common.md"></a>
### [msteams-platform/concepts/messaging-extensions/messaging-extensions-common.md](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/concepts/messaging-extensions/messaging-extensions-common.md)
 - **Line 5**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).
 - **Line 5**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).
 - **Line 5**: **[Warning]** Invalid file link:(~/get-started/code#microsoft-teams-extensions-for-the-bot-builder-sdk).
 - **Line 11**: **[Warning]** Invalid file link:(~/concepts/bots/bots-create).
 - **Line 11**: **[Warning]** Invalid file link:(~/concepts/bots/bots-create).
 - **Line 11**: **[Warning]** Invalid file link:(~/concepts/bots/bots-create).
 - **Line 17**: **[Warning]** Invalid file link:(~/resources/schema/manifest-schema#composeextensions).
 - **Line 17**: **[Warning]** Invalid file link:(~/resources/schema/manifest-schema#composeextensions).
 - **Line 17**: **[Warning]** Invalid file link:(~/resources/schema/manifest-schema#composeextensions).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C2%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903020014276974-479%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9P8fuGmUroPnVf3J%2F2F8b6KE%2Bl9VvSL%2FULDhL%2Bmk3lQ%3D&st=2019-03-02T00%3A10%3A51Z&se=2019-04-02T00%3A15%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clearab** [comment]
Can you point me to where the custom Teams header is loading? office-js-docs does seem to use the Dev_  https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/docfx.json. I can't seem to find any pages loading a custom header.

**Comment by clearab** [comment]
I'm also not seeing any difference in the header in the preview of this PR: https://review.docs.microsoft.com/en-us/microsoftteams/platform/overview?branch=lindalu-MSFT-patch-1

**Comment by lindalu-MSFT** [comment]
Hi, the header that appears on the Teams portal here on developer.microsoft.com: https://developer.microsoft.com/en-us/microsoft-teams should also appear on Teams content on Docs.microsoft.com.

To Repro:

  1.  Go to https://developer.microsoft.com/en-us/microsoft-teams.
  2.  On the Resources menu, click Docs.
  3.  In the swimlane titled Microsoft Teams Developer Documentation, click the first READ DOCS > link.

Result:
The default Docs header appears on the docsets.

Expect:
The custom Microsoft Teams developer header to appear.

It might take a while for the header to populate after the PR is merged to live.

Thanks
Linda

**Comment by clearab** [comment]
Ok, thanks for the additional information. I dug into the rendered code, and it looks like that header is using (/DEV_MicrosoftTeams/DEV_MicrosoftTeamsHeader):
image

I took a look at the header for Office Add-ins, and theirs looks like (/MSDocs/MSDocsHeader-Dev_Office):
image

In the Office Dev docfx.json it looks like:
"uhfHeaderId": "MSDocsHeader-Dev_Office"

So my assumption is the value we should be using is
"uhfHeaderId": "DEV_MicrosoftTeams-DEV_MicrosoftTeamsHeader"

Does that sound correct?

**Comment by o365devx** [comment]
OPS Build status updates of commit _[2830b9d](https://github.com/MicrosoftDocs/msteams-docs/pull/479/commits/2830b9db1054791a2fa0c97bf1f35e4da758b41a)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[2830b9d](https://github.com/MicrosoftDocs/msteams-docs/pull/479/commits/2830b9db1054791a2fa0c97bf1f35e4da758b41a)_: 

:clock10: **Full build**: average full build time is _30 sec(s)_ [calculated from last _2_ build(s)]

> Note: A full build takes more time than an incremental build. This is the expected behavior of the build system.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[2830b9d](https://github.com/MicrosoftDocs/msteams-docs/pull/479/commits/2830b9db1054791a2fa0c97bf1f35e4da758b41a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[msteams-platform/docfx.json](https://github.com/MicrosoftDocs/msteams-docs/blob/lindalu-MSFT-patch-1/msteams-platform/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C5%5Cd98cc23d-94e8-765b-0855-bdd8964dc537%5CPullRequest%5C201903052158002200-479%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=43R8e9Ldb%2Br6Z6o5OMOcvKGYE6S9K7jDmW9rbtVbpaU%3D&st=2019-03-05T21%3A54%3A20Z&se=2019-04-05T21%3A59%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
No, I think it should be “MSDocsHeader-DEV_MicrosoftTeams” but I will take the time to track down the engineer to verify for sure.

**Comment by clearab** [comment]
Hmm, that doesn't seem to be right either. Unless the header change just doesn't render in the review.doces.microsoft.com setup.

**Comment by clearab** [comment]
No worries, I can take it from here.

**Comment by lindalu-MSFT** [comment]
I’m working with the engineer right now, and he thinks perhaps it’s due to the typo in UHFHeaderId. He thinks it should be lowercase. Please accept the PR I just submitted so we can check.

**Pull request closed without merging**
