### PR TITLE
[Doc Improvement][Remove time and future ref: 11][3860144]

### PR DESCRIPTION
**Pull request by v-bvishnu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0820a5b50a77e7dc10ff14a606cfe06ca03594a9/msteams-platform%2Ftoolkit%2Ffaq.md) | 85 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd9b9c9e-d725-4fe9-a5ef-96ab65cfece3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/faq-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0820a5b50a77e7dc10ff14a606cfe06ca03594a9/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ffaq-v4.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd7500b2-9f8f-453f-b38d-bbfed6f2f2e2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce99bf91fc1fec544bc85149ff65f037f225a48b/msteams-platform%2Ftoolkit%2Ffaq.md) | 85 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1bda5271-5d93-42a8-a864-b3206110dc3d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/faq-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ce99bf91fc1fec544bc85149ff65f037f225a48b/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ffaq-v4.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23922b29-c941-4c8b-9dbd-a144e06b79a0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d92198031dc899e7b97270b770df501bf0364b5/msteams-platform%2Ftoolkit%2Ffaq.md) | 85 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/936416e4-effd-4ab2-b96d-279d4b8b7097) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/faq-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6d92198031dc899e7b97270b770df501bf0364b5/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ffaq-v4.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cbbecd35-647e-4f63-bf93-8e5f602eb352) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/faq.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba1642f4bc69d8ac18efcc55426d5ae4e452a04c/msteams-platform%2Ftoolkit%2Ffaq.md) | 85 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2f4b5768-9c6a-490c-ab20-95ab0d0f3d2e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/faq-v4.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba1642f4bc69d8ac18efcc55426d5ae4e452a04c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Ffaq-v4.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17420fe9-8c83-4bbe-9705-ed8b25cae03a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
