### PR TITLE
[Doc Improvement][Update tasks to dialog in meeting apps files][3480219]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/070be47e987557050cae452a8d5c1c8103ddadc7/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e279f156-770d-490d-970c-3add655f8153) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7aaa28cd202d3d840074c3ff2782e038bcb6f6b0/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9545c63-8560-4f18-8f2e-a672edc166ee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7aaa28cd202d3d840074c3ff2782e038bcb6f6b0/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56f22e04-8154-412d-9d75-17cd00ae16e6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b937e3e01d6939dff186f1b000626be472ab3b29/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56de326e-a01c-4f71-9b32-748d8f6e14ed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b937e3e01d6939dff186f1b000626be472ab3b29/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 91 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/050c8a8c-7cd6-4c54-93ac-639c5692f580) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/180dbea72030b31ac938d522027725995c40253a/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/93151a69-fc76-4f43-a78e-42917b5b8dee) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/180dbea72030b31ac938d522027725995c40253a/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7f24fae-21bf-4585-bafe-01cd0fff26c2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6753d9a560466ba86d48a10052d71f90b1d6cd80/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aac282fc-6ac8-4d51-b174-c543a37628fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/meeting-transcripts/fetch-id.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6753d9a560466ba86d48a10052d71f90b1d6cd80/msteams-platform%2Fgraph-api%2Fmeeting-transcripts%2Ffetch-id.md) | 90 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17d095ca-4fcc-4f72-90b6-86b03a5c4b5f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
