### PR TITLE
[Doc Improvement][Update Teams-Toolkit-CLI manifest parameters][3634069]

### PR DESCRIPTION
**Pull request by therealjohn**
Fix --manifest-file to match --teams-manifest-file for 2.x versions of the CLI

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b66c42e4fc985e3c4c29c06941f41ffdd85e8a37/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 88 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/302387ad-bdb8-44bf-95ad-b0c54d8d03d4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by ChetanSharma-msft — APPROVED** [review]
Changes looks fine, approving it.

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ff651529d0fd88e0547e65515fdb1fbf8a13ad07/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 88 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40f91019-26e4-4c4c-9266-0a0556b8f904) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e6d9cb663b012fc86466438d87485edf8e23c4e8/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 88 | 87 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9df708f-5b6f-4feb-9894-c9950d77ef5a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d91e62ba8442e2c60d9a6a3f92b4f74ccd08872d/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 88 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e653883d-e8e9-47dc-bd87-59e0eb1fb907) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/74ac676fb62c80f0d783dfd120cbe5610b76cac9/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 88 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec5a32ad-7ab1-47ba-8931-ab5967aebf70) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/bb83f3cf5f989dc65e642a8c80e85886424a226a/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 88 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1bf013cb-4e53-46fd-a34f-3bcff7e4c4de) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbe8d5ca491a5e98fa04169fcbdc104d8d5fe9d6/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 88 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc616320-f3d1-441f-a146-fb4c39669b4b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f9e29cf9b883d55d4d9ae9ceac3d262e8f8242b/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 88 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/299c6cca-4df7-4910-b401-b1951e15c738) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/TeamsFx-preview-and-customize-app-manifest.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f9e29cf9b883d55d4d9ae9ceac3d262e8f8242b/msteams-platform%2Ftoolkit%2FTeamsFx-preview-and-customize-app-manifest.md) | 87 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c79a5bca-c608-4864-b178-13df913a3f65) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/create-new-project.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7f9e29cf9b883d55d4d9ae9ceac3d262e8f8242b/msteams-platform%2Ftoolkit%2Fcreate-new-project.md) | 87 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd7a1e5f-35b9-4f0f-b577-36d4bc0b5fda) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3a8cfd47b8280eb5948e20e280c284cc751d35cb/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 88 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bf8b5a0e-25d9-405f-894e-ba939423d4a5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7d9f835f66701d3f3b77f8477e9046aba7fd8a42/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 88 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f49777a3-6872-473b-84fe-dcda2c9ae913) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2b54f1bec5f878b96e31faaa70999c3397e379f3/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 88 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2360c7a2-e68f-46f4-989c-5f9ddb0f6e45) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94bc7d147669ae91ce63015b9e07155a0016087c/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 88 | 86 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86be40cc-924c-498d-8de8-bbbf34a604ee) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/Teams-Toolkit-CLI.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ab715d0c254eb81404b3c10477cb751a90357e8/msteams-platform%2Ftoolkit%2FTeams-Toolkit-CLI.md) | 90 | 78 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/816433a0-aab8-4e69-89d9-9f86933957bd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
