### PR TITLE
[Doc Improvement][SEO meta description update][3939747]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-message-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abeb0244620fe449f5f69ed828c18143fc754472/msteams-platform%2Fresources%2Fbot-v3%2Fbots-message-format.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78973457-a825-41c3-8489-68aa5c43c79a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-text-formats.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abeb0244620fe449f5f69ed828c18143fc754472/msteams-platform%2Fresources%2Fbot-v3%2Fbots-text-formats.md) | 92 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/46b0bd9c-2305-465a-bdea-c397c365a945) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/faqs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abeb0244620fe449f5f69ed828c18143fc754472/msteams-platform%2Fresources%2Ffaqs.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb9b76a3-0c68-44c3-8668-321e5f4b150a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abeb0244620fe449f5f69ed828c18143fc754472/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e472cfd8-b520-46eb-8d5d-0b1f4a0f026a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/messaging-extensions-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abeb0244620fe449f5f69ed828c18143fc754472/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fmessaging-extensions-overview.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b2136ce-bfca-4f39-82cb-89b58fd57cd8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abeb0244620fe449f5f69ed828c18143fc754472/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 90 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/077a5db4-02ff-49cf-b73d-7758baddd29d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abeb0244620fe449f5f69ed828c18143fc754472/msteams-platform%2Fresources%2FmoodleInstructions.md) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83334b69-e73c-4dca-bb0a-8245f59b21dd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abeb0244620fe449f5f69ed828c18143fc754472/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aed35b56-478d-4528-8c86-704bb22dd80d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abeb0244620fe449f5f69ed828c18143fc754472/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 131 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/234dbf40-dfa3-4a1b-8b2d-77642487f732) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/abeb0244620fe449f5f69ed828c18143fc754472/msteams-platform%2Fresources%2Fteam-chat-member-api-changes.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de39cf00-8b72-4470-8d1e-e45594da0a36) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-message-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958e7dc0f8d161c47d2abf15828735b308e35191/msteams-platform%2Fresources%2Fbot-v3%2Fbots-message-format.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1d45cf79-4a39-41c9-a652-3ba39bb1a6dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-text-formats.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958e7dc0f8d161c47d2abf15828735b308e35191/msteams-platform%2Fresources%2Fbot-v3%2Fbots-text-formats.md) | 92 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/775a6123-0f70-4109-a057-29c34a61fb22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/faqs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958e7dc0f8d161c47d2abf15828735b308e35191/msteams-platform%2Fresources%2Ffaqs.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4a4a7553-09b3-441e-aca2-ca31b95af232) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958e7dc0f8d161c47d2abf15828735b308e35191/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/446a6698-2742-4f36-8ca9-fb7e8badc003) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/messaging-extensions-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958e7dc0f8d161c47d2abf15828735b308e35191/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fmessaging-extensions-overview.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4d1bfaed-b113-4e0a-a592-2efd4e09dde3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958e7dc0f8d161c47d2abf15828735b308e35191/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 90 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5a5da7b4-887e-4ee8-a77c-b2cf530dac6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958e7dc0f8d161c47d2abf15828735b308e35191/msteams-platform%2Fresources%2FmoodleInstructions.md) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4f726ba3-adab-4836-936f-ad27e0c3fa89) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958e7dc0f8d161c47d2abf15828735b308e35191/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d7e2cc89-644d-4e6f-bf76-5547811098ce) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958e7dc0f8d161c47d2abf15828735b308e35191/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 131 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3eeedc14-0cb7-4adb-a797-b562040fa1a8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/958e7dc0f8d161c47d2abf15828735b308e35191/msteams-platform%2Fresources%2Fteam-chat-member-api-changes.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0b5628f8-8c95-47b3-9ceb-206d62422f7c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-message-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/594267ffe133182013a9bcb1faf5d20ea27ae36c/msteams-platform%2Fresources%2Fbot-v3%2Fbots-message-format.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/279be1bb-930d-4d37-9a46-6913106ee035) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-text-formats.md](https://github.com/MicrosoftDocs/msteams-docs/blob/594267ffe133182013a9bcb1faf5d20ea27ae36c/msteams-platform%2Fresources%2Fbot-v3%2Fbots-text-formats.md) | 92 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/28cb306d-a777-44f6-aad4-bd56ce5e0930) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/faqs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/594267ffe133182013a9bcb1faf5d20ea27ae36c/msteams-platform%2Fresources%2Ffaqs.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e7aabf4-ce7f-4a02-96bb-1bba652192b6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/594267ffe133182013a9bcb1faf5d20ea27ae36c/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f313f536-9463-48a8-9dcf-d519c951d33c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/messaging-extensions-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/594267ffe133182013a9bcb1faf5d20ea27ae36c/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fmessaging-extensions-overview.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8aee6640-154d-4b55-85cf-5b8b37e945c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/594267ffe133182013a9bcb1faf5d20ea27ae36c/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 90 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f91e402-1c47-44f2-8992-dc992886742c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/594267ffe133182013a9bcb1faf5d20ea27ae36c/msteams-platform%2Fresources%2FmoodleInstructions.md) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d184ee69-3802-4502-84d0-e71331de81fa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/594267ffe133182013a9bcb1faf5d20ea27ae36c/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10fba0bf-2a76-4351-b957-09bd45d9c852) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/594267ffe133182013a9bcb1faf5d20ea27ae36c/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 131 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57c15344-6b52-4548-953d-ff672ff6a0a4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/594267ffe133182013a9bcb1faf5d20ea27ae36c/msteams-platform%2Fresources%2Fteam-chat-member-api-changes.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d65c6b0b-2d6f-4866-8648-edd6a8b6b057) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-sdhakshina — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-message-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43dee7100454da79577334150459f29b7321b88b/msteams-platform%2Fresources%2Fbot-v3%2Fbots-message-format.md) | 96 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04026723-da65-4393-bcf1-2d702c2963e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-text-formats.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43dee7100454da79577334150459f29b7321b88b/msteams-platform%2Fresources%2Fbot-v3%2Fbots-text-formats.md) | 92 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e064c9c-6e26-4e42-8f99-c675073656c4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/faqs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43dee7100454da79577334150459f29b7321b88b/msteams-platform%2Fresources%2Ffaqs.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fa6e85a5-999d-4d54-b781-dde4c6229a44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/create-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43dee7100454da79577334150459f29b7321b88b/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fcreate-extensions.md) | 91 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27269c7d-ee47-495f-9454-be816981930c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/messaging-extensions-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43dee7100454da79577334150459f29b7321b88b/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fmessaging-extensions-overview.md) | 94 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/99ec3b53-5881-4a35-a8e2-775642a9e2f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/messaging-extension-v3/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43dee7100454da79577334150459f29b7321b88b/msteams-platform%2Fresources%2Fmessaging-extension-v3%2Fsearch-extensions.md) | 90 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e73a5cf7-0358-47bc-b1d4-af4b292fbc5c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/moodleInstructions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43dee7100454da79577334150459f29b7321b88b/msteams-platform%2Fresources%2FmoodleInstructions.md) | 88 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4e5910b4-fa80-497d-9b11-0a554defbaf0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/localization-schema.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43dee7100454da79577334150459f29b7321b88b/msteams-platform%2Fresources%2Fschema%2Flocalization-schema.md) | 99 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a96a8af-160e-4899-88f0-9c872bd016aa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/schema/manifest-schema-dev-preview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43dee7100454da79577334150459f29b7321b88b/msteams-platform%2Fresources%2Fschema%2Fmanifest-schema-dev-preview.md) | 83 | 131 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01cbf142-2dea-4738-ad8c-032a1a17dae0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/team-chat-member-api-changes.md](https://github.com/MicrosoftDocs/msteams-docs/blob/43dee7100454da79577334150459f29b7321b88b/msteams-platform%2Fresources%2Fteam-chat-member-api-changes.md) | 90 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fc2c4c78-76d7-4eb3-8631-c7a044460456) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
