### PR TITLE
[Doc improvement][SEO7 Meta title Update][3876683]

### PR DESCRIPTION
**Pull request by v-ramyas5**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/test-chat-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a2ed9abf0df9693fc61d15750ae1402f3eeb17e/msteams-platform%2Fgraph-api%2Frsc%2Ftest-chat-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/95c807fb-e358-46c4-b07e-9ef37f14e481) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a2ed9abf0df9693fc61d15750ae1402f3eeb17e/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e68c399-dd05-4d3f-8722-c101e4cef971) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-team-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a2ed9abf0df9693fc61d15750ae1402f3eeb17e/msteams-platform%2Fgraph-api%2Frsc%2Ftest-team-rsc-json-file.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f375b488-898f-4456-92c2-45a1d4b4b6ae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365-quick-start-guide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a2ed9abf0df9693fc61d15750ae1402f3eeb17e/msteams-platform%2Fm365-apps%2Factions-in-m365-quick-start-guide.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b29095bf-c566-4dd7-8a98-c6a930f0cddf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a2ed9abf0df9693fc61d15750ae1402f3eeb17e/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/29e1fd78-908a-4bc7-859e-92430c669529) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-meeting-app.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a2ed9abf0df9693fc61d15750ae1402f3eeb17e/msteams-platform%2Fm365-apps%2Fextend-m365-meeting-app.md) | 92 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/60f5212e-36b0-4e17-9eca-e654c33299e2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a2ed9abf0df9693fc61d15750ae1402f3eeb17e/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a79e7ad3-ff4b-4e09-8793-a5bb3116bd0f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a2ed9abf0df9693fc61d15750ae1402f3eeb17e/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0124bc6f-4715-45b8-8727-b1f25295a94c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a2ed9abf0df9693fc61d15750ae1402f3eeb17e/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 95 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f60d81b-3c56-4c5f-8369-fb8a3781117a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9a2ed9abf0df9693fc61d15750ae1402f3eeb17e/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d05935dc-aa46-4c29-aab2-40b81bbdcbf2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/test-chat-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/392637eda83f8f1356b3af35c3104d171784206a/msteams-platform%2Fgraph-api%2Frsc%2Ftest-chat-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/06be9fe6-857d-403c-9070-84b97e00579c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/392637eda83f8f1356b3af35c3104d171784206a/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/441253f2-20bc-413c-8fd3-a93b7259860d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-team-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/392637eda83f8f1356b3af35c3104d171784206a/msteams-platform%2Fgraph-api%2Frsc%2Ftest-team-rsc-json-file.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89fd27ed-1c01-40ca-870f-904a23b67cae) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365-quick-start-guide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/392637eda83f8f1356b3af35c3104d171784206a/msteams-platform%2Fm365-apps%2Factions-in-m365-quick-start-guide.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9adb5df-c3bf-4953-88b4-d2954d6bf722) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/392637eda83f8f1356b3af35c3104d171784206a/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/afa2964c-bffb-4a7f-8fca-a66c81017c62) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/392637eda83f8f1356b3af35c3104d171784206a/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cb87f9d2-4cae-4a51-8917-8b0979f2b284) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/392637eda83f8f1356b3af35c3104d171784206a/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9073faab-4456-48ad-b964-7690e8d75b23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/392637eda83f8f1356b3af35c3104d171784206a/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4246b324-4a31-44ee-b2c0-5fbfb1779483) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/392637eda83f8f1356b3af35c3104d171784206a/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 95 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfcd814a-49d4-4a02-9459-a7333c3d6bad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/392637eda83f8f1356b3af35c3104d171784206a/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3aedb6d4-1b58-4aea-b2bd-d9ba902880c6) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/test-chat-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d09cb0f6cd05ba7cec92b63275ee791c918ed2cd/msteams-platform%2Fgraph-api%2Frsc%2Ftest-chat-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/816ded92-b26a-48fd-a55f-5ce1783efa98) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d09cb0f6cd05ba7cec92b63275ee791c918ed2cd/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7deda750-f5f9-4343-844c-763b21dacb5e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-team-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d09cb0f6cd05ba7cec92b63275ee791c918ed2cd/msteams-platform%2Fgraph-api%2Frsc%2Ftest-team-rsc-json-file.md) | 93 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1168dd2-9bcc-486c-b47b-2c931e3333be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365-quick-start-guide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d09cb0f6cd05ba7cec92b63275ee791c918ed2cd/msteams-platform%2Fm365-apps%2Factions-in-m365-quick-start-guide.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c0c73b2-66cd-4e3b-8102-3b6637be4960) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d09cb0f6cd05ba7cec92b63275ee791c918ed2cd/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a9295dc3-f987-48ac-9eef-5c98edb49637) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d09cb0f6cd05ba7cec92b63275ee791c918ed2cd/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cd6aad76-f505-49a0-95ce-04f1f50f6a92) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d09cb0f6cd05ba7cec92b63275ee791c918ed2cd/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/44e7d974-b3be-4c84-a43c-36195691dd7a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d09cb0f6cd05ba7cec92b63275ee791c918ed2cd/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4b2267a6-dd82-4984-bc6b-50e32ccaa03b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d09cb0f6cd05ba7cec92b63275ee791c918ed2cd/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 95 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d00047e3-98e0-436c-b378-f873acea08c8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d09cb0f6cd05ba7cec92b63275ee791c918ed2cd/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01479116-574c-4ca8-bce0-634e2159fcbb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/test-chat-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8166e4cb46677706b9eaee6b65ba59e90f405fb/msteams-platform%2Fgraph-api%2Frsc%2Ftest-chat-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cecac7c1-5c5e-4be6-8b48-58b95f171753) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8166e4cb46677706b9eaee6b65ba59e90f405fb/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/63f4e2a7-b7be-4b5e-bbde-88b595f6ce47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-team-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8166e4cb46677706b9eaee6b65ba59e90f405fb/msteams-platform%2Fgraph-api%2Frsc%2Ftest-team-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b086ead-01c1-4171-b6c5-ae4c6afbd09f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365-quick-start-guide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8166e4cb46677706b9eaee6b65ba59e90f405fb/msteams-platform%2Fm365-apps%2Factions-in-m365-quick-start-guide.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e3f8225-0853-4b40-804c-476fa8b39cb3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8166e4cb46677706b9eaee6b65ba59e90f405fb/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e1fd8dd1-a04c-4a21-8cbf-a9ed78820825) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8166e4cb46677706b9eaee6b65ba59e90f405fb/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac501f31-e963-416b-a9fa-2eb64e21e944) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8166e4cb46677706b9eaee6b65ba59e90f405fb/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/258f59c6-431b-46e6-be64-252a18d7912f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8166e4cb46677706b9eaee6b65ba59e90f405fb/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0f889e2-54b1-4ce1-99de-1fdf902eb907) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8166e4cb46677706b9eaee6b65ba59e90f405fb/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 95 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16721e9b-b980-4972-8eaf-e1283c4e46c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e8166e4cb46677706b9eaee6b65ba59e90f405fb/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/693b407c-03bf-4f6e-820d-1637570e0f32) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/test-chat-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac139bcb931d20510dc8986fa4be64694b0d0ef3/msteams-platform%2Fgraph-api%2Frsc%2Ftest-chat-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/923ca40c-726f-4afe-aa35-4164d6efdd52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac139bcb931d20510dc8986fa4be64694b0d0ef3/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1a335881-65f5-4831-b332-62d9e1ab8243) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-team-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac139bcb931d20510dc8986fa4be64694b0d0ef3/msteams-platform%2Fgraph-api%2Frsc%2Ftest-team-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ebef7ccb-09db-48e2-9cac-29c098e294fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365-quick-start-guide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac139bcb931d20510dc8986fa4be64694b0d0ef3/msteams-platform%2Fm365-apps%2Factions-in-m365-quick-start-guide.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e66fa8e1-3f8f-45f8-b179-dfd485b2dd15) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac139bcb931d20510dc8986fa4be64694b0d0ef3/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f3ba63b-6775-443a-ad1e-93435ab93e47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac139bcb931d20510dc8986fa4be64694b0d0ef3/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a0178d0-51d9-40b4-a7e4-3f62b19af1bd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac139bcb931d20510dc8986fa4be64694b0d0ef3/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/33365033-0dc4-44ad-af46-7ebe29692573) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac139bcb931d20510dc8986fa4be64694b0d0ef3/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5fc52fc4-4298-48ba-9382-f309607c6d1d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac139bcb931d20510dc8986fa4be64694b0d0ef3/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 95 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/792e6d22-3d2a-429f-8664-770c266180e0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ac139bcb931d20510dc8986fa4be64694b0d0ef3/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0fdd0fca-38b8-4288-83bf-d29df24d4120) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/graph-api/rsc/test-chat-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dab4eaabd6d57802887b89525bb8d34c8efcc51/msteams-platform%2Fgraph-api%2Frsc%2Ftest-chat-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/029999fb-68fc-49d3-adea-44c717309317) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-resource-specific-consent.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dab4eaabd6d57802887b89525bb8d34c8efcc51/msteams-platform%2Fgraph-api%2Frsc%2Ftest-resource-specific-consent.md) | 93 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f1c240d-4571-4e8a-bfce-1dd86df22807) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/graph-api/rsc/test-team-rsc-json-file.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dab4eaabd6d57802887b89525bb8d34c8efcc51/msteams-platform%2Fgraph-api%2Frsc%2Ftest-team-rsc-json-file.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d76fc8eb-b438-4e1b-ad00-960cf18083a6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/actions-in-m365-quick-start-guide.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dab4eaabd6d57802887b89525bb8d34c8efcc51/msteams-platform%2Fm365-apps%2Factions-in-m365-quick-start-guide.md) | 89 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6fd2afd2-24cf-4353-b096-09a285303053) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/cards-loop-component.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dab4eaabd6d57802887b89525bb8d34c8efcc51/msteams-platform%2Fm365-apps%2Fcards-loop-component.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c213246-50fc-4acc-ad44-67a7b67dba46) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-message-extension.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dab4eaabd6d57802887b89525bb8d34c8efcc51/msteams-platform%2Fm365-apps%2Fextend-m365-teams-message-extension.md) | 89 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32d06abf-e3b7-4245-beaf-84d655c7af4c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/extend-m365-teams-personal-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dab4eaabd6d57802887b89525bb8d34c8efcc51/msteams-platform%2Fm365-apps%2Fextend-m365-teams-personal-tab.md) | 96 | 26 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/536c0206-9c4b-4a91-b401-dda9515362e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/me-or-outlook-add-in.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dab4eaabd6d57802887b89525bb8d34c8efcc51/msteams-platform%2Fm365-apps%2Fme-or-outlook-add-in.md) | 97 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f6f2a69b-ed85-4704-9e68-10c13fc001d1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/prerequisites.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dab4eaabd6d57802887b89525bb8d34c8efcc51/msteams-platform%2Fm365-apps%2Fprerequisites.md) | 95 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/520d7754-f652-46f9-b51e-82f82c09b2eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/m365-apps/teamsjs-support-m365.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3dab4eaabd6d57802887b89525bb8d34c8efcc51/msteams-platform%2Fm365-apps%2Fteamsjs-support-m365.md) | 93 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/55fe44e4-6408-46de-b247-87b4718c9973) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
