### PR TITLE
[Doc Improvement][Meta description update][3860115]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/607eb873da6b324cdc89ebdbe949fc116981a55f/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b33e8422-0336-46dc-a434-96afd2ae7de3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/real-time-media-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/607eb873da6b324cdc89ebdbe949fc116981a55f/msteams-platform%2Fbots%2Fcalls-and-meetings%2Freal-time-media-concepts.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4924b47-3440-467b-a963-0262b70ba5fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/607eb873da6b324cdc89ebdbe949fc116981a55f/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2dc651e6-9cda-45df-a52f-79592b72b9eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/607eb873da6b324cdc89ebdbe949fc116981a55f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4adb18db-0dc3-44eb-9bfd-88f99b8b8e79) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/607eb873da6b324cdc89ebdbe949fc116981a55f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86fbfc18-8918-4b9c-8a12-aeb33aed778c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/607eb873da6b324cdc89ebdbe949fc116981a55f/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08a3a1ad-d4d1-4e4b-b7d5-ef17efa7cd22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/607eb873da6b324cdc89ebdbe949fc116981a55f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/78f15984-74e2-430d-b5ef-e08e86326fa0) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/192514b6c5a78f0bbb90db9fcbd7f879be33906a/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d555feb6-740b-4543-85a8-1c3d14e6ceef) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/real-time-media-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/192514b6c5a78f0bbb90db9fcbd7f879be33906a/msteams-platform%2Fbots%2Fcalls-and-meetings%2Freal-time-media-concepts.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/de698067-7670-4749-90ee-9e73563af164) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/192514b6c5a78f0bbb90db9fcbd7f879be33906a/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 88 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2caf732a-a23c-4687-976d-5e67bf046e62) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/192514b6c5a78f0bbb90db9fcbd7f879be33906a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0441d4cc-10ca-452d-aede-b7e8f61f610c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/192514b6c5a78f0bbb90db9fcbd7f879be33906a/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed4fdbac-4e75-4854-873c-4ad17b35ec62) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/192514b6c5a78f0bbb90db9fcbd7f879be33906a/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/473d95a5-7813-44e1-bfe7-77aac7c7d3d6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/192514b6c5a78f0bbb90db9fcbd7f879be33906a/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42bd3bed-a3b3-44e0-9051-91041f8d07b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/192514b6c5a78f0bbb90db9fcbd7f879be33906a/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Foverview.md) | 88 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b34625a-23d2-4d67-baea-dbd3e500eace) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fbd031e52becef3da40efbe29017ce79f720c531/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc80ff5e-924e-4cd2-a544-7f95e6fa11e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/real-time-media-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fbd031e52becef3da40efbe29017ce79f720c531/msteams-platform%2Fbots%2Fcalls-and-meetings%2Freal-time-media-concepts.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b886fa8-21ef-4a48-9bba-0e915d9d97db) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fbd031e52becef3da40efbe29017ce79f720c531/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 88 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f023d259-62e0-484a-85fe-73e92a1e90c7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fbd031e52becef3da40efbe29017ce79f720c531/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/771cab2d-dad9-45db-b3fb-18781d1f856d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fbd031e52becef3da40efbe29017ce79f720c531/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d59600dc-c50a-4ae7-9905-962d3b5f3d2d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fbd031e52becef3da40efbe29017ce79f720c531/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d0b603f7-759f-4ba7-bbb9-0a056424a5c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fbd031e52becef3da40efbe29017ce79f720c531/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/02f9663f-e0d3-405e-9667-b4dcd00e4dd9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fbd031e52becef3da40efbe29017ce79f720c531/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Foverview.md) | 88 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89e78f2a-7524-48b1-970f-e42736bb5eb7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/teams-store-ranking-parameters.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fbd031e52becef3da40efbe29017ce79f720c531/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fteams-store-ranking-parameters.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9a7fcec-1cf9-453d-9979-8dac84f9773f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fbd031e52becef3da40efbe29017ce79f720c531/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/08a5d09a-4f69-4131-a7e2-1b2f7a9d11b4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbc116720c3ef229051baa3a8929652f369e8d87/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5b3b159-2674-46f7-a946-542393f4eb16) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/real-time-media-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbc116720c3ef229051baa3a8929652f369e8d87/msteams-platform%2Fbots%2Fcalls-and-meetings%2Freal-time-media-concepts.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f7906a38-1c68-4e70-a632-c01d57b1128e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbc116720c3ef229051baa3a8929652f369e8d87/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 88 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/763926c5-0f70-41ea-82bc-778ef24548be) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbc116720c3ef229051baa3a8929652f369e8d87/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/18c0deb2-5440-45cc-bd7f-fad76ab436c1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbc116720c3ef229051baa3a8929652f369e8d87/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e6b5f89-9090-4b45-98f2-f7fc80c58926) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbc116720c3ef229051baa3a8929652f369e8d87/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4662306d-4ed3-4035-92c6-c9e4da9de3d7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbc116720c3ef229051baa3a8929652f369e8d87/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8ee1e528-f7c5-41a6-a3df-251f766bee24) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbc116720c3ef229051baa3a8929652f369e8d87/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Foverview.md) | 88 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17c341ec-0a98-43be-97e8-f8b06bea2655) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/teams-store-ranking-parameters.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbc116720c3ef229051baa3a8929652f369e8d87/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fteams-store-ranking-parameters.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d9d4d7da-83ac-4af2-ad59-4f35545b3bdf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dbc116720c3ef229051baa3a8929652f369e8d87/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e7315a34-23d3-493d-82e0-99a98fe5c9c3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be35be2093699161c649b4d11db44aed5ff5367f/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/68186f24-f2f6-4649-ada3-49ca999a36f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/real-time-media-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be35be2093699161c649b4d11db44aed5ff5367f/msteams-platform%2Fbots%2Fcalls-and-meetings%2Freal-time-media-concepts.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/49b34bdd-4a07-4c2a-8b1b-f974e07eae0d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be35be2093699161c649b4d11db44aed5ff5367f/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 88 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1bea8d26-3c89-4e88-91d6-e98259abf561) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be35be2093699161c649b4d11db44aed5ff5367f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2a2e134f-f5d8-4b29-9d50-8ca4097d188c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be35be2093699161c649b4d11db44aed5ff5367f/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/75b3dfc6-7f13-44d3-827a-5c1867a7bddd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be35be2093699161c649b4d11db44aed5ff5367f/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/00b31948-57a7-48a0-82c3-4e560ce7d209) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be35be2093699161c649b4d11db44aed5ff5367f/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/71ea8edd-3139-4b3e-b2c4-47a8282e5d37) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be35be2093699161c649b4d11db44aed5ff5367f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Foverview.md) | 88 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ee820a72-ca13-4bed-bcfc-d107ef8c006e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/teams-store-ranking-parameters.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be35be2093699161c649b4d11db44aed5ff5367f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fteams-store-ranking-parameters.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/afcd2ead-7b11-42d6-8d1a-f0f1051b7b8d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/be35be2093699161c649b4d11db44aed5ff5367f/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4dfb5133-a9cb-4b8a-bc08-a552052f91a3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/calls-and-meetings/calls-meetings-bots-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d96731c08fe521e88e664bec9cb1b40a060d45be/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fcalls-meetings-bots-overview.md) | 89 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b6ddbc8a-3468-4dd6-a3bf-b8149f756883) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/real-time-media-concepts.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d96731c08fe521e88e664bec9cb1b40a060d45be/msteams-platform%2Fbots%2Fcalls-and-meetings%2Freal-time-media-concepts.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87a760b1-7662-4348-8d59-79da8ed81545) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/calls-and-meetings/registering-calling-bot.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d96731c08fe521e88e664bec9cb1b40a060d45be/msteams-platform%2Fbots%2Fcalls-and-meetings%2Fregistering-calling-bot.md) | 88 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c7844d1b-9f59-4f36-9013-6c93b5cc07fb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/channel-and-group-conversations.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d96731c08fe521e88e664bec9cb1b40a060d45be/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fchannel-and-group-conversations.md) | 89 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/aba02cad-4d1b-425d-84fc-c9814c86d2de) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/how-to/conversations/subscribe-to-conversation-events.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d96731c08fe521e88e664bec9cb1b40a060d45be/msteams-platform%2Fbots%2Fhow-to%2Fconversations%2Fsubscribe-to-conversation-events.md) | 90 | 21 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9baba7c9-86af-4eef-954c-19e97f446989) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/app-fundamentals-overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d96731c08fe521e88e664bec9cb1b40a060d45be/msteams-platform%2Fconcepts%2Fapp-fundamentals-overview.md) | 90 | 18 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cf9e41c2-0dc6-4e5f-94c7-987d809f193a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d96731c08fe521e88e664bec9cb1b40a060d45be/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 91 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/98fd8b8c-1768-4162-85cd-7addf16300cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/overview.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d96731c08fe521e88e664bec9cb1b40a060d45be/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Foverview.md) | 88 | 27 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/26571f01-ebd1-4172-8c43-91d8ca8d8d8a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/post-publish/teams-store-ranking-parameters.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d96731c08fe521e88e664bec9cb1b40a060d45be/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpost-publish%2Fteams-store-ranking-parameters.md) | 96 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f9fb5b4b-a890-460f-8434-55af3857bd50) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d96731c08fe521e88e664bec9cb1b40a060d45be/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fprepare%2Finclude-saas-offer.md) | 90 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a1163ee-4fa2-47f9-b0d7-87681a82dcdf) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — DISMISSED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Review by v-deabira — APPROVED** [review]

**Pull request merged**
