### PR TITLE
[Doc Improvement][Teams 2.1 update][3417008] 

### PR DESCRIPTION
**Pull request by v-ganr**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-notificationbot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/4b2aac523019c22680f47bd9d7df5e2ed37069a1/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-notificationbot-v4.yml) | 86 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/027895a9-35bb-411a-ba32-2b2803c325e9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-notificationbot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e27d61363a056386e27364bd12cf2427ca21285c/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-notificationbot-v4.yml) | 86 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/43b2e303-be43-4acb-9c9c-448c496dd163) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-notificationbot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8efe04b51eff6763ecff22acba607edb56ed9218/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-notificationbot-v4.yml) | 86 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d146ad9-b69c-43f6-93ff-302582fdba84) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/prepare-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d2abc9297cc0411526c5d26af5880df8543d81a4/msteams-platform%2Fincludes%2Fget-started%2Fprepare-teams-toolkit.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/51f8f998-0472-4b76-891f-c98ac64a6751) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-notificationbot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d2abc9297cc0411526c5d26af5880df8543d81a4/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-notificationbot-v4.yml) | 86 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/563cff82-378b-4533-93ef-002cddd3e3d5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/prepare-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f0a9f705610654e96bcee466f09a83883c7254f5/msteams-platform%2Fincludes%2Fget-started%2Fprepare-teams-toolkit.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f8bd2794-82e7-4a3e-9234-456a80c58867) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-notificationbot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f0a9f705610654e96bcee466f09a83883c7254f5/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-notificationbot-v4.yml) | 86 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20b13bf9-aece-46f5-8598-995993cb5f21) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/prepare-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e1e58af5fa4a1cc75c48388a39605c8d2c62fc55/msteams-platform%2Fincludes%2Fget-started%2Fprepare-teams-toolkit.md) | 86 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/91c06765-7dd8-4da4-9261-e9fdff5cc17d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-notificationbot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e1e58af5fa4a1cc75c48388a39605c8d2c62fc55/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-notificationbot-v4.yml) | 87 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0a06a2b8-72a7-4307-b0da-ba47226099c7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/prepare-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0912edd0cecbc7398974f4606bff0e6029fc1df3/msteams-platform%2Fincludes%2Fget-started%2Fprepare-teams-toolkit.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e28cb727-bb1c-4c05-8af3-0adffa5d1f10) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-notificationbot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/0912edd0cecbc7398974f4606bff0e6029fc1df3/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-notificationbot-v4.yml) | 87 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7eb6b560-db99-4f44-ba1e-f5af754c8031) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/includes/get-started/prepare-teams-toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d15ffbeb15ba27f4afcc1b7fbfe826651a168d4f/msteams-platform%2Fincludes%2Fget-started%2Fprepare-teams-toolkit.md) | 91 | 11 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9b04b5cb-d5a6-47ae-9dcf-712f512540d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/toolkit-v4/sbs-v4/sbs-gs-notificationbot-v4.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/d15ffbeb15ba27f4afcc1b7fbfe826651a168d4f/msteams-platform%2Ftoolkit%2Ftoolkit-v4%2Fsbs-v4%2Fsbs-gs-notificationbot-v4.yml) | 87 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0c23854-87d6-4f33-a501-9321adcd9d87) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
