### PR TITLE
[Doc Improvement][document-signing]

### PR DESCRIPTION
**Pull request by v-shalinirobinson**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/07df31ddbc7a1de6c2fdf8a8acb1d3aea12ca192/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7b3b5fb0-4c79-4e62-b2b4-02de7cb1d5cd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/in-meeting-notification-for-meeting.md](https://github.com/MicrosoftDocs/msteams-docs/blob/07df31ddbc7a1de6c2fdf8a8acb1d3aea12ca192/msteams-platform%2Fapps-in-teams-meetings%2Fin-meeting-notification-for-meeting.md) | 95 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a912c608-a1eb-4e58-b851-dcb04108def2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/07df31ddbc7a1de6c2fdf8a8acb1d3aea12ca192/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 86 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bb8a829e-9166-433f-9683-2e59c3373787) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/07df31ddbc7a1de6c2fdf8a8acb1d3aea12ca192/msteams-platform%2Fwhats-new.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bcacd44b-3f13-485f-bcbe-3ea9f66516f1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/8778ac13dbae5323e7ca977eca8ef020113c4110/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6b1590b-8dbe-4597-9b98-3a90831fb8e9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/8778ac13dbae5323e7ca977eca8ef020113c4110/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 86 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/299cefd7-edea-41f9-b4d6-184c7d96b921) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efb0ccda489a70cfbc1a32ce3dd79cb77def2798/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9bd7be4b-f5e1-4c33-91d3-0fd1cac16c20) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/efb0ccda489a70cfbc1a32ce3dd79cb77def2798/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 86 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/05e1ac95-00d0-4fa8-94da-fc1f8d8929df) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/efb0ccda489a70cfbc1a32ce3dd79cb77def2798/msteams-platform%2Fwhats-new.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ed9ad9d9-11fe-4664-8c19-42a0b2112d69) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-teams-meeting-stage.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b77c0b9685e5fca90c4a71fc2128bd07cf8a0d2a/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-teams-meeting-stage.md) | 92 | 15 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/307ffcb0-12ce-497a-a389-2910d311768d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-inmeeting-document-signing.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/b77c0b9685e5fca90c4a71fc2128bd07cf8a0d2a/msteams-platform%2Fsbs-inmeeting-document-signing.yml) | 86 | 32 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c1944c2-ecba-4f8c-bde7-248d9e761d42) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b77c0b9685e5fca90c4a71fc2128bd07cf8a0d2a/msteams-platform%2Fwhats-new.md) | 92 | 36 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7cd3e9e2-261c-4a5a-8fd7-f516ec12614d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
