### PR TITLE
[Doc Improvement][update add API connection][2474589]

### PR DESCRIPTION
**Pull request by v-habibaumme**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cf4d37b7825c5c28a2f2833142cb83c046663fdc/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c94998ef-7d3b-415b-bc6a-ad2f5e17dff4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/377d91ac1a0f0b1e7d679435f7b596d6cd6d9508/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 88 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2ca30bf-9cf7-451b-a101-f27965b0ad72) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/377d91ac1a0f0b1e7d679435f7b596d6cd6d9508/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 81 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f974c2bf-af47-4d33-bbbd-3a5248211d76) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/acb4122c7fe9eb20b21d37bfd578b1d055d29a56/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 88 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d1619a75-cd45-4baa-b29a-8073b1b5fa6b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/acb4122c7fe9eb20b21d37bfd578b1d055d29a56/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 81 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7c84413c-2699-4e22-828e-0e4e1c730c0c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/deploy-and-publish/appsource/publish.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0f93a2b9cd8f8af58a995acfd523fae3e6b2e20/msteams-platform%2Fconcepts%2Fdeploy-and-publish%2Fappsource%2Fpublish.md) | 88 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ee07abc-4432-4df6-af69-a3c186353a21) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-test.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0f93a2b9cd8f8af58a995acfd523fae3e6b2e20/msteams-platform%2Fresources%2Fbot-v3%2Fbots-test.md) | 82 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/510a7fc1-43d7-4af1-b0c4-02d1303672cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/resources/bot-v3/bots-with-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0f93a2b9cd8f8af58a995acfd523fae3e6b2e20/msteams-platform%2Fresources%2Fbot-v3%2Fbots-with-tabs.md) | 88 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b3944b0d-ceb9-4508-9b14-9c4e1993ebe7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/add-API-connection.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a0f93a2b9cd8f8af58a995acfd523fae3e6b2e20/msteams-platform%2Ftoolkit%2Fadd-API-connection.md) | 81 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e57d9137-8df6-44ab-a0c8-1c1ee8d40599) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
