### PR TITLE
build-env-ttk-edits

### PR DESCRIPTION
**Pull request by Namitha-23**
build-environments.md

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99df973d87196c983b77001aec44a7aed9da19de/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/56ff796c-f0be-4969-8068-6eb2f9093f4f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/99df973d87196c983b77001aec44a7aed9da19de/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c9ede113-ed99-4c0a-aeef-1022af307447) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aefa9f36de9ba39a2a4b25251bb8e0d24048cb0/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ffc870dd-56af-402a-a862-fcc1af207ffa) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6aefa9f36de9ba39a2a4b25251bb8e0d24048cb0/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a4e870b1-e487-42f1-9bfd-0fc298fe57c5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8f83e0103f6c0833352733b3a73b0573a7c8e18/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dfd104b6-8226-40be-9e12-e59a472a5ac8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/d8f83e0103f6c0833352733b3a73b0573a7c8e18/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 91 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1b6cb417-276d-4ed0-8792-ecdda0d63662) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a3068ebc49181a749c3b8e5dea5a514169e678f/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 97 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/36bf0946-ecba-4f79-95e4-261f1d698ef4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1a3068ebc49181a749c3b8e5dea5a514169e678f/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/287d046b-dd3a-43b4-a8f0-3f16f09166d9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7490e29196c896adb320bff076303e15160977b2/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1f12e9ec-5205-4ef6-9282-e7d0a13f2ce2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7490e29196c896adb320bff076303e15160977b2/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 89 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3b15d4ab-0bb3-492e-b541-841446f6a42a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b0a3838df4a25165070953cc48dd19406790485/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a94e613f-9e1d-4681-82ab-57c4fc464061) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/3b0a3838df4a25165070953cc48dd19406790485/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 98 | 2 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/903ff673-de27-43b0-815a-c2031f4ff15f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/toolkit/build-environments.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e12277dc5486096629d6e7b4921e1e255cb4b86e/msteams-platform%2Ftoolkit%2Fbuild-environments.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac9bdd5c-e0a5-45d2-b680-84e9e693b836) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/toolkit/install-Teams-Toolkit.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e12277dc5486096629d6e7b4921e1e255cb4b86e/msteams-platform%2Ftoolkit%2Finstall-Teams-Toolkit.md) | 100 | 1 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/92e0c6db-c1ea-4757-b82e-654a9520a545) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
