### PR TITLE
[Doc Improvement][Update task modules to dialogs][3465457]

### PR DESCRIPTION
**Pull request by v-preethah**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48aeedb7b3a21aca7f4c7b776c4b4fa35de13214/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/210d895f-d690-49c1-9517-37722db260eb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48aeedb7b3a21aca7f4c7b776c4b4fa35de13214/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/17848489-613e-4132-b96d-41763ecb2336) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/48aeedb7b3a21aca7f4c7b776c4b4fa35de13214/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-task-modules.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/264d997b-7068-45cc-b6e2-fb96c1589afd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6e88e8c788a2b17963f840a1647b69db70cb262/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/04f295c6-77b5-4334-883f-73d0cc590147) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6e88e8c788a2b17963f840a1647b69db70cb262/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dad40f36-3cff-485f-b0f4-c2061e253957) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f6e88e8c788a2b17963f840a1647b69db70cb262/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-task-modules.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8f9b71b7-534e-4dfb-9d5f-ae85b36e5dba) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4277dda29535c689fb8c10fd563dd5a9d049ae8d/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0ebd8041-fa5c-4421-9a8c-9c1cc860a6b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4277dda29535c689fb8c10fd563dd5a9d049ae8d/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Finvoking-task-modules.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f942abf3-d0e9-46fe-921f-ab8c520e6827) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4277dda29535c689fb8c10fd563dd5a9d049ae8d/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/09baf379-6e4b-4903-b1e7-96fb5afa1be0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4277dda29535c689fb8c10fd563dd5a9d049ae8d/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-task-modules.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ca354c1c-0c68-4c78-85b4-d9e90a97dd85) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94020866a57615cf463c31536468b487d29eb057/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/23f89361-c74f-4855-bb00-ab0e9a9e03ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94020866a57615cf463c31536468b487d29eb057/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Finvoking-task-modules.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5b89b7b0-12ab-4129-b8a0-8bff43319db7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94020866a57615cf463c31536468b487d29eb057/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/869d1bb2-19f0-4a1f-88fb-3c28b7974200) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/94020866a57615cf463c31536468b487d29eb057/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-task-modules.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fbcb1449-8422-4eaf-8a53-e4b2cbfbf0b5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1bb5cfc4406ae371ac0a9892041aa7b144762289/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bbb6717f-5699-4803-893a-a7d6d328caa2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1bb5cfc4406ae371ac0a9892041aa7b144762289/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 87 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5bc9a3e2-6cbc-4a23-be17-cb2183f5c877) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1bb5cfc4406ae371ac0a9892041aa7b144762289/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Finvoking-task-modules.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9c4f94dd-8d08-4a96-8a45-899d67392963) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1bb5cfc4406ae371ac0a9892041aa7b144762289/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/50eb6814-3e0d-4134-9f1e-3b952001c926) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/1bb5cfc4406ae371ac0a9892041aa7b144762289/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-task-modules.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/32a30155-9a1b-4268-9cf8-af79572fee86) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0d2deb14c2ffb4eb7ef8960f2499dce0f6e8154/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6bff69f9-47d3-4ac6-b641-82fa2aaf6bcb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0d2deb14c2ffb4eb7ef8960f2499dce0f6e8154/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a45c770-5820-4d6c-aacd-0203a9ce2fda) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0d2deb14c2ffb4eb7ef8960f2499dce0f6e8154/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fd0ddf92-95b0-4166-a3ff-f5f0f7ca77ad) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0d2deb14c2ffb4eb7ef8960f2499dce0f6e8154/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 87 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f04f3ba3-0e50-45e3-a892-000bcf581c09) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0d2deb14c2ffb4eb7ef8960f2499dce0f6e8154/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Finvoking-task-modules.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07f70569-ced8-4e2f-9b23-5469b9ed79ab) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0d2deb14c2ffb4eb7ef8960f2499dce0f6e8154/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dc4f4705-2836-4ba7-b3d0-82c13c4416f0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b0d2deb14c2ffb4eb7ef8960f2499dce0f6e8154/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-task-modules.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d6ce0e59-d843-483d-b237-fafe2751be6a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f5532a7058f38fb26b0f26f9935c58af922e42d6/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/12203c0e-ed9a-4ed1-ba88-8ccfe559353d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f5532a7058f38fb26b0f26f9935c58af922e42d6/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7a9df9d6-a6e7-4fa0-971d-6c22f97aaea7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f5532a7058f38fb26b0f26f9935c58af922e42d6/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/440c47c7-1ba3-45c2-841a-714667c0276a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f5532a7058f38fb26b0f26f9935c58af922e42d6/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 87 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/592adc6c-4ee9-47cc-8c41-0e80b2868d59) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f5532a7058f38fb26b0f26f9935c58af922e42d6/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Finvoking-task-modules.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ad96233a-85b1-4417-9cde-5dcd8d4c406f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/task-modules-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f5532a7058f38fb26b0f26f9935c58af922e42d6/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Ftask-modules-tabs.md) | 93 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8774a9df-637c-4ece-b416-03b386be9b91) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f5532a7058f38fb26b0f26f9935c58af922e42d6/msteams-platform%2Ftask-modules-and-cards%2Fwhat-are-task-modules.md) | 91 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4295ff76-e47c-4d87-8c72-e3753193de00) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e30dd4048cd21fcb9040775c7f8ec8823a2f1988/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/80bf2ad2-00e2-417b-86f5-3d671d698973) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e30dd4048cd21fcb9040775c7f8ec8823a2f1988/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c6440df2-e51b-4145-8d49-e9c42c504b17) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e30dd4048cd21fcb9040775c7f8ec8823a2f1988/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d9587e7-15c6-4447-ba0c-bb4d68706c4a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e30dd4048cd21fcb9040775c7f8ec8823a2f1988/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 87 | 70 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/130fabd7-3015-4bf6-8f32-2675b5264d65) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e30dd4048cd21fcb9040775c7f8ec8823a2f1988/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Finvoking-task-modules.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8805273b-356a-4197-8040-8e2fb4e8047e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b87d4653b203fc184554d0d9a0f2098775096c/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5d0a3eac-be5f-4e47-a816-265eeaa6b83d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b87d4653b203fc184554d0d9a0f2098775096c/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0a35ae8-c2c8-406e-9c44-0336eec36c6a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b87d4653b203fc184554d0d9a0f2098775096c/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4bcb6a63-e51a-4899-80f3-7a9e6afe0d6e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b87d4653b203fc184554d0d9a0f2098775096c/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 87 | 74 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff7e7ce5-254c-496d-85f2-2a2845c14862) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e0b87d4653b203fc184554d0d9a0f2098775096c/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Finvoking-task-modules.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d6496cd-b368-4b9a-8b04-b61d6978ef52) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-npaladugu — APPROVED** [review]

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/apps-in-teams-meetings/build-apps-for-anonymous-user.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6974a527fe2fba756d089287d1d50970f66ef488/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-apps-for-anonymous-user.md) | 91 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/941a2433-4600-493c-ad39-ea7fcd31f3cb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/build-extensible-conversation-for-meeting-chat.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6974a527fe2fba756d089287d1d50970f66ef488/msteams-platform%2Fapps-in-teams-meetings%2Fbuild-extensible-conversation-for-meeting-chat.md) | 94 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c9bf6f4-1015-461f-823c-93ef470a10f2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/apps-in-teams-meetings/meeting-apps-apis.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6974a527fe2fba756d089287d1d50970f66ef488/msteams-platform%2Fapps-in-teams-meetings%2Fmeeting-apps-apis.md) | 92 | 34 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a82e1581-b8c6-46b2-8c8f-6712ea4ef642) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/overview-analytics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6974a527fe2fba756d089287d1d50970f66ef488/msteams-platform%2Fconcepts%2Fdesign%2Foverview-analytics.md) | 87 | 74 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a2dcd8a5-6f0f-4d7d-85aa-a629d051f0a5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6974a527fe2fba756d089287d1d50970f66ef488/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Finvoking-task-modules.md) | 94 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37b8a897-c6d0-4ecc-82aa-aea38823aa52) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
