### PR TITLE
[Doc Update][Message-extensions-2][2369900]

### PR DESCRIPTION
**Pull request by v-npaladugu**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/6cf341dc2ff3fff229b108f0ed18fba4ea03798b/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 93 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a597f0ed-c966-47f7-a700-3c980c565a1b) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db6ad42550a0ca79d5b4d95168fc333a5042d20c/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 93 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bd132e50-fe3f-42b0-8b42-f445ee1e856b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/db6ad42550a0ca79d5b4d95168fc333a5042d20c/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/0fcc69b3-8ded-4959-a97e-112745fbfea4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee4acdc3e9119b83a40ed3bcbe84c4f8749e9412/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 93 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec4f3218-a230-4322-86fb-d34c3d7bc697) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee4acdc3e9119b83a40ed3bcbe84c4f8749e9412/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e9e43d94-08c8-433d-989d-1b4228fb809f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ee4acdc3e9119b83a40ed3bcbe84c4f8749e9412/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c4c5ffc-062b-4632-8d57-e0d962744745) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b786db3d154ff2ecb14ce753bb5178a70ea80c41/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 93 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6c938fec-a69d-4cd3-b4c5-d5be327a1206) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b786db3d154ff2ecb14ce753bb5178a70ea80c41/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9baa24cb-b402-45a5-b7e6-8163af5ee838) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b786db3d154ff2ecb14ce753bb5178a70ea80c41/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/57f6c766-c265-48c3-ac73-bb2f305c478e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b786db3d154ff2ecb14ce753bb5178a70ea80c41/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/13b344bf-51ec-4f7f-bfd9-c9ad429eb170) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/961906660418bbfdb962aa96a3df9ca160dbd13e/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 93 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fca21464-a531-4454-b614-2ae872235428) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/961906660418bbfdb962aa96a3df9ca160dbd13e/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/24d2a485-8e38-4416-959d-3cc1374e76a0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/961906660418bbfdb962aa96a3df9ca160dbd13e/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d22633a4-277b-4ca9-baff-eab9a20c2806) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/961906660418bbfdb962aa96a3df9ca160dbd13e/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/301ffe01-9521-406b-8e80-13e59ad08a0a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/961906660418bbfdb962aa96a3df9ca160dbd13e/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7582a7fd-0925-48ce-a5c9-a1bb4e52ea7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/961906660418bbfdb962aa96a3df9ca160dbd13e/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d5549dc8-7fa4-412f-a968-537a555138da) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4364923f3a7bd182538d309073f30ad27b40309a/msteams-platform%2Fbots%2Fbot-basics.md) | 84 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6a03be93-672c-4119-875f-10a241af31f5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4364923f3a7bd182538d309073f30ad27b40309a/msteams-platform%2Fbots%2Fbot-features.md) | 87 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e2c3381c-d16f-44a4-a738-ac03211f1f22) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4364923f3a7bd182538d309073f30ad27b40309a/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 93 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9a439405-30ef-487e-90ac-8ce9ff8a31b5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4364923f3a7bd182538d309073f30ad27b40309a/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/86a0e6a9-fbad-4964-9edf-55d7c7cab8cc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4364923f3a7bd182538d309073f30ad27b40309a/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9261af6d-de59-43e6-a468-f62e27ade6f3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4364923f3a7bd182538d309073f30ad27b40309a/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bfecaf30-d418-40bb-bc32-7d1f1ee34514) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4364923f3a7bd182538d309073f30ad27b40309a/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 86 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/53bf5741-cbaf-456b-88c7-accb59232db9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4364923f3a7bd182538d309073f30ad27b40309a/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14e6d29e-9b68-46d4-9462-1d3f8456f2c6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4364923f3a7bd182538d309073f30ad27b40309a/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f03cd10c-f67b-46b2-856d-7b6c65507b23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/4364923f3a7bd182538d309073f30ad27b40309a/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7220998e-34e9-4a38-a874-6c77bb3745eb) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/bots/bot-basics.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e175bd9304b48678041c1314e490eef7ca16442/msteams-platform%2Fbots%2Fbot-basics.md) | 84 | 46 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c4960349-ca80-40f9-890f-7d8f698be48d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/bot-features.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e175bd9304b48678041c1314e490eef7ca16442/msteams-platform%2Fbots%2Fbot-features.md) | 87 | 16 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ccb4f6ab-b8d7-475f-8535-7b548d4c43a1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/bots/design/bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e175bd9304b48678041c1314e490eef7ca16442/msteams-platform%2Fbots%2Fdesign%2Fbots.md) | 93 | 19 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f0859adb-b8be-4abe-aa86-4f94be8b568e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/messaging-extensions/design/messaging-extension-design.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e175bd9304b48678041c1314e490eef7ca16442/msteams-platform%2Fmessaging-extensions%2Fdesign%2Fmessaging-extension-design.md) | 90 | 23 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fab629c2-2600-44bc-a8aa-228e5f6833a3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/build-adaptive-card-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e175bd9304b48678041c1314e490eef7ca16442/msteams-platform%2Ftabs%2Fhow-to%2Fbuild-adaptive-card-tabs.md) | 94 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b21723e7-5d6b-4f42-8777-fef8aeb38831) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/how-to/create-tab-pages/configuration-page.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e175bd9304b48678041c1314e490eef7ca16442/msteams-platform%2Ftabs%2Fhow-to%2Fcreate-tab-pages%2Fconfiguration-page.md) | 95 | 4 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e5f0358-9bea-4633-84e0-fb6a8a2ab8ec) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/tabs-link-unfurling.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e175bd9304b48678041c1314e490eef7ca16442/msteams-platform%2Ftabs%2Ftabs-link-unfurling.md) | 86 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e32b5f49-e1ea-4c9f-857b-db76aff52570) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e175bd9304b48678041c1314e490eef7ca16442/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 90 | 14 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/21b82b7f-9897-4d7e-8c96-8fd494a3726f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/cards/design-effective-cards.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e175bd9304b48678041c1314e490eef7ca16442/msteams-platform%2Ftask-modules-and-cards%2Fcards%2Fdesign-effective-cards.md) | 91 | 20 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2c2a6399-d875-4864-acec-6713fdf026c0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/task-modules-and-cards/task-modules/design-teams-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9e175bd9304b48678041c1314e490eef7ca16442/msteams-platform%2Ftask-modules-and-cards%2Ftask-modules%2Fdesign-teams-task-modules.md) | 91 | 13 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7e658cd8-18dd-4060-ae25-250d4f7556b9) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by stkong-sdk — APPROVED** [review]

**Review by v-habibaumme — APPROVED** [review]
Approved

**Pull request merged**
