### PR TITLE
[Doc Improvement][Activity feed notification][Design doc update][3038755]

### PR DESCRIPTION
**Pull request by v-vanv**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/68b30b19512ec49cd00d14b16bd0827414d85a81/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a42a0952-e174-4f08-a5da-80c13d366d3e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/34b4cea81247dfc6b8c033089f9406a0d10c2775/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/41e43171-7ebd-4b86-83f5-6a92e37610c5) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/36bf24f2413879ad487ea7346b10bcfa53db190e/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3ef80e8c-703f-443c-ad32-8344d9d2b0a4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/0171a3ecc8df31a31b8e7fd65d1136895e8a274a/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ec82e144-485f-458d-8d16-1271fa52472d) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7dc1c8ffb9ca63880e055e96df7e762681614117/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/365973b0-80c6-4cce-b4fe-594c7552a871) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/activity-feed-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/225dde7d37072603a574928eb09d11b14e479cc3/msteams-platform%2Fconcepts%2Fdesign%2Factivity-feed-notifications.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8f988dc-afa8-48aa-ab10-543664c35bf9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/225dde7d37072603a574928eb09d11b14e479cc3/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-ui-templates.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/70e9f52f-2055-4672-be50-1e7543537adc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/225dde7d37072603a574928eb09d11b14e479cc3/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8e179730-c8ef-4017-84e8-5adfa8f9edc1) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/activity-feed-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2574d0333fe2c2703bcbd043930f5992829ddb98/msteams-platform%2Fconcepts%2Fdesign%2Factivity-feed-notifications.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20ff8931-104c-45fc-b705-91cd54e53bdd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2574d0333fe2c2703bcbd043930f5992829ddb98/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-ui-templates.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3c91d845-280e-4257-b165-9cab6007d8b0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/2574d0333fe2c2703bcbd043930f5992829ddb98/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e91c860b-c875-4b4e-b98d-c8ee9d3ad502) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/activity-feed-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba87f5a94ef16d6fa4066b66182babebeb748308/msteams-platform%2Fconcepts%2Fdesign%2Factivity-feed-notifications.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c50ab8ca-83b3-4f54-9946-dce948fddcf4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba87f5a94ef16d6fa4066b66182babebeb748308/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-ui-templates.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddecfec5-1d46-42ab-acaf-6f156c64ef12) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba87f5a94ef16d6fa4066b66182babebeb748308/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a7839c08-bed4-492a-90a2-01baebe6b2c7) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/activity-feed-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba1719d6ecd5c77f3318e84cb0f4700efdbc5d7c/msteams-platform%2Fconcepts%2Fdesign%2Factivity-feed-notifications.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c77f2f3-fe97-4850-9db9-51a249aedebf) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba1719d6ecd5c77f3318e84cb0f4700efdbc5d7c/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-ui-templates.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/40da8d44-456e-4987-8aa2-5d69c68fd41b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ba1719d6ecd5c77f3318e84cb0f4700efdbc5d7c/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3d84254f-396c-423b-814d-a21d63d503f3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/design/activity-feed-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f11374169966d2cb8138f6aad4a7194697115838/msteams-platform%2Fconcepts%2Fdesign%2Factivity-feed-notifications.md) | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a409da10-b687-4e1a-9e1b-119a706671e4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/design-teams-app-ui-templates.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f11374169966d2cb8138f6aad4a7194697115838/msteams-platform%2Fconcepts%2Fdesign%2Fdesign-teams-app-ui-templates.md) | 94 | 5 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e68cd004-f63c-4fa0-b1f6-636acc3674d0) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f11374169966d2cb8138f6aad4a7194697115838/msteams-platform%2Fconcepts%2Fdesign%2Fpersonal-apps.md) | 94 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d8d36ff2-490b-4641-9d93-13cebaa39fe2) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
