### PR TITLE
[Doc Improvement][Acro Score Improvement-VSC Documents2][ADO-2438788]

### PR DESCRIPTION
**Pull request by v-psambrani**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/aee90369d113d45af52a8fa8f0b7d487f9cdee03/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/eaf7ca12-828d-4572-b74d-34774d46aaad) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e431c65c5f670e37e7c41bf8f470507326e867f4/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/289886d4-2928-4e45-8397-b11079deed19) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/e431c65c5f670e37e7c41bf8f470507326e867f4/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/919e6b04-691a-43e8-b8b6-f5026ef5421e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3edb068256ad095171cef18facaffe034deaeaa1/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/2d789d08-0a5e-4f55-b6f9-90cc54436c58) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3edb068256ad095171cef18facaffe034deaeaa1/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/01bc0ff1-b254-47a2-8cd0-39cf50515221) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3edb068256ad095171cef18facaffe034deaeaa1/msteams-platform%2Fsbs-bots-with-sso.yml) | 88 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/90b6ff9f-ff4a-482e-9b36-742c9feebdc3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/3edb068256ad095171cef18facaffe034deaeaa1/msteams-platform%2Fsbs-calling-and-meeting.yml) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3f936d1-6bec-44e3-990f-6f7f97e33d08) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a392f39bd6ce83a70733f1d7b33881662469e983/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a0e55a00-756f-4c77-9f93-adfbac91e37a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a392f39bd6ce83a70733f1d7b33881662469e983/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/924ab033-080d-4508-917f-65c1f4a23ab7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a392f39bd6ce83a70733f1d7b33881662469e983/msteams-platform%2Fsbs-bots-with-sso.yml) | 88 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/65302084-fd88-4821-85b9-ad6cb9ea84f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a392f39bd6ce83a70733f1d7b33881662469e983/msteams-platform%2Fsbs-calling-and-meeting.yml) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/83f6f90c-1bd1-4257-bf54-c78e60c501d4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/a392f39bd6ce83a70733f1d7b33881662469e983/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 83 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1281ffa0-8f92-4311-87fc-79a4df913c9f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/28df8a1de1e658a8eae0a2912dbd27cd201a9977/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5e999a11-0209-4fbb-b9a2-f2394789bb25) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/28df8a1de1e658a8eae0a2912dbd27cd201a9977/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4c587dd1-b172-42af-b47d-c2a86ae87dca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/28df8a1de1e658a8eae0a2912dbd27cd201a9977/msteams-platform%2Fsbs-bots-with-sso.yml) | 88 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16281e3f-d3c5-460c-8b39-b7ff2371ca44) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/28df8a1de1e658a8eae0a2912dbd27cd201a9977/msteams-platform%2Fsbs-calling-and-meeting.yml) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1c2e37c4-fd9e-48c7-a43a-e83fc6886571) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/28df8a1de1e658a8eae0a2912dbd27cd201a9977/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 83 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ddefaadb-1acd-4c2a-bfb8-7c569771b7f6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/28df8a1de1e658a8eae0a2912dbd27cd201a9977/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 82 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b97c4828-34ce-4e95-a13b-6645381e647e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/28df8a1de1e658a8eae0a2912dbd27cd201a9977/msteams-platform%2Fsbs-meeting-token-generator.yml) | 87 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/48de926a-6b15-4edc-aeb8-3792f751d95c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/542592aeb89fa9f8bc31e0bb2e3d4ccedd1e2532/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/85d9b82e-ce8f-4375-ba5e-643e0b935332) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/542592aeb89fa9f8bc31e0bb2e3d4ccedd1e2532/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/dd77c320-ef74-4f49-b1ab-26dcc727ecd6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/542592aeb89fa9f8bc31e0bb2e3d4ccedd1e2532/msteams-platform%2Fsbs-bots-with-sso.yml) | 88 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f4980d83-780b-4fa3-b354-4115b42718f8) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/542592aeb89fa9f8bc31e0bb2e3d4ccedd1e2532/msteams-platform%2Fsbs-calling-and-meeting.yml) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/42e08c45-70cb-492b-93e4-4f77148017ac) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/542592aeb89fa9f8bc31e0bb2e3d4ccedd1e2532/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 83 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/393dde0f-baf0-4075-bb95-86564028435d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/542592aeb89fa9f8bc31e0bb2e3d4ccedd1e2532/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 82 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/27072b78-8d21-46ca-b38d-f7aa96215f47) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/542592aeb89fa9f8bc31e0bb2e3d4ccedd1e2532/msteams-platform%2Fsbs-meeting-token-generator.yml) | 87 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3f192d2a-0e27-4124-b728-807a17791512) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/542592aeb89fa9f8bc31e0bb2e3d4ccedd1e2532/msteams-platform%2Fsbs-meetingextension-action.yml) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a1da3ccb-1599-41ec-bce4-8f232a183130) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/af8b05f99f0251c46fa4f677f322515757d9f166/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ac2e4592-5a33-424a-b2ba-05ada905d2dc) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/af8b05f99f0251c46fa4f677f322515757d9f166/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8fdcac6e-d07c-4814-902c-4a482a9954b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/af8b05f99f0251c46fa4f677f322515757d9f166/msteams-platform%2Fsbs-bots-with-sso.yml) | 88 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e5c31dff-eb6a-463f-b792-87aa6441f1d5) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/af8b05f99f0251c46fa4f677f322515757d9f166/msteams-platform%2Fsbs-calling-and-meeting.yml) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4390c2c6-2ed9-4682-93d0-81ae61552135) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/af8b05f99f0251c46fa4f677f322515757d9f166/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 83 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/20256ea3-d3dd-4ff8-9684-7916fd43cbed) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/af8b05f99f0251c46fa4f677f322515757d9f166/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 82 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/662dc2f7-aed3-441a-9aa7-1021e18b6f30) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/af8b05f99f0251c46fa4f677f322515757d9f166/msteams-platform%2Fsbs-meeting-token-generator.yml) | 87 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a86b5378-02b5-48f9-a1e3-3b005b1f35b7) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/af8b05f99f0251c46fa4f677f322515757d9f166/msteams-platform%2Fsbs-meetingextension-action.yml) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7f3e5c35-003b-43b6-ae8f-97be1735cb3a) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/af8b05f99f0251c46fa4f677f322515757d9f166/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/35ea538e-180e-408e-8670-676cd3c07b79) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba5c2a51a8e57c7eb9a223160e4bbd0278139d7b/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b0f5b0b0-d363-493b-a8a1-9a71b56b1e8e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba5c2a51a8e57c7eb9a223160e4bbd0278139d7b/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c6b1074-4e2b-4be3-8a9b-251e551809d9) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba5c2a51a8e57c7eb9a223160e4bbd0278139d7b/msteams-platform%2Fsbs-bots-with-sso.yml) | 88 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b2a4e6ff-375d-4142-98ff-ce4efaf39071) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba5c2a51a8e57c7eb9a223160e4bbd0278139d7b/msteams-platform%2Fsbs-calling-and-meeting.yml) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c477bc05-7f80-4e88-975b-f1ec3dbfdfca) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba5c2a51a8e57c7eb9a223160e4bbd0278139d7b/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 83 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/db70280e-4f8b-48bc-b46e-245f57a94c7e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba5c2a51a8e57c7eb9a223160e4bbd0278139d7b/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 82 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/1408f8db-c264-4725-846c-fb2836abb155) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba5c2a51a8e57c7eb9a223160e4bbd0278139d7b/msteams-platform%2Fsbs-meeting-token-generator.yml) | 87 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5ec8f285-e221-4831-bff6-98c29c52751b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba5c2a51a8e57c7eb9a223160e4bbd0278139d7b/msteams-platform%2Fsbs-meetingextension-action.yml) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e6d3f13c-6763-4234-90eb-2b94ed6ab598) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba5c2a51a8e57c7eb9a223160e4bbd0278139d7b/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b159ebbb-30ae-42b9-b4b1-135984e7f54c) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/ba5c2a51a8e57c7eb9a223160e4bbd0278139d7b/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/702c9077-da0f-4839-9a6e-09c8adaea99c) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/sbs-botbuilder-linkunfurling.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f377811de37aa08ea3ebc40d1661d8d84afacdc4/msteams-platform%2Fsbs-botbuilder-linkunfurling.yml) | 83 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/07dab837-944c-4606-9265-52e2fa8f5bea) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-botbuilder-taskmodule.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f377811de37aa08ea3ebc40d1661d8d84afacdc4/msteams-platform%2Fsbs-botbuilder-taskmodule.yml) | 83 | 42 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/d81970bc-4068-4424-bbd9-b80efd13543b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-bots-with-sso.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f377811de37aa08ea3ebc40d1661d8d84afacdc4/msteams-platform%2Fsbs-bots-with-sso.yml) | 88 | 22 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b4373884-ed72-4e94-ad11-08195943a318) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-calling-and-meeting.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f377811de37aa08ea3ebc40d1661d8d84afacdc4/msteams-platform%2Fsbs-calling-and-meeting.yml) | 90 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/4acfa4dc-87f8-4ab4-927e-b94fa7184d2f) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-file-handling-in-bot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f377811de37aa08ea3ebc40d1661d8d84afacdc4/msteams-platform%2Fsbs-file-handling-in-bot.yml) | 83 | 38 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/3a6e6190-a394-4448-8cbb-2ca15c5b8b82) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-content-bubble.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f377811de37aa08ea3ebc40d1661d8d84afacdc4/msteams-platform%2Fsbs-meeting-content-bubble.yml) | 82 | 33 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/7d96a1e1-d157-461c-ba53-c9a9b5613804) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meeting-token-generator.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f377811de37aa08ea3ebc40d1661d8d84afacdc4/msteams-platform%2Fsbs-meeting-token-generator.yml) | 87 | 37 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/14ad4926-dd97-4d92-a8d5-1a68ed4894fd) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetingextension-action.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f377811de37aa08ea3ebc40d1661d8d84afacdc4/msteams-platform%2Fsbs-meetingextension-action.yml) | 86 | 28 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/89d9f7cd-5923-4f73-9070-cbe504a91c23) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-meetings-sidepanel.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f377811de37aa08ea3ebc40d1661d8d84afacdc4/msteams-platform%2Fsbs-meetings-sidepanel.yml) | 85 | 29 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/a39b1149-b64a-404d-911b-8e5f7530fef2) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-messagingextension-searchcommand.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f377811de37aa08ea3ebc40d1661d8d84afacdc4/msteams-platform%2Fsbs-messagingextension-searchcommand.yml) | 84 | 31 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/37d50b5a-0978-46d7-97b6-66d038b0d04e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/sbs-outgoing-webhooks.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/f377811de37aa08ea3ebc40d1661d8d84afacdc4/msteams-platform%2Fsbs-outgoing-webhooks.yml) | 84 | 10 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/045025b0-e4e2-4f32-8e8b-b0118c742984) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
