### PR TITLE
[Doc Improvement][Share to Teams developer preview to GA]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/share-to-teams-from-personal-app-or-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2322ea66b5662c6f2535167a237c88a642cb761/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-from-personal-app-or-tab.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/134b41c8-5673-47a9-9de7-9dce8dae2d51) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/share-to-teams-from-web-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2322ea66b5662c6f2535167a237c88a642cb761/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-from-web-apps.md) | 91 | 6 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/62284194-7508-4045-a894-c8abde0ecae4) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/c2322ea66b5662c6f2535167a237c88a642cb761/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/562af06a-32cd-41a3-9a80-e1d56fb2fd40) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/share-to-teams-from-personal-app-or-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a18d95e739d76bd49f5972ecafc1ed802f8151dc/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-from-personal-app-or-tab.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/c3424e62-b46e-4038-a7e5-bdd6729c8544) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/a18d95e739d76bd49f5972ecafc1ed802f8151dc/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/bc6b90db-a584-4b70-8998-4eb3d4de507e) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/share-to-teams-from-personal-app-or-tab.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fb2cf0786589371a745e0230babc0fa5056310b6/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fshare-to-teams-from-personal-app-or-tab.md) | 93 | 3 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/beea8b9c-a243-4d94-8a89-ae93e3ec650d) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/whats-new.md](https://github.com/MicrosoftDocs/msteams-docs/blob/fb2cf0786589371a745e0230babc0fa5056310b6/msteams-platform%2Fwhats-new.md) | 91 | 35 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9e470c5e-38f7-4efc-9ebd-91f0e3193a32) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-habibaumme — APPROVED** [review]
Approved

**Review by ashishguptaiitb — COMMENTED** [review]
Existing changes in this PR are good. 

However, the feature docs need, at least, a better overview of the feature. Current one does not clearly convey the value add for the end-user and hence may not be convincing why a developer should use this functionality in their apps.

@surbhigupta12  and @v-habibaumme , please take up a review of this feature with customer-facing roles (beyond PMs) later.

**Pull request merged**
