### PR TITLE
[Doc Improvement][Feedback avenue tasks][4218199]

### PR DESCRIPTION
**Pull request by V-bvishnu5**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b4cbf134877bd08e78e5472bcc4405d0e52fde93/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/476279e0-c049-47c3-bd93-8e2b25b21959) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f18723b689e49fda0672d630d94ecfa4551754b9/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/f1965bbd-f3f1-4888-bab9-badcaf312ecb) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/f18723b689e49fda0672d630d94ecfa4551754b9/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/8b4ed661-fb73-4904-b570-86a69a50e40a) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea5da4d792229c0f4b16121efdd844bc62983f86/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/fb616c5f-a569-44da-9bc7-1a5918ff8238) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/ea5da4d792229c0f4b16121efdd844bc62983f86/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/6826d5a2-255e-4a85-8403-8d4cf0aa77b4) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by Wajeed-msft — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e81aab7f778dbf0dbd6dc4394d21e98e54c5df20/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 90 | 9 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/10d7953f-6956-4c7e-abd3-870314ad5392) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e81aab7f778dbf0dbd6dc4394d21e98e54c5df20/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/11df82a5-ec18-4267-88ee-b58ac4123a52) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e81aab7f778dbf0dbd6dc4394d21e98e54c5df20/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/16b3182f-cc50-4ed8-90dc-f58d8c89a286) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ec6b62e5d37be317f8f6ba70caf3a78f5e12f97/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 92 | 8 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/265b717b-6bd6-42d7-b363-2a92d84e643b) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ec6b62e5d37be317f8f6ba70caf3a78f5e12f97/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/e52e24cf-b14e-401a-9a27-1d89c55a0435) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/7ec6b62e5d37be317f8f6ba70caf3a78f5e12f97/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/59fbcab1-38c7-4415-8053-1af1069d6d27) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by v-kushals — APPROVED** [review]

**Review by v-deabira — DISMISSED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd5dfc8a4fca7094ee88415a7bb73e73285fcd03/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/395e0b71-e2ff-46ec-b1d8-806e7125151e) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd5dfc8a4fca7094ee88415a7bb73e73285fcd03/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/403d8195-bfbd-48b4-a350-728ef221f1e6) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/dd5dfc8a4fca7094ee88415a7bb73e73285fcd03/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/256e8257-e30c-46fc-b973-345079236d15) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb181ef4c67ef7be1272668a6690e4a48175e473/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/97d4bd03-f57a-4d94-a24f-01bb07ee9a77) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb181ef4c67ef7be1272668a6690e4a48175e473/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b990d90a-ced5-4349-8e9f-ad9fdcba9fe3) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/cb181ef4c67ef7be1272668a6690e4a48175e473/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/cdac2442-612a-4365-8a93-fc7a5ac27969) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/concepts/build-and-test/apps-package.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e9f902142c2ef992cf6d1aeca71282aff92a8f2d/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fapps-package.md) | 93 | 7 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/ff1911bd-b0dd-4bca-8fbd-cbdaee90cce1) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/concepts/build-and-test/deep-link-application.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e9f902142c2ef992cf6d1aeca71282aff92a8f2d/msteams-platform%2Fconcepts%2Fbuild-and-test%2Fdeep-link-application.md) | 93 | 17 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/b55cd74a-4b40-477a-a795-3255ffcc0f11) | [:white_check_mark:](# "Successfully processed") |
| [msteams-platform/tabs/what-are-tabs.md](https://github.com/MicrosoftDocs/msteams-docs/blob/e9f902142c2ef992cf6d1aeca71282aff92a8f2d/msteams-platform%2Ftabs%2Fwhat-are-tabs.md) | 89 | 12 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/9fdba463-a82e-4867-b6f6-5d9ae0c99c3f) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Pull request merged**
