### PR TITLE
[Doc Improvement][Update tab-sso-register-aad.md]

### PR DESCRIPTION
**Pull request by v-sdhakshina**

### CODE REVIEW

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/35107302ea8d81f9d38bd7b13c179abc112affe8/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-register-aad.md) | 87 | 65 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5c2f37c7-84e7-4419-9dee-98d70586b250) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/9d323451c24778cb3e900d416539186314a0af91/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-register-aad.md) | 90 | 57 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/335ad723-7061-4ff1-9eb2-d627f5b174f8) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/60b0ae4ba3be8132480241425d66b42ee4fca2cd/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-register-aad.md) | 91 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/87ba64bd-8a25-4445-ab35-b4856299e9dd) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Review by surbhigupta12 — APPROVED** [review]

**Comment by acrolinxatmsft1** [comment]
## Acrolinx Scorecards 
 
**We currently enforce a minimum score of 80.**
 
Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:
| Article | Score | Issues | Scorecard | Processed |
| ------- | ----- | ------ | --------- | --------- |
| [msteams-platform/tabs/how-to/authentication/tab-sso-register-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/b9d587456968c7f0e1175f0b3b3ce3c3a9d786ef/msteams-platform%2Ftabs%2Fhow-to%2Fauthentication%2Ftab-sso-register-aad.md) | 91 | 56 | [link](https://microsoft-ce-csi.acrolinx.cloud/api/v1/checking/scorecards/5208254e-e489-4ac6-81b5-377ca7e656c3) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**
 
Use the Acrolinx extension, or sidebar, in Visual Studio Code to check spelling, grammar, style, tone, clarity, and key terminology when you're creating or updating content. For more information, see [Use the Visual Studio Code extension to run Acrolinx locally](https://review.docs.microsoft.com/office-authoring-guide/acrolinx-vscode).

**Pull request merged**
