### PR TITLE
Added note related to federated users

### PR DESCRIPTION
**Pull request by Wajeed-msft**

### CODE REVIEW

**Review by laujan — APPROVED** [review]

**Comment by laujan** [comment]
Thank you, @Wajeed-msft!

**Comment by aosolis** [comment]
@laujan Is this also mentioned in user-facing docs?

**Comment by laujan** [comment]
Hi @Adrian Solis (TEAMS)<mailto:Adrian.Solis@microsoft.com>,

Do you referencing end-user documentation?

Thx,
La
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by aosolis** [comment]
@laujan Yup, I think users are likely to run into this issue, and raise support tickets ("Messaging extensions are missing from some chats"). We have already seen ICM incidents raised because of this.

**Pull request merged**
